### ISSUE TITLE
Navigation URLs aren't generated correctly when using Passenger's RackBaseURI

### ISSUE THREAD

**Issue by joevandyk** [activeadmin/activeadmin#101]
I have the Rails 3 application containing active_admin mounted as a suburi (i.e. http://domain.com/sub-uri/).

The links in ActiveAdmin below the navigation header work properly (http://domain.com/sub-uri/admin/path). 

But the links in the header navigation section don't include the suburi.  They look like http://domain.com/admin/path.

**Comment by armahillo** [comment]
Encountered this problem with AA 0.6.0 and Rails 3.2. 

This fix:
https://github.com/activeadmin/activeadmin/issues/101#issuecomment-22273869

correctly resolved the issue fo rme.

**Comment by betesh** [comment]
@armahillo 's solution worked for me.  Actually, all I needed was the 1st part--didn't need to use `SetEnv RAILS_RELATIVE_URL_ROOT=/foo`

**Comment by alfonsocora** [comment]
The only solution that worked for me with Rails 4.2 and AA from github is to manually set the menu urls like mentioned here https://github.com/activeadmin/activeadmin/issues/101#issuecomment-22273050

**Comment by pacuna** [comment]
yeah, not the best solution but also fixed the issue for me

**Comment by semen225** [comment]
my solution:

- config/environment.rb
```ruby
Rails.application.routes.default_url_options[:script_name] = ENV['RAILS_RELATIVE_URL_ROOT']
```

- app/controller/application_controller.rb
```ruby
protected
	def after_sign_in_path_for(resource)
		ENV['RAILS_RELATIVE_URL_ROOT']
	end

	def after_sign_out_path_for(resource)
		new_user_session_path
	end

	def authenticate_user!
		if user_signed_in?
			super
		else
			redirect_to new_user_session_path
		end
	end
```

app mounted in sub-uri "/record"

- nginx.conf
```
server {
        passenger_user web;
        passenger_group web;
        listen       80;
        server_name  localhost;
        client_max_body_size 20M;
        root   /home/web/ror_apps/share/static;
        passenger_enabled on;
        passenger_base_uri /record;
        rails_spawn_method smart;
        rails_env production;

        location ~ ^/(i|js|css)/ {
            expires 1d;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }
```

**Comment by betesh** [comment]
@semen225 2 suggestions:
In `authenticate_user!`, right before the redirect, add this:

    store_location_for(:user, request.fullpath) if request.get? && !request.xhr?

Also, `after_sign_out_path_for` could be more generic, so you don't have to change it if you ever add another devise model:

    send("new_#{resource_or_scope}_session_path")

**Comment by ReneB** [comment]
I hope this helps someone in the future because I've been struggling with this for a bit. Especially since things like `AdminComments` have no associated configuration in `app/admin` where I can specify the `url` for the `menu` item. Moreover, I really don't feel like hardcoding the app's path into the app itself, since that is no concern of the app - I should be able to move it to a different subdirectory without rewriting my code, I think.

**Comment by cazzerson** [comment]
@timoschilling Recent [work](https://github.com/rails/rails/pull/21743) and [documentation](http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root) seem to indicate that `relative_url_root`is no longer considered deprecated.

**Comment by victorlcampos** [comment]
+1
