### ISSUE TITLE
Paging error

### ISSUE THREAD

**Issue by maxs87** [activeadmin/activeadmin#1025]
Collection is not a paginated scope. Set collection.page(params[:page]).per(10) before calling :paginated_collection.

**Comment by Neodelf** [comment]
thanks for comment above, is true for my case
do not overwrite variable in ApplicatonController

**Comment by nayaabkhan** [comment]
@sebbean I was doing the same. Had a @categories which was set in the ApplicationControllers's before_filter. Changing the name of the variable fixed the issue.

**Comment by Stencil** [comment]
Holy shit yeah Application_Controller was the issue, I was setting labels to my projects through activeadmin so in application_controller I had this:
```
before_action :set_labels
  
private
def set_labels
  	@labels =Label.all
end
```

I changed the @labels to @categories so I get this

```
before_action :set_labels
  
private
def set_labels
  	@categories =Label.all
end

```

later I change the variable(s) used in application.html... from @labels.each to @categories.each (in my case)
```
  <%= link_to "Projects", projects_path %>
        	</li>
          <% @categories.each do |label|%>
          <li class="col-md">
            
            <%= link_to label.name, label%>
          </li>

          <%end%>
```

and make sure to restart the server (rails s)

**Comment by troystarwalt** [comment]
If you don't want to rename your variables, then you can set a skip_before_action on the model in active admin that is giving you troubles.

`skip_before_action :your_method`

**Comment by vivipoit** [comment]
True for me, too.
Reading @firedev's thing about `application_controller` pointed me in the right direction. 
My `application_controller` had a `before_action` thing that was creating and setting a variable that by coincidence had the same name as something `ActiveAdmin` does. Changing the variable name made all things run smoothly again.
Thank you!
