### ISSUE TITLE
undefined method 'admin_user_url'

### ISSUE THREAD

**Issue by Shpigford** [activeadmin/activeadmin#1133]
When trying to login to Active Admin, an exception is thrown...

```
NoMethodError in ActiveAdmin::Devise::SessionsController#create
undefined method `admin_user_url' for #<ActiveAdmin::Devise::SessionsController:0x007fa820e565d0>
```

I'm running Rails 3.2.1, Active Admin 0.4.3 and Devise 2.0.0

**Comment by somilmish** [comment]
Had the same problem, it solved itself when I restarted the server
