### ISSUE TITLE
formtastic 2.2.0 breaks active_admin

### ISSUE THREAD

**Issue by orlando** [activeadmin/activeadmin#1224]
formtastic 2.2.0 breaks active_admin and shows this error when you reach a form..

```
super: no superclass method `buttons' for #<ActiveAdmin::FormBuilder:0xxxxxxx>
```

**Comment by bonafernando** [comment]
In my case it happened because I had a polymorphic association with a lower case on the `type` field. Then, when linking, it thew this exception.
