### ISSUE TITLE
Getting scoped and filtered collection in custom collection action

### ISSUE THREAD

**Issue by dipeshba** [activeadmin/activeadmin#1266]
I am not sure how this can be done in active admin. Let say I have filtered a list of records using the search form provided in active admin. Now I want to perform some action on this filtered list of records. I have added a custom collection action, but don't know how to get the filtered list records. Can somebody help?

**Comment by vyadav12** [comment]
Any solution for this ?

**Comment by Fivell** [comment]
related to #2375
