### ISSUE TITLE
Loading show panels asynchronously 

### ISSUE THREAD

**Issue by chrisval** [activeadmin/activeadmin#1290]
Hi,

Could it be possible to load certain panels asynchronously ? Something like:
  div render :partial 'my_partial', :asynchronous => true

The asynchronous option could generate a button that would load the panel when clicked.

For some very loaded Show views it may be useful, isn't it?

**Comment by holyketzer** [comment]
Hi @chrisval, now you can do it with https://github.com/holyketzer/activeadmin-async_panel
