### ISSUE TITLE
Arbre prevents us from using form on show pages

### ISSUE THREAD

**Issue by chollier** [activeadmin/activeadmin#132]
I'm trying to display a form on my show page, i tried with semantic_form_for or just form_for but i can't get to know how to stop getting this kind of errors : 

`undefined method `model_name' for Symbol:Class`

well I have a Session model which has many Notes (marks actually in english), i would like to be able to set my Notes when i'm on /admin/sessions/2 for example. Btw Notes are created on an after_save filter in my Session.rb model :

```
  after_save :check_note

  def check_note
    self.clients.each do |c|
      if !Note.find_by_client_id_and_session_id(c.id, self.id)
        Note.create({:client_id => c.id, :session_id => self.id, :type => self.session_type})
      end
    end
  end
```

I'm not sure if it's a real bug but i'd love to find a workaround concerning this issue

**Comment by black-snow** [comment]
Is it fixed? Can't use `form.inputs` inside a `column`.

```ruby
ActiveAdmin.register_page 'Dashboard' do
    ...
    columns do
      column do
        panel 'XYZ' do
          form do |f|
            f.inputs 'xyz' do
              ...
```

> undefined method `inputs' for
:Arbre::HTML::Form

**Comment by Fivell** [comment]
@black-snow , not form but semantic_form_for(your-object)

**Comment by black-snow** [comment]
@Fivell thanks for your reply. What's `semantic_form_for`? Can you give a link or explain?

**Comment by Fivell** [comment]
@black-snow , [link with form examples](https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md)
