### ISSUE TITLE
Nested Resource - undefined method `find' for nil:NilClass

### ISSUE THREAD

**Issue by vitali-raikov** [activeadmin/activeadmin#1334]
Hey guys, i recently encountered a problem trying to do a nested resource with activeadmin. I hope you can help me.

Say i got 2 controllers.

advertiser_campaign and advertiser_ad.

I need advertiser_ad to be a child of advertiser_campaign but as i am fairly new to activeadmin (and ruby itself) i am having some problems. I am trying to do a nested resource using ActiveAdmin.

I followed advices in this issue: https://github.com/gregbell/active_admin/issues/78 trying to do nested resource
Code below indeed registers required routes

``` ruby
ActiveAdmin.register Advertiser::Ad do
  belongs_to :advertiser_campaign
end
```

BUT when i try to access /admin/advertiser_campaigns/1/advertiser_ads I get error

``` ruby
NoMethodError in Admin::AdvertiserAdsController#index
undefined method `find' for nil:NilClass
```

Which probably means that routes work quite well and problem is somewhere in controller. I tried to overwrite ActiveAdmin controller by doing something like this

``` ruby
controller do
  def index
    index! do |format|
      @advertiser_ads = Advertiser::Ad.all
      format.html
    end
  end
end
```

But there are absolutely no effect. Although i see that controller attempts to execute my customly overwritten controller but encounters same error.

In my advertiser_campaign model i have

``` ruby
has_many :advertiser_ads, :class_name => 'Advertiser::Ad'
```

and in my advertiser_ad model

``` ruby
belongs_to :advertiser_campaign, :class_name => 'Advertiser::Campaign'
```

Any help regarding this issue will be highly appreciated. Thank you in advance.

**Comment by AlexVentura** [comment]
I have the such a similar issue with AA:
```
ActiveAdmin.register User, namespace: :manager do
  menu parent: 'Users', label: 'Accounts'

  belongs_to :organization, optional: true
  scope :all, default: true
  scope 'Providers', :physicians
  scope 'Members', :patients

  controller do
    def scoped_collection
      if params[:id].to_i == current_user.id
        User.find(params[:id])
      else
        User.physicians.or(User.patients)
      end
    end
  end
end
```

And it gives me this error:
```
undefined method `find' for #<User:0x007fe040be3e80>
```

To fix it I changed the `find` method with `User.where(id: params[:id])`.

Any explanation why I'm getting this?

**Comment by jramiresbrito** [comment]
Hi guys, 10 years later and this issue seems to still.

Is there any solution to that?

Just for context:

I have a relationship between two models under the following namespaces:

```ruby
Sources -> CashReconciliation::Source

and

GeneralLedgerConfiguration -> GeneralLedgerReconciliation::GeneralLedgerConfiguration
```

The relationships are like that:

```ruby
belongs_to :payment_source, foreign_key: :payment_source_id, class_name: '::CashReconciliation::Source'

has_many :general_ledger_configurations, foreign_key: :payment_source_id, class_name: 'GeneralLedgerReconciliation::GeneralLedgerConfiguration'
```

my admin file is this:

```ruby
# frozen_string_literal: true

ActiveAdmin.register ::GeneralLedgerReconciliation::GeneralLedgerConfiguration, as: 'GeneralLedgerConfiguration' do
  belongs_to :source

  permit_params :source_id,
                :category,
                :group_name,
                :payment_type

  index do
    selectable_column
    id_column
    column :category
    column :group_name
    column :payment_type
    actions
  end

  show do
    attributes_table do
      row :category
      row :group_name
      row :payment_type
    end
  end

  form do |f|
    f.inputs 'GeneralLedgerConfiguration' do
      f.input :category
      f.input :group_name
      f.input :payment_type, collection: ::CashReconciliation::Payment.distinct(:payment_type).pluck(:payment_type)
    end
    f.actions
  end
end
```

and the Sources got the button to the new page: 

```ruby
action_item :add_general_ledger_configuration, only: :show do
      link_to 'Create General Ledger Configuration', new_admin_source_general_ledger_configuration_path(resource)
end
```

The button is rendered without problems
![image](https://user-images.githubusercontent.com/47673606/205718394-07129b5a-6eb0-43c5-adec-36d505c01be3.png)

But accessing the button route raises:

![image](https://user-images.githubusercontent.com/47673606/205718604-9bd543ee-8412-4e46-89ed-af85c2d15cf5.png)

Any hint is appreciated 🙏🏽
