### ISSUE TITLE
URL Paramater Congestion

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#1375]
Active Admin URL paramaters are far too noisy by default. In my app, one resource has a specific scope as the default. So, when I select a different scope (including the all-inclusive one), I get this:

```
/users?order=id_desc&page=1&scope=all
```

when it could simply set the scope and be done with it, only setting the page when you're past the first one

What's more, I get far too many URL parameters if I do any filtering through the sidebar. Simply searching for an email address generates this query:

```
/users?utf8=%E2%9C%93&q%5Bregion_id_eq%5D=&q%5Brole_eq%5D=&q%5Bemail_contains%5D=wee%40gmail.com&commit=Filter&order=id_desc&scope=
```

Even worse is all the special characters. Why not have this instead?

```
/users?email_contains=wee%40gmail.com&commit=Filter
```

While we're at it, why not replace the %40 with the intended @ symbol? Is it an Internet Explorer compatibility thing? Because it appears that modern web browsers will do percent encoding in the background.

One more thing... what's with all of the %5B and %5D characters in the above query? Those are brackets enclosing each value, and man are they ugly. I can't think of any reason for them to be there.

**Comment by gkop** [comment]
Thanks for the discussion Manu and Sean :+1: The encoded characters are really annoying - could we avoid them when JS is enabled in the browser by doing a window.location redirect instead of a GET form?
