### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by moonglum** [activeadmin/activeadmin#1515]
# Visualization

There have been tickets (#1064 and #1066) asking for visualization. I think this is very useful for a lot of people. I just finished building statistics for the dashboard of our [open source rails app](https://github.com/nerdhub/hcking) using ActiveAdmin. I would love to build that into AA. I want to introduce you to my solution. I have built it with a pie chart, because that's what I needed. But I would add other visualizations, too ;)
## The Data

The data I get from my model is a distribution (of tags) in the following form:

``` ruby
[["tag_1", 32], ["tag_2", 21], ["tag_3", 2]]
```

The array is in the form of `[label, amount]` and is sorted by the amount, descending.
## The Markup

I currently generate the markup in the following way:

``` ruby
panel "Tags" do
    stats = Tagging.distribution

    div "class" => "pie-chart",
        "data-numbers" => stats.map { |stat| stat[1] }.join(","),
        "data-labels"  => stats.map { |stat| stat[0] }.join(","),
        "data-size"    => "400"
  end
end
```
## The JavaScript

The JavaScript is based upon jQuery, Raphael and g.Raphael. You can find it [here](https://github.com/nerdhub/hcking/blob/4d9ba5a7ed77fc535e5bdfd8f95dfb1355406089/app/assets/javascripts/charts.coffee). As you can see in the markup above, it is unobtrusive and just searches for all elements with the "pie-chart" class. It is written in CoffeeScript, but I would of course use JavaScript in order to not unnecessarily increase dependencies. g.Raphael is a Toolkit for creating SVG graphs. The graphs feature mouse-overs: If you hover over one segment, the size will be increased and the corresponding legend will be highlighted.
jQuery is already a dependency. Therefore this would only add Raphael and G.Raphael. G.Raphael is distributed among multiple files for the different graph types. 

Here are the file sizes (uncompressed):
- raphael is 221kb
- g.raphael is 28kb
- g.pie is 9kb
## Demonstrating it in a video

I've uploaded a [video](http://www.youtube.com/watch?v=ivRYU7LJr9M) of the described functionality. If you don't want to see a video, here's a screenshot:

![Pie Demo](https://dl.dropbox.com/u/2088244/pie-demo.png)
## My Idea

I would add the JavaScripts (raphael, g.raphael, g.pie and the translated coffeescript) to the vendor (?) javascript. I would simplify the markup as shown above by introducing the following construct for the DSL (equivalent to the code above):

``` ruby
panel "Tags" do
    pie_chart for: Tagging.distribution, size: 400
end
```

or:

``` ruby
panel "Tags" do
    chart for: Tagging.distribution, size: 400, type: pie
end
```

g.raphael additionally provides the following graph types that could also be provided:
- Bar Charts
- Line Charts
- Dot Charts

I haven't looked into how to add elements to the DSL, but I think it won't be too much work ;)

**Comment by sherbo** [comment]
Any update on this?
