### ISSUE TITLE
Formtastic :size not working

### ISSUE THREAD

**Issue by shalvika** [activeadmin/activeadmin#1540]
I want to modify the length/size of the input fields. Using the convention
f.input :nam , :input_html => { :size =>10}
does not modify the size. 
I have tried both options of using this format in the resource controller as well as in an page.html.erb file using
<%= semantic_form_for @post do |f| %>
  <%= f.inputs do %>
    <%= f.input :name,      :input_html => { :size => 10 } %>
 <% end %>
  <%= f.actions %>
<% end %>
I also tried adding the :maxlength but, still not change. When I view the html source code generated on the browser it shows the size and maxlength parameters given 

<input id="booking_name maxlength="10" name="booking[name]" size="10" type="text" />

I am using activeadmin 0.4.4. My gem list for formtastic shows 2.1.1 and 1.2.4
Browsers - FireFox, Chrome

**Comment by markaschneider** [comment]
@jpmckinney's solution worked for me, but I had to add " !important"...
` width: auto !important;`
