### ISSUE TITLE
LoadError: cannot load such file -- coffee_script 

### ISSUE THREAD

**Issue by Paxa** [activeadmin/activeadmin#1544]
Use Rails 3.2.6 and latest ActiveAdmin from git

```
Started GET "/assets/active_admin.js" for 127.0.0.1 at 2012-07-22 14:01:02 +0800
Served asset /active_admin.css - 304 Not Modified (38ms)
Error compiling asset active_admin.js:
LoadError: cannot load such file -- coffee_script
  (in /Users/pavel/.rvm/gems/ruby-1.9.3-p194/bundler/gems/active_admin-5c4e75a6d36b/app/assets/javascripts/active_admin/lib/namespace.js.coffee)
Served asset /active_admin.js - 500 Internal Server Error
```

Should coffeescript be in gem dependences?

**Comment by fabioanselmo** [comment]
FYI if you're having this issue, it may be the cache. Try this: `rake tmp:cache:clear` and restart your server.

**Comment by zander312** [comment]
@fabioanselmo this fixed my issue. Could you explain why this is necessary?

**Comment by andrecgro** [comment]
@fabioanselmo Not worked for me

**Comment by Matkezi** [comment]
try adding "gem 'coffee-rails', '~> 4.1.0'" to the GemFile

**Comment by assassinsurvivor** [comment]
just remove coffee script its useless

**Comment by ephekt** [comment]
Since this is the top hit, adding this in for others. The cache clearing did not work. But I did find I had created a scaffold prior to disabling coffee-script from the Gemfile so if you did that, go find .coffee's in your js assets folder and remove them. Things are working again.

**Comment by pachun** [comment]
@ephekt 3 hours ago, huh? How fortunate for me. Thank you!

**Comment by bobv** [comment]
Assassinsurvivor is right... just remove it and it's corresponding scripts on your erb files.

**Comment by jamesst20** [comment]
I had removed CoffeeScript Gem + all .coffee and associated files.

What worked for me is "rake tmp:cache:clear".

**Comment by leoxmessi** [comment]
Please, I want to download game Tom & Jerry: War of the Whiskers Ps2
+Rap

**Comment by wakgari** [comment]
just actvate the coffee_script 
it worked for me
