### ISSUE TITLE
undefined local variable or method `collection_before_scope'

### ISSUE THREAD

**Issue by JohnMerlino1** [activeadmin/activeadmin#1690]
I updated ActiveAdmin gem, then tried to load an index page 

```
respond_to do |format|
  format.html {
    render "active_admin/resource/index"
  }
end
```

and get this error:

ActionView::Template::Error (undefined local variable or method `collection_before_scope' for #ActiveAdmin::Views::Scopes:0x007fd774331d98):

**Comment by aximuseng** [comment]
Can any shed light on how to track this down?  I have the same issue - it's just a single Resource that this fails on.  It's one of my odd ball ones so it will be hard to find.
