### ISSUE TITLE
Active Admin doesn't handle already-created Admin class

### ISSUE THREAD

**Issue by jrex** [activeadmin/activeadmin#1691]
RoR 3.2.8
Devise 2.1.2

I currently have User and Admin classes through Devise.  I wanted to add in active_admin and tie it into the Admin class, however active_admin's installer seems to be incapable of handling this case without throwing an error, even when using --skip-users.

within routes.rb:
  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

Both work just fine through Devise already.

Running "rails g active_admin:install" with and without "--skip-users" results in this:

/.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.2/lib/devise/rails/routes.rb:443:in `raise_no_devise_method_error!': Admin does not respond to 'devise' method. This usually means you haven't loaded your ORM file or it's being loaded too late. To fix it, be sure to require 'devise/orm/YOUR_ORM' inside 'config/initializers/devise.rb' or before your application definition in 'config/application.rb' (RuntimeError)
    from /.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.2/lib/devise/rails/routes.rb:211:in`block in devise_for'
    from /.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.2/lib/devise/rails/routes.rb:207:in `each'
    from /.rvm/gems/ruby-1.9.3-p194/gems/devise-2.1.2/lib/devise/rails/routes.rb:207:in`devise_for'
        from /config/routes.rb:39:in `block in <top (required)>'
    from /.rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:282:in`instance_exec'
    from /.rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:282:in `eval_block'
    from /.rvm/gems/ruby-1.9.3-p194/gems/actionpack-3.2.8/lib/action_dispatch/routing/route_set.rb:260:in`draw'
    from /config/routes.rb:1:in `<top (required)>'

It seems to be directly related to having the devise_for :admins line in the routes.  Unfortunately, there was a bug on this type of thing already (724) where the solution was to remove the line from the routes file to keep active_admin happy. Unfortunately, this is not a viable option in my situation so it would be good to fix this situation without that.

Thanks

**Comment by thisismydesign** [comment]
It's inconvenient to change the whole URL structure. Is there an actual fix for this?
