### ISSUE TITLE
Cannot access resources in `show` DSL with same name as HTML tags

### ISSUE THREAD

**Issue by timriley** [activeadmin/activeadmin#171]
When you have a resource with a name that is the same as an HTML tag, like `Article`, then you will not be able to access the resource instance.

For example:

```
ActiveAdmin.register Article do
  show :title => :title do
    attributes_table do
      row :title
      row :author
      row :body do
        md(article.body)
      end
    end
  end  
end
```

When I'm trying to pass `article.body` to my `md` helper method above, the "article" variable is actually an instance of `Arbre::HTML::Article`, instead of my ActiveRecord subclass.

To work around this, I'm currently doing the following:

```
ActiveAdmin.register Article do
  show :title => :title do
    _article = @_assigns['article']

    attributes_table do
      row :title
      row :author
      row :body do
        md(_article.body)
      end
    end
  end  
end
```

But it would probably be good to have some way of handling this more nicely.

**Comment by rendekarf** [comment]
Wow! Had the exact same issue (model named Area) in 2022, checked docs and google'd it with no luck, until I found this issue thread. Cheers @seanlinsley
