### ISSUE TITLE
Custom footer content 

### ISSUE THREAD

**Issue by izhiliang** [activeadmin/activeadmin#1714]
For remove the footer content that it is "Powered by Active Admin 5.0 "  to some apps, have to custom it.
Example in active_admin.rb:
ActiveAdmin.setup do |config|
   #...
   config.footer_content = "" # The footer content is empty, remove the "Powered by ... "
  #...
end

**Comment by FriscoTony** [comment]
This is an old topic, but still shows up in search results. A quick update to note that if you want to customize the footer in ActiveAdmin as described in many locations, you'll now need to provide a namespace parameter to the build method:

```ruby
class MyFooter < ActiveAdmin::Component
  def build(namespace)
    super id: "footer"
    para "Copyright #{Date.today.year} Monkeys Incorporated"
  end
end

ActiveAdmin.setup do |config|  
  config.view_factory.footer = MyFooter
end
```
And also note that, because this code is in an initializer (app/config/initializers/active_admin.rb) you'll need to restart your rails server to pick up any changes.

**Comment by buren** [comment]
At least since v1.4 this is how you add a custom footer:

```ruby
ActiveAdmin.setup do |config|  
  config.footer = 'My custom footer'
end
```

**Comment by buren** [comment]
@martinstreicher `config.footer` accepts a string or a proc, see [ib/active_admin/namespace_settings.rb#L21](https://github.com/activeadmin/activeadmin/blob/9a33a081c99d9aa19045d46155ffe5f51ea76710/lib/active_admin/namespace_settings.rb#L21).

```ruby
ActiveAdmin.setup do |config|  
  config.footer = -> { YourFooter.render }
end
```

**Comment by martinstreicher** [comment]
Thank you!

**Comment by martinstreicher** [comment]
@buren May I ask: What should `YourFooter` inherit from? An Arbre component?

**Comment by martinstreicher** [comment]
I tried many permutations to set `config.footer` to a proc. None of my attempts worked. I am using the arctic admin theme -- I am wonder if it is messing with my final page result.

**Comment by martinstreicher** [comment]
I got it to work in another project without issue. I am still curious what `YourFooter` should inherit from. `ActiveAdmin::Component`? 

> 
> ```ruby
> ActiveAdmin.setup do |config|  
>   config.footer = -> { YourFooter.render }
> end
> ```

**Comment by martinstreicher** [comment]
I wound up making a class derived from the controller

```
# frozen_string_literal: true

module Utilities
  class Footer < ::ActionController::Base
  end
end
```

I can then call `Utilities::Footer.render(template: ...)`

**Comment by buren** [comment]
@martinstreicher to be clear the call to `render` was just an example – as long as the method returns a string you're all good.

```ruby
ActiveAdmin.setup do |config|  
  config.footer = ->(footer) { YourFooter.method_that_returns_string }
end
```

I've updated my earlier https://github.com/activeadmin/activeadmin/issues/1714#issuecomment-445294136 to be clearer about that.

Here is a custom footer that I'm running in production:

- [active_admin_footer.rb](https://github.com/justarrived/just_match_api/blob/master/lib/admin/active_admin_footer.rb) (only contains a method that returns a string)
- Then [config/initializers/active_admin.rb](https://github.com/justarrived/just_match_api/blob/master/config/initializers/active_admin.rb#L317)
  ```ruby
  require 'admin/active_admin_footer'
  ActiveAdmin.setup do |config|
    # ...
    config.footer = ->(_) { Admin::ActiveAdminFooter.to_s }
  end
  ```

**Comment by martinstreicher** [comment]
Thank you. I dug through the code and came to the same conclusion. 

I made this... 

```
module Utilities
  class Footer < ::ActionController::Base
  end
end
```

which lets me do things like this... 

```
config.footer  = ->(_) { Utilities::Footer.render(template: 'common/_footer') }
```
