### ISSUE TITLE
How to send email in activeadmin when adding new comment

### ISSUE THREAD

**Issue by amal007** [activeadmin/activeadmin#1727]
I need to send an email whenever the admin add a comment from user show page. I am using active admin 0.4.3.

How can I get this event and send email. When I post a comment, In my console I can see the following actions performed

``` ruby

Started POST "/admin/comments"
Redirected to http://localhost:3000/admin/comments/182
Started GET "/admin/comments/182"
Started GET "/admin/accounts/227"

```

In my users.rb I have

``` ruby
ActiveAdmin.register User do

  controller do
    def create
      create! do |format|
        format.html { redirect_to '/admin/drivers' }
      end
    end

    def update
      update! do |format|
        format.html { redirect_to '/admin/drivers' }
      end
    end
  end

end 

```

Here I can get the user create and update actions.
But how can I get the comments create action, so I can configure email. 

Please help

**Comment by onetwopunch** [comment]
Is there any way to do this in 1.0.0-pre? I tried @amal007 's method of overriding `ActiveAdmin::Comment` and @fred 's method of adding a controller block in `app/admin/comment.rb`, though I had to update like so: 

``` ruby
ActiveAdmin.register ActiveAdmin::Comment do
  permit_params :comment
  controller do
    def create
      puts 'THIS GOT CALLED' #never saw this but comment was still created.
      @comment = Comment.new(params[:comment])

      respond_to do |format|
        if @comment.save
          Mailer.send_email
          redirect_to @comment
        end
      end
    end
  end

end
```

In both cases I've added `puts` statements before the mail action which verifies they are never called.

**Comment by hcarreras** [comment]
I find a bit lame that you cannot override easily the CommentsController.
@amal007 the problem with your solution is that it seems that you are modifying the controller because you are writing it inside application_controller.rb but anyways you are modifying the model, so, placing it in there just hides that fact.

My workaround was to redefine a route for my CommentsController:

```
  namespace :admin do
    resources :comments, controller: "overridden_comments"
  end

  ActiveAdmin.routes(self)
```

Then, I could write my controller in admin/overriden_comments_controller.rb

```
module Admin
  class OverriddenCommentsController < ApplicationController

    def create
      ...
    end
  end
end

```

I hope this helps someone

**Comment by Fivell** [comment]
@hcarreras , take a look https://github.com/activeadmin/activeadmin/issues/2493#issuecomment-24892236

**Comment by hcarreras** [comment]
@Fivell much better. Thanks for this! I've completely missed it!
