### ISSUE TITLE
Error flash message not shown

### ISSUE THREAD

**Issue by gcerquant** [activeadmin/activeadmin#1739]
In an ActiveAdmin controller, the `:error` flash message is not visible.

Doing this, you get the flash message shown:

```
redirect_to admin_phone_path(@phone), notice: 'A nice message - this one is visible.' 
```

but when trying to show an error, nothing is shown.

```
redirect_to admin_phone_path(@phone), error: 'A less nice error message - this one is NOT visible.'
```

Same behavior is seen on default CRUD actions of the controllers created by ActiveAdmin.  
This means you won't know your operation didn't work when you tried to update an object and the validation failed and prevented the save.

**Comment by adamthedeveloper** [comment]
What's the right way to use flashes on render (not redirect)? I'm getting inconsistent behavior. It shows the alert the first time, but upon forcing a refresh, it doesn't ever show up again even if I hard code it to do so.

```ruby
form do |f|
    #.......some code here

    alert_msg = "ALERT!! I'M BEING FORCED TO APPEAR BUT I DO NOT"
    flash.now[:alert] = alert_msg if alert_msg.present?
    render 'form', { locals: { product: :product } }
end
```

**Comment by Kutala-Abhiram** [comment]
If i want to display the multiple errors, how can i do
