### ISSUE TITLE
Solution for filtering models having polymorphic belongs_to associations

### ISSUE THREAD

**Issue by vjt** [activeadmin/activeadmin#1743]
Hi,

in order to have select-based index filters on models having a polymorphic `belongs_to`, I've hacked away the following new `PolymorphicSelect` input, leveraging [MetaSearch multi-level associations syntax](https://github.com/ernie/meta_search#multi-level-associations).

Given the model:

``` ruby
class Foo
  belongs_to :entity, :polymorphic => true
end
```

This input in `app/admin/active_admin/inputs/filter_polymorphic_select_input.rb`:

``` ruby
module ActiveAdmin::Inputs
  class FilterPolymorphicSelectInput < FilterSelectInput
    def initialize(*args)
      name, options = args.slice(4, 2)

      @_poly_type  = name
      @_poly_assoc = options[:on] or raise(":polymorphic_select needs the polymorphic association name in the :on option")

      super
    end

    # MetaSearch syntax for polymorphic associations
    def input_name
      "#{@_poly_assoc}_#{@_poly_type}_type_id_eq"
    end

  end
end
```

Referenced in a `register` block:

``` ruby
ActiveAdmin.register Foo do
  filter :bar, :as => :polymorphic_select, :on => :entity, :collection => proc { Bar.all }
  filter :baz, :as => :polymorphic_select, :on => :entity, :collection => proc { Baz.all }
end
```

Will yield two selects in the filters sidebar, behaving as you would expect, making MetaSearch generate `where entity_type = "bar" and entity_id = 42`.

There's still room for improvement, e.g. by automagically loading the `:collection` or automagically invoking the `:polymorphic_select` (with a better name) if the `:on` option is present and the reflection says it is a polymorphic association.

What do you think?

**Comment by wkoffel** [comment]
Is it safe to assume this solution is dead since Rails 4 and the Ransack cutover?  Very curious if anyone has done something similar there.  I'm trying to avoid refactoring all my admin models.  But the inability to search through nested polymorphic associations in any reasonable way has me stumped.

**Comment by seanlinsley** [comment]
@wkoffel as you noted on https://github.com/activerecord-hackery/ransack/issues/152, https://github.com/activerecord-hackery/ransack/wiki/Polymorphic-searches seems to work.

**Comment by varyonic** [comment]
Can be closed?

**Comment by vjt** [comment]
I haven't followed closely AA development lately, but yes as far as I understood this is now supported through Ransack so yes it can be closed from my point of view.

Cheers and thanks!

**Comment by holyketzer** [comment]
Also it you need filter by only one type from all polymorphs you can use it:

```
filter :entity_of_Bar_type_id, as: :select, collection: -> { Bar.all }

# more general
filter :<relation_name>_of_<ModelName>_type_id, as: :select, collection: -> { <ModelName>.all }
```

**Comment by Bhalani** [comment]
@holyketzer 
I'm using `activeadmin (1.4.3)`.
And I have post model, 
```
class Post
  belongs_to :user
end
```
and I want to filter post by user name.

How I'll add filter for that?

**Comment by holyketzer** [comment]
@Bhalani  

```
ActiveAdmin.register Post do
  # ...
  filter :user, as: :ajax_select, collection: [], data: {
    url: '/admin/users/filter',
    search_fields: [:name, :phone], # etc, here should be your User model fields
  }
end

ActiveAdmin.register User do
  include ActiveAdmin::AjaxFilter
  # ... 
end
```
