### ISSUE TITLE
Filter with default value

### ISSUE THREAD

**Issue by bitboxer** [activeadmin/activeadmin#1751]
I want to add a default value for a filter on a certain criteria of a model. Sadly I can't figure out a way on how to set the default value for the filters. Is this not possible right now?

**Comment by chrisseldo** [comment]
@seanlinsley this solution hobbles the export function -- allowing it only to export the default-ly filtered items.

**Comment by seanlinsley** [comment]
@chrisseldo this ticket is almost three years old. Could you elaborate? Does @macfanatic's option not work?

**Comment by chrisseldo** [comment]
Yep -- @macfanatic's option doesn't work. 

Your solution: 
`
before_filter only: :index do
  params[:q] = {country_eq: 'US'} if params[:commit].blank?
end
`
only exports what the 'default filter' is. 

For example, your solution would only export countries that are of the name 'US' -- despite whether or not you've filtered for all countries.

**Comment by seanlinsley** [comment]
Yeah my solution is definitely wrong :smile:

**Comment by chrisseldo** [comment]
Hi @seanlinsley, any insight on where I can look to fix this function? Would it be within the [CSV Builder](https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/spec/unit/csv_builder_spec.rb) file? 

Thanks!

Chris

**Comment by wongwf82** [comment]
This works. But do remember to follow an example of the filter params when applied. Took some time to figure out mine was missing the `..contains`:

> 
  controller do

    before_filter only: :index do
      if params['commit'].blank?
        extra_params = {"q" => {"code_contains" => "US"}}

        # make sure data is filtered and filters show correctly
        params.merge! extra_params

        # make sure downloads and scopes use the default filter
        request.query_parameters.merge! extra_params
      end
    end

**Comment by chrisseldo** [comment]
This works -- appreciate the help @wongwf82

**Comment by javierjulio** [comment]
Earlier solution does work for setting a default filter on load. We welcome a PR though!

**Comment by ukolovda** [comment]
Thank you!
`before_filter` should be changed to `before_action` on Rails 5 and above.
