### ISSUE TITLE
Add jquery callbacks for has_many field added and removed

### ISSUE THREAD

**Issue by antonmi** [activeadmin/activeadmin#1767]
In ActiveAdmin::FormBuilder in method has_many you have scripts to add and remove fields:
`:onclick => "$(this).before('#{js}'.replace(/NEW_RECORD/g, new Date().getTime())); return false;"`
and
`:onclick => "$(this).closest('.has_many_fields').remove(); return false;"`

Please add triggers to these scripts, so user can add his own callbacks.
I think ryanb approach is a good example https://github.com/ryanb/nested_form#javascript-events

**Comment by giomv** [comment]
Finally which is the event name that needs to be listened to handle callbacks after a nested field is added or removed?

**Comment by waleedarshad** [comment]
+1

**Comment by seanlinsley** [comment]
The callbacks are [documented here](https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/app/assets/javascripts/active_admin/lib/has_many.js.coffee)
