### ISSUE TITLE
belongs_to and custom foreign key

### ISSUE THREAD

**Issue by andrey-skat** [activeadmin/activeadmin#1800]
I have two models

``` ruby
class Firm < ActiveRecord::Base
  has_many :supports
end
```

``` ruby
class Support < ActiveRecord::Base
  belongs_to :firm, foreign_key: "firm_number"
end
```

Now I want view all supports by firm

``` ruby
ActiveAdmin.register Support do
  belongs_to :firm
end
```

And it throws error
`no such column: supports.firm_id`

`belongs_to` in inherited_resources don't have `foreign_key` option.

How I can view all `supports` by `firm`?

**Comment by runemadsen** [comment]
I'm seeing the same problem. Simple change in `foreign_key` name, and I'm getting there `_id_eq` nomethod errors on the index page.

**Comment by kvokka** [comment]
Had the same issue today
Made quickfix for method like
```
def foo;end
```
and all works :)

**Comment by achiinto** [comment]
I believe a lot of the functionalities of Activeadmin would fail with the foreign keys and Primary key are not the usually format (something_id and id, respectively). I am suffering from similar things too.

**Comment by Fivell** [comment]
@achiinto , @kvokka, @runemadsen, can someone confirm bug exists for master branch ? 
and if yes to show backtrace

**Comment by deivid-rodriguez** [comment]
This issue is very old and we haven't received quality feedback in a long time. Please open a new issue with reproduction steps if this is still happening.
