### ISSUE TITLE
with_role is causing all create/update to fail

### ISSUE THREAD

**Issue by phuongnd08** [activeadmin/activeadmin#1802]
I want admin to be able to update certain attributes from user (which he normally should not be able to update himself), so inside model User I declare this:

```
  attr_accessible :status, as: :admin
```

And so to enable active admin to update that, I add this initializer:

```
module ActiveAdmin
  class BaseController
    with_role :admin
  end
end
```

With that setup, ActiveAdmin is now UNABLE to change or update other accessible attributes (that haven't marked with `as: :admin`).

Any thought?

**Comment by petrbela** [comment]
You can also do it the other way by passing an array of roles with `:default`, ie.

```ruby
attr_accessible :sku, as: [:admin, :default]
attr_accessible :status, as: :admin
```
