### ISSUE TITLE
Unauthorized 401 for admin/login url

### ISSUE THREAD

**Issue by krishnasrihari** [activeadmin/activeadmin#1812]
I am getting the 401 Unauthorized for admin/login url and its redirected to user sign in page, I already set skip_before_filter for authenticate_user! as below in active admin initializer

``` ruby
ActiveAdmin::BaseController.class_eval do
  skip_before_filter :authenticate_user!
end
```

And I tried to debug the authenticate_user! filter as below in application_controller

``` ruby
before_filter :hack_filter
def hack_filter
    Rails.logger.debug('before authenticate user! filter')
    authenticate_user!
    Rails.logger.debug('exit hack filter')
end
```

It seems this issue is not due to authenticate_user! filter, may be other filters, my active admin config file includes the authenticate_admin_user!

``` ruby
config.authentication_method = :authenticate_admin_user!
```

You can check this gist https://gist.github.com/4243865 for log file

**Comment by blackblood** [comment]
I'm facing the same issue and known of the solutions are working for me

**Comment by rakethostph** [comment]
I got it working by adding
`config.skip_before_action :authenticate_user!`
to the
`# config/initializers/active_admin.rb`
