### ISSUE TITLE
Editing page_title on show action

### ISSUE THREAD

**Issue by mrpta** [activeadmin/activeadmin#184]
Hi there,

Sorry if this is the wrong place to ask, but I wonder if you can change the &lt;h2 id="page_title"> contents for the `show` block? At the moment its defaulting to RecordName #ID.

Thanks very much in advance.

**Comment by ryanwjackson** [comment]
Bringing up an old issue, but if you add HTML to the show, it also appears in the browser title.  Anyway to set one for the browser and one for the page?
