### ISSUE TITLE
I18n problem with table columns on Dashboard only (works well on model page)

### ISSUE THREAD

**Issue by ByScripts** [activeadmin/activeadmin#1848]
Hi,

Supposing a **Page** model, with a **title** column.

In `admin/pages.rb` with something like this :

``` ruby
index do
  column :title

  // etc.
end
```

:white_check_mark:  The **title** column is correctly translated to french word **Titre** from `fr.activerecord.attributes.page.title`
:white_check_mark:  Each th and td for this column has a `class="title"` html attribute

Perfect.

Now in `admin/dashboard.rb` :

``` ruby
columns do
  column do
    panel "Whatever" do
      table_for Page.all do |page|
        column :title
      end
    end
  end
end
```

:x:  The "title" column is not translated

With :

``` ruby
        column t(:title), :title
```

:heavy_exclamation_mark:  The "title" column is correctly translated, **but** from `fr.title` directly (this is not DRY)
:heavy_exclamation_mark:  Each `th` and `td` for this column has a `class="titre"` html attribute (but the class attribute should not be translated)

So for the moment, I need to do this :

``` ruby
        column t(:title), :title, :class => :title
```

Not a big deal, but annoying, and I think the column behavior should be the same in both model page and dashboard.

Thank you

**Comment by zorab47** [comment]
@ByScripts I think when you specify a `table_for` manually, you must provide the `i18n` key for translations to work. In your example (note the addition of `i18n`):

```ruby
columns do
  column do
    panel "Whatever" do
      table_for Page.all, i18n: Page do |page|
        column :title
      end
    end
  end
end
```

It isn't mentioned in the documentation, but see the [TableFor](https://github.com/activeadmin/activeadmin/blob/46526fc21917978f1d8253bc84082aeeb215ea45/lib/active_admin/views/components/table_for.rb#L14) component for more information.

**Comment by deivid-rodriguez** [comment]
Mmmm, is that code to autodetect the `resource_class` (if `i18n:` is not specified) rigtht? Shouldn't it look into the class of the elements in the collection (instead of the class of the collection itself)?

**Comment by Fivell** [comment]
@ByScripts  what version of AA do you use?

**Comment by deivid-rodriguez** [comment]
This is a very old bug, maybe it's been fixed.

**Comment by Fivell** [comment]
+1 for closing by https://github.com/activeadmin/activeadmin/commit/56f8aab55fda24d22a418e1d9e367eed40c180fc
