### ISSUE TITLE
AA + gem 'turbolinks'

### ISSUE THREAD

**Issue by crmaxx** [activeadmin/activeadmin#1862]
If '//= require turbolinks' connected to 'active_admin.js' then 'datepicker' works only after a full page reload.

**Comment by seanfcarroll** [comment]
I was having a similar issue, with the styles mixing when clicking the link to go to ActiveAdmin. The styles between the main app and ActiveAdmin were mixing.
The solution was to force a full Turbolinks refresh, by adding:

```data-turbolinks='false'```

To either the link or an enclosing html element.
