### ISSUE TITLE
Can't access helpers from Active Admin partials

### ISSUE THREAD

**Issue by shedd** [activeadmin/activeadmin#188]
I've created a custom partial for the show method for my object and the partial uses a view helper that I've developed.

I tried to include it from the admin/user.rb file that drives the administration of the object like so:

require "./app/helpers/admin_helper"

However, I still get an error that the helper method is undefined.  Is there a trick to getting this to work?

Thanks!

**Comment by leafr** [comment]
I ended up passing `self` to make helpers like `div` accessible inside my helpers. Also interested in the solution.

`app/active_admin/dashboard.rb`
~~~ruby
my_helper self, 42
~~~

`app/helpers/admin/my_helper.rb`
~~~ruby
module Admin::MyHelper
  def my_helper(contex, a)
    contex.instance_exec do
      div do
        a
      end
    end
  end
end
~~~

**Comment by ldlsegovia** [comment]
**Using activeadmin 1.0.0.pre1 from git://github.com/activeadmin/activeadmin.git**
**Rails 4.2.1**
This worked for me...

`my_app/app/helpers/active_admin/resources_helper.rb`

```ruby
module ActiveAdmin
  module ResourcesHelper
    def resource_form_for(_resource, _params, _options = {}, &_block)
      url = if _resource.new_record?
              UrlBuilder.resources_path(_resource.class, _params)
            else
              UrlBuilder.resource_path(_resource.class, _params)
            end

      method = _resource.new_record? ? :post : :put

      options = { url: url, method: method, builder: ActiveAdmin::FormBuilder }
      options.merge!(_options)

      semantic_form_for([:admin, _resource], options) do |f|
        _block.call(f)
      end
    end
  end
end
```

`my_app/app/admin/balance_sheets.rb`

```ruby
ActiveAdmin.register BalanceSheet do
  form partial: 'form'
end
```

`my_app/app/views/admin/balance_sheets/_form.html.erb`

```erb
<%= resource_form_for(resource, params) do |f| %>
  <%= f.inputs "Fields" do %>
    <%= f.input :progress_status %>
    <%= f.input :crew %>
    <%= f.input :shift %>
    <%= f.input :expected_progress %>
    <%= f.input :real_progress %>
    <%= f.input :analyst, collection: User.analysts %>
    <%= f.input :activity_ids, as: :check_boxes, collection: Activity.balance_sheet_activities %>
    <%= f.input :worker_ids, as: :check_boxes, collection: Worker.all %>
  <% end %>
  <%= f.actions %>
<% end %>
```

**Comment by kvokka** [comment]
@leafr thanks, this trick still works

**Comment by ccmcbeck** [comment]
Looking at https://github.com/activeadmin/arbre/issues/38 inspired me to do this:

    module ActiveAdmin::ViewsHelper

      def arbre(&block)
        Arbre::Context.new(&block).to_s
      end

      def show_boolean(b)
        arbre do
          b ? status_tag( "yes", :ok ) : status_tag( "no" )
        end
      end
    end

**Comment by kvokka** [comment]
I found how to not use self, like @leafr advice. This exctention will save Arbre context
```
module ActiveAdmin
  module Views
    module Pages
      class Show < Base
        # Extension for pretty table views

        def foo(var)
          instance_exec do
            ...something
          end
        end
      end
    end
  end
end
```

**Comment by one-more-alex** [comment]
Thanks to @stnguyen  I found this convenient way.

Helpers in file 
app/helpers/active_admin/scheduling_helper.rb
````ruby
module ActiveAdmin
  module SchedulingHelper
...
  end
end

````

Then in app/admin/schedule.rb
````ruby
  ActiveAdmin.register_page "Schedule" do
    ...
    controller do
      helper 'active_admin/scheduling'
    ...
````

Sometimes use of byebug + pry is very handy.

**Comment by ndbroadbent** [comment]
I'm still struggling to figure out how to include a global helper method for all of my active admin pages. I want to add a `guid_column` method that I can call from my `index` block, as well as `id_column`.

I just re-opened and monkeypatched the `IndexAsTable` class in my own app, at `lib/active_admin/views/index_as_table.rb`:

```ruby
module ActiveAdmin
  module Views
    class IndexAsTable < ActiveAdmin::Component
      # Display a column for the GUID
      def guid_column
        column(:GUID) do |resource|
          if controller.action_methods.include?('show')
            link_to resource.guid, resource_path(resource), class: "resource_id_link"
          elsif controller.action_methods.include?('edit')
            link_to resource.guid, edit_resource_path(resource), class: "resource_id_link"
          else
            resource.guid
          end
        end
      end
    end
  end
end
```

And I have this at the top of `config/initializers/active_admin.rb`:

```ruby
require 'active_admin'
Dir.glob(Rails.root.join('lib/active_admin/**/*.rb')).each { |f| require f }
```

This works fine but it would be nice if there was a cleaner way to do it.

**Comment by javierjulio** [comment]
@ndbroadbent perhaps another way you could do this is to create a new class that inherits from `IndexAsTable` and use the following to implement that new column method?

**Comment by javierjulio** [comment]
@ndbroadbent perhaps another way you could do this is to create a new class that inherits from `IndexAsTable` and [use a custom index](https://github.com/activeadmin/activeadmin/blob/master/docs/3-index-pages.md#custom-index) to implement that new column method?

**Comment by thisismydesign** [comment]
People who want to use "helpers" in a controller / `ActiveAdmin.register` context: don't! Helpers are for views. Instead you can create e.g. a service:

`app/services/my_service.rb`
```ruby
class MyService
  def self.something
    ...
  end
end
```

```ruby
ActiveAdmin.register Users do
  MyService.something
end
```

**Comment by Piioo** [comment]
Other solution:

When you need the helper within views which are defined within the register block:

```
ActiveAdmin.register Foo do
  extend Helper
end
````
