### ISSUE TITLE
How to use a customized print stylesheet?

### ISSUE THREAD

**Issue by yangchenyun** [activeadmin/activeadmin#1907]
I want to override the default print css settings? 
Besides editing the gem, is there a way I could include it?

**Comment by adamthedeveloper** [comment]
For the record, this is sooo rediculous. Not an easy way to leave the print styles out? Why did we leave out the ability to turn off the canned print styles?

**Comment by debreczeni** [comment]
@adamthedeveloper Here is a quick hacky monkey-patchy way to solve it: (I am sure there is a better way than that... something like unregister? :))

```
# Monkey-patching ActiveAdmin::Application to remove forced print stylessheet
module ActiveAdmin
  class Application
    def register_default_assets
      register_stylesheet 'active_admin.css', media: 'screen'
      # register_stylesheet 'active_admin/print.css', media: 'print'
      register_javascript 'active_admin.js'
    end
  end
end
```
