### ISSUE TITLE
Overriding default resources action

### ISSUE THREAD

**Issue by hbdev** [activeadmin/activeadmin#192]
Hello All,

I want to override default resources action. Please let me know if anyone of you have better solution for that. 

Thanks in advance

**Comment by alexventuraio** [comment]
Just for anyone else interested, there is also a _failure_ method:
```ruby
def create
  create! do |success, failure|
    success.html do
      redirect_to [:project_management, :disposable_email_domains, host: manage_domain]
    end

    failure.html do
      render :new
    end
  end
end
```
