### ISSUE TITLE
Customize Download Formats per Resource

### ISSUE THREAD

**Issue by michalosm** [activeadmin/activeadmin#1920]
I would like for ActiveAdmin gem only allow to download collection as csv file . Default it is set to download as xml, csv and json. I would like only allow to download as csv.

**Comment by PaulDaviesC** [comment]
If I do `index download_links = [:xml, :pdf]` , it shows only the relevant links. But where exactly will I put the code to handle those non standard formats which AA does not support(in this case pdf)?

**Comment by mikekibz59** [comment]
how do it move the csv download link from the bottom to the sidebar and still keep its behavior? ie if the page is paginated it downloads the paginated results or if I filter out the results in the index it downloads those results . if i do this it returns all the users instead the scoped results after a filter. 
` sidebar :download_links do
    ul do
      li link_to 'download CSV', admin_users_path(:format => :csv)
      li link_to 'render JSON', admin_users_path(:format => :json)
      li link_to 'render XML', admin_users_path(:format => :xml)
    end
  end
`
