### ISSUE TITLE
Multi-Level Menu

### ISSUE THREAD

**Issue by creativecommunion** [activeadmin/activeadmin#1983]
It would be nice to have support for a mulit-level menu. In the following scenario, it would be nice to see "Test3" show up as a sub menu under "Test2" rather than create a new top level menu item.

``` ruby
ActiveAdmin.register Test1 do
end

ActiveAdmin.register Test2 do
  menu :parent => "Test1"
end

ActiveAdmin.register Test3 do
  menu :parent => "Test2"
end
```

**Comment by santostiago** [comment]
Is this implemented?

**Comment by dmitry** [comment]
@santostiago no, but you can continue to work on it at #2522

**Comment by varyonic** [comment]
See also https://github.com/zorab47/active_admin-subnav

**Comment by javierjulio** [comment]
Closing out as stale. Also a plugin is provided. Seems a bigger issue is at hand here regarding `belongs_to` which I've seen pop up elsewhere.

**Comment by ntloi95** [comment]
+1

**Comment by Fivell** [comment]
related https://github.com/activeadmin/activeadmin/pull/5994
