### ISSUE TITLE
Ordering Parent Menus

### ISSUE THREAD

**Issue by hbdev** [activeadmin/activeadmin#199]
Hello All,

I have successfully implemented ordering of sub-menu items but I am unable to order parent menus.

Please let me know if anyone of you know a better way to implement ording of parent menu items.

**Comment by rfroetscher** [comment]
For anyone still trying to solve this issue, it can be done easily by declaring the parent menus first in the initializer, as mentioned here: https://activeadmin.info/2-resource-customization.html#customizing-parent-menu-items

Simply:
```
# config/initializers/active_admin.rb
config.namespace :admin do |admin|
  admin.build_menu do |menu|
    menu.add label: 'Blog', priority: 0
  end
end

# app/admin/post.rb
ActiveAdmin.register Post do
  menu parent: 'Blog'
end
```
