### ISSUE TITLE
Namespaced models fail to create/update due to wrong parameter key

### ISSUE THREAD

**Issue by jkolyer** [activeadmin/activeadmin#2029]
My models are namespace which prevents create and update because the parameter attribute key was wrong.  I am not sure if this is a problem with inheritable_resources or active_admin, but this is the fix I used:

``` ruby
ActiveAdmin.register Namespace::Section::Model do
  controller do
    def resource_request_name
      Namespace::Section::Model.model_name.param_key
    end
  end
end
```

So what happens is the POST parameters for the resource are stored under the wrong key in the request, so when AA tries to set the resource attributes, it cannot find them within the parameters.  Overriding resource_request_name fixes the problem.

**Comment by flyfy1** [comment]
Thanks @jkolyer. I spent half day yesterday just to resolve this issue.. ur solution helped.

**Comment by flyfy1** [comment]
However, I feel this issue should be fixed.. otherwise, all the new & edit form with namespaced models would fail without the fix given by @jkolyer .
