### ISSUE TITLE
ActiveAdmin creates an extra root route

### ISSUE THREAD

**Issue by jbhannah** [activeadmin/activeadmin#2049]
Abbreviated output of `rake routes`:

```
admin_root        /admin(.:format) admin/dashboard#index
      root        /                dashboard#index
(snip)
      root        /                home#index
```

Abbreviated contents of `routes.rb`:

``` ruby
RailsAppName::Application.routes.draw do
  ActiveAdmin.routes(self)
(snip)
  root to: "home#index"
end
```

A sample error while running specs:

```
ActionController::RoutingError: uninitialized constant DashboardController
```

I don't have a controller named `DashboardController`. The only other Rails engine I'm using is Devise, which doesn't have a `DashboardController`. This is a new behavior with 0.6.0, having made no changes other than updating my Gemfile to the new version from 0.5.1.

**Comment by ngouy** [comment]
I know its an old one, but I am not sure why we just don't give the user the choice to not implementing it in it's default namespace (whish ironically is `:root`)

When you only use custom namespaces, it doesn't make sense that ActiveAdmin is creating a root path

I found a simple way to monkey patched it but still I think it should be configurable
