### ISSUE TITLE
Default edit views corrupt (delete) array type columns (e.g. Postgres Array)

### ISSUE THREAD

**Issue by danielschwartz** [activeadmin/activeadmin#2064]
In the default edit view for a model instance, if you have a column that is of the type Array (Rails 4 will have this by default, Rails 3 has it via postgres_ext for Postgres), the array in that column will get deleted on instance update. It's fine to not be able to edit the property itself, but currently editing any field and hitting update will delete the information in the column.

**Comment by DaniG2k** [comment]
I'm encountering the same issue in a project that uses ActiveAdmin 1.0.0.pre4. I've explained my issue in further details in [this SO thread](https://stackoverflow.com/questions/55060600/rails-4-activeadmin-clears-out-an-array-field-upon-update).

Has this been resolved in more recent versions of ActiveAdmin?
