### ISSUE TITLE
redirect loop when user tries to access page without permissions but doesn't have permissions for the dashboard too

### ISSUE THREAD

**Issue by joker-777** [activeadmin/activeadmin#2081]
Is it possible to specify the redirect page when the user accesses a page without permissions?

**Comment by PhilipDeFraties** [comment]
implementing `on_unauthorized_access` in the config and in the ApplicationController does absolutely nothing, it gets stuck in a redirect loop regardless.

In `active_admin.rb`:

`config.on_unauthorized_access = :access_denied`

in my authorization adapter:

```
class ActiveAdminAdapter < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    return true if user.has_role?(:admin)
    case subject
    when normalized(Page)
      return user.has_role?(:page_group_editor, :any)
    else
      return true
    end
  end
end
```

In my ApplicationController:

```
def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end
  ```
  
  I have to say that working with ActiveAdmin is the worst part of my job, hot garbage library with even worse documentation.
