### ISSUE TITLE
This webpage has a redirect loop

### ISSUE THREAD

**Issue by jwmii2** [activeadmin/activeadmin#2102]
Error:
This webpage has a redirect loop
The webpage at http://localhost:3000/admin/login has resulted in too many redirects. Clearing your cookies for this site or allowing third-party cookies may fix the problem. If not, it is possibly a server configuration issue and not a problem with your computer.
Here are some suggestions:
Reload this webpage later.
Learn more about this problem.
Error 310 (net::ERR_TOO_MANY_REDIRECTS): There were too many redirects.

This is the error message i'm getting when logging into activeadmin. If i manually change the url to /admin by removing the /login it will allow me into the activeadmin interface just fine, but when i log out and try to log back in this error comes back again. 

I'm also using the devise workaround for redirecting people back to the page they were at after login. This appears to tbe the source of the problem but i'm not sure how to correct it. The code for devise in application.rb is:

  after_filter :store_location

  def store_location
    # store last url as long as it isn't a /users path
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_update_path_for(resource)
    session[:previous_url] || root_path
  end

Any help on this is appreciated :)

**Comment by dchersey** [comment]
👍  Thank you!  I was in my own redirect loop chasing this issue ... cause by me "cleaning up" the routes file edits generated by the active admin installer.  Moving devise_for back to the top made it go away.
