### ISSUE TITLE
feature: custom controller

### ISSUE THREAD

**Issue by traxanos** [activeadmin/activeadmin#215]
for custom buisness logics. eg.
- wizards
- complex forms
- statistics
- reports
- combined searches
- and much more

**Comment by Ruby-rocker** [comment]
@gregbell : Your provide link not working. Here is working link http://activeadmin.info/docs/10-custom-pages.html

**Comment by adisos** [comment]
+1

**Comment by marat93** [comment]
+1

**Comment by tatyshev** [comment]
+1

**Comment by seanlinsley** [comment]
https://github.com/activeadmin/activeadmin/blob/master/docs/8-custom-actions.md
