### ISSUE TITLE
Namespaced "X::Y" resource belongs_to, raises TargetNotFound exception

### ISSUE THREAD

**Issue by kozak** [activeadmin/activeadmin#2217]
A namespaced belongs_to resource raises TargetNotFound exception. 

``` ruby
class Tracking::Visit < ActiveRecord::Base
  has_many :page_views, :class_name => "Tracking::PageView", :dependent => :destroy
end

class Tracking::PageView < ActiveRecord::Base
  belongs_to :visit, :class_name => "Tracking::Visit"
end

ActiveAdmin.register Tracking::Visit do
end

ActiveAdmin.register Tracking::PageView do
  belongs_to :tracking_visit, :parent_class=>Tracking::Visit #I think I've added parent_class for it to work on 3.4.x
end
```

The exception is raised here: 
ActiveAdmin::Resource::BelongsTo

``` ruby
# Returns the target resource class or raises an exception if it doesn't exist
      def target
        namespace.resources.find_by_key(@target_name.to_s.camelize) or 
          raise TargetNotFound, "Could not find registered resource #{@target_name} in #{namespace.name} with #{namespace.resources.inspect}"
      end
```

**Comment by dmahlow** [comment]
Running activeadmin 0.6.6 with inherited_resources 1.3 and this problem still seems to persist. 

I have two models in a 1:n relationship: DataInput::Structure and DataInput::Store

In store.rb I'm defining `belongs_to :structure` which fails with `ActiveAdmin::Resource::BelongsTo::TargetNotFound (Could not find Structure in admin with ["DataInput::Store", "DataInput::Structure"]):`

If I set it to `belongs_to 'DataInput::Structure'` it works, but as soon as I try to link to the child resource from the parent via `li link_to('Stores', admin_data_input_structure_data_input_stores_path(data_input_structure))` and click on that link, I get the following error:
 `NameError (@DataInput::Structure' is not allowed as an instance variable name)`

**Comment by NullVoxPopuli** [comment]
I just ran in to this as well - using whatever version master is as of the date of this comment

**Comment by jcavalieri** [comment]
This appears to still be a problem with `gem 'activeadmin', '~> 1.3', '>= 1.3.1'`.

Is there are workaround that I missed? If not I don't think this issue should be closed.

**Comment by zyqxd** [comment]
The issue appears to be that active admin executes resource associations during file loading. This means that if your `belongs_to` file is before your `parent` file alphabetically, it won't be able to find it.

eg
#### bad
```ruby
# a.rb
ActiveAdmin.register A do
  belong_to :b # will not be able to locate `b` until `b.rb` is loaded.
end
```
```ruby
# b.rb
ActiveAdmin.register B do
...
end
```

#### good (my workaround)
```ruby
# b_a.rb << nested naming
ActiveAdmin.register A do
  belong_to :b
end
```
```ruby
# b.rb
ActiveAdmin.register B do
...
end
```

ActiveAdmin v 1.4.3
