### ISSUE TITLE
Kaminari Overwriting existing scope errors

### ISSUE THREAD

**Issue by patrick-fitzgerald** [activeadmin/activeadmin#2225]
Hi,
I'm getting the following scope errors on startup:

```
Creating scope :page. Overwriting existing method User.page. 
Creating scope :page. Overwriting existing method Address.page. 
Creating scope :page. Overwriting existing method AdminUser.page. 
```

I'm using the following gems:

```
gem 'rails', '3.2.12'
gem "activeadmin", "~> 0.6.0"
gem "kaminari", "~> 0.14.1"
gem "will_paginate", "~> 3.0.4"
```

It seems to be a kaminari '0.13.0' error which was fixed in https://github.com/amatsuda/kaminari/issues/57 . 
I've updated kaminari to 0.14.1 and ran "bundle update kaminari", I'm still getting the errors.
I've also tried the fix mentioned here: https://github.com/spree/spree/issues/436.

Any advice on how to fix?
Thanks

**Comment by walterjsilva** [comment]
This solution: `config.page_method_name = :kaminari_page` does not work for **mongoid** gem. See: [amatsuda/kaminari#646](https://github.com/amatsuda/kaminari/issues/646)
