### ISSUE TITLE
Support for select2 plugin

### ISSUE THREAD

**Issue by danmitchell-** [activeadmin/activeadmin#2267]
Select2 plugin does not render select boxes correctly.

Here is my active_admin.js file

```
//= require select2
//= require active_admin/base

$(".select2able").select2({
  placeholder: "Select a Partner"
});
```

and here is my activeadmin events.rb file

```
f.inputs "Partners" do
  f.input :partners, as: :select, collection: Partner.all, input_html: {class: 'select2able'}
end
```

**Comment by pencilcheck** [comment]
https://github.com/mfairburn/activeadmin-select2

Is this an answer? maybe merge this?

**Comment by varyonic** [comment]
See also #2692.

**Comment by aitbw** [comment]
Hi! I don't know if this might help someone, but I'm currently working with ActiveAdmin 1.0.0.pre5 and just today I managed to get select2 working with one of my forms without problems.

The trick is to build your form, then go to it, right-click on it and hit 'Inspect element', find the `id` the input has, then on your .js file (or .coffee), add the following:

```
# Coffeescript
jQuery ->
  $('#your_id').select2()
```

```
// Javascript
jQuery(function () {
  $('#your_id').select2()
})
```

That should do it :)

Same goes for Chosen and jQuery Tokeninput.

**Comment by Fivell** [comment]
implemented as a plugin https://github.com/mfairburn/activeadmin-select2
