### ISSUE TITLE
ActiveAdmin Not Surfacing Errors In Production

### ISSUE THREAD

**Issue by danielschwartz** [activeadmin/activeadmin#2278]
I'm seeing an issue on our production environment with AA, where when an exception occurs (e.g. a model validation fails, our payment processer throws an exception, mass-assignment error) and instead of surfacing the exception it simply hangs until Rack::Timeout throws an exception (for us after 15 seconds). 

This basically doesn't allow us to surface errors correctly when they happen in AA which is not allowing us to diagnose production bugs correctly, and is confusing our admins as to what actually went wrong. 

This is only happening in our production environment, if I try to recreate locally it does surface the actual error. If I take a look at the trace in New Relic it shows 90% of the time being attributed to "file Template" which makes no sense. 

![screenshot on 2013-06-13 at 12 35 30](https://f.cloud.github.com/assets/505433/649555/6cb6c918-d447-11e2-9f69-518d7d7587b7.png)

Any ideas?

**Comment by pencilcheck** [comment]
Is this fixed? We are getting some possible memory bloat from AA on rails 4 as well. The issue refers to this issue, wondering how's the progress on this front?

**Comment by javierjulio** [comment]
Closing as stale. We only support Rails 4.2 and up now.
