### ISSUE TITLE
validation error: Email and password cannot be blank.

### ISSUE THREAD

**Issue by fullmeasuredesign** [activeadmin/activeadmin#2284]
I am trying to add ActiveAdmin toa rails 4.0.0-rc2 project. For the most part, it is a barebones project at this point. I added the following gems to my gem file,

gem 'devise', github: 'plataformatec/devise', branch: 'rails4'
gem 'activeadmin', github: 'RubySource/active_admin', branch: 'rails4'
gem 'ransack', github: 'RubySource/ransack', branch: 'rails-4'
gem 'protected_attributes'

I am using postgresql, created a DB, installed activeadmin, and altered the devise_create_admin_users migration to use self.up and self.down methods, and moved this line "AdminUser.create!(:email => 'admin@example.com', :password => 'password', :password_confirmation => 'password')" to the end up of the .up file.

Other than those modifications everything is basically out of the box. When I run rake db:migrate I get the following error...

ITMBP:hlt dj$ rake db:migrate
==  DeviseCreateAdminUsers: migrating =========================================
-- create_table(:admin_users)
   -> 0.0102s
-- add_index(:admin_users, :email, {:unique=>true})
   -> 0.0048s
-- add_index(:admin_users, :reset_password_token, {:unique=>true})
   -> 0.0040s
rake aborted!
An error has occurred, this and all later migrations canceled:

Validation failed: Email can't be blank, Password can't be blank/Users/dj/.rvm/gems/ruby-2.0.0-p195@hlt/gems/activerecord-4.0.0.rc2/lib/active_record/validations.rb:57:in `save!'
(this bit continues on with many file references)

I have been racking my brain trying to figure this out. I am not sure where the email/password is blank that it is refering to, as the user it creates is clearly assigned both a user and a password.

**Comment by AtomSmash** [comment]
Still having issues with this in Rails 4.0.2, ruby 2.1.5p273, devise (3.2.4),  activeadmin 1.0.0.pre. Are any of these incompatible?

==  DeviseCreateAdminUsers: migrated (0.1006s) ================================

rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Validation failed: Email can't be blank, Password can't be blank ~/db/migrate/20131108204716_devise_create_admin_users.rb:5:in `migrate'

**Comment by rk-panchal** [comment]
hi. i want to go for omniauth facebook  authentication
 and my model is account.rb

 and my code is....
class Account < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |account|
      account.provider = auth.provider
      account.uid = auth.uid
      account.email =auth.info.email 
       account.password ='xxxxxxxxxx'
      account.oauth_token = auth.credentials.token
      account.oauth_expires_at = Time.at(auth.credentials.expires_at)
      account.save!
    end
  end
 def self.new_with_session(params, session)
    super.tap do |account|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        account.email = data["email"] if account.email.blank?
      end
    end
  end

end

 but i found  
Validation failed: Email can't be blank
plz suggest me any suggestion...
