### ISSUE TITLE
Bundler could not find compatible versions for gem "activerecord"

### ISSUE THREAD

**Issue by GCorbel** [activeadmin/activeadmin#2322]
Hi,

I'm trying to use the rails4's branch. I added this line in my gemfile : 

```
gem 'activeadmin', github: 'gregbell/active_admin', branch: 'rails4'
```

When I'm trying to do `bundle install`, I have this error : 

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    activeadmin (>= 0) ruby depends on
      activerecord (~> 3.0) ruby

    rails (= 4.0.0) ruby depends on
      activerecord (4.0.0)
```

Is there something to do?

Thanks!

**Comment by errakeshpd** [comment]
try this in Gemfile
``` gem 'activeadmin', github: 'gregbell/active_admin' ```

**Comment by fagianijunior** [comment]
Thanks @errakeshpd 
in rails 5.2 it works!!
