### ISSUE TITLE
ArgumentError: A copy of ApplicationController has been removed from the module tree but is still active

### ISSUE THREAD

**Issue by subhashb** [activeadmin/activeadmin#2334]
I am using the latest master, with Rails: 4.0.0.rc2
I experience the above exception, only when I change something in admin/*.rb files, and try to refresh the view.

The entire gist of the problem is here: [Stackoverflow 17561697](http://stackoverflow.com/questions/17561697/argumenterror-a-copy-of-applicationcontroller-has-been-removed-from-the-module)

I think this is related to ActiveAdmin + InheritedResources generated controllers "not being" in the autoload path of Rails, but I might be wrong.

Not sure if this is related to #697 either.

Is there a way to circumvent the problem?

**Comment by monteirobrena** [comment]
@mindhalt you are my hero https://github.com/activeadmin/activeadmin/issues/2334#issuecomment-40253691

**Comment by prognostikos** [comment]
Fully qualifying all constants in our app's ApplicationController fixed this issue for us.

Rails 4.2 with ActiveAdmin 1.0.0.pre1.

**Comment by JonRowe** [comment]
I get this on Rails 4.2 with ActiveAdmin 1.0.0.pre1 but with `ApplicationHelper` rather than `ApplicationController`

**Comment by ChristianPeters** [comment]
> fully qualifying the constant name, like so ::CommonPresenter.new

Thanks @subhashb for the workaround. Would be great to have this fixed – we restarted the server hundreds of times before starting looking for this. x)

**Comment by jayshepherd** [comment]
We also had this problem and fully qualifying our objects in the ApplicationHelper was the trick.

So, to be clear, I looked for any of our specific models and preceded with `::`

Example:
A reference to `UserSession` was updated to `::UserSession`

**Comment by westonplatter** [comment]
fully qualifying ALL constants solved the issue for: Rails 4.1.15 // ActiveAdmin 1.0.0.pre2

Example:
A reference to UserSession was updated to ::UserSession

**Comment by mklnz** [comment]
I'm still getting the circular dependency issue with Rails 4.2.7 and latest ActiveAdmin from git
After doing a fresh install, the generator adds app/admin/admin_user.rb, but seems to conflict with app/models/admin_user.rb

Coming from an older version I recall all models were plural, but now it seems they are singular?

```
RuntimeError: Circular dependency detected while autoloading constant AdminUser
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:492:in `load_missing_constant'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/michael/Development/pingzapper-site/app/admin/admin_user.rb:1:in `<top (required)>'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:457:in `load'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `const_get'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:261:in `block in constantize'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `each'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `inject'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:566:in `get'
... 48 levels...
	from (irb):1
	from /Users/michael/.rbenv/versions/2.3.1/bin/irb:11:in `<top (required)>'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `load'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:63:in `kernel_load'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli/exec.rb:24:in `run'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:304:in `exec'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/cli.rb:11:in `start'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:27:in `block in <top (required)>'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
	from /Users/michael/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.5/exe/bundle:19:in `<top (required)>'
	from /Users/michael/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
	from /Users/michael/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
```

**Comment by remofritzsche** [comment]
We're experiencing similar issues with things like `require_relative 'config/environment'`. Any news / insights on why rails behaves differently in this case?

**Comment by NullVoxPopuli** [comment]
This happens on Rails 5.0.0.1 as well -- whenever the code changes. If I don't change any code, I don't have to restart the server.

**Comment by jtomaszewski** [comment]
Prefixing `::` constants in my callbacks in `ApplicationController` helped for me. Similar to https://github.com/activeadmin/activeadmin/issues/2490#issuecomment-25627837 . Very annoying issue to fix, eh!

**Comment by kimroen** [comment]
Prefixing all the contants in our `ApplicationController` is what fixed this for us as well.

**Comment by varyonic** [comment]
Interesting that this was reported shortly after d7a3ea90eed7f56fd5abdb4ae9f0764cc720e032

**Comment by seanlinsley** [comment]
Yeah, it's likely a bug in how Rails auto-loads files. In particular, that commit made it so the file names for models and AA config files are identical.

**Comment by besi** [comment]
I am using `activeadmin-1.1.0` with `rails-4.2.2` and `ruby 2.2.1p85`.
When I ran `bin/rails g` I got the error:

> Circular dependency detected while autoloading constant AdminUser 

I did that @jtomaszewski suggested and renamed `admin_user.rb` to `admin_users.rb`.
I also had to rename `admin/news.rb` to `admin/newss.rb` (Yes, that's **ss**), before I could run the generator again.

I vote to re-open this issue.

**Comment by RocketPuppy** [comment]
If people are still encountering this (like I am with Rails 5.1.4 and ActiveAdmin 1.1.0) and coming to this ticket from google, you can fix this without renaming or fully qualifying classes. Just exclude app/admin from the eager loaded (or auto loaded) paths. It looks something like this:

```ruby
config.eager_load_paths = Dir.glob("#{Rails.root}/app/*").reject do |path|
  path.include?("admin")
end
```

From here: http://guides.rubyonrails.org/configuring.html.

> config.eager_load_paths accepts an array of paths from which Rails will eager load on boot if cache classes is enabled. Defaults to every folder in the app directory of the application.

**Comment by Dchamel** [comment]
Hello, everyone. I have the same problem as i thought in issues

> /.rvm/gems/ruby-2.3.1/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:508:in `load_missing_constant': Circular dependency detected while autoloading constant AdminUser (RuntimeError)

Rails v 5.1.4, Ruby v 2.3.1p112, ActiveAdmin 1.1.0
I tried to rename "app/admin/admin_user.rb" but nothing happen.
Listing issues few hours but cant understand what to do and how to fix it.

**Comment by rafaelsales** [comment]
Yeah, I have this...

**Comment by rafaelsales** [comment]
Prepending `::` to referenced classes in my `ApplicationController` solved my issue!
https://stackoverflow.com/a/18423438/2701824

**Comment by manhhung741** [comment]
I found out the issue was that `InheritedResources::Base` were not reloaded. Although ActiveAdmin did all the reloading correctly(*), the base class it used wasn't refreshed and still pointed to out-dated ApplicationController. 

It looks like we need to add mechanism to InheritedResources gem (also owned by ActiveAdmin) to do reloading correctly.
```
(byebug) Manage::PlatformSurveysController.superclass.superclass.superclass
InheritedResources::Base
(byebug) Manage::PlatformSurveysController.superclass.superclass.superclass.superclass == ApplicationController
false
```
ActiveAdmin reloaded the classes correctly in here
https://github.com/activeadmin/activeadmin/blob/e0ac14d0657fbba0ffd6623b46e6a755182f00da/lib/active_admin/application.rb#L190

**Comment by manhhung741** [comment]
When I dig into this further, it turns out that ActiveAdmin's own controllers are also not reloaded properly. It is this whole tree that need to be unload & reloaded. I've attempted to do that manually in my app without success. 

ActiveAdmin::ResourceController < ActiveAdmin::BaseController < InheritedResources::Base

Still have to rely on the hack in this issue to work-around it.

**Comment by ptiforka** [comment]
Prefixing all the constants in our ```ApplicationController``` is what fixed this for us as well.
