### ISSUE TITLE
Need to be able to specify the association name with belongs_to

### ISSUE THREAD

**Issue by mwlang** [activeadmin/activeadmin#2349]
belongs_to needs to be able to take an option that specifies the parent's association name when declared.  For example:

```
ActiveAdmin.register Article do
   # ...
end

ActiveAdmin.register LinkedContent do
   belongs_to :article
   # ...
end
```

The auto_link will attempt to infer the link as @article.linked_contents.

If the association is named differently than the child model name, then an error is generated: 

```
  undefined method `linked_contents' for #<Article:0x007fd12814f950>
```

Suggested:

```
ActiveAdmin.register LinkedContent do
   belongs_to :article, as: :related_contents 
   # ...
end
```

Which would cause @article.related_contents to be inferred.

**Comment by NullVoxPopuli** [comment]
is this going to get fixed?

**Comment by Fivell** [comment]
run into this myself , myself, don't see any other way except to handle option for this when declaring belongs_to

**Comment by Fivell** [comment]
@ka8725 , support for polymorphic belongs_to is not supported,but  this issue is about different bug

**Comment by Fivell** [comment]
@timoschilling , according to [specs](https://github.com/activeadmin/activeadmin/blob/6966a84c950b0c86f713548e78587ea659e13c55/spec/unit/auto_link_spec.rb) auto_link argument should be an object, but not collection or relation.

I think this should be closed

**Comment by deivid-rodriguez** [comment]
@Fivell But this seems like a real crash with a pretty standard configuration. As I understand the issue, the OP does not seem to be using `auto_link` directly, just traced down the crash to be inside that method.

And from the error message `"undefined method 'linked_contents' for #<Article:0x007fd12814f950>"`, the method seems to have been called with a proper single object (an article), not a collection.

**Comment by Fivell** [comment]
@deivid-rodriguez , not sure,  for tracking this is initial commit of auto_link and [line where public_send is used](https://github.com/activeadmin/activeadmin/commit/6c633e5d73a395f2430a170af5a088c0ed0928f9#diff-18e773076d81c9e9fe172d88844d6868R67)
