### ISSUE TITLE
Error in strange corner case of validation with lambda

### ISSUE THREAD

**Issue by chris-sun** [activeadmin/activeadmin#2361]
I have a model that has conditional validation like such:

``` ruby
    class Student
      attr_accessor :section
      BASICS = [:gender, :dob, :first_name, :last_name]

     # the line below has a lambda function that takes no arguments
      with_options if: -> { self.section == 'basics' } do |u|
        u.validates_presence_of *BASICS
      end

    end
```

This code works fine in our own application.  The basic views (create, edit, update, delete) all work for this model.

However, with activeadmin 0.5 (and 0.6), when I try to edit one of these Student objects (URL = /admin/students/joe123/edit) , I always get this error:

```
wrong number of arguments (1 for 0)
```

The lambda function (which determines when validation should occur) is getting passed as argument, namely a Student object.  I'm wondering why this is happening.  It's not difficult to update our lambda to take a required argument, but I'm wondering why a Student object is being passed as an argument to the validating function in the first place.

Is there a way to prevent this argument from being passed?
Can this argument not be passed, if possible?

**Comment by Arcolye** [comment]
I'm getting this problem, too.

`validates :phone, presence: true, if: -> { self.rep_university_id.present? }` causes that error
`validates :phone, presence: true, if: -> { true }` causes that error
`validates :phone, presence: true, if: -> true` does NOT cause the error.

It feels like active_admin is trying to figure out whether it should put a "required" asterisk next to the "Phone" field, and doesn't know how to handle Lambdas.

Full trace:

app/models/user.rb:41:in `block in <class:User>'
formtastic (2.2.1) lib/formtastic/inputs/base/validations.rb:39:in `call'
formtastic (2.2.1) lib/formtastic/inputs/base/validations.rb:39:in `validator_relevant?'
formtastic (2.2.1) lib/formtastic/inputs/base/validations.rb:27:in `block in validations'
formtastic (2.2.1) lib/formtastic/inputs/base/validations.rb:26:in `select'
formtastic (2.2.1) lib/formtastic/inputs/base/validations.rb:26:in `validations'
formtastic (2.2.1) lib/formtastic/inputs/base/validations.rb:129:in `validations?'
formtastic (2.2.1) lib/formtastic/inputs/base/validations.rb:136:in `required?'
formtastic (2.2.1) lib/formtastic/inputs/base/labelling.rb:28:in `requirement_text_or_proc'
formtastic (2.2.1) lib/formtastic/inputs/base/labelling.rb:32:in `requirement_text'
formtastic (2.2.1) lib/formtastic/inputs/base/labelling.rb:23:in `label_text'
formtastic (2.2.1) lib/formtastic/inputs/base/labelling.rb:9:in `label_html'
formtastic (2.2.1) lib/formtastic/inputs/phone_input.rb:35:in `block in to_html'
actionpack (3.2.21) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
actionpack (3.2.21) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
actionpack (3.2.21) lib/action_view/helpers/capture_helper.rb:40:in `capture'
formtastic (2.2.1) lib/formtastic/inputs/base/wrapping.rb:11:in `input_wrapping'
formtastic (2.2.1) lib/formtastic/inputs/phone_input.rb:34:in `to_html'
formtastic (2.2.1) lib/formtastic/helpers/input_helper.rb:240:in `input'
activeadmin (0.5.1) lib/active_admin/form_builder.rb:22:in `block in input'
activeadmin (0.5.1) lib/active_admin/form_builder.rb:167:in `with_new_form_buffer'
activeadmin (0.5.1) lib/active_admin/form_builder.rb:22:in `input'
app/admin/users.rb:194:in `block (3 levels) in <top (required)>'
actionpack (3.2.21) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
actionpack (3.2.21) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
actionpack (3.2.21) lib/action_view/helpers/capture_helper.rb:40:in `capture'
formtastic (2.2.1) lib/formtastic/helpers/fieldset_wrapper.rb:32:in `field_set_and_list_wrapping'
formtastic (2.2.1) lib/formtastic/helpers/inputs_helper.rb:292:in `inputs'
activeadmin (0.5.1) lib/active_admin/form_builder.rb:14:in `block in inputs'
activeadmin (0.5.1) lib/active_admin/form_builder.rb:167:in `with_new_form_buffer'
activeadmin (0.5.1) lib/active_admin/form_builder.rb:14:in `inputs'
app/admin/users.rb:183:in `block (2 levels) in <top (required)>'
activeadmin (0.5.1) lib/active_admin/views/pages/form.rb:23:in `instance_exec'
activeadmin (0.5.1) lib/active_admin/views/pages/form.rb:23:in `block in main_content'
actionpack (3.2.21) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
actionpack (3.2.21) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
actionpack (3.2.21) lib/action_view/helpers/capture_helper.rb:40:in `capture'
actionpack (3.2.21) lib/action_view/helpers/form_helper.rb:378:in `form_for'
formtastic (2.2.1) lib/formtastic/helpers/form_helper.rb:161:in `block in semantic_form_for'
formtastic (2.2.1) lib/formtastic/helpers/form_helper.rb:192:in `with_custom_field_error_proc'
formtastic (2.2.1) lib/formtastic/helpers/form_helper.rb:160:in `semantic_form_for'
activeadmin (0.5.1) lib/active_admin/view_helpers/form_helper.rb:8:in `active_admin_form_for'
arbre (1.0.1) lib/arbre/element.rb:175:in `method_missing'
activeadmin (0.5.1) lib/active_admin/views/pages/form.rb:22:in `main_content'
activeadmin (0.5.1) lib/active_admin/views/pages/base.rb:78:in `block (2 levels) in build_main_content_wrapper'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (0.5.1) lib/active_admin/views/pages/base.rb:77:in `block in build_main_content_wrapper'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (0.5.1) lib/active_admin/views/pages/base.rb:76:in `build_main_content_wrapper'
activeadmin (0.5.1) lib/active_admin/views/pages/base.rb:60:in `block in build_page_content'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (0.5.1) lib/active_admin/views/pages/base.rb:59:in `build_page_content'
activeadmin (0.5.1) lib/active_admin/views/pages/base.rb:42:in `block (2 levels) in build_page'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (0.5.1) lib/active_admin/views/pages/base.rb:39:in `block in build_page'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
activeadmin (0.5.1) lib/active_admin/views/pages/base.rb:38:in `build_page'
activeadmin (0.5.1) lib/active_admin/views/pages/base.rb:10:in `build'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (0.5.1) app/views/active_admin/resource/edit.html.arb:1:in `block in ___sers_stephen__rvm_gems_ruby_______gems_activeadmin_______app_views_active_admin_resource_edit_html_arb___1575161354278637386_70172020612780'
arbre (1.0.1) lib/arbre/context.rb:45:in `instance_eval'
arbre (1.0.1) lib/arbre/context.rb:45:in `initialize'
activeadmin (0.5.1) app/views/active_admin/resource/edit.html.arb:1:in `new'
activeadmin (0.5.1) app/views/active_admin/resource/edit.html.arb:1:in `___sers_stephen__rvm_gems_ruby_______gems_activeadmin_______app_views_active_admin_resource_edit_html_arb___1575161354278637386_70172020612780'
actionpack (3.2.21) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.21) lib/action_view/template.rb:143:in `render'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:18:in `render'
newrelic_rpm (3.6.0.78) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:160:in `block in render_with_newrelic'
newrelic_rpm (3.6.0.78) lib/new_relic/agent/method_tracer.rb:235:in `trace_execution_scoped'
newrelic_rpm (3.6.0.78) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:159:in `render_with_newrelic'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.21) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.21) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.21) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.21) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/Users/stephen/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:39:in `render'
activeadmin (0.5.1) lib/active_admin/resource_controller/actions.rb:42:in `block (2 levels) in edit'
actionpack (3.2.21) lib/action_controller/metal/responder.rb:230:in `call'
actionpack (3.2.21) lib/action_controller/metal/responder.rb:230:in `default_render'
actionpack (3.2.21) lib/action_controller/metal/responder.rb:160:in `to_html'
responders (1.1.0) lib/responders/flash_responder.rb:107:in `to_html'
actionpack (3.2.21) lib/action_controller/metal/responder.rb:153:in `respond'
actionpack (3.2.21) lib/action_controller/metal/responder.rb:146:in `call'
actionpack (3.2.21) lib/action_controller/metal/mime_responds.rb:239:in `respond_with'
inherited_resources (1.5.0) lib/inherited_resources/actions.rb:25:in `edit'
activeadmin (0.5.1) lib/active_admin/resource_controller/actions.rb:40:in `edit'
actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.21) lib/active_support/callbacks.rb:535:in `_run__633315143298306296__process_action__1234930790962632983__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
newrelic_rpm (3.6.0.78) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `block in process_action'
newrelic_rpm (3.6.0.78) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:272:in `block in perform_action_with_newrelic_trace'
newrelic_rpm (3.6.0.78) lib/new_relic/agent/method_tracer.rb:235:in `trace_execution_scoped'
newrelic_rpm (3.6.0.78) lib/new_relic/agent/instrumentation/controller_instrumentation.rb:267:in `perform_action_with_newrelic_trace'
newrelic_rpm (3.6.0.78) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
omniauth (1.1.1) lib/omniauth/strategy.rb:177:in `call!'
omniauth (1.1.1) lib/omniauth/strategy.rb:157:in `call'
newrelic_rpm (3.6.0.78) lib/new_relic/rack/error_collector.rb:12:in `call'
newrelic_rpm (3.6.0.78) lib/new_relic/rack/agent_hooks.rb:18:in `call'
newrelic_rpm (3.6.0.78) lib/new_relic/rack/browser_monitoring.rb:16:in `call'
newrelic_rpm (3.6.0.78) lib/new_relic/rack/developer_mode.rb:28:in `call'
warden (1.2.1) lib/warden/manager.rb:35:in `block in call'
warden (1.2.1) lib/warden/manager.rb:34:in `catch'
warden (1.2.1) lib/warden/manager.rb:34:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__3568539546183786786__call__1275304482342247243__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
lib/geoip/cloudflare_middleware.rb:19:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
request_store (1.0.6) lib/request_store/middleware.rb:8:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
railties (3.2.21) lib/rails/engine.rb:484:in `call'
railties (3.2.21) lib/rails/application.rb:231:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
railties (3.2.21) lib/rails/rack/log_tailer.rb:17:in `call'
thin (1.6.2) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.2) lib/thin/connection.rb:84:in `catch'
thin (1.6.2) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.2) lib/thin/connection.rb:53:in `process'
thin (1.6.2) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
thin (1.6.2) lib/thin/backends/base.rb:73:in `start'
thin (1.6.2) lib/thin/server.rb:162:in `start'
rack (1.4.5) lib/rack/handler/thin.rb:13:in `run'
rack (1.4.5) lib/rack/server.rb:268:in `start'
railties (3.2.21) lib/rails/commands/server.rb:70:in `start'
railties (3.2.21) lib/rails/commands.rb:55:in `block in <top (required)>'
railties (3.2.21) lib/rails/commands.rb:50:in `tap'
railties (3.2.21) lib/rails/commands.rb:50:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'

**Comment by th3m4ri0** [comment]
Got the same problem as @Arcolye . Any workaround ?

**Comment by th3m4ri0** [comment]
Just realized I may not have the exact same problem. Found my solution. Change : 
```ruby
# app/admin/signature.rb
def edit
   super do |format|
      @signature.skip_email_validation = true
   end
end

def update
   super do |format|
      @signature.skip_email_validation = true
   end
end
```
to : 
```ruby
before_filter :skip_email_validation, only: [:edit, :update]

private

def skip_email_validation
   resource.skip_email_validation = true
end
```
