### ISSUE TITLE
Ransack fails on tables using closure_tree gem

### ISSUE THREAD

**Issue by mikey0000** [activeadmin/activeadmin#2370]
undefined method `ancestor_hierarchies_id_eq' for #<Ransack::Search

creating a model using closure_tree causes ransack to do the above when adding it as a resource model in ActiveAdmin

it looks like it is failing against the second table created to hold relations in the original table as per the example here. https://github.com/mceachen/closure_tree

I'm putting this here as I'm not sure if it is an issue with AA or Ransack

**Comment by ulfmagnetics** [comment]
I was able to fix this issue by removing the filters that ActiveAdmin was automagically attempting to add based on closure_tree columns:

```
remove_filter :parent, :children, :ancestor_hierarchies,
    :self_and_ancestors, :descendant_hierarchies, :self_and_descendants
```

FYI you can see which filters ActiveAdmin is trying to create like this:

```
ActiveAdmin.application.namespaces[:admin].resources[:YourModel].filters
```
