### ISSUE TITLE
NameError when using config.before_filter

### ISSUE THREAD

**Issue by ryanwood** [activeadmin/activeadmin#2372]
I'm trying to set the time zone for the admin. Everything is functioning normally. I've tried the following:

in active_admin.rb:

`config.before_filter :set_admin_time_zone`

and in application_controller.rb:

```
def set_admin_time_zone
  Time.zone = "Eastern Standard (US & Canada)"
end
```

I've also tried it as a block:

```
config.before_filter do
  Time.zone = "Eastern Standard (US & Canada)"
end
```

Both result in the following error. My local pow development server fails to start (doesn't even make it to a Rails error) with:

```
NameError: uninitialized constant ActiveAdmin::BaseController
~/.rvm/gems/ruby-2.0.0-p247@moonclerk/gems/activeadmin-0.6.0/lib/active_admin/namespace.rb:200:in `eval'
~/.rvm/gems/ruby-2.0.0-p247@moonclerk/gems/activeadmin-0.6.0/lib/active_admin/page_controller.rb:1:in `<top (required)>'
(eval):1:in `register_page_controller'
```

If I comment either of the 2 attempts above, everything works perfectly.

Here's the [full stack trace](https://gist.github.com/ryanwood/6076809).

**Comment by maxrails** [comment]
@ryanwood you are a lifesaver - got same issue and your fix seems works well.activeadmin (0.6.0), rails 3.2.13

**Comment by darrenterhune** [comment]
Had the same issue, simple before filter in app_controller and adding the second config block worked. 

config.before_filter :load_some_data

def load_some_data
end

Cheers @ryanwood
