### ISSUE TITLE
Using single user table for active admin and devise, but different login form

### ISSUE THREAD

**Issue by dianseptiana** [activeadmin/activeadmin#2373]
Hi guys,

I want to implement user management with multiple roles system. The roles are front end user, supplier, moderator, and administrator. I want front end user to login in its login form using devise so the url will be something like this '/users/sign_in', and i want the admin (supplier, moderator, and admin) to login in different login page e.g. '/admin/login'. How i implement it using devise for front end and active admin for back end user? Any idea

**Comment by basco-johnkevin** [comment]
@dianseptiana  Have you found a solution?

**Comment by dianseptiana** [comment]
@basco-johnkevin Not yet. I end up implemented devise on single model (User) with single login form and redirected the user to user dashboard or admin dashboard based on their role.

**Comment by JymsD** [comment]
This can help https://medium.com/@acesubido/part-2-adding-two-factor-authentication-in-activeadmin-cc5eab67057c
