### ISSUE TITLE
Filter's date picker not styling correctly.

### ISSUE THREAD

**Issue by mwlang** [activeadmin/activeadmin#2381]
Rails 4.0 / Ruby 2.0 / active_admin master

The date picker in the filters on the sidebar are not styling correctly on the master branch.  See attached image.  It seems to not fully expand to fit to top and right boundaries.

![active_admin_date_picker](https://f.cloud.github.com/assets/18387/869181/619e97f2-f7e9-11e2-9f5f-561ac3e8e8d9.png)

**Comment by 9732227179** [comment]
Hi,
      in my case , date picker is not showing on the date range filter  on active admin 0.05 pre
any solution?
