### ISSUE TITLE
Incorrect behaviour when using non-default column names for associations

### ISSUE THREAD

**Issue by awh-tokyo** [activeadmin/activeadmin#2382]
Hi there,

I'm building out an admin interface on top of an existing, non-rails and not-too-well-designed database, so my associations are all named non-standard things, like so:

``` ruby
class NameChangeRequest < ActiveRecord::Base
  establish_connection "oldsts_#{Rails.env}"
  self.table_name = 'm_name_change_request'

  belongs_to :member, primary_key: "sts_id", foreign_key: "sts_id"
end

class Member < ActiveRecord::Base
  establish_connection "oldsts_#{Rails.env}"
  self.table_name = 'm_member'
end
```

sts_id is the name of the primary key on each table.

Now, with a "default" Name Change Request resoure in Active Admin:

``` ruby
ActiveAdmin.register NameChangeRequest do
end
```

I get the following error:

undefined method `member_id_eq' for #Ransack::Search:0x007f37358066c8

Which suggests to me that it's ignoring that I specified that the key name for the "member" association is "sts_id" instead of "member_id".

The following resource:

``` ruby
ActiveAdmin.register NameChangeRequest do
  remove_filter :member
end
```

is fine.

**Comment by amiuhle** [comment]
This is still an issue for me (on `master`, with rails `5.0.0.beta2`).

**Comment by seanlinsley** [comment]
Indeed it is: https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/filters/select_input.rb#L18

Here's an attempt @shekibobo made: https://github.com/shekibobo/active_admin/commit/3e075f58b90bdf08cf3876a47a2c82dad7dd6297. I don't remember the context behind that, and why there wasn't a PR.

Feel free to take that code and open a PR, provided you add tests :smile: 

```diff
diff --git a/lib/active_admin/inputs/filter_select_input.rb b/lib/active_admin/inputs/filter_select_input.rb
index e83f1ab..72b4e4e 100644
--- a/lib/active_admin/inputs/filter_select_input.rb
+++ b/lib/active_admin/inputs/filter_select_input.rb
@@ -13,9 +13,9 @@ def searchable_method_name
         if searchable_has_many_through?
           "#{reflection.through_reflection.name}_#{reflection.foreign_key}"
         else
-          name = method.to_s
-          name.concat '_id' if reflection
-          name
+          polymorphic = reflection && reflection.macro == :belongs_to && reflection.options[:polymorphic]
+          key = polymorphic ? nil : reflection.try(:association_primary_key)
+          name = [method, key].compact.join('_')
         end
       end
```

**Comment by amiuhle** [comment]
There actually was a PR, it's linked above.

I have already gone back to the standard `id:integer` primary keys. But if I can find the time, I might still give that problem a shot.

**Comment by javierjulio** [comment]
Closing as stale. Feel free to open a PR thanks!
