### ISSUE TITLE
active_admin logout link not working with Devise wrapped in an engine

### ISSUE THREAD

**Issue by karangb** [activeadmin/activeadmin#2396]
I have devise installed on my "core" engine. The logout link is: core.destroy_user_session_path

I just installed active_admin. Mostly working fine, except the logout link. In the config file, I found the following:

``` ruby
  # == Logging Out
  #
  # Active Admin displays a logout link on each screen. These
  # settings configure the location and method used for the link.
  #
  # This setting changes the path where the link points to. If it's
  # a string, the strings is used as the path. If it's a Symbol, we
  # will call the method to return the path.
  #
  # Default:
  config.logout_link_path = "core.destroy_user_session_path".to_sym
  # config.logout_link_path = "/core/users/sign_out" --> this works!

  # This setting changes the http method used when rendering the
  # link. For example :get, :delete, :put, etc..
  #
  # Default:
   config.logout_link_method = :delete
```

The error message I get is:

``` ruby
NoMethodError - undefined method `core.destroy_user_session_path' for #<ActiveAdmin::Views::TabbedNavigation:0x007f936dc8a8e0>:
  arbre (1.0.1) lib/arbre/element.rb:177:in `method_missing'
  /Users/krg07/.bundler/ruby/2.0.0/active_admin-a9949c152420/lib/active_admin/view_helpers/method_or_proc_helper.rb:56:in `call_method_or_proc_on'
```

Any ideas? I have a feeling that it is calling the method within the "admin" namespace, and hence it can't find the method. If this is the case, how would I fix this?

Thanks!

**Comment by armahillo** [comment]
I had the same problem but I think the issue was that Devise is expecting the :delete REST action, and it was getting :get

**Comment by flyfy1** [comment]
Getting same issue also. Using `Solidus`, which is a rails enigne.

**Comment by DylanReile** [comment]
I resolved this by chaning `config.logout_link_method = :get` to `config.logout_link_method = :delete` in `config/initializers/active_admin.rb`.
