### ISSUE TITLE
datetime picker problem

### ISSUE THREAD

**Issue by chenghung** [activeadmin/activeadmin#2408]
<pre>
  form do |f|
      ....
      f.input :last_play_at, as: :datetime_picker
    end
  end
</pre>

last_play_at column do not display datetime value properly when doing update
Is it formtasic bug ?
## bundled gem

formtastic (2.2.1)
activeadmin (0.6.0)

**Comment by BlackRabbitt** [comment]
Yes, I am having the same problem. datetime_picker is working fine with google chrome but not working in firefox. Same issue as mentioned by @Vizvamitra

**Comment by pessi-v** [comment]
Has anyone found a solution to this?

**Comment by ShamoX** [comment]
Still not resolved. I had to use just-datetime-picker.

You should re-open it.
