### ISSUE TITLE
passing additional parameter(-s) with submit form

### ISSUE THREAD

**Issue by okliv** [activeadmin/activeadmin#242]
``` ruby
form do |f|
...
f.submit_tag, :additional_parameter => 'value'
end
```

all form submits like a charm but i can't pass any hidden parameter (

help please!

**Comment by CapellaBlue** [comment]
I'm having the same problem: unable to pass parameters to my controller on the f.button submit.

This seems like a reasonable ask sans hidden inputs? Maybe I'm missing it in the docs-- do you have a link?

**Comment by varyonic** [comment]
Hidden inputs work for me. Not clear why an alternate solution is desirable.
