### ISSUE TITLE
Integration with Reform to support validation through Form object

### ISSUE THREAD

**Issue by coreyward** [activeadmin/activeadmin#2429]
I'm refactoring a moderately complex application with an ActiveAdmin admin setup. One of the things we're working on is moving our validations out of our models and into Form objects using Reform (or possibly our own). This is the same/similar technique as Avdi Grimm is using in Objects On Rails to greatly simplify workflow issues (of which we're plagued by many). 

On of the key difficulties we're having is ActiveAdmin's reliance on everything in the system being done “the Rails Way”. If our models don't contain our validation and attribute restriction logic anymore, how can we get ActiveAdmin to behave appropriately? Is there any particular class we can replace for our own that augments what objects are delegated to?

**Comment by kevinansfield** [comment]
In case anyone else finds this, I solved it by doing the following for an `active_type` backed form object:

```
ActiveAdmin.register Competitor do

  permit_params :email, :username, :password, :password_confirmation,
    :first_name, :last_name, :bio, :avatar

  controller do
    def new
      @competitor = Competitor::AsSignup.new
      new!
    end

    def create
      @competitor = Competitor::AsSignup.new(permitted_params[:competitor])
      create!
    end
  end
  
end
```

```
class Competitor::AsSignup < ActiveType::Record[Competitor]

  validates :email, presence: true, uniqueness: { case_insensitive: true },
    format: EMAIL_REGEXP
  validates :password, presence: true, confirmation: true,
    length: { within: PASSWORD_LENGTH }
  validates :password_confirmation, presence: true
  validates :age, numericality: { only_integer: true }, allow_nil: true

end
```
