### ISSUE TITLE
Refresh second drop down based on the first drop down

### ISSUE THREAD

**Issue by Dglgmut** [activeadmin/activeadmin#2440]
Would be nice if there were some way to refresh another element data, from one other element.
Something like:

```
  f.input :first_element, refreshes: :second_element
  f.input :second_element
```

So I dont have to use this kind of approach explicitly;
https://gist.github.com/Dglgmut/6328501
or 
http://stackoverflow.com/questions/9579402/active-admin-refresh-second-drop-down-based-on-first-drop-down-ruby-on-rails

**Comment by thuhuongly** [comment]
I've found this gem which supports nested select :yum: https://github.com/platanus/activeadmin_addons/blob/master/docs/select2_nested_select.md

**Comment by liurui12w** [comment]
Hide second drop down based on the first drop down.
How do?
