### ISSUE TITLE
Unable to find input class for hstore

### ISSUE THREAD

**Issue by rebyn** [activeadmin/activeadmin#2443]
I have hstore as one of the data types for my backend and it seems like formtastic hasn't supported this data type yet. Help :-(?

This is the error that I got: `Unable to find input class for hstore`

**Comment by aaditij-webonise** [comment]
@MicFin : I am not able to edit the data. The form loads up all correctly. But when I edit the data I get unpermmitted params error, though I have added it to the permitted params list.

Here is my code 
  `permit_params :name,  :current_address
   form do |f| 
     f.input :name
     f.fields_for :current_address do |current_address|
       f.object.current_address.try(:each) do |key, value|
         current_address.input key, :input_html => {:value => value }
       end
     end
   end`

**Comment by MicFin** [comment]
@aaditij-webonise If you can post the rb file and whole view I might be able to help.  Maybe open a www.stackoverflow.com question as well.

**Comment by aaditij-webonise** [comment]
@McFin, here is the rb file:

ActiveAdmin.register Provider do
  permit_params :dob, :current_address
  menu parent: 'User'
  config.sort_order = 'id_asc'
  actions :all, except: [:new]
  filter :mobile_number
  filter :id

  index do
    selectable_column
    column :id
    column :mobile_number
    column :name
    column :gender
    column :dob
    column :current_address
    actions
  end

  form do |f|
    f.inputs 'Provider Details' do
    f.input :dob, as: :datepicker
      f.fields_for :current_address do |current_address|
        f.object.current_address.try(:each) do |key, value|
          current_address.input key, :input_html => {:value => value }
        end
      end
    end
    f.actions
  end
end

**Comment by seanlinsley** [comment]
@aaditij-webonise the problem is your permitted params:
```ruby
permit_params :name, :current_address
```

That won't work because of the nested values. You either need to do this:
```ruby
permit_params :name, current_address: []
```

Or this:
```ruby
permit_params :name, current_address: {}
```

**Comment by ImDineshSaini** [comment]
Nested attribute must be defined or used blank array in case you are not sure about number of parameter.

**Comment by thejspr** [comment]
Quick'n'dirty fix for this is to create a Formtastic input in `app/inputs/hstore_input.rb`:

``` ruby
class HstoreInput < Formtastic::Inputs::TextInput
end
```

**Comment by seanfcarroll** [comment]
For people with JSONB columns, [try this](https://github.com/udacity/activeadmin_json_editor)

**Comment by yurii-holenko** [comment]
https://github.com/yurii-holenko/activeadmin_hstore_editor
