### ISSUE TITLE
How to display `before_destroy` error from my model in index view

### ISSUE THREAD

**Issue by besi** [activeadmin/activeadmin#2447]
I want to prevent the users from deleting a product if it is still in use like [so](http://stackoverflow.com/questions/4054112/how-do-i-prevent-deletion-of-parent-if-it-has-child-records):

``` ruby
class Product < ActiveRecord::Base

  before_destroy :check_for_users

  private

  def check_for_users
    if users.count > 0
      errors.add(:base, I18n.t('model.validation.product_has_still_users_assigned'))
      return false
    end
  end
end
```

Now if I delete a product from the index view in ActiveAdmin it won't be deleted, but I don't get to see the message, which I add to the errors object.

There seems to be [an approach](http://stackoverflow.com/questions/12358516/how-to-show-base-errors-on-active-admin-gem) to display such errors in a form, but not in the index view.

Is there a way to either configure ActiveAdmin to show those errors or to add the error to some other place so that it gets picked up by ActiveAdmin?

**Comment by mark100net** [comment]
@seanlinsley @murat-usenbai is saying when you click on a link on the resulting page the error message persists to the next page.

It worked for me to replace the flash[:error] line above with:

```
flash.now[:alert] = "#{flash.now[:alert]}  The deletion failed because: # {resource.errors.full_messages.to_sentence}"

```

**Comment by kaelumania** [comment]
I would expect that this is standard functionality of activeadmin.

**Comment by sebastian-echeverria-lenio** [comment]
Overriding shouldn't always be the answer, maybe including options to replicate the base code when creating a resource would be best. As of today, it still is a major issue everyday for Activeadmin.
