### ISSUE TITLE
CSV export produces only one page

### ISSUE THREAD

**Issue by joallard** [activeadmin/activeadmin#2449]
Following a8ad4f9, CSVs can only be generated for the page, which is cumbersome if one has for instance 5000 records.

I've seen nothing in documentation about this. How do we get the whole dataset back?

**Comment by darrenterhune** [comment]
If anyone finds this and wants a simple version of @stereoscott awesome version to export tables using sidekiq https://gist.github.com/darrenterhune/a58ec2e6e3ff83b8a0b7c2b9e937a071

**Comment by DaniilVas1** [comment]
@stereoscott Thanks for your implementing. but I have some questions. 
I had built the Activeadmin with rails and I have 20k records. I hope to download this with CSV. But this happens the timeout error. I deployed this on Heroku. How can I fix this?
Please help me.
Thanks.

**Comment by aramirezdecruz3148** [comment]
@luckhuang did you find a solution? I am struggling with h12 timeouts for our large csv's despite active admin implementing streaming. Most of the solutions and info I am find are pretty outdated, just curious where you landed
