### ISSUE TITLE
Allow inject into header or footer of layout html markup or js code

### ISSUE THREAD

**Issue by jalkoby** [activeadmin/activeadmin#2450]
I enjoy to use activeadmin, but also I like Gon gem which allow to transport some variables from ruby env to js. Gon requires to render helper method `include_gon` in view. But active_admin doesn't allow inject some html code into it layout, so I added dirty patch into my initializer https://gist.github.com/jalkoby/ead3b3a1febb2e8248ee.

It uses internal activeadmin and arbre methods with overriding footer builder of any page. It solves the problem, but solution is not good as it could be. I liked to have something like that in active_admin configuration

``` ruby
ActiveAdmin.setup do |config|
  config.content_for(:footer) do |view_context|
    view_context.concat(view_context.include_gon)
  end
end
```

Is it makes sense for anyone else? Maybe someone suggests more elegant way to solve my problem.

**Comment by mirelon** [comment]
It is fragile. In ActiveAdmin 2 you need to do this:
```
ActiveAdmin.setup do |config|
  config.view_factory.register footer: Footer
end

class Footer < ActiveAdmin::Component
  builder_method :footer

  def build(namespace)
    # you have access to Arbre in here
  end
end
```
