### ISSUE TITLE
Cancan when using ActiveAdmin.register Administrator, :as => "Something Else"

### ISSUE THREAD

**Issue by tomprats** [activeadmin/activeadmin#2468]
I have two similar pages, but want completely different things happening on them, including access.

To do this I have one file like this:

```
ActiveAdmin.register Administrator do
end
```

and one like this:

```
ActiveAdmin.register Administrator, :as => "Something Else" do
end
```

In my Cancan ability.rb file I specify access for the first page like this:

```
can :manage, Administrator
```

But that also allows the second page to be accessed.  How can I specific access to the second page?

**Comment by JeansReal** [comment]
Hi, any update?

**Comment by mabdelfattah** [comment]
LOL, I've the same issue: https://github.com/activeadmin/activeadmin/issues/4783

And the moderators closed it too without any solution!

**Comment by zinovyev** [comment]
The only working (ugly, but working)) solution I've found for now, is to extend your main class with an empty child class instead of renaming the activeadmin resources. So you'll get two completely different resources and you can manage them separately =)

The main class:

```ruby
class Main
#... some logic here
end

ActiveAdmin.register Main do
#... some logic here
end

can :manage, Main
```

An empty chlid:

```ruby
class Child < Main
end

ActiveAdmin.register Child < do
#... some logic here
end

can :manage, Child
```

**Comment by Corstiaan84** [comment]
@zinovyev I get a `undefined method 'column_names'`  error when using your approach. Somehow the child does not have column_names method exposed from the parent class. Did you come across this as well?

**Comment by zinovyev** [comment]
@Corstiaan84 I haven't faced this problem. Are your classes inherited from `ActiveRecord::Base` class?
