### ISSUE TITLE
A copy of ApplicationController has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by firedev** [activeadmin/activeadmin#2490]
I am trying to add ActiveAdmin to my Rails4 app from the `rails4` branch. It works, but I am getting this error every other time I go to `/admin` page and then I have to restart the app to get it to work: 

```
    ArgumentError in Admin::DashboardController#index
    A copy of ApplicationController has been removed from the module tree but is still active!
```

What does this even mean? I checked StackOverflow, but it isn't helping.

**Comment by ezino9** [comment]
This is caused by destroying active admin resource but the model is still used in application.
Do db:rollback and then destroy the model
