### ISSUE TITLE
The AA generator should detect and deal with require_tree

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2514]
This is part of #2513

If AA is installed inside of an app that uses `require_tree .`, the generator should pause and prompt the user to choose an option:
1. Install AA assets in `vendor/assets` instead of `app/assets`
2. Remove the `require_tree` directive from `application.css`
3. Remove the `application.css` file entirely (only appropriate for root-level installs)

**Comment by ccallebs** [comment]
@seanlinsley Is there anything left actionable on this issue?

**Comment by javierjulio** [comment]
Closing out as its gone stale. I'm afraid we are overthinking this. At most what we should do is show a warning on install if we detect that require_tree is in either file that it has to be removed for the admin styles to not be included in other parts of their app.

**Comment by CelsoDeSa** [comment]
## Solution for Rails 5.2.2

In **application.css**

Add:
`*= stub "active_admin"`

Bellow:
`*= require_self`
