### ISSUE TITLE
Filtering with Authorization returns unauthorized records

### ISSUE THREAD

**Issue by andrewhr** [activeadmin/activeadmin#2520]
Using `CanCan` to authorize specific records works well, but filtering doesn't work as expected. I will explain via examples to be more easy (at least to me) describe the issue:

I have something like this model relationship:

``` ruby
class Item < ActiveRecord::Base
  belongs_to :category
end
```

And my `CanCan`'s `Ability` configures the authorization as:

``` ruby
can :read, Category, id: allowed_items
can :manage, Item, category_id: allowed_items
```

When I go to Categories index page everything works well, filtering only allowed items. But I have a filter by category where shows a select box.

The first bug is that the category filter shows all categories (equivalent to `Category.all`) instead of filtering out the unallowed ones.

The second, and IMO worst problem is that when I filter by one unallowed category, it shows the unallowed items, bypassing the configured authorization scopes that initially worked.

If someone needs a more substation code to be able to reproduce the issue, I will be glad to provide. And if someone is able to help me with the AA internals, I can investigate the issue by myself. 

And sorry about my limited english. Thanks for the attention :smile:

**Comment by Fivell** [comment]
@andrewhr,  I'm not familiar with cancan, but I  think reason of this was wrong cancan ability declaration. Can you confirm this?

**Comment by deivid-rodriguez** [comment]
This issue is very old and we haven't received quality feedback in a long time. Please open a new issue with reproduction steps if this is still happening.
