### ISSUE TITLE
Resource locked to user class in specs (BUG)

### ISSUE THREAD

**Issue by andreaslyngstad** [activeadmin/activeadmin#2527]
I have some simple specs on my active admin controllers. Just to see that they handle basic CRUD
This is one example.
 ```ruby
it "assigns the requested blog to @blog" do
    @blog = FactoryGirl.create(:blog)
    get :show, id: @blog
    assigns(:blog).should eq(@blog) 
end
 ```
When I run only the spec file containing this spec It's all green, but when I run all my tests I get this kinds failures.

    Failure/Error: get :show, :id => @blog
    ActionView::Template::Error:
    No route matches {:id=>#<User id: nil, role: nil, phone: nil, name: nil, firm_id: nil, hourly_rate: nil, loginable_type: nil,     loginable_id: nil, loginable_token: nil, created_at: nil, updated_at: nil, avatar_file_name: nil, avatar_content_type: nil,     avatar_file_size: nil, avatar_updated_at: nil, email: "", encrypted_password: "", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil>, :controller=>"admin/blogs", :action=>"show", :format=>nil} missing required keys: [:id]

The url generation on some link_to gets the user class as its resource. 

I tried to override the link_to generation and added this to my initializers/active_admin.rb

```ruby
module ActiveAdmin
     class Resource
     module ActionItems
      private
      # Adds the default action items to each resource
      def add_default_action_items
        # New Link on all actions except :new and :show
        add_action_item :except => [:new, :show] do
          if controller.action_methods.include?('new') && authorized?(ActiveAdmin::Auth::CREATE, active_admin_config.resource_class)
            # link_to(I18n.t('active_admin.new_model', :model => active_admin_config.resource_label), new_resource_path)
          end
        end

        # Edit link on show
        add_action_item :only => :show do
          if controller.action_methods.include?('edit') && authorized?(ActiveAdmin::Auth::UPDATE, resource)
            # link_to(I18n.t('active_admin.edit_model', :model => active_admin_config.resource_label), edit_resource_path(resource))
          end
        end
         # Destroy link on show
        add_action_item :only => :show do
          if controller.action_methods.include?("destroy") && authorized?(ActiveAdmin::Auth::DESTROY, resource)
            # link_to(I18n.t('active_admin.delete_model', :model => active_admin_config.resource_label),
            #   resource_path(resource),
            #   :method => :delete, :data => {:confirm => I18n.t('active_admin.delete_confirmation')})
          end
        end
      end
    end
    end
end

```

Now I got other errors like this
    
    Failure/Error: get :edit, :id => blog
    ActionView::Template::Error:
    undefined method `author' for #<User:0x000000203badb0>

Clearly the User class is the resource, and not Blog. 

This does not error out when I just run the blogs_controller_spec.rb, but i happens for all my active admin controller specs when I run all specs.

**Comment by seanlinsley** [comment]
You need to be doing `get :show, id: @blog.id` instead of passing the blog object as a parameter.
