### ISSUE TITLE
Combine attributes_table and table_for

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2562]
As of #2544 you can now have an attributes table with multiple entries, like this:

``` ruby
attributes_table_for collection do
  row :id
  row :name
end
```

![](https://f.cloud.github.com/assets/25094/1286164/3e53d99a-2fc7-11e3-976a-0ba84e627969.png)

But we want to move it further; combining `attributes_table_for` and `table_for` into the same simple `table_for` method. In #2544 we discussed multiple approaches at a DSL, but eventually settled on using the `row` & `column` methods to distinguish how the table would be rendered. So:

``` ruby
# A normal table
table_for collection do
  column :foo
  column :bar
end
# A flipped table, displayed like the current attributes table
table_for collection do
  row :foo
  row :bar
end
# This would raise an error
table_for collection do
  column :foo
  row :bar
end
```

As well, both table types would A) accept a single record and B) have a plural shortcuts to easily create multiple columns/rows with a single line of Ruby.

``` ruby
table_for User.last do
  column :id
  column :name
  # or:
  row :id
  row :name
end

table_for User.limit(10) do
  columns :id, :name, :email
  # or:
  rows :id, :name, :email
end
```

**Comment by deivid-rodriguez** [comment]
@seanlinsley Do you know the status of this?
