### ISSUE TITLE
undefined method `users_user_id_eq' for Ransack::Search<class: Detail, base: Grouping <combinator: and>>:Ransack::Search

### ISSUE THREAD

**Issue by perkins2099** [activeadmin/activeadmin#2565]
Error: undefined method `users_user_id_eq' for Ransack::Search<class: Detail, base: Grouping <combinator: and>>:Ransack::Search

Rails 4, Ruby 2.  Latest version of Active Admin.

Added basic admin functionality to a model I have called Detail.  Not sure what is going on or what info might be needed to troubleshoot the bug.

Thanks for any help.

**Comment by romainyakarouler** [comment]
thanks u @seanlinsley

**Comment by ronnyworm** [comment]
> Ah, yeah we aren't correctly handling nested `has_many :through` relationships. For now, you can just remove that filter:
> 
> ```ruby
> ActiveAdmin.register Detail do
>   remove_filter :users
> end
> ```

Thanks! For me it was remove_filter :user
