### ISSUE TITLE
I got ActiveModel::ForbiddenAttributesError, can't fix it. Please help.

### ISSUE THREAD

**Issue by Jim2002** [activeadmin/activeadmin#2569]
I got ActiveModel::ForbiddenAttributesError in Admin::PostsController#update when i tried to update a post via activeadmin. This happen when I try to update a post category also.

This is my post controller code.

class PostsController < ApplicationController

   def index
     @post = Post.all
   end

   def new
     @post = Post.new
     @category = Category.all
   end

   def create
      @post = Post.new(post_params)
       if @post.save
       redirect_to posts_path, :notice => 'Your post has been posted!'
       else
       render 'new'
       end
   end

   def edit
      @post = Post.find(params[:id])
   end

   def update
      @post = Post.find(params[:id])
      if @post.update_attributes(post_params)
         redirect_to post_path, :notice => 'Your post has been updated.'
         else
         render 'new'
        end  
   end

   def show
      @post = Post.find(params[:id])
   end

   def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to posts_path, :notice => 'Your post has been deleted.'
   end

```
 def post_params
      params.require(:post).permit(:title, :body, :category_id, :admin_user_id)
```

   end

end

**Comment by mirzoz** [comment]
@zorab47  thanks man!!!!
