### ISSUE TITLE
disable filters on index page

### ISSUE THREAD

**Issue by okliv** [activeadmin/activeadmin#257]
is it possible to disable filters on index page at all? i need to use all width of page to show items table

something like:

index do

   filters false

...

end

**Comment by chetan-alef** [comment]
From the docs

`config.filters = false`

**Comment by ptiforka** [comment]
```
ActiveAdmin.register Post do
  before_action :skip_sidebar!, only: :index
  ...
end
```
rails 5
ruby 2.4

**Comment by tbohr** [comment]
@

> ```
> ActiveAdmin.register Post do
>   before_action :skip_sidebar!, only: :index
>   ...
> end
> ```
> 
> rails 5
> ruby 2.4

yes this is working / with conditions:

`before_action :skip_sidebar!, only: :index, if: proc{ current_admin_user.is_admin? }`
