### ISSUE TITLE
`:commit` and `:utf8` ignored with Strong Parameters

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2595]
Oddly in Rails 4 you don't get an exception in development if a parameter is sent by your form, but isn't expected (the default is to log an error). However you can change that:

``` ruby
config.action_controller.action_on_unpermitted_parameters = :raise
```

So then it's obvious when you aren't whitelisting all of your form parameters. However once you've got your form working correctly, you're still blasted with exceptions because `:commit` and `:utf8` are being sent but aren't expected.

The question here is: what should be done about that? Should either AA or Inhertied Resources whitelist these two params?

**Comment by diegodesouza** [comment]
I know this was discussed last year, but i just ran into the same issue with the params ```Unpermitted parameters: utf8, commit```. Do we still need to monkey patch it to get it "fixed"? Or did we come up with a better solution?

**Comment by ejamesm** [comment]
I'm getting the same error.  Did this ever get fixed - utf8, authenticity_token, and commit whitelisted by active admin??
