### ISSUE TITLE
Bad Documentation - Error adding a history page

### ISSUE THREAD

**Issue by cpfarher** [activeadmin/activeadmin#2600]
In rails 4.0 the documentation in: https://github.com/gregbell/active_admin/wiki/Auditing-via-paper_trail-%28change-history%29#adding-a-history-page fail in file app/views/layouts/history.html.erb:

panel "Historia" do
  table_for assigns[:versions]
end

NoMethodError in Admin::Formulas#history
Showing /home/christian/public_html/rails/cr/app/views/layouts/history.html.erb where line #2 raised:

undefined method `panel' for #<#Class:0x007f5a511a2040:0x007f5a48611030>

Any solution?
Thank you

**Comment by sbpipb** [comment]
Hi, I tried out the history page and it shows an empty page. 
https://gist.github.com/sbpipb/97586bd62b245190595e
