### ISSUE TITLE
Default text boxes are too long

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2633]
I think that the default AA styles leave you with text boxes in forms that are so wide as to be unwieldy. I think it would be better to set the width as a function of the font size, so you get something like [this](http://codepen.io/anon/pen/ekmcl):
![screen shot 2013-10-29 at 2 18 44 pm](https://f.cloud.github.com/assets/688886/1431447/fddae8e0-40ce-11e3-8dd7-f076d328e4a5.png)

So the question then becomes: how wide do we want the default to be?

**Comment by javierjulio** [comment]
We've addressed this in #3862. Once we set master for v2 I'll do more clean up on that as I agree we should have some configurable width for input elements otherwise it gets out of hand.
