### ISSUE TITLE
Handle huge associations

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2692]
AA users are commonly frustrated by our naive building of dropdowns everywhere for a given association, because that option isn't scalable when you have millions of records.

The most obvious option is to allow the developer to blacklist certain models or tables:

``` ruby
ActiveAdmin.setup do |config|
  config.huge_db_tables = %w[tags categories user_actions]
end
```

The question then becomes: what do you replace it with?

As far as I can tell, there are three options:
- just remove it
- use [AJAX](https://github.com/meltingice/ajax-chosen)
- use Rails' `pluck` method to just grab a name and an ID

So which would be best, as far as integrating into the official repo? (both for filters and forms)

**Comment by drush** [comment]
@igorbernstein Your approach looks pretty interesting.  Have you gotten anyone else to collaborate with you on completing the spec prototype?  Is this code in a branch/PR somewhere?

**Comment by ryanwaggoner** [comment]
+1

**Comment by franklsf95** [comment]
Would be a really nice addition. Now I need to manually exclude all the huge associations from generating huge dropdown lists.

**Comment by osmancrush** [comment]
+1

**Comment by benoittgt** [comment]
+1

**Comment by Epiju** [comment]
+1

**Comment by wkoffel** [comment]
+2

**Comment by thinkalike-dev** [comment]
+1

**Comment by kiote** [comment]
+1

**Comment by dmitry** [comment]
Plus one, +1 or :+1: cannot help. Instead please tell how would you like to use it and how the DSL should look like.

**Comment by kiote** [comment]
DSL [here](https://github.com/activeadmin/activeadmin/issues/2692#issuecomment-29355831) seems to be pretty clear, what do you think?

**Comment by aaronchi** [comment]
+1 for this DSL

**Comment by mwlang** [comment]
Is anything being done with this or is it sitting idle?

**Comment by dmitry** [comment]
@mwlang nothing done since: https://github.com/activeadmin/activeadmin/issues/2692#issuecomment-29355831

**Comment by raldred** [comment]
Proposed DSL seems fairly clean, I'd be happy to proceed. It seems consensus is all good. I'm interested in picking this up to implement, does anyone already have this WIP?

**Comment by mwlang** [comment]
I thought about doing it myself, but I'm tight on time at the moment due to project deadlines.  However, if you get started on it, you've got a keen collaborator/tester in me.

**Comment by dmitry** [comment]
@raldred :+1: could be tested by me aswell.

**Comment by seanlinsley** [comment]
I'd be happy to help test.

Coming back to this ticket, I think I'd prefer this syntax instead of providing the catch-all `autocomplete` DSL.
```ruby
filter :user, as: :autocomplete, on: [:first_name, :last_name]

f.input :user, as: :autocomplete, on: [:first_name, :last_name]
```

It requires a little duplication, but I'd prefer to keep it consistent with the existing DSL. An added benefit is that you can decide what order the filters and form fields should show up in.

**Comment by seanlinsley** [comment]
If Postgres is in use, we can easily get [approximate row counts](https://wiki.postgresql.org/wiki/Count_estimate) to automatically detect large tables.

**Comment by seanlinsley** [comment]
Maybe we should make use this instead of reinventing the wheel: https://github.com/activeadmin/activeadmin/issues/1754#issuecomment-131555996

**Comment by raldred** [comment]
Possibly, I actually like your recent proposal, seems consistent like you say with what users are used to.
I'll look into both approaches.

**Comment by fabn** [comment]
I want to share my current implementation (working in my project), it could be abstracted to work in every situation.

I'm using [select2](http://select2.github.io/) at version 4.0.0 which handles normal select inputs instead of needing custom markup for remote datasources.

I created a [gist](https://gist.github.com/fabn/f084ac6aa572d4055588) to avoid including a lot of code here, I explain what my code currently does here.

The core classes (that I think can be reused here) are a [custom input for forms](https://gist.github.com/fabn/f084ac6aa572d4055588#file-ajax_select_input-rb) and a [custom filter class](https://gist.github.com/fabn/f084ac6aa572d4055588#file-filter_ajax_input-rb).

They add some css classes (used in javascript code as selectors) and compute the collection values. If record is new the association is empty, if submitted or edited it only loads current values to prefill select2 options.

The `html_options[:data][:'ajax-url']` part tells select2 the endpoint to query for available completions, in my case I've used a [single controller](https://gist.github.com/fabn/f084ac6aa572d4055588#file-completions_controller-rb) for all completable classes.

Finally there is a javascript file that can be partially reused. My implementation relies on format returned by `Model.completions` which is implemented with elasticsearch. Currently my completable models have a macro like this

```ruby
class Person < ActiveRecord::Base
  # Allow person to be completed with ES.
  acts_as_completable on: :full_name
end
```

My forms use the custom input in this way:

```ruby
  # This model belongs_to :author, class_name: Person
  f.input :author, as: :ajax_select
```

My filters are declared in this way

```ruby
filter :author, as: :ajax
filter :category, as: :ajax
filter :keywords, as: :ajax, multiple: true
```

I think this can work pretty well with the DSL above. The only missing part is to implement the resource DSL part. If one want to use my approach (single parametric controller that handle all completions) the `autocomplete` call should add a method to that controller. 

Otherwise (better, imho) the proposed DSL can be implemented as described and in my inputs the `html_options[:data][:'ajax-url']` should be changed accordingly. A good default could be

```ruby
html_options[:data][:'ajax-url'] ||= options[:completion_path] || default_completions_path

# This will provide a default value if no completion path is given, it's computed using association
# class and complete prefix.
def default_completions_path
  # data_type == User => complete_users_path
  # when massaged by select2 code final url will become /users/complete?q=prefix
  template.url_for([:complete, data_type])
end

# Change it to return model to complete
def data_type
  reflection_for(method).klass
end
```

Hope to help in the implementation and finally have this in core AA.

**Comment by feng88724** [comment]
Here's another one hoping for progress on this. :-)

**Comment by seanlinsley** [comment]
@raldred have you had time to work on this?

**Comment by raldred** [comment]
@seanlinsley sorry not had chance to push on with this yet, i'm just back from a break.
The project that I'm using to drive this is just starting so I hope to get on it very soon. Will keep you posted with my progress here.

**Comment by Darhazer** [comment]
+1

**Comment by terry90** [comment]
+1

**Comment by resaca** [comment]
+1

**Comment by dmitry** [comment]
Please guys, use emotions, in other case those +1 doesn't matter anything:

![github-use-plus](https://cloud.githubusercontent.com/assets/5091/14641577/e71f6e18-063e-11e6-9b5c-cc39f495dd56.png)

**Comment by epitron** [comment]
A nice plugin that solves this problem was released at the beginning of this year: https://github.com/holyketzer/activeadmin-ajax_filter

It supports autocomplete for associations in the form, as well as for filters on the index pages. It's quite simple to configure as well.

**Comment by phillipoertel** [comment]
+1

**Comment by blocknotes** [comment]
IMO one-to-many and many-to-many associations selections are a weak point in ActiveAdmin.

If it can help: some times ago I made a [plugin](https://github.com/blocknotes/activeadmin_selectize) which integrates selectize.js (I didn't know of activeadmin-ajax_filter plugin when I started, which seems quite good).
Now I'm working on another [plugin](https://github.com/blocknotes/activeadmin_select_many) with the same intent: to improve the association selection (similar to RailsAdmin).

**Comment by seanlinsley** [comment]
#4132 should make it so scopes with counts are usable on large tables.

**Comment by allisonphillips** [comment]
Why not just make it the default to add `config.filters = false` at the top of your page definitions? For example:

```ruby
ActiveAdmin.register SomeModel do
  config.filters = false
  # ...
end
```

Alternatively, you can override the default filters by manually declaring only filters that matter to you, or filtering on :
```ruby
# SomeModel: { id: integer, name: string, association1_id: integer, association2_id: integer }
ActiveAdmin.register SomeModel do
  filter :name 
  # Add filter for column value that has a Contains/Equals/'Starts with'/'Ends with' dropdown
  filter :association1_id
  # Add filter for column's exact value (meaning, the exact ID of the associated record)
  filter :association2_id_eq
  # ...
end
```

You can also include records so they will load with your paginated result set:
```ruby
ActiveAdmin.register SomeModel do
  includes :association1, :association2
```

Or define a `controller` block that contains a `scoped_collection` method definition inside the `register` block if you want even more flexibility on what you're putting in your index page.

IMHO the current functionality provides a lot of solutions that require less effort than the implementation details what this feature request is asking for.

**Comment by deivid-rodriguez** [comment]
We added a `maximum_association_filter_arity` configuration for this, but we never changed the default value to something low yet.

**Comment by brianjlandau** [comment]
Is there a reason this was never addressed? Seems like a huge weak spot, as one can't do a `belongs_to` `select` with lots of records as options.

**Comment by rogerkk** [comment]
Would also love seeing a clean solution for this.

I've got some associations with tens of thousands of records and generating the drop downs for adding/removing these can be a real resource hog. Not to mention that finding the correct record in the select box is bit of a hassle. Some kind of typeahead find in stead of a select box would be so awesome.

On a related note: Is there any way to sponsor the development of specific features? :D

**Comment by deivid-rodriguez** [comment]
This was addressed through the `maximum_association_filter_arity` configuration. Did you try setting it?

**Comment by rogerkk** [comment]
@deivid-rodriguez I'm sorry, I was a bit unclear in my description.

I don't have an issue with the filters – I've manually overriden those before when they have been problematic  – but with editing a record with one or more associations to large amounts of items. Finding the right item to add add there, in a huge plain select box, can be cumbersome. 

Especially cumbersome if you don't know exactly what letters(s) the item name starts with. :sweat_smile: 

![Peek 2022-07-29 09-29](https://user-images.githubusercontent.com/97647/181707904-17d24b9d-832b-4696-b006-52cf6868de5b.gif)
