### ISSUE TITLE
Mongoid support

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2714]
Inspired from [a conversation in IRC](https://botbot.me/freenode/activeadmin/msg/7993192/) with @machonemedia, I actually read the source code of @elia's [activeadmin-mongoid gem](https://github.com/elia/activeadmin-mongoid) and was surprised by how little code was actually there. I've never used Mongoid, but it's about time that Active Admin supported a different ORM.

Now in this ticket I'm not looking for +1s; #26 has already made the desire for this clear. Instead I want to identify the hurdles in the way for Active Admin to natively support Mongoid, and what we can do to get from here to there.

There are obviously changes (like #1713) to be made to Active Admin, but I'm more concerned about our dependencies:
#### Kaminari

Do things like #2638 apply to huge MongoDB data sets?
#### Ransack

Ransack [doesn't currently support](https://github.com/activerecord-hackery/ransack/issues/120) Mongoid, and it [may never happen](https://github.com/activerecord-hackery/ransack/issues/120#issuecomment-16276809). There's an [in-progress attempt](https://github.com/kristianmandrup/ransack-mongoid) at adding that functionality, but I don't know how far that's going to go.

I've set the 1.0.0 milestone to February, so the question is can we get a compatibility layer for Ransack 90% done in that time? If that's a dead end, what other options do we have?

CC @johnnyshields, @kristianmandrup

**Comment by maran** [comment]
It's been a while. Anybody did any work on this lately?

**Comment by pencilcheck** [comment]
It's sad but @Zhomart version still has a lot of holes with the current master of activeadmin, it just doesn't work out of box, and in the errors are methods that should've been overwritten a long time ago.

**Comment by Zhomart** [comment]
activeadmin is improved a lot in the last month. Now I got latest master changes and started adding mongoid as @timoschilling suggested earlier. It doesn't work yet, after finishing basic mongoid support and comments I'll make pull request. I'm working on https://github.com/Zhomart/active_admin/tree/mongoid.

**Comment by timoschilling** [comment]
@Zhomart what do you think about activerecord-hackery/ransack#469, how should we deal with it?

**Comment by Zhomart** [comment]
@timoschilling we need to improve it too.

**Comment by timoschilling** [comment]
@Zhomart If you work on the adapter interface, please create a issue for the discussion about the API.

**Comment by Zhomart** [comment]
I need a little help to support multiple ORMs simultaneously. We have method `ActiveAdmin::Filters::FormBuilder#filter` that can only work for one ORM. To support other ORMs it should find ORM using property `klass`. Example:
```ruby
def filter(method, options={})
  if defined?(ActiveRecord) && klass.ancestors.include?(ActiveRecord::Base)
    # then do active record related code
  elsif # something something
  end
end
```

Also, implementations of this methods for different ORMs should be placed in `active_admin/orm/*`. I tried multiple solutions, all of them failed.
There are more than 15 methods in different classes that need to be written specifically for one ORM.

**Comment by timoschilling** [comment]
NOTE: all this thinks are not testet, they are just ideas

How should we detected wich adapter we need to use for wich model?
I see 2 ways:
1. With a `config.default_orm_adapter = "ActiveRecord"` and param for `register`:  
`ActiveAdmin.register Foo, adapter: "Mongoid"`
2. With a detection Based on the model. I have build something similar for a configurable `pretty_format`: https://github.com/activeadmin/activeadmin/compare/master...idea/pretty_format_api

The usage of the Adapter could look like:
```ruby
class ActiveAdmin::Filters::FormBuilder
  def filter(method, options={})
    ActiveAdmin.adapter_for(model).filter(method, options = {})
  end

  # or

  delegate :filter, to: :model_adapter

  def model_adapter
    @model_adapter = "ActiveAdmin.adapter_for(model)"
  end
end
```

```ruby
class MongoidAdapter < AbstractAdapter
  detection do |object|
    object.is_a?(::Mongoid::Document)
  end

  def filter? # not every 
    true
  end

  def filter(method, options={})
    # ...
  end
end
```

I hope that will help you. Otherwise provide more informations.

**Comment by timoschilling** [comment]
@Zhomart you should include #3551 into your work

**Comment by Zhomart** [comment]
@timoschilling I like your ideas. I'll try to implement them.

**Comment by pencilcheck** [comment]
https://github.com/elia/activeadmin-mongoid/issues/97

I believe the setup works for me in Rails 4.1.1, Mongoid 4.

If you are encountering this bug https://github.com/elia/activeadmin-mongoid/issues/95, just use my branch.

```
gem 'activeadmin-mongoid', github: 'pencilcheck/activeadmin-mongoid', branch: 'patch-1'
```

**Comment by juni0r** [comment]
@Zhomart Is there a setup that is currently working?

I used to have
```
gem 'activeadmin', github: 'Zhomart/active_admin', branch: 'mongoid'
gem 'ransack', github: 'activerecord-hackery/ransack', branch: 'master'
```

which was working fine. Now I get a whole bunch of errors e.g.

```
undefined method `except' for #<Mongoid::Criteria:0x007fbfabd957c0>
```

**Comment by Zhomart** [comment]
@juni0r 
try

```ruby
gem 'ransack', github: 'activerecord-hackery/ransack'
gem 'activeadmin',         git: 'git@bitbucket.org:Zhomart/mongoid.git', branch: 'mongoid-old'
```
Example is here https://github.com/Zhomart/ActiveAdminMongoidExample.
Current `Zhomart/active_admin` is under development. I'm experimenting different implementations.

**Comment by juni0r** [comment]
@Zhomart Thanks for the quick reply!

I'm getting

```
Fetching git@bitbucket.org:Zhomart/mongoid.git
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

**Comment by timoschilling** [comment]
Maybe @Zhomart can push that branch to github too

**Comment by Zhomart** [comment]
The branch `mongoid-old` is already at github `https://github.com/Zhomart/active_admin/tree/mongoid-old`.

Try
```ruby
gem 'activeadmin',         github: 'Zhomart/active_admin', branch: 'mongoid-old'
```

**Comment by juni0r** [comment]
@Zhomart This works. Thank you so much for your help and your work on Mongoid support! Thanks also to @timoschilling for incorporating this into Activeadmin. I'm very glad I can finally use it with Mongoid!

**Comment by Ames** [comment]
Thank you all for the awesome work on this!
Apologies if this is not the appropriate place to post this (maybe it should be a ransack ticket?). 

I just updated to:

```
gem 'rails', '~> 4.2'
gem 'mongoid', '~> 4.0.1'
gem 'ransack', github: 'activerecord-hackery/ransack'
gem 'activeadmin', github: 'Zhomart/active_admin', branch: 'mongoid-old'
```

and everything seems to work except for sorting. I'm noticing something funny about the query:

``` 
Started GET "/users?order=first_name_desc" for 127.0.0.1 at 2015-02-13 17:09:23 -0500
...
  MOPED: 127.0.0.1:27017 QUERY        database=mydb collection=users selector={"$query"=>{}, "$orderby"=>{"\"users\".\"first_name\""=>-1}} flags=[] limit=30 skip=0 batch_size=nil fields=nil runtime: 1.7580ms
...
```

It looks like it's including the model name and some extra quotes. I believe it should just be `{"first_name"=>-1}`. Perhaps the cause of the sorting issue lies elsewhere and this funny-looking query is incidental. Curious if anyone else has seen this issue, or has any tips on how to debug this. Thanks!

**Comment by awsmsrc** [comment]
@zhomart we're using your mongoid-old branch and sorting doesnt appear to be working at all?

Is this a known issue or should I spend some time investigating?

**Comment by Zhomart** [comment]
@awsmsrc thanks for the report. I've temp. fixed it on the mongoid-old branch.

**Comment by awsmsrc** [comment]
Thanks @Zhomart what is the difference between mongoid and mongoid-old? which should i be using?

**Comment by Zhomart** [comment]
@awsmsrc mongoid-old is the my first attempt to integrate mongoid to activeadmin using "defined?" everywhere; and comments doesn't work. 
I currently use mongoid to experiment more correct ways intagrate as we discussed in this thread.

**Comment by pencilcheck** [comment]
Should I use Zhomart mongoid fork or is activeadmin supporting mongoid now?

**Comment by Zhomart** [comment]
I'm currently using this temprorary solution:
```ruby
gem 'activeadmin',         github: 'Zhomart/active_admin', branch: 'formtastic2'
gem 'activeadmin-mongoid', github: 'Zhomart/activeadmin-mongoid', branch: 'ransack-mongoid'
```

I've stuck on design problem while adding mongoid to the activeadmin, as it was initially designed to use only one ORM.

**Comment by pencilcheck** [comment]
Cool, thanks. It's a shame that's as far as we can do for now.  :\

**Comment by ptrikutam** [comment]
@pencilcheck did you ever get it working with your Rails project? What version of Mongoid were you using?

**Comment by leandromoreira** [comment]
Nice!
Are there any updates about it? what is the best work around for using active admin with mongoid and rails 4 today?

**Comment by gonzaM** [comment]
Is ActiveAdmin supporting mongoid actually?

**Comment by gonzaM** [comment]
Any update on this? Is ActiveAdmin supporting mongoid with rails 4 ?

**Comment by IvRRimum** [comment]
How about rails 5?

**Comment by varyonic** [comment]
FYI [ActiveAdmin with Rails 5 AND Mongoid 6](https://www.webvolta.com/blog/activeadmin-with-rails-5-and-mongoid-6)

**Comment by IvRRimum** [comment]
@varyonic Neat!

**Comment by gerryhd** [comment]
Anyone know of a workaround for Rails 4 + Mongoid 5? I'm getting a "undefined method 'connection'" error which I assume is because of ActiveAdmin current incompatibility with mongo. The solutions provided here (specifically for Rails 5 and Mongoid 6) gives me gem dependencies problems.

**Comment by varyonic** [comment]
Try [this branch](https://github.com/activeadmin/activeadmin-mongoid/commits/rails4-mongoid5) and open any issue with Elia and Nic [here](https://github.com/activeadmin/activeadmin-mongoid/issues)

**Comment by varyonic** [comment]
Any further issues or suggestions should be directed to [activeadmin-mongoid](https://github.com/activeadmin/activeadmin-mongoid/issues)
