### ISSUE TITLE
Resources using belongs_to have broken menus in at least 2 ways

### ISSUE THREAD

**Issue by pietschy** [activeadmin/activeadmin#2739]
Howdy,

It seems that 0.6.2 menus are broken for resources using belongs_to.  There are two cases I've come across.

If the resource also includes `menu false` then AA raises a `ActiveAdmin::MenuCollection::NoMenuError`

If the the menu isn't disabled the page renders, but the menu only displays a single entry for the current resource type as can been seen below.

![aa_menu_issue](https://f.cloud.github.com/assets/556703/1687747/94d4faa4-5dfa-11e3-84b7-327293f496af.png)

**Comment by achiinto** [comment]
Seeing same issue here. Agree with @yagudaev  that @paulj suggestion would break the application at the root pages, as it is asking for the parent resource id.

**Comment by Fivell** [comment]
@yagudaev , @achiinto , 


```navigation_menu_name``` supports blocks.
I think this is supported


```ruby
navigation_menu do
   if can?(:read, User) 
     :default
  else
     :user
  end
```

**Comment by Fivell** [comment]
looks like https://github.com/activeadmin/activeadmin/commit/5101f786f72e67a6ef25fe21eeff65b8fe37a69b was introduce this
