### ISSUE TITLE
Backport bugfixes to 0.6.stable

### ISSUE THREAD

**Issue by shekibobo** [activeadmin/activeadmin#2742]
In response to @seanlinsley's question in #2739:

Here's a quick summary of things I suspect can be cleanly backported to `0.6.stable`

- [x] Hide blank slate: ecfb8bb
- [ ] Probably can backport the advanced datepicker options (before the JS reorganization, probably)
- [ ] Possibly kaminari update
- [ ] Various translation fixes and updates
- [ ] Long menu CSS styling
- [ ] SVG Icon fixes
- [x] Probably various spec updates that have kept the spec suite passing on master.

**Comment by timoschilling** [comment]
I'm going to close this, but if someone will have a backport create a PR against the `0-6-stable` branch.
