### ISSUE TITLE
Generator Runtime options

### ISSUE THREAD

**Issue by givanse** [activeadmin/activeadmin#2789]
If you execute:
`rails generate active_admin:install --skip-users --skip`
Not all the files, that already exist, will be ignored; prompts for action are still shown.

Complete output:

```
$ rails generate active_admin:install --skip --skip-users
        skip  config/initializers/active_admin.rb
       exist  app/admin
   identical  app/admin/dashboard.rb
       route  ActiveAdmin.routes(self)
    generate  active_admin:assets
   identical  app/assets/javascripts/active_admin.js.coffee
    conflict  app/assets/stylesheets/active_admin.css.scss
Overwrite /home/ivan/Desktop/corzo/app/assets/stylesheets/active_admin.css.scss? (enter "h" for help) [Ynaqdh] n
        skip  app/assets/stylesheets/active_admin.css.scss
```

What I expected was to get zero conflicts and automatically skip all the files that already exist.

My guess is that the flags from the original command are not passed to subsequent commands.
Shouldn't `generate  active_admin:assets` receive the `--skip` flag too?
I think that is the reason why the behavior is not what I expected.

**Comment by zorab47** [comment]
I tried and was unable to reproduce the issue with ActiveAdmin 1.2.1 and Rails 5.1.4. @givanse if this is still a reproducible issue for you, please re-open.
