### ISSUE TITLE
Consider using Cocoon for nested form fields (has-many)

### ISSUE THREAD

**Issue by shekibobo** [activeadmin/activeadmin#2797]
I recently used [Cocoon](https://github.com/nathanvda/cocoon) to implement a has-many sort of form interface in a non-AA environment, and it was seamless. It runs the same kind of callbacks as we do now, and I believe it does removal of persisted records without using checkboxes. Nested fieldsets are inserted using partials. I'm not sure how we might implement that in the current setup, but I think it might be worth trying to outsource a bit of our `has_many` nightmare into something tried and true (it's been around for over 3 years and has a full spec suite).

**Comment by deivid-rodriguez** [comment]
Is this something we still want? This stuff seems to be working properly so I don't feel we need cocoon unless we have a reason. Thoughts?

**Comment by varyonic** [comment]
I do think our has_many implementation is an ugly hack, and I would be happy to see it replaced by Cocoon.

**Comment by dhyegofernando** [comment]
Any updates on this @varyonic @dhahn ? I really wanna see this feature working. By now, has anyone started to working on this? If hasn't, I'd appreciate to start it. I just need some guide for where do I have to start.

Regards

**Comment by varyonic** [comment]
Not a priority for me. I did start trying to make has_many more maintainable in #5196 but beyond that you are on your own.

**Comment by dhahn** [comment]
None from me. Apologies.
