### ISSUE TITLE
How to filter for nil value?

### ISSUE THREAD

**Issue by ncri** [activeadmin/activeadmin#2803]
We need to be able to have a filter that filters a column for nil. This is essential when working with STI in rails, as base class records automatically have nil in their type field.

**Comment by jancel** [comment]
Any update on this?

**Comment by kokethebest** [comment]
its there a simple way to do it??

**Comment by dmil** [comment]
Any update?

**Comment by Fivell** [comment]
guys you can use ransackable scope for this, you can put any logic to your scope

**Comment by varyonic** [comment]
Can be closed?

**Comment by seanlinsley** [comment]
As @Fivell mentioned, Ransackable scopes make it possible to build whatever database query you want.

ActiveAdmin could be changed so that a `nil` in `:collection` automatically turns into a `_is_null` Ransack query, but I suspect that's a pretty complex change.

**Comment by thephw** [comment]
If anyone else is using the model of timestamp or null for states, heres any easy filter for nulls

```
filter :locked_at_not_null, as: :boolean, label: "Locked?"
filter :confirmed_at_not_null, as: :boolean, label: "Confirmed?"
```

**Comment by fohanist** [comment]
> If anyone else is using the model of timestamp or null for states, heres any easy filter for nulls
> 
> ```
> filter :locked_at_not_null, as: :boolean, label: "Locked?"
> filter :confirmed_at_not_null, as: :boolean, label: "Confirmed?"
> ```

You are the best 👍
