### ISSUE TITLE
including jquery.js

### ISSUE THREAD

**Issue by okliv** [activeadmin/activeadmin#281]
i've included jquery.js with config.register_javascript 'jquery.js' (in initializers)
but now i have an error in firebug - "ReferenceError: Can't find variable: $"
i guess, it is because jquery loads after active_admin.js

how to fix it?

thanx

**Comment by liurui12w** [comment]
@okliv Hello, I would like to ask you a question about how to use activeadmin to do cascade drop-down menu. thank
