### ISSUE TITLE
found unpermitted parameters: utf8, authenticity_token, commit

### ISSUE THREAD

**Issue by deneuxa** [activeadmin/activeadmin#2817]
Raise this exception on create action: 

found unpermitted parameters: utf8, authenticity_token, commit

when using in application config :   

```
config.action_controller.action_on_unpermitted_parameters = :raise
```

**Comment by dharb** [comment]
The following worked for my rails 4.2 app:
add this to your app/admin/model.rb
```
permit_params :attribute, :attribute_date, :attribute_time_hour, :attribute_time_minute
```
add this to your app/models/model.rb
```
just_define_datetime_picker :attribute
```

**Comment by jroock** [comment]
But how do you remove the validation?
