### ISSUE TITLE
singular resources support

### ISSUE THREAD

**Issue by Fivell** [activeadmin/activeadmin#2825]
Is there possibility to use singular resources in AA ? 
Rails manual http://guides.rubyonrails.org/routing.html#singular-resources 

"Sometimes, you have a resource that clients always look up without referencing an ID. For example, you would like /profile to always show the profile of the currently logged in user. In this case, you can use a singular resource to map /profile (rather than /profile/:id) to the show"

For instance I have Config resource, and now what I do is redirecting from index to first resource show action.

**Comment by ylecuyer** [comment]
ping

**Comment by timoschilling** [comment]
@ylecuyer pong, if you want this feature write a PR

**Comment by javierjulio** [comment]
Closing out as stale. Happy to take a PR although I think this is best done by the host app, not as a feature from AA. This is something that should be easy enough to do. Perhaps a PR with docs would be best or on the wiki.
