### ISSUE TITLE
Why are tests failing on the 0-6-stable branch?

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2833]
These two tests are failing on the 0-6-stable branch:
```
Failures:

  1) Stylesheets when Rails 3.0.x should render the scss stylesheets using SASS
     Failure/Error: File.exists?(stylesheet_path).should be_true
       expected false to be true

  2) Stylesheets when Rails 3.0.x should not have any syntax errors
     Failure/Error: css = File.read(stylesheet_path)
     Errno::ENOENT:
       No such file or directory - .../active_admin/spec/rails/rails-3.0.20/public/stylesheets/active_admin.css

Finished in 0.3834 seconds
2 examples, 2 failures

Failed examples:

rspec ./spec/integration/stylesheets_spec.rb:31 # Stylesheets when Rails 3.0.x should render the scss stylesheets using SASS
rspec ./spec/integration/stylesheets_spec.rb:35 # Stylesheets when Rails 3.0.x should not have any syntax errors
```

Which I can reproduce locally; until I manually boot up Rails and do an HTTP request, no such file exists. Apparently this was the expected behavior for Active Admin back in the Rails 3.0 days? (ref: https://github.com/gregbell/active_admin/issues/414#issuecomment-1912564)

The thing is, our test suite was [passing](https://travis-ci.org/gregbell/active_admin/builds/15456509) not that long ago. But now we're [consistently failing](https://travis-ci.org/gregbell/active_admin/builds/16118587) :frowning:

How were our tests passing before? I don't see any code that would have previously caused `active_admin.css` to be generated, but then again I don't know what to look for.

**Comment by timoschilling** [comment]
The Travis build is green agin on 0-6-stable.
