### ISSUE TITLE
How to render pages content without layout

### ISSUE THREAD

**Issue by dmitry** [activeadmin/activeadmin#2834]
There are a `main_content` in `ActiveAdmin::Views::Pages::Show` that I would like to render using on xhr method. Just it, without layout content, but the `Base` class adds it. Is there are any clean method to get it?

Methods I've already tried:

1)
`show partial: 'show'`

2)

``` ruby
  show do
    render 'show', context: self, layout: false
  end
```

3)
Overrided the `ActiveAdmin::Views::Pages::Show` registered view_factory in config, and tried to use `build` method, without show's `build` method. But without any luck. Can't get well enough arbre to get it work.

Please give me a point, where to look. Maybe there are some method to get just a partial of the fully rendered DOM, using the something similar to css/xpath?

**Comment by asok** [comment]
I'm using version 1.0.0-pre2 and overwriting `determine_active_admin_layout` is not helping.
