### ISSUE TITLE
Renaming resource doesn't work with nested routes

### ISSUE THREAD

**Issue by samkpower** [activeadmin/activeadmin#2841]
I renamed my resource like so:

```
ActiveAdmin.register ScorecardTemplate, :as => "Foo" do
```

I tried to nest another resource under Foo:

```
ActiveAdmin.register Scorecard, :as => "Bar" do
  belongs_to :scorecard_template
```

But when I tried to access the route (admin/foos/2/bars), it returned this error: 

![image](https://f.cloud.github.com/assets/4931681/1840800/9eb77f7e-7498-11e3-9849-f7e98fb59710.png)

If I remove the name from the parent resource I get this error (admin/scorecard_templates/2/bars):

```
undefined method `bars` for #<ScorecardTemplate:0x00000008986770>
parameters: {"scorecard_template_id"=>"2"}
```

If I remove the new names for both resources on ActiveAdmin and vist admin/scorecard_templates/2/scorecards, it works fine.

**Comment by pmor** [comment]
I know this is quite an old issue, but it's exactly the problem I'm having with a resource that is nested under a renamed resource.

The parameter that gets passed in the URL is `foo_id`, while the nested resource is expecting a `scorecard_template_id`

So, is there a way to specify which `param` gets used to fetch the parent resource?

**Comment by zorab47** [comment]
@pmor It isn't called out in the README, but you can provide a `:param` option to the `defaults` method. See the documentation for [`defaults`](https://github.com/josevalim/inherited_resources/blob/eb430c1ea8c5118bd0437108b14a5d0d0a6b7196/lib/inherited_resources/class_methods.rb#L112-L113) in inherited_resources.

Something like this (which is unverified):

```ruby
ActiveAdmin.register Scorecard, :as => "Bar" do
  belongs_to :scorecard_template

  controller do
    # Instruct Inherited Resources to use the `:foo_id` param.
    defaults :collection_name => "scorecards", :param => :foo_id
  end
end
```

Do report back if you find a solution!

**Comment by zorab47** [comment]
@pmor Any updates on the issue?
