### ISSUE TITLE
Internationalization of float values

### ISSUE THREAD

**Issue by jirubio** [activeadmin/activeadmin#2842]
In floats the separator is locale dependant. A float like 12.35 in spanish should be shown as 12,35. I have configured a valid es.yml file with the correct separator value, but in the show and index pages the float is shown with the english format.
I fix this in my code calling the rails helper "number_with_delimiter()".

**Comment by Fivell** [comment]
@jirubio , how did you configure 

> valid es.yml

**Comment by zorab47** [comment]
Rails requires that numbers which should be internationalized be formatted with one of the `NumberHelper` formatting methods, otherwise they are displayed via `to_s`.

I don't see this as an ActiveAdmin issue unless there is a way to internationalize numbers without using a formatter.
