### ISSUE TITLE
Authorization on a custom page in a namespace

### ISSUE THREAD

**Issue by JakeAustwick** [activeadmin/activeadmin#2854]
Talked to @seanlinsley in [IRC](https://botbot.me/freenode/activeadmin/msg/9606940/), asked me to create an issue.

There is currently no way to set authorisation rules on a custom page if it is name-spaced.

Usual way that doesn't work:

``` ruby
can :read, ActiveAdmin::Page, :name => "General Overview"
```

Also doesn't work:

``` ruby
can :read, ActiveAdmin::Page, :name => "General Overview", :namespace => "reports"
```

Custom Page File:

``` ruby
ActiveAdmin.register_page "General Overview", :namespace => "reports" do
end
```

**Comment by itkin** [comment]
`:namespace_name` value should be a string (an not a symbol) worth saying ... (took me a while to dig this out ;-) )
