### ISSUE TITLE
undefined method `status_tag' for NodeDecorator

### ISSUE THREAD

**Issue by christoph-buente** [activeadmin/activeadmin#2874]
I added draper support for my app (rails 4, activeadmin 1.0.0.pre, draper 1.3) and created a NodeDecorator with the following method:

```
  def wheelchair
    status_tag(model.wheelchair, :class => model.wheelchair)
  end
```

But it wouldn't work. Do i have to include AA View helpers manually? Maybe you can update the decorators documentation.

Cheers

**Comment by cpfarher** [comment]
I think, there is another problem with this approach. Some helpers are not defined in arbre context. For example in https://gist.github.com/cpfarher/d96cdb0c4de617237c7e#file-recipe_recorator-rb-L16 .... How is the best

**Comment by danielricecodes** [comment]
I can confirm @seanlinsley's example works with Draper Decorators also.

### Gem Versions
  * ActiveAdmin 1.0
  * Draper 3.0

### Code Example
```ruby
class FooDecorator < Draper::Decorator
  delegate_all

  def aasm_state
    arbre { status_tag(object.aasm_state, :ok) }
  end

  def some_boolean_field
    object.some_boolean_field? ? arbre { status_tag( "yes", :ok ) } : arbre { status_tag( "no" ) }
  end

  private
  
  def arbre(&block)
    Arbre::Context.new(&block).to_s
  end
end

**Comment by danielricecodes** [comment]
The following worked for me on Rails 6.0.3.2 and ActiveAdmin 2.7.1.   At some point between my last comment in 2018 and now, there's been a change in Rails and/or ActiveAdmin which is causing the suggested solutions to be HTML Escaped.  

Creating instances of [ActiveAdmin::Views::StatusTag](https://www.rubydoc.info/github/gregbell/active_admin/ActiveAdmin/Views/StatusTag) and calling `#status_tag` works, too.

```ruby
def active
  if object.active?
    ActiveAdmin::Views::StatusTag.new.status_tag( 'yes', class: 'ok' )
  else
    ActiveAdmin::Views::StatusTag.new.status_tag( 'no' )
  end
end
```
