### ISSUE TITLE
Is it possible to avoid of writing ALL model's attributes for strong params?

### ISSUE THREAD

**Issue by meliborn** [activeadmin/activeadmin#2875]
I have models with a lot of attributes(including nested). And write them each time makes me crazy.

**Comment by danielricecodes** [comment]
Landed here from a google search.  The answer is easy:

```ruby
controller do
  def permitted_params
    params.permit!
  end
end
```

Voilà

**Comment by gerryhd** [comment]
@danielricecodes That was suggested on the second comment but the point of security was brought up, so I'm wondering what's the correct approach to this given that no field can be edited by default and I have a lot of fields? I'm basically in the same situation as @meliborn 

> By default, I can't edit at all - getting ActiveModel::ForbiddenAttributesError exception. Ok, let's take a look at docs https://github.com/gregbell/active_admin/blob/master/docs/2-resource-customization.md#setting-up-strong-parameters
> 
> It's says, that I should enumerate all model's attributes if I want to edit all of them. How to avoid it? (enumerate all list of attributes for each model)

>Imagine, that I have a list of 20 models with 30 attributes per one model. It's a hell to write them all...

**Comment by danielricecodes** [comment]
@gerryhd - there's no other solution that I know of other than permitting all params or painstakingly listing them all. 

If you want to create the parameter whitelist programmatically, you can still use the `permitted_params` method to do this:

```ruby
controller do
  def permitted_params
   #this could be anything....use your imagination!  
    params.require(resource.param_key).permit(resource.attributes)
  end
end
```

**Comment by jpsilvashy** [comment]
Per @shekibobo's point, you can "reverse" the notion and do something like this:

```
MyModel.attribute_names.map(&:to_sym) - [:password, :update_at, :created_at]
```

If you'd rather say which attributes you _don't_ want to be updated.
