### ISSUE TITLE
Make default AdminUser registration more friendly for user creation and updates

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2885]
Spawned from comments by @krainboltgreene in IRC, we really should make the default user class more simple to use. In particular, we should:
- [ ] make it simple to invite users
- [ ] add a UI that allows you to update the password if you so choose

**Comment by Fivell** [comment]
implemented as plugin https://github.com/platanus/admin-invitable

**Comment by Fivell** [comment]
closing this because no progress/discussion for this feature + it is already implemented as gem
