### ISSUE TITLE
Unable to autoload constant Base

### ISSUE THREAD

**Issue by hooverlunch** [activeadmin/activeadmin#2908]
Encountering this error when trying to run `rake db:migrate` (or any other rake/rails command) after running the generator.

See the gist: https://gist.github.com/hooverlunch/013e7f87216b8ccbf701

I believe the problem is that the InheritedResources gem is trying to be clever and figure out the name of the resource_class and in doing so it's trying `BaseController` with the 'Controller' removed, which ends up as `Base`, on which it calls `.constantize`. (inherited_resources/class_methods.rb:296).

`constantize` then tries to autoload a class called `Base`, which it thinks it should find in an unrelated file in my project: `/app/jobs/base.rb` -- which is actually a Sidekiq file.

I know InheritedResources lets you manually specify the resource_class if you want to, but I have no idea what to set it to in this case.

Please help! This seems like a fairly big issue if the whole thing breaks any time there is a file named `base.rb` in the load path.

I found another similar issue that mentions `active_admin` on a different project page: https://github.com/the-teacher/the_role/issues/42

Thanks!

**Comment by TylerRick** [comment]
I'm running into this too.  Seems to be related to having this in my Rails config:
```ruby
config.autoload_paths += Dir["#{config.root}/app"]
```
and then having a file named `app/whatever/base.rb` which `inherited_resources` stupidly assumes must define a class called `Base`.  But the thing is, I need that, and the autoloading works fine everywhere else, and allows `app/whatever/base.rb` to be auto-loaded when the Whatever::Base is encountered.  This use of autoload_paths seems legitimate (and I probably picked up the idea from some Rails blog recommending it).  So this seems like a bug in `inherited_resources` to me.

I tried the `ActiveAdmin.register User` trick but my app doesn't have a User class (or equivalent). I tried substituting some other model for `User` but still get this error:

```
activeadmin-0.6.0/lib/active_admin/namespace.rb:231:in `eval': Expected app/reports/base.rb to define Base
```

I don't understand why I'd have to configure something to do with User — when it appears to be the loading of `ActiveAdmin::ResourceController` (which then attempts to load `ActiveAdmin::BaseController`, which in turn causes it to look for a `::Base` class) that triggers this, which has nothing to do with User per se.

I've also tried using the latest from the master branch and it still gives the error.

Any suggestions would be appreciated...

**Comment by TylerRick** [comment]
Just thought of a possible workaround... What if we created a dummy `Base` class in `app/models/base.rb` like this?

```ruby
class Base
end
```

I tried that and it seemed to get me past this first error, but now I run into this error:
```
activeadmin-0.6.0/lib/active_admin/namespace.rb:200:in `eval': Expected app/admin/dashboard.rb to define Admin::Dashboard (LoadError)
```

But `app/admin/dashboard.rb` doesn't define a class — it just calls `ActiveAdmin.register_page "Dashboard" do`.  This file was generated by `rails g active_admin:install --skip-users` and has not been modified.

**Comment by TylerRick** [comment]
Adding this to `app/admin/dashboard.rb`:
```ruby
class Admin::Dashboard
end
```
got me past that error and now my app will at least start up... but now I get a `constant Admin::CommentsController not defined` error whenever I visit any page.

**Comment by TylerRick** [comment]
Switching back to master branch resolves that error... (but still requires a dummy `Admin::Dashboard` be defined)

**Comment by timoschilling** [comment]
Maybe `Admin::Dashboard` is required while you have old active admin code in your `app/` folder.

Do you use some magic code with autoload the Model class by the controller name for you?
Something like `cancan`'s `load_and_authorize_resource` method, in you `ApplicationController`?

**Comment by erickreutz** [comment]
Running into this. Anybody have a solution?

**Comment by bekicot** [comment]
Grape + Active Admin + Base class = Uninitialized constant base

Here is a japanese article with work around solution 

[Translated article](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fqiita.com%2Fgamerinshaft%2Fitems%2Fe5c173209f221abd561f&edit-text=
)
[Original Link](http://qiita.com/gamerinshaft/items/e5c173209f221abd561f)

**Comment by timoschilling** [comment]
I'm closing this while it is a inherited_resources issue
