### ISSUE TITLE
Can you release 1.0.0.pre to rubygems?

### ISSUE THREAD

**Issue by ncri** [activeadmin/activeadmin#2910]
Would be helpful for using in an engine. We need to create our own copy of the gem and push it to rubygems otherwise. This is because engines don't allow using gems from github.

**Comment by seanlinsley** [comment]
The only major change that may make it into the 1.0.0 release is #3862, which is a deep refactor of our CSS. If anyone would like to give that a try in their apps and go over the points needed in the as-of-yet unwritten migration guide (#3536), that would help get 1.0.0 out faster.

**Comment by seanlinsley** [comment]
I plan on getting 1.0.0 out as soon as possible. If anyone has further comments, please leave them on #3862 and #3536
