### ISSUE TITLE
Handle 404s

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#2916]
@krainboltgreene in [IRC](https://botbot.me/freenode/activeadmin/msg/10389421/) was confused that the default behavior for a 404 was to show an actual 404 page instead of redirecting to the index page with a flash error. I agree that would provide a better user experience, so lets talk DSL!

I think the default behavior would be to redirect to the `collection_path` if you're going to a resource page, else to redirect to the [`root_to`](https://github.com/gregbell/active_admin/blob/bae6cec4c38ac43deff4476b128796ecfad5741b/lib/generators/active_admin/install/templates/active_admin.rb.erb#L113) location. What haven't I thought of?

**Comment by bsvineeth** [comment]
@seanlinsley, @timoschilling I am interested in picking up this issue. But I am planning on allowing the dev to configure the pages in the `initializers/active_admin.rb` file and look into the `/public` directory for the static pages.

Now, with the changes, the  `initializers/active_admin.rb` file is going to contain additional configurations like 

`config.not_found_page = '/404.html'`
`config.server_error_page = '/500.html'`
`config.unprocessable_entity_page ='/422.html'`

where, `404.html`, `500.html` and `422.html` are present in the `/public` directory of the rails app.

I am planning on letting the defaults(redirecting to the index page with a flash error) remain unchanged, if the config variables are not assigned.

If the config variables are assigned, the corresponding static page is going to get displayed for the corresponding http error.

**Comment by timoschilling** [comment]
@bsvineeth why do we need that? Thats the default behavior of each Rails App.

I think we talk about a error page like this:
![kunden___telecom_consult_hansmann](https://cloud.githubusercontent.com/assets/165599/6805516/b4d71d8c-d243-11e4-8e5e-7d4f49ee69d1.jpg)
Every thing should happen in the ActiveAdmin Layout

**Comment by bsvineeth** [comment]
@timoschilling What you are suggesting makes perfect sense and I'm going to use your advise here.

When discussing about customization, I imagined that different static pages were to be displayed(other than the rails defaults).

**Comment by timoschilling** [comment]
That should not dealt with static pages. We should find a way to catch errors and deliver a error page for that case. The Customization for the could be with a I18n text or by error number named view partials.

**Comment by bsvineeth** [comment]
@timoschilling I'm thinking of extending the `ActiveAdmin::Page` for the error page.

And like how you said, we could use I18n or error number named view partials to display it. 

My next thought is how do we display the contents of the stack trace when the error is hit during the development ?

I will take this up as a next task as soon as I'm done with implementing the error views.

**Comment by bsvineeth** [comment]
@timoschilling Rails is doing global exception handling like this: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/show_exceptions.rb#L31

Do you think we might have to do something similar? Or do you have any alternatives ideas/suggestions?

**Comment by bsvineeth** [comment]
@timoschilling I'm also thinking like this. Let rails do its thing of catching the errors. But when displaying it, let us show it in our Activeadmin layout. What are your thoughts?

![screen shot 2015-03-25 at 5 22 39 pm](https://cloud.githubusercontent.com/assets/1446361/6824006/b536e548-d313-11e4-9f3c-9adeb2dc212a.png)

**Comment by timoschilling** [comment]
I think we should not touch the development errors.
And the Production error should be like my screen shot.

**Comment by timoschilling** [comment]
Hint: Devise has a FailureApp, which is a Rack App, that do something like that what we want. Or maybe a middleware can be a solution.

**Comment by bsvineeth** [comment]
@timoschilling Like how you suggested, I have a middleware that catches errors that are coming from the activeadmin namespace and displays an html page(not the default provided by rails). 

There are two approaches that I see from here. One is that I can register an errors page and redirect the user to it whenever the user encounters an error. The problem with this approach is that the errors page can be accessed with a simple get request to it. And along with this, the error status is lost.

The other approach is that I can render an HTML page from the middleware itself. The problem/tradeoff with this approach is that, all the nice helpers that are available for the view/controller will be unavailable here.

I'm going towards the second idea. Your thoughts/suggestions?

**Comment by bsvineeth** [comment]
Hi @timoschilling I have a working solution. Just like how you had suggested, I followed the working of Devise FailureApp. I created a middleware, which catches the exception if it is under the activeadmin namespace and gives it to an exception_app (just like failure_app). The exception_app is a controller, which renders the required view. 

I'm figuring out the testing strategies for this. As soon as I feel I have a sufficient test coverage for the code that I have written, I will send out a PR.

**Comment by timoschilling** [comment]
That's sounds good! Feel free to create a WIP PR right now, then I can take a look on it and can help you.

**Comment by tjohnell-handy** [comment]
Landed here from Google.  Wanted to link the PR you mentioned:

https://github.com/activeadmin/activeadmin/pull/3870

This is something I'd be interested in!

**Comment by javierjulio** [comment]
This is not a solution we want. This is best handled by the Rails app itself which it already does quite well. If someone wants a custom error page they will get it otherwise just the default is used. I don't think its worth bringing the overhead and duplication in AA if its meant to be used with Rails and Rails already provides this behavior.

**Comment by AlexVentura** [comment]
@javierjulio I want to have a different 404 page for Admin users in ActiveAdmin namespace `/admin` and a different one for users in the rails app.
- How can I achieve this?

**Comment by bsvin33t** [comment]
@AlexVentura I think you can configure rails's errors app to allow your users to see a different 404 page when they are in the `/admin` namespace.

**Comment by AlexVentura** [comment]
@bsvin33t  Is there a working example around here? I saw your PR was not accepted to manage custom 404 pages in AA, right?
So can you help me out how to do this in a good way, please?

**Comment by bsvin33t** [comment]
@AlexVentura I think you will find answers if you explore more as to how to configure errors app on a rails engine, as AA is another rails engine under the hood. I hope this has given you some insight :)
