### ISSUE TITLE
Date field defaults to wrong years

### ISSUE THREAD

**Issue by mstahl** [activeadmin/activeadmin#2925]
I have a field for birthdate but in ActiveAdmin it only gives me this year and the next few years as possibilities.... Well, what if the thing I'm trying to set a date for is in the past, like someone's birthdate?

**Comment by mhassaan** [comment]
Thanks it really helped.

**Comment by salmagomaa** [comment]
https://activeadmin.info/5-forms.html#datepicker

**Comment by leosok** [comment]
This did not work for me - but all the options for the [jQuery-UI-datepicker ](https://api.jqueryui.com/datepicker/#option-yearRange) did. You need to "translate" them from CamelCase to snake_case.

Example [yearRange](https://api.jqueryui.com/datepicker/#option-yearRange): 
```
 input :birthday, as: :datepicker,
        :input_html => {:value => "#{f.object.birthday.strftime("%d.%m.%Y") unless f.object.birthday.nil? } "},
        datepicker_options: {
                            dateFormat: "dd.mm.yy",
                            change_year: true,
                            change_month: true,                 
                            year_range: "#{Time.now.year - 100}:#{Time.now.year - 18}"
                        }
```
