### ISSUE TITLE
member_action render not displaying in main_content div

### ISSUE THREAD

**Issue by jtvjt** [activeadmin/activeadmin#2928]
I'm trying to have a URL under the the User resource that displays a chart. However, no matter what I put inside of the haml view, the main_content div is always blank. The view is being run because I do see log output when I record things there (and breaks if I break the haml syntax)

If I do

``` ruby
ActiveAdmin.register User do
  member_action :internal_chart, :method => :get do
  end
end
```

to get `/admin/users/:id/internal_chart` as a URL

and try to have an `internal_chart.haml` to render the view, I get no content besides the basic AA layout no matter what is in `internal_chart.haml` If I turn `internal_chart.haml` into `_internal_chart.haml`

``` ruby
ActiveAdmin.register User do
  member_action :internal_chart, :method => :get do
    render "internal_chart"
  end
end
```

Fails because it cannot find the main view. (No template error)

If I am explicit about the partial with

``` ruby
ActiveAdmin.register User do
  member_action :internal_chart, :method => :get do
    render :partial => "internal_chart"
  end
end
```

I get the partial rendered directly with no layout, as expected.

Any reason why this would be the case? Thought on what I'm doing wrong? I'm thinking I will have to have a completely custom page to get this working.

**Comment by TJamesCorcoran** [comment]
I'm seeing the exact same thing; it's not just you.

**Comment by micapam** [comment]
Looks to me like ActiveAdmin doesn't recognise haml. If I use an erb it's fine; haml, no go.
