### ISSUE TITLE
Rename class name of resource

### ISSUE THREAD

**Issue by philipgiuliani** [activeadmin/activeadmin#2930]
Hello,

ActiveAdmin automatically adds the classname of an resource to all elements, for example: class="attributes_table section".

My Model has the name "Section" and a class of ActiveAdmin also so i get a lot of formatting problems with this resource. Its possible to rename a class name or to prevent ActiveAdmin of adding this classes?

![bildschirmfoto 2014-02-05 um 09 01 33](https://f.cloud.github.com/assets/5446019/2085118/95b46bb4-8e3b-11e3-9016-92cb39ea8562.png)

i also tried to rename the resource with as: "", but the classnames always take the name of the models.

**Comment by krainboltgreene** [comment]
Please tell me this still isn't an issue :(

**Comment by krainboltgreene** [comment]
What if we just switch it so that the assignment for the resource is called `record`?
