### ISSUE TITLE
Using symbols for describing parent menus leads to errors

### ISSUE THREAD

**Issue by davekapp** [activeadmin/activeadmin#2966]
We're using ActiveAdmin on a Rails 4.0.x application and discovered that using a symbol to set a parent menu for an admin resource led to periodic (but not immediate) errors. By this I mean that things would work and the initially set menu would be correct (and usable) but eventually the application would enter a "bad state" (sorry, I don't have a better way to describe it) where we would get errors on about 80% of ActiveAdmin calls until restarting the server. 

The problem was using something like this:

```menu parent: :users```

in one place, whereas in all other places we had:

```menu parent: 'Users'```

The errors showing up in our logs were along the following lines:

```ActionView::Template::Error: undefined method `users' for <ul class="header-item tabs" id="tabs"></ul>:ActiveAdmin::Views::TabbedNavigation ```

It wasn't until I noticed that in strings we used "Users" (capital U) but had a single place where we had :users as a symbol (lowercase u) that I was able to put that problem together.

After changing to using strings everywhere we have not had a problem with this in over five days. 

I do not know if this is an ActiveAdmin or Arbre issue. We are using Ruby 2.0.0-p353 if that is important. (And we are using Arbre at 4bce1c65b9d65eff343ebdfb36e446547e28b569 to get the Ruby 2 memory fixes.)

**Comment by seanlinsley** [comment]
I'm not seeing this bug on master, so it looks like it has been fixed.
