### ISSUE TITLE
model virtual attributes always nil

### ISSUE THREAD

**Issue by vnmjacky** [activeadmin/activeadmin#2984]
I'm with problems with model virtual attributes with active admin master branch. I'm using rails 4 and on my uploader class i can't get values from this attributes. I use this same class outside active admin and work normal. Have already set permit_params. I updated my active_admin about 2 weeks ago, this problem didn't hapen before. Is this a bug? Thanks

**Comment by buren** [comment]
*tl;dr* The form accesses the fields on the model with `model[:field]`, so it doesn't work with with `#field` or `#field=`.

I tried to set some virtual attributes like this:

```ruby
post = Post.new
post.name = 'Post name'
```
the form still rendered the form with `name` being `nil`.

Instead I needed to set `name` like this:

```ruby
post = Post.new
post[:name] = 'Post name'
```
