### ISSUE TITLE
Circular dependency detected while autoloading constant ...

### ISSUE THREAD

**Issue by vadym-kovalenko** [activeadmin/activeadmin#2990]
Hey. I'm using rails 4.0.0 and AA from master branch. It works fine with web UI, but when I'm trying to run my rspec tests I have `Circular dependency detected while autoloading constant ...` error for every resource registered in AA

**Comment by Fedcomp** [comment]
In my case it was because i was in subdirectory of project, and not root directory. Also project bin directory was in the path.

**Comment by tillcarlos** [comment]
> This issue comes up if your active_admin files are not pluralized. e.g. app/admin/post.rb as opposed to app/admin/posts.rb. Pluralizing all the active_admin files fixed my issue.

I can't believe this was it. 3 months of pain is finally resolved. Thanks so much @dmastylo !!

My model was inside a module, and it seems that AA is not distinguishing between the folders, so my folders also looked like:

`module_name/module_name_classname.rb `

This did the trick. Thanks a lot!
