### ISSUE TITLE
has_many creates duplicated records on Edit

### ISSUE THREAD

**Issue by varholl** [activeadmin/activeadmin#2994]
Hello guys, I'm pretty new to active admin, I'm loving it, but I'm running into an issue that I'm not sure if it's a bug or my mistake, but the documentation didn't helped me to solve this.

Basically, I have a nested resources, and I want to create and EDIT records on the same form.

This is what I'm doing:

``` ruby
ActiveAdmin.register Activity do
  menu label: "Deportes", parent: I18n.t("menu.activities")
  permit_params :name, :description, activity_branches_attributes: [ :name]

  form do |f|
    f.inputs "Details" do
      f.input :name
      f.input :description
    end
    f.inputs "Tiras" do
      f.has_many :activity_branches, :allow_destroy => true do |cf|
        cf.input :name
      end
    end
    f.actions
  end
end
```

Basically, when I create a new Activity, I can add new activity branches, as supposed to, when I try to Edit that category, I see the list of branches there (all seems good :) ), but when I save, instead of updating the branches, it creates a whole new set. 

Let's say I created 3 branches when I was creating the activity, so I go to edit the activity and change the name of one of the branches, instead of updating it, it creates all 3 new branches.

How can I fix this? I know I could use a custom partial view, but I'm not sure if there is a better way!

Thanks in advanced!

**Comment by swilgosz** [comment]
Thank you!

**Comment by NikoEEMI** [comment]
Would you have a solution for an old version of rails where attr_accessible is still set in the model.

For now I have: attr_accessible :collection_attributes 

But it's still creating a new entity and not updating. I had try to pass an array of attributes but without any result...

**Comment by kitayamablue** [comment]
thanks

**Comment by tommotaylor** [comment]
I had the same problem for duplicating records. Adding `:id` and `:_destroy` to the `permit_params` method stopped the duplication but didn't allow records to be destroyed.

You also need to make sure you allow destroy in the model, eg: 

_in activity.rb (model)_
````
accepts_nested_attributes_for :activity_branches_attributes, allow_destroy: true
```

**Comment by mxdavis** [comment]
I used `accepts_nested_attributes_for :activity_branches, allow_destroy: true` but thanks @tommotaylor !!
