### ISSUE TITLE
Comments on models with uuid id's

### ISSUE THREAD

**Issue by skull-squadron** [activeadmin/activeadmin#2999]
### Error encountered

```
PG::InvalidTextRepresentation: ERROR: invalid input syntax for uuid: "1" : SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY created_at ASC LIMIT 1
```
### Workaround
1. Change all models with comments to have `id: :uuid` 
2. Change `active_admin_comments` from:
   
   ``` ruby
   t.references author, polymorphic: true 
   ```
   
   to:
   
   ``` ruby
   t.string :author_type, null: false
   t.uuid   :author_id, polymorphic: true
   ```

See also: http://labria.github.io/2013/04/28/rails-4-postgres-uuid-pk-guide/

**Comment by ronnyworm** [comment]
See also [this](https://github.com/activeadmin/activeadmin/issues/5258)
