### ISSUE TITLE
best way to add actions

### ISSUE THREAD

**Issue by joaomilho** [activeadmin/activeadmin#30]
Hy guys, awesome work!

What is the best way to add custom actions, like "approve"? Where I'm supposed to config routes and this kinda stuff?

Thanks in advance.

**Comment by imarbol** [comment]
To get the layout in your view it's also nice having this:
`render "name_of_your_template", :layout => "active_admin"`
It's not valid with a partial, only with a template, as far as I know.

**Comment by conficker1805** [comment]
thank you @gregbell

**Comment by rocketspacer** [comment]
How to authorize member_action and collection_action?
