### ISSUE TITLE
Don't register ActiveAdmin::Comment as Comments

### ISSUE THREAD

**Issue by gregbell** [activeadmin/activeadmin#301]
It can be confusing to not be able to register your own model named Comment because of the default comments that come with Active Admin. We should register ActiveAdmin::Comments as something other than Comments.

**Comment by abrambailey** [comment]
I know this is very old, but apparently I missed the ability to change the registered names for comments using [config.comments_registration_name = 'AdminComment'](https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/docs/1-general-configuration.md#comments) (posting this comment in case someone else is digging around looking for the solution).

**Comment by edwincarbajal** [comment]
@abrambailey +1 thank you! Saved me a lot of time. Cheers!

**Comment by shootingfly** [comment]
How stupid it is!
Why not make `config.comments_registration_name = 'AdminComment' ` as default?

**Comment by sarmaddevc** [comment]
> config.comments_registration_name = 'AdminComment'
in which file i past it

**Comment by zulays** [comment]
> 
 you don't put it anywhere, you uncomment it in the config folder. It's in this [config repo ](https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/docs/1-general-configuration.md#comments)
