### ISSUE TITLE
error while installing active admin using rails-api

### ISSUE THREAD

**Issue by salayhin** [activeadmin/activeadmin#3017]
Got this error while installing active admin on rails 4.0.2 application. I am using rails-api, where I need something like this admin to manage content apart from client.

undefined method `layout' for ActiveAdmin::Devise::SessionsController:Class

I am not sure about this error. Please help.

**Comment by fd** [comment]
@salayhin I'm seeing the same error. what was your solution?

**Comment by alex88** [comment]
Same here with rails-api

**Comment by alex88** [comment]
Just seen that in case you use `rails-api` you've to add `include ActionView::Layouts` into your application controller

**Comment by ImDineshSaini** [comment]
another error:  undefined method `helper' for ActiveAdmin::Devise::SessionsController:Class

**Comment by tiwariArvind** [comment]
I got same problem to installing Active Admin with rails 5 api.

**Comment by anke1460** [comment]
when use rails api only, it needs to modify the ApplicationController to inherit ActionController::Base

**Comment by damuz91** [comment]
I can confirm @anke1460  solution works on a rails 5 api only project

**Comment by rafaeldalpra** [comment]
Same solution on 6.0.0

**Comment by kevr** [comment]
So.. this gem cannot be used in a rails-api project, without an absurd amount of customization -- perhaps another command should exist for injecting the required deps in that case?

**Comment by bhadoriyaji** [comment]
I got same problem to installing Active Admin with rails 5 api with ruby 2.6 version

**Comment by Hariram-Technomatz** [comment]
I got same problem to installing Active Admin with rails 7.1.2 api with ruby 3.2.2 version
