### ISSUE TITLE
Invalid login credentials

### ISSUE THREAD

**Issue by salayhin** [activeadmin/activeadmin#3018]
"Invalid login credentials" shows when I trying to login. I am using rails 4.0.2 rails application.

localhost:3000/admin

Anybody get this error before ?

**Comment by ahmedshipper** [comment]
I am having the same problem, am new to rails i used this [Tutorial](http://www.sitepoint.com/easy-admin-interfaces-active-admin-rails/) to add active admin in my olx like rails app
