### ISSUE TITLE
Layout customization

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#3023]
After speaking with @vasilakisfil in [IRC](https://botbot.me/freenode/activeadmin/msg/12577261/), it became obvious that we need a built-in way of adding custom HTML to AA's main layout (particularly because [some gems](https://github.com/assembler/attachinary) use this to inject dynamic JS objects). I suggested this monkey patch for now:

``` ruby
# The Active Admin equivalent of putting this in your application layout:
# <head>
#   <%= cloudinary_js_config %>
# </head>

module ActiveAdmin
  module Views
    module Pages
      class Base < Arbre::HTML::Document

        alias_method :original_build_head, :build_active_admin_head

        def build_active_admin_head
          original_build_head

          within @head do
            text_node include_gon
          end
        end

      end
    end
  end
end

```

**Comment by DimaSamodurov** [comment]
What about Idea of https://github.com/bys-control/activeadmin_custom_layout ? Would AA benefit from having page components API public and make it possible to define custom layout?  
E.g. it would allow rendering AA features like index_as_table with filtering within default application layout.
