### ISSUE TITLE
ActiveAdmin "Add New" Button is not working for has_many association

### ISSUE THREAD

**Issue by ricbermo** [activeadmin/activeadmin#3039]
Hi there guys, how are you?

I' working on a project and I need to use nested form in ActiveAdmin, I'm following the docs but I think there's a bug in the latest version of ActiveAdmin. I'm using rails 4 so I need to use the gem directly from github (`gem 'activeadmin', github: 'gregbell/active_admin'`).

Here is my code:

```
 form do |f|
    f.inputs "Mission" do
      f.input :level
      f.input :points
      f.input :title
      f.input :description
    end

    f.has_many :requirements do |r|
      r.input :kind, as: :select, collection: %w(text video image)
      r.input :count
      r.input :description, as: :text
    end

    f.actions
  end
```

and this is actually generating an "Add New Requirement" button at the bottom of the form but
when I click on it the button is just taking me up to the top page (it has a # as the href value) and not generating the form.

**Comment by peggles2** [comment]
I am having the exact same issue. It just jumps to the top of the page and will not work.  Is there a solution for this?

**Comment by doomspork** [comment]
I'm having this same issue myself now, @ricbermo what ultimately worked for you?

**Comment by ricbermo** [comment]
@doomspork, as I posted before, I just created a new file with the coffee code in plain javascript and added it to application.js. Take a look at my second post, just before posting the issue.
