### ISSUE TITLE
Assets not working

### ISSUE THREAD

**Issue by Riddlerrr** [activeadmin/activeadmin#3060]
My ActiveAdmin assets file is not included after I logged in in ActiveAdmin. In logging page work fine.

I am using Ruby 2.1.1, Rails 4.0.4 and ActiveAdmin 1.0.0.pre master brunch on GitHub.

_Gemfile_

``` ruby
gem 'rails', '~> 4.0.4'
...
gem 'activeadmin', github: 'gregbell/active_admin'
```

_active_admin.css.scss_ and _active_admin.js.coffee_ is generated by _active_admin:assets_

After logging ActiveAdmin generated

``` html
<link href="/stylesheets/active_admin.css" media="screen" rel="stylesheet" /> etc...
```

instead

``` html
<link href="/assets/active_admin.css?body=1" media="screen" rel="stylesheet" /> etc...
```

This is bug or I doing something wrong?

**Comment by kaka-ruto** [comment]
Since mine was an API, I had to enable `sprockets` inside `config/application.rb`, then created `manifest.js` file inside `app/assets/config/manifest.js` and added to it an empty `{}`, then added `gem "sassc-rails"` to the `Gemfile`, then `bundle install`ed and restarted the server
