### ISSUE TITLE
ViewsHelpers methods not available in ActiveAdmin with include_all_helpers = false

### ISSUE THREAD

**Issue by aprescott** [activeadmin/activeadmin#3061]
In a project with

``` ruby
config.action_controller.include_all_helpers = false
```

set in `config/application.rb` (different from the default value of `true`), view helpers are not global across all views. This can be desired behaviour to keep things scoped.

However, with this setting, ActiveAdmin can no longer see methods defined in `ActiveAdmin::ViewsHelper`.

``` ruby
# dummy example
module ActiveAdmin::ViewsHelper
  def final_cost(item)
    item.on_sale? ? 10 : 50
  end
end
```

``` ruby
ActiveAdmin.register Item do
  # ...

  index do
    # ...

    column :cost do |item|
      final_cost(item) # not available with include_all_helpers = false
    end

    # ...
  end
end
```

This fails with

```
ActionView::Template::Error (undefined method `final_cost' for #<ActiveAdmin::Views::IndexAsTable:0x00000008ab47c8>):
```

This seems like a bug, since helpers that are defined for ActiveAdmin should be available to ActiveAdmin even if the config setting is set to `false`.

The only work-around I found was to define the helper "inline" with the `register` content:

``` ruby
ActiveAdmin.register Item do
  # ...

  controller do
    def final_cost(item)
      item.on_sale? ? 10 : 50
    end
    helper_method :final_cost
  end

  index do
    # ...

    column :cost do |item|
      final_cost(item)
    end

    # ...
  end
end
```

Obviously this isn't great for organising helper methods, and doesn't allow ActiveAdmin-global helpers.

**Comment by reicheltd** [comment]
@jhenkens your approach works for me in 1.0.0.pre2. thx
