### ISSUE TITLE
PunditAdapter does not apply scopes to non-read actions

### ISSUE THREAD

**Issue by shekibobo** [activeadmin/activeadmin#3068]
I'm using pundit with scopes defined in my policies. The admin user is scoped to an organization, so everything that they create should also be a part of the organization. If I override the scope in the `scoped_collection` method, this works as expected. However, after updating to use a Pundit policy to define the scope, the scope only applies to `index` and `show`.

Indeed, it says as much in the [comments of the adapter](https://github.com/gregbell/active_admin/blob/5ac883c59978799829a8c085fab47f858574c42f/lib/active_admin/pundit_adapter.rb#L14):

``` ruby
    def scope_collection(collection, action = Auth::READ)
      # scoping is appliable only to read/index action
      # which means there is no way how to scope other actions
      Pundit.policy_scope!(user, collection)
    end
```

I'm wondering if this is the desired effect? It seems like it should apply the scope everywhere. Perhaps we need to patch pundit to allow different scopes for different actions?

**Comment by Fivell** [comment]
@shekibobo, can you add detailed example when policy is not applied ? thanks
