### ISSUE TITLE
Undefined mixin 'global-reset'

### ISSUE THREAD

**Issue by kivanio** [activeadmin/activeadmin#3072]
I got this every time i try deploy to heroku.

In development it does not happen.
<code>
gem 'rails',                      '4.0.4'
gem 'activeadmin',                github: 'gregbell/active_admin'
</code>

<code>
   config.assets.initialize_on_precompile = false
  config.assets.precompile += %w( *.js *.css *.svg *.eot *.woff *.ttf *.gif *.png *.ico)
</code>

active_admin.css.scss is inside assets folder.

rake assets:precompile also works fine in development

But when pushing to heroku:
<code>
rake aborted!
       Sass::SyntaxError: Undefined mixin 'global-reset'.
       (in /tmp/build_d04c84fd-22cb-4ef5-8f60-652e72c50318/vendor/bundle/ruby/2.0.0/bundler/gems/active_admin-5ac883c59978/app/assets/stylesheets/active_admin/_base.css.scss:3)
       /tmp/build_d04c84fd-22cb-4ef5-8f60-652e72c50318/vendor/bundle/ruby/2.0.0/bundler/gems/active_admin-5ac883c59978/app/assets/stylesheets/active_admin/_base.css.scss:3:in `global-reset'
       /tmp/build_d04c84fd-22cb-4ef5-8f60-652e72c50318/vendor/bundle/ruby/2.0.0/bundler/gems/active_admin-5ac883c59978/app/assets/stylesheets/active_admin/_base.css.scss:3
       /tmp/build_d04c84fd-22cb-4ef5-8f60-652e72c50318/vendor/bundle/ruby/2.0.0/gems/sass-3.2.18/lib/sass/tree/visitors/perform.rb:253:in`visit_mixin'
       /tmp/build_d04c84fd-22cb-4ef5-8f60-652e72c50318/vendor/bundle/ruby/2.0.0/gems/sass-3.2.18/lib/sass/tree/visitors/base.rb:37:in `visit'
</code>

I have already tried all tweaks i've found in issues list, stackoverflow, google and etc
Nothing seems to fix this.

**Comment by thedma** [comment]
Probably you have wrong settings in initializers/assets.rb
Try to delete it
