### ISSUE TITLE
custom sort on custom column in index ?

### ISSUE THREAD

**Issue by Epiju** [activeadmin/activeadmin#3085]
Hi,

I'm looking for a way to make a custom sort on a custom column in an index page.

``` ruby
ActiveAdmin.register User do
  index do
    id_column
    ...
    column 'Drivers' do |user|
      user.drivers_in_neighborhood.count
    end
  end
end
```

My User#drivers_in_neighborhood method is in User model and is doing SQL queries.
I just want to make the column "Drivers" sortable.

How to do that?

Thanks!

**Comment by gkop** [comment]
+1 @timoschilling , wanting to sort by count(...) but running into this wall.

**Comment by timoschilling** [comment]
@gkop depend on what kind of `count` do you want to do, take a look on:
http://guides.rubyonrails.org/association_basics.html#belongs-to-association-reference (4.1.2)

**Comment by gkop** [comment]
Thanks @timoschilling , you're referring to a counter cache eh? My scenario is habtm with conditions. I don't think you can use the counter cache with conditions - it gets messy - IE a column of an associated row may change, which should affect our count, so then activerecord must not only observe the lifecycle of the joiner rows but also the associated records.

**Comment by timoschilling** [comment]
@gkop yes, I think it don't work for your case too. But I many "I want to sort by count" cases it helps

**Comment by kaelumania** [comment]
I also wanna do something like:

`column :foo, sortable: 'lower(foo)'`

for case-insensitive sorting!

**Comment by Fivell** [comment]
guys, how I  you can override ```apply_sorting``` on controller level 

sort of 
```
controller do 
  def apply_sorting(chain)
      order_clause = ActiveAdmin::OrderClause.new params[:order]
      if order_clause.field == 'lower_foo'
        chain.reorder("lower(foo)  #{order_clause.order}")
      else
        super
      end
    end
end
```


and then describe column like

``` column :foo, sortable:  :lower_foo ```

**Comment by Fivell** [comment]
Just an Idea, would be nice to have something like
```ruby
ActiveAdmin.register User do
   config.order_clause_class = ActiveAdmin::UserOrderClause
end
```
in this case we can extend ```ActiveAdmin::OrderClause``` with our own class to support custom sortings

**Comment by smtheard** [comment]
What is the status of this issue? I am coming across the same problem as the original poster. Is there a workaround?

**Comment by gkop** [comment]
@smtheard I gave up without discovering a workaround.

Instead I have a numeric filter on the counts, which required custom scopes.

**Comment by seanlinsley** [comment]
We could use existing aliases:

```ruby
controller do
  def scoped_collection
    super.includes(:authors).select '*, count(authors.*) as author_count'
  end
end

index do
  column(:authors, sortable: 'author_count') { |b| b.authors.count }
end
```

Or we could allow `sortable` to be set with custom SQL as long as an alias is defined in the string:
```ruby
controller do
  def scoped_collection
    super.includes(:authors)
  end
end

index do
  column(:authors, sortable: 'count(authors.*) as author_count') { |b| b.authors.count }
end
```

In both cases, we'd use the alias in the HTML, instead of the SQL fragment itself.

**Comment by seanlinsley** [comment]
I'd probably prefer to only support one of these, to reduce complexity. What does everyone think?

**Comment by seanlinsley** [comment]
The first option would better suit @Epiju's needs. It could also allow you to do this:

```ruby
controller do
  def scoped_collection
    super.includes(:authors).select '*, count(authors.*) as author_count'
  end
end

index do
  column :author_count, sortable: true
end

**Comment by aruncsengr** [comment]
Guys and @seanlinsley, i tried to implement the following approach but facing a issue in it. Here goes the code snippet:

```
class FailureGroup < ActiveRecord::Base
  has_many :jobs, -> { where(status: Job::STATUS_FAILED).with_exception }
end
```

```
index do
  column :jobs_count, sortable: true do |failure_group|
    link_to failure_group.jobs.count, admin_failure_group_jobs_path(failure_group)
  end
end

controller do
  def scoped_collection
    super.includes(:jobs).select '*, count(jobs.*) as jobs_count'
  end
end
```

I get the following error:
PG::UndefinedTable - ERROR:  missing FROM-clause entry for table "jobs"
LINE 1: SELECT  *, count(jobs.*) as jobs_count FROM "failure_groups"...

It would be really helpful if someone support me in resolving this issue!

**Comment by dmitry** [comment]
You need `eager_load(:jobs)`

**Comment by aruncsengr** [comment]
Thanks @dmitry i tried with that, then i faced the error:

> PG::GroupingError - ERROR:  column "failure_groups.id" must appear in the GROUP BY clause or be used in an aggregate function
> LINE 1: SELECT *, count(jobs.*) as jobs_count, "failure_groups"."id"...

So changed my code to:
`super.eager_load(:jobs).select('*, count(jobs.*) as jobs_count').group("failure_groups.id")`
but again it leads to another grouping error:

> PG::GroupingError - ERROR:  column "failure_groups.id" must appear in the GROUP BY clause or be used in an aggregate function
> LINE 1: SELECT *, count(jobs.*) as jobs_count, "failure_groups"."id"...

Any idea how to proceed further?

**Comment by krishnasrihari** [comment]
This not required any select count statement, you can simply use this syntax to achieve sortable count for has_many association.

`    column :invite_count, sortable: true do |object|
      object.invites.count
    end`

**Comment by krishnasrihari** [comment]
I have tried @seanlinsley solution but this is not working as include doesn't include any has_many relation column. I have come up with new solution here

`super.joins("LEFT JOIN invites ON profiles.id = invites.profile_id").select("profiles.*, COUNT(invites.id) as invite_count").group("profiles.id")`

`column :invite_count, sortable: true`

**Comment by aruncsengr** [comment]
Cool, thank u so much @krishnasrihari, i have analyzed it and would like to suggest a minor change to resolve sorting URL issue.,
`column :invite_count, sortable: invite_count`

Finally, here goes the working solution to get revealed so that it'll be helpful for others too.,
```
class FailureGroup < ActiveRecord::Base
  has_many :jobs, -> { where(status: Job::STATUS_FAILED).with_exception }
end
```

```
index do
  column :job_count, sortable: job_count do |failure_group|
    link_to failure_group.jobs.count, admin_failure_group_jobs_path(failure_group)
  end
end

controller do
  def scoped_collection
    super.joins(
        %(LEFT JOIN "jobs" ON "jobs"."failure_group_id" = "failure_groups"."id" AND "jobs"."status" = #{Job::STATUS_FAILED}
          AND ("jobs"."exception" IS NOT NULL)))
        .select('failure_groups.*, COUNT(jobs.id) as job_count')
        .group('failure_groups.id')
  end
end
```

**Comment by nicodeceulaer** [comment]
Thanks; this solved my problem.
One small remark, the above example code is missing a colon on invite_count

`column :invite_count, sortable: :invite_count`**

**Comment by aruncsengr** [comment]
@nicodeceulaer Thanks for the heads up! missed it while editing. Updated it now ;)

**Comment by nicodeceulaer** [comment]
The above solution does not work very well with the pagination logic.
Pagination triggers a count() on scoped_collection. But due to the join/select/group added there, the end result is an SQL query that reads the entire table:
`    def scoped_collection
      super.joins('LEFT JOIN "debugdumps" ON "debugdumps"."crash_id" = "crashes"."id"')
           .select('crashes.*, COUNT(debugdumps.id) as debugdump_count')
           .group('crashes.id')
    end

SELECT COUNT(*) AS count_all, crashes.id AS crashes_id FROM "crashes" LEFT JOIN "debugdumps" ON "debugdumps"."crash_id" = "crashes"."id" GROUP BY crashes.id
`
Regretfully, the same scoped collection also blocks against the current pagination disable code. So the only way out now is to make my own pagination logic as proposed in [stackoverflow](http://stackoverflow.com/questions/32357724/activeadmin-pagination-links-are-gone-with-scoped-collection-group-by)

**Comment by Fivell** [comment]
test and feedback are appriciated

**Comment by andreydeineko** [comment]
Is there a possibility to sort in index by method (non-db backed values)?

**Comment by senid231** [comment]
how about adding `sort_clause` as `column` option
```ruby
column :name, sort_clause: 'LOWER(authors.name)' do |r| # optional sortable: true
  r.name # URL ...&sort=name_asc => SQL ... ORDER BY LOWER(authors.name) ASC
end
column :name, sortable: :lower_name, sort_clause: 'LOWER(authors.name)' do |r|
  r.name # URL ...&sort=lower_name_desc => SQL ... ORDER BY LOWER(authors.name) DESC
end
```

**Comment by heridev** [comment]
This is the way I'm sorting by custom values and preventing n + 1 queries
```
class TechResult < ActiveRecord::Base
  belongs_to :user
end

class User < ActiveRecord::Base
  belongs_to :organization
end

class Organization < ActiveRecord::Base
  has_many :users
end
```

and then in your tech_results section, you want to render an organization field, in my case the value `tech_result.user.organization.name` this is the way to sort them out:

```
ActiveAdmin.register TechResult do
  config.batch_actions = false
  permit_params :user_id

  preserve_default_filters!

  index do
    column :id
    column 'user', sortable: 'users.name' do |tr|
      tr.user.name
    end
    column 'organization', nil, sortable: 'organizations.name' do |tr|
      tr.user.organization.name.titleize if tr.user.organization
    end

  end

  controller do
    def scoped_collection
      super.includes(user: [:organization])
    end
  end
end
```

**Comment by praveenrajt** [comment]
How to I sort store Attribute Accessor

user.rb

```
class User < ApplicationRecord
    valivalidates :email , presence: true
    valivalidates :name , presence: true
    valivalidates :phone_number , presence: true
    store :extra_fields, accessors: [:status, :another_email_id, :another_phone_number]
end
```
admin/users.rb

```
ActiveAdmin.register User do

index do
    column :name
    column :email
    column :phone_number
    column :status
    column :another_phone_number
    column :another_email_id
end
```

**Comment by olleicua** [comment]
> guys, how you can override `apply_sorting` on controller level
> 
> sort of
> 
> ```
> controller do 
>   def apply_sorting(chain)
>       order_clause = ActiveAdmin::OrderClause.new params[:order]
>       if order_clause.field == 'lower_foo'
>         chain.reorder("lower(foo)  #{order_clause.order}")
>       else
>         super
>       end
>     end
> end
> ```
> 
> and then describe column like
> 
> `column :foo, sortable: :lower_foo`

This was extremely useful and should probably get documented somewhere. Also I had to modify it slightly as `ActiveAdmin::OrderClause.new` expects two parameters the first of which is supposed to be a config object.
