### ISSUE TITLE
Changes in CSV headers?

### ISSUE THREAD

**Issue by Jamevidi** [activeadmin/activeadmin#3096]
This code,
    csv do 
      column("name") { |i| i.name }
      column("last_name") { |i| i.last_name }
    end

..gives these headers in the csv file: "Name", "Last name"

I use the latest branch: activeadmin (1.0.0.pre)
   gem 'activeadmin', github: 'gregbell/active_admin'

Any ideas? Or am I doing something wrong?

**Comment by varyonic** [comment]
#2771 was a breaking change, now fixed.
