### ISSUE TITLE
When mouting the application in a subdirectory, generated links don't respect the prefix

### ISSUE THREAD

**Issue by robotex82** [activeadmin/activeadmin#3106]
I have to mount my whole rails application in a subdirectory '/central'. So I changed my config.ru to look like this:

```
map '/central' do
    run Central::Application
end # map
```

Using a scope or namespace is unfortunately no option, because the wohle thing is being deployed as war-file under '/central'

Outside of active admin I get correctly prefixed links, like

```
http://localhost:3000/central/posts/1
```

Inside of activeadmin I see

```
http://localhost:3000/backend/posts
```

But it should be

```
http://localhost:3000/central/backend/posts
```

I tried to put following lines in application.rb, but no look either:

```
config.relative_url_root = "/central"
config.action_controller.default_url_options = { :path_prefix => '/central' }
```

Any clues?

I'm using: 
- jruby-1.7.11 (switching to mri makes no difference)
- rails-3.2.17
- activeadmin-0.6.3

**Comment by sgruhier** [comment]
I just tried activeadmin and I still have that issue on top menu links 
![image](https://cloud.githubusercontent.com/assets/3385/19105418/1979603a-8ae2-11e6-9834-f847d2b737f8.png)
