### ISSUE TITLE
Eager Loading Has_Many Association 

### ISSUE THREAD

**Issue by pivotalshiny** [activeadmin/activeadmin#3108]
Hey there,
- We have two models. Amodel and Bmodel. 
- Table for Amodel is very large. 
- Amodel belongs to Bmodel.
- Bmodel has_many Amodels.

When we view the index view for Bmodel, we see in the logs that it tries to call

```
select * from amodels
```

which hangs because the table Amodels is huge.

Here is the code snippet

``` ruby
class Amodel < ActiveRecord::Base
  belongs_to :bmodels, :foreign_key => :bmodel_id
end

class Bmodel < ActiveRecord::Base
  has_many :amodels
end

ActiveAdmin.register Bmodel do
  menu label: 'Bmodel', parent: 'Amodel',  priority: 15
  index title: 'Bmodel'
end
```

Please let us know how we can disable eager loading of this has_many association. Or maybe there is another way to solve this problem.

Thanks
Alex & Josh

**Comment by ThomasTheFourth** [comment]
Thank you! I was looking everywhere for an answer to this problem.
