### ISSUE TITLE
is it possible to replace formtastic with simple_form ?

### ISSUE THREAD

**Issue by dfang** [activeadmin/activeadmin#3111]
i always use simple_form, never used formtastic, it would be great if active_admin depends on simple_form instead of formtastic, how much work for this ?

thanks !

**Comment by timoschilling** [comment]
There is no simple way to replace the FormBuilder, if some want to use a different one, feel free to create a PR with a FormBuilder Adapter.

**Comment by javierjulio** [comment]
@dfang were you able to fork and try it out? As a maintainer I'm very curious to know what you found out. It doesn't seem formtastic sees many updates and simple_form has. It has better features for customization or at least provide it in an easier way for a tool like ActiveAdmin to not conflict with a host app. I'm not a fan of formtastic but it does have a good DSL. It seem simple_form has a very similar one so its doable. Would love to know if you found out anything.
