### ISSUE TITLE
ActiveAdmin Inherited Everything From my Application Contrller

### ISSUE THREAD

**Issue by robertomiranda** [activeadmin/activeadmin#3143]
I need to be logged in the main site in order to access to the admin site

Since I have something like this

``` ruby
class ApplicationController <ActionController::Base
  before :authenticate_user!
end
```

Is really annoying this, I solved the issue creating another controller called `BaseController`

There's another way to solve this here?

ref https://github.com/josevalim/inherited_resources/pull/356

**Comment by awh-tokyo** [comment]
It would be lovely to open this again now that ActiveAdmin is maintaining Inherited Resources.  I find it ridiculous to have all these conditionals in my ApplicationController because I can't have an AdminController that ActiveAdmin controllers inherit from instead.
