### ISSUE TITLE
Forms should display validation errors added to :base

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#3160]
When you have a validation error that doesn't belong to any one attribute, the Rails convention is to add them to `:base`:

``` ruby
class User
  validate :name_or_email_is_present
  def name_or_email_is_present
    unless email.present? || first_name.present? && last_name.present?
      errors.add :base, "You must provide either a name or an email address."
    end
  end
end
```

AA should display these errors somewhere on the form so new devs aren't confused, and so once they do figure out what's happening they don't have to build their own custom solution.

**Comment by bchellingworth** [comment]
Anyone reading this in 2020. 
Add the following to your form decleration:

` f.semantic_errors`

You can read more here: [https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md](https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md)

**Comment by joeadcock** [comment]
> Anyone reading this in 2020. Add the following to your form decleration:
> 
> ` f.semantic_errors`
> 
> You can read more here: https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md

Not exactly related because my missing errors weren't on `:base`, but I found I found the mention of `f.semantic_errors(*f.object.errors.attribute_names)` at https://activeadmin.info/5-forms.html#displaying-errors to be especially helpful in my case, I had left a required attribute off of the form.
