### ISSUE TITLE
Release of version 1.0.0

### ISSUE THREAD

**Issue by RobWu** [activeadmin/activeadmin#3213]
Hej, 

When do you plan to release 1.0.0.
Would like to use rails 4.1 in production.

**Comment by emilebosch** [comment]
Reasons to make a gem:

- Commmunication, knowing what features we're running, bugfixes etc. General best practice for all the reasons everyone knows.
- Has been forerever in BETA, even though everyone probably runs it.
- Make it trackable for security vulnerabilities trough bundler-audit, and ruby security vulnerability db. 
- Every new install could potentially break the environment and introduce security vulnerabilities. No way to yank it. 

Please people, just build a gem, don'tm make it a a 1.0.0 if it isnt stable. but hey tons of people are using it. So please just let us track numbers and build gems already.

**Comment by timoschilling** [comment]
Which 'version' should that gem have be?

I think:
1. `1.0.0.preX` until we have all [millstones](https://github.com/activeadmin/activeadmin/milestones/1.0.0) closed
2. `1.0.0.betaX` until all major bugs are closed (not feature request bugs)
3. `1.0.X` after step 2.

**Comment by emilebosch** [comment]
Wow.  Lot of these milestones i wouldn’t even put into 1.0.0 tb. 

- Mogoid support? Why? separate it out in another gem
- Interactive AA installer? Nope
- Faster associated filters? Nope 
- Anything that doesn’t completely break the current API just put into 1.0.0. and be done with it.
- Paperclip? Just use carrier wave for now or separate it out. Cafrrierwave is now defacto anyway. 

Just remove anything which needs major refactoring and introduce that as a breaking change using sem-ver. Just
ship it already. Stable means stable. I.e nothing’s changing unless i upgrade my gem.

Ofcourse this is an arrogant way of putting it, but people can still fork it and give pull-requests. But the main repo not having
its own 1.0.0 gem is really unfortunate after all these years.

Also are you aware of semver.org? There are guidelines on how tot deal with this. Check this for instance:

How do I know when to release 1.0.0?

If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.

- Just consider a stripped down version 1.0.0
- All the fixes, features follow server guidelines. 

That maybe a good idea?

**Comment by timoschilling** [comment]
Not all millstones need to be done until `1.0.0`, but the bugs (I labeled them now).
- Mongoid support will not be a separate gem, while it will become a clean integration (for all other ORM's not only mongoid). Maybe later we have a new activeadmin-mongoid or activeadmin-rom, but first it's needs a clean interface in AA. But at all it can be come in a 2.0, if it stops the 1.0
- Interactive AA installer, sure can wait
- Faster associated filters, would be nice, but can wait
- Paperclip, that issue is a form bug in general and not really related to Paperclip, so it need's to be fixed

**Comment by timoschilling** [comment]
Maybe we revert @varyonic changes from #3486, this will reopen some issues, but allow us a stable (major bug free) release.

**Comment by timoschilling** [comment]
I think I start releasing `1.0.0.pre1` on rubygems today.

What should be the release cycle for the `pre` version?
- one each week
- or after each new feature
- or after each major bug fix

**Comment by fabn** [comment]
@timhabermaas it would be great to finally have a 1.0.0.pre1 release in rubygems, please do that. Most of us are using AA in production at its current version, so have the tag is a great improvement for us.

For the release cycle I'd say one after each major bug fix and after new (minor) features. just my two cents.

**Comment by varyonic** [comment]
If reverting #3486 gets us a gem release I am in favor.  I am not able to contribute further at this time.

**Comment by timoschilling** [comment]
I released `1.0.0pre1` right now!

**Comment by emilebosch** [comment]
🎉🎉

Verstuurd vanaf mijn iPhone
