### ISSUE TITLE
If I customize the form section, I still need to provide the permitted params option.. This is not DRY

### ISSUE THREAD

**Issue by ktaragorn** [activeadmin/activeadmin#3236]
Shouldnt a reasonable default be to extract the `permitted_params` form specification? Its uncommon to have other fields that might change.. would need entirely custom actions and pages, and they can specify the `permitted_params` manually..

**Comment by codyrobbins** [comment]
I’m not sure of his intended meaning, but I read @dmitry’s comment as supporting @ktaragorn’s original comment and not that this issue should be closed.

I agree with @ktaragorn that `permitted_params` should automatically be built from the fields that are specified on the form. In almost every ActiveAdmin project I’ve ever worked on I have a list of inputs on the form and then an exact duplicate of that list of attribute names being passed to `permit_params`. Keeping these two lists of what are effectively the same list of attribute names in sync is not DRY. These are all cases where there are only a small handful of trusted superadmins and there are no concerns about the security of the model.

Short of an ability to whitelist all params as discussed and discarded in #2875, I’ve taken to placing

```ruby
  controller do
    define_method(:permitted_params) do
      params.permit!
    end
  end
```

in every resource to sidestep the issue, but this kind of boilerplate is cumbersome.

Ideally the permitted params are automatically discovered via the inputs defined on the form, but a `permit_all_params` DSL method as originally discussed in #2875 would work too.

**Comment by dmitry** [comment]
@codyrobbins it could be good for some cases. In the projects I'm working, it's not the case, as in most of the cases I have roles or some exceptions, like building forms through the partial not the DSL, or passing attributes through the JS generated forms.
