### ISSUE TITLE
Make development reloading faster (and smarter)

### ISSUE THREAD

**Issue by dmitry** [activeadmin/activeadmin#3239]
Current reloading isn't very smart. I'm proposing to think how we can improve speed of the reloading on every request.
### Temporary solution

Temporary improvement of the speed, it doesn't reload's active_admin routes and resources/pages. Dumb but it works.

``` ruby
module ActiveAdmin
  module Reloader
    class Rails32Reloader
      def attach!
      end
    end
  end
end
```
### Related issues

https://github.com/gregbell/active_admin/issues/278
https://github.com/gregbell/active_admin/issues/170

**Comment by javierjulio** [comment]
Closing out as stale. We have a smaller PR to tackle not reloading routes twice. Be great to have smaller focused issues on improving load time.
