### ISSUE TITLE
customize default action links 

### ISSUE THREAD

**Issue by sachin87** [activeadmin/activeadmin#3259]
here is my code for some index view

``` ruby
index do
    selectable_column
    column :id
    column :title
    column :net_amount
    column :arrival_date
    column :departure_date
    column :site
    column :master_confirmation_code
    column :booking_status
    actions :defaults => [:show] do |booking|
      link_to 'Send Voucher', email_voucher_booking_path(booking.id), :remote=> true
    end
  end
```

here i don't want to remove destroy action but i don't want to show delete link, i just want to show 'view' and 'Send Voucher' link, can it be possible, right now its not working?

**Comment by wongmingrui** [comment]
why do i encounter this error when i try to disable the destroy controller action?

wrong number of arguments (2 for 0..1)
