### ISSUE TITLE
issue with country select

### ISSUE THREAD

**Issue by royzinn** [activeadmin/activeadmin#3279]
Hi,
I'm using the gem:
`gem 'activeadmin', github: 'gregbell/active_admin'`

and i'm trying to use the country select using the country_select gem. I have created the form:

``` haml
= semantic_form_for [:admin, @team] do |f|
  = f.inputs do
    = f.input :name
    = f.input :country, as: :country, priority_countries: ["IL", "ES", "GB", "FR"]
  = f.actions :commit
```

but I keep getting this error: `wrong number of arguments (4 for 1..3)` no matter what I do.
Any suggestions?
Thanks,
Roy

**Comment by abdullahtariqb** [comment]
I'm experiencing the same issue as described here.

My setup initially only included the country_select gem:

`gem "country_select", "~> 8.0"
`

Solution:
Adding the countries gem to my Gemfile and running bundle install resolved the problem:

`gem "countries", "~> 5.7"
`

My f.input configuration:
Here's how my country input field is configured, in case it's relevant:

```
f.input :country, as: :country,
          selected: "US",
          priority_countries: [ "US", "GB" ],
          except: [ "IL" ],
          prompt: "Select a Country"
```
