### ISSUE TITLE
Roadmap ideas

### ISSUE THREAD

**Issue by dmitry** [activeadmin/activeadmin#3282]
I'm very interested in participating the active_admin development actively. Is it possible somehow? The reason, almost all the projects I'm working on using the activeadmin gem, so I really want to contribute and make admin panel better. But current situation with long PR acceptance stops me from sending more patches. 

What I have in my mind so far in my own roadmap:
- Range input filter

![bookings 9flats](https://cloud.githubusercontent.com/assets/5091/3605116/e1c39a78-0d27-11e4-9cad-3b544db7095a.png)
- Ability to add associations right from the form or index pages

![out](https://cloud.githubusercontent.com/assets/5091/3605081/8f70234a-0d27-11e4-92dd-3280b5eb20aa.gif)
- Diagonal index column headers

![dxgangledheaderscomplete_2](https://cloud.githubusercontent.com/assets/5091/3605080/8e8632d0-0d27-11e4-958b-5ca37224e765.png)

(https://css-tricks.com/rotated-table-column-headers/)
- Extend routes support
- Improve performance of reloading on each request

**Comment by varyonic** [comment]
I'm closing this as stale.  Feel free to open separate issues.
