### ISSUE TITLE
It is impossible to use "semantic_fields_for" inside "has_many"

### ISSUE THREAD

**Issue by bioform** [activeadmin/activeadmin#3285]
I have the following models:

```
class Profile < ActiveRecord::Base
  has_many :projects, dependent: :destroy

  accepts_nested_attributes_for :projects, allow_destroy: true
  validates_associated :projects 
end

class Project < ActiveRecord::Base
  belongs_to :profile
  belongs_to :cover_image, class_name: "Image", foreign_key: "cover_image_id"

  accepts_nested_attributes_for :cover_image, allow_destroy: true
  validates_associated :cover_image
end

class Image < ActiveRecord::Base
  validates :title, presence: true
end
```

AA doesn't render "Image.title" field for the following form:

```
  form html: { enctype: "multipart/form-data" } do |f|
    f.semantic_errors
    f.inputs "Profile" do

    f.inputs "Projects" do
      f.has_many :projects, allow_destroy: true do |g|

        g.semantic_fields_for :cover_image, g.object.cover_image || g.object.build_cover_image do |ci|
          ci.input :title
        end

        g.input :name, input_html: { maxlength: 300 }
      end
    end

    f.actions
  end
```

"Project.name" field renders OK

**Comment by jtomaszewski** [comment]
I had the same problem. If I use `semantic_form_for` inside the `has_many` relation, it doesn't render any inputs. If the same code was used without the `has_many` relation, it worked.

Solution: use `template.concat` before `ff.semantic_form_for`.
Example:

```rb
    f.inputs "Projects" do
      f.has_many :projects, allow_destroy: true do |g|

        template.concat g.semantic_fields_for :cover_image, g.object.cover_image || g.object.build_cover_image do |ci|
          ci.input :title
        end

        g.input :name, input_html: { maxlength: 300 }
      end
    end
```

**Comment by alekseyl** [comment]
Thanks for idea! Little remark to your solution:
instead of 

`template.concat ...`

must be

`g.template.concat`

pure call without 'g.' brings some #Class junk to form

**Comment by richpeck** [comment]
This is still an issue and the `.conact` method no longer seems to work - does anyone have any solutions?

**Comment by bioform** [comment]
all provided way looks ugly.
`ci.input :title` without `g.template.concat` before `g.semantic_fields_for` looks much better 😄 
But it is clear that for most people such king of `workaround` is suitable.

**Comment by richpeck** [comment]
What's your full code please? The only way I got it to work was with a partial (which is worse).

**Comment by bioform** [comment]
@richpeck, see the issue description 😄

**Comment by bioform** [comment]
I meant that it is a bug and it should be fixed
