### ISSUE TITLE
Master Branch: Kaminari  vs Will_paginate errors

### ISSUE THREAD

**Issue by Rio517** [activeadmin/activeadmin#330]
Hey,

With the new master branch migrating to kamari, will_paginate is now incompatible, leading to errors such as this.  Perhaps we could support both  will_paginate or kaminari.

`undefined local variable or method 'per' for #<ActiveRecord::Relation:0xa0bbc74>`

relevant commit:   https://github.com/gregbell/active_admin/commit/96a0cfa25fb3bcb0be7e4b7121b627cce6f7b960#lib/active_admin/resource_controller/collection.rb

-Mario

**Comment by gautamevontech** [comment]
#Its working for me
if defined?(WillPaginate)
  module WillPaginate
    module ActiveRecord
      module RelationMethods
        def per(value = nil) per_page(value) end
        def total_count() count end
      end
    end
    module CollectionMethods
      alias_method :num_pages, :total_pages
    end
  end
end
