### ISSUE TITLE
register as does not change the text for submit button

### ISSUE THREAD

**Issue by keating** [activeadmin/activeadmin#3321]
I am using 0.6.1

```
ActiveAdmin.register AdminUser, as: 'Sub Investor' do
```

![screen shot 2014-08-09 at 2 03 00 am](https://cloud.githubusercontent.com/assets/271395/3860633/417b1490-1f26-11e4-8602-24aafcab132e.png)

It should be `Update Sub Investor`

**Comment by ShPakvel** [comment]
@timoschilling Model as wrapper approach doesn't work with associations, at least in one of my project with autocomplete for association.
