### ISSUE TITLE
active_admin_form_for duplicates output when using Rails 3 style erb tags

### ISSUE THREAD

**Issue by danxexe** [activeadmin/activeadmin#333]
ActiveAdmin::FormBuilder generates multiple output when using Rails 3 erb content tags like in the following:

```
<%= f.inputs do %>
  <%= f.input :email %>
<% end %>
```

One possible solution is using Rails 3 capture helper on the ActiveAdmin::FormBuilder methods, but I haven`t thought about how to concatenate the output when using the DSL.

**Comment by glampr** [comment]
Just a hacky solution, but someone might find it useful to hide duplication inside a ```has_many``` in an .erb partial.
Since it's an erb partial, you can append a small JavaScript snippet that will hide/delete the redundant fields.
```html
<script type="text/javascript">
  $('.inputs.has_many_fields > ol li:nth-child(even)').hide();
</script>
```
or
```html
<script type="text/javascript">
  $('.inputs.has_many_fields > ol li:nth-child(even)').remove();
</script>
```
