### ISSUE TITLE
Rails 4.2 compatibility

### ISSUE THREAD

**Issue by jamilabreu** [activeadmin/activeadmin#3346]
Getting the following on Rails 4.2 beta clean install:
`/gems/inherited_resources-1.4.1/lib/inherited_resources/responder.rb:2:in '<module:InheritedResources>': cannot load such file -- action_controller/metal/responder (LoadError)`

**Comment by preston** [comment]
Does anyone happen to have a migration guide for general Rails 4.2 projects needing to address this prior to Rails 5? There are a ton of projects that will fall into this boat.

**Comment by timoschilling** [comment]
@preston The Rails 4.2 thinks are in the Readme. Or what do you mean?

**Comment by preston** [comment]
Was just hoping someone had a more detailed guide or gem to assist in migrating off of inherited_resources. Oh well.

**Comment by timoschilling** [comment]
I think there is no and will be no drop in solution to replace inherited_resources

**Comment by timoschilling** [comment]
Maybe someone will continue the development of inherited_resources. //cc @rafaelfranca
