### ISSUE TITLE
AdminLTE Theme anyone?

### ISSUE THREAD

**Issue by rdsubhas** [activeadmin/activeadmin#3347]
ActiveAdmin is great. But it sucks at UI. [AdminLTE](https://github.com/almasaeed2010/AdminLTE) hits the spot right on - its an Admin-focused Bootstrap derivative, and would make a perfect match for ActiveAdmin.

So how about ActiveAdmin+AdminLTE?

**Comment by jimmyn** [comment]
I've found this https://github.com/barock19/activeadmin-lte, but I couldn't implement it completely, too many errors.

**Comment by halilim** [comment]
+1 for this. AdminLTE is an awesome Bootstrap admin theme with a permissive license (MIT) that would make the default Active Admin look beautiful too if implemented. Actually I'm dreaming of starting a pull request for this quite a while, as soon as I have some time.

Though it looks like we need to wait on #3862 and #1027 (if reopened) before this. Moving to Bootstrap would open the doors of a whole different world with Bootstrap themes, Bootstrap plugins etc.

**Comment by quangtt** [comment]
@jimmyn Hi! How did you implement that gem? The author didn't say anything...Thank you!

**Comment by jimmyn** [comment]
@quangtt I didn't actually. I did my own theme https://github.com/jimmyn/active_admin_theme. It worked for me. It was a long time ago so It's terribly outdated.

**Comment by quangtt** [comment]
@jimmyn Your theme is a good one :+1: 
I'm still trying to make activeadmin-lte work, but no luck, cause I really need it (AdminLTE + ActiveAdmin).

**Comment by quangtt** [comment]
Everyone, there is a repo here forked from @barock19's one. At least it works! But there are many bugs still there. Can we help him?
https://github.com/CapSens/activeadmin-lte

**Comment by varyonic** [comment]
In response to #3862 I have started collecting and reviewing all the themes I can find [on the wiki](https://github.com/activeadmin/activeadmin/wiki/Themes)  I like the plugin approach in combination with #3392.  I propose closing this.

**Comment by rdsubhas** [comment]
Closing as its been documented and #3392 is in progress. Thanks!
