### ISSUE TITLE
conflict css class '.dropdown_menu' using bootstrap

### ISSUE THREAD

**Issue by sanchojaf** [activeadmin/activeadmin#3351]
Hi I am using activeadmin and bootstrap like framework css

then I have an issue with 'dropdown_menu' css class

in lib/dropdown-menu.js.coffee

$('.dropdown_menu').aaDropdownMenu()

[Error] TypeError: 'undefined' is not a function (evaluating '$('.dropdown_menu').aaDropdownMenu()')
    (anonymous function) (dropdown-menu.js, line 120)
    fire (jquery.js, line 3120)
    fireWith (jquery.js, line 3232)
    ready (jquery.js, line 3444)
    completed (jquery.js, line 3475)

**Comment by rajesh-zuu** [comment]
@timoschilling  I am having same error pattern as @sanchojaf , and yes i use bootstrap for frontend not in ActiveAdmin

**Comment by duet-ngyen** [comment]
remove require tree and require active_admin.js at the last

//= require jquery
//= require jquery_ujs
//= require turbolinks
...
//= require active_admin.js
