### ISSUE TITLE
Ability to change labels in show -> attributes_table

### ISSUE THREAD

**Issue by ownadi** [activeadmin/activeadmin#3359]
Is it possible?

**Comment by edatrix** [comment]
glad that this ability exists, but it's frustrating that the syntax is different when customizing labels on the index v. the form v. the show page.  

It also took me a while to find this, you should add to the docs on the show page info :)

**Comment by timoschilling** [comment]
@edatrix why is there a difference?

```ruby
    attributes_table do
      row('Renamed'){ |r| r.username }
    end

    attributes_table do
      row 'Renamed' do |r|
        r.username
      end
    end
```

That is just a other ruby code style.

**Comment by edatrix** [comment]
@timoschilling that's not what I meant, what i mean is that here (in the attributes table) you have to override the default with ruby.  When adjusting labels for the index or on the form, it's easy to just pass in a label.  It would be convenient if it were consistent across all ActiveAdmin elements, preferably by just passing the string.

examples:

```ruby
index do
    column :category
    column "This is the name of the columnl", :column_label
    column "Another Label", :another_label
end
```

```ruby
form do |f|
    f.input :column_label, :label => "This is the name of the column"
end
```

**Comment by timoschilling** [comment]
@edatrix someware is already a discussion about that, but I can't find it at the moment.

**Comment by michon** [comment]
row("label_row){table.field}

I think it's correct, at least work fine for me.

**Comment by gerryhd** [comment]
Is this feature available now? Because it would be quite useful, and not including it makes for some confusing inconsistency with the implementation of attributes in general. Inputs have it, columns have it, filters have it, is there a reason for rows to not have it?

**Comment by AlexVentura** [comment]
Yeah as @edatrix said, there should be consistency doing this simple customization in all AA or at least in `show`, `index` and `form` page.

**Comment by danielricecodes** [comment]
This doesn't take into account if you're using `decorates_with`.  I just want to change the row label, but I still want to use a decorator to present the row.  If you use the block syntax to provide a label, the decorator is ignored.

**Comment by malaimo** [comment]
+1 for this feature.

**Comment by cristi** [comment]
+1 for this feature

Meanwhile, in newer versions  of Ruby, I'm using
```
row 'Timestamp', &:created_at
```
but would still like to see consistency here

**Comment by Altons** [comment]
> +1 for this feature
> 
> Meanwhile, in newer versions of Ruby, I'm using
> 
> ```
> row 'Timestamp', &:created_at
> ```
> 
> but would still like to see consistency here
Just want to highlight that this trick does not work for `attributes_table_for`

**Comment by BishalMukherjee** [comment]
Is there any way to make the label in uppercase in the show page. Actually I want to do something like this 
```
row("GST Registered") {
  r.gst_registered
}
```
But it doesn't work, it's only making the words start capital.

**Comment by cristi** [comment]
> Is there any way to make the label in uppercase in the show page? Actually I want to do something like this
> 
> ```
> row("GST Registered") {
>   r.gst_registered
> }
> ```
> 
> But it doesn't work, it's only making the words start with capital.

You need to pass a block, try something like:

```ruby
row('GST Registered') { |r| r.gst_registered }
```

or

```ruby
row 'GST Registered' &:gst_registered
```

**Comment by BishalMukherjee** [comment]
@cristi I tried that too. But it isn't working.

**Comment by javierjulio** [comment]
@BishalMukherjee I believe this is similar to what I've run into. For most of these fields, if supported, ActiveAdmin will use the `human_attribute_name` method [(rails docs source)](https://api.rubyonrails.org/classes/ActiveModel/Translation.html#method-i-human_attribute_name) which also changes the case. You should be able to address the issue by specifying the field in the locale. So as an example, if `gst_registered` is a field on a `User` model, I'd have the following in my locale to get the right casing to display:

```yaml
en:
  activerecord:
    attributes:
      user:
        gst_registered: "GST Registered"
```

I've done this often as I have tables with `provider` and `provider_id` columns which for the latter, the `human_attribute_name` method will not include the "Id" suffix in the output.

**Comment by BishalMukherjee** [comment]
@javierjulio Thanks. It worked.

**Comment by danielricecodes** [comment]
> @BishalMukherjee I believe this is similar to what I've run into. For most of these fields, if supported, ActiveAdmin will use the `human_attribute_name` method [(rails docs source)](https://api.rubyonrails.org/classes/ActiveModel/Translation.html#method-i-human_attribute_name) which also changes the case. You should be able to address the issue by specifying the field in the locale. So as an example, if `gst_registered` is a field on a `User` model, I'd have the following in my locale to get the right casing to display:
> 
> ```yaml
> en:
>   activerecord:
>     attributes:
>       user:
>         gst_registered: "GST Registered"
> ```
> 
> I've done this often as I have tables with `provider` and `provider_id` columns. For the latter, the `human_attribute_name` method will just return "Provider" as the output but "Provider Id" is desired so the locale is updated to correct that.
> 
> ```
> >> User.human_attribute_name(:provider_id)
> => "Provider"
> ```

This doesn't work with non-ActiveRecord objects.  

This issue has been ongoing for so long I may take a crack at it....

`column` has a `label` option.  forms have it.  Filters have it.  `row` should have it also.

**Comment by danielricecodes** [comment]
This issue has been ongoing for so long I may take a crack at it....

`column` has a `label` option.  forms have it.  Filters have it.  `row` should have it also.

**Comment by Souhardya1204** [comment]
```row "DCT Purchase", &:dct_purchase_document``` here while displaying it is displayed as   ```Dct Purchase```.  How can I keep it upcase ?

**Comment by dixonnataliej** [comment]
I also think there is still an issue where you're unable to override human_attribute_name to get the desired capitalization in show attributes_table. In **index**, `column "Registration ID", :registration_id` displays correctly as `Registration ID`, but in **show**, `row("Registration ID"){|s| s.registration_id}` displays incorrectly as "Registration Id" without the capital "D". I've tried several different syntax options, labels, changing the locale file, still won't capitalize correctly.

 In the same vein, the display adds spaces between consecutive capital letters if there is more text that follows, ex `row("Registration IDe Test"){|s| s.registration_id}` displays as `Registration I De Test`
