### ISSUE TITLE
config.register_stylesheet doesn't work for Namespaces

### ISSUE THREAD

**Issue by hakunin** [activeadmin/activeadmin#3362]
Hi,
the documentation says:

    Each setting available in the Active Admin setup block
    is configurable on a per namespace basis.

but when I tried this for css file:
`````
  config.namespace :hosted do |hosted|
    hosted.site_title = "TechFest"
    hosted.register_stylesheet 'hosted_admin.css'
  end
````
I get a missing method error for `register_stylesheet`, while on the root `config` it works fine.

**Comment by rafaelparra** [comment]
@hakunin Were you able to apply specific stylesheet to a namespace? can you please share how did you do this?

**Comment by hakunin** [comment]
I discarded the idea of using AA for tha part of my app. I needed to be able to work fast and have control over everything.

**Comment by seanlinsley** [comment]
If someone in the future comes across this ticket, we're open to a PR, but this isn't high priority so I'm closing the ticket.
