### ISSUE TITLE
Response to Inherited Resources being deprecated

### ISSUE THREAD

**Issue by brianjlandau** [activeadmin/activeadmin#3370]
With [Inherited Resources being deprecated](https://github.com/josevalim/inherited_resources#deprecation-notice) a decision needs to be made. Seems like the 2 options are:
1. Switch to not using Inherited Resources
2. ActiveAdmin team takes on maintaing Inherited Resources

**Comment by reicheltd** [comment]
@benjamin-thomas "Personally I find the gem irritating to use". same here. Since I started to use AA, in my cases I had to look up IR docs to see if any issues are related to this. I dont want/need a magically dry controller, where you always have in mind there is a another gem behind this.

**Comment by benjamin-thomas** [comment]
Yeah for anyone upgrading to rails 4.2 you may need to update your Gemfile as such.

```ruby
gem 'inherited_resources', github: 'josevalim/inherited_resources', branch: 'rails-4-2'
```

There doesn't seem to be any progress on this and I don't have time (or maybe the skills) to look at the code (unfortunately) at the moment, but ideally I'd be great if we could at least opt out of this feature.

**Comment by mathieujobin** [comment]
does not look like that rails 4.2 branch still exist?
could anyone update this thread with newest info on how to integrate active_admin within a rails 4.2 app ?

thanks

**Comment by timoschilling** [comment]
For Rails 4.2 you need the activeadmin master and the inherited_resources master or gem >= 1.6.

**Comment by mathieujobin** [comment]
:+1: thank you !

**Comment by dgtm** [comment]
I am using master of both activeadmin and inherited_resources and still getting the same error
