### ISSUE TITLE
Patch Proposal: A more easily customizable theme

### ISSUE THREAD

**Issue by caleb** [activeadmin/activeadmin#3392]
I am using ActiveAdmin in a project where I have customized the default appearance, and found that in a lot of cases I had to override a lot of CSS declarations to do basic customizations.

I am interested in putting some work into AA to make the default theme more customizable through variables.

Specific pain points I ran into were:
- removing gradients
- removing shadows
- removing outlines
- removing text shadows
- tweaking border radiuses
- customizing built in components (the #header, tables, etc)

My goal would be to allow basic tweaking with a small set of base variables, but allow more fine grained control with more specific variables (like frameworks like Bootstrap do).

I also thought of adding some classes to the default actions. So for example, the "New" button might get a `new-button` class that would let you style that button separately, but this could be saved for another patch.

Would this be something that you would be interested in accepting?

**Comment by javierjulio** [comment]
Anyone working on this? We use activeadmin and would like to update it to match our app theme. If no one is working on this mind if I try my hand at contributing a solution? If someone is tackling, I would love to help out and contribute.

**Comment by javierjulio** [comment]
Obviously redoing this would be a major effort but some thoughts on how to transition to a new setup keeping in mind that with smaller tasks will help to get more familiar with the CSS as a whole. Let me know what you think.

* Remove excessive heavy styles to simplify CSS (shadows, gradients, etc.)
* Take a component variable based approach like Bootstrap with smaller components at first (e.g. status_tag) and see where we can expand from there
* Review some CSS frameworks we could use (Bootstrap, Semantic UI, etc.) possibly?

**Comment by javierjulio** [comment]
@seanlinsley @timoschilling @caleb not to be pushy but I've been working on this today and would love to contribute here. If you don't think anyone is handling this area I'd love to tackle this as I feel I'd be able to help significantly. I can create a pull request with what I intend to do and see if others would like to assist. This area of ActiveAdmin could really use a complete revamp. Modifying styles is currently very painful without specifying very long selectors and sometimes when its completely unnecessary e.g. one selector has 3 id's 😩.

**Comment by timoschilling** [comment]
@javierjulio go for it

**Comment by msaspence** [comment]
@javierjulio did you get anywhere with this?

**Comment by javierjulio** [comment]
@msaspence I sure did! Its a complete overhaul of the ActiveAdmin CSS but its just a first step. All this does is simplify and modernize the CSS thus making it much easier to edit. I've fixed majority of the pain points listed in the original post. I've always been running ActiveAdmin off master (not sure if you are but hopefully yes) and you if point to my branch its probably off by just a few commits: https://github.com/activeadmin/activeadmin/pull/3862 Keep in mind this is a CSS overhaul so I'd clear out any custom styles you have and copy over AA variables (there are many now and better organized). From there run the admin and see how things look. Would love to know how it worked out for you and problems/errors you ran into.

**Comment by javierjulio** [comment]
Closing this out as everything listed in the description is already handled by #3862 which is also set for 2.0.
