### ISSUE TITLE
switch from svg icons to Font Awesome

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3399]
I would prefer a switch from the ~140 [svg icons](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/iconic/icons.rb) to the ~550 [Font-Awesome](http://fortawesome.github.io/Font-Awesome/cheatsheet/) icons.

One other reason is that svg is not colorable from css, Font-Awesome is that!
For example I work on a Icon in Flash messages, but coloring for svg smells:
```ruby
        def build_flash_messages
          div class: 'flashes' do
            flash.each do |type, message|
              div class: "flash flash_#{type}" do
                color = case type
                when :error
                  "#b33c33"
                when :notice
                  "#416347"
                end
                span Iconic.icon :x_alt, color
                span message
              end
            end
          end
        end
```

Font coloring works out of the box

**Comment by sepastian** [comment]
+1 for font awesome

**Comment by timoschilling** [comment]
closed by #3553

**Comment by Fivell** [comment]
@timoschilling , sorry but not very clean for me,  how to use new icons? should I add  gem font-awesome-rails to Gemfile or active_admin  has it as dependency ?

**Comment by yoyos** [comment]
Same question.

Something like that ? How to implement it ?

```
actions defaults: false do |p|
      links = '<span class="default_actions"> '.html_safe
      links += link_to '<i class="fa fa-camera-retro fa-lg"></i>'.html_safe, edit_admin_user_path(p), :title =>  'my title'      
      links += '</span>'.html_safe
      links
    end
```

**Comment by timoschilling** [comment]
We haven't switched to Font Awesome, but we have removed the Icon support, thats why I closed this issue. // cc @Fivell

**Comment by timoschilling** [comment]
I have a idea for a new gem `font-awesome-i18n`, where you can do things like:
```yaml
en:
  edit: "{{edit}}"
```
Which is rendered as:
```
<i class="fa fa-edit"></i>
```

**Comment by yoyos** [comment]
Good idea :)

**Comment by terry90** [comment]
+1
