### ISSUE TITLE
Adding custom javascript 

### ISSUE THREAD

**Issue by tobyhede** [activeadmin/activeadmin#340]
I was wondering if there was a mechanism for adding custom javascript to the admin UI? 
Was thinking it might be a useful way of injecting features without requiring massive updates of the ruby code?

An example would be adding a plugin like jquery chosen [http://harvesthq.github.com/chosen/] to enhance certain filters and drop downs on forms.

**Comment by ivanyv** [comment]
My hack to add scripts at the top (added at the top of the ActiveAdmin initializer):

```ruby
Rails.application.config.after_initialize do
  javascripts = [] 
  javascripts << "//maps.googleapis.com/maps/api/js?sensor=false&key="
  javascripts += ActiveAdmin.application.javascripts.to_a
  ActiveAdmin.application.javascripts.replace javascripts
end
```

**Comment by serradura** [comment]
@ivanyv You can do this too.

Add in your config/initializers/active_admin.rb.

```ruby
ActiveAdmin.setup do |config|

  config.register_stylesheet "//cdn.foo.net/example.css"

  config.register_javascript "//cdn.foo.net/example.js"
  
  # ...
end
```

**Comment by ivanyv** [comment]
@serradura Yeah but that appends the scripts at the bottom and some scripts I need at the top.

**Comment by serradura** [comment]
@ivanyv I understood now. Thanks for sharing! :smile:

**Comment by workgena** [comment]
My solution to load additional JS before closing </body> tag, for each controller:

Create file /lib/active_admin/views/footer.rb

```ruby
module ActiveAdmin
  module Views
    class Footer < Component

      private

      def powered_by_message
        para I18n.t('active_admin.powered_by', active_admin: link_to("Active Admin", "http://www.activeadmin.info"), version: ActiveAdmin::VERSION).html_safe

        if MyApplicationName::Application.assets.find_asset("ui/#{params[:controller]}.js")
          render text: javascript_include_tag("ui/#{params[:controller]}")
        end
      end

    end
  end
end
```

This will patch AA-view with our code. It includes JS-file it it exists.

For example we have controller /app/admin/customer.rb
```ruby
ActiveAdmin.register Customer, as: 'Customer' do
  # ...
end
```

Then create relevant JS-file:
/app/assets/javascripts/ui/admin/customers.js

```ruby
alert('controller_name is: admin/customers');
```

This works in development mode. 

To get this work in production you need:
1. in application.js and active_admin.js not to use "require_tree ." (IMPORTANT)
2. /config/environments/production.rb add this

```ruby
config.assets.precompile += %w(ui/admin/*.js)
```

And compile assets with:
``` RAILS_ENV=production bundle exec rake assets:precompile ```

**Comment by jtomaszewski** [comment]
My solution:

```rb

ActiveAdmin::Views::Pages::Base.class_eval do
  def build_active_admin_head_with_js_script
    build_active_admin_head_without_js_script
    add_js_config_to_head
  end

  def add_js_config_to_head
    within @head do
      script """
      I18n = window.I18n || {};
      I18n.defaultLocale = \"en\";
      I18n.locale = \"#{I18n.locale}\";
      """.html_safe
    end
  end

  alias_method_chain :build_active_admin_head, :js_script
end
```

**Comment by yaaase** [comment]
Since config.register_javascript now appears deprecated, is there a prescribed mechanism for including an external JS? Specifically google maps, with a key.

**Comment by dchersey** [comment]
I think you may be able to use arbre script tags to link in the google map scripts, and initialize. 

for example 
```ruby
    script src: 'url for google maps'
```
and for inline initialization
```ruby
    script do
      raw '$(document).ready(function($) {console.log("insert page initialization code here");})'
    end
```

**Comment by rivella50** [comment]
And if you need to use ruby variables in the script part switch the quotation marks:
```
script do
    raw "$('.link-delete').bind('ajax:complete', function() {
      $('#content').load('#{customer_id}/customer_data');
    });"
end
```

**Comment by davidwparker** [comment]
Is there a way to add JS per namespace?

**Comment by Ritesh-Katare** [comment]
@dchersey @rivella50 Thanks for inline js stuff,
Could you please help to append html element from inline js in active admin with "script" helper?

**Comment by theangular** [comment]
https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api
