### ISSUE TITLE
work with devise invitable

### ISSUE THREAD

**Issue by peterwongpp** [activeadmin/activeadmin#344]
We are currently using Devise Invitable gem (https://github.com/scambra/devise_invitable) which is used to integrate with devise providing the ability to invite the others by email.

I would like to know if active_admin could work with the gem? If so, how could I set it up?

The best solution I could think of is that there are 2 forms for the User model, one for updating the user's fields, another one has email field only for inviting the user.

Thank you for your help.

**Comment by alexandrecardinal** [comment]
I had to change params[:user] in the user creation for permitted_params[:user] in order for it to work

**Comment by chrisgeek** [comment]
I followed the sample code and the invitation is sent and delivered via email, but this is only half the task, how then do i customize the  accept_invitation_path in active admin too

**Comment by EdgarB** [comment]
More than 10 years laters and this is still relevant and useful.
Thank you.

**Comment by jacob-hedengren** [comment]
Hello, could anyone be so kind and help out with the complete steps? Can't find a single resource online with a sufficient level of guidance. Thanks a million times!
