### ISSUE TITLE
Translation not possible with default batch actions modal dialog 

### ISSUE THREAD

**Issue by nudzg** [activeadmin/activeadmin#3445]
Seems like there's no good way to translate texts "OK" and "Cancel" of modal dialog that shows when using default batch delete action. 

Last lines of app/assets/javascript/active_admin/lib/modal_dialog.js.coffee:

<pre lang="coffeescript"><code>
  $(html).appendTo('body').dialog
    modal: true
    dialogClass: 'active_admin_dialog'
    buttons:
      OK: ->
        callback $(@).serializeObject()
        $(@).dialog('close')
      Cancel: ->
        $(@).dialog('close').remove()
</code>
</pre>

"OK" and "Cancel" strings should be translatable with some entry on config/locales/*.yml

**Comment by waclock** [comment]
any updates on this?

**Comment by mrzou** [comment]
``` 
$('body').on('modal_dialog:after_open', function() {
    $("button:contains('OK')").text('确定');
    $("button:contains('Cancel')").text('取消');
  })
```

**Comment by javierjulio** [comment]
I would accept a PR for improving this. Thank you.
