### ISSUE TITLE
Could you release a pre version of AA 1.0.0?

### ISSUE THREAD

**Issue by fabn** [activeadmin/activeadmin#3448]
I understand that there is a [milestone page](https://github.com/activeadmin/activeadmin/issues?milestone=18) for relase 1.0.0 and that there is some work to finish before releasing the final version of the gem, but imho it would be nice to have a pre version available in Rubygems for a lot of reasons.

Some examples:
- Dependent gems/plugins which rely on AA can lock their requirements (I forked a [plugin](https://github.com/fabn/activeadmin-globalize) which relies on AA internals and it keeps crashing when AA is updated)
- Allow production code to not rely on github gems. I know that bundler will take care of this, but it would be nice to have some tagged version without specifing refs in Gemfile.
- For the same reasons one could write its components/filters/whatever for a given AA version and reuse them across projects.

So my question is could you tag and release some alpha/beta/pre/whatever version of ActiveAdmin?

Thanks.

**Comment by jaredbeck** [comment]
> It'd be nice to lock to a specific version instead of a specific commit.

`1.0.0.pre1` was released 2015-03-12.  @seanlinsley is this the recommended version for rails 4 apps?
