### ISSUE TITLE
css issue: input field width; wraps beneath label

### ISSUE THREAD

**Issue by glaszig** [activeadmin/activeadmin#3450]
i'm on the master branch and suffer this one:

![bildschirmfoto 2014-09-23 um 17 41 10](https://cloud.githubusercontent.com/assets/201135/4374965/54182ee0-4338-11e4-87a4-3b71a914a1ef.png)

with any viewport width inputs will wrap beneath the label. anybody else experiencing this?

**Comment by varyonic** [comment]
I’m going to close this since no-one else responded. Please feel free to update this issue with additional information so it can be reconsidered.
