### ISSUE TITLE
don't use !important in SVG color mixin

### ISSUE THREAD

**Issue by yoyos** [activeadmin/activeadmin#3451]
Hello, this commit made a color bug in my ActiveAdmin UI: https://github.com/activeadmin/activeadmin/commit/930d34cd224272687613dcf1db4cf5b1347f1098

Are you sure !important wasn't important for something ^^ ?
I didn't put any custom css, here what I have:

![ActiveAdmin UI](https://cloud.githubusercontent.com/assets/1993859/4389901/212a866a-43f9-11e4-8f68-01f5e36f583d.png)

**Comment by timoschilling** [comment]
closed by #3553
