### ISSUE TITLE
Why is the export to CSV file limited to 10K items?

### ISSUE THREAD

**Issue by amokranesub** [activeadmin/activeadmin#346]
Hi, 

Thanks for providing the community with such a great tool! I have one issue here regarding CSV generation, typically it's impossible to generate more than 10K items. 

Is there anyway to configure this without modifying the code?

Thanks!

**Comment by fabrouy** [comment]
Just a little comment. If you run into issues with devise try renaming the initializer's filename with a "z" at the begining so it gets loaded after devise initializer.

# config/initializers/z_active_admin_csv_override.rb
