### ISSUE TITLE
Redirect (globall)y to index page after create or edit action

### ISSUE THREAD

**Issue by cpfarher** [activeadmin/activeadmin#3468]
Is it possible to redirect after "create or edit action" in any controller to "index" page, instead of redirect to "show" page?

I would like to change de behaviour globally instead per controller.....
Thank you...

**Comment by vaibhavmalik** [comment]
How to do the same just for single active admin page?

**Comment by wspurgin** [comment]
You can simply add that code inside the `create` and `update` methods the admin `controller block like so:

```ruby
ActiveAdmin.register AdminUser do
  permit_params :email, :password, :password_confirmation

  controller do

    def create
      create! do |success, failure|
        success.html { redirect_to collection_url }
      end
    end

    def update
      update! do |success, failure|
        success.html { redirect_to collection_url }
      end
    end
  end

end

```

The only difference is wrapping the `update!` and `create!` blocks in their respective controller methods (e.g. `create` and `update`).
