### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3498]
This a new version for #614, to get some attention/feedback on it.

I will build keyboard shortcuts for ActiveAdmin, with [`jwerty`](https://github.com/keithamus/jwerty).

Now I have 3 question to the community:
1. jwerty or something else?
2. What should all have a keyboard shortcut?
3. Should we use [Github](https://help.github.com/articles/using-keyboard-shortcuts/) style shortcuts or should we use Modifiers (STRG/CMD, OPTION/ALT, ...)?

And there should be a Cheat like Github has:
![issues_ _activeadmin_activeadmin](https://cloud.githubusercontent.com/assets/165599/4689200/648d4792-56ac-11e4-946f-9ec668c66e38.jpg)

Any other features?

Functions from the comments and me:
- [ ] focus to filter
  - [ ] first
  - [ ] each
- [ ] dashboard
- [ ] menu
  - [ ] focus
  - [ ] navigation
  - [ ] shortcuts for entries
- [ ] index table
  - [ ] first row
  - [ ] navigation
  - [ ] actions on the row
- [ ] action_items

**Comment by adisos** [comment]
I'd like to have shortcut for saving/updating models
