### ISSUE TITLE
we should add documentation for view_factory customizing

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3517]
see https://github.com/activeadmin/activeadmin/issues/2808#issuecomment-60476695, #554 for example

**Comment by grimmwerks** [comment]
Yeah would love this as I'm trying to change the view factory.blank_slate for a resource like the original question; if I do it in the index as self.view_factory.blank_slate=HippaBlankSlate it of course ONLY happens after that index is drawn; can't figure out how to do it in the resource itself.

**Comment by varyonic** [comment]
@grimmwerks Consider a [custom index](https://www.activeadmin.info/3-index-pages/custom-index.html) instead

**Comment by grimmwerks** [comment]
@varyonic I do have a custom index; are you able to change the blank slate within the custom index?  It's unclear to me that you can.  Is it something that's always there but obscurred by the table if there is a collection?

**Comment by varyonic** [comment]
I would think a custom index would be enough.  I don't think modifying factories inside the index is a good design.  Either way I think design decisions for your application is off topic for this issue.  'Normal' usage to be documented would be just to override the default view_factories in an application initializer.
