### ISSUE TITLE
Update / replace activeadmin.info

### ISSUE THREAD

**Issue by varyonic** [activeadmin/activeadmin#3521]
I scraped the old site, converted it to GitHub pages and merged the most recent docs (not including the documentation front page which is missing from master).  You can browse the site at www.activeadmin.org and the source code at https://github.com/varyonic/activeadmin/tree/gh-pages.  I would like to know if you are willing to accept a pull request for this (after I fix documentation.md).  To do so you would need to create an empty, orphaned branch as discussed at https://help.github.com/articles/creating-project-pages-manually/

The great advantage of GitHub pages in my opinion is that changes committed to the gh-pages branch get published automatically with no additional effort: simpler than maintaining a separate project to publish on Heroku.

If Greg is not responsive with updating the DNS entry for activeadmin.info I am happy to point activeadmin.org at the GitHub pages for activeadmin/activeadmin.

See also #3515, #3443, #3436, #3249

**Comment by timoschilling** [comment]
I have now the DNS and will redirect activeadmin.info to the [activeadmin/activeadmin.info](https://github.com/activeadmin/activeadmin.info) repo
