### ISSUE TITLE
Date range filter doesn't cover the last day

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3529]
refs #2374 and activerecord-hackery/ransack#458

![date filter](https://cloud.githubusercontent.com/assets/165599/4809100/54243088-5ea8-11e4-86c6-9be135707327.jpg)

With this UI we create a request like `?q[date_lteq]=2014-10-29`, put this queries the db with ````appointments`.`date` <= '2014-10-29 00:00:00'````, but it should be ````appointments`.`date` <= '2014-10-29 23:59:59'````, otherwise it not cover the last date of the range.

We could solve this via a hidden field for `date_lteq` witch adds the `23:59:59` via JS, like we do it with the predict select.

**Comment by chrp** [comment]
@timoschilling - here's our temporary solution for your problem: 

Change date_range filter to use a custom ransack predicate:
```ruby
module ActiveAdmin
  module Inputs
    module Filters
      class DateRangeInput < ::Formtastic::Inputs::StringInput
        def lt_input_name
          "#{method}_lteqdate"
        end
      end
    end
  end
end
```
And define that predicate in an intializer or next to that monkey patch: 
```ruby
Ransack.configure do |config|
  config.add_predicate 'lteqdate',
    arel_predicate: 'lteq',
    formatter: -> (v) { v.strftime '%Y-%m-%d 23:59:59.9999' }
end
```
So ```lteqdate``` provides a more intuitive ```lteq``` for dates.

**Comment by keithlayne** [comment]
@chrp - I like your approach - my previous workaround for this stopped working when I started using master.  However, your formatter caused problems for me considering timezones.  I ended up using this predicate instead, and it seems to do what I want:

```ruby
config.add_predicate 'lteqdate',
  arel_predicate: 'lt',
  formatter: -> (v) { v + 1.day }
```

**Comment by chrp** [comment]
@keithlayne Thanks, your approach is indeed timezone proof when there are differences between application time and UTC.

**Comment by kaelumania** [comment]
+1

**Comment by nitsujri** [comment]
+1

**Comment by seanlinsley** [comment]
It seems like the only reasonable solution is @chrp's. If someone would like to open a PR, we'd be happy to review it.

**Comment by groony** [comment]
#4340

**Comment by hanumakanthvvn** [comment]
I also stuck on the same issue, any update on the PR.

**Comment by lucasfais** [comment]
In case you are using a similar monkey patch, it is now broken with ransack 4.4.0 due to https://github.com/activerecord-hackery/ransack/issues/1649

Here is my fix:

```ruby
  config.add_predicate :lteqdate,
    arel_predicate: 'lt',
    formatter: -> (v) do
      v = Time.zone.parse(v) if v.is_a?(String)
      (v + 1.day).beginning_of_day
    end
```

**Comment by javierjulio** [comment]
[Ransack 4.4.1 was released](https://github.com/activerecord-hackery/ransack/releases/tag/v4.4.1) reverting a related change so it may work now. Give it a try and report back. Otherwise, I would avoid upgrading to Ransack 4.4.0. Thanks.
