### ISSUE TITLE
ActiveAdmin 1.0.0 migration guide

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#3536]
This is going to be the meta ticket for discussing the 1.0.0 release.

We need to 1) itemize all breaking changes in the changelog and 2) create an upgrade guide.

We should also consider whether there are things we can add (deprecation warnings, helpful exceptions) to make upgrading easier.

Open question: when upgrading your application to use master, what were the biggest pain points? How can we make it easier?

**NOTE: please don't post things that already listed here and please don't make a discussion about off topics aka "When is the version 1.0 release expected?"**

EDIT (@timoschilling), summary form the comments:
- [ ] rename `f.buttons` to `f.actions` (link to formtastic changenotes for this)
- [ ] `default_actions` -> `actions`
- [ ] `strong_params`
- [ ] `metasearch` -> `ransack`
  - This is maybe help full https://github.com/activerecord-hackery/ransack/#ransack-search-method
- [ ] `form_buffers` remove
- [ ] https://github.com/activeadmin/activeadmin/issues/3153#issuecomment-65485293
- [ ] Mongoid support
- [ ] Asset Pipline https://github.com/activeadmin/activeadmin/issues/3793#issuecomment-74645081

**Comment by davidcpell** [comment]
is `gem 'inherited_resources', github: 'josevalim/inherited_resources', branch: 'rails-4-2'` still required in `1.1.0pre`?

**Comment by timoschilling** [comment]
@davidcpell no, it's not required, inherited_resources rails-4-2 is merged in inherited_resources master.

Please don't Post questions like that in this Topic!

**Comment by joelmichael** [comment]
Hey guys, I just wanted to mention that we are tracking master in production. Well, we were, but recently something in master broke, so we are now tracking a specific commit.

None of the other gems we use have this kind of release schedule -- the "track master" release schedule. What they release is major versions, minor versions, and point releases.

Rails 4 has been out for over two and a half years, and many people are currently using your software with Rails 4. Please release version 1.0.0. Your current approach is irregular and is making things more difficult for your users.

**Comment by codingluke** [comment]
Hey guys, im migrating a application to the actual active_admin, cause we have some day to migrate to Rails 4. I agree with @joelmichael, but in my case, i just fork the actual master, so I can be sure nothing changes when i deploy.

But my actual problem is. I havily use `form_buffers.last` cause wie customized the backend a lot. My question is now, what ist the new way to do it? As I can see [here](https://github.com/Neohapsis/activeadmin/blob/master/lib/active_admin/form_builder.rb) internal you still use form_buffers.last. I just need an other method to append my own HTML into the formbuilder.

**Comment by timoschilling** [comment]
@codingluke your fork is not up to date, `form_buffers.last` is no more available, we don't have a 1:1 replacement. But you can now use arbre in the form, that should help you.

**Comment by codingluke** [comment]
Hey @timoschilling, my fork ist not up do date cause its my private ;) im working at the moment for a company, so i forked it new as the organization. I figured it out how to fix some parts with arbre! Thx for the fast response

**Comment by javierjulio** [comment]
I'd love to get my CSS Overhaul pull request #3862 as part of this release.

**Comment by timoschilling** [comment]
@javierjulio that should be work!

**Comment by taryneast** [comment]
While upgrading - I had a concern that I was adding to two activeadmin controllers. it had an included section (which just had a delegation and helper-method), and threw an exception telling me I was not allowed to have two included sections. There was no way around it but to remove the included section from the concern and duplicate it into the controllers that included that concern.

**Comment by seanlinsley** [comment]
https://github.com/justinfrench/formtastic/wiki/Upgrading-to-Formtastic-3.1

**Comment by seanlinsley** [comment]
I'm worried that the form builder rewrite introduced a lot of bugs and undocumented backwards incompatibilities. I'm going to work through the open form bug tickets to better understand the current state of the code.

**Comment by justin808** [comment]
@seanlinsley I'm doing a migration. I had to replace `render active_admin_template(:edit)` with `render :edit`

**Comment by gommo** [comment]
How is this (v1) coming along now?

**Comment by deivid-rodriguez** [comment]
Does this guide make any sense at this point? The latest (non pre-) release of activeadmin only supports a very old unsupported version of Rails (Rails 3). Almost every one is tracking master nowadays.

**Comment by jamie** [comment]
Definitely this guide makes sense. We're on a legacy Rails3 app working toward a Rails4 upgrade, and our options are either upgrade ActiveAdmin or replace it with something else. A concise guide covering the relevant changes is of huge value (and could probably be made a wiki page on the project).

**Comment by deivid-rodriguez** [comment]
I think it made sense at the time, now it doesn't. It does make sense that someone who still has to go through the trouble documents the process.

In any case, it's up to the maintainers to choose where they focus their efforts.

**Comment by varyonic** [comment]
We completed a substantial upgrade of our e-commerce back-end from Rails 3 w/ ActiveAdmin 0.6 to Rails 4 with ActiveAdmin 1.0 [earlier this year](http://www.varyonic.com/2016/03/from-rails-3-2-to-rails-4-2-if-we-really-must/)  The changes from 0.6 to 1.0 are significant, and we took the approach of switching to master as of Nov 2013 and then skipping down master in 60-90 day increments isolating and fixing breaking changes along the way.  Needless to say good test coverage is key.

I listed the issues we encountered in the blog post, they included:
- replacing metasearch with Ransack
- Formtastic updates
- jquery-ui updates and their impact
- CSVBuilder changes, including streaming and column name changes
- default_actions replaced by actions
- changes to has_many forms CSS
- removal of form_buffers breaks partials inside form_for and other issues (my fault I’m sorry to say)

Migrating from Rails 3 to 4 has plenty of other minor challenges of its own, including strong parameters, ActiveRecord tweaks/deprecations and coordinating updates of other gems you may be depending on.  I'm skeptical anyone is going to provide a more detailed guide at this point but I'll help if I can.  Whatever its weaknesses AA provides value and I would not rush to replace it.

**Comment by jrochkind** [comment]
Are there currently maintainers of Activeadmin? Is a 1.0 release planned, or is it expected that everyone will just track master from here on out?

It makes it difficult to deal with old projects that may be a rails version or two behind, and need to be upgraded, to not have clear version releases of activeadmin for the past ~2 years.

**Comment by varyonic** [comment]
I published a summary of the [commits we used on master before 1.0.0.pre1](http://www.varyonic.com/wp-content/uploads/2016/11/ActiveAdmin-0.6-to-1.0-notes.pdf) with notes on each.  YMMV, usual disclaimers apply.

**Comment by deivid-rodriguez** [comment]
What's the plan here? Latest two @varyonic's comments seem like a gold resource for people upgrading. Should they be put in an `UPGRADE.md` document?

There haven't been any comments here from any mantainers for more than one year but this is supposed to be blocking a 1.0 release... ¯\_(⊙︿⊙)_/¯

**Comment by dmitry** [comment]
I'd like to help, but nobody from the maintainers are active anymore.

BTW https://github.com/activeadmin/activeadmin/issues/4677

**Comment by gommo** [comment]
Sad that AA has fallen so far. Wonder if we can get a new group of maintainers happening in '17

**Comment by dmitry** [comment]
@gommo I think we can do that by forking AA. First of all we need to understand who are :+1: for that. Then lets fork and start to work. :)

**Comment by joelmichael** [comment]
It's time for someone to fork this and release actual versions.

**Comment by varyonic** [comment]
I'm subscribed to the project and I see Timo responding frequently.  Perhaps this should be discussed with him on Gitter or IRC?

**Comment by dmitry** [comment]
Why not to discuss such question here? It's a direct way, and probably the easiest way for the other parties to see how is it going.

**Comment by varyonic** [comment]
I created an [Upgrading ActiveAdmin wiki page](https://github.com/activeadmin/activeadmin/wiki/Upgrading-ActiveAdmin) as suggested earlier, feel free to update or give feedback.

**Comment by joallard** [comment]
@timoschilling is there anything else besides #4173 blocking 1.0?

**Comment by timoschilling** [comment]
#4173 is not a blocker!

I will make a new pre release in the next minutes.

And in the next days I will write something about comments like `It's time for someone to fork this and release actual versions.`, #4677 and https://github.com/activeadmin/activeadmin/issues/3536#issuecomment-257637893

**Comment by deivid-rodriguez** [comment]
> #4173 is not a blocker!

Great, let's remove it from the 1.0.0 milestone then!

> I will make a new pre release in the next minutes.

How many minutes (approx.)? 

> And in the next days I will write something about comments like It's time for someone to fork this and release actual versions., #4677 and #3536 (comment)

How many days (approx.)?

Finally, could you let us all know what's blocking a 1.0.0 release?

**Comment by deivid-rodriguez** [comment]
I was thinking that maybe you'll want to release a new version of `inherited_resources` first. Is that the case?

**Comment by dmitry** [comment]
Looks like should be updated or closed.

**Comment by deivid-rodriguez** [comment]
@varyonic is actively maintaining the upgrade guide in the wiki, so I think it's fine to close this, yes.

**Comment by joallard** [comment]
Approaching the 3 year anniversary of this ticket, can I just take a moment to congratulate the maintainers and contributors on releasing 1.0, we even have a 1.1! I thought this day would never come, so cheers (I am however very sorry for this notification-generating non-mission-critical comment.)

Bravo!
