### ISSUE TITLE
Default render of XML, CSV... is highly unsecure (even with download_links = false)

### ISSUE THREAD

**Issue by micred** [activeadmin/activeadmin#3539]
In standard activeadmin configuration all formats renderer are enabled by default (even if download_links = false).
CSV, XML... render by default all database attributes.
I think it's important to explicitly enable that feature, otherwise sensible data not shown in activeadmin show or index will leak out.

How can I disable output different from HTML?

**Comment by juliogarciag** [comment]
I don't know if this issue is still active but i found that constraining the format in a `constraint` block to just html when mounting activeadmin invalidates the `xml` and `json` routes.

```ruby
constraints :format => :html do
  ActiveAdmin.routes(self)
end
```

**Comment by seanlinsley** [comment]
I don't see this as a serious security issue, since Active Admin is meant for true administrators of your website to use (people who already have your trust). While it is a security issue for certain uses of Active Admin, fixing it isn't a priority.

However that doesn't mean a PR wouldn't be accepted.

**Comment by timoschilling** [comment]
@seanlinsley I'm with you but we should leave this open

**Comment by seanlinsley** [comment]
:+1:

**Comment by vraravam** [comment]
hi - I am looking for this exact solution: just hiding the download links does not work, I need to be able to un-authorize a user if their role does not allow to actually download CSVs, etc. Could this be merged soon?
