### ISSUE TITLE
Cocoon problems in last commit of ActiveAdmin

### ISSUE THREAD

**Issue by jjmiranda** [activeadmin/activeadmin#3546]
Hi friends!
I think the last deployment of ActiveAdmin has broken Cocoon functionality, because using:
gem 'activeadmin', github: 'activeadmin', ref: '6e55bd28acdb5697618aa832c75722333de46c13'
from 2 weeks ago everything with Cocoon works perfectly.
Any ideas about that?
P.D.:  sorry for my English :)!

**Comment by Fivell** [comment]
@jjmiranda , can you check if #3897 helps?

**Comment by deivid-rodriguez** [comment]
Closing for lack of feedback. Feel free to reopen if you still can reproduce it after checking what was requested.
