### ISSUE TITLE
permit_params does not include belongs_to

### ISSUE THREAD

**Issue by kmayer** [activeadmin/activeadmin#3556]
If I have a resource with a `belongs_to` relationship, the new action fails because the "parent" id is not whitelisted:

```ruby
class AdminUser < ActiveRecord::Base
  belongs_to :employer
end

class Employer < ActiveRecord::Base
  has_many :administrators
end
...
ActiveAdmin.register Administrator do
  belongs_to :employer

  permit_params :employer_id
end
ActiveAdmin.register Employer do
end
```

visiting `/admin/employer/1/users/new` raises an error:

```
ActionController::UnpermittedParameters in Admin::AdministratorsController#new
found unpermitted parameters: employer_id
```

And with some digging, it turns out that `employer_id` isn't wrapped in the `param_key` (https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource_dsl.rb#L50), so it isn't permitted.

once the generated `permitted_params` method is called by InheritedResource, the resulting list of keys are:

```
[:utf8, :_method, :authenticity_token, :commit, :id, {:administrator=>[:employer_id]}]
```

but the submitted parameters (to the `new` action) are:

```
{"action"=>"new", "controller"=>"admin/administrators", "employer_id"=>"1"}
```

As a workaround, I just overrode the `permitted_params` method in the `Administrator` resource:

```ruby
  controller do
    define_method :permitted_params do
      params.permit *active_admin_namespace.permitted_params, :employer_id,
                    :administrator => [:email, :role, :employer_id, :password, :password_confirmation]
    end
  end
```

**Comment by macowie** [comment]
Just hit this too on 1.0.0pre2, so it's still around. The workaround above did, in fact, work around it.

**Comment by timoschilling** [comment]
You need to list all needed attrs

**Comment by codyrobbins** [comment]
I’m running into the same problem on 1.0.0pre4. As described in the original comment, creating new nested resources is not possible. Unless I’m misunderstanding something, I think this is indeed a bug and shouldn’t have been closed.

@timoschilling If this isn’t a bug would you mind explaining in a little more detail how this issue can be worked around without redefining `permitted_params` in the controller? Thanks!

**Comment by Ruff9** [comment]
The problem is still here on 1.0.0pre4.

**Comment by dmitry** [comment]
@Ruff9 can you post a simple code that reproduces a problem?

**Comment by Ruff9** [comment]
Considering that ActionItem belongs_to Action:

`ActiveAdmin.register Action do
  permit_params :action_id, ...
  
  form do |f|
    f.inputs "Action" do
      f.object.build_action_step if f.object.new_record?
      f.semantic_fields_for :action_step do |a|
        a.input :date
        a.input :comment
      end
    end
    f.actions
  end

end`

validate this form raise a mysterious `Unpermitted parameter: action_id`

**Comment by dmitry** [comment]
Try out:

```
     controller do
        define_method :permitted_params do
          params.require(:action).permit(:action_id) # add here other attributes 
        end
     end
```

I think you have some other name for the model `Action` when it gets `param_key`.

**Comment by dmitry** [comment]
Please look how it's implemented: https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/lib/active_admin/resource_dsl.rb#L50

**Comment by jaredbeck** [comment]
`belongs_to`, by itself, should be sufficient configuration, so this issue should be re-opened.

Consider

```ruby
ActiveAdmin.register Post do
  belongs_to :blog
end
```

then `permitted_params.include?(:blog_id)` should return `true`. Currently (in `1.0.0.pre4`) returns `false`.

To accomplish this, `active_admin_namespace.permitted_params.include?(:blog_id)` should return `true`.

CC: @sbleon
