### ISSUE TITLE
Paperclip handler missing

### ISSUE THREAD

**Issue by walidvb** [activeadmin/activeadmin#3559]
upgraded from 05778f4b7c8e821d584c7b4b08bcd79c02a0db76 to 49bc61a3785004429e0a536d77f506bbfb6ba72b, and found 2 issues with Paperclip form:

 - Rendered input puts the object instance(i assume):
![screen shot 2014-11-03 at 12 00 53](https://cloud.githubusercontent.com/assets/810604/4881427/be0b57b6-6348-11e4-8868-87d232a465ed.png)

 - Paperclip handler not found error when uploading(parameter is permitted)
![screen shot 2014-11-03 at 12 03 34](https://cloud.githubusercontent.com/assets/810604/4881442/178a9b08-6349-11e4-8109-c5e7f14264f6.png)

    form do |f|
      f.inputs "Details", :class => "collapsible" do
        f.input :header_image, :as => :file, :hint => f.template.image_tag(f.object.header_image.url(:thumb))
      end
    end

**Comment by ktaragorn** [comment]
This wiki page should be edited to remove `f.template` https://github.com/activeadmin/activeadmin/wiki/showing-an-uploaded-image-in-the-form

**Comment by timoschilling** [comment]
@ktaragorn :+1:

**Comment by ktaragorn** [comment]
Ive just edited it.. turns out I was logged out earlier, thats why I didnt realize I could edit :P

**Comment by timoschilling** [comment]
> Paperclip handler not found error when uploading(parameter is permitted)

@walidvb do you still have that problem?

**Comment by walidvb** [comment]
Hey @timoschilling very sorry, i haven't had the time to test that again, as some other parts of my code broke when I upgraded(such as the `fl.form_buffers.last << ...` trick ). I'll try it ASAP, and thanks for the fix!

**Comment by walidvb** [comment]
Hi, finally took the time to upgrade to the latest version, and i do not have the issue.
