### ISSUE TITLE
add i18n/translation documentation

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3561]
We should add a documentation about how to translate ActiveAdmin

This should be include:
- [ ] how to contribute on [localeapp.com](http://www.localeapp.com/)
- [ ] i18n gems for gem translation
  - [ ] devise-i18n
  - [ ] https://github.com/activeadmin/activeadmin/issues/2718#issuecomment-62035151
- [ ] some i18n key guidelines
  - [ ] no keys for third party gems
  - [ ] key order
  - [ ] key formatation
- [ ] https://github.com/activeadmin/activeadmin/issues/2779#issuecomment-31433018

**Comment by javierjulio** [comment]
I would accept a PR for improving the docs. Thank you.
