### ISSUE TITLE
has_many rendering without fields

### ISSUE THREAD

**Issue by aalong** [activeadmin/activeadmin#3570]
I'm on Rails 4.1 with AA pulled in from github, and ran into some complications when I last tried to update. In particular, I have a complicated nested form that is structured something like this:

```ruby
form do |f|
  f.inputs do
    f.has_many :items, :sortable => :position do |item|
      item.inputs :class => "item_wrapper" do
        item.inputs do 
          "<p>some static html</p>".html_safe
        end
        item.input :title, :input_html => {:class => 'item_title'}
        item.input :blurb, :input_html => { :rows => 3, :class => 'item_blurb'}
        item.inputs do 
          "<p>More static html</p>".html_safe
        end
      end
    end
  end
  f.actions
end
```
(EDIT by @timoschilling, moved code from pastebin into inline)

Before I updated (I was at ref 8299dee5bd0), this rendered as expected; all of the fields and the static html I needed for each item ended up in the page.

When I first tried to update last week (at ref 0becbef091), only the last method call inside each item_wrapper inputs block rendered. This held true with or without the innermost inputs blocks, and rearranging the various calls just changed which "last thing" was rendered. 

Per the answer I got at http://stackoverflow.com/questions/26666560/activeadmin-has-many-and-arbitrary-html-with-the-newer-1-0-0-dsl I made another attempt at updating today (this time to c93f6f49c6d4), but the problem seems to have gotten worse; at this revision, only the hidden`position` field and the drag-and-drop handle are rendered. If I turn off `:sortable` for the has_many block, all I get are empty ol tags. 

Since I managed to resolve my dependency tree for the security update this is no longer urgent for me, but still a cause for concern since my project depends heavily on these has_many forms. Is this regression already being investigated?

**Comment by Fivell** [comment]
@timoschilling , according to implementation has_many is Arbre Component that just wraps form builder, 
https://github.com/activeadmin/activeadmin/blob/714d100cd8d99dcfba5d908c56887e170f1ec708/lib/active_admin/views/components/active_admin_form.rb#L121
block that passed to form-builder has no access to arbre context, so it is not possible to use arbre syntax by design. 

@aalong , also it's not clear what html do you expect, block that passed to has_many is evaluated inside ```<o></o>``` tag and can be used to generate ```li``` items. Your code have no sense,  you're building bad html structure.

**Comment by aalong** [comment]
That suggests pretty strongly that this isn't something that's going to be fixed without a lot of work. Thanks for digging into the problem. 

As for the intent of the static html, the example given is simplified and has a lot of placeholders. My real form uses custom html for some dummy inputs and contextual instructions as part of a specialized polymorphic name-search autocomplete on an association, one that wouldn't be a good fit for the new ```:as => :autocomplete``` input. Using Formtastic's DSL would (to my knowledge) require me to add dummy transient attributes on the model to reproduce these behaviors, and would add some layout concerns and JS complications. It's not the end of the world, and it's admittedly a rather extreme use-case, but the loss of flexibility inside the has_many block was surprising and will probably affect other users of the gem.

**Comment by irubnich** [comment]
Any updates on this? I'm experiencing the same issue. It only seems to be occurring on an "edit" action though.

**Comment by aalong** [comment]
I finally got around to trying to update again, this time using the `concat` method described in https://github.com/activeadmin/activeadmin/issues/3834#issuecomment-93678418 with great success. Aside from having to remove the `.inputs` wrapper, my existing form worked with very little modification. Closing this since I have a workaround and since #3834 covers more or less the same subject matter.

**Comment by johnmcconnell** [comment]
I experienced this issue. It is related to my comments at: https://github.com/justinfrench/formtastic/issues/795

**Comment by johnmcconnell** [comment]
Following up on this discussion: https://github.com/justinfrench/formtastic/issues/794#issuecomment-347965457

It looks like formtastic does not want to support this feature.

I would propose `ActiveAdmin` supporting this use case.
