### ISSUE TITLE
Comments no longer associated with an STI model's base class

### ISSUE THREAD

**Issue by johnmaxwell** [activeadmin/activeadmin#3583]
Rails has a feature called Single Table Inheritance that allows you to subclass ActiveRecord models via a type field, and when that particular record is loaded from a database, it will be instantiated as the subclass in specified in the type field.  You can read more about this Rails feature here: http://api.rubyonrails.org/classes/ActiveRecord/Base.html#class-ActiveRecord::Base-label-Single+table+inheritance

In ActiveAdmin 0.6.3, ActiveAdmin::Comments were created and associated with an ActiveRecord model's base_class (http://api.rubyonrails.org/classes/ActiveRecord/Inheritance/ClassMethods.html#method-i-base_class) via it's `resource` polymorphic association.   In ActiveAdmin 1.0.0.pre the ActiveAdmin::Comments are associated with the subclass itself, not its model base class.

So in the documentation example above where you have the following STI hierarchy:

    class Company < ActiveRecord::Base; end
    class Firm < Company; end
    class Client < Company; end
    class PriorityClient < Client; end

Creating a comment on any instance of these in ActiveAdmin 0.6.3 and earlier would be associated with the "Company" class.  In ActiveAdmin 1.0.0.pre, the same comments comments would be associated with their respective subclass: Firm, Client, or PriorityClient.

The upshot is that this change breaks the comment associations with models that use STI in two ways:

- Coming from ActiveAdmin versions < 1.0.0, Comments won't be found for an STI model.
- If a model switches type, it loses the associated comments.

Is this an intentional change?  I've monkey-patched ActiveAdmin::Comment.resource_type in my own app to restore the old, more compatible behavior.  I can submit a patch if you want to restore that behavior.

**Comment by timoschilling** [comment]
@johnmaxwell any updates?

**Comment by johnmaxwell** [comment]
I'm sorry.  I do intend to work on this but have been slammed with personal
matters since last update.  Can you give me until early next week?

**Comment by timoschilling** [comment]
sure
