### ISSUE TITLE
Remove inherited_resources

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3604]
`inherited_resources` will support Rails 4.2 for us, see https://github.com/activeadmin/activeadmin/pull/3193#issuecomment-62421649 for details.

To support Rails 5.0 in the future we need to remove `inherited_resources` and need to implement some features of `inherited_resources` in our base controller.

NOTE: This ticket is only for the replacement of `inherited_resources`, please don't post `inherited_resources` bugs and not no other off topics here!
And please no `+1` posts, you don't need to need to do that, it is a done thing, there is no way around on the long term.

**Comment by Fire-Dragon-DoL** [comment]
Are there any chance you guys can take over the development (and the upgrade) of inherited_resources (and keep it as a separate gem, which provides a double bonus). I don't use inherited_resources myself but I definitely agree that responders and respond_with is not a full replacement for what inherited_resources does, and considering how important is this for activeadmin, it can be option (also code will adapt to activeadmin requirements, which is quite good).

**Comment by bamorim** [comment]
@timoschilling So, today I was dealing with some problems with the belongs_to :optional and breadcumbs and so and It got me thinking about it.

Well, I have an idea that I like to discuss here. Its somewhat complicated but it's also robust, I think

My solution to this problem (as well as for routing, nested, breadcumb generation and so on) is to create an Directed Graph.

Well, the way it should work is to have a Resource Graph, that keeps all resources and related stuff (actions, namespaces, and so on)

For default, the Resource Graph is initiated with the Root namespace.
Some actions on the DSL acts directly on the Resource Graph.

For example: belongs_to add a relation from the parent to the actual resource and removes the root connection unless optional: true is passed.

After we have our resource graph defined, we can then generate the routes and the controllers.

The routes are really straight forward: We just run a Graph Search, checking for and removing/warning about cycles on the Graph "instance_exec-ing" the routes. For each time we find something (A Resource, a Page or a Singleton Resource, we run some different router)

For generating the controllers, we can a similar approach, but modifying the controller evertime a route is added. After that the controller will have a tree of forms of getting to the resource.

When the request comes, the controller finds the path from the root down to the main resource.
After that he will run the request chain and the last item of the chain will be the required resource.

For breadcrumb generator, it just follows the resource chain.

Well, this is just some toughts (and a little bit crazy) and it's not refined. It'd also be complicated to implement. However this should gives us a better control over our problem and maybe will allow us to move faster.

That's it.

**Comment by jaredbeck** [comment]
Today, when asked to release a version of `inherited_resources` that supports rails 5, Rafael França said:

> .. for more than 4 years this gem is deprecated .. there is no motivation 
> by any of the maintainers to work on this gem.  .. I don't want to work on it.

Of course Timo is already aware of this, as he stated above, in 2014. I just thought the quote was interesting and shows the urgency of this issue.

**Comment by varyonic** [comment]
@Fire-Dragon-DoL Your [wish is granted](https://github.com/activeadmin/inherited_resources/pull/420/commits/849eecd13dd699c2528878165b87b992fc083b88)  For the curious, I believe inherited_resources was the inspiration and heart of ActiveAdmin, see Greg's [original repo](https://github.com/gregbell/inherited_views)

**Comment by Fire-Dragon-DoL** [comment]
!!!!
@varyonic thanks, that's a great surprise and comes with great surprise, making me extremely happy!

Good luck with the maintenance, and good job for all the work on ActiveAdmin!

**Comment by deivid-rodriguez** [comment]
I think it's good to keep this opened. It's something we want to do, so why not let contributors know about it with an opened issue? Maybe apply some enhacement / todo / help_wanted labels.

**Comment by timoschilling** [comment]
@varyonic I agree with @deivid-rodriguez

**Comment by kiddrew** [comment]
Is there any plan to move on from inherited resources at this point? It's a relatively minor annoyance, but having BaseController inherit from ApplicationController through inherited resources really overloads that controller with a lot of logic that should belong elsewhere. Before hooks, etc. I know that before hooks can be done in the AA initializer, but that feels like a hack.

**Comment by Fivell** [comment]
@kiddrew  https://github.com/activeadmin/activeadmin/issues/3604#issuecomment-274981487 is actual

**Comment by javierjulio** [comment]
I figure removing this dependency would be too major as we likely use a lot from InheritedResources. If it's doable though I would be open to that and accept PRs. I'll move this to discussions for now instead of closing. Thank you.
