### ISSUE TITLE
replace `nested_menu_arrow.gif` with css

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3612]
We should replace [`nested_menu_arrow.gif`](https://github.com/activeadmin/activeadmin/tree/master/app/assets/images/active_admin/nested_menu_arrow.gif) and [`nested_menu_arrow_dark.gif`](https://github.com/activeadmin/activeadmin/tree/master/app/assets/images/active_admin/nested_menu_arrow_dark.gif) with css arrows.

![arrows](https://cloud.githubusercontent.com/assets/165599/5010918/530cc472-6a78-11e4-86be-1ce3c2131f1f.jpg)

Maybe @cohart can work on this?

**Comment by timoschilling** [comment]
@cohart any update?

**Comment by cohart** [comment]
Sorry, sorry got slammed with work/vacations. I'm gonna try and get this
tackled over the week/weekend.

**Comment by timoschilling** [comment]
:+1:

**Comment by seanlinsley** [comment]
This will be done by #3862
