### ISSUE TITLE
Using semantic_form_for inputs in a sidebar partial double-renders inputs on resource show page

### ISSUE THREAD

**Issue by johnmaxwell** [activeadmin/activeadmin#3613]
I upgraded to a new version of AA, and a sidebar partial that I had written quite some time ago started showing its inputs doubled.  I had another sidebar partial that was using plain form_tag that worked fine.  I adapted the semantic_form_for version to not use the `f.input` calls and instead use the standard Rails form methods and it fixed the issue.  

To be specific, I converted

```
= f.input :market, collection: Market.for_select
```

to 

```
= f.select :market_id, Market.for_select.map {|m| [m.name, m.id]}, include_blank: false
```

Making this change fixed the problem.

To be clear, I am still using semantic_form_for in my partial; I just stopped using Formtastic's `f.input` helpers.

I think something changed in the past few weeks to cause this issue.  Hopefully that's enough for you to go on, because I don't have time right now to dig into it.

**Comment by johnmaxwell** [comment]
Could this be related to #3486 ?

**Comment by timoschilling** [comment]
Yes it's related to #3486, I hope @varyonic find some time to look on all [Forms](https://github.com/activeadmin/activeadmin/labels/Forms) labeled tickets.

**Comment by vraravam** [comment]
I'm having the same issue - and had to revert to using the non-arbre style. Converting to the included arbre-style of forms within AA exposes this issue on my codebase.

```ruby
form do |f|
	f.semantic_errors(*f.object.errors.keys)

	f.inputs I18n.t('activerecord.models.customer', count: 1) do
		f.input :name, input_html: { autofocus: true }
		f.input :email, as: :email
		f.input :mobile_no, as: :phone

		f.semantic_fields_for :customer_meta, f.object.customer_meta || f.object.build_customer_meta do |fi|
			fi.input :alternate_no, as: :phone
		end
	end

	f.actions
end
```

This(^^^) works; while this(vvv) does not:

```ruby
form do |f|
	semantic_errors(*f.object.errors.keys)

	inputs I18n.t('activerecord.models.customer', count: 1) do
		input :name, input_html: { autofocus: true }
		input :email, as: :email
		input :mobile_no, as: :phone

		semantic_fields_for :customer_meta, f.object.customer_meta || f.object.build_customer_meta do |fi|
			input :alternate_no, as: :phone
		end
	end

	actions
end
```
