### ISSUE TITLE
Multilevel nested form.has_many

### ISSUE THREAD

**Issue by dhahn** [activeadmin/activeadmin#3614]
Currently the code for my form looks like this:

```ruby
ActiveAdmin.register QuestionSection, as: "Survey Sections" do
	form do |f|
		f.inputs do
			f.input :title
		end

		f.inputs do
			f.has_many :questions, :allow_destroy => true do |qf|
				qf.input :text

				qf.has_many :choices, :allow_destroy => true do |cf|
					choice_partial cf
				end
			end
		end

		f.actions
	end

	show do
		attributes_table do
			row :questions do |question_section|
				ul do
					question_section.questions.each do |question|
						render partial: "questions", locals: { question: question }
					end
				end
			end

			row :created_at
			row :updated_at
		end
	end
end

def choice_partial form
	form.input :name

	form.has_many :triggered_questions, :allow_destroy => true do |tqf|
		tqf.input :text

		tqf.has_many :choices, :allow_destroy => true do |cf|
			unless cf.object.new_record?
				choice_partial cf
			end
		end
	end
end
```

The issue with this is that I cannot infinitely nest choices inside of questions and questions inside of choices. The "Add new question" or "Add new choice" disappears after it reaches the level of the `form.object.new_record?`. Is there another way that allows me to infinitely nest these associations.

For the record triggered_questions is the same model as questions. Also, I realize that I can make the partial a little more dry, but I figured I would show the code that I have now.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
