### ISSUE TITLE
Right to left language support

### ISSUE THREAD

**Issue by aalsaif** [activeadmin/activeadmin#362]
Could you please add support for right to left languages? I will try to help with Arabic translations, too.

**Comment by amit0001** [comment]
Hi, is there another solution to this, or has this been included in some other way?

**Comment by javierjulio** [comment]
@amit0001 no there isn't but after I complete my work in #3862 which will make up v2 I'd love to have help for this. I'm thinking it would be a good candidate for a 2.1 release perhaps.
