### ISSUE TITLE
Wrong redirect after login/logout when using namespaces

### ISSUE THREAD

**Issue by datenimperator** [activeadmin/activeadmin#3622]
Having two separate namespaces `:admin` and `:merchants`, a successful login into `/merchants/login` will always redirect to `/admin/dashboard`, which in turn will redirect to the admin login form. I was able to monkey-patch this using this code:

``` ruby
class ActiveAdmin::Devise::SessionsController
  def after_sign_in_path_for(resource)
    case resource
      when AdminUser then admin_dashboard_path
      when Merchant then merchant_dashboard_path
      else super
    end
  end

  def after_sign_out_path_for(resource)
    '/'
  end
end
```

However I feel that ActiveAdmin::Devise::Controller.root_path shouldn't simply use the default namespace as it does now.

**Comment by artemsemir** [comment]
I have no issue with login redirection, but it still redirects to default namespace when logging out.

I've solved this by modifying after_sign_out_path_for, now it tries to find the current namespace (by comparing resource with authentication_model or with name of namespace). 
'authentication_model' is a new setting for namespace configuration, it should be used if namespace name and model name aren't equal (ex. '/admin' for AdminUser).

What do you think about this solution?

**Comment by timoschilling** [comment]
Your workaround works only for the case that you have different User-Models for each Namespace.

**Comment by saiqulhaq** [comment]
I have same issue
so could @artemsemir's pull request (https://github.com/artemsemir/activeadmin/commit/0ded1d8e79d7662c84f592ee0fddcf4012b49545) to be merged?

**Comment by anhkind** [comment]
@timoschilling So you mean STI _may_ work with this workaround?

**Comment by timoschilling** [comment]
@anhkind it should
