### ISSUE TITLE
Formtastic 3.1.0 has a ton of deprecation warnings

### ISSUE THREAD

**Issue by dankohn** [activeadmin/activeadmin#3624]
DEPRECATION WARNING: custom_input_class_name is deprecated and will be removed from Formtastic 4.0 (configure Formtastic::FormBuilder.input_class_finder instead). (called from input_class at /Users/dan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-aa23647f29d5/lib/active_admin/form_builder.rb:111)
DEPRECATION WARNING: action_class is deprecated and will be removed from Formtastic 4.0 (configure Formtastic::FormBuilder.action_class_finder instead). (called from block (2 levels) in build_comment_form at /Users/dan/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-aa23647f29d5/lib/active_admin/orm/active_record/comments/views/active_admin_comments.rb:65)

I'm getting dozens of these.

If it's not easy to replace the deprecated methods, could you please lock activeadmin to Formtastic 3.0.0.

**Comment by achiinto** [comment]
And whoever still seeing the deprecation warnings, don't forget to follow the instruction here.
https://github.com/justinfrench/formtastic/wiki/Upgrading-to-Formtastic-3.1

`Formtastic::FormBuilder.action_class_finder = Formtastic::ActionClassFinder
Formtastic::FormBuilder.input_class_finder = Formtastic::InputClassFinder`
for the initializer.
