### ISSUE TITLE
ActiveAdmin takes several *minutes* to load (first time) on development

### ISSUE THREAD

**Issue by gingerlime** [activeadmin/activeadmin#3637]
We're having an issue with ActiveAdmin (master) when trying to upgrade our app from Rails 3.2 to 4.0.

When we launch the rails server in development mode, pages are loading ok, but when we try to go to active admin, it takes several _minutes_

`INFO  Rails : method=GET path=/admin/dashboard format=html controller=admin/dashboard action=index status=200 duration=599275.57 view=599114.99 db=19.07`

This happens the first time we access the page. Afterwards it seems snappy, and we can even restart rails and it will stay fast.

To reproduce this, we clear the rails `tmp/` folder and then it happens again...

Even if we remove all `rb` files from `app/admin` and only load an empty dashboard, it seems to behave the same. Whilst the admin page is loading we see 100% cpu, but memory consumption seems stable (it's not increasing). This also affects our feature specs for the admin, which run with no pre-loaded data. Tests take several minutes longer than with rails 3, and we're pretty sure the time difference is within the admin feature specs.

Our first thought is something to do with caching or building assets? any suggestions what to look for?

**Comment by Batch-filerushing** [comment]
@timoschilling https://stylesheets.space/questions/what-is-the-most-efficient-way-to-import-all-scripts-stylesheets-and-markup-using-just-one-javascript-file
