### ISSUE TITLE
devise_create_admin_users migration created without `.rb` extension

### ISSUE THREAD

**Issue by coreyward** [activeadmin/activeadmin#3657]
The `rails g active_admin:install` creates a file at `db/migrate/[datestamp]_devise_create_admin_users` without the appropriate `.rb` file extension. 

Running off master at bd3380e8df3aec665981737f11f98b3582d64a24 on Ruby 2.1.1, Rails 4.1.6.

**Comment by tomoyuki28jp** [comment]
I had the same problem. The wired thing is `devise:install` works fine for me, but `rails g active_admin:install`  generates "xxx_devise_create_admin_users" withiout the .rb extension.
