### ISSUE TITLE
Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by mmalek-sa** [activeadmin/activeadmin#3660]
I had a working website admin, suddenly I'm getting this error:

Trying to sign into ActiveAdmin causes this error:
Processing by ActiveAdmin::Devise::SessionsController#create as HTML
2014-11-27T12:08:02.579802+00:00 app[web.1]: Parameters: {"utf8"=>"✓", "authenticity_token"=>"hJlrgH8iHF8u2QHdC9ZOQeC2qRlQ9Gi++EQmQrd8V7M=", "admin_user"=>
{"email"=>"my_username", "password"=>"[FILTERED]", "remember_me"=>"0"}
, "commit"=>"Login"}
2014-11-27T12:08:02.580604+00:00 app[web.1]: Can't verify CSRF token authenticity
2014-11-27T12:08:02.701474+00:00 app[web.1]: Completed 401 Unauthorized in 122ms

Any Idea?

**Comment by abidiqbalk** [comment]
Facing same issue with rails 6.1 and active admin 2.14.0. Login on development environment is working fine but on heroku its giving "Can't verify CSRF token authenticity". Any help would highly be appreciated.

**Comment by tagliala** [comment]
As per the comment above, please make sure that the SECRET_TOKEN is set:

https://stackoverflow.com/questions/23709416/increasing-from-1-dyno-to-2-creates-authenticity-token-error

**Comment by abidiqbalk** [comment]
@tagliala Added secret token ENV[SECRET_TOKEN] to heroku but still getting "Can't verify CSRF token authenticity" :(
![image](https://github.com/activeadmin/activeadmin/assets/1542924/404e09bc-aeb1-4563-a7b5-7120780cf6bf)
