### ISSUE TITLE
Add 'not' options to filter

### ISSUE THREAD

**Issue by jostster** [activeadmin/activeadmin#3662]
There should be 'does not contain' or 'does not have' option in the filters. I have a :through relationship and want to be able to filter results based on entries that do not have a specific relationship. This should be togglable so that the admin can either use it to find records that DOES contain the relation or DOES NOT contain the relation. Also being able to add this to strings would be needed so admins can find users or fields that were left empty. A good filter system that has these options that can be used used to see what I am talking about is keystonejs.

**Comment by att14** [comment]
+1

**Comment by Fivell** [comment]
@jostster , 
for relationships you can use
```ruby
ActiveAdmin.register Order do
  filter :user_id_not_eq, label: 'Except User', as: :select, collection: ->{ User.all }
end
```

**Comment by Fivell** [comment]
string search is still possible
```
ActiveAdmin.register User do
   filter :username, filters: [:not_start,  :not_end, :not_cont]
end
```
one issue is there is no aliases to use it like  not_starts_with, not_ends_with ...
I think providing aliases and  documenting it to close the issue.
@varyonic , what do you think ?

**Comment by ryanflach** [comment]
Using version 1.0.0.pre of ActiveAdmin, I was able to implement 'Does Not Contain' to a string filter with a few small workarounds, guided mostly by @Fivell's last comment.

```ruby
ActiveAdmin.register User do
  filter :username, as: :string, filters: [:contains, :equals, :starts_with, :ends_with, :not_contains]
end
```

Note that in order to include the default options in the drop-down, they needed to be included, and `:not_cont` needed to be changed to `:not_contains`.

In my `en.yml` translations file, I needed to add a translation for `:not_contains`:
```yml
en:
  active_admin:
    filters:
      predicates:
        not_contains: "Does Not Contain"
```

With these in place, filtering by 'Does Not Contain' works as expected.

**Comment by ghilead** [comment]
@ryanflach I managed to get this working by using `:not_cont` and adding the translation for `not_cont`

**Comment by yagudaev** [comment]
@ghilead and @ryanflach thanks guys it works like a charm. It would be nice to add these across the board for any string.

This should really be a PR, such a great feature.

**Comment by Ankk98** [comment]
I would like to work on a PR for this if this. Shall I?

**Comment by yagudaev** [comment]
Since this issue is old, probably good to ask @deivid-rodriguez and @javierjulio if they think it is a good addition.

Sadly I don't use AA on any projects currently. Good luck 😁

**Comment by deivid-rodriguez** [comment]
@Ankk98 Yes, go ahead!

**Comment by javierjulio** [comment]
We would accept a PR for this. Thank you.
