### ISSUE TITLE
deprecated methods in Formtastic

### ISSUE THREAD

**Issue by kivanio** [activeadmin/activeadmin#3663]
<pre>
DEPRECATION WARNING: custom_input_class_name is deprecated and will be removed from Formtastic 4.0 (configure Formtastic::FormBuilder.input_class_finder instead (upgrade guide on wiki: http://bit.ly/1F9QtKc )). (called from input_class at /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-8b6586c23a62/lib/active_admin/form_builder.rb:123)
DEPRECATION WARNING: action_class is deprecated and will be removed from Formtastic 4.0 (configure Formtastic::FormBuilder.action_class_finder instead (upgrade guide on wiki: http://bit.ly/1F9QtKc )). (called from block in action at /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-8b6586c23a62/lib/active_admin/form_builder.rb:43)
</pre>

**Comment by shivanibhanwal** [comment]
@kivanio  Is this fixed in activeadmin (1.0.0.pre2)? Because I am using activeadmin (1.0.0.pre2) and I still see this issue.

**Comment by wangthony** [comment]
try this: https://github.com/justinfrench/formtastic/wiki/Upgrading-to-Formtastic-3.1
