### ISSUE TITLE
Login labels are displayed twice

### ISSUE THREAD

**Issue by philipgiuliani** [activeadmin/activeadmin#3666]
I get the following issue after installing ActiveAdmin. I saw that the form is styled by activeadmin, but uses formtastic. So i wasnt sure if its a formtastic, devise or activeadmin issue. 

The forms of the models inside of ActiveAdmin are ok.

![bildschirmfoto 2014-12-01 um 12 58 50](https://cloud.githubusercontent.com/assets/5446019/5245306/fef1b8c0-7959-11e4-8a0b-4e59f648bfcc.png)

**Comment by izumeroot** [comment]
Hello! Is that fix included in 1.0.0.pre2 ? I have same problem in this release.

**Comment by izumeroot** [comment]
I think it is not fixed in master https://github.com/activeadmin/activeadmin/blob/master/app/views/active_admin/devise/sessions/new.html.erb
master have "t" instead of "I18n.t"

**Comment by izumeroot** [comment]
Please, anybody, reopen this issue.

**Comment by philipgiuliani** [comment]
I reopened the issue @izumeroot

**Comment by batizhevsky** [comment]
Same issue. Rails 4, ActiveAdmin from master
https://www.dropbox.com/s/tlrk088eur7ox9y/Screenshot%202016-06-09%2014.24.01.png?dl=0

**Comment by izumeroot** [comment]
Hello!
Sorry. Was it resolved? Or just closed?

**Comment by batizhevsky** [comment]
Can't see any changes in master
Also, maybe it helps:
`> t('active_admin.devise.password.title').class`
=> Arbre::HTML::TextNode

**Comment by timoschilling** [comment]
I don't fully remembered the problem but it was in the application scope and not in the active admin scope.

**Comment by batizhevsky** [comment]
It's in the Devise's views, which shipped with ActiveAdmin

**Comment by aldesantis** [comment]
I'm having this problem as well... I read the thread but not sure what the issue actually is. I'm not overriding any of the Devise/ActiveAdmin views.

**Comment by afriqs** [comment]
Hi,

I'm having the same issue and the culprit is the Redcloth gem which also has a `t` method...

I understand @timoschilling 's [argument](https://github.com/activeadmin/activeadmin/issues/3666#issuecomment-65215159) but in this case the *key* to translate is a fixed one and we don't really care of *path/action* [Rails retrieval](https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/actionpack/lib/abstract_controller/translation.rb#L12).

Will go with `I18n.t` instead.

**Comment by afriqs** [comment]
What is strange is, for example for [app/views/active_admin/devise/sessions/new.html.erb](https://github.com/activeadmin/activeadmin/blob/master/app/views/active_admin/devise/sessions/new.html.erb), the `t` method is not interpreted the same way if it is outside a formtastic helper or not:
- `<%= title t('active_admin.devise.login.title') %>` works well
- `f.input key, label: t("active_admin.devise.#{key}.title")` does not (uses Redcloth's `t` method in my case).

:thinking:
