### ISSUE TITLE
String representation of Enumerator output to view when using table_for

### ISSUE THREAD

**Issue by hoverlover** [activeadmin/activeadmin#3669]
I'm currently using AA master at commit 8c87611980fa.  When I use `table_for` in a custom page inside a `panel`, and there are no items in the collection, I'm getting a string representation of Enumerator printed to the screen.  Attached below is a screen shot showing this.  Here is the code I'm using:

```ruby
panel "Last 10 Donations" do
  table_for controller.exhibit(LastNDonationsReport.new(10, current_admin_user, current_ability, params[:organization_id]).run) do
    column :amount
    column :confirmed_at do |donation|
      donation.confirmed_at_with_time_zone
    end
    column "" do |donation|
      link_to "View", admin_donation_path(donation.id)
    end
  end
end
```
![dashboard___txt2give](https://cloud.githubusercontent.com/assets/169285/5274637/4c7e3222-7a5d-11e4-90bd-107f6b3828d4.png)

Any ideas?

**Comment by seanlinsley** [comment]
An easy fix would be to call `to_a`. We'd be willing to review a PR, but this ticket is a year old now, so I doubt @hoverlover is open to creating one.
