### ISSUE TITLE
Concerns in resources

### ISSUE THREAD

**Issue by Strnadj** [activeadmin/activeadmin#3673]
I am trying to separate and group member and action items into concerns, but when I am trying to include it, it behave like there is no concern members, no includes. When I put some _member_action_ into the concern file, nothing happend, no route etc... It's bug, or am I doing something wrong?

``` ruby
module ConfirmActions
  extend ActiveSupport::Concern

  included do
    member_action :confirm_later do
         # do sth with resource
    end
  end
end

ActiveAdmin.register Advertisment do
   include ConfirmActions
   include ...
end
```

**Comment by SamMolokanov** [comment]
This is another solution:
```
# app/controllers/concerns/shared_admin.rb
# Module: common methods for ActiveAdmin resources
module SharedAdmin
  extend ActiveSupport::Concern

  def self.included(base)
    # Shared member action. Using "send" due to "member_action" is a private method
    base.send(:member_action, :shared_action) do
      render :text => 'Hello from shared action!'
    end
  end

end
```

And then

```
ActiveAdmin.register MyResource do
  include SharedAdmin
end
```

**Comment by reignmaker** [comment]
Awesome! Thank you @SamMolokanov! I stuck at calling private methods, didn't know about ``send`` trick.

**Comment by klappradla** [comment]
Thanks @SamMolokanov, your solution works like charm!
I use it to share action_items, if anyone needs that too:
```ruby
def self.included(base)
  base.send(:action_item, :view_in_app, only: :show, if: proc{ resource.location }) do
    link_to 'View in Location context', [resource.location, resource]
  end
end
```

**Comment by jtomaszewski** [comment]
Yeah, it's just based on [this source from activeadmin](https://github.com/activeadmin/activeadmin/blob/ed1fbca8c64af827616c58f274d7be256ca513b6/lib/active_admin/dsl.rb#L54):

```rb
    # Include a module with this resource. The modules's `included` method
    # is called with the instance of the `ActiveAdmin::DSL` passed into it.
    #
    # eg:
    #
    #   module HelpSidebar
    #
    #     def self.included(dsl)
    #       dsl.sidebar "Help" do
    #         "Call us for Help"
    #       end
    #     end
    #
    #   end
    #
    #   ActiveAdmin.register Post do
    #     include HelpSidebar
    #   end
    #
    # @param [Module] mod A module to include
    #
    # @return [Nil]
    def include(mod)
      mod.included(self)
    end
```

**Comment by rhymes** [comment]
I noticed an issue with this mechanism. You can't directly share resource DSL view methods, because they are private https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource_dsl.rb#L5

Which means that you have to use `dsl.send(:index)` if you want two models (for example STI models) to have the same code for the index view, and so on.

Is there a reason why those methods are private?

**Comment by grimmwerks** [comment]
Hmm; I've got to implement Comments sort of like a git commit - if someone wants to delete any resource within ActiveAdmin they're supposed so get a popup with a line of input text stating why they are making the deletion (HIPPA compliant backend) -- is this how I'd override / autoload?

**Comment by itkin** [comment]
+1

**Comment by spinlock99** [comment]
@rhymes if you want to share the index view between resources, you can use a partial.

    index do
      render "shared/admin_index", klass: resource.class, ...
    end

**Comment by aabdaab** [comment]
@SamMolokanov how about shared `page_action`s ?
I tried to use it analogically

# SharedAdmin Concern
```
def self.included(base)
  base.send(:page_action, :upload_datafile) do 
    # do shared stuff
  end
end
```
and then in my page

```
ActiveAdmin.register_page 'SomePage' do
  include SharedAdmin
  ...
end
```
but it's not working, it doesn't register the route. 
Any idea what am I doing wrong?

**Comment by namiwang** [comment]
> NOTE: Don't mix the `app/admin_share` stuff into `app/admin`, that would be end up in loading/caching problems

@timoschilling 

Hi! Do you think this would be magically resolved with zeitwerk loader introduced by rails 6?

**Comment by gingerlime** [comment]
@namiwang thank you. Can you give a bit more details on how you structured your concerns with ActiveAdmin and Rails 6?

**Comment by vfonic** [comment]
This seems to be the easiest solution for me, since you can simply copy-paste the same code from the admin page/resource:

```ruby
# app/admin/concerns/active_admin_dsl_extension.rb
module ActiveAdminDslExtension
  def initialize_entity_record
    config.filters = false

    controller do
    end
  end
end
```

```ruby
# app/admin/entities.rb

ActiveAdmin.register Event do
  extend ActiveAdminDslExtension
  initialize_entity_record

  # ...
end
```

**Comment by aki1221** [comment]
this also works
`
module UserActions
  module Actions
  
    def self.included(dsl)
        dsl.instnace_eval do 
            # define method here ..... like member_action, collecton_action
        end
   end
end
end`

**Comment by tuval10** [comment]
To anyone who is struggling with Rubocop, an answer based on the previous ones:
```
# frozen_string_literal: true

module ConfirmableController
  def confirmable?
    resource.respond_to?('confirmed_at')
  end

  def error_redirect
    redirect_to(
      request.referer,
      alert: "Cannot confirm #{resource_class.name.underscore.humanize}!"
    )
  end
end

module Confirmable
  ACTIONS = proc do
    member_action :confirm_later do
      return error_redirect unless confirmable?

      args = {}
      unless resource.update(confirmed_at: value)
        args = { alert: "#{resource_class.name.underscore.humanize} confirm didn't succeed" }
      end
      redirect_to request.referer, **args
    end
  end

  def self.included(dsl)
    dsl.controller do
      include ConfirmableController
    end

    dsl.instance_eval(&Confirmable::ACTIONS)
  end
end
```
