### ISSUE TITLE
extra SQL queries are performed when custom establish_connection was performed

### ISSUE THREAD

**Issue by Fivell** [activeadmin/activeadmin#3674]
Hello, dear AA community.   I have doubts if it is AA bug or not, but still ...

If you're connecting to multiple databases (say by using establish_connection in certain models), it appears that only the ActiveRecord::Base.connection gets query caching enabled.  

See middleware for details https://github.com/rails/rails/blob/3d70f0740b26b0a137d7e6436f9909330f8ee888/activerecord/lib/active_record/query_cache.rb 

So when AA uses such model (with custom establish_connection) it appears that it triggers COUNT(*)  5 times rendering index  and it causes some problems using big tables.
What can you advise ?  Thanks

**Comment by ukolovda** [comment]
I append this code for prevent extra queries to database:

```
  controller do
    # Convert to array
    def find_collection(options = {})
      Kaminari.paginate_array(super(options),
                              limit: 1000000,
                              offset: 0)
    end
  end
```
