### ISSUE TITLE
Country select wrong number of arguments (4 for 0)

### ISSUE THREAD

**Issue by karamosky** [activeadmin/activeadmin#3675]
Hello i have been facing some troubles with activeadmin in rails 4.1.8. In fact i think that the problem came from formtastic. It considers my country field as country_select automatically. Is there any solution to force formtastic to disable the country select rendering. 
Thank you
Here is where it happen

``` ruby
module ActionView

  module Helpers

    module FormOptionsHelper

      # Return select and option tags for the given object and method, using country_options_for_select to generate the list of option tags.

      def country_select(object, method, priority_countries = nil, options = {}, html_options = {})

        InstanceTag.new(object, method, self, options.delete(:object)).to_country_select_tag(priority_countries, options, html_options)

      end

      # Returns a string of option tags for pretty much any country in the world. Supply a country name as +selected+ to

      # have it marked as the selected option tag. You can also supply an array of countries as +priority_countries+, so

      # that they will be listed above the rest of the (long) list.

      #
```

**Comment by coorasse** [comment]
I can't say if it is an ActiveAdmin or a Formtastic error but using a 
```
f.input :country
```
will throw the above exception. Using `as: :string` is not really a solution since will change the field to a standard input text field.

I solved using the following and I have my old select back:
```
f.input :country, as: :select, collection: ActionView::Helpers::FormOptionsHelper::COUNTRIES 
```

**Comment by EricaNichol** [comment]
@coorasse Great solution, I was everywhere to solve this problem. None worked, thank you!

**Comment by Schwad** [comment]
I am only here because a google search with that exact same error was found on my end while *attempting* to incorporate the country_select gem which had been gemified out of Rails. Didn't work and produces this error. So in case anyone else is here for that reason an adapted version of @coorasse 's worked for me:

`= f.select :country, Countries: ActionView::Helpers::FormOptionsHelper::COUNTRIES `

**Comment by fidenz-kaushiks** [comment]
f.input :country, priority_countries: [], only: ["GB", "US", "CA"]
keep 'priority_countries' as empty if no need priorities.
