### ISSUE TITLE
Allow has_many sortable to be configured with the start index

### ISSUE THREAD

**Issue by yaychris** [activeadmin/activeadmin#3680]
Per the discussion [here](https://github.com/activeadmin/activeadmin/commit/7cbcf32bca473a05e3623fe445aec87a81f606f3#commitcomment-4747920), `acts_as_list` uses 1-based indexing but `sortable` uses 0-based. It would be great if this where configurable in the `has_many` call. It doesn't look like a ticket was ever created for this, so here we go.

This syntax, suggested in the thread, seems good to me:

```ruby
f.has_many :posts, sortable: { key: :position, start: 0 }
```

**Comment by timoschilling** [comment]
closed by #3684
