### ISSUE TITLE
Unable to find input class InetInput

### ISSUE THREAD

**Issue by rodrigopinto** [activeadmin/activeadmin#3682]
Hi guys!
I've got an error using active admin with a devise model and it's error seems to be on Formtastic.

```
Formtastic::UnknownInputError at /admin/users/1/edit
Unable to find input class InetInput
```

I've already opened an [issue #1115 on formtastic](https://github.com/justinfrench/formtastic/issues/1115), but posted here to keep tracked to the future searchs.

**Comment by timoschilling** [comment]
#4178 contains some hints to solve this

**Comment by LucasCioffi** [comment]
Also, there is a solution here in the Formatastic repo: https://github.com/activeadmin/activeadmin/issues/4178
```
1. mkdir app/inputs/inet_input.rb
2. put the following code.
class InetInput < Formtastic::Inputs::StringInput
end
```

**Comment by gsum** [comment]
add a form in your /app/admin/users.rb
`form do |f|
  f.inputs do
    f.input :name
    f.input :city
    f.input :rooms
    f.input :code
    f.input :fund
  end
  f.actions
end`

**Comment by danielricecodes** [comment]
> Also, there is a solution here in the Formatastic repo: #4178
> 
> ```
> 1. mkdir app/inputs/inet_input.rb
> 2. put the following code.
> class InetInput < Formtastic::Inputs::StringInput
> end
> ```

Why can't ActiveAdmin just include this by default?  It seems almost too easy of a win here.

**Comment by danielricecodes** [comment]
I went ahead fixed this in my own fork of Formtastic.  I have an open PR, but in the meantime just use my fork and branch.

```ruby
gem 'formtastic', github: 'ldstudios/formtastic', branch: 'danielricecodes-support-inet'
```

Hopefully my PR will get accepted and this issue can be put to rest once and for all.

**Comment by rafaltrojanowski** [comment]
Thanks @danielricecodes! What's the status of your PR by the way?
