### ISSUE TITLE
Invalid route name error with namespaces as strings

### ISSUE THREAD

**Issue by yagudaev** [activeadmin/activeadmin#3687]
Just ran into this simple, yet very confusing (from a user standpoint) bug.

If you use

```
ActiveAdmin.register_page "Dashboard", namespace: 'super_admin' do
end
```

Rails throws the following error:

```
`add_route': Invalid route name, already in use: 'super_admin_root'  (ArgumentError)
You may have defined two routes with the same name using the `:as` option, or you may be overriding a route already defined by a resource with the same naming. For the latter, you can restrict the routes created with `resources` as explained here: 
http://guides.rubyonrails.org/routing.html#restricting-the-routes-created
```

But when using a symbol for the namespace like the code below, everything works fine.

```
ActiveAdmin.register_page "Dashboard", namespace: :super_admin do
end
```

**Comment by timoschilling** [comment]
Thats not a bug, `:namespace` need's to be a symbol. I have extend the docs about this

**Comment by pedrorolo** [comment]
IMHO, this should support strings before supporting symbols, since the character sequence is even relevant in the UI (the URL). I suggest that both are supported.

**Comment by timoschilling** [comment]
It don't make sense to support strings at this place, you can represent any string in a symbol and the namespace look up (based on a hash) is faster with symbols.

**Comment by pedrorolo** [comment]
that makes sense from an optimization and internal representation perspective , though, from the point of view of the API user, not being able to use strings there is an interface that might lead him to commit a mistake, it at least happened to me and to yagudaev. I believe that you could reconsider converting any entered string to symbol. The performance overhead would be far from big and some accidents by this lib users could be avoided.
