### ISSUE TITLE
Numbering items in Index as a Table report

### ISSUE THREAD

**Issue by bnussey** [activeadmin/activeadmin#3693]
Is it possible to get the sequential number of each item in ActiveAdmin?

So it would look like this:

    | Number | Name  |

    | 1      | Bill  |

    | 2      | Smith |  

I know this can be achieved with each_with_index but don't think there is a way to use this with ActiveAdmin.

Could something be added in as controller do ?

I want to add this functionality into an Index as a Table report so for example

    index do
        column "Number" do |a|
           # Some way of specifying index number         
       end
       column "Name" do |a|
           a.name
       end
    end

Thanks

**Comment by seanlinsley** [comment]
Sounds like this has been implemented in #4093
