### ISSUE TITLE
Filters, comments and global AA config

### ISSUE THREAD

**Issue by pranas** [activeadmin/activeadmin#3695]
I'd like to propose a change to config behaviour. Currently if you set `config.filters = false` or `config.allow_comments = false` in your global AA config, you can no longer use those features:

```
activeadmin/lib/active_admin/filters/resource_extension.rb:62:in `add_filter': Can't remove a filter when filters are disabled. Enable filters with 'config.filters = true' (ActiveAdmin::Filters::Disabled)
```

I would like to be able to disable them but still have an option to add filters and comments where I want them. 

Default filters became a common problem in our projects: when the data set grows association filters start to consume a lot of memory. I'd like to make `config.filters = false` a standard practice in my organisation. By default our admin pages wouldn't have any filters, we would add just the ones we want.

The similar situation is with AA comments, I don't want them on every model. I'd better have comments disabled by default but add them where I need to.

I can make a PR if I get a thumbs up.

**Comment by swilgosz** [comment]
I know it is already done, but I think it would be nice to include new syntax in default generated 'config/active_admin.rb' file or information about this change.

**Comment by timoschilling** [comment]
Wait a day, I want to rethink about it

**Comment by ghilead** [comment]
It seems that this PR introduces the issue described here

https://github.com/activeadmin/activeadmin/issues/5117

I was about to add a PR to only register the Comment page when the namespace has comments enabled, but dug deeper and found this PR.

Do you guys have any suggestion on how to achieve both ?

**Comment by TiSer** [comment]
Do you have some way to disable all filters in all models globally for now?

When I try to `config.filters = false` at activeadmin's initialisers I have the same error mentioned at the start of the topic: `Can't remove a filter when filters are disabled`.
