### ISSUE TITLE
Migrate some CSS values to variables and mixins

### ISSUE THREAD

**Issue by ezekielriva** [activeadmin/activeadmin#3699]
A little background:
As Developer my customers sometimes want to change some Admin colors or styles. So, to perform it, I need spend time in review the classes, the styles, add new ones, and more.

So, I was thinking that if all the CSS is migrated to a "Admin framework" it could be great for all those people that want to change their admin panel styles.

I could do this task.

What do you think?

**Comment by timoschilling** [comment]
@ezekielriva any updates on this?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
