### ISSUE TITLE
Rails 4.2.0 and "can't find compatible version of 'rails' gem" error

### ISSUE THREAD

**Issue by btnpushnmunky** [activeadmin/activeadmin#3703]
I'm getting the following when trying to install activeadmin with a new Rails 4.2.0 app:
Bundler could not find compatible versions for gem "rails":
In Gemfile:
activeadmin (>= 0) ruby depends on
rails (< 4.2, >= 3.2) ruby

rails (4.2.0)

I've searched for a similar error with no success.

**Comment by misner** [comment]
+1 blocked too. anybody found a way to update to Rails 4.2 ?

**Comment by timoschilling** [comment]
It's fixed already, you need to read this:
https://github.com/activeadmin/activeadmin#rails-42

**Comment by misner** [comment]
thanks reading it now!

**Comment by misner** [comment]
working , thanks a lot

**Comment by nguyenchiencong** [comment]
thanks. :cake:

**Comment by gkunwar** [comment]
Thanks

**Comment by rjewell2200** [comment]
I think the link above is no longer relevant. Can someone share with me the updated link?

**Comment by timoschilling** [comment]
@rjewell2200 there is no updated link, while there is no longer a difference between rails 4.x and 4.2, so you can simply read the ActiveAdmin 1.0 section https://github.com/activeadmin/activeadmin#100

**Comment by yaneeka** [comment]
@rjewell2200: 

Per the 1.0 section on the main page, I've had "gem 'activeadmin', github: 'activeadmin'" in my Gemfile. But I still needed to do 

bundle update activeadmin

to get the latest changes including the dependency going from Rails < 4.2 to < 5.0.
