### ISSUE TITLE
Adding erb tags and rendering js.erb

### ISSUE THREAD

**Issue by RickS1** [activeadmin/activeadmin#3707]
Hi!
I've been working with this gem for a while and I haven't found a way to insert this erb tags  inside views. Is it possible to do this? If so, how can I do it? The reason of this is because I'm trying to implement private_pub functionality into my app; however, and for this reason, I need to set some erb tags inside the view and add some JS with erb tags.

Thanks in advance!

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
