### ISSUE TITLE
Custom filters for Active Admin (e.g. filter by the count of child models)

### ISSUE THREAD

**Issue by azangru** [activeadmin/activeadmin#3712]
Hi,

I’m using Active Admin version 1.0.0pre. What I would like to do, is to create a filter for the index page of a model which would filter by the count of the instances of an associated model. Here’s an example.

For simplicity, let’s call one model Parent, and the other model Child, so that

```
class Parent < ActiveRecord::Base
   has_many :children 
end

class Child < ActiveRecord::Base
   belongs_to :parent 
end
```

What I would like to create in `admin/parent.rb`, is a filter that will show parents that have a particular number of children (or who have more than or less than a certain number of children):

```
filter :number_of_children, as: :numeric
```

Obviously, this filter wouldn't work as written, because the `Parent` model doesn't have a `number_of_children` field. I looked into using Ransacker as discussed [here](http://cavewall.jaguardesignstudio.com/2014/05/01/activeadmin-filters-with-ransack/), but couldn't quite figure out the syntax of how to write my query. Apparently, at some point it was possible to make custom filters that would filter by scopes (as discussed [here](https://gist.github.com/rdj/1057991)), but this doesn't work any longer.

What would be a way to make such a filter in Active Admin version 1.0.0pre? Is it possible at all?

**Comment by azangru** [comment]
Just wanted to thank you for the `counter_cache` approach. This is what I went with eventually :smile:

**Comment by azangru** [comment]
Here is another question concerning filters in ActiveAdmine.

Suppose I have two models: `Person` and `Address`. A person may have_one address.

Now, I want to filter People by the city where they live (`city` being one of the attributes of the model `Address`). Here is the current code for the filter:

    filter :address, label: 'City', as: :select,
            collection: proc { Address.map { |a| [a.city, a.id] } }
 
The filter works to the extent that it produces a dropdown with a list of the cities. My problem is that different addresses in one city will duplicate the name of that city in the list. For example, "London, King's Cross street" "London, Piccadilly line" will result in London being shown twice in the dropdown list. This makes the filter quite unusable. Is there any way of showing only unique names of the cities in the dropdown list given the described association of the models?

**Comment by timoschilling** [comment]
For Rails > 4
```ruby
proc { Address.distinct.pluck :city, :id }
```

For Rails < 4
```ruby
proc { Address.map { |a| [a.city, a.id] }.uniq }
```

**Comment by azangru** [comment]
That doesn't really work, because the combination of address.city and address.id is itself unique.

In rails console, on my dev database (where city names are generated by faker), the line `Address.distinct.pluck :city, :id` gives the following result:

[["Deckowview", 8], ["Kulasport", 1], ["Kulasport", 5], ["New Daphnee", 2], ["West Adellburgh", 4], ["Lake Simeonhaven", 6], ["North Leatha", 3], ["North Hilmastad", 7]]

Notice that the city Kulasport is repeated (one time with address id 1, the other time with address id 5). This means that in the select dropdown in the browser Kulasport is also repeated. What I am after is having Kulasport listed in the filter's dropdown only once. Is this possible?

**Comment by timoschilling** [comment]
Ok, I understand.

I don't have the time to write the whole code, but I can point you in the right direction.

With Ransack you can search via relations:
```ruby
filter :addresses_city # assdresses = relation table name, city = column name
```

No you only need to create a list uniq list with all cities

**Comment by Goran1708** [comment]
> Ok, I understand.
> 
> I don't have the time to write the whole code, but I can point you in the right direction.
> 
> With Ransack you can search via relations:
> 
> ```ruby
> filter :addresses_city # assdresses = relation table name, city = column name
> ```
> 
> No you only need to create a list uniq list with all cities

assdresses, it's called underwear ? :D
