### ISSUE TITLE
Travis setup for ruby 2.2 / rails 3.2.x

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#3715]
It look's like rails 3.2 will not support ruby 2.2, see rails/rails#18160 and thoughtbot/shoulda-matchers#633 for details.

**Comment by timoschilling** [comment]
The issue rails/rails#18160 is closed
But there is a new PR rails/rails#18306

**Comment by timoschilling** [comment]
> It will be not any new release of 3-2-stable branch. (from @rafaelfranca on rails/rails#18160)

I think we shouldn't no longer maintain ActiveAdmin from Rails 3.2 / Ruby 2.2.

@seanlinsley what do you think?

**Comment by rafaelfranca** [comment]
I'd say that, if it doesn't require a lot of work, it is safe to maintain. When I said any new releases, I mean normal releases. Severe security releases will still be done until Rails 5 is released. They just doesn't happen often. The last release was November 16, 2014 and I'm not sure when will be the next one. But the stable branch is stable and should not change, so it still works.

**Comment by timoschilling** [comment]
@rafaelfranca sorry for not posting the full quote (Updated to the full text)

But the question is still the same...

**Comment by rdlugosz** [comment]
Looks like they've merged the 3.2/2.2 patches into the 3-2-stable branch and closed rails/rails#18160. If a future 3.2.22 is released (for security) it will contain these patches (if I understand the comment thread correctly).

Any general ideas what causes the incompatibility with 3.2/2.2 for AA? I ran into the issue mentioned in #3733. I'd be willing to look into a fix for this unless someone else already knows exactly what's wrong & plans to implement.

**Comment by rdlugosz** [comment]
I've fixed the Ruby 2.2 & Rails 3.2 compatibility issue for the 0-6-stable branch in PR #3760. I suspect the change is also relevant to master, so you may want to review and merge it there as well.
