### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by akashkamboj** [activeadmin/activeadmin#3726]
Starting this thread to address the basic issues to support Rails 4.2

I know that ActiveAdmin streched usage of inherited_resources for long time, while it should be retired ages ago. (Hope to see ActiveAdmin without inherited_resources soon). But for now since we have to live with inherited_resources only alternative i found is that remove inherited_resources from activeadmin.gemspec from your fork.

```
require File.join(File.dirname(__FILE__), "lib", "active_admin", "version")

Gem::Specification.new do |s|
  s.name          = 'activeadmin'
  s.license       = 'MIT'
  s.version       = ActiveAdmin::VERSION
  s.homepage      = 'http://activeadmin.info'
  s.authors       = ['Greg Bell']
  s.email         = ['gregdbell@gmail.com']
  s.description   = 'The administration framework for Ruby on Rails.'
  s.summary       = 'The administration framework for Ruby on Rails.'

  s.files         = `git ls-files`.split("\n").sort
  s.test_files    = `git ls-files -- {spec,features}/*`.split("\n")

  s.add_dependency 'arbre',               '~> 1.0', '>= 1.0.2'
  s.add_dependency 'bourbon'
  s.add_dependency 'coffee-rails'
  s.add_dependency 'formtastic',          '~> 3.1'
  s.add_dependency 'formtastic_i18n'
  #s.add_dependency 'inherited_resources', '~> 1.4', '!= 1.5.0'
  s.add_dependency 'jquery-rails'
  s.add_dependency 'jquery-ui-rails',     '~> 5.0'
  s.add_dependency 'kaminari',            '~> 0.15'
  s.add_dependency 'rails',               '>= 3.2', '< 5.0'
  s.add_dependency 'ransack',             '~> 1.3'
  s.add_dependency 'sass-rails'
end
```

and manually add inherited_resources branch rails-4-2 in your project

so my Gemfile look like this:

```
gem 'responders'
gem 'inherited_resources', github: 'josevalim/inherited_resources', branch: 'rails-4-2'
gem 'activeadmin', github: '' ##(define your github fork here where the above gemspec resides)
```

and you will have a working copy of activeadmin in rails 4.2. Will soon post other issues / fixes soon as I will find those.

**Comment by akashkamboj** [comment]
well this change is not there in the gemspec file neither in master nor in rails-4-2 branch... that's why i created this one. please recheck.

**Comment by akashkamboj** [comment]
😄

**Comment by timoschilling** [comment]
The active admin `rails-4-2` branch allows you to use the inherited_resources `rails-4-2` branch. So there is no need for this issue.

**Comment by steakknife** [comment]
What happened to the `rails-4-2` branch?  `master` instead?

**Comment by timoschilling** [comment]
`rails-4-2` has been merged into `master`.
