### ISSUE TITLE
Inline editing in index and show pages

### ISSUE THREAD

**Issue by eshaiju** [activeadmin/activeadmin#3728]
Hi @seanlinsley, @timoschilling 
What about adding inline editing as a built in feature to active admin?.
I achived this using gem best_in_place 
http://tech.eshaiju.in/blog/2014/04/30/in-page-editing-in-rails-active-admin-using-gem-best-in-place/

**Comment by timoschilling** [comment]
I have think about this too, some month ago. I like the idea, but there are some problems about the authorization. The other reason is that it already works with the `best_in_place` gem. So I don't see a need to bring the into the core. This will only mess up the code. How thy want that feature can use `best_in_place`.

**Comment by eshaiju** [comment]
@timoschilling  Agree with  your point. Most of them is not avare about this possiblility of adding inline editing in AA with best_in_place. What about mentioning this in some where in AA documentation and adding examples for it?

**Comment by timoschilling** [comment]
You can write a article in the Wiki

**Comment by eshaiju** [comment]
@timoschilling 

Added article in Wiki : https://github.com/activeadmin/activeadmin/wiki/How-to-Add-In-Page-Editing-Using-Gem-'Best-in-Place'

**Comment by timoschilling** [comment]
@eshaiju :+1:, I have renamed the page to https://github.com/activeadmin/activeadmin/wiki/How-to-Add-In-Page-Editing-Using-Gem-best_in_place, to prevent linking problems

**Comment by timoschilling** [comment]
@eshaiju offtopic, I have deleted you wiki page "ActiveAdmin is causing all rake tasks to fail   ActiveAdmin::DatabaseHitDuringLoad" while: setting a collection with a DB value without a proc is a bad practice, even the docs shows a example with proc

**Comment by eshaiju** [comment]
@timoschilling :+1:
