### ISSUE TITLE
Undefined Method `time_ago_in_words`

### ISSUE THREAD

**Issue by SingleShot** [activeadmin/activeadmin#3734]
Attempting to use the `time_ago_in_words` from `DateHelper` results in

    undefined method `>' for nil:NilClass

Example config:

    ActiveAdmin.register User do
      index do
        column :last_sign_in_at do |user|
          time_ago_in_words(user.last_sign_in_at)
        end
      end
    end

`Gemfile`:

    gem 'activeadmin', github: 'activeadmin'
    gem 'inherited_resources', github: 'josevalim/inherited_resources', branch: 'rails-4-2'

**Comment by timoschilling** [comment]
I can reproduce your problem, in the case of that one `last_sign_in_at` value is nil.

You can't use `time_ago_in_words` with `nil` values.

This should help you:
```ruby
ActiveAdmin.register User do
  index do
    column :last_sign_in_at do |user|
      time_ago_in_words(user.last_sign_in_at) if user.last_sign_in_at
    end
  end
end
```

**Comment by SingleShot** [comment]
Oh man. I'm such a newb. Thanks!
