### ISSUE TITLE
Trouble adding ActiveAdmin into engine

### ISSUE THREAD

**Issue by wendy0402** [activeadmin/activeadmin#3735]
Hi, I tried to move my admin page into mountable engine. It cannot work properly.when I tried to go to my admin page it says `No route matches [GET] "/dashboard"` , but when i check the route it exists. Anybody know what is wrong? I follow the instruction in https://github.com/activeadmin/activeadmin/wiki/Define-a-resource-inside-an-engine but does not go well.
somebody please help me, thank you

**Comment by timoschilling** [comment]
Have you read this: https://github.com/activeadmin/activeadmin/wiki/Define-a-resource-inside-an-engine

And you can take a look on this: https://github.com/timoschilling/activeadmin/tree/info_pages (the last 4 commits)

**Comment by wendy0402** [comment]
now I get this error `uninitialized constant UsersPortal::DashboardController` it is improvement, but I already add the namespace. I actually, have 2 different namespace, does it give effect?
I have one more question. if I want to mount it, should I use the same name with the link?
e.g: 
`mount UsersPortal::Engine => "/users_portal", as: :users_portal`
while the config : 
```
config.namespace :users_portal do |users|
    users.site_title = "Portal"
    users.site_title_link = "/users_portal"
    users.authentication_method = :authenticate_users_portal_user!
    users.current_user_method = :current_users_portal_user
end
```

**Comment by wendy0402** [comment]
I already solved the problem. I was give wrong files to be loaded, thank you. By the way, don't you think it will be nice to add more detail for the wiki about Define a resource inside an engine ?

**Comment by timoschilling** [comment]
Feel Free to add more details.

**Comment by timoschilling** [comment]
This issue can be closed?

**Comment by wendy0402** [comment]
yes, thank you for the fast response
