### ISSUE TITLE
routes generator not working when using custom devise user

### ISSUE THREAD

**Issue by xylolink** [activeadmin/activeadmin#3737]
In my application, I have a custom user, in a specific namespace Main::User.
When I generate active_admin:install, the generator doesn't add the following line to routes.rb :

```
ActiveAdmin.routes(self)
```

instead it creates 

```
devise_for :users, class_name: "Main::User"
```

whereas I already have a route for devise actions like this : 

```
  devise_for  :users,  class_name: 'Main::User',
              path: 'session',
              path_names: { sign_in: 'login', sign_out: 'logout'},
              controllers: { registrations: 'users/registrations'}
```

I solved the issue by removing the created line and adding manually : 

```
ActiveAdmin.routes(self)
```

just after my own "devise_for" call

**Comment by deivid-rodriguez** [comment]
@xylolink Could you check if this is still a problem?
