### ISSUE TITLE
ArgumentError when updating

### ISSUE THREAD

**Issue by agmattbrand** [activeadmin/activeadmin#3740]
I am getting an ArgumentError when I update a model in ActiveAdmin.  I'm using Rails 4.2 with:

gem 'activeadmin', github: 'activeadmin'
gem 'inherited_resources', github: 'josevalim/inherited_resources', branch: 'rails-4-2'

The error is on this line (line # 75 of actionpack (4.2.0) lib/action_controller/metal/redirecting.rb):
self.location      = _compute_redirect_to_location(request, options)

The model changes I made do get saved properly...just doesn't redirect.

Any ideas?

Thanks,

**Comment by timoschilling** [comment]
Please provide a longer stacktrace.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
