### ISSUE TITLE
Ignore blank nested parameters doesn't work

### ISSUE THREAD

**Issue by lucianosousa** [activeadmin/activeadmin#3741]
I'm trying remove a blank password field in my nested resource and doesn't work properly.

scenario:
```
  permit_params :name, responsible_attributes: [:name, :email, :password, :id, :_destroy]
```

test1
```
    def update
      params[:enterprise]["responsible_attributes"].delete("password") if
       params[:enterprise]["responsible_attributes"]["password"].blank?
      update!
    end
```

test2
```
  controller do
    def update
      params[:enterprise]["responsible_attributes"].delete("password")
      update!
    end
```

both cases:
```
SystemStackError - stack level too deep:
```

Can someone reproduce the same error to confirm this?

Thanks

**Comment by timoschilling** [comment]
Try this:
```ruby
  def update
    permitted_params[:enterprise]["responsible_attributes"].delete("password") if
      permitted_params[:enterprise]["responsible_attributes"]["password"].blank?
    update!
  end
```

**Comment by lucianosousa** [comment]
@timoschilling I tried before, and now.
It doesn't remove the field password. I received an password blank error

**Comment by timoschilling** [comment]
```ruby
permit_params do
  responsible_attributes  = [:name, :email, :id, :_destroy]
  responsible_attributes << :password if params[:password].present?
  [:name, responsible_attributes: responsible_attributes]
end
```

**Comment by lucianosousa** [comment]
Updated rails and activeadmin and same error:

```
SystemStackError (stack level too deep):
  actionpack (4.1.9) lib/action_dispatch/middleware/reloader.rb:79
```

also:
```
Unpermitted parameters: password
```
my params doesn't have password on the update request

**Comment by timoschilling** [comment]
Ok, try to delete the param in a `before_action` (`before_filter`).

**Comment by lucianosousa** [comment]
@timoschilling the permit_params do/end solution works in a new project I created here.
The project this error is happening there is decorator(draper) and another dependencies that may be the problem. I'm still trying discover where is the problem but it can happen for some active admin integration with another gem.
Could you please keep this issue open until I discover why this problem is happening?

**Comment by timoschilling** [comment]
Please try the `before_action` way, it should work with decorators

**Comment by lucianosousa** [comment]
Oh man... Didn't work

**Comment by lucianosousa** [comment]
using params...delete()
```
SystemStackError (stack level too deep):
  actionpack (4.1.9) lib/action_dispatch/middleware/reloader.rb:79
```

using permitted_params...delete()
error password is blank

**Comment by timoschilling** [comment]
Have you tried the before filter way?

**Comment by lucianosousa** [comment]
yes, I tried. doesn't work and happened what I said above

**Comment by timoschilling** [comment]
Please provide the code for all your tries.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
