### ISSUE TITLE
turbolinks and batch select 

### ISSUE THREAD

**Issue by nextbyte** [activeadmin/activeadmin#3744]
If I enable turbolinks selecting items for batch actions is not working anymore. When I click the checkbox I get the following error in console:

Uncaught Error: cannot call methods on aaDropdownMenu prior to initialization; attempted to call method 'enable'

 Any idea were to look to fix it?

![aa-turbolinks-error](https://cloud.githubusercontent.com/assets/88761/5753468/a49b2e68-9c92-11e4-9126-bcf810a2db44.png)

**Comment by nextbyte** [comment]
There are some javascript blocks that need to be ran on document:ready/page:load events I'll fix them

**Comment by timoschilling** [comment]
Can you test this PR #3287?

**Comment by nextbyte** [comment]
That is a different issue, doesn't help with this issue

**Comment by timoschilling** [comment]
Is my understanding right? It is the same kind of problem, but with other JS code?

**Comment by nextbyte** [comment]
In that PR the problem was that some events were triggered twice. I think he might had jquery-turbolinks gem also because turbolinks gem only doesn't trigger anything on document ready just on page:load. 

In my case the checkbox in the header that should select all items loaded in the page is not working properly because drop menu was not initialized yet. For example in dropdown-menu.js.cofee I had to change 

$ ->
  $('.dropdown_menu').aaDropdownMenu()

to 

$(document).on 'ready page:load', ->
  $('.dropdown_menu').aaDropdownMenu()

**Comment by timoschilling** [comment]
Would you like to provide a pull request for that. Does we have more places with this problem in our JS code?

**Comment by nextbyte** [comment]
Yes, I am working on it. I think I fixed all from the lib folder I'll check if there are some in other places also.

**Comment by nextbyte** [comment]
https://github.com/activeadmin/activeadmin/pull/3753

**Comment by timoschilling** [comment]
closed by #3753
