### ISSUE TITLE
Coffeescript dependency generating .coffee files for non-coffeescript users

### ISSUE THREAD

**Issue by JGailor** [activeadmin/activeadmin#3746]
For people not using Coffeescript, the current master branch has a coffee-rails dependency that is causing Rails generators to create .coffee files instead of .js.

Relevant Gemfile.lock segment:

    activeadmin (1.0.0.pre)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.4, != 1.5.0)
      jquery-rails
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack (~> 1.3)
      sass-rails

**Comment by timoschilling** [comment]
I don't understand what you want to tell us.

**Comment by JGailor** [comment]
For people who do not use coffeescript in their rails app, and have removed the coffee-rails gem, the rails generators are now generating coffeescript files again instead of javascript files.  To me this is introducing unexpected behavior into the rest of the application and I would consider it a bug.

**Comment by seanlinsley** [comment]
I'm not at a computer right now, but I believe we can rely on the coffee-script-source gem to still allow Our CoffeeScript files to be usable without causing this issue.

**Comment by seanlinsley** [comment]
Maybe not: https://github.com/rails/coffee-rails/blob/master/lib/coffee/rails/template_handler.rb

**Comment by timoschilling** [comment]
I think this is not a ActiveAdmin issue, Rails or Coffee script should have a config option or commandline flag for which js template should be used.

**Comment by timoschilling** [comment]
The Rails Generator has a command line flag for that.

`rails g scaffold --help`:
```
Asset options:
  -j, [--javascripts], [--no-javascripts]       # Generate JavaScripts
                                                # Default: true
  -je, [--javascript-engine=JAVASCRIPT_ENGINE]  # Engine for JavaScripts
                                                # Default: coffee
```

And it can be configured:
```ruby
    config.generators do |g|
      g.javascript_engine "javascriptscript" # maybe `javascriptscript` is not the right value
    end
```

**Comment by JGailor** [comment]
The following both work:

rails g controller Simple --javascript-engine=js 

- or - 

config.generators do |g|
  g.javascript_engine "js"
end

The first is pretty onerous to ask someone to do every they use a rails generator that will generate javascript, but the second form is a handy solution.  Having documentation on the readme would probably prevent people from getting tripped up on this.

I'm still amazed that Rails does not let you isolate this library dependency more cleanly.

**Comment by timoschilling** [comment]
Feel free to create PR to add this to the docs Gotchas page
