### ISSUE TITLE
Brand new Rails 4.2.0 app with Devise generates asset error when trying to login

### ISSUE THREAD

**Issue by spemmons** [activeadmin/activeadmin#3756]
There error says:

```
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( active_admin/nested_menu_arrow.gif )` to `config/initializers/assets.rb` and restart your server
  (in ***/app/assets/stylesheets/active_admin.css.scss)
```

Steps to reproduce involve `rails new` then adding `gem 'activeadmin',git: 'https://github.com/activeadmin/activeadmin.git'`.

Any advice? TIA -SE-

**Comment by spemmons** [comment]
I was able to get past the error by adding `Rails.application.config.assets.precompile += %w(active_admin/*.gif active_admin/*.png)` as suggested in the error message, but this seems brittle. Can't this be accounted for in the Rails Engine somewhere?

**Comment by timoschilling** [comment]
Please look up the versions from the following gems in your Gemfile.lock:
* rails
* sprockets
* sprocket-rails
* sass
* sass-rails

**Comment by spemmons** [comment]
Here's what I've got...
rails (4.2.0)
sprockets (2.12.3)
sprockets-rails (2.2.3)
sass (3.4.10)
sass-rails (5.0.1)

**Comment by timoschilling** [comment]
can you check something for me? Does it happen with sass-rails 4.x?

**Comment by spemmons** [comment]
I can try. My use of sass-rails in the Gemfile specifies ~>5.0 as generated by `rails new`. Not sure if 4.X will work...

**Comment by timoschilling** [comment]
I't should be, sass-rails 4 has the same rails dependency as sass-rails 5

**Comment by spemmons** [comment]
OK, looks like this was just my bad luck. According to this issue (https://github.com/rails/sprockets-rails/issues/217), sprockets-rails 2.2.3 was just released and introduces this issue. I have downgraded to 2.2.2 and everything is working! Closing since there is no action for this team...

**Comment by spemmons** [comment]
... and even better: 2.2.4 has just been released reverting the breaking change! :-)
