### ISSUE TITLE
Git clone failing with error about repo being disabled

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#3757]
A couple people have [reported](https://botbot.me/freenode/activeadmin/msg/30262407/), and I've confirmed that trying to clone the repo is currently failing. This ticket is for tracking the issue.

**Comment by seanlinsley** [comment]
Emailed this to support@github.com:

>When trying to clone Active Admin via the URL git://github.com/activeadmin/activeadmin.git, multiple people have reported that they’re getting this error:

>
```
fatal: remote error: 
  Repository `activeadmin/activeadmin' is disabled. Please ask the owner to check their account.
```
>The account is definitely not disabled. Any idea what the issue is?

>If you’d like to reply there, we’re tracking this as a ticket: https://github.com/activeadmin/activeadmin/issues/3757

>Thanks,

>Sean Linsley

**Comment by coryodaniel** [comment]
Just a heads up if you are needing a repo, I have a fork that is about 8 days old... I was able to get the ref I needed out of it.

**Comment by jeffutter** [comment]
I was one of the users having problems before. I just managed to pull from the repo no problem. Not sure if it is resolved for everyone, but it works for me.

**Comment by timoschilling** [comment]
I can't confirm this, clone via HTTP and SSH works, maybe a temp problem?

**Comment by seanlinsley** [comment]
Looks like they've resolved the issue on their side. I got this response:

> Hi Sean,

>Really sorry about that, a bug on our end caused the repository and a few others to lock. All of the affected repositories should be available again now. We restored availability to activeadmin/activeadmin at 7:10pm (PST).

>Best regards,
John
