### ISSUE TITLE
SystemStackError: stack level too deep while installing activeadmin 1.0.0.pre

### ISSUE THREAD

**Issue by redyaffle** [activeadmin/activeadmin#3759]
I created a new rails project with ruby 2.2.0, rails 4.2 and added activeadmin to the Gemfile, tracking activeadmin master. When I did a bundle install I got the following error: 

```
SystemStackError: stack level too deep
An error occurred while installing activeadmin (1.0.0.pre), and Bundler cannot continue.
```

For reference, my Gemfile: 

```
source 'https://rubygems.org'

ruby '2.2.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'

gem 'jquery-rails'
gem 'turbolinks'

gem 'activeadmin', github: 'activeadmin'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
```

Other than adding ActiveAdmin, the only change dependency from a basic rails install is the use of pg instead of sqlite. There are a couple of gems (coffee-rails) that were removed. I'm using bundler 1.7.12.

**Comment by timoschilling** [comment]
Could you please try a different bundler version, or delete your gem folder and then try again

**Comment by redyaffle** [comment]
After reinstalling rvm, ruby, and all the gems, this issue clears itself up. Looks like a complication of my recent Yosemite upgrade. I'll close this issue out.
