### ISSUE TITLE
batch actions on a model with default_scope

### ISSUE THREAD

**Issue by Vizvamitra** [activeadmin/activeadmin#3764]
In my app I have a model with default scope. In some cases admin user can through activeadmin create records of this model that are outside the default scope. The problem is, in this case when admin tries to perform a default batch action :destroy on these records, activeadmin can't find them.

Here is a string in [:destroy batch action sources](https://github.com/activeadmin/activeadmin/blob/abe59fdc6cd73803bd94e6b8403b9df9ec11d947/lib/active_admin/batch_actions/resource_extension.rb#L70) that performs find and destroy:

     active_admin_config.resource_class.find(selected_ids).each { |r| r.destroy }

where `active_admin_config.resource_class` is my model. So it performs MyModel.find(ids), and records with those ids are not in the default scope, and I get RecordNotFound error.

It there anything I can do with that without writing 15 lines of code that redefines :destroy batch action just to change that one line (`active_admin_config.resource_class` => `MyModel.unscoped`)

**Comment by timoschilling** [comment]
There are 3 ways:
1. `remove_batch_action : destroy` and rewrite them
2. redefine `find` on your Models
```ruby
ActiveRecord::Base.class_eval do
  def find(*args)
    unscoped.find(*args)
  end
end
```
3. write a PR to change this :wink: 

You point me to a other problem, it looks like the destroy batch action doesn't respect the constraints form cancan.

**Comment by Fivell** [comment]
@timoschilling, how do you think  should default batch actions to use ```find_resource``` DSL method and/or  ```method_for_find ```  instead of direct `find` ? I mean this implementation of resource retrieving   https://github.com/activeadmin/activeadmin/blob/802ccd2ff2a9d3051122034afe733b794af8c54d/lib/active_admin/resource.rb#L146

**Comment by timoschilling** [comment]
@Fivell yes that's a solution for @Vizvamitra problem. But it doesn't fix the cancan problem. And maybe `find_resource` has the same issue

**Comment by timoschilling** [comment]
And it solves @Vizvamitra problem only if he writes a finder method wich calls unscoped. I think we should fix this by using the `end_of_assioisation_chain` method and using `find_resource`

**Comment by Fivell** [comment]
@timoschilling , maybe ```DataAccess``` module can be used,  there is one more ```find_resource``` in data_access which call collections, which is already authorised.
https://github.com/activeadmin/activeadmin/blob/c47ac2ae669fa9722afd9bcdd0509ce12d1d0e24/lib/active_admin/resource_controller/data_access.rb#L106

**Comment by timoschilling** [comment]
@Fivell :+1:

**Comment by Fivell** [comment]
@timoschilling, can you take a look https://github.com/Fivell/activeadmin/commit/7688519c8fd0e258615b2fb6c040c88b1f3050b9

There are 2 changes
  - it authorises each object before destroying
  - it uses collection method from DataAccess

**Comment by Fivell** [comment]
UPD, no it sucks. For batch actions ```find_collection``` must be different , 
sort of 
```ruby
 collection = scoped_collection
 collection = apply_authorization_scope(collection)
 collection = apply_collection_decorator(collection)
```

**Comment by timoschilling** [comment]
You mean the other appliements are a problem?

The only problem that I can see is the `apply_pagination`.

**Comment by Fivell** [comment]
@timoschilling 
```
  collection = apply_sorting(collection)
  collection = apply_filtering(collection)
  collection = apply_scoping(collection)
```
this lines are problematic, because in the time when user selecting checkboxes, records  can be changed by other users , in this case when batch action start processing , such records can not exist in scope anymore

**Comment by timoschilling** [comment]
OK, I understand, but this is not a problem for sorting.

**Comment by timoschilling** [comment]
What do you think can we do to solve this?

**Comment by Fivell** [comment]
@timoschilling, ```find_collection``` is root,  it should be different for batch actions and default index. It is easy to fix to make conditions like for pagination, but this way code smells. We need to refactor somehow DataAccess module to make it reusable for different situations but I have no clean idea in my mind right now .....

**Comment by timoschilling** [comment]
Just a idea:
```ruby
APPLIES = [:authorization_scope, :sorting, :filtering, :scoping, :includes, :pagination, :collection_decorator]

def find_collection(*options)
  collection = scoped_collection

  (APPLIES && options.fetch(:except, []).each do |applyer|
    collection = collection.send("apply_#{applyer}")
  end

  collection
end
```

**Comment by timoschilling** [comment]
Or `:except` maybe not as `find_collection` options, but as `DataAccess` args.

**Comment by Fivell** [comment]
@timoschilling , I've got your point about ```except```,  we also can use ```only``` too like in some other places.

so I can call 

```
find_collection(only: authorization_scope, :filtering)
```

But I don't get about ```DataAccess``` args.

**Comment by timoschilling** [comment]
> But I don't get about DataAccess args.

Forget the that. I had `DataAccess.new(except: : authorization_scope)` on my mind, but DataAccess is a Module not a Class.

And maybe we can find a way to do this [`unless request.format == 'text/csv'`](https://github.com/activeadmin/activeadmin/blob/c47ac2ae669fa9722afd9bcdd0509ce12d1d0e24/lib/active_admin/resource_controller/data_access.rb#L54) out side of `DataAccess`

**Comment by Fivell** [comment]
> And maybe we can find a way to do this unless request.format == 'text/csv' out side of DataAccess

@timoschilling ,I think it is possible even now , tell me if I wrong
https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/csv_builder.rb#L43

```ruby
@collection = controller.send(:collection)
``` 
can be changed to 
```ruby
@collection = controller.send(:collection).except(:offset, :limit)
```
I like this idea of custom collection building very much, It will help to implement in future this https://github.com/activeadmin/activeadmin/issues/2375 
In theory on server side it will be possible to apply just filters to authorised collection and perform bulk update on thousand of records at one `update_all`

**Comment by Fivell** [comment]
I will try to improve in this branch https://github.com/Fivell/activeadmin/tree/collection_method_refactoring

**Comment by dmitry** [comment]
I also had similar issue with `default_scope` and `find_resource` method from `Resource` class: https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource.rb#L147 Looks like it should be also `unscoped`.

**Comment by timoschilling** [comment]
With `unscoped` `find_resource` we get a new problem.

I think people often use `default_scope` in the wrong way.

Bad way:
```ruby
class Vehicle
  scope :rentable, -> { where(away: false) }
end

class Car < Vehicle
  default_scope -> { rentable.where("weight < 3.5") }
end

class Truck < Vehicle
  default_scope -> { rentable.where("weight > 3.5") }
end

# Frontend:
Car.all.each { |car| ... }
Truck.all.each { |truck| ... }

# Backend:
Car.unscoped.all.each { |car| ... }
Truck.unscoped.all.each { |truck| ... }

# Ability:
if user.trucker?
  can :manage, Truck
else
  can :manage, Car
end
```

You see the problem? In the Backend each user can manage each `Vehicle` while the `weight` limitation is removed by the `unscoped`.

Good way:
```ruby
class Vehicle
  scope :rentable, -> { where(away: false) }
end

class Car < Vehicle
  default_scope -> { where("weight < 3.5") }
end

class Truck < Vehicle
  default_scope -> { where("weight > 3.5") }
end

# Frontend:
Car.rentable.all.each { |car| ... }
Truck.rentable.all.each { |truck| ... }

# Backend:
Car.all.each { |car| ... }
Truck.all.each { |truck| ... }

# Ability:
if user.trucker?
  can :manage, Truck
else
  can :manage, Car
end
```

Now I don't run in a case where I need to `unscoped` the class in the backend.

**Comment by timoschilling** [comment]
And we should include `apply_scoping` for the `destroy` batch action, while the creteria for the deletion should deal by the current state of the object in the db and not the old one in the browser list.
For example someone leave the index list open for a while, delete all thinks that he see in a scope, but some else have removed it form this scope, so this item should not delete.

**Comment by Fivell** [comment]
@timoschilling ,  in this case we should use ```apply_filtering```  as well, how do you think?

**Comment by dmitry** [comment]
In one of the applications we have an issue with https://github.com/radar/paranoia and https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/view_helpers/breadcrumb_helper.rb#L18 (`BreadcrumbHelper` and `find_resource`). If the record was destroyed, it's `default_scope`ing with `where(deleted_at: false)` and cannot be found, in result we have no record found error, although were have redefined `scoped_collection`. Actually, `BreadcrumbHelper` should use the same method for finding the resource as the `scoped_collection` (https://github.com/activeadmin/activeadmin/blob/c47ac2ae669fa9722afd9bcdd0509ce12d1d0e24/lib/active_admin/resource_controller/data_access.rb#L73), but how to be with the parents in this case I don't know.

**Comment by timoschilling** [comment]
@Fivell what do you think, can we close this now?

**Comment by Fivell** [comment]
@timoschilling, BatchActions now use DataAccess to retrieve records, so I think yes
