### ISSUE TITLE
ActiveAdmin creates commets routes while commets are disabled

### ISSUE THREAD

**Issue by chumakoff** [activeadmin/activeadmin#3766]
I have set the option  'config.comments = false'  in my initializers/active_admin.rb file.   

But, including 'ActiveAdmin.routes(self)' to my config/routes.rb file creates the following routes, which should not be created:

  * admin/comments#index
  * admin/comments#create
  * admin/comments#show

Is there a way to avoid this ?

**Comment by timoschilling** [comment]
No, not at the moment, while you can reenable comments pre resource.

Is the not used comments controller a problem for you?

**Comment by chumakoff** [comment]
Yes. I have created my own Admin::CommentsController and it conflicts with ActiveAdmin's CommentsController. Changing the name under which comments are registered in initializers/active_admin.rb file solve the problem.  

config.comments_registration_name = 'AdminComment'

Thank you for quick answer !
