### ISSUE TITLE
Index pages should link to edit action if show action is disabled

### ISSUE THREAD

**Issue by momolog** [activeadmin/activeadmin#3767]
In `Model` we can disable the show action like so:
```
ActiveAdmin.register Model do
  actions :all, :except => [:show]
```
Now if in `OtherModel` we link to an associated user:
```
ActiveAdmin.register OtherModel do
  index do
    column :model
  end
```
AA will generate links to the `Model` instances but still generate links to the show action instead of to the edit action, as one would expect.
This will result in an exception for the user clicking the link.

**Comment by timoschilling** [comment]
@momolog you mean your first `Model` is the `User` model?

**Comment by timoschilling** [comment]
Should be fixed now by #3754

**Comment by momolog** [comment]
That's exactly what I meant, thanks. Will try it out right now.

**Comment by momolog** [comment]
Works correctly now, thanks!
