### ISSUE TITLE
I18n translation for update button missing

### ISSUE THREAD

**Issue by momolog** [activeadmin/activeadmin#3768]
The localization key for the update action button used to be 

    helpers.submit.update

and allowed for values like 

    '%{model} aktualisieren'

Now defining this key in locales other than english does not have an effect anymore.

**Comment by timoschilling** [comment]
1. ActiveAdmin don't have / use a `helpers.submit.update` key
2. I think you mean the button under the update form, this button translation come form formtastic you use the `formtastic_i18n` gem

**Comment by momolog** [comment]
I defined a model `User` where in app/admin/user.rb it says:

```
form do |f|
  ...
  f.actions
end
```

I would expect that with german locale the action buttons are both translated to german, but in fact they say "Update Nutzer" (wrong) and "Abbrechen" (correct).

using
- activeadmin 15687751fa9ff637a7b39aae36d6b35abdb8fed4
- formtastic (3.1.3)
- formtastic_i18n (0.1.1)

The translation for update is defined in formtastic_i18n (I checked) but not used.
