### ISSUE TITLE
Inputs in has_many not displayed

### ISSUE THREAD

**Issue by catclinic** [activeadmin/activeadmin#3769]
Hi everyone,

I have three models organized as follows:
- Eleve has many Representant
- Representant in turns has one Adressecommunication

Here's what they look like. I have tried to trim them a bit for the sake of simplicity so I hope I didn't forget anything.

    class Eleve < ActiveRecord::Base
      has_many :eleves_representants, :foreign_key =>  :eleve_numec, :primary_key => :numec
      has_many :representants, through: :eleves_representants
      accepts_nested_attributes_for :representants
    end

    class Representant < ActiveRecord::Base
      has_many :eleves_representants, :foreign_key =>  :representant_numec, :primary_key => :numec
      has_many :eleves, through: :eleves_representants
      has_one :adressecommunication, :foreign_key =>  :numec
      accepts_nested_attributes_for :adressecommunication
    end

    class Adressecommunication < ActiveRecord::Base
        belongs_to :representant, :foreign_key =>  :numec
    end

Here's a simplified version of my form:

    form do |f|
    f.inputs "Détails" do
        f.input :nom
    end  
    f.inputs "Scolarité" do
        f.input :code_division
    end
    f.has_many :representants, heading: 'Representants', new_record: true do |r|
        r.input :nom
        r.inputs :for => [:adressecommunication, (r.object.adressecommunication || r.object.build_adressecommunication)] do |a|
        a.input :adresse1
        end
    end
    f.actions
    end

The problem here is that when clicking "Add Representant", I get my r.input displayed correctly but my  a.input :adresse1 is not displayed, although aborting in the for loop (abort (a.input :adresse1).inpect) shows that it exists. It looks like that:

    "<li class=\"string input optional stringish\" id=\"eleve_representants_attributes_NEW_REPRESENTANT_RECORD_adressecommunication_attributes_adresse1_input\"><label class=\"label\" for=\"eleve_representants_attributes_NEW_REPRESENTANT_RECORD_adressecommunication_attributes_adresse1\">Etage, couloir, escalier, n° d’appartement</label><input id=\"eleve_representants_attributes_NEW_REPRESENTANT_RECORD_adressecommunication_attributes_adresse1\" maxlength=\"250\" name=\"eleve[representants_attributes][NEW_REPRESENTANT_RECORD][adressecommunication_attributes][adresse1]\" type=\"text\" />\n\n</li>"

I have been spending a fair amount of hours on that, trying almost everything to get this sorted out but alas, to no avail. Need to know if this is a bug or just me going crazy.

Thanks !

**Comment by timoschilling** [comment]
You try to use the formtastic solution for `has_many`, active admin has his own one, take a look on:
https://github.com/activeadmin/activeadmin/blob/7aef260921d418d904d2dba9b1a97eed893e9019/docs/5-forms.md#nested-resources

**Comment by nextbyte** [comment]
I have the same problem and I don't understand what is wrong in that example, how do we specify that we want to use has_many from active admin? Also I checked with the debugger and it goes to has_many from /lib/active_admin/views/components/active_admin_form.rb
