### ISSUE TITLE
Class data showing up above form file inputs

### ISSUE THREAD

**Issue by torreyj** [activeadmin/activeadmin#3773]
All of a sudden I'm getting server class object data showing up above my file inputs in my forms. 
![screen shot 2015-01-29 at 11 12 01 am](https://cloud.githubusercontent.com/assets/6643464/5962191/bb6ce8aa-a7a7-11e4-93d7-bd3f83553666.png)

Anybody else seeing this? Is there a fix?

**Comment by timoschilling** [comment]
Please post your form.

**Comment by torreyj** [comment]
It's on all of them that have the file input... but here's an example of one.  The class showes up above the f.input.  It's in a <ol> tag

  form do |f|
    f.inputs 'Buyers Info' do
      f.input :name, :label => 'Buyer Name:', :required => true
      f.input :location, :label => 'Location:'
      f.input :buyer_image, :label => 'Buyers Image:', :required => true, :as => :file, :hint => f.object.buyer_image.present? ? f.template.image_tag(f.object.buyer_image.url(:large), id: 'blah') : f.template.content_tag(:img, '',{ alt: "no image uploaded yet", id: 'blah'})
      f.input :active, :label => 'Make Active?'
    end
    f.actions
  end

**Comment by timoschilling** [comment]
part double of #3559, solution https://github.com/activeadmin/activeadmin/issues/3559#issuecomment-67382422
