### ISSUE TITLE
Labels suddenly stopped working on login screen

### ISSUE THREAD

**Issue by aaronsakowski** [activeadmin/activeadmin#3777]
I can't figure out why on a recent deploy my admin login screen suddenly started looking like this. Can someone point me in the right direction? Rails 4.0 and 4.1 (tried with both) and ActiveAdmin 1.0.0.pre.

![login neighborly](https://cloud.githubusercontent.com/assets/963659/5969841/18fe60da-a7de-11e4-929a-162f5ec3649c.png)

**Comment by timoschilling** [comment]
please show the markup of one of the input label's and of the button.

**Comment by aaronsakowski** [comment]
Sure. Here's the markup of the main elements of the form. The labels are being rendered like so: ```&lt;p&gt;active_admin.devise.email.title&lt;/p&gt;```

    <form accept-charset="UTF-8" action="/admin/login" class="formtastic admin_user" id="session_new" method="post" novalidate="novalidate"><div style="display:none"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="cnfXPtoClHe/MriL2Z5CMZrYuIvxtXjc8wegdTodDLE=" /></div><fieldset class="inputs"><ol><li class="email input required autofocus stringish" id="admin_user_email_input"><label class="label" for="admin_user_email">&lt;p&gt;active_admin.devise.email.title&lt;/p&gt;<abbr title="required">*</abbr></label><input autofocus="autofocus" id="admin_user_email" maxlength="255" name="admin_user[email]" type="email" value="" />

    </li><li class="password input required stringish" id="admin_user_password_input"><label class="label" for="admin_user_password">&lt;p&gt;active_admin.devise.password.title&lt;/p&gt;<abbr title="required">*</abbr></label><input id="admin_user_password" maxlength="128" name="admin_user[password]" type="password" />

    </li><li class="boolean input optional" id="admin_user_remember_me_input"><input name="admin_user[remember_me]" type="hidden" value="0" /><label class="" for="admin_user_remember_me"><input id="admin_user_remember_me" name="admin_user[remember_me]" type="checkbox" value="1" />&lt;p&gt;active_admin.devise.login.remember_me&lt;/p&gt;</label>

    </li></ol></fieldset><fieldset class="actions"><ol><li class="action input_action " id="admin_user_submit_action"><input name="commit" type="submit" value="&lt;p&gt;active_admin.devise.login.submit&lt;/p&gt;" /></li></ol></fieldset></form>

  
    <a href="/admin/password/new">Forgot your password?</a><br />

**Comment by timoschilling** [comment]
For me it sound like a Formtastic problem, this is the source of the related file:
```erb
<div id="login">
  <h2><%= render_or_call_method_or_proc_on(self, active_admin_application.site_title) %> <%= title t('active_admin.devise.login.title') %></h2>

  <% scope = Devise::Mapping.find_scope!(resource_name) %>
  <%= active_admin_form_for(resource, as: resource_name, url: send(:"#{scope}_session_path"), html: { id: "session_new" }) do |f|
    f.inputs do
      resource.class.authentication_keys.each_with_index { |key, index|
        f.input key, label: t('active_admin.devise.'+key.to_s+'.title'), input_html: { autofocus: index.zero? }
      }
      f.input :password, label: t('active_admin.devise.password.title')
      f.input :remember_me, label: t('active_admin.devise.login.remember_me'), as: :boolean if devise_mapping.rememberable?
    end
    f.actions do
      f.action :submit, label: t('active_admin.devise.login.submit'), button_html: { value: t('active_admin.devise.login.submit') }
    end
  end
  %>

  <%= render partial: "active_admin/devise/shared/links" %>
</div>
```

Can you post your Formtastic version.

**Comment by aaronsakowski** [comment]
Here u go.
formtastic (3.1.3)
formtastic_i18n (0.1.1)

**Comment by dmitry** [comment]
I have the same issue and the worst thing, it's not easy to get fork and fix, because the issue is with the RedCloth gem and it must be compiled in a special way and bundled into a gem before placing it into a `Gemfile`. So please vote for this PR: https://github.com/jgarber/redcloth/pull/19 if you would like to fix it, or as one of the possible options how to fix this issue is might be changing of using `t` translation alias to `I18n.t` in every erb template.

**Comment by aaronsakowski** [comment]
Thanks dmitry. At least now I know why it's happening.

**Comment by timoschilling** [comment]
This should work as hotfix:
```ruby
require "redcloth"
class ERB::Util
  alias t translate
  module_function :t
end
```

Closed while a external problem and can't be solved by active admin

**Comment by dmitry** [comment]
Why not to change `t` to `I18n.t` in every .erb file?

**Comment by timoschilling** [comment]
While t != I18n.t

**Comment by dmitry** [comment]
I see, but is there are anything used from `t` (https://github.com/rails/rails/blob/master/actionview/lib/action_view/helpers/translation_helper.rb#L38)?

**Comment by timoschilling** [comment]
Maybe some one want to overwrite the rails `t`, using `I18n.t` feel's wrong to me.
And it's a problem introduced by `redcloth`, so `redcloth` should fix it.

If ActiveAdmin will fix every bug that is introduced by a gem, ActiveAdmin will be full of workarounds.

**Comment by aaronsakowski** [comment]
Agreed. Seems like overkill to modify ActiveAdmin to fix problems with other gems. I switched from Redcloth to Redcarpet and that fixed things for me.

**Comment by codingluke** [comment]
I run into the same problem. I could fix it with an initializer like this:
```ruby
# Fixes I18n.t alias t in ERB Templates
# https://github.com/jgarber/redcloth/blob/master/lib/redcloth/erb_extension.rb
require "redcloth"
class ERB
  module Util
    def translate(s)
      if s && s.respond_to?(:to_s)
        I18n.t(s)
      end
    end

    alias t translate
    module_function :t
  end
end
```
The Example above was not working and for my usecase t => I18n.t ;)

**Comment by introvert** [comment]
My heart is hurting me with those monkey fixes..

**Comment by rishabhtayal** [comment]
@codingluke What file did you put this in?
