### ISSUE TITLE
Authorization for custom member_action and action_item

### ISSUE THREAD

**Issue by kushkella** [activeadmin/activeadmin#3778]
Hello,

AA supports authorization for CURD operations, but it doesn't play nicely with custom member actions and action items. I've seen the docs mentioning the use of `authorize!` in member actions. It does solve the problem, but we should have some DRY way of implementing authorization for `member_action` and `action_item`. In my current application, I've applied a global before_filter to all actions except the standard CRUD actions that AA already handles. The before_filter calls authorize! method with action name. Also, I've extended the ActionItems view to call `authorized?(action_item.name)` before rendering each action_item. Do you guys think  if it makes sense to apply authorization by default to all member actions and action items?

Thanks

**Comment by Fivell** [comment]
@kushkella , ```authorize_resource!``` always called using ```resource```   method  -> https://github.com/activeadmin/activeadmin/blob/c47ac2ae669fa9722afd9bcdd0509ce12d1d0e24/lib/active_admin/resource_controller/data_access.rb#L91 

```authorize_resource!``` checks for current action  https://github.com/activeadmin/activeadmin/blob/0bfb53fe41df2996083b9a5bc07000b32152bbdc/lib/active_admin/base_controller/authorization.rb#L65


so it works behind the scenes 
```ruby
 member_action :approve, method: :put do
    begin
     resource.appove!  #<-- use resource here  
      flash[:notice] = "Order approved!"
    rescue StandardError => e
      logger.warn { e.message }
      logger.warn { e.backtrace.join("\n") }
      flash[:warning] = e.message
    end
    redirect_to :back
  end
```

**Comment by kushkella** [comment]
Thanks a lot for the clarification. Since I was using a custom resource method, the authorization was not being applied. In that case I guess the only issue is to disable rendering of action items based on authorization. Thanks!

**Comment by timoschilling** [comment]
Maybe we can build a generic authorization around member_action's and action_item's. In any case we should improve the documentation about this

**Comment by ccallebs** [comment]
@timoschilling Would something like this work? (resource_dsl.rb)

``` RUBY
    def action(set, name, options = {}, &block)
      set << ControllerAction.new(name, options)
      title = options.delete(:title)

      controller do
        before_filter(only: [name]) { resource } if options[:authorize!] == true # this line
        before_filter(only: [name]) { @page_title = title } if title
        define_method(name, &block || Proc.new{})
      end
    end
```

**Comment by kushkella** [comment]
As @Fivell suggested if we use `resource` method in `member_action`, it calls `authorized_resource!`, which I think is sufficient. If anybody uses a custom resource method for any reason, he can call `authorize_resource!` method in the `member_action`. If we implement something like @ccallebs suggested, we will have to redefine `resource` method such that `authorize_resource!` is not called when `resource` is used within `member_action`, otherwise it may show different behavior because of two layers of authorization. 

The main problem that still remains is that if a member_action is not authorized, then action_item related to it should not be displayed. I think when defining action_item, we should have options `if` and `unless` that accept lambdas. And based on the return value of lambda the `action_item` should be rendered or not. We can probably extend the same approach to `member_action` to be consistent or for people who do not use standard `resource` method within `member_action`.

Thanks!
