### ISSUE TITLE
Dropdown menu js error

### ISSUE THREAD

**Issue by IslamAzab** [activeadmin/activeadmin#3779]
I am using activeadmin 0.6.5, coffee-script-source 1.8.0. When I coffee-script-source was updated to 1.9.0, I kept getting error [here] (https://github.com/activeadmin/activeadmin/blob/v0.6.5/app/assets/javascripts/active_admin/components/jquery.aa.dropdown-menu.js.coffee#L13).
```
constructor: (@options, @element) ->

    @$element = $(@element)

    defaults = {
      fadeInDuration: 20,
      fadeOutDuration: 100,
      onClickActionItemCallback: null
    }

    @options = $.extend({}, defaults, options)
```
I was getting 'options is not defined'.

When I reverted back to coffee-script-source 1.8.0, everything worked fine.

**Comment by timoschilling** [comment]
closed by 081c5fd
