### ISSUE TITLE
undefined method `except' for #<OpenStruct count=0>

### ISSUE THREAD

**Issue by trenchwarfare** [activeadmin/activeadmin#3782]
I get the error 

```ruby
undefined method `except' for #<OpenStruct count=0>
```

When trying to access the user alerts page inside activeadmin.

ruby 2.1.5
rails 4.0.x

```
Gemfile.lock:
 remote: git://github.com/activeadmin/activeadmin.git
  revision: 41043fa9aecc47f04eefc6322eea89a7bd4b0876
  specs:
    activeadmin (1.0.0.pre)
    ....
```

The problem model in question:

```ruby
class UserAlert < ActiveRecord::Base
  belongs_to :user

  ALERT_TYPES = [:item_added_without_nom]

  def self.remove_any(args)
    completed = where(
      user_id: args[:user_id], 
      alert_type: args[:alert_type], 
      alerted_name: args[:alerted_name], 
      alerted_id: args[:alerted_id])

    completed.destroy_all unless completed.nil?
  end

end
```

Default ActiveAdmin generation
```ruby
ActiveAdmin.register UserAlert do


  # See permitted parameters documentation:
  # https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#setting-up-strong-parameters
  #
  # permit_params :list, :of, :attributes, :on, :model
  #
  # or
  #
  # permit_params do
  #   permitted = [:permitted, :attributes]
  #   permitted << :other if resource.something?
  #   permitted
  # end


end
```

here's a better_errors view, if that would help

![screen shot 2015-02-05 at 12 57 53 pm](https://cloud.githubusercontent.com/assets/3596468/6066965/a398b1d4-ad36-11e4-8446-410913ca6078.png)

**Comment by timoschilling** [comment]
I think that's not a ActiveAdmin bug.

ActiveAdmin don't use `OpenStruct`'s in the code, only in some tests.

That could have some reasons:
1. you have `scoped_collection` overwrite someware
2. you set `@user_alert` someware
3. you have `find_collection` overwrite someware
4. you have a fancy decorator someware

Please check that and please post your `User` model and every place where you use `OpenStruck` in your code.

**Comment by trenchwarfare** [comment]
Just figured it out - 

Correct! #3 - the variable was being set somewhere else, and would return as an openstruct with some default attributes. Issue solved. Thank you :)
