### ISSUE TITLE
config.assets.prefix is ignored

### ISSUE THREAD

**Issue by volkert** [activeadmin/activeadmin#3784]
I'm using the latest source from the master branch with Rails 4.2. It seems to be that ActiveAdmin completely ignores the value for config.assets.prefix in all environments. No matter what I set, the path is always 'www.host.com/stylesheets/active_admin.css' etc.

This was not the case a few weeks/months ago. Unfortunately I can't tell when this error occured exactly, I'm using the master branch for a while now. Any ideas?

**Comment by timoschilling** [comment]
double of #3654
