### ISSUE TITLE
git://github.com/activeadmin/activeadmin.git (at master) is not yet checked out. Run `bundle install` first.

### ISSUE THREAD

**Issue by optimum-dulopin** [activeadmin/activeadmin#3786]
Hi,

can't understand why but since yesterday when I tape :
rails console
it return git://github.com/activeadmin/activeadmin.git (at master) is not yet checked out. Run `bundle install` first.
and go back to ubuntu shell.

rails server is working fine

I use ruby 2.2.0
bundle show activeadmin
xxxxxxx/bundler/gems/activeadmin-2fd42a3502fe
bundle -v
Bundler version 1.7.13

rails 4.1.9
edit : 
Im using rvm, so I was trying with ruby 2.1.5 , but still same problem. I also remove ruby 2.2.0 and reinstall it with all the gem, and still same problem. I read related other issue on https://github.com/activeadmin/activeadmin/issues/2899 but nothing seems to be working

**Comment by ajgon** [comment]
Are you using `spring` gem? Had the same problem, commenting out
```
  gem 'spring'
  gem 'spring-commands-rspec'
```

did the trick for me...

**Comment by timoschilling** [comment]
have you tried to remove this folder `xxxxxxx/bundler/gems/activeadmin-2fd42a3502fe` and try it again, maybe you need to remove your complete bundler foulder

**Comment by svyatov** [comment]
Same error for me. I figured it's correlated to `spring` gem and that error occurs for `spring` v1.3.0, but for v1.2.0 everything is fine. Not sure where the actual problem is - `activeadmin` or `spring` :(

**Comment by alexbottoni** [comment]
Same error for me, too. Commenting out Spring as suggested by ajgon fixed it.
(Ruby 2.2.0,  Rails 4.2.0, ActiveAdmin Pre 1.0 from github)

**Comment by timoschilling** [comment]
I'm closing this while 3 people confirmed that it is a spring problem.

**Comment by amalagaura** [comment]
Wow thank you. I never would have guessed it was a problem with spring. I was trying so many different things.

**Comment by philduffy** [comment]
Hmmm. I'm hitting it without spring

```
➜  gdi-new-site git:(master) ✗ bundle | grep activeadmin
Using activeadmin 1.0.0.pre from https://github.com/activeadmin/activeadmin.git (at master)
➜  gdi-new-site git:(master) ✗ rails c
https://github.com/activeadmin/activeadmin.git (at master) is not yet checked out. Run `bundle install` first.
➜  gdi-new-site git:(master) ✗ spring stop
Spring is not running
➜  gdi-new-site git:(master) ✗ rails c
https://github.com/activeadmin/activeadmin.git (at master) is not yet checked out. Run `bundle install` first.
```

**Comment by amalagaura** [comment]
Do you have spring in your gemfile? That is what we had to remove to get it working.

**Comment by ThomasTheFourth** [comment]
Thank you Algon, removing spring fixed it for me.

**Comment by jvenezia** [comment]
The solution is to regenerate spring binstubs https://github.com/rails/spring/issues/387 

`bundle exec spring binstub --all`

**Comment by erose** [comment]
Removing spring just fixed this for me too. Thank you so much.
