### ISSUE TITLE
undefined method `page_action' for ActiveAdmin::ResourceDSL  in latest activeadmin

### ISSUE THREAD

**Issue by modsaid** [activeadmin/activeadmin#3787]
I'm on the latest rails 4.1.6 and the development version of activeadmin

for some reason it seems that page_action is unknown... has it been removed?

**Comment by timoschilling** [comment]
`page_action` is only available for pages (`ActiveAdmin.register_page)` not for resources (`ActiveAdmin.register`).

**Comment by modsaid** [comment]
Thank you @timoschilling
