### ISSUE TITLE
Deprecation Warning - Active Admin

### ISSUE THREAD

**Issue by iamgenius** [activeadmin/activeadmin#3788]
Receive this error when trying to issue the following command: 

rails generate active_admin:install

DEPRECATION WARNING: Support for Rails < 4.1.0 will be dropped. (called from <top (required)> at /home/hguerrier/.bundler/ruby/1.9.1/activeadmin-3f916d6bee73/lib/active_admin.rb:8)
/home/hguerrier/active_admin/config/application.rb:10:in `<module:ActiveAdmin>': superclass mismatch for class Application (TypeError)
        from /home/hguerrier/active_admin/config/application.rb:9:in `<top (required)>'
        from /var/lib/gems/1.9.1/gems/railties-4.0.2/lib/rails/commands.rb:43:in `require'
        from /var/lib/gems/1.9.1/gems/railties-4.0.2/lib/rails/commands.rb:43:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

I hope this is a known issue...

**Comment by timoschilling** [comment]
This message come from Formtastic. `active_admin.rb` Line 8 is the loading of Formtastic.
