### ISSUE TITLE
NoMethodError when working with nested resources 

### ISSUE THREAD

**Issue by schneiderderek** [activeadmin/activeadmin#3791]
I am getting a `NoMethodError undefined method '<<' for nil:NilClass` when calling `has_many` in the form DSL. 

Here is some additional information that will hopefully help. I've omitted some stuff for brevity.

Here is what I have for the active admin resource 'config':
```
ActiveAdmin.register College do
  config.filters = false
  actions :all, :except => [:destroy]

  permit_params :name, :description, location_attributes: [:city]

  form do |f|
    f.semantic_errors
    f.input :name
    f.input :description

    f.inputs do
      f.has_many :location do |l| # The error is being raised here
        l.input :city
      end
    end

    f.actions
  end

end
```

Here is my model:
```
class College < ActiveRecord::Base
  has_one :location, inverse_of: :college, class_name: 'CollegeLocation'

  accepts_nested_attributes_for :location
end
```

I've also attached a couple of screenshots of the error page. 
![screenshot 2015-02-12 20 39 20](https://cloud.githubusercontent.com/assets/2245041/6180763/5fa24c62-b2f7-11e4-85a5-4c2d048262cb.png)
![screenshot 2015-02-12 20 39 34](https://cloud.githubusercontent.com/assets/2245041/6180765/61145c70-b2f7-11e4-851b-a9002461c255.png)

I'm not sure if I have something misconfigured or if this is a bug? Any help would be greatly appreciated. Thanks!

**Comment by davydovanton** [comment]
Sorry, but why do you use `has_one` association in model and `has_many` in active admin edit page form?

**Comment by schneiderderek** [comment]
@davydovanton The docs indicate that you can use `has_many` even if your model is using `has_one`. See: https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md#nested-resources

Also, just to double check, I switched it to `has_one` and I got this:
`undefined method `has_one' for #<ActiveAdmin::Views::ActiveAdminForm:0x007fa741221330>`

So it looks like there is definitely no `has_one` for the form DSL.

**Comment by ccallebs** [comment]
Try this:

``` RUBY
f.inputs do
  f.object.build_location unless f.object.location
  f.has_many :location do |l|
    l.input :city
  end
end
```

**Comment by schneiderderek** [comment]
@ccallebs Thanks for the reply! That did the trick. Everything is working as expected now.
