### ISSUE TITLE
Batch action popover not working

### ISSUE THREAD

**Issue by iurifq** [activeadmin/activeadmin#3793]
I'm using activeadmin master and the batch actions menu is not working. I'm getting a JS error on Chrome

```
Uncaught TypeError: undefined is not a function
```

The error happens on this line

```coffee
  $('.dropdown_button').popover()
```

https://github.com/activeadmin/activeadmin/blob/762d2b9b376dc41cbc1e5016361b314597913212/app/assets/javascripts/active_admin/application.js.coffee#L16

`$('.dropdown_button')` is always empty and I couldn't find any occurrence of this class in the codebase.

Is anyone else experiencing the same issue?

**Comment by timoschilling** [comment]
I think `$('.dropdown_button').popover()` is a outdated pease of code that has replaces by [dropdown-menu.js.coffee](https://github.com/activeadmin/activeadmin/blob/51faef09fe27cdf84568cd00b10ccb9ee8a26151/app/assets/javascripts/active_admin/lib/dropdown-menu.js.coffee).

**Comment by iurifq** [comment]
Great, thanks :wink:

**Comment by iurifq** [comment]
That error went away, but the batch actions dropdown still doesn't work. I'm getting the same error but on another line.

```coffee
$('#active_admin_content .tabs').tabs()
```

https://github.com/activeadmin/activeadmin/blob/master/app/assets/javascripts/active_admin/application.js.coffee#L25

I've commented it out but the batch actions dropdown keeps disabled when I select some records.

**Comment by timoschilling** [comment]
I already thought before that this was not the solution to your problem.

Do you use a other javascript framework then jQuery in your app?

If yes, make sure that his files are not loaded into ActiveAdmin.

**Comment by iurifq** [comment]
Well, I've discovered that there were files not being required in my application. It was working in Rails 3, but after I upgraded to 4 and started to use the master branch it stopped working.

In my `active_admin.js.coffee`, there were some jquery and jquery-ui stuff and this

```
#= require active_admin/application
```

I've changed it to

```
#= require active_admin/base
```

This required all the dependencies and I could remove the requires for jquery stuff. Everything came back to work without errors.

**Comment by javierjulio** [comment]
@iurifq when you mentioned everything worked again, did that include the popovers? Or did you switch to using dropdown_menu?

@timoschilling when I asked about popovers you showed a modal dialog but the popover is something else. It definitely is the same as the dropdown_menu but I can't tell for sure if dropdown_menu has replaced it. Is it safe to remove to popover related code or I should leave it and just remove (or ignore) the CSS? Happy to take care of this just didn't want to mess up anything if popover is meant to still be supported.

**Comment by timoschilling** [comment]
@javierjulio please repost the to me related part of your comment in #3862

**Comment by javierjulio** [comment]
@timoschilling this was [my comment](https://github.com/activeadmin/activeadmin/pull/3862#issuecomment-86816281) and then yours immediately following it where you have two screenshots. I've modified and cleaned up dropdown_menu. I still have yet to get to modal_dialogs but I will start on that next. Its the popover component that I'm unsure of. When attempting to use the following in a test app I don't see anything (the generated HTML is set to display:none) but that's because these components generate just the list that appears when you hit a button (the dropdown menu provides both button and drop down list) so:

```ruby
    batch_action_popover do
      action ActiveAdmin::BatchAction.new( :action_1, "Action 1" )
      action ActiveAdmin::BatchAction.new( :action_2, "Action 2" )
      action ActiveAdmin::BatchAction.new( :action_3, "Action 3" )
    end

    action_list_popover id: "my_awesome_action_list_popover" do
      action "My First Great Action", "#"
      action "My Second Great Action", "http://www.google.com"
    end
```

But I don't understand what they could be used for seeing how they don't do anything useful and if they did dropdown_menu already does that and more.
