### ISSUE TITLE
Don't know what context to use

### ISSUE THREAD

**Issue by michaellouieloria** [activeadmin/activeadmin#3794]
I'm getting the error "Don't know what context to use " whenever I visit the index page.

The other pages like admin dashboard, new and edit are working properly.

ActiveAdmin.register ServiceProviderCategory do
  permit_params :name  
  index do
    column :name
    actions
  end
end

**Comment by timoschilling** [comment]
ActiveAdmin has no error message like "Don't know what context to use".
Please provide a stacktrace.

PS: Use the Github Markdown [syntax-highlighting](https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting) next time you post code.

**Comment by michaellouieloria** [comment]
/home/mic/.rvm/gems/ruby-2.1.1/bundler/gems/ransack-3e4b6e34abc4/lib/ransack/context.rb:30:in `for'
/home/mic/.rvm/gems/ruby-2.1.1/bundler/gems/ransack-3e4b6e34abc4/lib/ransack/search.rb:32:in `initialize'
I'm currently using rails 4.1.0
Gemfile
gem 'activeadmin', github: 'activeadmin'
gem 'ransack',     github: 'activerecord-hackery/ransack'

I can't use gem 'ransack', github: 'activerecord-hackery/ransack', branch: 'rails-4.1' because activeadmin is asking for diff. version

/home/mic/.rvm/gems/ruby-2.1.1/bundler/gems/ransack-3e4b6e34abc4/lib/ransack/adapters/active_record/base.rb:15:in `new'
/home/mic/.rvm/gems/ruby-2.1.1/bundler/gems/ransack-3e4b6e34abc4/lib/ransack/adapters/active_record/base.rb:15:in `ransack'
activerecord (4.1.0) lib/active_record/relation/delegation.rb:94:in `public_send'
activerecord (4.1.0) lib/active_record/relation/delegation.rb:94:in `block in method_missing'
activerecord (4.1.0) lib/active_record/relation.rb:286:in `scoping'
activerecord (4.1.0) lib/active_record/relation/delegation.rb:94:in `method_missing'
/home/mic/.rvm/gems/ruby-2.1.1/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/resource_controller/data_access.rb:228:in `apply_filtering'
/home/mic/.rvm/gems/ruby-2.1.1/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/resource_controller/data_access.rb:50:in `find_collection'
/home/mic/.rvm/gems/ruby-2.1.1/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/resource_controller/data_access.rb:32:in `collection'
inherited_resources (1.6.0) lib/inherited_resources/actions.rb:7:in `index'
/home/mic/.rvm/gems/ruby-2.1.1/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (4.1.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.0) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.0) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.0) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.0) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.0) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.0) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.1.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.0) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:80:in `call'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:48:in `call'
actionpack (4.1.0) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.1.0) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.0) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.0) lib/action_dispatch/routing/route_set.rb:676:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.1.0) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
activerecord (4.1.0) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.0) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
better_errors (2.1.1) lib/better_errors/middleware.rb:59:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.0) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.0) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.0) lib/rails/engine.rb:514:in `call'
railties (4.1.0) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in `catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in `process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
rack (1.5.2) lib/rack/server.rb:264:in `start'
railties (4.1.0) lib/rails/commands/server.rb:69:in `start'
railties (4.1.0) lib/rails/commands/commands_tasks.rb:81:in `block in server'
railties (4.1.0) lib/rails/commands/commands_tasks.rb:76:in `tap'
railties (4.1.0) lib/rails/commands/commands_tasks.rb:76:in `server'
railties (4.1.0) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
railties (4.1.0) lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:8:in `require'
bin/rails:8:in `<main>'

**Comment by michaellouieloria** [comment]
solution is
gem 'ransack', '1.3.0'

the gem is an old version though

**Comment by treenewbee** [comment]
use old ransack version just not working for me, better to remove the ransack dependency version?

https://github.com/activeadmin/activeadmin/pull/3938
