### ISSUE TITLE
Possible regression when overriding controller actions, not using activeadmin layout

### ISSUE THREAD

**Issue by amalagaura** [activeadmin/activeadmin#3796]
I overrode a controller action (inside `controller do` block and when it rendered it was not using the activeadmin layout. There was a blank layout.

Is that expected behavior? To behave as I needed I had to give it:

```
      render layout: 'active_admin'
```
at the end of the controller method.

**Comment by timoschilling** [comment]
Please provide a common complete code example.

**Comment by amalagaura** [comment]
```
ActiveAdmin.register Model::Info do
  menu false
  config.clear_action_items!
  config.filters = false

  actions :edit, :update

  controller do
    def edit
      item        = Item.find(params[:id])

      # Without the following line I get no layout, not even the application layout
      render layout: 'active_admin'
    end
  end
end
```

**Comment by timoschilling** [comment]
I can't reproduce this, can you provide a small test app to reproduce this?

**Comment by timoschilling** [comment]
Or maybe it come from a layout overwrite in your `ApplicationController`

**Comment by amalagaura** [comment]
If it is not easily reproducible I think it is not worth getting into. It is a minor issue and probably caused by some weird gem incompatibilities.

I shouldn't have bothered you guys without doing the small test app myself. Sorry for the trouble.
