### ISSUE TITLE
undefined method `setup' for ActiveAdmin:Module

### ISSUE THREAD

**Issue by shah743** [activeadmin/activeadmin#3798]
I update activeadmin gem on my development machine before update it works fine. But now when i run rake db:migrate or rails s it gives me following error
config/initializers/active_admin.rb:1:in `<top (required)>': undefined method `setup' for ActiveAdmin:Module (NoMethodError)

**Comment by timoschilling** [comment]
Add `require "activeadmin"` to your initializer should fix that problem. Thats not necessary in general, but in some cases rails autoloading can not work if you have already a ActiveAdmin constant, for example if you extend the `ActiveAdmin` module somewhere in you code.

**Comment by rokkit** [comment]
I had this error and this solution helped me
