### ISSUE TITLE
Add sortable attribute on index table

### ISSUE THREAD

**Issue by lordjavac** [activeadmin/activeadmin#3800]
Since there is some built-in drag-and-drop sorting functionality in there already, why not expand that to allow for drag-and-drop sorting of the index table (or grid)?

There is a plugin that does this for the table (activeadmin-sortable), but it looks a little different and it'd be nice to have a unified syntax for sortable collections. Also unified indicators and cursor behaviors would be nice.

```ruby
index sortable: :position do
  # columns
end
```

**Comment by timoschilling** [comment]
How do you want to deal with sorting and pagination?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by lordjavac** [comment]
Sorry, I somehow missed the initial notification of your response. The simplest solution would be to sort the records by the specified column and disable other sorting criteria. As for pagination, you could have a drop target that moved the dragged record after the last visible row (or before the first one if not on the first page). It would be somewhat cumbersome to move an item many pages, but doable.

i think any other setup would simply be too confusing to use properly.
