### ISSUE TITLE
Batch Actions forms use wrong path for nested, optional resources

### ISSUE THREAD

**Issue by sfoop** [activeadmin/activeadmin#3801]
Say you have a nested resource, Forum > User, where User's belong_to is optional. If you use batch_action to define batch actions on User, the generated HTML form's 'action' field will point to /admin/user/batch_action, rather than /admin/forum/1/user/batch_action. This prevents custom batch actions from doing what they need to do, because (in this example), they won't be able to access forum 1. If you remove the belong_to's optional: true, the batch action works properly with the correctly generated form path.

This comes down to the implementation of ResourceExtension's batch_action_path, which relies on route_collection_path.

**Comment by JeansReal** [comment]
+1

**Comment by kaelumania** [comment]
+1

**Comment by javierjulio** [comment]
@sfoop sounds like you have a good idea on what's wrong. We'd love a PR to fix this!

**Comment by javierjulio** [comment]
There is a PR for this. Would appreciate any help in updating it. Thank you.
