### ISSUE TITLE
PunditAdapter doesn't mark the action as verified_authorized

### ISSUE THREAD

**Issue by hajpoj** [activeadmin/activeadmin#3806]
Pundit has a way to ensure that pundit is being used via [the verify_authorized after_action](https://github.com/elabs/pundit#ensuring-policies-are-used)

```
class ApplicationController < ActionController::Base
  after_action :verify_authorized, :except => :index
end
```

However even though pundit is being used by active admin it still fails in this callback. The reason is with normal pundit usage, you use the `authorize` method which set's an instance variable `@_policy_authorized = true`. Then `verify_authorize` check's `@_policy_authorized` to see if it's true and if its not, it throws an error. 

the PunditAdapter doesn't use the `authorize` method, so `@_policy_authorized` isn't ever set and `verify_authorize` always fails. 

A current workaround is to skip the `verify_authorize` for active admin controllers:

```
after_action :verify_authorized, unless: :active_admin_controller?

def active_admin_controller?
  is_a?(ActiveAdmin::BaseController)
end
```

Though it would be nice to have verify_authorize work with active_admin, I'm currently not sure what the correct solution is.

**Comment by timoschilling** [comment]
To use `authorize` is not possible in ActiveAdmin, because of the way that the AuthorizeAdapter works.
We have the same problem with cancan(can) by the way.

We can change the `PunditAdapter` to set the `@_policy_authorized` variable.

**Comment by hajpoj** [comment]
Ah i see. It seems like it would be useful to make AA seamlessly work with pundit, however I guess a con would be that we are accessing an internal instance variable.

**Comment by dkniffin** [comment]
I've just run into this problem as well, and after thinking about it for a bit, I think @hajpoj's "workaround" is actually the right solution here. Pundit aims to be as minimal as possible, and do as little "magic" as possible behind the scenes, so I think most of pundit's users would prefer to do this step manually, so they know how Pundit and AA are working together.

To that end, I think we should add that snippet to the documentation. I will make a PR for that.
