### ISSUE TITLE
Option to include boilerplate code in new resource generation

### ISSUE THREAD

**Issue by dpmccabe** [activeadmin/activeadmin#3807]
When you create a new resource, the default capabilities for that resource (index columns, filters, form fields, etc.) are all of the ones for that model. This makes perfect sense: You get everything unless you specify otherwise. This is accomplished by the following file:

    ActiveAdmin.register Partner do
    end

Now what if I just want to remove a single column from the index table, show page, filters, and form? Well, great, now I have to write all of those blocks from scratch because the generator gave me nothing to start with. This is a _lot_ of tedious work if there are many columns in the database table. I've used AA on a dozen projects and I've wasted so much time copying boilerplate code from other resource files into one I just created, manually entering index table columns, specifying filters, etc., just to make a slightly less full version of the default resource.

A new resource includes all possible information and features by default. A new resource _file_ includes no information and features. This makes no sense. Is AA's philosophy to provide an admin tool that lets developers start from everything or start from nothing? It can't be both simultaneously.

I understand that the point of the blank resource file is to ensure the actual pages work regardless of what changes in the underlying model. But who actually uses blank resource files? I've never done it and any production app is going to have some customization in every resource file.

The generator should at least provide a sensible default template that includes boilerplate code using the model's current columns for the index columns, filters, form fields, and show fields.

**Comment by ccallebs** [comment]
@dpmccabe I like this idea, but the question remains what should be included and what should be omitted?

I suppose *everything* could be generated (and just commented out, with documentation/explanations). Deleting code is certainly easier than writing it.

**Comment by dpmccabe** [comment]
I'm thinking that whatever you see when you load the actual pages should be what appears in the code. This might not be the default behavior, but rather something available in an alternate generator.

**Comment by ccallebs** [comment]
@dpmccabe I think I get what you mean, but there's a *lot* that we could show. For example, the `controller do` block could be populated with each of the actions. That seems like overkill.

I'd propose each of the pages (index, show, form), the filters, and the action visibility.

**Comment by timoschilling** [comment]
closed by #3825
