### ISSUE TITLE
Dymanic parent label menu

### ISSUE THREAD

**Issue by krim** [activeadmin/activeadmin#3813]
I want to use dynamic parent on menu.
So, i try to use proc, but it didn't work:
menu label: Client.model_name.human,
          parent: proc { "#{ I18n.t('active_admin.users') } (#{User.non_moderated_count })" }.call

How i can create dynamic parent label?

**Comment by timoschilling** [comment]
I can't tell you the right answer now, but it can't work with a `.call` at the end.

**Comment by krim** [comment]
I understand it, but how i can do dynamic parent label?

**Comment by timoschilling** [comment]
Take a look into the docs https://github.com/activeadmin/activeadmin/blob/6bde1f57ec5f9b724c21e5af146678f4ade839bc/docs/2-resource-customization.md#dynamic-parent-menu-items
