### ISSUE TITLE
Formtastic :date_picker input unstyled

### ISSUE THREAD

**Issue by ccallebs** [activeadmin/activeadmin#3817]
For code:

``` RUBY
filter :variation
filter :experiment
filter :template
filter :from_date_gteq, label: "From", as: :date_picker
filter :to_date_lteq, label: "To", as: :date_picker
filter :category
```

It generates the following filters:

![screen shot 2015-02-25 at 12 17 30 pm](https://cloud.githubusercontent.com/assets/397982/6375926/6f38ea5a-bce8-11e4-9a79-ef414b4d2e24.png)

It would be nice if the date picker style was more consistent with the rest of the filters. If this is something you want to pursue, I can work on it.

**Comment by timoschilling** [comment]
:+1:

**Comment by ccallebs** [comment]
@timoschilling Additionally, the datepicker control only renders on WebKit. This is *expected*, as the other browsers don't support the input. However, I'll add something in to make it cross-browser compatible.
