### ISSUE TITLE
Problem with active_admin:install

### ISSUE THREAD

**Issue by projectxxx** [activeadmin/activeadmin#3820]
Hello everyone, 
when i generate active:admin:install, it`s give this error: 
"/home/user1/.rvm/gems/ruby-2.1.4@rails418/bundler/gems/activeadmin-a0bf8da21b7a/lib/generators/active_admin/devise/devise_generator.rb:21:in `rescue in install_devise': uninitialized constant ActiveAdmin::Generators::DeviseGenerator::DependencyError (NameError)
".
I install devise without problems, but the error is still there.  
Good day and thank you.

**Comment by hail2skins** [comment]
I am having the precise same error.

uninitialized constant ActiveAdmin::Generators::DeviseGenerator::DependencyError

This is a brand new app.   Devise is the latest available gem.   ActiveAdmin is being gathered from master.

**Comment by hail2skins** [comment]
When I run the install with the skip-users flag, things do start, but then I get an error from line 1 of the active_admin.rb file:

uninitialized constant ActiveAdmin (NameError)

**Comment by hail2skins** [comment]
So, I think I have it installed.

After running the active admin install with the --skip-users flag, I got the error mentioned above.   I added the "hack" require 'activeadmin' to the top of the active_admin.rb file.   I then got a java runtime error, but I hadn't installed nodejs on my instance.   

Once by that I was able to run the install without the skip-users flag and it seems to have worked.

**Comment by timoschilling** [comment]
@projectxxx's problem is closed by e27ccba8a7ea1f7f3085748decec1f6911f6d5d2

**Comment by rafapolo** [comment]
Opz. Got stuck on same error here, 
~/.rvm/gems/ruby-2.2.1/gems/activeadmin-1.0.0.pre1/lib/generators/active_admin/devise/devise_generator.rb:19:in `install_devise': uninitialized constant ActiveAdmin::Generators::DeviseGenerator::Dependency (NameError)

gem 'rails',      '4.2.1'
gem 'activeadmin',  '~> 1.0.0.pre1'
gem 'devise',       '~> 3.5'

even with --skip-user

any suggestion? thanks

**Comment by rafapolo** [comment]
Solved adding gem 'execjs' and installind nodejs.
