### ISSUE TITLE
check_authorization method with CanCanCan Adapter

### ISSUE THREAD

**Issue by reicheltd** [activeadmin/activeadmin#3827]
Hey,

Ive been trying to use the `check_authorization` method within my `application_controller.rb`. I always get get the error `CanCan::AuthorizationNotPerformed in Admin::DashboardController#index`.

`check_authorization :unless => :devise_controller?` gives me the same error.

**Comment by ccallebs** [comment]
@reicheltd You need to call `load_and_authorize_resource` beforehand.

**Comment by timoschilling** [comment]
`check_authorization` is not compatible with ActiveAdmin, you need to do something like this:
`check_authorization :unless => :activeadmin_controller?`
