### ISSUE TITLE
belongs_to form issue

### ISSUE THREAD

**Issue by navjeetc** [activeadmin/activeadmin#3828]
I have a model 

``` ruby
class Consent < ActiveRecord::Base
  belongs_to :disclosed_from_org, :class_name => "Organization", :foreign_key => "disclosed_from_orid"
  belongs_to :disclosed_to_org, :class_name => "Organization", :foreign_key => "disclosed_to_orid"
end
```

With this code in Active Admin edit form, it shows both two dropdowns for Organizations as well as two additional text fields for  disclosed_from_orid and disclosed_to_orid and no matter. How to hide showing id fields. With this no matter what I choose in dropdown, it sets the org ids in consent model to the values in text fields.

**Comment by seanlinsley** [comment]
@navjeetc this is the reason: https://github.com/activeadmin/activeadmin/issues/4298#issuecomment-185467400

**Comment by timoschilling** [comment]
That's can't be the reason. `content_columns` filter `_id`, but his fields ends with `_orid`.

**Comment by timoschilling** [comment]
@navjeetc is this still a issue for you?

**Comment by seanlinsley** [comment]
@timoschilling they're saying that the ID is showing up, and the don't want it to show up. So it's the reverse of https://github.com/activeadmin/activeadmin/issues/4298#issuecomment-185467400

**Comment by Fivell** [comment]
so looks like we should implement own content_columns that works better for our needs

**Comment by Fivell** [comment]
created ticket in formtastic repo for tracking

**Comment by Fivell** [comment]
There is a solution now. Not sure if we need to create PR for this untill get answer from formtastic mantainers. 

```ActiveAdmin::FormBuilder``` is  inherited from ```Formtastic::FormBuilder```
we can override ```default_columns_for_object``` with

```ruby
ActiveAdmin::FormBuilder.class_eval do
  def default_columns_for_object
    assoc_columns  = association_columns(:belongs_to)
    cnt_columns = content_columns
    klass = @object.class
    # remove custom foreign keys from content columns to prevent duplicated inputs
    if assoc_columns.present?
      cnt_columns -=  klass.reflections.map {|_,v| v.options[:foreign_key] }.compact
    end
    cols = asooc_columns + cnt_columns
    cols -= Formtastic::FormBuilder.skipped_columns
    cols.compact
  end
end
```


I will track it  until formtastic provide more elegant way to fix this

**Comment by Fivell** [comment]
@timoschilling , formtastic guys they will accept PR for v 4.0.

**Comment by Fivell** [comment]
fixed by https://github.com/justinfrench/formtastic/pull/1241 
until this https://github.com/activeadmin/activeadmin/issues/3828#issuecomment-279156895 can be used
