### ISSUE TITLE
double post requests

### ISSUE THREAD

**Issue by pkoltermann** [activeadmin/activeadmin#3830]
Hi,
I've got an app with AA v0.6.0 and a problem with one model create form.
This form is sometimes send twice (two requests send at the exactly same time), this was only reported on one winows 8 laptop, but it is mostly used on that form so it can occur also on other machines, probably. Also when I click on post button many times one after another before the page reloads, the form will be posted multiple times. Shouldn't there be any failsave preventing this from happening? How can I prevent it in an elegant way not messing with rails js events?

**Comment by timoschilling** [comment]
I think that can't be a ActiveAdmin issue. 

Maybe something submit the form twice.

What you can do is to disable the submit button after the click, Rails has a build in way for that, I'm not sure to use that with formtastic. Google should be your friend.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by timoschilling** [comment]
Maybe your issue is related to http://blogs.msdn.com/b/ieinternals/archive/2010/11/22/internet-explorer-post-bodies-are-zero-bytes-in-length-when-authentication-challenges-are-expected.aspx

**Comment by TakaakiFuruse** [comment]
>  Rails has a build in way for that, I'm not sure to use that with formtastic. Google should be your friend.

I just made it working. 
I got the same HTML output when I used "actions" only, so I hope this might be right.

```rb
  form do |f|
    inputs 'user' do
      input :id
      input :name
    end
    actions do
      f.action :submit, button_html: { data: {disable_with: 'please wait....' }}
      cancel_link
    end
  end
```

**Comment by Fivell** [comment]
patch to make it work globally
```
module ActiveAdmin
  module Views
    module FormtasticProxyPatch
      def action(method, options = {})
        if method.to_sym == :submit
          options = ({
            button_html: { data: { disable_with: 'Please wait...' } }
          }).deep_merge(options)
        end

        super(method, options)
      end
    end
  end
end

ActiveAdmin::Views::FormtasticProxy.send(:include, ActiveAdmin::Views::FormtasticProxyPatch)
```
