### ISSUE TITLE
Error wrong number of arguments in 'page_action' /active_admin/page_dsl

### ISSUE THREAD

**Issue by ConorLinehan** [activeadmin/activeadmin#3835]
I keep getting the following error on my machine when trying to run rails.

/Users/conorlinehan/.rvm/gems/ruby-2.0.0-p598/bundler/gems/activeadmin-b3a9f4b3e405/lib/active_admin/page_dsl.rb:21:in `page_action': wrong number of arguments (0 for 1..2) (ArgumentError)

I've tried uninstalling the gems using rvm gemset empty mygems and reinstalling but that doesnt work.

The error only comes up on one machine and persists across all branchs of the code, while the same code works on other machines.

Thanks.

**Comment by timoschilling** [comment]
Please provide the code of the related page.

Whats the difference between the machines? OS, Ruby, Processor Architecture?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
