### ISSUE TITLE
cancancan and menu in initializer

### ISSUE THREAD

**Issue by andywenk** [activeadmin/activeadmin#3837]
Hi,

I am wondering what the best way is to apply abilities to the menu and pages. We have around five different roles with different abilities. We created the menu in the active-admin initializer. I understand, that it is not possible to use the abilities there (at least I assume this - if I am wrong, please correct me). So one will most likely not use the menu creation in the initializer but in each admin controller. But there, the priority for ordering the menu is not working correctly. 

I am looking for documentation or advice how to build the menu correctly so that the abilities will be used and the priority is possible to set. We also do have sth like this in the initializer:
```ruby
    config.namespace :admin do |admin|
      admin.build_menu do |menu|
        #menu.add label: I18n.t('active_admin.menu.player.title'), priority: 10
        menu.add label: I18n.t('active_admin.menu.export.title'), priority: 20
        #menu.add label: I18n.t('active_admin.menu.statistics.title'), priority: 30
        menu.add label: I18n.t('active_admin.menu.tools.title'), priority: 50
        menu.add label: I18n.t('active_admin.menu.files.title'), priority: 60 do |fm|
          fm.add label: I18n.t('active_admin.menu.files.statistics'),        priority: 10, url: '/admin/filemanager/statistics'
          fm.add label: I18n.t('active_admin.menu.files.elv_data'),          priority: 20, url: '/admin/filemanager/elv'
          fm.add label: I18n.t('active_admin.menu.files.outgoing_data'),     priority: 30, url: '/admin/filemanager/outgoing'
          fm.add label: I18n.t('active_admin.menu.files.incoming_data'),     priority: 40, url: '/admin/filemanager/incoming'
          fm.add label: I18n.t('active_admin.menu.files.lotto_ident_done'),  priority: 50, url: '/admin/filemanager/lotto_ident_done'
          fm.add label: I18n.t('active_admin.menu.files.lotto_ident_error'), priority: 60, url: '/admin/filemanager/lotto_ident_error'
        end
        menu.add label: I18n.t('active_admin.menu.system.title'), priority: 70
      end
    end
```
As you can see, there are entries in filemanager which do not need to have an own controller. Can I also create this in the filemanager admin controller? My tryouts have been with no success.

Your help is highly appreciated

Thanks

Andy

**Comment by amuntasim** [comment]
Menu items can be shown or hidden at runtime using the :if option. 
`menu.add label: I18n.t('active_admin.menu.export.title'), priority: 20 , if: proc{ current_user.can_export? } end`

The proc will be called in the context of the view, so you have access to all your helpers and current user session information.

**Comment by andywenk** [comment]
@amuntasim thanks a lot for the info. We will check this out.

**Comment by seanlinsley** [comment]
I assume this worked for you. Please respond back if it didn't.
