### ISSUE TITLE
current_active_admin_user returns the user's URL

### ISSUE THREAD

**Issue by vassyz** [activeadmin/activeadmin#3842]
In the right side of the admin page, right next to the Logout link, there's a link with the "/admin/admin_users/1" label where my username/email should be.

I haven't used the admin on this app in a while, so I don't know what's causing it. 

I'm using Rails 4.2

**Comment by timoschilling** [comment]
Can you post your User resource file and your cancan ability file please

**Comment by vassyz** [comment]
I figured out what it was, and it's not an ActiveAdmin bug.

My app uses a login field for the user resource. It can be either an email or an username.
https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-using-their-username-or-email-address

I had to put this into my AdminUser model to make it work:

```
  attr_accessor :login

  def login
    @login || self.email
  end
  
  protected
  
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(email) = :value", { :value => login.strip.downcase }]).first
  end
```

Sorry for being a little bit out of context. You can close this issue now.
Thank you.
