### ISSUE TITLE
Scope only show one custom Chinese label

### ISSUE THREAD

**Issue by rocLv** [activeadmin/activeadmin#3844]
Hi, when I use `scope`, there are some trouble:
The follow works fine:
```ruby
  scope 'custome label', :my_scope_1
  scope 'anothe label',   :my_scope_2
```
But if I use Chinese, only first label show up in the view. Others won't display at all.

```ruby
   scope '标签1', :my_scope_1
   scope '标签2',   :my_scope_2
```

I'm using Ruby 2.1.5 and Rails 4.2, ActiveAdmin 1.0

**Comment by timoschilling** [comment]
double of #3012
