### ISSUE TITLE
Form helper for associations does not respect custom primary_key in belongs_to

### ISSUE THREAD

**Issue by killthekitten** [activeadmin/activeadmin#3846]
I have a model with an association like this:

```
class Product < ActiveRecord::Base
  belongs_to :product_group, primary_key: :custom_id, foreign_key: :custom_product_group_id
end
```

But ActiveAdmin still uses default `id` column for building options for select.

**Comment by timoschilling** [comment]
The edit/create form is generated by formtastic

**Comment by killthekitten** [comment]
@timoschilling it's still a part of a whole `activeadmin`, so I think it should be better integrated.

**Comment by timoschilling** [comment]
That's a point where we can't do anything. Building a own formbuilder is not a option. Ask on the formtastic issue tracker, maybe they will fix the bug or show you up your miss take.

**Comment by seanlinsley** [comment]
I disagree. This is a bug we should fix.

**Comment by seanlinsley** [comment]
If this is actually a bug in Formtastic, we can create a ticket there to track the bug. But we shouldn't just ignore bug reports.

**Comment by Fivell** [comment]
@killthekitten , would be nice to see more details, because I can't reproduce such behaviour with current master.

**Comment by killthekitten** [comment]
@Fivell not sure if I can, will try in a couple of days.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback. @killthekitten Feel free to reopen the issue with the information requested by @Fivell.
