### ISSUE TITLE
How to make the filters in activeadmin built-in comments work

### ISSUE THREAD

**Issue by muhammadn** [activeadmin/activeadmin#3850]
I have this code  

```
def display_name
    reference_id
end
```

in Orders.rb to show the reference_id as the Order in comments, however i cannot search it by filter in the built-in comments. I have also searched in the internet about this but i could not get the answer on how to make the built-in comments more useful in searching comments. (for example, based on reference_id)

**Comment by timoschilling** [comment]
I understand you correctly, you want a search field under `/admin/comments` where you can type in a order id to find all comments for that order?

**Comment by muhammadn** [comment]
yes, i would like to search for the reference_id string in admin/comments to get all the related comments but i do not know how.

**Comment by timoschilling** [comment]
This is not testet and just out of my mind, but it should work:
```ruby
ActiveAdmin::Comments.class_eval do
filter :resource_id
filter :resource_type, as: :select, collection: [...] # a list of your models to select wich resource type you want to find
end
```

**Comment by muhammadn** [comment]
It says
    undefined method `filter' for ActiveAdmin::Comments:Module

should i replace :resource_id with :reference_id and do i put the :resource_type as:

    filter :resource_type, as: :select, collection: [ @order, @reloads]

**Comment by timoschilling** [comment]
sorry `Comment` not `Comments`
```ruby
ActiveAdmin::Comments.class_eval do
  filter :resource_id # resource_id not reference_id
  filter :resource_type, as: :select, collection: [["Order", "order"], ["Reload", "reload"]]
end
```

What is the `reference_id`?

**Comment by muhammadn** [comment]
I get 

    NoMethodError: undefined method `filter' for #<Class:0x32c08610>

The code is

    ActiveAdmin::Comment.class_eval do
      filter :resource_id # resource_id not reference_id
      filter :resource_type, as: :select, collection: [["Order", "order"], ["Reload", "reload"]]
    end

reference_id is an order number that i created myself (not activeadmin's)

**Comment by timoschilling** [comment]
`reference_id` is on the Order Modle?

**Comment by muhammadn** [comment]
yes. reference_id is an order number in the Order model.

**Comment by javierjulio** [comment]
Closing out as stale. Would appreciate a PR to address this!

**Comment by leandro** [comment]
Hi all. Apparently, I found out a possible way to fix this problem, but unfortunately I have no time for write a formal fix for it through an ideal PR. Nonetheless here is the code (I've tested it):

```diff
diff --git a/lib/active_admin/orm/active_record/comments.rb b/lib/active_admin/orm/active_record/comments.rb
index 3350b69..a8420b5 100644
--- a/lib/active_admin/orm/active_record/comments.rb
+++ b/lib/active_admin/orm/active_record/comments.rb
@@ -8,6 +8,7 @@ ActiveAdmin::Application.inheritable_setting :comments,                   true
 ActiveAdmin::Application.inheritable_setting :comments_registration_name, 'Comment'
 ActiveAdmin::Application.inheritable_setting :comments_order,             "created_at ASC"
 ActiveAdmin::Application.inheritable_setting :comments_menu,              {}
+ActiveAdmin::Application.inheritable_setting :comments_filters,           :all

 # Insert helper modules
 ActiveAdmin::Namespace.send :include, ActiveAdmin::Comments::NamespaceHelper
@@ -76,6 +77,13 @@ ActiveAdmin.after_load do |app|

       permit_params :body, :namespace, :resource_id, :resource_type

+      if namespace.comments_filters != :all
+        namespace.comments_filters.each do |column, settings|
+          settings ||= {}
+          filter column, **settings
+        end
+      end
+
       index do
         column I18n.t('active_admin.comments.resource_type'), :resource_type
         column I18n.t('active_admin.comments.author_type'),   :author_type
diff --git a/lib/generators/active_admin/install/templates/active_admin.rb.erb b/lib/generators/active_admin/install/templates/active_admin.rb.erb
index 82fc5d6..6fea563 100644
--- a/lib/generators/active_admin/install/templates/active_admin.rb.erb
+++ b/lib/generators/active_admin/install/templates/active_admin.rb.erb
@@ -138,6 +138,12 @@ ActiveAdmin.setup do |config|
   #
   # You can customize the comment menu:
   # config.comments_menu = { parent: 'Admin', priority: 1 }
+  #
+  # You can customize the comment filters:
+  # config.comments_filters = {
+  #   author_type: { as: :check_boxes },
+  #   body: nil
+  # }

   # == Batch Actions
   #
```

Not sure though if this DSL is the best one possible.
