### ISSUE TITLE
Reason to use GH as the default way for installation (i.e. use rubgems)

### ISSUE THREAD

**Issue by emilebosch** [activeadmin/activeadmin#3852]
Hi all, what's the reason that there still isnt a active-admin gem released with an version number instead of tracking master?

It's unhandy to rely on (cause things might break). And the upgrade path is ackward, and vulnerabilites can't be added to the ruby security db because we don't maintain version numbers.

What's the reason that we just have gem with version numbers?

**Comment by timoschilling** [comment]
ActiveAdmin is to much beta at the moment, thats why it has no release yet. Equal to Rails, if you want to use Rails you need to use it from GH master. We will release a gem if we hit the 1.0.0.beta and getting a bit more stable in the api.

**Comment by emilebosch** [comment]
Hi, although this is understandable. Active admin is ran in production in many locations. There is now no way you can track vulnerabilities, or even updates or anything. I think it would be smart and wise to release gems anyway and provide upgrade paths. For all people that are tracking master its too easy to have some malicious commmit entering master and not even able to report it to rubysec vulnerability db or things such as a https://github.com/rubysec/bundler-audit.

This project has been in beta forever. Just release it with a pre. Rather being unstable, with proper upgrade paths and versions, than unstable and all bets are off. People will use it anyway.

**Comment by timoschilling** [comment]
I understand you partly, but I close this as double of #3213

**Comment by timoschilling** [comment]
Please repost your argumentation in #3213 and let us continue the discussion over there
