### ISSUE TITLE
How to add filter for number of returned records (like SQL LIMIT) on index page

### ISSUE THREAD

**Issue by skeppet** [activeadmin/activeadmin#3853]
Hi,

I'm trying to add a filter on how many records gets returned, but can't figure out how. I tried with a ransacker but didn't get it to work.

I have a Contact resource with a field called score and another one for country. I would like to make it easy for a user to sort out the top X highest scorers from country Y, so she then can use the csv export as an input for another service.

However, I can't find an easy way to limit the number of results returened. From reading here: https://github.com/activerecord-hackery/ransack/wiki/Using-Ransackers and here: http://nikhgupta.com/code/activeadmin/custom-filters-using-ransacker-in-activeadmin-interfaces/
I tried a ransacker like this:

```
ransacker :number_of_top_scorers, formatter: proc { |v| 
  Contact.all.order(score: :desc).limit(v).map(&:id)} do |parent|
    parent.table[:id]
  end
```

But it doesn't work.

Any ideas are much appreciated!

**Comment by timoschilling** [comment]
First: your ransacker is bullshit! I know it's a frequently search result, but it's wrong. The `:formater` proc is for formatting the search value and not for collecting IDs.

Second: a ransacker is for searching and not for limiting.

To your szenario: Filtering by country and sorting by score works out of the box. The limitation for the result set size is not possible. But take a look on the `active_admin_pagination` gem, it helps you to customize the pagination size on a per request base.
