### ISSUE TITLE
nested resource with many tabs

### ISSUE THREAD

**Issue by benjamin-schaefer** [activeadmin/activeadmin#3858]
Hey,

I want to do something like this:

    tabs do
      f.has_many :books  do |b|
        tab b.title do 
          b.inputs
        end
      end
    end

But if I try it, the following error occurs:

    undefined method `tab' for #<ActiveAdmin::Views::ActiveAdminForm:0x0000000bdebf88>

What am I doing wrong? Or is using tabs in nested resources not possible?

Regards,

Benjamin

**Comment by timoschilling** [comment]
That what you want to do is not possible and don't make sence in the way how has_many and tabs are working, btw.
