### ISSUE TITLE
Incorrect page title for models with a to_s method

### ISSUE THREAD

**Issue by wolfemm** [activeadmin/activeadmin#3860]
It seems that defining a `to_s` method on a model will forcefully set the page title to the fallback "(model name) #(id)" instead of using any of the methods defined in `display_name_methods`.

Consider the following model:
    
    class Chart < ActiveRecord::Base
      #...

      def name
        "test"
      end
      alias_method :to_s, :name
    end

The page title and heading for "/admin/charts/1" will be "Chart #1" instead of "test".

This only seems be happening with the page title/heading on the `show` page. `name` gets used everywhere else, breadcrumbs included. `show title: :name do [...]` would fix it, but seems unnecessary. 

I'm using ActiveAdmin 1.0.0.pre1 and Rails 4.2.0.

**Comment by wolfemm** [comment]
After some looking around, it looks like [this](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/views/pages/show.rb#L38) is causing it.

**Comment by timoschilling** [comment]
What does your `display_name_methods` looks like?

**Comment by wolfemm** [comment]
I haven't overridden it, but calling `ActiveAdmin::Application.new.display_name_methods` just to be sure returns `[:display_name, :full_name, :name, :username, :login, :title, :email, :to_s]`.

The issue seems to be that `name` and `to_s` are aliased, so `title == resource.to_s` is true when it uses `name`.

**Comment by wolfemm** [comment]
What do you think about dropping the `title == resource.to_s` condition entirely, since `DisplayHelper#display_name_method_for` already does a [more comprehensive check](https://github.com/activeadmin/activeadmin/blob/6bde1f57ec5f9b724c21e5af146678f4ade839bc/lib/active_admin/view_helpers/display_helper.rb#L30) to prevent the Kernel's `to_s`?

**Comment by timoschilling** [comment]
What doesn't work in your case, your `to_s` alias brings a `source_location`.
```ruby
class Bar
  def name
    "foo"
  end
  alias_method :to_s, :name
end
Bar.new.method(:to_s).source_location
# => ["(irb)", 2]
```

But you can simply remove `to_s` from `display_name_methods`.

**Comment by wolfemm** [comment]
I should have mentioned sooner that this problem only occurs when a title hasn't been provided to the show page.

The problem is that `ActiveAdmin::Views::Pages::Show#default_title` doesn't check if there's a source location for `to_s`. It gets the value of the model's `name` from `ActiveAdmin::ViewHelpers::DisplayHelper#display_name` (which does check for a source location), sees it matches the model's `to_s` (since they're aliased) and uses the fallback without checking if `to_s` was user-defined.

**Comment by timoschilling** [comment]
You can simply remove to_s from display_name_methods.
