### ISSUE TITLE
Breadcrumb styling selector is over-broad and should be scoped

### ISSUE THREAD

**Issue by dpehrson** [activeadmin/activeadmin#3861]
[_breadcrumbs.scss](https://github.com/activeadmin/activeadmin/blob/6bde1f57ec5f9b724c21e5af146678f4ade839bc/app/assets/stylesheets/active_admin/components/_breadcrumbs.scss#L1)

I recently added a model named `Breadcrumb` to my project (for tracking the movements of users between places) and was very confused as to why the styling of all the links in the model's attribute table were styled all weird. I quickly realized that it was because the markup produced is:

`<div class="attributes_table breadcrumb" id="attributes_table_breadcrumb_1">`

I believe we need to add a parent to the `_breadcrumb.scss` selector scoping it's styles to `#titlebar_left > .breadcrumb`

I'm happy to work on a PR when I have time, but I just wanted to get the ticket logged for discussion.

**Comment by timoschilling** [comment]
double of #2930
