### ISSUE TITLE
on amazon ec2 - error clone active admin when i try bundle install

### ISSUE THREAD

**Issue by ikaiser** [activeadmin/activeadmin#3865]
Hi all,
thanks for helpme.

I have an error:

$ bundle install
Your Gemfile lists the gem mysql2 (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of just one of them later.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Fetching git://github.com/activeadmin/activeadmin.git
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection timed out

Retrying git clone 'git://github.com/activeadmin/activeadmin.git' "/home/ubuntu/.rvm/gems/ruby-2.2.0@dettofatto/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528" --bare --no-hardlinks --quiet due to error (2/3): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/activeadmin/activeadmin.git' "/home/ubuntu/.rvm/gems/ruby-2.2.0@dettofatto/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528" --bare --no-hardlinks --quiet` in directory /home/ubuntu/projects/dettofatto has failed.
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out

Retrying git clone 'git://github.com/activeadmin/activeadmin.git' "/home/ubuntu/.rvm/gems/ruby-2.2.0@dettofatto/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528" --bare --no-hardlinks --quiet due to error (3/3): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/activeadmin/activeadmin.git' "/home/ubuntu/.rvm/gems/ruby-2.2.0@dettofatto/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528" --bare --no-hardlinks --quiet` in directory /home/ubuntu/projects/dettofatto has failed.

github.com[0: 192.30.252.130]: errno=Connection timed out

Git error: command `git clone 'git://github.com/activeadmin/activeadmin.git'
"/home/ubuntu/.rvm/gems/ruby-2.2.0@dettofatto/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528" --bare --no-hardlinks --quiet`
in directory /home/ubuntu/projects/dettofatto has failed.

why??

thanks.

**Comment by timoschilling** [comment]
Thats an network error:
```
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out
```
Ask AWS or Github, thats not a ActiveAdmin problem
