### ISSUE TITLE
missing locales

### ISSUE THREAD

**Issue by kivanio** [activeadmin/activeadmin#3866]
I've used master branch version and I started to see missing locales:

<pre>
remote: git://github.com/activeadmin/activeadmin.git
  revision: 53e85d6a2cf4f5bc083e8da7c6786b5cd69ce7a1
  specs:
    activeadmin (1.0.0.pre1)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack (~> 1.3)
      sass-rails
    formtastic (3.1.3)
    formtastic_i18n (0.2.0)
</pre>

![missing](https://cloud.githubusercontent.com/assets/5107/6869073/8e6a9766-d467-11e4-8261-c980058c7570.png)

That is not reflected in locales:
https://github.com/activeadmin/activeadmin/blob/master/config/locales/en.yml#L27
https://github.com/activeadmin/activeadmin/blob/master/config/locales/pt-BR.yml#L27

I can send a pull request but I need to know if it was a intentional change or not.

**Comment by timoschilling** [comment]
Please post the filter path of the related resource file.

**Comment by Sergey-B** [comment]
:+1: 

Missing locale for search status heading, current filters heading

![image](https://cloud.githubusercontent.com/assets/2233710/7065380/de8dec72-debf-11e4-97bb-6169b3037901.png)

filter part of the related resource file:

```ruby
  filter :title
```

**Comment by timoschilling** [comment]
@Sergey-B you talking about a other problem. Your problem is fixed in e82b68ca90e8a25f34805e9983d7353c2c33c05c. PR's for Russian locales are welcome.

**Comment by Sergey-B** [comment]
thank you, it solves my problem

**Comment by kivanio** [comment]
@timoschilling 'Search Status' panel is getting predicates names as it is named in formtastic rather than use active_admin.filters.predicates

<pre>
  filter :expire_at
</pre>

Expire At translation missing: pt-br.active_admin.filters.predicates.gteq 2015-04-14
Expire At translation missing: pt-br.active_admin.filters.predicates.lteq 2015-04-30

I can add all this missed locales there but I do not know if it is a good fix

**Comment by timoschilling** [comment]
I don't know how you get "Expire At translation missing: pt-br.active_admin.filters.predicates.lteq 2015-04-30", ActiveAdmin don't use `lteq`, `gteq` or `eq`, it only uses `less_than`, `greater_than` and `equals`.

**Comment by kivanio** [comment]
@timoschilling Yes, that's weird.

No matter what filter I use It always say that is missing locales and point to `.predicates.gteq`, `eq` or whatever other thing but never use `less_than`, `greater_than` and etc.

You can see it in images attached.

I am using last master version:
<pre>
gem 'activeadmin',                github: 'activeadmin/activeadmin'
</pre>
<pre>
GIT
  remote: git://github.com/activeadmin/activeadmin.git
  revision: c96fadb5a5e00c7fef3aa18e2a76ee9b6e4214cc
  specs:
    activeadmin (1.0.0.pre1)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails (~> 5.0)
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack (~> 1.3)
      sass-rails
</pre>

Let me know if I can do anything to help simulate.

**Comment by timoschilling** [comment]
Please post the HTML output of the filter form from `filter :expire_at`

**Comment by kivanio** [comment]
Here is it:
<pre>
  filter :expire_at
</pre>
<pre>
  filter :trusted
</pre>

 https://gist.github.com/kivanio/8bbf48dc956176e7f1ad

**Comment by joker-777** [comment]
There is another missing locale related to ransack `en.ransack.predicates.contains`.
The error happens [here](https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/lib/active_admin/filters/humanized.rb#L54) where you use the keyword `contains` but ransack uses just `cont` (https://github.com/activerecord-hackery/ransack/blob/b1cfed8fa902b4fa7b6c9438dcb88de49eeee958/lib/ransack/locale/en.yml#L47).

**Comment by dannysullivan** [comment]
We're also seeing a missing locale for `en.ransack.predicates.equals` on Active Admin 1.0.0.pre4 and Ransack 1.8.2.

**Comment by casiodk** [comment]
+1

**Comment by varyonic** [comment]
Related #4859?

**Comment by greyblake** [comment]
+1 here

**Comment by greyblake** [comment]
Also we're getting errors regarding the following translation keys:
* ` en.ransack.predicates.starts_with`
* `en.ransack.predicates.equals`

**Comment by FabioRos** [comment]
+1
