### ISSUE TITLE
AA thinks "false" means "empty" in show view

### ISSUE THREAD

**Issue by dpmccabe** [activeadmin/activeadmin#3867]
If you have a boolean attribute on a resource and have a row for that attribute in your `show` view, AA will display "true" for `true` and "empty" for `false`. Try the following:

    show do
      attributes_table do
        row :id
        row :true do |a|
          true
        end
        row :false do |a|
          false
        end
      end
    end

This yields the following:

![screen shot 2015-03-27 at 5 50 07 pm](https://cloud.githubusercontent.com/assets/527578/6878314/034092f6-d4aa-11e4-8b2f-804906192ae3.png)

This is using PostgreSQL. I'm not sure if the bug exists in other DBs.

It's not a problem on the `index` view, though, where `true` and `false` are correctly interpreted as `status_tag('yes')` and `status_tag('no')`, respectively. I think `status_tag` should also be the default behavior in show, but at the very least it shouldn't be confusing `false` with `empty`/`nil`, which are certainly different things in Ruby, falsiness aside.

**Comment by bsvin33t** [comment]
Hi @timoschilling I have created a PR for this bug in https://github.com/activeadmin/activeadmin/pull/3882

**Comment by dpmccabe** [comment]
Thanks, @bsvin33t, I've confirmed the patch is working on my original sample code and in an actual resource.
