### ISSUE TITLE
has_many issue with new 

### ISSUE THREAD

**Issue by sahild** [activeadmin/activeadmin#3876]
I have a problem with ActiveAdmin and nested form: when I create a new question with some replies, I get an error (Question can't be blank). But if I create a question and then, on update, I add some replies everything goes well.

Can anyone help me?

Here my codes

# models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :points, :text, :replies_attributes
# RELATIONS
  has_many :replies

  accepts_nested_attributes_for :replies
end

# models/reply.rb
class Reply < ActiveRecord::Base
  attr_accessible :correct, :question_id, :text, :question
# VALIDATIONS
  validates_presence_of :text, :question_id
# RELATIONS
  belongs_to :question
end

# admin/question.rb
ActiveAdmin.register Question do
  form do |f|
    f.inputs "Details" do
      f.input :text
      f.input :points
    end
    f.inputs do
      f.has_many :replies do |rp|
        rp.input :text
        rp.input :correct
      end
    end
    f.actions
  end
end

**Comment by sahild** [comment]
t's not a good solution but if i remove the validation on question_id all goes well. this looks like a very basic issue, i wonder why no-one answered this on SO
http://stackoverflow.com/questions/23130069/activeadmin-nested-form-whit-new-item

**Comment by timoschilling** [comment]
I don't see a reason to have a validation on `question_id`. And it can't work, while the validation runs before the Question is saved, so the `question_id` can't be set at that time.
