### ISSUE TITLE
Belongs_to polymorphic owner fails

### ISSUE THREAD

**Issue by noctivityinc** [activeadmin/activeadmin#3877]
I have a model that is "owned" by a polymorphic relationship called "owner:" 

```
class Task > ActiveRecord
   belongs_to :owner, polymorphic: true
end

class Student > ActiveRecord
    has_many :tasks, as: :owner
end

class Teacher > ActiveRecord
    has_many :tasks, as: :owner
end
```

And I want to be able to view the tasks for the student or teacher in AA.  When I try creating a tasks.rb file:

```
ActiveAdmin.register Board do
   belongs_to :student, :teacher, polymorphic: true
end
```

It fails as it doesnt know to use the owner id.  How can I set this up?

**Comment by timoschilling** [comment]
> ActiveAdmin.register Board do

You mean `ActiveAdmin.register Task do`?

**Comment by noctivityinc** [comment]
Yes.  sorry.  Odd.

I THINK I might have fixed this using Inherited Resources:

```
  controller do
    belongs_to :teacher, :student, :polymorphic => true

    def scoped_collection
      @teacher = Teached.find_by_id(params[:teacher_id])
      Tash.where(owner_id: @teacher.id)
    end

    def find_resource
      @teacher = Teacher.find_by_id(params[:teacher_id])
      Task.find_by_token(params[:id])
    end
  end
```

and then setting up routes in Routes.rb to resolve.  Not sure if this is the right way but seems to work

**Comment by timoschilling** [comment]
I'm closing this while polymorphic belongs_to aren't supported jet and your specific problem is solved.
