### ISSUE TITLE
ArgumentError in ActiveAdmin::Devise::Sessions#new

### ISSUE THREAD

**Issue by kpenzin** [activeadmin/activeadmin#3884]
Showing /home/***/.bundler/ruby/2.1.0/active_admin-dd5d6573f826/app/views/layouts/active_admin_logged_out.html.erb where line #9 raised: 

wrong number of arguments (3 for 2)
  (in /home/***/dev/***/app/assets/stylesheets/active_admin.css.scss)

Extracted source (around line #9):

     <title><%= [@page_title, render_or_call_method_or_proc_on(self, ActiveAdmin.application.site_title)].compact.join(" | ") %></title>
   
     <% ActiveAdmin.application.stylesheets.each do |style, options| %>
       <%= stylesheet_link_tag style, options %>
     <% end %>
     <% ActiveAdmin.application.javascripts.each do |path| %>
       <%= javascript_include_tag path %>

**Comment by timoschilling** [comment]
Please provide more informations to reproduce this problem.
Things that can help:
- Your Gemfile / Gemfile.lock
- the full stacktrace
- a test app to reproduce this problem
