### ISSUE TITLE
Active Resource support

### ISSUE THREAD

**Issue by kpenzin** [activeadmin/activeadmin#3888]
Well, I didn't find information about this. Will Active Admin support Active Resource in future? That's very important for me, beacuse our project have a lot of Active Resource models and we haven't another way to do it( this is my superior's requirement).

Sorry for mistakes if they have to be here

**Comment by timoschilling** [comment]
There is no plan to support ActiveResource natively in the future. But while ActiveResource based on ActiveModel you maybe only hack some small things. Simply create a ActiveAdmin resource with a ActiveResource as Model and look whats happen.

What we plan for the future is a ORMAdapter API, which allows you to use ActiveAdmin with every ORM, ActiveResource is nothing else then a REST ORM. Take a look on the Mongoid supprt issue (#2714), @Zhomart is working on something.

And you can take a look on the source code of the [activetrail](https://github.com/fernandes/activetrail) gem, which brings trailblazer support for activeadmin.

**Comment by Fivell** [comment]
Few days ago I was playing with ActiveResource also, here is a gist 
https://gist.github.com/Fivell/15f39050b8db7092684f

**Comment by timoschilling** [comment]
@Fivell maybe you wann to St that to the Wiki?

**Comment by kpenzin** [comment]
@Fivell  Thanks, i'll try this way.

**Comment by timoschilling** [comment]
I will close this, but if you need some more help feel free to ask here

**Comment by tokhi** [comment]
Is there any wiki pages for this? I googled a lot but couldn't find something to follow the `ActiveResource` integeration.
