### ISSUE TITLE
How to handle scopes or batch_actions per role and per action (index, show ...)?

### ISSUE THREAD

**Issue by andywenk** [activeadmin/activeadmin#3890]
Hi,

we are using the abilities in AA. So there is a role 'hotline'. This role shall not be able to see defined scopes in a registered model. The admin user is held in `current_admin_user` as usual. Now the problem:

I can't reach `current_admin_user` in `ActiveAdmin::ResourceDSL` like so:

    ActiveAdmin.register Player do
         config.batch_actions = false
         if current_admin_user.role == 'admin'
           config.batch_actions = true
         end
         ...

On the other hand, I can't set ` config.batch_actions` in an action like `index` but I can call `current_admin_user` there. I have the same problem with scopes. 

What is the correct way to achieve this. I can't find an explanation in the docs or SO (all the examples are too high level).

Thanks a lot in advance!

Cheers

Andy

**Comment by dmitry** [comment]
With scopes and batches you can use `:if` hash for defining the permission (condition when to show or hide). For more info look here: https://github.com/activeadmin/activeadmin/blob/607054214d4eaba5b59e2eab736c6a41edfc7795/lib/active_admin/batch_actions/resource_extension.rb#L107

**Comment by andywenk** [comment]
@dmitry thanks for your answer. Not sure if I understand correctly but I don't want to define batch actions. I want to be able to say

    config.batch_actions = true | false

by checking if the current_admin_user is allowed to see the batch action dropdown at all. The same for scopes.

**Comment by timoschilling** [comment]
You can't doing that!

What you do is to remove the default batch destroy and add a new one which has a if: argument with a proc. or you can hide / show the select column with a if user.admin?

**Comment by andywenk** [comment]
@timoschilling thanks for your answer. Is this by design not possible? I mean this is a plain simple recommendation and I am wondering, why this is so complicated.

**Comment by timoschilling** [comment]
It's possible by design. 

Two solutions:
1. `config.batch_actions` need's to support proc`s
2. Permissions for batch actions #2856

Or you do one of the two described workarounds

**Comment by Fivell** [comment]
@timoschilling ,  I have question, now if I hide every batch action with ```:if``` proc  I still see inactive batch action link, why it is needed? Should we change it ?

**Comment by andywenk** [comment]
@timoschilling how about scopes then? It's the same recommendation. Would it also be the solution to allow proc's?

**Comment by timoschilling** [comment]
@andywenk the scopes already supporting `if:`, see the [index docs](https://github.com/activeadmin/activeadmin/blob/6bde1f57ec5f9b724c21e5af146678f4ade839bc/docs/3-index-pages.md#index-scopes) for details.

@Fivell the hide / show of the batchaction selector is bound to the `selectable_column`. But we can change the logic to "show batchaction selector if selectable_column.visible? and batchactions.any?"

**Comment by andywenk** [comment]
@timoschilling oh thanks - have not been aware of it! Great!
