### ISSUE TITLE
Sass::SyntaxError: Undefined variable: "$em-base".

### ISSUE THREAD

**Issue by achiinto** [activeadmin/activeadmin#3892]
I am seeing this error when precompiling assets.
Sass::SyntaxError: Undefined variable: "$em-base".
  (in /..../gems/bourbon-4.2.1/app/assets/stylesheets/functions/_modular-scale.scss:21)

production.rb has this
  config.assets.compile = false
  config.assets.precompile += %w(*.svg *.eot *.woff *.ttf *.gif *.png *.ico)
  config.assets.precompile << /\A(?!active_admin).*\.(js|css)\z/

and my application is purely Active Admin application, therefore all css and js are from the ActiveAdmin. 
I tried to set the $em-base at the active_admin.css.scss but it does not help. 

Any idea how to fix this or is it a bug in the system? I do not see any installation guide that mention about this. Anyone seeing the same issue.

**Comment by timoschilling** [comment]
That seams to be a bug in the bourbon gen. Please try some different versions of that gem or ask on the bourbon issue tracker.

**Comment by achiinto** [comment]
sorry, I guess not suppose to precompile css file. Away from front-end for a while. Figure is my ngnix server setup.
