### ISSUE TITLE
Infinite tab reloading when specifying non-'pretty' title

### ISSUE THREAD

**Issue by saidie** [activeadmin/activeadmin#3894]
Hi, I encountered infinite tab reloading when I've used an UTF-8 string for `tab` method:

``` ruby
tabs do
  tab "ほげ" do # be converted something like `<a href="#">ほげ</a>`
    # ...
  end
end
# => infinite reloading
```

It seems due to an empty URL fragment of `a` tag and maybe the implementation of jQuery.
The empty URL fragment may be produced by `String#parameterize` here:
https://github.com/activeadmin/activeadmin/blob/v1.0.0.pre1/lib/active_admin/views/components/tabs.rb#L19 .
Hence, same issue would be occurred when passing non-'pretty' ASCII string such as `'...'`.

I propose several fixes for this issue:
- taking a `fragment` (or any other) option for URL fragment,
- taking a `label` option for the anchor text, or
- passing the `title` argument to `I18n.t`.

Thank you for your attention.

**Comment by ifyouseewendy** [comment]
I've encountered the same issue with Chinese character. My temp solution was monkey-patch on *String*, and use a gem to convert non-ascii characters.

```ruby
class String
  def parameterize(sep = '-')
    if self.ascii_only?
      ActiveSupport::Inflector.parameterize(self, sep)
    else
      Pinyin.t(self, splitter: '-')
    end
  end
end
```

**Comment by ShallmentMo** [comment]
我是 monkey patch 了 `active_admin/view/tabs` 的 `build_menu_item` 方法：

```ruby
ActiveAdmin::Views::Tabs.class_eval do
  def build_menu_item(title, options, &_block)
    options = options.reverse_merge({})
    li { link_to I18n.t(title), "##{title.parameterize}", options }
  end
end
```
