### ISSUE TITLE
Queries everything and assigns to @collection_before_scope and this is possibly caused by rails-footnotes

### ISSUE THREAD

**Issue by philipnery** [activeadmin/activeadmin#3898]
This problem happens both in 0.6.2 and 1.0.0.pre1. In all index pages, the last query is something like this

```
SELECT "subjects".* FROM "subjects" ORDER BY "subjects"."id" desc LIMIT 30 OFFSET 0
SELECT "subjects".* FROM "subjects" ORDER BY "subjects"."id" desc
```

It adds this last unnecessary SQL query that's slowing down the pages. I can't trace where this is coming from. 

I also noticed that all the records are being assigned to @collection_before_scope. @active_admin_authorization is also bloated. What's strange is that this also happens with something as simple as this

```
ActiveAdmin.register Login do
end
```

Any ideas what's causing this? BTW, I'm still using Rails 3.2.21

Thanks!

**Comment by timoschilling** [comment]
Are the `SELECT "subjects".* FROM "subjects" ...` happen in the `Login` resource?

**Comment by philipnery** [comment]
Hi and thanks for the quick response.

I'm sorry I wasn't clear enough. 

For login, this happens ```SELECT "logins".* FROM "logins" ORDER BY "logins"."id" desc``` and this applies to the others as well.

**Comment by philipnery** [comment]
I think I've found the culprit. Removing [rails-footnotes] (https://github.com/josevalim/rails-footnotes) solves the issue but still I'm still curious why this is happening and I prefer to keep it if possible.

**Comment by timoschilling** [comment]
I'm closing this while it looks like a third party problem, until you show up a ActiveAdmin fault.

**Comment by philipnery** [comment]
Thanks for your time.
