### ISSUE TITLE
CanCanCan non restful resource not mapped to current_admin_user?

### ISSUE THREAD

**Issue by andywenk** [activeadmin/activeadmin#3899]
Hi, 

I have defined abilities in a model called `ActiveAdminAbility` and configured AA to use this. The admin role has the abilities `can :manage, :all`. 

I am not quite sure why this:

```
if can? :add_comment, :player
  div do
    active_admin_comments
  end
end
```

does not work but this: 

```
if Admin::ActiveAdminAbility.new(current_admin_user).can? :add_comment, :player
  div do
    active_admin_comments
  end
end
```

The ability is a non restful resource and is defined in a different role like this:

```
if admin.has_role? :trainee
    cannot :manage, :all
    cannot :add_comment, :player
    ...
end
```

All other abilities are working correctly. Am I overseeing sth? 

Thanks a lot for your help. 

Cheers

Andy

code for the ability model:

```
module Admin
  class ActiveAdminAbility
    include CanCan::Ability

    def initialize(admin)
      if admin.has_role? :admin
        can :manage, :all
        cannot :destroy, Player
      end

      if admin.has_role? :customer_service
        can :manage, :all
        can :update, AdminUser, id: admin.id
        ...
```

Config in `config/initializers/active_admin.rb`

```
  config.cancan_ability_class = 'Admin::ActiveAdminAbility'
```

**Comment by toao** [comment]
Hi,
just experienced the same issue (even 1.5 years later 😞 )...

If you check ```controller.current_ability.class``` at the position where you call ```can?``` you will notice that it's not using the defined ```cancan_ability_class``` but the default ability that you use in the normal controllers. I guess only the authorization for the menu and default actions is actually using the custom admin ability setting.

Solution: You can simply use [authorized?](https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/lib/active_admin/cancan_adapter.rb#L14) instead which considers the proper settings.

I think this behaviour is surprising and dangerous and potentially many people are unknowingly running into this issue. I guess it can be solved by patching the [CancanAdapter](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/cancan_adapter.rb) and/or the related [authorization module](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/base_controller/authorization.rb).

**Comment by timoschilling** [comment]
`can?` is the helper defined by `cancan` it self and don't uses the ActiveAdmin Auth Adapter Config.

The concept of the ActiveAdmin adapter is to have authentication concept in AA, which can use cancan or pundit or whatever as backend. It has not the concept to fully integrate `cancan` into ActiveAdmin. The reason is that `cancan` and `pundit` are working in different ways, thats way we need a abstraction.

Our abstraction don't support something like the `can?` helper. But hey we are OpenSource and accept PR's! ;)

**Comment by andywenk** [comment]
@toao thanks for your examination ;-). @timoschilling is right with requesting a PR ;-)
