### ISSUE TITLE
How to customize devise mail instructions?

### ISSUE THREAD

**Issue by DmitryKK** [activeadmin/activeadmin#3900]
I want to be able to edit the text of the letter (app/views/devise/mailer/confirmation_instructions.html.erb) using active admin. Is this possible?

**Comment by mattvague** [comment]
Not 100% sure this will work, but you might try overriding the active admin devise email templates in your app's views folder. Try creating a custom email template like `app/views/active_admin/mailer/confirmation_instructions.html.erb` in your app and see what happens

**Comment by DmitryKK** [comment]
I apologize for my stupid question, but apart from overriding the way for the instructions I had something else to do? For example, to create a custom page? In any case, nothing happened

**Comment by timoschilling** [comment]
No there is nothing else to do
