### ISSUE TITLE
If filter is Relational Model it would be better, if Search Status Bar will show us 'title' of filter then only 'ID'.

### ISSUE THREAD

**Issue by Shoroh** [activeadmin/activeadmin#3901]
If filter is relations then Search Status Bar will try to show (title|name|value|id) instead of just ID. Let me show on examples.

Before:
![screen shot 2015-04-21 at 17 11 17](https://cloud.githubusercontent.com/assets/1865984/7254144/63543416-e86b-11e4-866c-4dea382c8065.png)

After:
![screen shot 2015-04-21 at 21 15 03](https://cloud.githubusercontent.com/assets/1865984/7254161/8449cd52-e86b-11e4-81f7-748b3bb027c5.png)

Patch at activeadmin/lib/active_admin/filters/resource_extension.rb#search_status_section:

```ruby
active.filters.each do |filter|
  li do
    if filter.body =~ /ID/i
      begin
        klass = filter.body.split(' ').first.constantize
        method = klass.inspect.scan(/(title|name|value|id)/).last[0].to_sym
        value = klass.find(filter.value).send(method)
        span "#{klass}: "
        b value
      rescue
        span filter.body
        b filter.value
      end
    else
      span filter.body
      b filter.value
    end
  end
end
```

Do not judge me strictly for the code, I'm a Junior )

**Comment by timoschilling** [comment]
I don't understand what you want or what your problem is.

**Comment by timoschilling** [comment]
Now I think I know what you want. I close this we now have #3902
