### ISSUE TITLE
Test rails apps don't have strong params setup for Posts, Users, and Categories

### ISSUE THREAD

**Issue by mattvague** [activeadmin/activeadmin#3904]
@timoschilling @seanlinsley Right now you get `ActiveModel::ForbiddenAttributesError` trying to update these models after generating a test rails app. Do you know if there is a reason we don't add `permit_params` for them?

Would be happy to change, just want to make sure it wasn't intentional

**Comment by seanlinsley** [comment]
Pretty sure I'd only added it where necessary to get the test suite passing when initially building strong_params support. It'd definitely make sense to set it up for the other models as well.

**Comment by seanlinsley** [comment]
I'm going to merge this into #3308
