### ISSUE TITLE
Infinite loop when install activeadmin

### ISSUE THREAD

**Issue by auszone** [activeadmin/activeadmin#3905]
As title, I put `gem 'activeadmin'` in my Gemfile and bundle install. It shows the following message
```
Your Gemfile requires gems that depend on each other, creating an infinite loop. Please remove gem 'meta_search' and try again.
```
Why is that?

**Comment by timoschilling** [comment]
Have your tried to remove `meta_search` from your Gemfile?

Please post your Gemfile and Gemfile.lock (if exist)

**Comment by auszone** [comment]
Yes I did. but no difference..

**Comment by timoschilling** [comment]
Please post your Gemfile and Gemfile.lock (if exist)

**Comment by auszone** [comment]
It turns out that the version I installed was 0.6.6  which does not support rails 4, and I'm using rails 4.
I changed `gem activeadmin` to `gem 'activeadmin', github: 'activeadmin'`. It's working again. Thanks!

**Comment by gangcai** [comment]
Still have this problem

**Comment by donpdonp** [comment]
rails 4 has been out long enough, and this gem is popular enough, that perhaps the 0.6 gem should throw a descriptive error regarding rails 4? i came to this ticket because of the infinite loop error.

**Comment by seanlinsley** [comment]
I'm thinking we'll release the official 1.0.0 in the next ~month, so there's no point going back and coining a 0.6.x release just to get around a bug in Rubygems / Bundler.

**Comment by donpdonp** [comment]
okay thats great to hear. thanks for the work on this gem!

**Comment by pboling** [comment]
After 1.0.0 is out though it might make sense, for some gold-hearted forker, to add warnings and deprecation notices to a new point release of 0.6, from the stable branch https://github.com/activeadmin/activeadmin/tree/0-6-stable

**Comment by seanlinsley** [comment]
@pboling that's definitely going to be needed, lest we get a ton of support requests from people that didn't check the (not yet written) 1.0 migration guide
