### ISSUE TITLE
Custom form in partial doesn't work

### ISSUE THREAD

**Issue by adisos** [activeadmin/activeadmin#3910]
```
# admin/post.rb
ActiveAdmin.register Post do
  form partial: 'form'
end
```

```
# app/views/admin/posts/_form.html.arb
insert_tag active_admin_form_for resource do |f|
  inputs :title, :body
  actions
end
```
Error:
```undefined method `posts_path' for #<#<Class:0x007f9980312588>:0x007f9981f96358>```

**Comment by noijd** [comment]
I have a similar problem and I fix it establishing the controller action.

In my case I have a `member action` like this:

```ruby
  member_action :publish, method: [:get, :post] do
    @page_title = "Publish #{resource.title}"

    if request.get?
      render :publish
    else
      # ...
    end
  end
```

So this would render the view on `views/admin/posts/publish.html.arb`, which contains this code:

```ruby
active_admin_form_for assigns[:post], url: { action: 'publish' } do
  semantic_errors
  inputs
  actions
end
```

**Comment by reicheltd** [comment]
+1 same problem using rails 4.2.3 and activeadmin 1.0.0.pre1

**Comment by jtomaszewski** [comment]
Use `active_admin_form_for [:admin, resource] do |f|` instead of `insert_tag active_admin_form_for resource do |f|`.

We should update this in the documentation.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by davidstosik** [comment]
After trying to update (from a really old version!), I had the same issue:
`undefined method `posts_path' for #<#<Class:0x007f9980312588>:0x007f9981f96358>`

@jtomaszewski's suggestion helped me fix it: although ActiveAdmin's documentation recommends
`active_admin_form_for resource do |f|`, it only works when I use `active_admin_form_for [:admin, resource] do |f|`.

**Comment by AlexVentura** [comment]
I had a problem described here https://github.com/activeadmin/activeadmin/issues/5410 I could not found what was causing the wrong URL params in my resource. So, I decided to override each and every `action_item`, `member_action`, `form_action`, etc.

To solve the form concept I did the following and it really works pretty fine:

```ruby
# app/admin/organizations.rb
ActiveAdmin.register Post do
  form partial: 'form'
end
```

```ruby
# app/views/admin/organizations/_form.html.arb
active_admin_form_for [:admin, resource] do |f|
  tabs do
    tab 'General Configuration' do
      f.inputs 'Organization Details' do
        f.input :name
        f.input :kind, :as => :enum
        f.input :company_logo, :as => :file
      end

      f.inputs('Organization Contacts', { class: 'organization_contacts_section' }) do
        saved_contacts = f.object.organization_contacts.count
        n = 3 - saved_contacts.to_i
        n.times do
          f.object.organization_contacts.build
        end
        contact_counter = 0
        f.fields_for :organization_contacts do |m|
          contact_counter = contact_counter +  1
          m.inputs "Contact #{contact_counter}" do
            m.input :name, placeholder: 'Name'
            m.input :email, placeholder: 'Email'
          end
        end
      end
    end
  end

  f.actions
end
```

I hope it could be useful for somebody else 🙂

**Comment by woto** [comment]
It could be offtop. But i've also searched way to use calendar in custom sidebar, here is the snippet:

```ruby
ActiveAdmin.register_page "Events" do
  sidebar :filter, partial: 'form'
...
```

```erb
<%= semantic_form_for '', builder: ActiveAdmin::FormBuilder, :html => { :method => :get } do |f| %>
  <%= f.input :from, as: :datepicker %>
  ...
```

**Comment by TonyArra** [comment]
why has the documentation never been updated on this? Seems to still be an issue.

**Comment by deivid-rodriguez** [comment]
Be my guest.
