### ISSUE TITLE
Error on Subdomain without default namespace(Invalid route name, already in use: 'root')

### ISSUE THREAD

**Issue by dpaluy** [activeadmin/activeadmin#3911]
I got this error:
`add_route: Invalid route name, already in use: 'root'  (ArgumentError)`

on following configuration:

```
# config/initializers/active_admin.rb
config.default_namespace = false

# routes.rb
root to: "welcome#index"

constraints subdomain: "admin" do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end
```

It caused by excluding `default_namespace`.
Another reference: https://github.com/rails/rails/issues/10494

**Comment by timoschilling** [comment]
Sound like a double of #2837 fixed in #3502

Change your ActiveAdmin config to `config.root_to_options = { as: :admin_root }`
