### ISSUE TITLE
New devise helpers not included in ActiveAdmin?

### ISSUE THREAD

**Issue by scouttyg** [activeadmin/activeadmin#3912]
This may be related to https://github.com/plataformatec/devise/issues/3583, but I figured I'd put it here as well.

Devise seems to be messing up when helper methods end up getting pulled into ActiveAdmin, unless they are explicitly included (via ```include Devise::Controllers::Helpers```) in the application_controller.rb. I built a quick app to demo what's been broken:

Branch https://github.com/scouttyg/test-devise-group/tree/devise uses devise_group in application_controller without any issues

Branch https://github.com/scouttyg/test-devise-group/tree/devise-activeadmin shows that once ActiveAdmin is added in, the functionality breaks, and we get the error that makes the app fail to load:

```/test-devise-group/app/controllers/application_controller.rb:5:in `<class:ApplicationController>': undefined method `devise_group' for ApplicationController:Class (NoMethodError)```

Branch https://github.com/scouttyg/test-devise-group/tree/devise-activeadmin-fixed shows that once we explicitly add in ```include Devise::Controllers::Helpers``` to application_controller.rb, everything again works.

**Comment by timoschilling** [comment]
Your test app is confusing. It would be much more cleaner if you build it with this commits:
1. empty rails app
2. add devise
3. add activeadmin
4. fix activeadmin

**Comment by timoschilling** [comment]
On the first view it sounds like a devise bug for me.

**Comment by scouttyg** [comment]
I recreated the app with more commits, hope it is verbose enough.

* https://github.com/scouttyg/test-devise-group/tree/1ce9a722143d487cc6b800ed73d02c8729b2ba2a is the "initial commit" code, you can just git checkout the first commit to get here.
* https://github.com/scouttyg/test-devise-group/tree/devise adds in devise User and Student models, along with devise_group, still looking good.
* https://github.com/scouttyg/test-devise-group/tree/devise-activeadmin-1 Adds in the initial ActiveAdmin details, and boots up. 
* https://github.com/scouttyg/test-devise-group/tree/devise-activeadmin-2 Tries to skip a before_filter in active_admin.rb, which is when it fails (with the message ```undefined method `devise_group' for ApplicationController:Class (NoMethodError)```)
* https://github.com/scouttyg/test-devise-group/tree/devise-activeadmin-fixed Adds in ```ruby  include Devise::Controllers::Helpers``` to application_controller.rb, which now fixes behavior.
* https://github.com/scouttyg/test-devise-group/tree/master has all commits of course, going from beginning to end of what I did.

**Comment by MagicalMonkey** [comment]
Possibly related to this issue: https://github.com/plataformatec/devise/issues/3757

**Comment by seanlinsley** [comment]
Yep, sounds like this is a Devise bug. Merging this into plataformatec/devise#3757
