### ISSUE TITLE
Undefined method safe_append= for nil

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#3916]
I just upgraded an app from using Active Admin b794f4b7550dc4756bd76c31221ae3bde6185e5e to b3a9f4b3e4051447d011c59649a73f876989a199. A form that looks like this:

``` erb
<%= active_admin_form_for [:admin, @property] do |f| %>
  <% f.inputs do %>
    <% f.input :name %>
    <% f.input :address %>

    <%= f.form_buffers.pop %>
    <% f.form_buffers << ''.html_safe %>

    <h3>Junk</h3>
    <table>
      <!-- ... -->
    </table>

    <% f.has_many :images do |i| %>
      <% i.input :image, as: :file, hint: i.object.image.url ? image_tag(i.object.image.url) : '' %>
    <% end %>

    <%= f.form_buffers.last %>
  <% end %>
<% end %>
```

Started raising this error:

```
NoMethodError - undefined method `safe_append=' for nil:NilClass:
  app/views/admin/properties/_form.html.erb:1:in `block in _app_views_admin_properties__form_html_erb__4480795312609525413_70285274106140'
   activeadmin-b3a9f4b3e405/lib/active_admin/views/components/active_admin_form.rb:35:in `build'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `active_admin_form_for'
   activeadmin-b3a9f4b3e405/lib/active_admin/view_helpers/form_helper.rb:7:in `block in active_admin_form_for'
  arbre (1.0.3) lib/arbre/context.rb:45:in `initialize'
   activeadmin-b3a9f4b3e405/lib/active_admin/view_helpers/form_helper.rb:6:in `active_admin_form_for'
  app/views/admin/properties/_form.html.erb:1:in `_app_views_admin_properties__form_html_erb__4480795312609525413_70285274106140'
  actionview (4.1.6) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.1.6) lib/active_support/notifications.rb:161:in `instrument'
  actionview (4.1.6) lib/action_view/template.rb:339:in `instrument'
  actionview (4.1.6) lib/action_view/template.rb:143:in `render'
```

Which is confusing since #3486 was supposed to [raise an error](https://github.com/activeadmin/activeadmin/pull/3486/files#diff-7c53d0f8a3de08d4b0a2ab80e91c8ac4R76) to make the upgrade path clear. Any idea what the issue might be? Note that I haven't yet tried upgrading Rails to 4.2, or Active Admin past b3a9f4b3e4051447d011c59649a73f876989a199.

Rewriting the form to use Arbre fixed the issue, but I should've seen a better error message.

**Comment by timoschilling** [comment]
I'm wondering about where is `safe_append=` coming from, both b794f4b and b3a9f4b, don't have this method and even arbre don't have this method.

**Comment by seanlinsley** [comment]
Yeah. The stack trace doesn't help, but I'm guessing it's being called from [here](https://github.com/rails/rails/blob/68a2a6711643db6b8b0775fe004bc0de0cdc07db/actionview/lib/action_view/template/handlers/erb.rb#L18).

**Comment by timoschilling** [comment]
Does this error still happens after you removed `form_buffers` and use arbre?

**Comment by seanlinsley** [comment]
The form's contents are not causing the error. I was able to get that exception with just this:
```erb
<%= active_admin_form_for [:admin, @property] do |f| %>
<% end %>
```

That is, merely having a `do` / `end` block caused the error.

**Comment by aennchen** [comment]
For me, using semantic_form_for and specifying the builder explictly fixed the error

```ruby
<%= semantic_form_for resource, builder: ActiveAdmin::FormBuilder do |f| %>
```

**Comment by francirp** [comment]
@aennchen solution worked for me with the following slight modification to point to the correct url:

```html
<%= semantic_form_for [:admin, resource], builder: ActiveAdmin::FormBuilder do |trip_builder| %>
```

**Comment by varyonic** [comment]
I'm closing this as won't fix.  `active_admin_form_for` is no longer supported from an ERB partial but a workaround is provided above, though the recommended action is to convert to Arbre, which is now supported inside the form. Yes, the error was not friendly but this issue has seen little activity past couple of years.  Added link here from upgrading page on wiki.

**Comment by vfonic** [comment]
For anyone coming here, `active_admin_form_for` seems to be working for ERB partials, if you use a single `<%= %>` tag, across the whole form, like this:

```erb
<%=
  active_admin_form_for [:admin, resource] do |f|
    f.semantic_errors *f.object.errors.keys
    f.inputs do
      f.input :url
      f.input :community_id
    end
    f.actions do
      f.action :submit
    end
  end
%>
```

Please also note the `[:admin, resource]`.

**Comment by adrian-BOS** [comment]
> For anyone coming here, active_admin_form_for seems to be working for ERB partials, if you use a single <%= %> tag, across the whole form, like this:

this worked for me thanks
