### ISSUE TITLE
"PG::Error: ERROR:  missing FROM-clause entry for table" in admin panel

### ISSUE THREAD

**Issue by sdilshod** [activeadmin/activeadmin#3920]
Hello!

I have issue with ActiveAdmin(not sure). After updating gem i start get in admin panel error "protected method `authorize!' called for #<Admin::CategoriesController:0x000000085db940>". 
I solve this by removing line controller.authorize_resource in admin/*.rb file, but get another error like this:

 ` PG::Error: ERROR:  missing FROM-clause entry for table "category_users"
  LINE 1: SELECT "users".* FROM "users"  WHERE "category_users"."conne...
                                             ^
  : SELECT "users".* FROM "users"  WHERE "category_users"."connection_type" =   "category_users"."favorite" `

https://gist.github.com/sdilshod/10355be872a366ef225b 

How can solve this?
Thanks

**Comment by timoschilling** [comment]
Please post the related ActiveAdmin file.

**Comment by sdilshod** [comment]
```ruby
# encoding: utf-8
ActiveAdmin.register Category do
  menu :label => "Категории", :priority => 7, :if => proc{ can? :manage, Category }
  #controller.authorize_resource
  #controller.load_and_authorize_resource
  index do
    column :image do |c|
      if c.image.present?
        image_tag c.image.url('48x48#'), :alt => ''
      end
    end
    column :name
    column(:description) {|c| c.description.to_s.truncate(200, :separator => ' ') }
    column :parent do |c|
      c.ancestors.map {|c| link_to c.name, [:admin, c] }.join(' -> ').html_safe
    end
    default_actions
  end
  show do |c|
    attributes_table do
      row :name
      row :parent do
        link_to c.parent.name, admin_category_path(c.parent) if c.parent
      end
      row :description
      row :slug
      row :products do
        c.products.map do |p|
          link_to p.list_name, admin_product_path(p)
        end.join('<br/>').html_safe
      end
    end
    active_admin_comments
  end
  form :partial => 'form'
  scope :roots
  scope :all
end
```
This is one of admin file.
thank you for helping @timoschilling

**Comment by sdilshod** [comment]
I'm able to inter admin panel, but when click menu "Categories" get this error FROM-clause

**Comment by timoschilling** [comment]
I think there is a missing `has_many :category_users`.
```ruby
# encoding: utf-8
class Category < ActiveRecord::Base
  has_many :category_users
  has_many :favorite_users, :through => :category_users, :source => :user, :conditions => {:category_users => {:connection_type => :favorite}}
  has_many :responsible_users, :through => :category_users, :source => :user, :conditions => {:category_users => {:connection_type => :responsible}}
```

Following the stack trace, this error is triggered by a filter maybe it help you enable only the filter that you need.

**Comment by sdilshod** [comment]
>>I think there is a missing has_many :category_users.
Yes. I mess it when copying from source code

>>Following the stack trace, this error is triggered by a filter maybe it help you enable only the filter that you need.

You mean custom filter sidebar for index page?

**Comment by seanlinsley** [comment]
sounds like it's coming from [`default_association_filters`](https://github.com/activeadmin/activeadmin/blob/4baf474177fb6c4e2638d103dfb28c576b3084df/lib/active_admin/filters/resource_extension.rb#L122).

@sdilshod can you post the results of this?
```ruby
ActiveAdmin.application.namespaces[:admin].resources[Category].filters
```

**Comment by sdilshod** [comment]
![screenshot from 2015-05-04 19 10 45](https://cloud.githubusercontent.com/assets/242699/7454874/49542cbc-f291-11e4-9b51-4d8a924ea6e2.png)

output of rails console @seanlinsley

**Comment by seanlinsley** [comment]
That's confusing. You're using 0.6.6, but [even that has `ResourceCollection#[]`](https://github.com/activeadmin/activeadmin/blob/v0.6.6/lib/active_admin/resource_collection.rb#L27)

**Comment by sdilshod** [comment]
Sorry @seanlinsley i give this command inside branch which already rolled back for fix issue. So output from from that branch which i have problem

![screenshot from 2015-05-04 20 08 22](https://cloud.githubusercontent.com/assets/242699/7455932/b56b215a-f299-11e4-9473-ef0eaadea04a.png)

**Comment by seanlinsley** [comment]
One of your associations must be invalid. `config.include_default_association_filters = false` is a quick fix.

```ruby
  # == Filters
  #
  # By default the index screen includes a "Filters" sidebar on the right
  # hand side with a filter for each attribute of the registered model.
  # You can enable or disable them for all resources here.
  #
  # config.filters = true
  #
  # By default the filters include associations in a select, which means
  # that every record will be loaded for each association.
  # You can enabled or disable the inclusion
  # of those filters by default here.
  #
  # config.include_default_association_filters = true
```
