### ISSUE TITLE
Order of comments DESC not ASC and how to change it

### ISSUE THREAD

**Issue by andywenk** [activeadmin/activeadmin#3922]
Hi,

I was searching for how to change the order of the displayed comments in a resource view. What I found (per accident) is this PR:

https://github.com/varyonic/activeadmin/commit/eade36c64755363cde8c5edb673799007bd5f88e

I am wondering why the order is "hard coded" and not configurable? And furthermore I am wondering why it is ascending what means per default, I see the oldest comment first. Most likely, I want to see the newest comment first.

Can anyone describe the best way how to change the order? 

Thanks a lot and keep on doing this awesome gem ;-)

Andy

**Comment by andywenk** [comment]
I did for sure achive the DESC order by monkey patching the file https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/orm/active_record/comments/comment.rb but that's really ugly ...

**Comment by timoschilling** [comment]
If you want to change that, you need to monkey patch or you create a PR with a config.

**Comment by andywenk** [comment]
ok thanks @timoschilling - I'll try to send a PR

My approach would be to simply configure this in 

    # == Admin Comments
    # ...
    config.comments_order = 'DESC'

where the default will be 'ASC' if the config is not set. Or do you prefer to have smth. like

    # == Admin Comments
    # ...
    config.comments_order_desc = true

where the default will be false if the config is not set.

Then I will read the setting in 

https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/orm/active_record/comments/comment.rb#L32

Thoughts? 

And finally, which kind of tests do I need to write? An example would be helpful.

Thanks and Cheers

Andy

**Comment by timoschilling** [comment]
> where the default will be 'ASC' if the config is not set.

The default `ASC` should be set in the application.rb

**Comment by timoschilling** [comment]
Or even better we cream the complete order clause from the config, then is the order field configurable too.

**Comment by andywenk** [comment]
I am not sure how both these ideas should be done. Why should the default `ASC` go into the application.rb (I assume you mean the application.rb from the app I use AA in) if we have an initializer? I mean imho it is just a configuration flag.

If we choose to do it the second way, what do you mean with "cream the complete order clause from the config" and how would that look like?

**Comment by andywenk** [comment]
why did you close the issue? Isn't this not the correct place to discuss a PR?

**Comment by timoschilling** [comment]
I mean the [application.rb](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/application.rb) from ActiveAdmin. Each ActiveAdmin setting has a default value and that should be `ASC`.

What I mean is:
```ruby
.order(config.comments_order)
```

**Comment by timoschilling** [comment]
As I closed this issue I did not expect a discussion

**Comment by andywenk** [comment]
ok I will write an PR. Let's discuss it there then. Thanks !

**Comment by andywenk** [comment]
@timoschilling one question. I created a test in spec/unit/comments_spec and try to run it but get this:

       rspec spec/unit/comments_spec.rb                                                                                                                                  ⏎ ✱
    /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
    DEPRECATION WARNING: Support for Rails < 4.1.0 will be dropped. (called from warn at /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/2.2.0/forwardable.rb:183)
    Coverage report generated for RSpec to /Users/andwen/project/sumcumo/activeadmin/coverage. 1186 / 2720 LOC (43.6%) covered.
    /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- test/unit/testcase (LoadError)
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/test_case.rb:1:in `<top (required)>'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/assertion_error.rb:5:in `<module:Matchers>'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/assertion_error.rb:2:in `<module:Shoulda>'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers/assertion_error.rb:1:in `<top (required)>'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
      from /Users/andwen/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/shoulda-matchers-2.8.0/lib/shoulda/matchers.rb:1:in `<top (required)>'

How do I run the tests?

**Comment by timoschilling** [comment]
You need to switch to Rails 4 or Ruby < 2.2. For Rails see https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md

**Comment by Fivell** [comment]
@andywenk , any update ?

**Comment by Fivell** [comment]
closed by #3923 ... long time ago
