### ISSUE TITLE
Adding pages dynamically to the menu after the application has started

### ISSUE THREAD

**Issue by elenatanasoiu** [activeadmin/activeadmin#3932]
Hi, 

I want my users to be able to create some pages and then these pages should be added dynamically in the menu, under a parent page called "Help". However, I can't workout how to register newly created pages, since the register_page method only runs when the server is started. 

Is there a way to dynamically build the path to newly created pages? Or is there a way to run register_page dynamically (perhaps in a proc?) without having to restart?

Elena

**Comment by seanlinsley** [comment]
I don't think this has been done before. Are custom pages saved in the database?

**Comment by elenatanasoiu** [comment]
Yes, the pages are saved in the db. They just have a title and a content field. 
I've wracked my brain trying to figure this one out.

**Comment by elenatanasoiu** [comment]
The problem is the fact that I don't have a route for the newly created page so I get an error saying that "admin_page_title_path" could not be found. 

If I use Rails.application.reload_routes! then the route is built, BUT this also clear my menus and I basically get a monster list of all the pages in the place where the menu used to be. 

All the methods for rebuilding the menu that I tried seemed a bit hack-ish. So I assume there should be a way to rebuild just that one route instead of meddling with resetting resources and readding menu items.

**Comment by timoschilling** [comment]
One other problem do you maybe have depend on your production environment, your code will only work on single thread / single process servers. You need some code with triggers the Page building on each other thread / process.

You can try this to trigger the loading:
```ruby
ActiveAdmin.application.unload!
Rails.application.reload_routes!
```

But you still need code to run this in each thread / process.

**Comment by elenatanasoiu** [comment]
I did not consider the single thread issue. That could prove to be a problem but I will check to see what exactly we have on production.

However, I tried your solution with using unload! and then reload_routes!
But the reload_routes! part will still reset my menus and I'm stuck with how to rebuild it.

**Comment by elenatanasoiu** [comment]
So it looks like we have multiple unicorn instances running on the server. So this code will backfire on production anyway. In the end I decided to add the pages manually after they are created and restart the server.
