### ISSUE TITLE
Navigation DropDown Menu Disappears

### ISSUE THREAD

**Issue by jostster** [activeadmin/activeadmin#3933]
All my menu items are grouped under dropdowns. When using Chrome v41 if you select a main dropdown and you try to move your mouse down to the first item, the dropdown disappears making it impossible to select any dropdown items.

**Comment by jostster** [comment]
It seems this is mainly occurring after first login into the system while on the dashboard panel. By right clicking and selecting inspect element, this seems to fix the issue where the menu is able to stay popped up while you drag the mouse down to select a menu item.

**Comment by timoschilling** [comment]
Is this still a issue?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
