### ISSUE TITLE
Sidebars page is missing or incorrect

### ISSUE THREAD

**Issue by jancel** [activeadmin/activeadmin#3941]
The link on the right hand menu takes you to the section on the page, 
  
![screen shot 2015-05-10 at 2 32 22 pm](https://cloud.githubusercontent.com/assets/157374/7555905/74e9e062-f721-11e4-9bd4-afc514866b84.png)

**Comment by timoschilling** [comment]
I can't reproduce this.

Did you mean this link?

![active_admin___the_administration_framework_for_ruby_on_rails](https://cloud.githubusercontent.com/assets/165599/7559865/28bac0a2-f7bd-11e4-8c79-0efa018a4ceb.jpg)

Please post this issue in the https://github.com/activeadmin/activeadmin.info repo.

**Comment by jancel** [comment]
I. Will. It's actually a shortcut link on the dashboard page I do believe.
I'll send a pr if I get a few

On Monday, May 11, 2015, Timo Schilling <notifications@github.com> wrote:

> Closed #3941 <https://github.com/activeadmin/activeadmin/issues/3941>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/activeadmin/activeadmin/issues/3941#event-301456793>.
>


-- 
Jeff Ancel

(314) 703-8829 - Main

www.jeffancel.com
