### ISSUE TITLE
FROM clause is not updated when associated specifies JOIN (at master, Rails 4.2, Ransack 1.6.6)

### ISSUE THREAD

**Issue by samstickland** [activeadmin/activeadmin#3942]
I have an association that specifies some conditions:

models/user.rb:

    has_many :acquired_certifications,
        -> { joins(certification: [:vendor]).where.not('vendors.name' => 'UK Government') }

(I know it's not the tidiest, I may rewrite this with STI)

an acquired_certification belongs to a certification which belongs to a vendor

In admin/users.rb I have:

    filter :certifications_name, as: :string, label: 'Certification'

Now, when I attempt to search via this filter I get the following error:

    PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "vendors"
    LINE 1: ...red_certifications"."user_id" = "users"."id" AND ("vendors"....
                                                                 ^
    : SELECT COUNT(DISTINCT count_column) FROM (SELECT  "users"."id" AS count_column FROM "users" LEFT OUTER JOIN "acquired_certifications" ON "acquired_certifications"."user_id" = "users"."id" AND ("vendors"."name" != 'UK Government') LEFT OUTER JOIN "certifications" ON "certifications"."id" = "acquired_certifications"."certification_id" WHERE ("certifications"."name" ILIKE '%CCNP%') LIMIT 30 OFFSET 0) subquery_for_count

So it's picked up the where clause from the association scope, but it hasn't added the join. Most odd. This association works elsewhere in my application.

Any idea where I should start looking to fix this, or any possible work arounds?

**Comment by seanlinsley** [comment]
Shouldn't this be `filter :acquired_certifications_name`?

If this doesn't work from a console, it's a bug in Ransack:
```ruby
User.search(acquired_certifications_name_eq: 'foo').result

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
