### ISSUE TITLE
Again... Bundler could not find compatible versions for gem "rails"

### ISSUE THREAD

**Issue by cschao83** [activeadmin/activeadmin#3946]
Hi,
I download a redmine plugin, and I'm trying to install it by executing the following command:

rake redmine:plugins NAME=redmine_contacts RAILS_ENV=production

and I'm getting the next error: 

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    wicked_pdf (>= 0) ruby depends on
      rails (>= 0) ruby

    acts-as-taggable-on (~> 2.3.1) ruby depends on
      rails (~> 3.0) ruby

    rails (= 4.2.1) ruby

Don't have many experience dealing with it... Even when I execute a bundle update, got a similar error:

Bundler could not find compatible versions for gem "i18n":
  In Gemfile:
    rails (= 4.2.1) ruby depends on
      railties (= 4.2.1) ruby depends on
        activesupport (= 4.2.1) ruby depends on
          i18n (~> 0.7) ruby

    money (~> 5.1.0) ruby depends on
      i18n (~> 0.6.0) ruby

So, any ideas? Thank you very much.

**Comment by timoschilling** [comment]
This is the ActiveAdmin not the Redmine one
