### ISSUE TITLE
Input fields disappeared after updating from 1.0.0.pre to 1.0.0.pre1

### ISSUE THREAD

**Issue by avbrychak** [activeadmin/activeadmin#3947]
Hello there! In the active_admin-b794f4b7550d version, form renders as intended, but in the newer versions generated html omits inputs fields.
So I have a form like that:
```ruby
panel 'Email Search' do
  semantic_form_for(Person.new,
                    url: :email_search_people,
                    method: :post,
                    builder: ActiveAdmin::FormBuilder) do |f|
    f.inputs do
      f.input :name
      f.input :domain
    end

    f.actions do
      f.action :submit, label: 'Lookup Email'
    end
  end

end
```
But after updating it renders the form without inputs fieldset. Html looks like:
```html
<form novalidate="novalidate" method="post" id="new_person" class="formtastic person" action="/people/email_search" accept-charset="UTF-8">
    <div style="display:none">
        <input type="hidden" value="✓" name="utf8">
        <input type="hidden" value="5OmOzg4Xmsh/giz0x2+6Lb1c+F2/SiblHr+B1N2eLzw=" name="authenticity_token">
    </div>
    <fieldset class="actions">
        <ol>
            <li id="person_submit_action" class="action input_action ">
                 <input type="submit" value="Lookup Email" name="commit">
            </li>
        </ol>
    </fieldset>
</form>
```
In the formtastic wiki it is said that updating from 3.0 to 3.1 does not require any changes in the code... Any ideas how to fix that?

**Comment by februaryInk** [comment]
I'm experiencing the same problem. It's been frustrating me for the past two hours! Unless I remove `f.actions` (which I of course need), all input fields disappear.

Replacing `semantic_form_for` with `active_admin_form_for` seems to help, but I am very new to Active Admin and don't know why this would be.
