### ISSUE TITLE
Pagination range issue in active admin on last page in ruby on rails

### ISSUE THREAD

**Issue by HiteshSongra** [activeadmin/activeadmin#3950]
I have the issue in active-admin pagination,
Ex: suppose i have 100 records in my database, and per_page = 30 then the following issue is arise.

on last page Displaying 51-60 of 100 in total << First << Prev 1 2 3 4

I have around 7000-7500 records in my database.

Second Last page display range correct

![second-last-page](https://cloud.githubusercontent.com/assets/6860099/7675290/4a31750e-fd54-11e4-9951-a6204794265f.png)

last page display range incorrect

![last-page](https://cloud.githubusercontent.com/assets/6860099/7675296/5ac67310-fd54-11e4-890c-7aac906c8bdd.png)

Please advise.

**Comment by shishir127** [comment]
@HiteshSongra Are you still facing this issue?

**Comment by seanlinsley** [comment]
I'm not seeing this in my application, and the OP hasn't responded in a month, so I'm going to close this.
