### ISSUE TITLE
wrong parsing query params in js ActiveAdmin.PerPage

### ISSUE THREAD

**Issue by senid231** [activeadmin/activeadmin#3955]
```coffee
ActiveAdmin.PerPage::_queryParams 
```
this function create wrong params hash for cases when value of filter contains spaces

how to reproduce:
1) add dynamic per_page select box to index page and bind it to ActiveAdmin.PerPage
2) filter table with value that contains space (you will see that all of spaces in query are replaced with + (plus character)
3) change per_page value

You will see that, besides of adding/changing per_page param, this action change other params in query ( + characters were replaced with %2B)
So qurery params like "q%5Bsome_filter%5D=some+value" will changed to "q%5Bsome_filter%5D=some%2Bvalue" and decoded by rails like q[some_filter]=some+value

i write a solution. can you check it?

per_page_fix.coffee
```coffee
# fix issue in ActiveAdmin.PerPage when + in query params interprets as %2B but should be space (%20)
ActiveAdmin.PerPage::_queryParams = ->
  query = window.location.search.substring(1)
  params = {}
  re = /([^&=]+)=([^&]*)/g
  while m = re.exec(query)
    params[decodeURIComponent(m[1])] = decodeURIComponent(m[2].replace(/\+/g, '%20'))
  params
```

as you can see i just replace
```coffee
m[2]
```
with
```coffee
m[2].replace(/\+/g, '%20')
```

**Comment by senid231** [comment]
```javascript
jQuery.serialize( )
```
replace space with plus when encoding form inputs into query params
and
```javascript
decodeURIComponent( )
```
does not replace plus with space

i assume we need to replace *decodeURIComponent* with something like *jQuery.deserialize* but there is no such thing

**Comment by Fivell** [comment]
to be shorter, 
after changing per_page value URL param value
```
some+value
```

becomes

```
some%2Bvalue
```

which changes filtered results

**Comment by senid231** [comment]
solved
