### ISSUE TITLE
Predicates are i18n'ed, but ransacked scopes aren't

### ISSUE THREAD

**Issue by k3rni** [activeadmin/activeadmin#3958]
Even when i18n translations for attributes are provided, they remain untranslated in the "Search status" box. This is understandable for custom ransackers, but surprising for simple ones that match attribute names directly.

In [lib/filters/humanized.rb](/activeadmin/activeadmin/blob/master/lib/active_admin/filters/humanized.rb), `parse_parameter_body`, the predicate is correctly dismantled into its field name and operator. But then (in `body`) the field name is presented as is, with no i18n applied.

What it should do, is look it up under:
1. `ransack.attributes.#{resource_class_name}.#{scope_name}`. This is actually supported by ransack itself, through `Ransack::Translate.attribute`, albeit used only in Ransack's own form helper.

and then, as a fallback:
1. `activemodel.attributes.#{resource_class_name}.attributes.#{scope_name}`
2. same as above, looking up the class hierarchy
3. same as the two above, but under activerecord
4. something like `active_admin.ransack_scopes.#{resource_class_name}.#{scope_name}`

**Comment by Fivell** [comment]
@k3rni , please try master branch now,

**Comment by k3rni** [comment]
Testing with a new trivial app on Rails 5.0.2. Can confirm it correctly displays translated attribute name both in filter box and search status box. Also traverses model class hierarchy correctly. However, only translations provided under `activerecord` scope work, `activemodel` and `ransack.attributes` don't; this is not a big issue.

Closing, because the issue is solved. Thanks!
