### ISSUE TITLE
NameError in Admin::DashboardController#index

### ISSUE THREAD

**Issue by matisoffn** [activeadmin/activeadmin#3961]
I've read through the other issues with this same error, but none of the fixes worked.  I tried moving my root route above the AA routes to no avail.

`NameError in Admin::DashboardController#index` is the error after a fresh install that Rails is giving back.

Gemfile:

```ruby
gem "activeadmin", github: "gregbell/active_admin"
gem "polyamorous", github: "activerecord-hackery/polyamorous"
gem "ransack", github: "activerecord-hackery/ransack"
gem "formtastic", github: "justinfrench/formtastic"
```

**Comment by timoschilling** [comment]
Please post your routes file, your dashbord and the complete stacktrace

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
