### ISSUE TITLE
Bug when create a register page and use Pundit for authorization

### ISSUE THREAD

**Issue by lucianosousa** [activeadmin/activeadmin#3966]
I just followed all examples here in ActiveAdmin and in the Pundit documentation but I think there is some bug or unknown pending information to block access in Custom Pages from Active Admin.

Here my example:

#upload.rb
```
ActiveAdmin.register_page "Upload" do
  page_action :index do
    ...
  end
end
```

#app/policies/upload_policy.rb
```
class UploadPolicy < ApplicationPolicy

  def index?
    true if user.admin?
  end
end
```

So, even with this code, all users can access this index page.

Any tip here or this is a real bug?

**Comment by timoschilling** [comment]
It's not a Bug, its a missing feature ;)
ActiveAdmin don't support Authorization on pages at the moment.

**Comment by lucianosousa** [comment]
@timoschilling Even with cancan/cancancan?

**Comment by timoschilling** [comment]
yes, I think so, even cancan can't do that.

**Comment by lucianosousa** [comment]
Do you have any thoughts to do that? Maybe I can build a solution here and do a PR.

**Comment by timoschilling** [comment]
EDIT: deleted some comments with wrong informations

**Comment by timoschilling** [comment]
authorization for pages: https://github.com/activeadmin/activeadmin/blob/master/docs/13-authorization-adapter.md#managing-access-to-pages
authorization with cancan (incl. page example): https://github.com/activeadmin/activeadmin/blob/master/docs/13-authorization-adapter.md#using-the-cancan-adapter
But we don't have a Pundit example, maybe you find the way and can add a normal and a page example.

**Comment by lucianosousa** [comment]
I'll take a look. Thanks!

**Comment by blocknotes** [comment]
If it may help someone else - *app/policies/active_admin/page_policy.rb*:

```
module ActiveAdmin
  class PagePolicy < DefaultPolicy
    class Scope < Struct.new(:user, :scope)
      def resolve
        scope
      end
    end

    def show?
      if @record
        case @record.name
        when 'Reserved Page'
          @user.is_powered?  # check role for example
        else
          true
        end
      else
        false
      end
    end
  end
end
```

In my case I have custom AuthAdapter for Pundit, but it should work anyway.

**Comment by reicheltd** [comment]
@blocknotes thanks. that worked for me.
