### ISSUE TITLE
undefined method `index' when attempting to customize Dashboard

### ISSUE THREAD

**Issue by CantusFirmus** [activeadmin/activeadmin#3967]
I'm following the documentation for Customizing the Index page.  It doesn't say anywhere where these sample blocks of code are supposed to go, but I'm guessing app/admin/dashboard.rb.  Is that not right?

The code examples using "index as: ...." are causing this error message:

> undefined method `index' for #<ActiveAdmin::Views::Pages::Page:0x007f83cb751df8>

Here's the specific code that's causing this.  (Modified to suit my app)

    index as: :block do |publication|
      div for: publication do
        resource_selection_cell publication
        h2  auto_link     publication.work_title
        div simple_format publication.long_description
      end
    end

**Comment by timoschilling** [comment]
The Desktop is a Page not a Resource, `index` is only available for resources.
https://github.com/activeadmin/activeadmin/blob/master/docs/10-custom-pages.md
