### ISSUE TITLE
f.template.image_tag cause object reference to be display

### ISSUE THREAD

**Issue by seraphimlord** [activeadmin/activeadmin#3968]
Hi guys,

Not really a bug but some display issue instead.

Why is using f.template.image_tag causing the object reference to be display as below?
#<#<Class:0x007f948d83ae68>:0x007f948d988c98>

It will disappear once I use image_tag instead. Whats the difference between using this two?

**Comment by timoschilling** [comment]
Please take a look on this issues:
https://github.com/activeadmin/activeadmin/issues?q=is%3Aissue+f.template.image_tag+is%3Aclosed
