### ISSUE TITLE
Show does not display all attributes of attributes table

### ISSUE THREAD

**Issue by BenjaminHolland10** [activeadmin/activeadmin#3975]
![screen shot 2015-06-03 at 3 38 12 pm](https://cloud.githubusercontent.com/assets/10546097/7969709/c47d7628-0a06-11e5-9eb2-db8032a493c2.png)

In active admin after updating the info on a model, the show block should display all thing listed in the attribute tables block. The last one for some reason is listed as empty even the user inputs something for it in the form(i.e. 223). The database is updated with the form info and the index page shows the id.

![screen shot 2015-06-03 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/10546097/7969746/0a02d044-0a07-11e5-9d77-f7c877bb2599.png)
![screen shot 2015-06-03 at 3 43 43 pm](https://cloud.githubusercontent.com/assets/10546097/7969789/47321dda-0a07-11e5-9e98-78c2275d79ea.png)

![screen shot 2015-06-03 at 3 36 55 pm](https://cloud.githubusercontent.com/assets/10546097/7969648/51702a90-0a06-11e5-85f4-0c8f1e9f4a52.png)

**Comment by workgena** [comment]
Try this:

```ruby
row :institutuin do |row|
  row.institution_id
end
# or 
row :institutuin do |row|
  row.institution
end
```

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by BenjaminHolland10** [comment]
Sorry I didn't respond but @workgena's solution did work. Thanks!
