### ISSUE TITLE
Cannot fetch activeadmin

### ISSUE THREAD

**Issue by JevanWu** [activeadmin/activeadmin#3981]
I use Rails4.1.8
I add ```gem 'activeadmin', github: 'activeadmin'``` to my gemfile to bundle
But i was stuck  with ```Fetching git://github.com/activeadmin/activeadmin.git``` for a very long time
So that i cannot fetch this gem

If i directly use ```gem 'activeadmin'```, it does't support Rails 4

Any help? Thanks in advance

**Comment by timoschilling** [comment]
If you can't fetch from github, you maybe have a network or bundler problem.

You can use the preversion of ActiveAdmin `gem 'activeadmin', '~> 1.0.0.pre1'
