### ISSUE TITLE
Blank index page, new setup

### ISSUE THREAD

**Issue by francispotter** [activeadmin/activeadmin#3982]
Hi there,

Experienced Rails dev here but my first time using ActiveAdmin. I created a very simple model in ActiveRecord with just one attribute, "name". I then ran the generator for ActiveAdmin as per the instructions. Here's what happens:

- Navigation button: It's there
- Index page: Completely blank. Absolutely nothing renders in the browser
- Object page: Looks great. I just enter the object's ID in the URL field, and I get a nice page

I tried adding

```
index do
  column :name
end
```

to the ActiveAdmin config but that didn't make a difference.

So I've never seen an ActiveAdmin index page. There's nothing useful in the logs. Any suggestions?

**Comment by timoschilling** [comment]
Please try this:
```bash
curl http://localhost:3000/admin/MODEL
# and
curl -I http://localhost:3000/admin/MODEL
```

Whats the output?

**Comment by francispotter** [comment]
We had a conflict between kaminari and will_paginate. The fix was:

```ruby
# config/initializers/will_paginate.rb
if defined?(WillPaginate)
  module WillPaginate
    module ActiveRecord
      module RelationMethods
        alias_method :per, :per_page
        alias_method :num_pages, :total_pages
        alias_method :total_count, :count
      end
    end
  end
end
```
