### ISSUE TITLE
 Unknown action AbstractController::ActionNotFound

### ISSUE THREAD

**Issue by Snoobie** [activeadmin/activeadmin#3983]
Hi,
I follow all the instruction available to this link [activeadmin install](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md).

When I create a new project, I have no problem to access to `localhost:3000/admin`.

But when I add it to a project that already had devise installed, I get the following error: ` Unknown action AbstractController::ActionNotFound` when trying to access to `localhost:3000/admin`.

I would like to know if I'm doing something wrong ?

You can get more informations on this post [activeadmin stackoverflow](http://stackoverflow.com/questions/30719906/how-to-configure-routes-rb-for-get-access-to-localhost3000-admin)

Thank you for your help !

**Comment by seanlinsley** [comment]
This person eventually moved to rails_admin to get around this problem.

**Comment by Snoobie** [comment]
Effectively i had to move on rails_admin, that could solve my problem thank you.
