### ISSUE TITLE
ActiveAdmin will not run in engine

### ISSUE THREAD

**Issue by crystalneth** [activeadmin/activeadmin#3985]
activeadmin 0.6.6
rails 3.2.21

I've tried to create an engine to avoid having active admin in my application code. I can't get the admin to load in the test app of the engine.

Here are the relevant config settings:
activeadmin.rb: # for activeadmin engine

    config.default_namespace = false # Since I will mount the admin engine at /admin

config/routes.rb: # for activeadmin engine

    ActiveAdmin.routes(self)

config/routes.rb: # for test app

    mount AppAdmin::Engine => "/"

Running rake routes in test app:
```
app_admin  / AppAdmin::Engine

Routes for AppAdmin::Engine:
    new_admin_user_session GET    /admin_users/sign_in(.:format)       app_admin/sessions#new
        admin_user_session POST   /admin_users/sign_in(.:format)       app_admin/sessions#create
destroy_admin_user_session DELETE /admin_users/sign_out(.:format)      app_admin/sessions#destroy
       admin_user_password POST   /admin_users/password(.:format)      app_admin/passwords#create
   new_admin_user_password GET    /admin_users/password/new(.:format)  app_admin/passwords#new
  edit_admin_user_password GET    /admin_users/password/edit(.:format) app_admin/passwords#edit
                           PUT    /admin_users/password(.:format)      app_admin/passwords#update
                      root        /                                    app_admin/dashboard#index
     batch_action_comments POST   /comments/batch_action(.:format)     app_admin/comments#batch_action
                  comments GET    /comments(.:format)                  app_admin/comments#index
                           POST   /comments(.:format)                  app_admin/comments#create
                   comment GET    /comments/:id(.:format)              app_admin/comments#show
```

Now when I run the test app and hit "/" I get this error:

    ActionController::RoutingError (uninitialized constant AppAdmin::DashboardController):

or /admin_users/sign_in

    uninitialized constant AppAdmin::SessionsController

So activeadmin doesn't seem to be defining the controllers in the engine module's namespace.

**Comment by timoschilling** [comment]
Have you reed this? https://github.com/activeadmin/activeadmin/wiki/Define-a-resource-inside-an-engine

**Comment by crystalneth** [comment]
Thanks. I have not seen that. I ended up just putting the active admin stuff in my base repository unfortunately. Might give the tips in their a try at some point.

**Comment by timoschilling** [comment]
Sounds like this issue can be closed, otherwise let me know
