### ISSUE TITLE
Edit resource fails after changing the name of a column

### ISSUE THREAD

**Issue by icyflame** [activeadmin/activeadmin#3990]
- Everything was working
- I changed the name of a column from `Alumni_id` to `alumni_id`. (using an appropriate migration: [find here](https://github.com/icyflame/erp-rails/blob/master/db/migrate/20150611172333_down_case_column_names.rb)
- Now, **Resources that have `alumni_id` as a member in their permitted params list can't be edited.**
- I have changed the case of letters in all the files under `app/admin`.
- Other functionality of the App is unaffected.

This is the app: [icyflame/erp-rails](http://github.com/icyflame/erp-rails)

**Comment by icyflame** [comment]
@timoschilling 

?

**Comment by timoschilling** [comment]
Do you have solve your problem?

**Comment by icyflame** [comment]
No, I have not. As a matter of fact, I had to move to RailsAdmin to solve this problem. Please fix this issue in future releases.
