### ISSUE TITLE
modal_dialog event triggering (proposal)

### ISSUE THREAD

**Issue by Fivell** [activeadmin/activeadmin#3991]
Hello dear contributors, I have a proposal to create js event for Modal Dialog initialization, I think this hook can be very helpful and used in many ways, for instance to attach choosen for drop-downs, or other jquery plugins to input elements.

The event can  be triggered in same way as AA already does for has_many inputs  here
https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/app/assets/javascripts/active_admin/lib/has_many.js.coffee#L20

The similar can be implemented here 
https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/app/assets/javascripts/active_admin/lib/modal_dialog.js.coffee#L31

My suggestion is using next

```coffeescript
form = $(html).appendTo('body')
$('body').trigger 'modal_dialog:before_open', [form]  #<--- here we go
  form.dialog
    modal: true
    dialogClass: 'active_admin_dialog'
    buttons:
      OK: ->
        callback $(@).serializeObject()
        $(@).dialog('close')
      Cancel: ->
        $(@).dialog('close').remove()

$('body').trigger 'modal_dialog:after_open', [form]  #<--- here we go
```

@timoschilling , do you have any thoughts  about this?

**Comment by timoschilling** [comment]
:+1:

**Comment by Fivell** [comment]
idea is to make such construction work for different pages
```javascript
$('body.customers').on('modal_dialog:after_open', function(event, form) {
 
});
```
```javascript
$('body.order').on('modal_dialog:after_open', function(event, form) {
 
});
````

**Comment by workgena** [comment]
Good Idea, if I understend jquery-ui modals correctry, close-events should be written like this:

```javascript
form = $(html).appendTo('body')
$('body').trigger 'modal_dialog:before_open', [form]  #<--- here we go
  form.dialog
    modal: true
    dialogClass: 'active_admin_dialog'
    open: (event, ui)->
      $('body').trigger 'modal_dialog:after_open', [form]  #<--- here we go
    buttons:
      OK: ->
        callback $(@).serializeObject()
        $(@).dialog('close')
      Cancel: ->
        $(@).dialog('close').remove()
```

http://api.jqueryui.com/dialog/#event-open

**Comment by workgena** [comment]
What will happened if there would be two modal-forms in same page?

The events will be without special marks. Perhapse it would be good to have another parameter

$('body').trigger 'modal_dialog:before_open', ['some-uniqu-id', form]

But in this method we don't have any unique marks. Only "message".

**Comment by Fivell** [comment]
@workgena , for now there is only one possible dialog for each page (for batch actions), AA doesn't support custom dialogs for member actions and so on.

**Comment by Fivell** [comment]
dialog form inside AA has id ```dialog_confirm``` which I think is not describes itself. 

@timoschilling, maybe would be better to rename it to ```batch_action_dialog_confirm``` ?

**Comment by Fivell** [comment]
@workgena , that's it, :+1: 

@timoschilling , can it be merged ?
