### ISSUE TITLE
Paper trail history as index page with filters and pagination

### ISSUE THREAD

**Issue by cpfarher** [activeadmin/activeadmin#3993]
I saw in the doc this feature: [https://github.com/activeadmin/activeadmin/issues/561] that is awesome, but I need filters and pagination over versions. I have a model (Product) with it's own version table (ProductLog) implemented with paper_trail gem. 

Now I have a belongs_to relations in order to access to product log like: http://localhost:3000/admin/products/8973/product_logs (and here I have filters an pagination), but the problem is that I can't see the object fields as columns in index...I would like to see in the index the name, category_id, etc. of every version... I tried to redefine "collection" method of inherited resourece without success.... What is the best option for this ?

Also, I think I will add documentation of this case in the link above, if I find the solution...

**Comment by timoschilling** [comment]
Ask on stackoverflow
