### ISSUE TITLE
Ransack definition issue upgrading activeadmin from 1.0.0.pre to 1.0.0.pre1

### ISSUE THREAD

**Issue by swaroopmurthy** [activeadmin/activeadmin#3994]
We have model classes defined as a separate gem from the activeadmin app. Upon upgrading from 1.0.0.pre to 1.0.0.pre1 we get the following error:

    Error Message: undefined method `ransack' for #<#<Class:0x4bf754f0>:0x2aec155>

It's trying to call "ransack" on a presenter object. The object doesn't have "ransack" nor "search" methods, please document how to upgrade.

**Comment by Fivell** [comment]
@swaroopmurthy . did you try master branch ? 
I think this was fixed here https://github.com/activeadmin/activeadmin/commit/49eea30553f12ee5e516392470faa0bb15459009

**Comment by swaroopmurthy** [comment]
@Fivell wow, that does work. please discard the pull request. thank you :+1:
