### ISSUE TITLE
Add locale to the configuration

### ISSUE THREAD

**Issue by crashbell** [activeadmin/activeadmin#3998]
I'm finding a good way to make the localization config easily. 

Regarding [this](https://github.com/activeadmin/activeadmin/wiki/Switching-locale) I got a problem with default action items. I have to override all default action items in each resource. That's painful. I read the source code and see that I can do something at [this method](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource/action_items.rb#L57) but I don't know how `resource_path` methods was defined. I'm thinking about putting the custom locale to these `resource_path` methods and then we can make a new configuration for locale in `initializers/active_admin.rb`, something like `config.locale_enable = true` and all links will include the current locale.

**Comment by crashbell** [comment]
Currently, I added the `:locale` in [this commit](https://github.com/crashbell/activeadmin/commit/47505a93d1715bf6c09cce875e02cf55763b1568), just to make my application works first. That's not a good way, but somehow, it can solve my problem. Looking for another way to do it elegantly.

**Comment by timoschilling** [comment]
Your repo is deleted, so I think this is no longer a issue

**Comment by crashbell** [comment]
Thank you. That's such too long for an issue, I was good with my way.
