### ISSUE TITLE
filtering does not get applied to batch_action_collection

### ISSUE THREAD

**Issue by AndrewSwerlick** [activeadmin/activeadmin#4000]
When performing a batch action on a filtered set of records, batch_action_collection still returns all records. This appears to be because there's nothing in the BatchActionForm that ensures that `params[:q]` will be included in the post request, either in the action url or as a hidden input. 

Is there something I should be doing to ensure batch_action_collection is filtered, or is this a bug?

**Comment by timoschilling** [comment]
Please provide an example

**Comment by AndrewSwerlick** [comment]
Here's a sample project demonstrating the issue https://github.com/AndrewSwerlick/active-admin-bug-ex.  To reproduce do the following

1. `rake db:migrate`
2. `rake db:seed`
3. `rails s`
4. Browse to http://localhost:3000/admin/posts
5. Filter by one of the categories
6. Select the batch action "Feature posts Selected"
7. Check the "apply_to_hidden_pages" box
8. Submit

You'll see that the batch action applies to all 501 records, rather than the 100 that meet the filter criteria.

It was my understanding that `batch_action_collection` method which I use in my batch action method was supposed to only include the filtered record set. But this shows it always includes the whole thing.

**Comment by osyoav2** [comment]
When you do a small debug you can see that batch_action_collection is the complete data-set, not the filtered one.
However, look at the code [here] (https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/active_admin/batch_actions/controller.rb) and you'll see it can accept some parameters.
Also, "collection_selection" contains the dataset for the batch action.

Hope this helps.

**Comment by timoschilling** [comment]
@Fivell can you take a look

**Comment by Fivell** [comment]
Will check after returning from vocation, looks like js is not submitting
filters data, while performing batch actions
29.06.2015 9:56 пользователь "Timo Schilling" <notifications@github.com>
написал:

**Comment by Fivell** [comment]
after small review, 
method 
```
batch_action_path(params = {})
```
should return uri with populated ```q``` and  ```scope``` params
https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/active_admin/batch_actions/resource_extension.rb#L56

**Comment by Fivell** [comment]
@timoschilling , pls review PR

**Comment by Fivell** [comment]
@AndrewSwerlick , possible better solution for your problem https://github.com/activeadmin-plugins/active_admin_scoped_collection_actions
