### ISSUE TITLE
Remove Filter Referencing Wrong Model

### ISSUE THREAD

**Issue by SirUncleCid** [activeadmin/activeadmin#4001]
Currently I have a model Shirt, and I want to remove a filter because it is a has_many :through association.

So, I have Shirt, ShirtCollection, Collection.

Without trying to remove the filter, I get:
undefined method `shirt_collections_id_eq' for Ransack::Search<class: Shirt, base: Grouping <combinator: and>>:Ransack::Search

When I attempt to remove the filter with "remove_filter :shirt_collections", I get:
uninitialized constant Shirt::Collections

Thank you very much in advance.

**Comment by timoschilling** [comment]
please try:
```ruby
remove_filter :shirt_collection
# or
remove_filter :shirt_collections_id
```

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
