### ISSUE TITLE
"+HH:MM" or "-HH:MM" expected for utc_offset: Argument Error

### ISSUE THREAD

**Issue by nrakochy** [activeadmin/activeadmin#4006]
I just created a new app using these configurations:

    jruby-1.7.18
    rails 4.2.2
    activeadmin 1.0.0pre1

After bundling everything up, I can log into the admin portal and view the dashboard. When I navigate to anything related to an admin user (#show, #index, etc.), I get a
    
    ArgumentError in Admin::AdminUsers#show

    "+HH:MM" or "-HH:MM" expected for utc_offset

    Rails.root: /code/rails_projects/incident_management

There is a problem with the timestamp of the Admin User, but I am not sure if this is a JRuby issue or ActiveAdmin. Any help would be definitely appreciated.
 
What is saved in the DB (note esp. the timestamps, which are ActiveSupport::TimeWithZone):

    #<ActiveRecord::Relation [#<AdminUser id: 1, email: "admin@example.com", encrypted_password: 
    "$2a$10$kahd6zgnFr8Bw0EdlUb8augzMvUb6TcHwREcHtZqUaA...", reset_password_token: nil,   
    reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-
    06-25 03:21:32", last_sign_in_at: "2015-06-25 03:21:32", current_sign_in_ip: #<IPAddr: 
    IPv4:127.0.0.1/255.255.255.255>, last_sign_in_ip: #<IPAddr: IPv4:127.0.0.1/255.255.255.255>, 
    created_at: "2015-06-25 03:12:52", updated_at: "2015-06-25 03:21:32">]>

And a partial stacktrace (this goes on for 127 lines, so please let me know if you would like more):

    org/jruby/RubyTime.java:443:in `getlocal'
    activesupport (4.2.2) lib/active_support/time_with_zone.rb:79:in `localtime'
    activesupport (4.2.2) lib/active_support/time_with_zone.rb:208:in `strftime'
    i18n (0.7.0) lib/i18n/backend/base.rb:74:in `localize'
    i18n (0.7.0) lib/i18n.rb:247:in `localize'
    actionview (4.2.2) lib/action_view/helpers/translation_helper.rb:88:in `localize'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/view_helpers/display_helper.rb:49:in `pretty_format'
    arbre (1.0.3) lib/arbre/element.rb:180:in `method_missing'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/views/components/attributes_table.rb:82:in `content_for'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/views/components/attributes_table.rb:39:in `row'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `build_tag'
    arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:18:in `td'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/views/components/attributes_table.rb:38:in `row'
    org/jruby/RubyArray.java:1613:in `each'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/views/components/attributes_table.rb:37:in `row'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `build_tag'
    arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:18:in `tr'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/views/components/attributes_table.rb:33:in `row'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/views/components/attributes_table.rb:19:in `rows'
    org/jruby/RubyArray.java:1613:in `each'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/views/components/attributes_table.rb:19:in `rows'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/views/components/attributes_table.rb:15:in `build'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `build_tag'
    arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:18:in `attributes_table_for'
    /Users/nrakochy/.rbenv/versions/jruby-1.7.18/lib/ruby/gems/shared/bundler/gems/active_admin-655e2be7a351/lib/active_admin/views/pages/show.rb:29:in `attributes_table'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `build_tag'
    arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
    arbre (1.0.3) lib/arbre/element/builder_methods.rb:18:in `panel'

And the full Gemfile: 

    source 'https://rubygems.org'
    gem 'rails', '4.2.2'
    gem "activeadmin", github: "gregbell/active_admin"
    gem "devise"
    gem 'activerecord-jdbcpostgresql-adapter'
    gem 'sass-rails', '~> 5.0'
    gem 'uglifier', '>= 1.3.0'
    gem 'coffee-rails', '~> 4.1.0'
    gem 'therubyrhino'
    gem 'jquery-rails'
    gem 'turbolinks'
    gem 'jbuilder', '~> 2.0'
    gem 'warbler'
    gem 'sdoc', '~> 0.4.0', group: :doc
    gem 'puma'

    group :development, :test do
    gem 'rspec-rails'
    gem 'capybara'
    end

    gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jru

**Comment by osyoav2** [comment]
Defiantly a jruby issue.
Have a look [here] (https://github.com/jruby/jruby/issues/755), According to the last comment you should use jruby 1.7.4 to fix the issue.
@timoschilling I think you can close this..

**Comment by timoschilling** [comment]
@nrakochy let me know if @osyoav2 post don't help
