### ISSUE TITLE
set default value to text_field

### ISSUE THREAD

**Issue by praneeththota** [activeadmin/activeadmin#4007]
How to set default value to text field
i tried with 
f.text_field :date, :value => Date.today

Can you please help me out of this

**Comment by timoschilling** [comment]
```ruby
f.text_field :date, input_html: { value: Date.today }
```
For the formbuilder usage take a look on the [formtastic](https://github.com/justinfrench/formtastic)

**Comment by praneeththota** [comment]
@timoschilling it is not working
below is my code
f.inputs do
       f.input :club_id, :as => :select, :collection => Club.where(:status => true), :prompt => "Select Club"
       f.input :name, :label => "Event Name"
       f.input :web_link
       f.text_field :date, input_html: { value: Date.today }
     end

I tried with f.input also but not working
