### ISSUE TITLE
update installation documentation for rails 4.

### ISSUE THREAD

**Issue by perrierism** [activeadmin/activeadmin#4013]
http://activeadmin.info/docs/documentation.html says:

> If you are using Rails >= 3.1, you must also include a beta version of MetaSearch and sass-

>    # Gemfile in Rails >= 3.1
>    gem 'activeadmin'
>    gem 'sass-rails'
>    gem "meta_search", '>= 1.1.0.pre'

following these instructions for Rails 4 leads the user to #3926 .

Rails 4 seems to require just:
   `gem 'activeadmin', github: 'activeadmin'`

But this can only be guessed at by reading the github readme.

**Comment by timoschilling** [comment]
http://activeadmin.info is out of date

**Comment by perrierism** [comment]
@timoschilling 

That's not very helpful. Any plans on making it not out of date? or adding a message to the site? "out of date" is the whole point of the ticket. It took a few minutes to figure this out and a few to write you a ticket, which I did as a curtesy to the project.

**Comment by timoschilling** [comment]
Yes we plan to update http://activeadmin.info, but didn't have the time
