### ISSUE TITLE
Can't add a custom class to filter

### ISSUE THREAD

**Issue by swaroopmurthy** [activeadmin/activeadmin#4014]
Not exactly an issue, more of a question, does anyone know how to add a custom class to the side filters?

I've tried
    filter :property, as: :select, label: 'Property', html: {class: 'something'}
and 
    filter :property, as: :select, label: 'Property', class: 'something'

**Comment by Fivell** [comment]
@swaroopmurthy 
```ruby
filter :property, as: :select, label: 'Property', input_html: {class: 'something'}
```
