### ISSUE TITLE
Hello I want links to open up in a new page!

### ISSUE THREAD

**Issue by YonasBerhe** [activeadmin/activeadmin#4017]
At first I added the <b>target="_blank"</b> to all of my link tags. After I realized that did not work I tried changing the links on my page to a tiny url, assuming that their was something wrong with my link, but I was wrong. Then I tried adding that snippet of code to my page and that also did not work. I'm stuck and I need help. 
```
$(document).ready(function() {
  $("a[@href^=http]").each(
    function(){
     if(this.href.indexOf(location.hostname) == -1) {
        $(this).attr('target', '_blank');
      }
    }
  )
});
```

**Comment by timoschilling** [comment]
What doesn't work? Your JS code or the integration into ActiveAdmin?
Does this works?
```javascript
$(document).ready(function() {
  alert('test');
});
```
If not where do you have placed your code?

**Comment by YonasBerhe** [comment]
Links will not open in new tabs on the Active Admin edit pages. I tried your code and it also did not work. I enter the JavaScript in a script tag along side the markup, should I be entering it in different?. It seems like the Active Admin doesn't allow links to be open in new tab. The image below is what I'm using to edit my pages.
![screenshot from 2015-07-02 12 02 15](https://cloud.githubusercontent.com/assets/8443899/8485410/3f99197c-20b2-11e5-8c26-d3309c3e0d41.png)


The code snippet below won't work on ActiveAdmin

 href="http://google.com/" target="_blank"
<a href="http://google.com/" target="_blank">Click here</a>

**Comment by timoschilling** [comment]
> JavaScript in a script tag along side the markup

What do you mean with that?

Search for `register_javascript` in your activeadmin initializer

**Comment by YonasBerhe** [comment]
I just open two script tags and put my JS in between those tags. My markup is located above.

**Comment by timoschilling** [comment]
Again the question, where do you have placed the JS code? I can't see the markup anywhere.

**Comment by YonasBerhe** [comment]
I can't show the exact code written, but the code below illustrates where my Javascript is being placed. 
<html>
<a>example code</a>
<script>
$(document).ready(function() {
  $("a[@href^=http]").each(
    function(){
     if(this.href.indexOf(location.hostname) == -1) {
        $(this).attr('target', '_blank');
      }
    }
  )
});
</script>
</html>

**Comment by timoschilling** [comment]
There is no code, that shows where do you have placed the JS code!
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by YonasBerhe** [comment]
Re-edited the last comment, bad Github markup. Does the link to the Gist answer your question? I really want to get this solved.

**Comment by timoschilling** [comment]
It still don't show how this code came into active admin

**Comment by YonasBerhe** [comment]
I put the code into the text editor that active admin provides.? Can you be a bit more concrete? Maybe I'm missing something, I'm fairly new to active admin so please excuse me.

**Comment by timoschilling** [comment]
First let me ask what do you want to do?
Where should your JS run? In the ActiveAdmin backend or in you Frontend?

**Comment by YonasBerhe** [comment]
I simply want links to open in new tabs. This is all client side.

**Comment by timoschilling** [comment]
Client side in the ActiveAdmin backend or in the frontend?

**Comment by YonasBerhe** [comment]
Frontend

**Comment by timoschilling** [comment]
I'm closing this, while your problem is not ActiveAdmin related.

But some hints:
- You can't past JS code in the editor, while it will be escaped in the frontend, to protect XSS attacks. http://edgeguides.rubyonrails.org/security.html#cross-site-scripting-xss
- You should place the JS code in the application.js file of you app
