### ISSUE TITLE
Add/Remove columns from Comments index page

### ISSUE THREAD

**Issue by scarver2** [activeadmin/activeadmin#4020]
How does one add or remove columns from the Comments index page?

In https://raw.githubusercontent.com/activeadmin/activeadmin/master/lib/active_admin/orm/active_record/comments.rb, I found this code (line 71..78):

```ruby
      index do
        column I18n.t('active_admin.comments.resource_type'), :resource_type
        column I18n.t('active_admin.comments.author_type'),   :author_type
        column I18n.t('active_admin.comments.resource'),      :resource
        column I18n.t('active_admin.comments.author'),        :author
        column I18n.t('active_admin.comments.body'),          :body
        actions
      end
```

I would like to add the creation date as a column.

```ruby
    column I18n.t('active_admin.comments.created_at'), :created_at
```

**Comment by timoschilling** [comment]
There is no API way, for that. You can place the same file in your app to overwrite it.

But a `created_at` column is a good idea at that point, so PR's are welcome.

**Comment by scarver2** [comment]
I tried overriding the file at #{Rails.root}/lib/active_admin/orm/active_record/comments.rb to no avail. Any suggestions?

**Comment by scarver2** [comment]
Hi Tom. I added the column to this pull request: https://github.com/activeadmin/activeadmin/pull/4021
