### ISSUE TITLE
Adding action buttons to Create/Edit pages

### ISSUE THREAD

**Issue by syndbg** [activeadmin/activeadmin#4022]
What's the best way to add buttons to http://demo.activeadmin.info/admin/products/new

Instead of having actions `Create Product` and `Cancel`, lets say that it should have actions `Create Featured Product`, `Create Product` and `Cancel` ?

**Comment by osyoav2** [comment]
I think this is what you need
```Ruby
  form do |f|
    f.actions do
      f.action :submit
      f.action :submit, label: "Create Featured Product", url: "some_url_for_create(@product)"
      f.action :cancel, :wrapper_html => { :class => 'cancel'}
    end
  end
```

**Comment by syndbg** [comment]
Hey @osyoav2  thanks for your response. I figured it out and I should answer it for other people and maybe update the docs.

Anyway the solution is:

1. Add submit buttons as you showed, except that having a different `url` is probably an overkill and won't do all the ActiveAdmin validation and error displaying.
2. Override the create/update actions for the specific ActiveAdmin Controller.
3. Read from `permitted_parameters[:commit]` which is actually the submit button's label text.

So in code the controller part is something like
```
  controller do
    def create
      submit_status = permitted_params[:commit].downcase

      if submit_status.include?('featured')
        @product = Product.new(permitted_params[:product].merge(status: submit_status))
      end

      super
    end

    def update
      submit_status = permitted_params[:commit].downcase

      if resource.errors.empty? && submit_status.include?('featured')
        resource = resource.update(status: submit_status)
        @product = resource
      end

      super
    end
  end
```
