### ISSUE TITLE
Help needed with AA internals

### ISSUE THREAD

**Issue by fabn** [activeadmin/activeadmin#4024]
First of all sorry to bother you with this but I don't know where to get some help with this issue, please feel free to close it if you think I'm completely off theme.

Some time ago I forked an unmantained activeadmin plugin and customized to work with latest AA versions. After you removed `#form_buffers` api in #3486 my fork stopped to work and I had to change it.

However when I changed the code to work without `#form_buffers` the intented gem syntax stopped to work as is and now it works only if [wrapped into a `f.inputs` block](https://github.com/fabn/activeadmin-globalize/issues/4#issuecomment-96618071).

I tried in every way to make it working but I do not fully understand what is happening in [#inputs method](https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/active_admin/views/components/active_admin_form.rb#L44) and whatever syntax I use for my implementation I always get the latest user input field.

I created a branch with [unit tests](https://github.com/fabn/activeadmin-globalize/blob/feature/issue-4/spec/lib/active_admin/globalize/form_builder_extension_spec.rb) in order to get some more detailed results while experimenting with this issue and I'm close to the result however I still miss user fields.

[This test](https://github.com/fabn/activeadmin-globalize/blob/feature/issue-4/spec/lib/active_admin/globalize/form_builder_extension_spec.rb#L95) fails because all but last user inputs are stripped out. I think the key is in the way [I call the user block](https://github.com/fabn/activeadmin-globalize/blob/feature/issue-4/lib/active_admin/globalize/form_builder_extension.rb#L49), I tried a lot of combinations but I'm not able to render all user inputs. Any clue on how to use the `inputs` method with a user block?

Thank you in advance for any answer.

**Comment by timoschilling** [comment]
Maybe @varyonic can help?

**Comment by timoschilling** [comment]
Is this still a issue?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
