### ISSUE TITLE
No route matches for member actions after update

### ISSUE THREAD

**Issue by chengguangnan** [activeadmin/activeadmin#4025]
I was using the master branch. 

    gem 'activeadmin', github: 'activeadmin'

My code was working for months without change. I did `bundle update` several times recently, so I do not know which version introduced the problem. 

Here is the code that used to be working, a member_action and an action_item.

```
  member_action :build_rhymes do
   resource.build_rhymes
   redirect_to resource_path, notice: "New rhymes built."
 end

  action_item :build_rhymes do
    link_to("Build rhymes", action: :build_rhymes)
  end
```

Now I'm getting an error that says:

```
No route matches {:action=>"build_rhymes", :controller=>"admin/words"}
```

which is thrown from the action_item

```
    link_to("Build rhymes", action: :build_rhymes)
```

Do you know what caused this problem and how to fix this?

**Comment by timoschilling** [comment]
What does `rake routes` says?

**Comment by chengguangnan** [comment]
I can't spot any error from `rake routes`.

          build_rhymes_admin_word GET        /admin/words/:id/build_rhymes(.:format)      admin/words#build_rhymes

**Comment by chengguangnan** [comment]
I find the problem. The error happens on the listing page. Perhaps due to the lack of object "word" thus failed to build the url.

```
  action_item(:build_rhymes, only: %i( show edit ) )do
    link_to("Build rhymes", action: :build_rhymes)
  end
```
Perhaps in the past this error would be `rescued`? I don't know. You may close this ticket if you think it's the desired behavior.

**Comment by seanlinsley** [comment]
The error definitely could have been better presented, but this error is expected because `member_action` defines a controller action for an individual record, but your `action_item` was being rendered on the index page. Your addition of `only: %i( show edit )` was the correct fix.
