### ISSUE TITLE
NoMethodError in ActiveAdmin::Devise::Sessions#new

### ISSUE THREAD

**Issue by guille1194** [activeadmin/activeadmin#4027]
I've just added activeadmin to my project following the instructions, and on loading http://localhost:300/admin, I get this error: 

Showing c:/12_in_12_challenge/Ruby21/lib/ruby/gems/2.1.0/gems/activeadmin-1.0.0.pre1/app/views/layouts/active_admin_logged_out.html.erb where line #9 raised:

undefined method `path' for ["active_admin.css", {:media=>"screen"}]:Array

Here is the code of active_admin_logged_out.html.erb:

```erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
 
  <title><%= [@page_title, active_admin_application.site_title].compact.join(" | ") %></title>

  <% ActiveAdmin.application.stylesheets.each do |style| %>
    <%= stylesheet_link_tag style.path, style.options %>
  <% end %>
  <% ActiveAdmin.application.javascripts.each do |path| %>
    <%= javascript_include_tag path %>
  <% end %>

  <%= csrf_meta_tag %>
</head>
<body class="logged_out <%= controller.action_name %>">
<div id="wrapper">

  <div id="content_wrapper">
    <% if flash.keys.any? %>
      <% flash.each do |type, message| %>
        <%= content_tag :div, message, :class => "flash flash_#{type}" %>
      <% end %>
    <% end %>
    <div id="active_admin_content">
      <%= yield %>
    </div>
  </div>
  <div id="footer">
    <%= yield :footer %>
  </div>
</div>
</body>
</html>
```

**Comment by timoschilling** [comment]
From where do you have this file? Thats file version is outdated since ~3 years.
You can find the current version here: https://github.com/activeadmin/activeadmin/blob/master/app/views/layouts/active_admin_logged_out.html.erb
