### ISSUE TITLE
how to hide fields

### ISSUE THREAD

**Issue by tralles** [activeadmin/activeadmin#403]
I've an Location-Object wich calculates Latitude and Longitude on save. But these two fields should not apear in the admin-backend. i found no solution to hide fields …

**Comment by abhijitsinha** [comment]
@tralles agree. It will be great to have explicit hide rather specifying what I want to see may work for some but having both will satisfy both needs.

**Comment by FanaHOVA** [comment]
You should be able to do `default_fields Model.attribute_names.map(&:to_sym) - %i[field_to_exclude another_one_too]`
