### ISSUE TITLE
Consider using Baremetrics datepicker

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#4034]
Baremetrics' datepicker is the best I've seen so far. We might want to consider vendoring it as the default.

Github: https://github.com/Baremetrics/calendar

Demo: http://baremetrics.github.io/calendar/

<img width="289" alt="screen shot 2015-07-19 at 11 56 29 pm" src="https://cloud.githubusercontent.com/assets/688886/8770206/7924da1e-2e72-11e5-9661-ffbdfddb0418.png"><img width="296" alt="screen shot 2015-07-19 at 11 56 54 pm" src="https://cloud.githubusercontent.com/assets/688886/8770207/792c1df6-2e72-11e5-992a-58a7faca3c47.png">

**Comment by timoschilling** [comment]
look's nice, but I think we should not depend on a UI gem, do everyone can make it's own choice.

**Comment by seanlinsley** [comment]
@timoschilling while we shouldn't prevent them from using what they want, we should provide something by default that looks good and works well. I think Baremetrics' datepicker makes more sense than the jQuery UI datepicker we're currently using.

**Comment by timoschilling** [comment]
@seanlinsley I understand you, but we jQuery UI, if some want something else he can use it. or can use `activeadmin-baremetrics`.

**Comment by seanlinsley** [comment]
We only use jQuery UI because it's convenient. That shouldn't stop us from using the best possible tools available.

**Comment by deivid-rodriguez** [comment]
I don't think we should worry about this kind of things at this stage. But if we were to start changing this dependencies, so should move towards little standalone utilities that don't depend on jquery.

Here, for example, https://github.com/chmln/flatpickr.

So I vote to close this.

**Comment by varyonic** [comment]
We have a couple of [date picker plugins](https://github.com/activeadmin/activeadmin/wiki/Plugins) already, building another with this widget would be a good project for someone.
