### ISSUE TITLE
Resource page returning a "Could not find table"

### ISSUE THREAD

**Issue by Gespinha** [activeadmin/activeadmin#4037]
Hi there,

I have created an activeadmin resource called "product" and an activeadmin model called "product" to create a section about "Products" in the admin interface.

But inside the admin interface, when I go to the Products page, it show the following error:

Could not find table "products"

What is the problem? Am I missing any configuration?

**Comment by seanlinsley** [comment]
Could you post a stack trace, and the `admin/product.rb` config file?

**Comment by timoschilling** [comment]
Does the model works in you regular rails app?

**Comment by Gespinha** [comment]
I have discovered the origin of my problem, I was creating an ActiveAdmin Resource before a model, which makes my rails app crash.

Thanks for the attention anyway guys :)
