### ISSUE TITLE
Double habtm in nested Activeadmin form

### ISSUE THREAD

**Issue by Defoncesko** [activeadmin/activeadmin#4038]
I am facing a problem, it is not an issue.
In my opinion, I am just missing something.

So here it is :
Recipes have a HABTM relation with Preparations. Preparations have a HABTM relation with Ingredients too.

I can add/update/delete relation to Preparation through Recipe but I can't add/update/delete relation to Ingredient through Recipe.

I also put an example with Recipes and Authors which have also a HATBM relations together and it works fine.

Below my code, I commented where I am facing the problem. Maybe, I am not correctly accessing ID attribute. But I really can't find how to do with a double nested form with HATBM relations.

>Recipe Active Admin

```ruby
ActiveAdmin.register Recipe do

    permit_params :title,
    author_ids:[],
    preparation_ids:[],
    preparations_attributes: [:id, :title, :_destroy, :_update, :_create, 
        #ingredients_attributes: [:id, :text, :_destroy, :_update, :_create],
        #ingredients_ids:[]
    ]
 form do |f|
    f.actions

    f.inputs do

      f.input :title
      f.inputs "Authors" do
        f.input :authors, :as => :select, :input_html => { :class => 'chosen-select' }

      end

      f.inputs "Preparations" do
        f.has_many :preparations do |prep|
            prep.input :title
            prep.has_many :ingredients do |ing|
                ing.input :content, :as => :select, collection: Ingredient.all.map{|ing| ing.content} , :input_html => { :class => 'chosen-select' }
                ing.input :_destroy, :as=>:boolean, :required => false, :label=>'Remove ingredient ?'
            end
        end
      end

    end

    f.actions
end
```

>Recipe Model

```ruby
class Recipe < ActiveRecord::Base

    belongs_to :country

    has_and_belongs_to_many :authors
    accepts_nested_attributes_for :authors, allow_destroy:true

    has_many :preparations, :dependent => :destroy 
    accepts_nested_attributes_for :preparations, allow_destroy:true
end
```

>Preparation Model

```ruby
class Preparation < ActiveRecord::Base

    belongs_to :recipes

    has_and_belongs_to_many :ingredients
    accepts_nested_attributes_for :ingredients, allow_destroy:true
end
```

>Ingredient Model

```ruby
class Ingredient < ActiveRecord::Base
    has_and_belongs_to_many :preparations
end
```

>Author Model

```ruby
class Author < ActiveRecord::Base
    has_and_belongs_to_many :recipes
end
```

Using Rails 4.2.1 and Active Admin 1.0.0

Thanks in advance

**Comment by timoschilling** [comment]
```ruby
    permit_params :title, # you miss the ',' here
    author_ids:[]
```

If that not help you can try turning of permitted parameters with:
```ruby
# config/application.rb
config.action_controller.permit_all_parameters = true
```

If that work you know you need to check your `permit_params` list

**Comment by Defoncesko** [comment]
Is it possible to do a form with 2 levels of HABTM ?
I just added 
`config.action_controller.permit_all_parameters = true`
but it didn't work, I tried to add an ingredient trough recipes form but it wasn't saved.

I tried to change 

`preparations_attributes: [:id, :title, :_destroy, :_update, :_create, 
        #ingredients_attributes: [:id, :text, :_destroy, :_update, :_create],
        #ingredients_ids:[]
    ]`

to 

`preparations_attributes: [:id, :title, :_destroy, :_update, :_create, 
        ingredient_ids:[]
    ]`

Am I right according to relations to recipes, preparations and ingredients ?

**Comment by timoschilling** [comment]
2 levels of HABTM should work.

If you turn off permitted parameters, you don't need to set `permit_params`.

Please post the `Parameters: { ... }` part of your request console output.

BTW: you don't need :_update, :_create, only :_destroy http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html

**Comment by Defoncesko** [comment]
here they are:

`Parameters: {"utf8"=>"✓", "authenticity_token"=>"WacHIFh6qk9pdp80w6TR7yVGZLPzvZahPlLTCurPQLpPd0r94DdDI+8PuvFsw4qyj28nHFZyiG3LjrTcE7psWA==", "recipe"=>{"title"=>"apple pie", "url"=>"", "isVisible"=>"0", "country_id"=>"", "cooking_time"=>"", "preparation_time"=>"", "waiting_time"=>"", "difficulty"=>"", "person"=>"", "advice"=>"", "url_video"=>"", "isVegetarian"=>"0", "isVegan"=>"0", "isNoGluten"=>"0", "isNoLactose"=>"0", "isNoOven"=>"0", "isNoEgg"=>"0", "keyword_ids"=>[""], "author_ids"=>[""], "category_ids"=>[""], "subclass_ids"=>[""], "preparations_attributes"=>{"0"=>{"title"=>"prep1", "ingredients_attributes"=>{"0"=>{"content"=>"ing1", "_destroy"=>"0"}}, "_destroy"=>"0"}}}, "commit"=>"Create Recipe"} `

I can see that I don't have "ingredient_ids" but I have "ingredients_attributes", that should be my problem.

**Comment by timoschilling** [comment]
You don't need `ingredient_ids`

**Comment by timoschilling** [comment]
Have you remind to restart your server after the changes from https://github.com/activeadmin/activeadmin/issues/4038#issuecomment-127217438?

**Comment by Defoncesko** [comment]
Furthermore, I deleted "permit_params" with permitted parameters turned on. I was able to add a new record for ingredients. But the ingredient has been duplicated in my ingredients table and when I update one, the value change. 
For exemple: 
I have ing1 for recipe A
then
I update ing1 to ing2 for recipeA
finally I have 2 ing2 in my ingredients table, and no ing1 anymore.

Yes I did restart the server, but I did'nt delete permit_params. Now I am fine, I restarted and permit_params have been deleted.

**Comment by timoschilling** [comment]
`"ingredients_attributes"=>{"0"=>{"content"=>"ing1", "_destroy"=>"0"}}` need's to look like
`"ingredients_attributes"=>{"0"=>{"id"=>"1", "content"=>"ing1", "_destroy"=>"0"}}`

**Comment by Defoncesko** [comment]
By setting `permit_params` :
`preparations_attributes: [:id, :title,
  		ingredients_attributes: [:id, :content]
  	]`
and disabled `permit_all_parameters`

I have `"ingredients_attributes"=>{"0"=>{"content"=>"ing1", "_destroy"=>"0", "id"=>"20"}}` when I update an ingredient. 
I have a recipeA with ing1 and in my ingredients table I have ing1 and ing2.
Then, when I update ing1 to ing2, I have ing2 and ing2 in my ingredients table.

I noticed, when I create a new recipe, with for example "ing2", it will create a new record for ingredient. And as you said, I don't have the `id` key : 
`"ingredients_attributes"=>{"0"=>{"content"=>"ing2", "_destroy"=>"0"}}`

Should I change my permit_params?

**Comment by timoschilling** [comment]
Is this still a issue?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
