### ISSUE TITLE
Allow max_per_page to be changed via config

### ISSUE THREAD

**Issue by stephenlawrence** [activeadmin/activeadmin#4039]
As an admin, I want to be able to set the max_per_page value in the AA configuration so that I can limit the maximum number of items that will return for a single page in case a user tries to over-ride via per_page with a number I find to be too high.

**Comment by eshaiju** [comment]
@stephenlawrence 
You can set this using   config.default_per_page = 30
https://github.com/activeadmin/activeadmin/blob/master/docs/3-index-pages.md#user-content-index-pagination

**Comment by stephenlawrence** [comment]
I am looking for max_per_page, not default_per_page. As far as I can tell, the max_per_page is hardcoded to 10,000. I would like it lower than that since users can over-ride via the &per_page parameter.

**Comment by timoschilling** [comment]
`max_per_page` don't work in your case, `max_per_page` is only the fallback value.

What we need to support your case (which is a good point btw.) is:
1. make `max_per_page` configurable
2. [`ActiveAdmin::ResourceController::DataAccess#per_page`](https://github.com/activeadmin/activeadmin/blob/8791b6501d464bf707e2c4530e2ca8de14a97b9f/lib/active_admin/resource_controller/data_access.rb#L283) need's to check the value of `dynamic_per_page || configured_per_page` against `max_per_page` and returns `max_per_page` if `dynamic_per_page || configured_per_page` is higher.

**Comment by timoschilling** [comment]
closed by #4052
