### ISSUE TITLE
Conflict with my ApplicationController

### ISSUE THREAD

**Issue by adrianotadao** [activeadmin/activeadmin#4040]
Hello, good night!

ActiveAdmin really need extend my ApplicationController? I would like that ActiveAdmin do not extend it. Is it possible? I'm having conflicts in my variables...

**Comment by maartenvanvliet** [comment]
Could you give a simplified example of the conflicts your variables give?

**Comment by adrianotadao** [comment]
@maartenvanvliet For sure. In my case, I've in my application_controller a variable called @categories and in the active_admin, a page called /categories/. That was the problem. To solve this, I created a new controller, called BaseController and my others controllers extends this one.

I think that we can close this issue. Maybe, the problem is in my application.

Thank you
