### ISSUE TITLE
Rails 5.0 support

### ISSUE THREAD

**Issue by dankohn** [activeadmin/activeadmin#4042]
I wanted to check in if the developers and other users of ActiveAdmin have a plan for supporting Rails 5.0 when it ships, likely later this year. The issue is that ActiveAdmin-dependency inherited_resources is [deprecated](https://github.com/josevalim/inherited_resources#deprecation-notice) and will not be supporting Rails 5.0. They suggest building an alternative solution around the [responders](https://github.com/plataformatec/responders) gem.

If someone else could begin organizing an effort to replace inherited_resources with responders, I may be able to contribute developer resources.

Thanks.

**Comment by timoschilling** [comment]
There is already a Issue for removing inherited_resources (#3604), you are right, but I'm closing this as a double.

**Comment by jlecour** [comment]
Is there any other area of ActiveAdmin that will need some work to be Rails 5 compatible ?

**Comment by jlecour** [comment]
I can see 2 scenarios that seem logical to me, depending on the amount of work needed : 

1. **ActiveAdmin 1.0** is released with **Rails 4.2+/5** compatibility
2. **ActiveAdmin 1.0** is released with the **same compatibility as today**, then another release (1.1 or 2.0 depending on backward compatibility changes) is compatible with Rails 5.0

Scenario **1** is the best in my opinion :)
