### ISSUE TITLE
Active admin with Rails 4.0.0 fails with uninitialized constant ActiveAdmin::Inputs::FilterNumericRangeInput::FilterBase

### ISSUE THREAD

**Issue by alin-turcu** [activeadmin/activeadmin#4044]
I am using gem 'activeadmin', github: 'gregbell/active_admin', with Rails 4.0.0
I also have Node JS installed on a CentOS machine.
I get the following error:

     uninitialized constant ActiveAdmin::Inputs::FilterNumericRangeInput::FilterBase (NameError)
     /home/dev/tracker-backend/config/initializers/filter_numeric_range_input.rb:4:in     `   <class:FilterNumericRangeInput>'
      /home/dev/tracker-backend/config/initializers/filter_numeric_range_input.rb:3:in `<module:Inputs>'
     /home/dev/tracker-backend/config/initializers/filter_numeric_range_input.rb:2:in `<module:ActiveAdmin>'

**Comment by jostster** [comment]
@alin-turcu  What did you do to fix this? I am getting a FilterBase issue as well now that I updated to the master

**Comment by bacrossland** [comment]
The FilterBase class was changed to Base in the module Filters. You have to modify the filter_numeric_range_input.rb that you have in your config/initializers to be ActiveAdmin::Inputs::Filters::FilterNumericRangeInput. Then change the include FilterBase to include Base.
