### ISSUE TITLE
Add scope inside show block

### ISSUE THREAD

**Issue by KelvinMutuma** [activeadmin/activeadmin#4045]
How do I add a scope inside a resource's show block. When I add scope there, I get an error ```Undefined Method 'scope' ```

**Comment by timoschilling** [comment]
What do you want to do with that?

**Comment by KelvinMutuma** [comment]
@timoschilling I have a form resource with many questions. People fill in the form so that I can determine if they have failed or passed. On the form index page, I have a listing of all forms and on the show page of each form/survey I want to have a scope showing the people who have passed or failed.

**Comment by timoschilling** [comment]
Thats not a use case for `scope`, you need to build your own solution for that.

**Comment by KelvinMutuma** [comment]
@timoschilling But I would just do a scope that merges the different models involved. This allows me to take advantage of the activeadmin scope styling that gives buttons for filtering different results according to what I want to view, i.e. ```all```, ```failed``` and ```passed```

**Comment by timoschilling** [comment]
The active admin `scope` is only a filter for the index and don't work in the show context.

**Comment by KelvinMutuma** [comment]
Okay thanks
