### ISSUE TITLE
Docs: Should mention `navigation_menu(nil)`

### ISSUE THREAD

**Issue by jaredbeck** [activeadmin/activeadmin#4046]
The docs show how to specify a particular menu ..

```
ActiveAdmin.register Ticket do
  belongs_to :project
  navigation_menu :project
end
```

~~~.. but they should also demonstrate `navigation_menu(nil)` which is useful for showing all resources (the "top level", or "complete", or "parent" menu - not sure of the correct term).~~~

If `nil` is in fact a supported argument value, please add it to the docs. Thanks!

Possibly relevant docs:

- http://activeadmin.info/docs/2-resource-customization.html#customize-the-menu
- http://activeadmin.info/docs/2-resource-customization.html#belongs-to

**Comment by jaredbeck** [comment]
On second thought, seems like `navigation_menu(nil)` doesn't work.  I'm trying `navigation_menu(:admin)` instead, seems to work better.

**Comment by jaredbeck** [comment]
Maybe `navigation_menu(nil)` should raise an error, like "hey, dummy, there is no such menu"?

**Comment by jaredbeck** [comment]
I see there's a `ActiveAdmin::NoMenuError` but not sure why `navigation_menu(nil)`

**Comment by jaredbeck** [comment]
So far, this is what I've got:

```ruby
  # Show the complete menu, not the limited "child" menu that
  # would be shown because of the `belongs_to`.
  # https://github.com/activeadmin/activeadmin/issues/4046
  navigation_menu :default

  # Do not try to link to posts in the navigation menu.
  # We had to add this when we set `navigation_menu` to `:default`.
  menu false
```

Sorry for the "stream of consciousness" issue.

**Comment by timoschilling** [comment]
`navigation_menu` could raise a `ArgumentError` if no name and no block is given.
https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/active_admin/dsl.rb#L140

**Comment by jaredbeck** [comment]
> navigation_menu could raise a ArgumentError if no name and no block is given.

Sounds good. It could also raise an error if there's no name and the block returns nil?

**Comment by timoschilling** [comment]
If the blog returns nil, a exception will be raised here https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/active_admin/resource/menu.rb#L39

**Comment by timoschilling** [comment]
We have many places where the dev can use wrong arguments, should we really raise ArgumentError everywhere? // cc @seanlinsley

**Comment by jaredbeck** [comment]
> We have many places where the dev can use wrong arguments, should we really raise ArgumentError everywhere?

Not sure if this answers the question, but as an end-user, if I do something dumb, I want a warning.

**Comment by timoschilling** [comment]
> as an end-user, if I do something dumb, I want a warning.

I understand you, but this is out of topic now, maybe you create a new issue to discourse that.

**Comment by timoschilling** [comment]
I'm closing this now, while `navigation_menu(nil)` don't work and should not be documented. Every think else is a new discussion.
