### ISSUE TITLE
Mount engine inside ActiveAdmin

### ISSUE THREAD

**Issue by zackperdue** [activeadmin/activeadmin#4047]
I would like to mount Sidekiq::Web inside ActiveAdmin. Is this possible?

**Comment by timoschilling** [comment]
Yes, follow:
https://github.com/mperham/sidekiq/wiki/Monitoring#rails-3-and-4

The auth part depend, on you auth system.

```ruby
# config/routes.rb
authenticate :admin_user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/admin/sidekiq'
end
```

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by zywx** [comment]
> ```ruby
> authenticate :admin_user, lambda { |u| u.admin? } do
>   mount Sidekiq::Web => '/admin/sidekiq'
> end
> ```

good idea but it won’t work since u.admin? is not a function.
I guess u.present? should be enough though.
