### ISSUE TITLE
has_many breaks in production works in development

### ISSUE THREAD

**Issue by nurulshuvo** [activeadmin/activeadmin#4048]
.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-5a2b7b5bc683/app/views/active_admin/resource/new.html.arb (191.9ms)
I, [2015-07-31T10:51:31.326590 #26202]  INFO -- : Completed 500 Internal Server Error in 254ms
F, [2015-07-31T10:51:31.329305 #26202] FATAL -- : 
ActionView::Template::Error (too many arguments for format string):
    1: insert_tag renderer_for(:new)
  app/admin/business.rb:51:in `block (3 levels) in <top (required)>'
  app/admin/business.rb:36:in `block (2 levels) in <top (required)>'

**Comment by timoschilling** [comment]
please post the `app/admin/business.rb` file

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
