### ISSUE TITLE
How can I use pg_search to do full-text searches using filters?

### ISSUE THREAD

**Issue by ericgross** [activeadmin/activeadmin#4050]
I would like to add a filter that uses pg_search to do it's filtering - can this be done?

http://stackoverflow.com/questions/31791527/how-can-i-use-pg-search-capabilities-from-activeadmin-filters

**Comment by timoschilling** [comment]
Thats not posible. But you can build many queries which can `pg_search` with `ransack` which is supported by activeadmin.
