### ISSUE TITLE
Use different Ransack method

### ISSUE THREAD

**Issue by tmilewski** [activeadmin/activeadmin#4056]
Use `.ransack(params[:q])` over `.search(params[:q])` to avoid conflicts with other libraries that provide a search class method.

https://github.com/activerecord-hackery/ransack#ransack-search-method

**Comment by timoschilling** [comment]
We using already the `ransack` method https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource_controller/data_access.rb#L228
