### ISSUE TITLE
Boolean status_tag only recognizes strings 'true' and 'false'

### ISSUE THREAD

**Issue by StyleOffDev** [activeadmin/activeadmin#4057]
The status_tag component currently renders booleans properly only if they have been converted to strings. `row(:verified) { |u| status_tag(u.verified) }` renders a gray box that says TRUE when true and an empty gray square when false, but `row(:verified) { |u| status_tag(u.verified.to_s) }` renders the proper blue YES or gray NO.

**Comment by noomerikal** [comment]
Looks like this was resolved in a commit for v1.0.0.pre2 -  [14b71181f1af678e2fbe39d40398860e5dc7687f](https://github.com/activeadmin/activeadmin/commit/14b71181f1af678e2fbe39d40398860e5dc7687f)
