### ISSUE TITLE
paper_trail audit doesn't show item correctly

### ISSUE THREAD

**Issue by jostster** [activeadmin/activeadmin#4058]
I've noticed with the current master branch that following https://github.com/activeadmin/activeadmin/wiki/Auditing-via-paper_trail-(change-history) shows the item as <class>. While I can see you can customize the name, with each different model having different structures, this would cause an issue. Why is it showing the item as the class by following the auditing instructions above?
<img width="680" alt="screen shot 2015-08-06 at 9 59 30 am" src="https://cloud.githubusercontent.com/assets/278510/9121266/0e6abc1c-3c36-11e5-9fcc-3ffda1426243.png">

**Comment by bsvin33t** [comment]
I think ActiveAdmin is calling `to_s` on your `member` object. By overriding the `to_s` method, you can get AA to display the correct name.

**Comment by jostster** [comment]
So is the documentation incorrect? I would have to add a `to_s` in all my objects?

**Comment by timoschilling** [comment]
https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/docs/3-index-pages/index-as-table.md#defining-columns
