### ISSUE TITLE
Sharing Controller Code Between AA and Application

### ISSUE THREAD

**Issue by bkubic** [activeadmin/activeadmin#4061]
I use Twilio for my application, and the code managing the Twilio conversation is housed in a separate controller. While that works fine for user-driven action, Admins also need to use the same actions on behalf of users in some cases. As far as I can tell, there is no way to access that controller code in AA, and I have to copy the same code into the appropriate AA controller, which is extremely un-DRY. Am I missing something, or is there no way for AA to access controller code in the main application?

**Comment by timoschilling** [comment]
you can place this code in the ApplicationController or in a Model wich you include in you user and admin controller.

**Comment by bkubic** [comment]
That doesn't really make much sense, though. Twilio interactions are
business logic and should be handled in a controller, not a model, and just
dumping it into Application Controller feels lazy. Wouldn't it make more
sense to allow interaction with controllers in the main application?

**Comment by timoschilling** [comment]
Sorry, I had a miss typing, I mean Module.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
