### ISSUE TITLE
CSV export is localising column headers and inhibiting from import

### ISSUE THREAD

**Issue by kennym** [activeadmin/activeadmin#4063]
When exporting data via CSV and your environment locale is set to something other than English, like this in an initializer:

    I18n.default_locale = :es

My DB schema is in English.

The column headers of the exported CSV are in the localised language. When you then try to import that CSV with `active_admin_import` you'll get an error because it cannot match the headers with the column names which are in English.

I am on master (95fdfe19e3eee9fde4f3ce01a5d96368834eff98)

One quick fix was doing this: https://github.com/kennym/activeadmin/commit/015f54fcfc840eddb9c71971d0560aa6184fc8c0

I wonder though if that's appropriate, and if it would be better to try to reverse match the column name in the `active_admin_import` plugin?

**Comment by Fivell** [comment]
@kennym, this may be fixed in ```active_admin_import```, can you create issue ? also there various  files used in specs , can you provide buggy one? (example https://github.com/activeadmin-plugins/active_admin_import/blob/master/spec/fixtures/files/authors.csv)

**Comment by kennym** [comment]
The CSV itself is not buggy. The column headers are in Spanish, while the DB schema is in English, which results in an unsuccessful import.

**Comment by timoschilling** [comment]
I'm closing this, while it's a `active_admin_import` bug.
