### ISSUE TITLE
Active Admin Truck Factor

### ISSUE THREAD

**Issue by gavelino** [activeadmin/activeadmin#4065]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Active Admin** and obtained a value of **2**.

The developers responsible for this TF are:

Greg Bell - author of 61% of the files
Sean Linsley - author of 16% of the files

To validate our results, we would like to ask **Active Admin** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Active Admin**?

(b) Do you agree that **Active Admin** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Active Admin** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by timoschilling** [comment]
Have you ever take a look on https://github.com/activeadmin/activeadmin/graphs/contributors?
