### ISSUE TITLE
Batch action with all resources

### ISSUE THREAD

**Issue by SebastianVomMeer** [activeadmin/activeadmin#4067]
Having a batch action with a form and a paginated index, I wonder if it's possible to trigger the batch action for all resources. I thought about the following approaches:

#### "Select all" checkbox

The select all checkbox only selects the current page in paginated indexes. I cannot remove pagination in my case.

#### Collection action besides batch action

I could use a collection action that does the same as the batch action. However, it seems like collection actions do not support batch action forms, do they? At least I couldn't find it in the docs.

#### Trigger batch action with custom action_item

A link to the batch action with keyword 'all' instead of the ID list would work, too. However, batch action URL generation seems to be complicated so I don't really know if that is possible and how it can be done.

Does somebody know which approach is the way to go?

**Comment by timoschilling** [comment]
You can use a batch action like for on every post action like:
```html
<a data-confirm="Später anrufen?" data-inputs="{'date':'datepicker','hour':'text','minute':'text','important':'checkbox'}" data-method="post" href="/call_lists/595421/call_later" id="call_later" rel="nofollow">Später anrufen</a>
```

**Comment by SebastianVomMeer** [comment]
This should do it. Thanks a lot.
