### ISSUE TITLE
How can i use activeadmin inside mountable rails engine

### ISSUE THREAD

**Issue by nazrulcse** [activeadmin/activeadmin#4069]
I want to integrate active admin into my mountable rails engine. my configuration:
gem 'activeadmin'
gem 'devise'

My Engine:

``` ruby
module AuthForum
  class Engine < ::Rails::Engine
    isolate_namespace AuthForum
    initializer :auth_forum do
      ActiveAdmin.application.load_paths += Dir[File.dirname(__FILE__) + '/admin']
      require 'jquery-ui-rails'
    end
  end
end
```

Engine Routes:

``` ruby
AuthForum::Engine.routes.draw do
  root 'welcome#index'
  resources :posts
  ActiveAdmin.routes(self)
  devise_for :users, module: :devise
  mount Forem::Engine, :at => '/forums'
end
```

Mount the engine to a application like 

``` ruby
mount AuthForum::Engine => '/'
```

active admin resources located at app/auth_forum//admin directory.

when i try to access admin like http://localhost:3000/admin then it return me error 
uninitialized constant AuthForum::Admin

I am stuck here from 7 days. Could you please help me out?

Thank you

**Comment by nazrulcse** [comment]
Hi @timoschilling 
Any update, I am still stuck here. please give me some instruction so that i can continue.
Thank you.

**Comment by timoschilling** [comment]
I have never used that bevor by my self, so I need to test it.

**Comment by varyonic** [comment]
Two gems that do this are [CommunityEngine](https://github.com/bborn/communityengine) and [PageFlow](https://github.com/codevise/pageflow)

**Comment by risinglf** [comment]
@nazrulcse did you solve this problem with a solution?

**Comment by fuxinhao-crypto** [comment]
@varyonic do you know how to fix this issue?
