### ISSUE TITLE
Cannot use belongs_to in ActiveAdmin if the model doesn't have a belongs_to

### ISSUE THREAD

**Issue by Plaristote** [activeadmin/activeadmin#4071]
Hi,
In my use case, we have UserData which has_many User. And to avoid circular dependencies, we don't want UserData to belongs_to User.
When creating the ActiveAdmin interface for UserData, we use ActiveAdmin's belongs_to:

```
ActiveAdmin.register UserData do
  belongs_to :user, parent_class: User
end
```

Problem is that when we try to create or update an instance of UserData, ActiveAdmin complains because our UserData class does not have an attribute `user`.

Just creating a dummy method called `user` is enough to make it work though... however, we do not want to implement an empty method just for this. Isn't this a bug ? If not, how can we fix this on our end, without using `belongs_to` on the model ?

Thanks.

**Comment by timoschilling** [comment]
Thats not a bug, `belongs_to` and `has_many` is how a relation works in ActiveRecord.

There is no other way then using a `belongs_to` in the User model or the hack with the `user` method.

**Comment by Plaristote** [comment]
Good to know. Thanks for the clarification.
