### ISSUE TITLE
Filterting as check_boxes with enumerize multiple

### ISSUE THREAD

**Issue by kaelumania** [activeadmin/activeadmin#4072]
Filtering is not working with check_boxes and an enumerize object with multiple values.

e.g.: 

Model:
```ruby
serialize :interests, Array
enumerize :interests, in: [:one, :two, :three, :four], multiple: true
```

ActiveAdminController:
```ruby
filter :interests, as: :check_boxes, collection: Model.interests.options
```

**Comment by timoschilling** [comment]
ActiveAdmin `filter` use [`ransack`](https://github.com/activerecord-hackery/ransack) to query the database. Thats why it can't work directly.

You can try it with a `contains` filter, while the serialized object `"[:one, :two, :three]"` contains the string `":one"`.

Or you can write a custom ransacker to query the database.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by kaelumania** [comment]
@timoschilling Thanks. Indeed it worked with a custom ransack :)
