### ISSUE TITLE
The default Collection Applies ordering should be preserved

### ISSUE THREAD

**Issue by wspurgin** [activeadmin/activeadmin#4074]
Here's an error in batch_actions from 1.0.0.pre1: 
```
undefined method `ransack' for #<#<Class:0x00000007f0d7d0>:0x007fab3ed05ca0>
```

This bug occurs because of the order in which the [COLLECTION_APPLIES in are set within the 1.0.0.pre1 block](https://github.com/activeadmin/activeadmin/blob/v1.0.0.pre1/lib/active_admin/batch_actions/controller.rb#L28-L34)

I can see that as of 49eea30 the ordering was fixed, but the root cause is all from how the options and defaults are merged [inside of data_access](https://github.com/activeadmin/activeadmin/blob/v1.0.0.pre1/lib/active_admin/resource_controller/data_access.rb#L277-L281). 

Using the `options.fetch(:only, COLLECTION_APPLIES)` won't preserve the default order (which is the correct order) like thus:
```ruby
defaults = [ :foo, :bar, :baz ]
# => [:foo, :bar, :baz]
only = {only: [:baz, :bar]} # note the change in ordering
Array(only.fetch(:only, defaults))  
# => [:baz, :bar] and now the ordering is wrong :(
```
Which isn't a big deal if the order doesn't matter, but the order *does* matter in this case.

It isn't as pretty, but performing a select and a reject is more suited to preserve the order of the defaults:
```ruby
defaults = [ :foo, :bar, :baz, :ray, :day ]
# => [:foo, :bar, :baz, :ray, :day]
options = { only: [:day, :bar, :foo, :ray], except: [:ray, :foo] }

only = Array(options.fetch(:only, defaults))
# => [:day, :bar, :foo, :ray] again there's a change in the order

except = Array(options.fetch(:except, []))
# => [:ray, :foo] likewise here too

appliers = defaults
               .select { |applier| only.include? applier }
               .reject { |applier| except.include? applier }
# => [:bar, :day] Note that now the original order is preserved with the options applied
```

That's my two-cents on how to do that a little better. It'll be especially helpful if/when you decide to expose some of that configuration ability with how the collections are retrieved to ActiveAdmin users such as myself. That way they won't get headaches wondering why their unbeknownst out-of-order options are making filtering/scoping/includes fail.

**Comment by timoschilling** [comment]
can you create a PR for that?

**Comment by wspurgin** [comment]
Sure thing!


Will Spurgin
will.spurgin@gmail.com
