### ISSUE TITLE
rewriting the CONTRIBUTING guide

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#4079]
We should rewrite the CONTRIBUTING guide.
- [ ] better description of the test setup
- [ ] a issue guide, like [ransack](https://github.com/activerecord-hackery/ransack/blob/master/CONTRIBUTING.md#filing-an-issue) it have

**Comment by varyonic** [comment]
Ref. #4714.  I googled briefly on labels and participation and found [this article about labelling issues for first timers](https://medium.com/@kentcdodds/first-timers-only-78281ea47455).  I don’t expect we will use it often but I propose we have the `first-timers-only` label available in case an opportunity presents itself.  [These](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) [sites](http://www.firsttimersonly.com/) look like good resources to perhaps mention in CONTRIBUTING. Ransack references an [article by thoughtbot](https://robots.thoughtbot.com/8-new-steps-for-fixing-other-peoples-code).

[help-wanted](https://github.com/corylanou/oss-helpwanted) and [up-for-grabs](http://up-for-grabs.net/) are also popular labels, but I prefer to have one label explicitly for first-timers-only and a different label for interesting/stuck issues that deserve attention from someone more experienced looking to make a contribution.  My inclination is to rename ‘stalled’ to ‘help-wanted’ or ’TODO' with the understanding that these are more than first-timers-only.  Reactions?

**Comment by varyonic** [comment]
Another article, this one about [issue tagging best practices](https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/)

**Comment by varyonic** [comment]
Amusing to see @nayafia list the current guide as her [first example](https://github.com/nayafia/contributing-template).

**Comment by nayafia** [comment]
:smile: It has a very friendly introduction!

You might find some useful bits of documentation inspiration [in this guide](https://opensource.guide/building-community/), too.

**Comment by deivid-rodriguez** [comment]
Since we've recently improved both of the bullet points @timoschilling mentions in the issue description, and the current guide seems to be liked by people, I'm tentatively closing this. :tada: 

@timoschilling Of course feel free to reopen if you feel we're missing things here. :)
