### ISSUE TITLE
paper_trail documentation incorrect

### ISSUE THREAD

**Issue by jostster** [activeadmin/activeadmin#4080]
paper_trail documentation https://github.com/activeadmin/activeadmin/wiki/Auditing-via-paper_trail-(change-history) for The 'Add history page' documentation doesn't seem to output any results. Just a blank panel. What is expected is a list of that items version history.

**Comment by pacuna** [comment]
+1

**Comment by pacuna** [comment]
+1

**Comment by timoschilling** [comment]
The Wiki is written by the community and not maintained by the ActiveAdmin team, that means thinks can be outdated, broken oder wrong!

I now have at the same not to the wiki

**Comment by ericpeters0n** [comment]
Updated with my workaround. For reasons unknown (to me), the "versions" method is not available to the model instance in the admin object.

https://github.com/activeadmin/activeadmin/wiki/Auditing-via-paper_trail-(change-history)
