### ISSUE TITLE
undefined local variable or method `devise_migration_file'

### ISSUE THREAD

**Issue by athiraramanan** [activeadmin/activeadmin#4081]
When I am trying to install active admin am getting the following error in devise_generator.rb

 `add_default_user_to_seed': undefined local variable or method `devise_migration_file' for #<ActiveAdmin::Generators::DeviseGenerator:0xb17540c> (NameError)

**Comment by timoschilling** [comment]
should be fixed by 86f7303c17747528eb5cbbb451e2a5a4ac8b188f
