### ISSUE TITLE
How to modify scoped_collection for a sub index

### ISSUE THREAD

**Issue by gjastrab** [activeadmin/activeadmin#4090]
Is there a way to change the scoped_collection just for a sub-index page created like:

```ruby
ActiveAdmin.register Thing do
  class SubThing < ActiveAdmin::Views::IndexAsTable
    def build(page_presenter, collection)
      super(page_presenter
        collection.joins(...).where(...) # to limit what shows up on this sub-index page
      )
    end
  end

  index as: SubThing do
    # custom columns
  end
end
```

The `SubThing` sub-index page shows up properly and overriding `#build` in the class gets the correct data showing up in the table, however the total count and pagination at the bottom are still operating at the top level scoped_collection.  Is there a way to modify the scoped_collection ONLY for this sub-index page?

(this is off of the master branch btw)

**Comment by timoschilling** [comment]
```ruby
ActiveAdmin.register Thing do
```

305	    def scoped_collection

**Comment by timoschilling** [comment]
```ruby
ActiveAdmin.register Thing do
  controller do
    def scoped_collection
      if ...
        super.joins(...).where(...)
      else
        super
      end
    end
  end
end
```

**Comment by timoschilling** [comment]
You can overwrite the `scoped_collection` method to do that.
```ruby
ActiveAdmin.register Thing do
  controller do
    def scoped_collection
      if ...
        super.joins(...).where(...)
      else
        super
      end
    end
  end
end
```

But for the most siturations we have better solutions:
You can do the `where` and `joins` part with a [`scope`](https://github.com/activeadmin/activeadmin/blob/ab3065cec7d2706e379926090815d28a0838ad9b/docs/3-index-pages.md#index-scopes)

**Comment by gjastrab** [comment]
Oops sorry for not clarifying further. On the page we actually have multiple sub indexes - each of which I want to have a different scoped collection for (but which are all indeed scoping off of Thing - just with different joins and conditions).

**Comment by timoschilling** [comment]
You don't need to use indexes for that, use [scopes](https://github.com/activeadmin/activeadmin/blob/ab3065cec7d2706e379926090815d28a0838ad9b/docs/3-index-pages.md#index-scopes) for that or describe why can't use them.

**Comment by gjastrab** [comment]
Different columns as well.

**Comment by timoschilling** [comment]
you can use different columns like this:
```ruby
index do
  column :a if params[:scope] == "a"
  column :b if params[:scope] == "b"
end
```

The different index are for other optical representations, not for data changing.

**Comment by gjastrab** [comment]
Ah true, but then it's doing the counts on all of those different scopes on every scoped page under `Thing`. These pages we're trying to do add are a bit more expensive to query so we'd only want the queries run when actually looking at that page.

I guess what we really want is a sub-page that has an index's behavior so that we can still filter and column sort.

**Comment by timoschilling** [comment]
You can disable all count stuff.

Or you can register one Resource different times.

**Comment by gjastrab** [comment]
Can you expand on what you mean by? Thanks for the help btw!

> register one Resource different times

**Comment by gjastrab** [comment]
(and we do want counts on other existing scopes we have - just not these more expensive sub-indices). Are you able to turn the count of for only certain scopes?

**Comment by timoschilling** [comment]
https://github.com/activeadmin/activeadmin/blob/1fb85de86e537f5a3e7b5692382b53819795ecc3/docs/2-resource-customization.md#rename-the-resource

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
