### ISSUE TITLE
max_width not working

### ISSUE THREAD

**Issue by rebeccacaroline** [activeadmin/activeadmin#4091]
am working with ActiveAdmin in Rails and I want to have a max column width. I researched the docs and it looks like there is a max_width selector, but it's not working for this column. Here is my code:

```column :utility_url, max_width: "200px", sortable: 'meter.url' do |meter|
  link_to meter.url, meter.url if meter.url
end```

Here is the html output: ```<td class="col col-utility_url"><a href="(url is too long to show)"></a></td>```

**Comment by seanlinsley** [comment]
Unfortunately `max_width` only exists on "pages" (i.e. `register_page`), and not on "resources" (i.e. `register`). Instead you can do this:
```css
.col-utility_url {
  max-width: 200px;
}

**Comment by davidalejandroaguilar** [comment]
Is there an update for this?
