### ISSUE TITLE
FIlter using string and 'contains' method generates invalid  Postgres SL

### ISSUE THREAD

**Issue by ashrocket** [activeadmin/activeadmin#4094]
Need to use SIMILAR TO instead of >>

 "SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM \"airlines\" WHERE (\"airlines\".\"name\" >> '---\n- MyQuery\n') LIMIT 30 OFFSET 0) subquery_for_count"

**Comment by timoschilling** [comment]
closed as double of #4078, look over there for some help

**Comment by ashrocket** [comment]
Ah!  I searched but didn't find such an issue logged originally.  Thanks.  Yes the filer action list will work around no problem .  I was using 
filter: attrname_eq for now to avoid the problem , so pleased I can get all 4 actions back!
