### ISSUE TITLE
ActionMailer's default_url_options used as global default_url_options

### ISSUE THREAD

**Issue by lakim** [activeadmin/activeadmin#4098]
Hi AA team,

We have this config in order to track our email links with Google Analytics:

```ruby
config.action_mailer.default_url_options = { host: 'localhost', port: 3000, utm_source: 'dev', utm_medium: 'email' }
```

But after upgrading recently AA, we've seen these params added to all our AA links. For example in the menu header, the Dashboard's href is `http://localhost:3000/admin/dashboard?utm_medium=email&utm_source=dev`
It event breaks the batch actions that post to urls like `http://localhost:3000/admin/posts?utm_medium=email&utm_source=dev/batch_action`.

I've looked into AA's source code, and the culprit is in https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/helpers/routes/url_helpers.rb:

```ruby
module ActiveAdmin
  module Helpers
    module Routes
      module UrlHelpers
        include Rails.application.routes.url_helpers
      end

      extend UrlHelpers

      def self.default_url_options
        Rails.application.config.action_mailer.default_url_options || {}
      end
    end
  end
end
```

I don't quite understand why ActionMailer's default_url_options are used here. These url options are supposed to be used in the emails only, not as a global option.
Am I missing something?

Here's my configuration:
* rails 4.2.3
* activeadmin master (6364302c2010f1f59f8ebbc917400ef8d2e7cbcc)

Here is an example project illustrating the issue:
```
git clone https://github.com/lakim/aa_url_options_issue
cd aa_url_options_issue
bundle
rake db:migrate
rake db:seed
rails s
open http://localhost:3000
# admin@example.com / password
```

Thanks

**Comment by timoschilling** [comment]
I think @hasghari has made a miss take in #3823, I think he want to use `action_controller.default_url_options` and not `action_mailer.default_url_options`.

**Comment by lakim** [comment]
It should be `Rails.application.routes.default_url_options`.
I'm preparing a PR.
