### ISSUE TITLE
Index filter as: text with custom ransacker and format

### ISSUE THREAD

**Issue by kaelumania** [activeadmin/activeadmin#4100]
I have a filter as textarea where I can paste structured text like `id1,id2,id3` (possibly 100 ids). Afterwards I want to filter all entries with these ids - this part works absolutely fine. But after the filtering, the textarea has the content `["id1,id2"]` which is not what I want. When I use `as: :string` for the filter, everything looks good. But a simple textfield is too small for my purpose.

``` ruby
Product.ransacker :retailer_product_id, formatter: proc {|ids| ids.split(',') } do |parent|
  parent.table[:retailer_product_id]
end

filter :retailer_product_id_in, as: :text
```

**Comment by timoschilling** [comment]
You need to copy this file and build it with a textarea https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/filters/string_input.rb.

PR's are welcome

**Comment by kaelumania** [comment]
If you might give me a little more information, I could be able to create a PR, e.g. where does the builder come from, which methods does it provide? Ideally I want to be able to define a formatter of the input, e.g. if the User pastes text like `id1, id2    , id3 \\n id4' I want it to normalize to `id1,id2,id3,id4`. I can achieve this partially with my custom ransacker for the query part, but for the render part, value would remain the same.

**Comment by kaelumania** [comment]
The problem here is, that activeadmin uses the ransacker search object to determine the values of the filter inputs in the sidebar. For `text_field` it works due to ActiveView https://github.com/rails/rails/blob/9f44aa08636dfbba9261f4350ec14684425c4b7b/actionview/lib/action_view/helpers/tag_helper.rb#L179, but for `text_area` there is no special Array handling. One the one hand activeadmin shouldn't use the ransacker object (which returns an array instead of the provided value). On the other hand ActiveView might be inconsistent in their escape handling.

**Comment by Fivell** [comment]
@kaelumania , ransackers with type formatters can be  not handled at the moment, 

Your case is resolved using ransackable scopes
Ransackable scopes do not modify types , so it will be always string. 


Example
```ruby
  scope :order_id_in, -> (str) { where("orders.id IN (?)", str.split(',')) }
   def self.ransackable_scopes(auth_object = nil)
      [:order_id_in]
  end

```


And then
```ruby
  filter :order_id_in, as: :text
```

**Comment by jayshepherd** [comment]
I am also working on way for users to paste in a list to be parsed via a ransacker, but it would be good to preserve the original string so that the filter form could easily be adjusted and resubmitted.

Before form submitted:
![books freetextbooks 2017-02-14 21-24-33](https://cloud.githubusercontent.com/assets/4238/22959447/10fdc568-f2fc-11e6-8f4a-7519d4e5796b.png)

After form submitted:
![books freetextbooks 2017-02-14 21-25-30](https://cloud.githubusercontent.com/assets/4238/22959457/2b58016c-f2fc-11e6-8cad-63667bb1ba74.png)

**Comment by purplejacket** [comment]
@jayshepherd Did you ever resolve the problem of the ISBN list looking wrong after the form is submitted?
