### ISSUE TITLE
rails g active_admin:install hangs indefinitely and seems to do nothing

### ISSUE THREAD

**Issue by Diosan** [activeadmin/activeadmin#4102]
I am attempting to run active_admin:install generate ... but nothing happens it simply hangs at the command prompt for hours until I interrupt the process.

I am on ubuntu server 12.04
Rails 4.2.4
ruby 2.2.2p95

and I am using RVM ... 

Any help with this would be greatly appreciated.

**Comment by timoschilling** [comment]
Does `rails g model Foo` or `rails g devise:install` works? Have tried more then one time? Have you tried to do `spring stop` bevor? Try it in a fresh shell.

**Comment by scarver2** [comment]
@Diosan Try `bundle exec rails g active_admin:install`

**Comment by Diosan** [comment]
@timoschilling  Doing 'spring stop' seems to have worked ... I'll just close this for now Thank you for your help @scarver2

**Comment by k00ka** [comment]
I had the same issue. There is a call to #gets on line 96 of lib/spring/client/run.rb. This appears to be where the install gets "hung up" (waiting for input).

**Comment by stoplion** [comment]
same issue `spring stop` worked

**Comment by FreeApophis** [comment]
Same Issue, same solution. There is a problem here.

**Comment by SampsonCrowley** [comment]
definitely still an issue, don't know why this is closed

**Comment by tetsuo692** [comment]
`spring stop` doesn't work for me.

` generate  active_admin:assets` for minutes.

**Comment by ar4420** [comment]
@gsum, what version of active admin are you using? I'm still facing the same issue even after stopping spring, and using ` bundle exec rails g active_admin:install `.

Tried starting in a fresh shell as well.  Everything seems to hang on the `generate  active_admin:assets` step.

**Comment by Loschcode** [comment]
My rails app is an API but I re-activated what's needed from ActiveAdmin to make it work. When I used the command it doesn't work and hangs like everyone else in this issue.

```
➜  api git:(master) ✗ spring stop
Spring stopped.
➜  api git:(master) ✗ rails g active_admin:install --skip-users
```

**Comment by nicolassrod** [comment]
`$ bundle exec spring stop`
