### ISSUE TITLE
Include parent resource in index title

### ISSUE THREAD

**Issue by samstickland** [activeadmin/activeadmin#4103]
Hi,

I'm trying to work out how to display an attribute from a parent resource (via belongs_to) in the index page and I'm pretty stuck.

I've tried this:

```
ActiveAdmin.register Child do
  belongs_to :parent

  index title: "Children in #{config.belongs_to_config.target.name}" do
```

But it doesn't find target, raising TargetNotFound on line 23 in https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/active_admin/resource/belongs_to.rb

And I think even if that did work it would only return the class name of Parent and not the actual resource.

Can anyone help?

**Comment by Fivell** [comment]
@samstickland , did you try to use proc object for title option ?

**Comment by Fivell** [comment]
@samstickland , please check this conversation,  feel free to reopen if this doesn't work for you.

**Comment by Fivell** [comment]
@samstickland , just leave a comment and this will be reopened
