### ISSUE TITLE
Minor bug in belongs_to

### ISSUE THREAD

**Issue by samstickland** [activeadmin/activeadmin#4107]
Hi,

I found a minor bug with belongs_to. In my class I had:

```
ActiveAdmin.register JobSubcategory do
  belongs_to :job_category
end
```

I have a ActiveRecord class call JobCategory, but there's also this object activeadmin resource

```
ActiveAdmin.register JobCategory do
end
```

For some reason the parent class in inherited resources ended up being Admin::JobCategory and not JobCategory, giving this error message:

```
undefined method `find' for Admin::JobCategory:Module

Extracted source (around line #90):
           
88          end
89
90          parent = parent.send(parent_config[:finder], params[parent_config[:param]])
91        end
92
93        instance_variable_set("@#{parent_config[:instance_name]}", parent)
```

This hasn't happened to me before, it's still working with other object hierarchies. The fix is to manually specify ActiveRecord class as the parent class 

    belongs_to :job_category, parent_class: JobCategory

**Comment by syndbg** [comment]
*belongs_to* in an ActiveAdmin class looks quite wrong.

Remove the belongs to from the ActiveAdmin class and try again.


P.S you have a belongs_to in the ActiveRecord class, right?

**Comment by sps196** [comment]
belongs_to in ActiveAdmin has a slightly different meaning - it's documented here: https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#belongs-to
