### ISSUE TITLE
CSV export problem with 1.0.0 version

### ISSUE THREAD

**Issue by Ruff9** [activeadmin/activeadmin#4108]
Using the last version of your gem, I'm facing what seems to be an old behaviour. 

My CSV export option take only the first page of data, like in this old issue:  [#2449](https://github.com/activeadmin/activeadmin/issues/2449).

Is there something I need to know about this ?

**Comment by zorab47** [comment]
Which exact git revision are using? Are you using any specific ActiveAdmin configuration overrides?

**Comment by seanlinsley** [comment]
Closing due to a lack of activity.
