### ISSUE TITLE
menu label does not work

### ISSUE THREAD

**Issue by ccfiel** [activeadmin/activeadmin#4109]
I want to change the menu label and priority. I tried this config priority works but label does not work. Im using  Active Admin 1.0.0.pre1. Any ideas?

ActiveAdmin.register AdminUser do
  menu label: 'test this'
  menu priority: 2
end

**Comment by timoschilling** [comment]
```ruby
ActiveAdmin.register AdminUser do
  menu label: 'test this', priority: 2
end
```

**Comment by ccfiel** [comment]
@timoschilling thanks!
