### ISSUE TITLE
Custom filter breaks db:create/migrate

### ISSUE THREAD

**Issue by seankovacs** [activeadmin/activeadmin#4117]
I added a custom filter override for the broken date filter currently in place (non-inclusive end date filters). In doing so, it apparently prevents a db:create from going through successfully. 
The filter is this (in the active_admin.rb):
```Ruby
module ActiveAdmin
  class ResourceDSL
    def filter(*args)
      field = args[0]
      klass = @config.resource_class_name.constantize
      type  = klass.columns.select{|c| c.name == field.to_s}.first.try(:type)

      if type == :datetime
        controller do
          before_filter :only => :index do
            if !params["q"].blank? && !params["q"]["#{field}_lteq"].blank?
              params["q"]["#{field}_lteq"] += " 23:59:59.999999"
            end
          end
        end
      end

      super
    end
  end
end
```

When doing a fresh db:drop, db:create, it fails when it hits the first file under app\admin\*.rb which happens to be a model page with a regular "filter :field". I've read  about wrapping filters in procs, but that is for custom filtered objects (nor do I wish to do it for ALL filters on every page)?

The short term solution is comment out the code above, but it is not ideal.

**Comment by timoschilling** [comment]
In your case currently the only solution is to check that the current process is a `rails server` and not a `rake`. `$PROGRAM_NAME` should be help full, but keep in mind that the value can be different on local and server setup.

**Comment by seankovacs** [comment]
Would you suggest using $rails_rake_task or  something like this File.basename($0) == 'rake' for future compatibility?

**Comment by timoschilling** [comment]
`$PROGRAM_NAME` is a variable assigned by ruby and should be equal to `$0`. I think you should test what `$0` is in the different cases (rails server on the server, rails server local, rake on server, rake local). I think a `$PROGRAM_NAME.include?("rake")` should work.

**Comment by seankovacs** [comment]
Thank you @timoschilling , that solved the issue while maintaining functionality.
