### ISSUE TITLE
table_for is_attribute? triggers a deprecation warning in Rails 4.2

### ISSUE THREAD

**Issue by rhymes** [activeadmin/activeadmin#4119]
In the index page of an active admin controller I noticed I have a few deprecation warnings because this method gets called https://github.com/activeadmin/activeadmin/blob/9c46b14ea0d9b3aaaa3d7520555c9959d06ce7f3/lib/active_admin/views/components/table_for.rb#L121

According to Rails 4.2 it's #column_for_attribute behavior will be changed in Rails 5: https://github.com/rails/rails/blob/4-2-stable/activerecord/lib/active_record/attribute_methods.rb#L206

Just wanted to bring it to your attention.

**Comment by timoschilling** [comment]
thanks, but double of #3838
