### ISSUE TITLE
Parent Menu not handling internationalization correctly.

### ISSUE THREAD

**Issue by mwlang** [activeadmin/activeadmin#4124]
The parent Menu items that are passed to I18n.translate do not switch languages when locale is changed by the user:

``` ruby
ActiveAdmin.register ShippingCharge do
  menu parent: I18n.translate("active_admin.menu.price_and_delivery")
end
```

Whatever the locale happens to be the first time the menu is constructed is what the menu remains at even when switching locales.  Other top-level menus and sub-items of the parent menu _do_ translate correctly, just not the parent menu.  This issue exists even when running in :production mode, so it's not a Rails reload! issue.

![menu_example](https://cloud.githubusercontent.com/assets/18387/9944442/357bb226-5d3c-11e5-8cb8-8a16438da30b.png)

If a source file containing the parent menu directive is touched, _then_ menu updates correctly to the current locale.

It's also not the locale switching code because if I place a raise error line in the file, it requests the correct locale:

``` ruby
ActiveAdmin.register ShippingCharge do
  raise I18n.translate("active_admin.menu.price_and_delivery").inspect
  menu parent: I18n.translate("active_admin.menu.price_and_delivery")
end
```

``` log
RuntimeError ("Price & Delivery"):
  app/admin/shipping_setting.rb:2:in `block in <top (required)>'
  app/admin/shipping_setting.rb:1:in `<top (required)>'
  config/routes.rb:5:in `block in <top (required)>'
  config/routes.rb:1:in `<top (required)>'
```

**Comment by sandrew** [comment]
The reason is `I18n.translate` here is evaluated once page is loaded, not each time page loads.
The problem is that `parent` param does not take proc as `label` does.
You can use following workaround:

config/initializers/active_admin.rb
```ruby
  config.namespace :admin do |admin|
    admin.build_menu do |menu|
      menu.add id: 'price_and_delivery', label: proc{ I18n.translate("active_admin.menu.price_and_delivery") }
    end
  end
```

AA resource:
```ruby
ActiveAdmin.register ShippingCharge do
  menu parent: 'price_and_delivery'
end
```

**Comment by seanlinsley** [comment]
@sandrew how would you suggest we change it?

**Comment by sandrew** [comment]
@seanlinsley I think the `parent` option should allow to pass some kind of Menu instance or a `proc` returning a string (preferable), because it is expected that such an option behaves in similar way with the `label` option.

I know that the `parent` param is supposed to work another way, but customizing submenus' parents is so common, that it would better be allowed not only in the initializer.

**Comment by rod-stuchi** [comment]
I achieved a solution with an ugly hack, but maybe can help for a while.

**app/admin/layout_hacks.rb**

```ruby

# howto: http://stackoverflow.com/questions/4470108/when-monkey-patching-a-method-can-you-call-the-overridden-method-from-the-new-i
# howto: https://github.com/activeadmin/activeadmin/issues/340
module ActiveAdmin::Views::Pages::BaseExtension
  require "json"
  def add_classes_to_body
    super
    locales = {
      "parentMenus" => [
        { "name" => :menu_general, "value" => I18n.t(:menu_general) },
        { "name" => :menu_users, "value" => I18n.t(:menu_users) },
      ]
    }
    within @body do
      div id: "metadata", style: "display: none" do
        """
          <input id='locales' type='text' value='#{locales.to_json}' />
        """.html_safe
      end
    end
  end
end
class ActiveAdmin::Views::Pages::Base
  # mixes in the module directly below the class
  prepend ActiveAdmin::Views::Pages::BaseExtension
end
```

**app/assets/javascripts/admin/base.js**

```javascript
  var menus = JSON.parse($("#metadata>#locales").val() || "{}")
  if (menus.hasOwnProperty("parentMenus")) {
    menus.parentMenus.forEach(function(menu) { // forEach IE9+
      $("#" + menu.name + " > a").text(menu.value)
    });
  }
```
