### ISSUE TITLE
default password is not working after install - Unauthorized Access

### ISSUE THREAD

**Issue by Abdul24** [activeadmin/activeadmin#4127]
I have installed active admin on three different apps today and the default login information is not working.  I keep getting Unauthorized error message. The error is the same in my local development in terminal, as we as Nitrous.io IDE. I check stackoverflow for a solution, however, what they we prescribing I have tried already. I.E. Changing the password in the console for Admin user.  Please advise if  I should be using using different install instructions. Thanks  

```
Started POST "/admin/login" for 50.17.182.190 at 2015-09-19 23:52:53 +0000
Cannot render console from 50.17.182.190! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
  ActiveRecord::SchemaMigration Load (0.1ms)  SELECT "schema_migrations".* FROM "schema_migrations"

Processing by ActiveAdmin::Devise::SessionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"nwr2HyEpObNw+u5KErgjXAw+HxgXWNd2Ph8sleNC2v82CH7QmLwq/XeQc80HyL/bx3HEb1RUwcoogzsdyV/utQ==", "admin_user"=>{"email"=>"admin@example.com
", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Login"}
  AdminUser Load (0.2ms)  SELECT  "admin_users".* FROM "admin_users" WHERE "admin_users"."email" = ?  ORDER BY "admin_users"."id" ASC LIMIT 1  [["email", "admin@example.com"]]
Completed 401 Unauthorized in 21ms

Processing by ActiveAdmin::Devise::SessionsController#new as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"nwr2HyEpObNw+u5KErgjXAw+HxgXWNd2Ph8sleNC2v82CH7QmLwq/XeQc80HyL/bx3HEb1RUwcoogzsdyV/utQ==", "admin_user"=>{"email"=>"admin@example.com
", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Login"}
 
 Rendered .bundle/bundler/gems/activeadmin-893b46c6530c/app/views/active_admin/devise/shared/_links.erb (12.7ms)
 
 Rendered .bundle/bundler/gems/activeadmin-893b46c6530c/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out (63.0ms)
Completed 200 OK in 586ms (Views: 481.7ms | ActiveRecord: 0.0ms)
```

**Comment by stevesizer** [comment]
I am also getting this error. Tried setting up active admin with a new project I am currently working on and the default username and password don't work.

**Comment by hobbes37** [comment]
Hi Abdul24 and stevesizer! I was able to track down your the issue. When installing after you run "rake db:migrate" you need to run "rake db:seed" before starting the rails server. Doing this will add the default admin account and you can log in with "admin@example.com" "password". I updated the installation documentation and submitted a pull request, hopefully we can get it updated before anyone else runs into this problem.

**Comment by josemota** [comment]
:+1: for @hobbes37's answer. Thank you!

**Comment by Abdul24** [comment]
hobbes37 -

Thanks for tracking down this issue and resolving this matter!

**Comment by seanlinsley** [comment]
The PR, #4144, has been merged :octocat:

**Comment by tarriqhamza** [comment]
thanks alot @hobbes37  for the the solution

**Comment by tarriqhamza** [comment]
thanks alot @hobbes37  for the the solution

**Comment by edohartono** [comment]
> Hi Abdul24 and stevesizer! I was able to track down your the issue. When installing after you run "rake db:migrate" you need to run "rake db:seed" before starting the rails server. Doing this will add the default admin account and you can log in with "[admin@example.com](mailto:admin@example.com)" "password". I updated the installation documentation and submitted a pull request, hopefully we can get it updated before anyone else runs into this problem.

Thanks a lot. Still work in 2019

**Comment by AbdullahButt2611** [comment]
When I am working with devise, even if I add the default credentails, it takes me to the login of the Devise. How can i override to provide different interfacse to both of these
