### ISSUE TITLE
Equivalent of `scoped_collection` for index table, but not scope counts?

### ISSUE THREAD

**Issue by ahmacleod** [activeadmin/activeadmin#4133]
I frequently need to customize the scope for the index table by including associations, joins for sorting, custom count queries, etc. I've been using `scoped_collection` for this, but then my scope counts are computed using this more expensive query. Is there a way to specialize the scope for just the index table without overriding the controller?

**Comment by timoschilling** [comment]
I think there is no way.

@seanlinsley ???

**Comment by timoschilling** [comment]
We have something for [`includes`](https://github.com/timoschilling/activeadmin/blob/master/docs/2-resource-customization.md#eager-loading)

**Comment by ahmacleod** [comment]
Ok thanks; I'll try monkey patching for now.

**Comment by Fivell** [comment]
@ahmacleod , don't know if it can help only an idea. There is an option to create methods for scopes.
For instance
```ruby
def scoped_collection
  MyModel.special_scope 
end
```
and than on model level

```ruby
class MyModel
   scope :special_scope, -> { joins(:sometable)) }   do 
      def count
         1000000
      end 
   end
end
```

**Comment by seanlinsley** [comment]
You can override `ActiveAdmin::Views::Scopes#get_scope_count`, or `ActiveAdmin::Helpers::Collection#collection_size`. You might be able to use `@collection_before_scope` as a hack to grab the collection before too many queries are added to the chain.

As far as speeding up scope counts in general, I created #4132 recently.

**Comment by Fivell** [comment]
@seanlinsley , 
ActiveAdmin uses more expensive count queries than for instance kaminari.
Maybe ActiveAdmin can just use implementation from kaminari https://github.com/amatsuda/kaminari/blob/3974ae5f39ce31bfca28d17eccd8daf3ca263aa3/lib/kaminari/models/active_record_relation_methods.rb#L12
(it should except also includes from relation )

in  ```collection_size(c = collection) ``` method ?

**Comment by Fivell** [comment]
@ahmacleod , is this still an issue?

**Comment by varyonic** [comment]
I think overriding `ActiveAdmin::Views::Scopes#get_scope_count` mentioned above is a good suggestion.
