### ISSUE TITLE
Redirect to another page when scope button is pressed, is it possible?

### ISSUE THREAD

**Issue by adisos** [activeadmin/activeadmin#4134]
I have STI models: User and successors Subscriber and Super User. In User resource I created scopes "Subscribers" and "Super User". But when user clicks this scopes I want redirect them to index page of Subscriber and Super User. Is it possible? I can do it with javascript, but if it's possible in scope of AA it'd be good.

**Comment by timoschilling** [comment]
That's a good point, I would like to see the same for filters or pagination.

**Comment by sandrew** [comment]
```ruby
controller do
  before_filter only: :index do
    redirect_to send("#{params[:scope]}_path") if %w(subscribers super_users).include?(params[:scope])
  end
end
```

**Comment by Fivell** [comment]
action item for collection also can be used
sort of
```ruby
 action_item(:users, only: :index) do
    dropdown_menu 'Users Menu' do
      item('Super User', admin_super_users_path)
      item('Subscribers', admin_subscribers_path)
      item('Admins', admin_users_path)
    end
  end
```

**Comment by Fivell** [comment]
@timoschilling , not sure what do you mean by 

>  I would like to see the same for filters or pagination.

**Comment by timoschilling** [comment]
@Fivell I think I have misread the post

**Comment by Fivell** [comment]
@timoschilling , I don't  think it is good idea to make such changes to scope, because they were designed for another  stuff. I'm more about closing this issue and recommend using ```action_item``` for this case

**Comment by timoschilling** [comment]
Yes, what he want is a hack, your and @sandrew provide some possible solutions, lets close this
