### ISSUE TITLE
active_admin.rb directives ignored

### ISSUE THREAD

**Issue by selfagency** [activeadmin/activeadmin#4138]
Not sure if this is a bug or human error in this case, but I'm working on a site using AA 0.6.0 and for some reason, the call to `/assets/active_admin.js` is being made twice, and modifications I make to `active_admin.rb` are being ignored.

Presently, this is in my `active_admin.rb`:

```ruby
#config.register_javascript 'active_admin.js'
config.register_stylesheet 'active_admin_custom.css.scss'
config.register_javascript '//cdnjs.cloudflare.com/ajax/libs/twemoji/1.3.2/twemoji.min.js'
```

What shows up on the frontend of my site's admin, however, is:

```html
<link href="/assets/active_admin.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/active_admin/print.css?body=1" media="print" rel="stylesheet" type="text/css" />
<link href="/assets/active_admin_custom.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/active_admin/editor.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/active_admin/editor/wysiwyg.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<script src="/assets/active_admin.js" type="text/javascript"></script>
<script src="/assets/active_admin.js" type="text/javascript"></script>
<script src="/assets/active_admin/editor.js" type="text/javascript"></script>
```

You'll notice, as I stated above, that `active_admin.js` is appearing twice (despite its only mention in the entire codebase of my project being that single commented-out instance) and that neither the .scss file nor external .js files are being loaded. Why would that be the case?

**Comment by timoschilling** [comment]
keep in mind that you need to restart your server to effect changes in the `active_admin.rb`

**Comment by selfagency** [comment]
that must've been it. thanks.
