### ISSUE TITLE
CSS file not being generated

### ISSUE THREAD

**Issue by dpmccabe** [activeadmin/activeadmin#414]
I'm using the most recent version of active_admin (master branch) and when I run the generator, it's making all of the assets, including JS, but not the CSS file.

Here's the output in a gist: https://gist.github.com/1172111

**Comment by andela-bbello** [comment]
rails generate active_admin:assets
The above command works for me. I was able to get the styling back on rails 4 and active admin. After which I get this error below
WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.

**Comment by timoschilling** [comment]
@andela-bbello that's fixed in the newer versions of ActiveAdmin, see #3832 for details
