### ISSUE TITLE
Filters don't respect configured `display_name_methods`

### ISSUE THREAD

**Issue by molgin** [activeadmin/activeadmin#4143]
When objects are referenced in filters, e.g. auto-generated association filters with dropdowns, their display names are apparently handled by Formtastic rather than ActiveAdmin itself, bypassing ActiveAdmin's `display_name_methods`.

The default `display_name_methods`: `[ :display_name, :full_name, :name, :username, :login, :title, :email, :to_s ]`

Formtastic's default `collection_label_methods`: `["to_label", "display_name", "full_name", "name", "title", "username", "login", "value", "to_s"]`

So if an object responds to `:to_label`, that will be displayed in filters rather than the output of any of ActiveAdmin's specified methods. Or if you've configured ActiveAdmin to prioritize a custom method, say `:admin_name`, that will never be used in a filter.

You can change the methods Formtastic uses in its configuration, but if you use Formtastic elsewhere in your app and want this behavior to be specific to ActiveAdmin, that's not an ideal solution.

In any case, this is confusing and worth noting somewhere.

**Comment by ypresto** [comment]
This would be better to be documented..!

**Comment by timoschilling** [comment]
write a PR to change the behavior or to improve the documentation

**Comment by ypresto** [comment]
wrote PR!
