### ISSUE TITLE
ActiveAdmin::BaseController inherits before actions from the ApplicationController

### ISSUE THREAD

**Issue by asok** [activeadmin/activeadmin#4147]
Hi,
I've setup my app to use activeadmin.
And from the rails console I see:
```
ActiveAdmin::BaseController._process_action_callbacks.map(&:filter)
=> [:verify_authenticity_token,
 :verify_same_origin_request,
 :authenticate_user!,
 :set_locale,
 :store_last_action_name,
 :store_return_to_location,
 :only_render_implemented_actions,
 :authenticate_active_admin_user,
 :set_current_tab]
```
There are 2 authentication callbacks. The one setup by ActiveAdmin - `authenticate_active_admin_user`, and one setup by me in the `ApplicationController` - `authenticate_user!`.
So when I'm not logged in and try to access `/admin` path in my app I'm redirected to the `new_user_session_path` instead of `new_admin_session_path` because of the actions precedence.

As a workaround I've monkey patched the `BaseController` to skip `authenticate_user!` method.

All in all it looks counter intuitive for me. Can't `BaseController` include `InheritedResources::DSL` instead  of inheriting from `InheritedResources::Base`. That way it wouldn't have the application's controller callbacks? Or if not, shouldn't this behavior be mentioned in the docs?

**Comment by chengguangnan** [comment]
I had a similar issue where my ApplicationController filter also filters the ActiveAdminControllers. How to make them irrelevant to each other?

**Comment by asok** [comment]
Well after figuring out the culprit I just monkey patched the controller in the initializer:
```rb
class ActiveAdmin::BaseController
  skip_before_action :authenticate_user!
end
```

**Comment by shishir127** [comment]
@asok Wouldn't a better approach be to change the `config.authentication_method` in the active admin config file? I don't think it's wise for `ActiveAdmin::BaseController` to not inherit from the `ApplicationController` because then we might not get the benefit of Rails's CSRF countermeasures.

**Comment by asok** [comment]
@shishir127 this is what I have in the initializer: `config.authentication_method = :authenticate_admin!`. And still I have the `authenticate_user!` before action because of the fact that `ActiveAdmin::BaseController` inherits from `ApplicationController`.
About the CSRF countermeasures active admin's controller might include `ActionController::RequestForgeryProtection` module.

**Comment by shishir127** [comment]
@asok In `ActiveAdmin::BaseController`, it looks like `authenticate_active_admin_user` calls the method assigned in the active admin config file
```
# Calls the authentication method as defined in ActiveAdmin.authentication_method
    def authenticate_active_admin_user
      send(active_admin_namespace.authentication_method) if active_admin_namespace.authentication_method
    end
```

**Comment by asok** [comment]
Yes but that's not the issue. The issue is that the base controller has 2 before actions as inspected in the console:
```rb
ActiveAdmin::BaseController._process_action_callbacks.map(&:filter)
=> [:verify_authenticity_token,
 :verify_same_origin_request,
 :authenticate_user!,
 :set_locale,
 :store_last_action_name,
 :store_return_to_location,
 :only_render_implemented_actions,
 :authenticate_active_admin_user,
 :set_current_tab]
```
`:authenticate_active_admin_user` which is what I want, and `:authenticate_user!` which is not what I want. The reason because it's there is the fact that I have `before_action :authenticate_user!` code in my `ApplicationController`.
The way I see it there are 2 things that could be done:
* make the base controller include the `InheritedResources::Dsl` module instead of inheriting from `InheritedResources::Base` (and indirectly from `ApplicationController`). The drawback is that the `Admin`'s controllers will not have methods defined by user in the `ApplicationController`.
* leave it as it is, but make some explicit statement in the docs that the generated controllers in the `Admin` namespace will inherit from `ApplicationController`. So the users will remove `:authenticate_user!` from `ApplicationController` and put it in every controllers in their codebase.

**Comment by seanlinsley** [comment]
We're going to have to drop Inherited Resources as a dependency pretty soon anyway (#3604), so I'm opting to just have it noted in the documentation.
