### ISSUE TITLE
Custom filter and search for a table's json attribute

### ISSUE THREAD

**Issue by rafiaqutab** [activeadmin/activeadmin#4152]
I am trying to accomplish the following filtering mechanism and was not sure what would be the best approach. I have a model with an attribute that is a json type; for example an instance would return, 
```ruby
myobject.some_json_attr => { my_lookup_key: { "key1" => "value1", "key2" => "value2", "key3" => "value3" }
```
I would like the filter to be associated to the ```some_json_attr``` which can easily be accomplished using ransacker:
```ruby
Arel::Nodes::InfixOperation.new('->', parent.table[:some_json_attr], Arel::Nodes.build_quoted('some_json_attr'))
```
however, I want the filter to behave in a manner where the label drop down (that contains the predicates greater_than, less_than etc) to show key1, key2 and key3 and the text field be a numeric input type. I want the search to behave in such manner that I can take the predicate value for e.g if the user selects ```key2``` and look up all the rows in the data table associated to ```MyObject``` that has column ```some_json_attr != null``` and the value ```some_json_attr['key2']``` to be greater than (always) the numeric value the user has entered in the input field. Is there a way to pass the predicate drop down selected value (in this e.g it will be ```key2```) to ransacker and then customize the search in the ```formatter```. Please help! :sob: @seanlinsley

**Comment by rafiaqutab** [comment]
The two solutions I had in mind were:

1. (More work) create a custom filter for this type of lookup
2. (Not sure how to do this) pass ransacker arguments that will be the selected value from the predicate drop down i.e ```key2``` considering ``` ransacker formatter: ``` already takes a block with the input value (the user entered) as the argument.

**Comment by seanlinsley** [comment]
As I learned through a bit of research just now, you can do this to search against a JSON key:
```ruby
filter :json_key, as: :numeric

ransacker :json_key do |parent|
  Arel.sql "(#{parent.table.name}.json_column->>'json_key')::int"
end
```

I'm too lazy to figure out how to do type coercion in straight Arel ¯\\_(ツ)_/¯ 

To have a select field to choose different JSON keys, you're going to have to build a custom filter. Unless you want to take that on, it'd be simpler to create a ransacker and a filter for each JSON key.
