### ISSUE TITLE
ActiveAdmin converts the param "1" to true for a custom filter

### ISSUE THREAD

**Issue by jcohenho** [activeadmin/activeadmin#4158]
Parameters: {"utf8"=>"✓", "q"=>{"interests_search"=>"1"}, "commit"=>"Filter", "order"=>"_desc"}

   (10.5ms)  SELECT COUNT(*) FROM "users" WHERE (interests @> '{true}')

Why does this happen? I need the string/integer value, not a boolean evaluation!

**Comment by Fivell** [comment]
@jcohenho , try to change ransack version, I think this is ransack bug

**Comment by seanlinsley** [comment]
https://github.com/activerecord-hackery/ransack/issues/593
