### ISSUE TITLE
Using decorator to provide setter and getter

### ISSUE THREAD

**Issue by bolshakov** [activeadmin/activeadmin#4160]
Given I have the following models

```ruby
class User < ActiveRecord::Base
  has_one :profile
end

class Profile < ActiveRecord::Base
  belongs_to :user
end
```

I want to provide ability to assign profile through the User's edit form. This is a business requirements and direction of the relation could not be changed.

So my user's form looks like this:

```ruby
ActiveAdmin.register User do
  decorate_with UserDecorator
  permit_params :profile_id

  show do
    attributes_table :profile
  end

  form decorate: true do |f|
    f.inputs do
      f.input :profile, as: :select
    end
    f.actions
  end
```

To achieve that behavior I can add `#profile_id` and `#profile_id=` methods to `User`:

```ruby
  def profile_id
    return unless profile

    profile.id
  end

  def profile_id=(value)
    model.profile = Profile.find(value)
    value
  end
```

But I don't want to add admin-specific code to my models, so it would be nice if I could add this code to decorators. But currently it is impossible since `ActiveAdmin::ResourceController::DataAccess#build_resource` method applies decorator after populating record with attributes. The proper workflow should be:

```ruby
      def build_new_resource
-        scoped_collection.send method_for_build, *resource_params
+        scoped_collection.send method_for_build
      end

      def build_resource
        get_resource_ivar || begin
          resource = build_new_resource
+        resource = apply_decorator resource           
+          resource.assign_attributes(*resource_params)
          run_build_callbacks resource
          authorize_resource! resource

-          resource = apply_decorator resource           
          set_resource_ivar resource
        end
      end
```

What do you think? Is it appropriate change?

**Comment by rchezrutt88** [comment]
Four years later and today I find myself wishing for this very feature.

**Comment by bolshakov** [comment]
@rchezrutt88 you can use Reform with ActiveAdmin https://github.com/bolshakov/activeadmin-reform or use your own decorator. All the required extension points were added here https://github.com/activeadmin/activeadmin/pull/4166
