### ISSUE TITLE
Add ability to set a custom name for CSV file

### ISSUE THREAD

**Issue by rakvium** [activeadmin/activeadmin#4162]
I haven't find an option to customize a name in the normal way, so I _incidentally did some code like this_:

```
module ActiveAdmin
  class ResourceController < BaseController
    module Streaming
      def csv_filename
        return 'User Details.csv' if resource_collection_name == :users
        super
      end
    end
  end
end
```

Could you please provide such an option if you have some time?
_P.S.: I will also be happy if you'll provide me with a more peaceful way to rename a CSV file_

**Comment by drn** [comment]
I just ran into this and I was able to override the `csv_filename` method in the specific admin page.
```ruby
ActiveAdmin.register User do
  controller do
    def csv_filename
      'User Details.csv'
    end
  end
end
```
 I realize this issue is a year old, so this might not have been possible at the time this issue was opened.

**Comment by varyonic** [comment]
Document this in 4-csv-format.md
