### ISSUE TITLE
generates duplicate routes.

### ISSUE THREAD

**Issue by amoludage** [activeadmin/activeadmin#4167]
If active admin install and generate config files using following command
   rails g active_admin:install --skip-users
And 
after that if user re-enter the above command (i.e  rails g active_admin:install --skip-users) then it generates config files but in that configurations file it rewrite the routes for activeadmin in config/routes file.

Example:
Rails.application.routes.draw do
   ActiveAdmin.routes(self)
   ActiveAdmin.routes(self)
end

It should not be rewrite the routes.

Am I missing something?
Thanks.

**Comment by timoschilling** [comment]
It's no the task of the installer to prevent user faults!

**Comment by amoludage** [comment]
@timoschilling  I think you should check for the already installed active-admin, and if its already installed then you should not re-write route into config/routes.rb file.
