### ISSUE TITLE
Is there a way to keep password in the form if validation failed

### ISSUE THREAD

**Issue by Bill-SnowWolf** [activeadmin/activeadmin#4169]
Right now, for `password` and `password_confirmation` field, if form validation failed, it got cleared automatically. Is there a way to keep it in the form.

(I know this is not normal, but this is a weird requests that client asked for)

**Comment by timoschilling** [comment]
https://github.com/activeadmin/activeadmin/blob/master/app/views/active_admin/devise/registrations/new.html.erb#L11
copy this file with the same path into your app and change the following thing:
```erb
f.input :password, label: t('active_admin.devise.password.title'), input_html: { value: params[:password] }
# or
f.input :password, label: t('active_admin.devise.password.title'), input_html: { value: params[:user][:password] }
# If that not work you need to check the param name / scope in the console output.
```
same for confirmation.
