### ISSUE TITLE
Results from filter are not unique

### ISSUE THREAD

**Issue by asecondwill** [activeadmin/activeadmin#4171]
I have a resource in activeadmin for users.  it has a filter set:

````  filter :industries ````

and in user model, the relationship is:

```` has_many :industries, -> {uniq}, :through => :resume ````

however if i select two industries in the filter that both match the same user, the user shows up twice. 

is this an active admin issue? something I've done wrong? or a ransack issue?

**Comment by timoschilling** [comment]
`has_many :industries, -> {uniq}, :through => :resume` means that a user can have a industry only once.
I you make a lookup for 2 industries users, a doubled result entry is right!
What you realy get is a list like this
```
id | username | industry
------------------------
 1 | foo      | I1
 1 | foo      | I2
 2 | bar      | I1
```
This is a logic issue from you not a issue of active admin or ransack.

**Comment by asecondwill** [comment]
That isn't right from the perspective of the person using the admin interface.  

Looking at a list of users, and filtering to say only users from these 2 industries should of not show duplicates.

**Comment by timoschilling** [comment]
Then you need to build the query in a different way, ActiveAdmin shows only the result of the runsacker

**Comment by asecondwill** [comment]
This is how ransack readme says to do it, and I have done successfully on a index page outside of AA.  

````
@q = users.ransack(params[:q])
@users = @q.result(distinct: true).page(params[:page]).per(20)
````
so, pass ```` distinct: true ````

I would think that could be a default? Or, is that something that can be overridden?

**Comment by seanlinsley** [comment]
Using `distinct: true` as the default could cause request slowdowns by asking the database to do more work, so it might not make sense as the default.

As a quick solution, you could override [`apply_filtering`](https://github.com/activeadmin/activeadmin/blob/c1c6ca6ff56ce47f560b3e4bc197f0748afb3b26/lib/active_admin/resource_controller/data_access.rb#L224) so it sets `distinct: true`

**Comment by asecondwill** [comment]
perfect, thank you.  Ill leave this here for anybody else looking -e.g. me in a few weeks : ) 

````
controller do
  def apply_filtering(chain)
     @search = chain.ransack clean_search_params params[:q]
     @search.result(distinct: true)
   end
end
````

**Comment by matthewrudy** [comment]
I think there should be a good solution for this.

Eg. ransack should offer a `assocation_name_field_any_contains` that doesn't do a LEFT OUTER JOIN.

**Comment by maxpark-jd** [comment]
Thank you @asecondwill, very useful.

**Comment by ninjarabbi** [comment]
this no longer works in pre5
`
NameError - undefined local variable or method `clean_search_params' for #<Admin::UsersController:0x007f96424e7c00>:`

**Comment by Fivell** [comment]
@ninjarabbi , try
```
controller do
  def apply_filtering(chain)
      super.distinct
  end
end

```

**Comment by MikeRogers0** [comment]
Another thing you can do is:

```
has_many :industries, -> { distinct }, :through => :resume
```

**Comment by SirRawlins** [comment]
@Fivell's approach worked really well, although expanding to multiple resources might lead to duplicate code.

I agree that distinct shouldn't be the default behaviour, but perhaps a way to declare it through the DSL might be nice. `filter :distinct` or something similar? Would be less verbose than overwriting apply_filtering all the time.
