### ISSUE TITLE
Is there a way to add a second CSV download link?

### ISSUE THREAD

**Issue by rhnorment** [activeadmin/activeadmin#4172]
I can customize the columns for the default CSV link, but I want to add a second CSV link that downloads a separate group of columns and call the link 'Download for Email.'

Thanks in advance.

**Comment by varunlalan** [comment]
@rhnorment You can do following in `initializer`:

```
ActiveAdmin.setup do |config|
  ...

  config.namespace :admin do |admin|
    admin.download_links = [:csv, :xml, :json, :csv_email]
  end

  ...
end

module ActiveAdmin::ViewHelpers::DownloadFormatLinksHelper
  def build_download_format_links(formats = self.class.formats)
    params = request.query_parameters.except :format, :commit
    
    div class: "download_links" do
      span I18n.t('active_admin.download')
      formats.each do |format|
        if format == :csv_email
          params.merge!(resource_class: controller.controller_name)
          a("Download for Email", href: some_path(params: params))
        else
          a format.upcase, href: url_for(params: params, format: format)
        end
      end
    end
  end
end

```

Let me know if this helps.

**Comment by rhnorment** [comment]
Thank you @varunlalan!   I will give this a try.  

Few more questions:  (1)  Does the Module code go in the same initializer file?  (2)  Can you explain what the module code is doing?  Are we creating a new view helper or modifying a default one?

Thanks!!

**Comment by varunlalan** [comment]
@rhnorment 

1. Yes the `module` should go in same initializer file outside `ActiveAdmin.setup` block.
2. We are modifying the existing module that is responsible to add those links in ActiveAdmin page.

**Comment by seanlinsley** [comment]
Sounds like that's a working solution. If someone would like to create a PR to introduce a cleaner way to add custom download links we'd be willing to review it, but for now I'm going to close this ticket.

**Comment by rhnorment** [comment]
Thanks everyone!!

**Comment by rhnorment** [comment]
I have another question as I am having trouble with the finishing pieces here.  I would like the :csv_for_email download to include the results from a query and only contain the names and email fields.  I guess I'm not sure how to make that happen.

Can I customize :csv_for_email using the DSL just as I customize the standard CSV?

**Comment by varunlalan** [comment]
@rhnorment Yes. You need to define a new collection action which would export names and email fields.

**Comment by AlexVentura** [comment]
@varunlalan I'm also wondering how to download specific records coming from a custom query or even from a scope using the default `csv` link. And it doesn't matter what records are shown in the index page I just want the customer query records to be exported in the csv file.

Can you please share an example?

**Comment by varunlalan** [comment]
@AlexVentura Where is custom query or scope applied? I won't recommend hacking into existing features like default `csv` link. 

You question is probably out of context with the original question / issue.

**Comment by AlexVentura** [comment]
@varunlalan Yes I know it my be a little bit out of context. But I decided to post my question here because at the end @rhnorment has finished exactly with the same question I'm stuck at the moment.
My scope is in the main `User` model and also it exist in `admin/user` and all I want is to change the records the actual `csv` link export by default with the ones resulted in that scope. But I don't have any idea where to start and searching in google I can't find something really helpful.
Do you have any idea o suggestion, maybe a post to follow?
I'll really appreciate any kind of help!

**Comment by varunlalan** [comment]
@AlexVentura 

For exporting records with default `csv` link, you might need to override the default `index` action inside active admin, something like - 

In `config/initializers/active_admin.rb`

```
class ActiveAdmin::ResourceController
  module Streaming
    class DummyController
      def initialize(collection:)
        @collection = collection
      end
      attr_reader :collection

      def find_collection(*)
        collection
      end

      def apply_decorator(resource)
        resource
      end

      def view_context
        @view_context ||= ViewContext.new
      end

      class ViewContext
        include MethodOrProcHelper
      end
    end

    def export_csv(collection)
      controller = DummyController.new(collection: collection)
      headers['Content-Disposition'] = %{attachment; filename="#{csv_filename}"}
      stream_resource &active_admin_config.csv_builder.method(:build).to_proc.curry[controller]
    end
  end
end
```

In `admin/users.rb`

```
controller do
  def index
    index! do |format|
      @users = User.custom_query # or scope

      format.html
      format.csv   { export_csv @users }
      format.json  { render json: @users }
      format.xml   { render xml: @users }
    end
  end
end
```

This might or might not work depending on rails and active admin version you are using.

**Comment by AlexVentura** [comment]
@varunlalan Thank you, I appreciate! I will try to implement this and see if it works with Rails 4.2.3 and Ruby 2.2.6. I will let you know how it goes!

**Comment by unionups** [comment]
I'm use another way for this -  define custom format by patching activeadmin

in `config/initializers/active_admin.rb`
``` ruby
ActiveAdmin.setup do |config|
...
  config.namespace :admin do |admin|
      admin.download_links = [:csv, :custom_csv, :xml, :json]
  end
...
end

module ActiveAdmin
  module ResourceControllerStreamingPrepend
    def index
      super do |format|
        format.custom_csv { stream_custom_csv }
        yield(format) if block_given?
      end
    end
  end

  module ResourceControllerStreamingPatch
    protected
    def stream_custom_csv
      headers['Content-Type'] = 'text/csv; charset=utf-8' 
      headers['Content-Disposition'] = %{attachment; filename="#{csv_filename}"}
      stream_resource &active_admin_config.custom_csv_builder.method(:build).to_proc.curry[self]
    end    
  end

  module ResourceDSLPatch
      private
      def custom_csv(options = {}, &block)
        options[:resource] = config
        config.custom_csv_builder = CSVBuilder.new(options, &block)
      end
  end

  module ResourcePatch
    extend ActiveSupport::Concern
    included do
      attr_accessor :custom_csv_builder
    end
  end
end

ActiveAdmin::Resource.send :include, ActiveAdmin::ResourcePatch
ActiveAdmin::ResourceDSL.send :include, ActiveAdmin::ResourceDSLPatch
ActiveAdmin::ResourceController.send :include, ActiveAdmin::ResourceControllerStreamingPatch
ActiveAdmin::ResourceController.send :prepend, ActiveAdmin::ResourceControllerStreamingPrepend
```
in `config/initializers/mime_types.rb`
``` ruby
Mime::Type.register "text/csv", :custom_csv
```

in `app/admin/your_models.rb`
``` ruby
ActiveAdmin.register  YourModel do
...
csv do
    column :bla_bla
    ....
end
custom_csv do
    column :bla_bla_bla
    ...
end
```
This add custom_csv  link in download section and there way for how to customize your csv with the standart activeadmin DSL.
Good luck)))
