### ISSUE TITLE
Creating Pundit Policy for Comments

### ISSUE THREAD

**Issue by kalkin** [activeadmin/activeadmin#4174]
Hello,

I am using Pundit for authorization with ActiveAdmin (current master HEAD). I can not figure out or find any documentation how to authorize the usage of comments.

**Comment by seanlinsley** [comment]
I haven't used Pundit myself, but here's our documentation: [[link]](https://github.com/activeadmin/activeadmin/blob/c1c6ca6ff56ce47f560b3e4bc197f0748afb3b26/docs/13-authorization-adapter.md#using-the-pundit-adapter)

AA comments are a normal model. You should just be able to create a policy for `ActiveAdmin::Comment`

**Comment by kalkin** [comment]
@seanlinsley Thank you for your answer i finally figured out how to do it.

You have to create a `CommentPolicy` by extending `ActiveAdmin::CommentPolicy` like this:

```ruby
class CommentPolicy < ActiveAdmin::CommentPolicy
⋮
end

```
