### ISSUE TITLE
Troubleshooting strong parameters with ActsAsTaggableOn and Globalize

### ISSUE THREAD

**Issue by romiras** [activeadmin/activeadmin#4181]
I'm trying to figure out how to configure `ActsAsTaggableOn::Tag::Translation` to allow updates of model.

For correct usage of strong parameters I followed manual [Setting up Strong Parameters](https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#setting-up-strong-parameters) which states

```ruby
ActiveAdmin.register Post do
  permit_params :title, :content, :publisher_id
end
```

Tag names should be translatable.
I've tried different ways for `ActsAsTaggableOn::Tag::Translation` and all of them doesn't allow to update parameters.

This:
```ruby
ActiveAdmin.register ActsAsTaggableOn::Tag::Translation, :as => "TagTranslation" do
  permit_params :name, :tag_id, :locale
end
```

And this:
```ruby
ActiveAdmin.register ActsAsTaggableOn::Tag::Translation, :as => "TagTranslation" do
  permit_params acts_as_taggable_on_tag_translation: [:name, :tag_id, :locale]
end
```

And even this:
```ruby
ActiveAdmin.register ActsAsTaggableOn::Tag::Translation, :as => "TagTranslation" do
  controller do
    def permit_params
      params.permit! # allow all parameters
#      params.permit acts_as_taggable_on_tag_translation: [:name, :tag_id, :locale]
#      params.require(:acts_as_taggable_on_tag_translation).permit(:name, :tag_id, :locale)
    end
  end
end
```

I get message
WARNING: Can't mass-assign protected attributes for ActsAsTaggableOn::Tag::Translation: tag_id, locale, name

What I'm doing wrong?

**Comment by timoschilling** [comment]
Whats your problem? You write what you have tried, but you don't write what doesn't work.

**Comment by romiras** [comment]
I get message
WARNING: Can't mass-assign protected attributes for ActsAsTaggableOn::Tag::Translation: tag_id, locale, name

**Comment by timoschilling** [comment]
> Can't mass-assign protected attributes for ActsAsTaggableOn::Tag::Translation

It looks like `ActsAsTaggableOn::Tag::Translation` still uses the old `attr_accessible` system. With strong parameters, you will get a `ActiveModel::ForbiddenAttributes`.

**Comment by timoschilling** [comment]
Im closing this, while it's not a ActiveAdmin bug
