### ISSUE TITLE
add rake db:seed to instructions to avoid confusion

### ISSUE THREAD

**Issue by ianheggie** [activeadmin/activeadmin#4186]
Add 'rake db:seed' to README as otherwise the login given does not work, eg add it as follows:
```
 Migrate your db and start the server:

  $> rake db:migrate 
  $> rake db:seed
  $> rails server

Visit http://localhost:3000/admin and log in using:

    User: admin@example.com
    Password: password
```
I also suggest changing the db/seed.rb line to allow rake db:seed to be run more than once:
```
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if AdminUser.where(email: 'admin@example.com').blank?
```

**Comment by timoschilling** [comment]
We already have the `rake db:seed` in the installment instruction https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md#setting-up-active-admin.

But the `AdminUser.create!(...) if AdminUser.where(email: 'admin@example.com').blank?` is a good point.
It can be done simpler `AdminUser.create!(...) unless AdminUser.exists?(email: 'admin@example.com')`

**Comment by ianheggie** [comment]
Oops - the page that needs `rake db:seed` is http://activeadmin.info/docs/documentation.html - sorry for the confusion. And yes - using `unless exists?...` is cleaner

**Comment by seanlinsley** [comment]
We'll update the website when we push out the official 1.0.0 release, which should be fairly soon.
