### ISSUE TITLE
Nested form in show resource page does not display form submit button

### ISSUE THREAD

**Issue by nileshtrivedi** [activeadmin/activeadmin#4189]
```ruby
show do |article|
    attributes_table do
      row :id
      row :title
    end

    div do
      semantic_form_for [:admin, article], builder: ActiveAdmin::FormBuilder do |f|
         f.has_many :comments, allow_destroy: false, new_record: true, heading: false do |g|
            g.input :body
         end
         f.actions
      end
    end
end
```
The nested form is displayed and works correctly but the submit button is not displayed (which should be as per `f.actions`

**Comment by kashifnaseer** [comment]
Any information on this ? I'm facing the same issue ?

**Comment by kashifnaseer** [comment]
Workaround: I moved the Nested form to a view and i'm able to see the "Update" button. like 

      show do
        attributes_table do
          row :id
          row :description
        end
        panel "Link Projects" do
          render partial: 'project_links', locals: { id: company }
        end  
       end

**Comment by timoschilling** [comment]
Is this still a issue?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
