### ISSUE TITLE
Conflict with Comment ressource ?

### ISSUE THREAD

**Issue by vdaubry** [activeadmin/activeadmin#4190]
We have a ``` comments ``` table in our schema.

The comments tab in ActiveAdmin is empty, all other ressources are working fine.
It looks like the comments tab is displaying ``` ActiveAdmin::Comment ``` instead of our comments ?

We're using 1.0.0.pre2 with Rails 4.2.0

We tried to disable active admin comments without success (the tab disappears) 

```
ActiveAdmin.setup do |config|
  config.allow_comments = false
end
```

We would like to be able to edit rows from our comments table just like any other ressource, is that possible ?

Thanks for your help,
Vincent

**Comment by timoschilling** [comment]
Yes, ActiveAdmin uses its own model by default.
Take a look on your `active_admin.rb`, to configure it different:
```
  # == Admin Comments
  #
  # This allows your users to comment on any resource registered with Active Admin.
  #
  # You can completely disable comments:
  # config.comments = false
  #
  # You can disable the menu item for the comments index page:
  # config.show_comments_in_menu = false
  #
  # You can change the name under which comments are registered:
  # config.comments_registration_name = 'AdminComment'
  #
  # You can change the order for the comments and you can change the column
  # to be used for ordering
  # config.comments_order = 'created_at ASC'
```

**Comment by vdaubry** [comment]
@timoschilling Thanks for your answer ! Now i get a 

```
NoMethodError in Admin::CommentsController#index
undefined method `per_page_kaminari' for #<Comment::ActiveRecord_Relation:0x007f8217533b80>
```

It seems related to these issue : https://github.com/activeadmin/activeadmin/issues/2537
https://github.com/amatsuda/kaminari/issues/481

The activeadmin (1.0.0.pre1) requires kaminari (~> 0.15) , which resolves to kaminari 0.16.3


Here is my active admin config :

```
config.comments_registration_name = 'AdminComment'
...
ActiveAdmin.register Comment, as: "Comment"
```

I'm using ```will_paginate 3.0.5 ``` , 

I have added an initializer for kaminari :
```
Kaminari.configure do |config|
  config.page_method_name = :per_page_kaminari
end
```

**Comment by timoschilling** [comment]
I think I have miss understand your first post.
Let me reflect your problem: You want to have a Comment model as a normal model in ActiveAdmin not as a replacement for ActiveAdmin::Comment?

**Comment by vdaubry** [comment]
@timoschilling Exactly, we have a comment model and we would like to display it in activeadmin just like other models (users, etc) 

Given the error i get i think i'm on the right track : we are using will_paginate and it seems there's a problem regarding pagination with kaminari.

**Comment by timoschilling** [comment]
try this:
```ruby
ActiveAdmin.register ::Comment
```
and read this
https://github.com/activeadmin/activeadmin/blob/ba285ea2fc23ade108ed582134cae8c641f910a4/docs/0-installation.md#will_paginate

**Comment by vdaubry** [comment]
I have registered the Comment model, in ActiveAdmin initializer :

``` ActiveAdmin.register ::Comment ```

I have an initializer for kaminari :

```
Kaminari.configure do |config|
  config.page_method_name = :per_page_kaminari
end
```

All models works fine, but when i go to Comment i get :

``` undefined method `per_page_kaminari' for #<Comment::ActiveRecord_Relation> ```

P.S: If i disable the kaminari initializer, all ressource in active admin fail because it cannot find the ``` per ``` method.
If i enable the kaminari initializer only Comment model fails because it cannot find the ``` per_page_kaminari ``` method.
So it seems there's something specific to this registered model ?

**Comment by timoschilling** [comment]
Is this still an issue?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
