### ISSUE TITLE
Date filtering is not working

### ISSUE THREAD

**Issue by bnussey** [activeadmin/activeadmin#4193]
Recently I've noticed that the date filtering is not working correctly.Could it be a Ransack problem?

The logs indicate that the params are being correctly passed through, and they are also still in the URL.. The count works fine, but the actual querying does not take place. Any ideas what could be going on here? I did recently upgrade to `Ruby 2.2` but I'm not sure if that's related.

Here are the params:

```
Started GET "/admin/users?utf8=%E2%9C%93&q%5Bcreated_at_gteq%5D=2015-11-01&q%5Bcreated_at_lteq%5D=2015-11-30&q%5Brole_contains%5D=read&commit=Filter&order=id_desc" for 50.17.182.190 at 2015-11-13 05:16:52 +0000
```

Here you can see the date is never used in the SQL query:

```
User Load (0.8ms)  SELECT  "users".* FROM "users"  WHERE ("users"."role" ILIKE '%read%')  ORDER BY "users"."id" desc LIMIT 30 OFFSET 0
```

Full logs are below:

```
 Started GET "/admin/users?utf8=%E2%9C%93&q%5Bcreated_at_gteq%5D=2015-11-01&q%5Bcreated_at_lteq%5D=2015-11-30&q%5Brole_contains%5D=read&commit=Filter&order=id_desc" for 50.17.182.190 at 2015-11-13 05:16:52  +0000
Processing by Admin::UsersController#index as HTML
  Parameters: {"utf8"=>"✓", "q"=>{"created_at_gteq"=>"2015-11-01", "created_at_lteq"=>"2015-11-30", "role_contains"=>"read"}, "commit"=>"Filter", "order"=>"id_desc"}
  User Load (0.4ms)  SELECT  "users".* FROM "users"  WHERE "users"."id" = 1  ORDER BY "users"."id" ASC LIMIT 1
   (0.4ms)  SELECT COUNT(*) FROM "users"  WHERE ("users"."role" ILIKE '%read%')
   (0.3ms)  SELECT COUNT(*) FROM "users"  WHERE ("users"."role" ILIKE '%read%') AND (created_at > '2015-11-01 00:00:00.000000')
   (0.3ms)  SELECT COUNT(*) FROM "users"  WHERE ("users"."role" ILIKE '%read%') AND (created_at > '2015-11-09 00:00:00.000000')
   (0.3ms)  SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM "users"  WHERE ("users"."role" ILIKE '%read%') LIMIT 30 OFFSET 0) subquery_for_count
  CACHE (0.0ms)  SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM "users"  WHERE ("users"."role" ILIKE '%read%') LIMIT 30 OFFSET 0) subquery_for_count
  CACHE (0.0ms)  SELECT COUNT(*) FROM "users"  WHERE ("users"."role" ILIKE '%read%')
  CACHE (0.0ms)  SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM "users"  WHERE ("users"."role" ILIKE '%read%') LIMIT 30 OFFSET 0) subquery_for_count
  User Load (0.8ms)  SELECT  "users".* FROM "users"  WHERE ("users"."role" ILIKE '%read%')  ORDER BY "users"."id" desc LIMIT 30 OFFSET 0
```

**Comment by timoschilling** [comment]
Please post your `app/admin/user.rb`

**Comment by bnussey** [comment]
Hey @timoschilling its actually effecting all pages across activeadmin so thinking it could be related to something else..

Here is the code:

    ActiveAdmin.register User do

    menu :if => proc{ current_user.role=="administrator" }

    controller do
      def update
        if params[:user][:password].blank?
          params[:user].delete("password")
          params[:user].delete("password_confirmation")
        end
        super
      end
    end


    scope :all, :default => true
    scope :new_this_month
    scope :new_this_week

    permit_params do
      params  = [:email, :password, :password_confirmation, :currency, :first_name, :last_name, :address, :phone_number, :favorite_category_id, :phone_number, :country, :categories, :onboarding_call, :favorite_category_subscribe, :trial_end, :trial_elapsed, :trial_checked, :free_trial_offered, :api_key, user_ids: [], category_ids: []]
      params.push :role if current_user.role=="administrator"
      params
    end

    index do
      selectable_column
      column :id
      column :email
      column :created_at
      column :last_seen_at
      column :current_sign_in_at
      column :sign_in_count
      column "Referrals" do |r|
        unless r.referrals_id.nil?
          Referral.find(r.referrals_id).name
        end
      end
      column :subscribed do |s|
        "Yes" if Subscription.exists?(:user_id => s.id)
      end
      column :first_name
      column :last_name
      column :currency
      column :country
      column :phone_number
      column :role
      column :onboarding_call
      column :trial_end
      column :trial_elapsed
      column :trial_checked
      column :free_trial_offered
      column "Categories" do |user|
        user.categories.map{ |p| p.name }.join(' ')
      end
      column :favorite_category_id
      column :favorite_category_subscribe
      column :welcome_email
      column :failure_email
      column :api_key
      column :current_sign_in_ip
      column :last_sign_in_ip
      actions
    end

    filter :email
    filter :current_sign_in_at
    filter :sign_in_count
    filter :created_at
    filter :role
    filter :free_trial_offered
    filter :country
    filter :onboarding_call, :as => :select, :collection => ["No", "Attempted", "Completed", "Wrong Number", "Unsuccessful", "Coaching Session Scheduled"]
    filter :failure_email
    filter :referrals_id, :as => :select, :collection => Referral.all
    filter :current_sign_in_ip
    filter :last_sign_in_ip

    form do |f|
      f.inputs do
        f.input :email
        f.input :password
        f.input :password_confirmation
        f.input :first_name
        f.input :last_name
        f.input :phone_number
        f.input :currency, :as => :select, :collection => ["USD", "AUD", "CAD", "EUR", "GBP", "NZD"]
        f.input :country
        f.input :categories, :as => :select, :input_html => {:multiple => true}
        f.input :favorite_category_id, :as => :select, :collection => [["Adult Products", 1], ["Automotive", 2], ["Bed & Bath", 3], ["Electronics & Accessories", 4], ["Experiences", 5], ["Fashion & Footwear", 6], ["Health & Beauty", 7], ["Home & Furniture", 8], ["Jewellery & Accessories", 9], ["Kitchen", 10], ["Miscellaneous", 11], ["Pets Accessories", 12], ["Print & Personalized", 13], ["Sporting Accessories", 14], ["Toys & Kids", 15]]
        f.input :favorite_category_subscribe
        #  f.input :phone_number
        if current_user.role=="administrator"
          f.input :onboarding_call, :as => :select, :collection => ["No", "Attempted", "Completed", "Wrong Number", "Unsuccessful", "Coaching Session Scheduled"]
          f.input :role, :as => :radio, :collection => [["Guest", "guest"], ["Read", "read"], ["Moderator", "moderator"], ["Administrator", "administrator"]]
          f.input :free_trial_offered
          f.input :trial_end
          f.input :trial_checked
          f.input :trial_elapsed
          f.input :api_key
        end
      end
      f.actions
    end

    show title: "My Profile" do
      attributes_table :email, :first_name, :last_name, :currency, :categories, :phone_number, :onboarding_call
    end

    sidebar :statistics do
      render '/admin/user_analysis'
    end

    end

**Comment by Fivell** [comment]
@bnussey , is it still an issue?
