### ISSUE TITLE
Using tabs in index page

### ISSUE THREAD

**Issue by saifuddin** [activeadmin/activeadmin#4201]
I love the tabs design that we can use in show pages. Here's an example:
![screen shot 2015-11-17 at 19 37 26](https://cloud.githubusercontent.com/assets/175973/11230225/af85f04e-8d62-11e5-8e08-91542d617395.png)
I've tried to use this in the index page, but somehow the UI goes haywire.
![screen shot 2015-11-17 at 19 38 53](https://cloud.githubusercontent.com/assets/175973/11230245/e150fd3a-8d62-11e5-8f75-4eaa92888624.png)

I was wondering if I can use tabs in the index page.

How would they even work, and if that's even possible?

Thanks!

**Comment by timoschilling** [comment]
This is to much edge case

**Comment by itkin** [comment]
+1

**Comment by varyonic** [comment]
You can use multiple [index pages](https://activeadmin.info/3-index-pages.html) and/or define your own [custom index](https://activeadmin.info/3-index-pages/custom-index.html).
