### ISSUE TITLE
Obligatory Ransack

### ISSUE THREAD

**Issue by joallard** [activeadmin/activeadmin#4202]
I just noticed calling `.search` on one of my models that we just automatically include Ransack on models. That's a little rude. I didn't expect AA to modify my models directly especially when there's not even an admin page for that model.

**Comment by seanlinsley** [comment]
Unfortunately that's not something we can control. Feel free to open a ticket or PR on Ransack to change its behavior.

BTW, while surprising, it's certainly not uncommon behavior. To list off a few other gems that do the same thing: paper_trail, will_paginate, kaminari, carrierwave

**Comment by joallard** [comment]
You're right, thanks.
