### ISSUE TITLE
ActiveAdmin - limit admin interface to sub-net or localhost

### ISSUE THREAD

**Issue by ACPK** [activeadmin/activeadmin#4203]
I'm surprised that this isn't an option in active_admin, but how many people here limit access to their admin interface via IP address?

If anyone's interested, I'm happy to make a PR.

**Comment by timoschilling** [comment]
You can do that via rails scope constraints, so there is no reason do build this into ActiveAdmin

**Comment by ACPK** [comment]
@timoschilling - My reasoning was to recommend the security feature.

**Comment by seanlinsley** [comment]
A better way to ensure security would be to require user accounts. If you're extra paranoid you could require accounts, and only allow access from certain IPs, but neither of which are direct concerns for Active Admin. For example we delegate authentication to Devise. For authorization we have our own plugin system that allows you to use gems like CanCan.

**Comment by seanlinsley** [comment]
But if you would like to write up documentation on security best practices, we'd be happy to review it.

**Comment by ACPK** [comment]
@seanlinsley - We already have user accounts and also use two-auth. For HIPAA, we want to limit access to the office.
