### ISSUE TITLE
Can't use active admin with refinerycms 

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [activeadmin/activeadmin#4204]
I have my app already integrated with refinerycms gem and when I install active admin and navigated to 
locahost:3000/admin/login got the below error.

undefined method `new_admin_user_password_path' for #<ActionDispatch::Routing::RoutesProxy:0x00000006a9cbc0>

Please tell me
1. why devise routes for active admin are not identified.
2. Is it good having both refinerycms and activeadmin in the same app.

I am sure I am not having smooth journey integrating activeadmin in the app which is already having refinerycms

If both refinerycms and activeadmmin can't fit in same app, I have to rebuild the app to use activeadmin alone.

Note: Both activeadmin & refinerycms uses devise for login.

**Comment by timoschilling** [comment]
please post your `routes.rb`

**Comment by railsfactory-bhaskararao** [comment]
require 'sidekiq/web'
require 'sidetiq/web'

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  unless Rails.env.production?
    mount Sidekiq::Web => '/sidekiq'
  end

  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"

  get '/blog' => redirect("/page/blog")
  get '/page' => redirect("/")

  mount Refinery::Core::Engine, at: '/page'

  get '/refinery', to: redirect { |path_params, req| "/page/refinery" }
  get '/humans', to: 'application#humans'
  get '/sitemap', to: 'application#sitemap'

  patch '/page/refinery/website_users/competitions/:id/state' => 'refinery/website_users/admin/competitions#state',
    as: 'website_users_admin_competition_state'

  devise_for :users, :controllers => {
    omniauth_callbacks: 'omniauth_callbacks',
    passwords: "passwords",
    registrations: "registrations",
    sessions: "sessions"
  }
  # The priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'home#index'

  resource :profile, except: [:new, :destroy, :create], path: '/dashboard' do
    get :account_type
    match 'finish_signup', to: 'profiles#finish_signup', via: [:get, :patch]
  end

  resources :contests, controller: :competitions, as: :competitions do
    patch 'feedback'
    resource :payment, only: [:new, :create] do
      get 'express' => 'payments#express', as: 'express'
    end
    resources :names do
      member do
        put 'set_winner' => 'names#set_winner', as: 'set_winner'
      end
      resources :comments, except: [:new, :edit]
    end
    resources :competition_comments, only: [:index, :create, :destroy]
    collection do
      get 'name_choosing' => 'competitions#name_choosing', as: 'name_choosing'
    end
  end

  post '/change_current_country' => 'application#change_current_country'

  post '/instamojo_webhook', to: 'application#instamojo_webhook'
  get '/instamojo_payment_complete', to: 'application#after_instamojo_payment'

  get '/contacts', to: 'home#contacts'

end

**Comment by timoschilling** [comment]
pleas post your `admin_user` model too

**Comment by railsfactory-bhaskararao** [comment]
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

**Comment by timoschilling** [comment]
please read this and use it for you next comments https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

**Comment by railsfactory-bhaskararao** [comment]
@timoschilling  any luck with my issue?

**Comment by timoschilling** [comment]
@railsfactory-bhaskararao every thing look's ok to me. Whats happen if you remove this code?
```ruby
  devise_for :users, :controllers => {
    omniauth_callbacks: 'omniauth_callbacks',
    passwords: "passwords",
    registrations: "registrations",
    sessions: "sessions"
  }
```

**Comment by railsfactory-bhaskararao** [comment]
undefined method `user_signed_in?' for #<Admin::DashboardController:0x0000000ae52270>

**Comment by kiddrew** [comment]
I'm running into this issue too.  The core problem is that Rails defaults to Refinery::Authentication::Devise::User for auth instead of my AdminUser class.  Anyone find a workaround for this?

**Comment by ogerman** [comment]
Hi!
I've disabled devise config overriding in [my fork](https://github.com/ogerman/refinerycms-authentication-devise), and now activeadmin works

**Comment by eneeyac** [comment]
Disabling the devise config does not work for me. After disabling login form for ActiveAdmin is shown, but after form submission 'undefined method "username'' ' appears. It seems ActiveAdmin tries to use Refinery's User model.

Does anyone have any thoughts how to fix this issue? Maybe not implementation, but just an idea, which can be implemented by someone else.

**Comment by timoschilling** [comment]
@ogerman thanks for investigating! This is the fault of refinerycms, they change the global devise config.
