### ISSUE TITLE
Adding X::Editable::Rails

### ISSUE THREAD

**Issue by chrisseldo** [activeadmin/activeadmin#4205]
Ever think about adding [x-Editable](https://vitalets.github.io/x-editable/) for the index page? 
I've been trying to implement it myself using [this gem](https://github.com/werein/x-editable-rails), but to no avail. 
If anyone has found a workaround/solution that'd be awesome!

Thanks :octocat:

**Comment by timoschilling** [comment]
We don't wont to over blow the core with functionality and dependencies, but feel free to build a gem as extension.

**Comment by Fivell** [comment]
@chrisseldo , maybe this can help https://github.com/activeadmin/activeadmin/wiki/How-to-Add-In-Page-Editing-Using-Gem-best_in_place

**Comment by chrisseldo** [comment]
Yeah, I'm already using the Best In Place gem for the Show pages for a few models, but I feel like it doesn't make for a clean solution on the Index page. Perhaps I'll look into making a gem for it. I can see it now: **ActiveEditable**!

Thanks again!
