### ISSUE TITLE
 upgrade to rails4.2 - filters stopped working

### ISSUE THREAD

**Issue by niksfirefly** [activeadmin/activeadmin#4206]
After upgrade from rails 4.1 to 4.2
filters stopped working without any errors from development logs
1.filtering not working at all
2.there is no way to disable search sidebar
even when i set
config.current_filters = false
3.search fields become - simple inputs

![filters](https://cloud.githubusercontent.com/assets/639578/11324600/71cbc260-9136-11e5-9178-5d14df2cb5d0.png)

I tried to downgrade ransack/formtastic - no effect
Is Activeadmin incompatible with rails 4.2? or there is procedure to upgrade?

regards

**Comment by seanlinsley** [comment]
What versions of Active Admin and Ransack were you using before, and what are you using now?

**Comment by niksfirefly** [comment]
RVM and

rails (4.1.5)
ransack (1.2.3)
activeadmin (1.0.0.pre) from github master

not working with:
rails (4.2.0 - 4.2.5)
ransack (1.7.0)
activeadmin (1.0.0.pre2)  from github master

**Comment by niksfirefly** [comment]
Sorry my mistake.
Custom input for formtastic bring some nasty side effects.
