### ISSUE TITLE
Export does not include belongs_to or has_one

### ISSUE THREAD

**Issue by jostster** [activeadmin/activeadmin#4207]
When exporting a resource in csv format, the file will not include any belongs_to columns or has_one columns.

**Comment by seanlinsley** [comment]
CSV doesn't allow for nested resources, so this isn't currently possible. You might be able to accomplish this with https://github.com/randym/activeadmin-axlsx

**Comment by jostster** [comment]
If I specify the columns in the resource it works. Just doesn't work
automatically.

**Comment by seanlinsley** [comment]
Sure, but that's not a bug, nor is it a feature that Active Admin should provide (IMO).

**Comment by jostster** [comment]
I could be wrong but it seems that specifying
'''Column(:Person)''' works so that should happen automatically in the
default csv export if it is a column

**Comment by edatrix** [comment]
@jostster I'm running into the same issue.  would you mind more clearly explaining what you did to get this working?  does it include filtering on the downloads?

**Comment by virtru-bjost** [comment]
@edatrix iirc i ended up having to specify Column(:blah) for everything i wanted exported.

**Comment by jostster** [comment]
@edatrix iirc i ended up having to specify `Column(:name)` for all the columns i wanted exported.
