### ISSUE TITLE
Filter search results ignore i18n

### ISSUE THREAD

**Issue by doc** [activeadmin/activeadmin#4214]
Hi All,

The filter results sidebar section does not seem to be i18n'ified. Looking quickly at the code, it appears that the filters are just translated the by removing '_' characters, segregating the predicates and then capital casing the field name rather than looking to the i18n API to get the translation.  I am open to the possibility that i'm doing something wrong too; can someone confirm?

Mark

**Comment by deivid-rodriguez** [comment]
Is this the same as #4899?

**Comment by Fivell** [comment]
closed by #4951
