### ISSUE TITLE
Eager load author 

### ISSUE THREAD

**Issue by betesh** [activeadmin/activeadmin#4215]
ActiveAdmin::Comment's [#find_for_resource_in_namespace method](https://github.com/activeadmin/activeadmin/blob/b44b4f4896ef78b50c35c82a343356d68b937cde/lib/active_admin/orm/active_record/comments/comment.rb#L27) should eager-load authors.

The only time that method is called is for [the comments section of the show page](https://github.com/activeadmin/activeadmin/blob/b44b4f4896ef78b50c35c82a343356d68b937cde/lib/active_admin/orm/active_record/comments/views/active_admin_comments.rb#L15), where it iterates through them and calls `author` on each one.

Eager-loading polymorphic associations is not trivial.  Here's [one approach](http://blog.animascodelabs.com/2014/10/30/preloading-polymorphic-relationships-in-rails/)

**Comment by timoschilling** [comment]
:+1:

**Comment by betesh** [comment]
Here's a rough idea of what's involved, based on the Rails 4.1 approach [described here](http://cha1tanya.com/2013/10/26/preload-associations-with-find-by-sql.html).  I tried this in the Rails console suing Rails 4.2.5

    comments = ActiveAdmin::Comment.find_for_resource_in_namespace(resource, :root)
    grouped_comments = comments.group_by(&:author_type)
    grouped_comments.each do |k,v|
      ActiveRecord::Associations::Preloader.new.preload(v, :author)
    end
    comments.collect(&:author)

I wish I had time to submit a whole PR with tests.  Tests are especially important because the Preloader is a nodoc and so not guaranteed to continue working the same way from one version to the next.  See rails/rails#11719

**Comment by betesh** [comment]
One other thing to keep in mind, however, is that sometimes the display name may require preloading an additional model, so the above code gets more complex:

    grouped_comments.each do |k,v|
      options = SomeConfigurationObject.display_name_preloader(k.underscore).presence   # Image that this could return some set of nested associations
      options = { author: options } if options
      ActiveRecord::Associations::Preloader.new.preload(v, options || :author)
    end

**Comment by seanlinsley** [comment]
We're not going to be able to support this until Rails itself supports eager loading polymorphic associations.

**Comment by betesh** [comment]
I understand not wanting to rely on undocumented behavior, even if AA has the test coverage to detect breaking changes right away.  Nevertheless, at the end of the day, it's a performance bug in AA, so whether a fix is possible at this time or not, it should be tracked.

Is there a "Known Issues" page that would be a better way of keeping track of this as an alternative to keeping open a ticket that we can't act on right now?

**Comment by seanlinsley** [comment]
How bad is the performance issue? I haven't noticed a large speed problem when viewing the comments index page. Are you sure you have indexes on the primary keys of all the tables comments are left on?

**Comment by seanlinsley** [comment]
How big is the speed difference with and without this change in your application?

**Comment by betesh** [comment]
Even with good indexes, it's not scalable.  Turn your logging up to DEBUG and you'll see that getting the author's display_name is O(n)--1 query per comment (and multiple queries per author).  Eager-loading would make it O(1)--1 query per author_type no matter how many comments and no matter how many authors.

While the difference might not be visible with 20 comments, it's going to be very visible with 500 comments.

**Comment by javierjulio** [comment]
While I've done the preloader approach and in fact I'm using it in ActiveAdmin, we have tests in our app for it to cover on Rails upgrades. I don't think its a good idea to include this in AA proper though since it is considered private in Rails.

Its odd that its not paginated. I don't think it was intended for it to have that many comments. We should consider at minimum a next/prev pagination setup. I'll open that as a new ticket.
