### ISSUE TITLE
Need help regarding custom filters

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [activeadmin/activeadmin#4218]
I have a user model with having attributes namer, family and both are of type boolean.

activeadmin generating namer and family as a two different filters instead I want to create a single filter such as UserType having drop down with Family, Namer available.
```ruby
filter :by_user_type, label: "UserType", as: :select, collection: ['Family', 'Namer']
```

and in my app/models/user.rb
```ruby
  ransacker :by_user_type,
    formatter: proc { |by_type|
      results = User.where(by_type.downcase.to_sym => true)
    }, splat_params: true do |parent|
    parent.table[:id]
  end
```
  
I just got that code snippet by googling and it is not working. Can someone suggest to make this happen?

**Comment by timoschilling** [comment]
You use ransack in the wrong way, I know google is full with examples like yours, but it is wrong!
That's not for what a `formatter` is made for.

We don't have the time to help with not related ActiveAdmin problems. You can comeback if you have a working ransacker and need help with the integration into ActiveAdmin, but until them I going to close this issue.

**Comment by madakopihub** [comment]
please take a look on this thread @railsfactory-bhaskararao  : https://stackoverflow.com/questions/22473391/custom-search-with-ransacker
