### ISSUE TITLE
Active admin sending data unserialized format

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [activeadmin/activeadmin#4219]
I have a model called Award where prices will be serialized as follloowss.

:coffee: 
{:single=>{:namer=>{:usd=>20, :inr=>1200}, :family=>{:usd=>30, :inr=>1800}, :instamojo_base_link=>"https://www.instamojo.com/Epaminond/pay-for-a-contest", :instamojo_competition_id_field_name=>"Field_70261"}, :twins=>{:namer=>{:usd=>40, :inr=>2400}, :family=>{:usd=>50, :inr=>3000}, :instamojo_base_link=>"https://www.instamojo.com/Epaminond/pay-for-a-contest", :instamojo_competition_id_field_name=>"Field_70261"}, :triplets=>{:namer=>{:usd=>60, :inr=>3600}, :family=>{:usd=>70, :inr=>4200}, :instamojo_base_link=>"https://www.instamojo.com/Epaminond/pay-for-a-contest", :instamojo_competition_id_field_name=>"Field_70261"}}

But when I submit the above data from activeadmin form I am getting this data stored as string instead of as hash.

In my app/modes/award.rb file
serialize :prices

Kindly tell me how to store data serialized from activeadmin form.

**Comment by timoschilling** [comment]
The ActiveAdmin form works like any other form. I close this while it is not a ActiveAdmin problem.

Hint: try this:
```ruby
serialize :prices, Hash
```

If it works with a normal form, but not with a ActiveAdmin one, you can come back.

**Comment by railsfactory-bhaskararao** [comment]
I want to activeadmin form that comprises the serialized attributes

**Comment by timoschilling** [comment]
You want a ActiveAdmin form to edit the serialized attributes?

**Comment by railsfactory-bhaskararao** [comment]
Yes @timoschilling
