### ISSUE TITLE
CanCan::AuthorizationNotPerformed in AdminPanel::DashboardController#index 

### ISSUE THREAD

**Issue by wolfieorama** [activeadmin/activeadmin#4221]
How can i Whitelist the whole of activeadmin and devise  to no use cancan for authorization, so far 
>   check_authorization unless: :devise_controller?

works for login page only but cant get past that as it throws the error 

> CanCan::AuthorizationNotPerformed in AdminPanel::DashboardController#index

**Comment by timoschilling** [comment]
Why do you want to do that?

**Comment by wolfieorama** [comment]
because I am using device for activeadmin authorization only  and the erst of the App is being handled by sorcery, I have an admin_user for device who is not part of cancan or even User.rb (sorcery model)

if i comment out check_authorization in application controller, everything works well but i feel thats not ideal

**Comment by timoschilling** [comment]
is that `check_authorization` for devise or sorcery?

**Comment by wolfieorama** [comment]
its for devise

**Comment by timoschilling** [comment]
if it's for devise and you use devise only for active admin, then you don't need `check_authorization` in application controller. ActiveAdmin has it's own code for that

**Comment by wolfieorama** [comment]
ok... thanks for confirming that
