### ISSUE TITLE
It's wrong `@underscored_user_name` defined in `InstallGenerator`.

### ISSUE THREAD

**Issue by jarosluv** [activeadmin/activeadmin#4225]
When I install AA with class name like `Foo::BarBaz` (`rails g active_admin:install Foo::BarBaz`) I get wrong method names in initializer:
```
config.current_user_method = :current_foo/bar_baz
config.logout_link_path = :destroy_foo/bar_baz_session_path
config.authentication_method = :authenticate_foo/bar_baz!
```
but should (like Devise define this names):
```
config.current_user_method = :current_bar_baz
config.logout_link_path = :destroy_bar_baz_session_path
config.authentication_method = :authenticate_bar_baz!
```

**Comment by seanlinsley** [comment]
Thanks for reporting this @jarosluv. Unfortunately we don't really have a test suite around the installer, so I just committed a fix for this on master: 5f190fba809a20f3cae83cc547d1a9003e91193f
