### ISSUE TITLE
filters with belongs to association dont show 

### ISSUE THREAD

**Issue by wolfieorama** [activeadmin/activeadmin#4227]
I have installed active admin works well but on all filters that have a belongs_to: associaation i get very weird name listed e. for the model user.rb 
```ruby
class User < ActiveRecord::Base
  belongs_to :team
  has_many :attendances

  def name
    "#{first_name} #{last_name}"
  end
end
```
this is what i get on the team dropdown <Team:0xx007yfgfgddjhjhgghjj0007> while these association are working well on my app, what i am missing here 

even when i pass the filter as so:

```ruby
filter :team, as: :select, collection: proc { Team.all }
```

**Comment by timoschilling** [comment]
```ruby
class User < ActiveRecord::Base
  belongs_to :team
  has_many :attendances

  def name
    "#{first_name} #{last_name}"
  end
  alias_method :display_name, :name
end
```

**Comment by wolfieorama** [comment]
The user names are displaying well on active admin its the 'Team' that are showing as i indicated, or I am missing your explanation , I dont understand the line you added to the def name method

**Comment by wolfieorama** [comment]
@timoschilling any progress on this ? thanks

**Comment by timoschilling** [comment]
If you want to show the name of the model and not `Team:0xx007yfgfgddjhjhgghjj0007`, you need to implement `display_name` in that model

**Comment by wolfieorama** [comment]
will try that and get back , bu shouldnt that method go to the team model or to the model where i want to display the team names ?

**Comment by wolfieorama** [comment]
may be i should have posted this instead, to stop the confusion:

```ruby 
class Team < ActiveRecord::Base

  validates :team_code, :description, presence: true
  validates :team_code, uniqueness: true

  has_many :users
  belongs_to :admin 
  has_many :attendance_sheets
end
```

see now, when ever i want to assign an admin a new team, the drop down show those weird number and not the team names, so to seek clarification, you mean i implement the display method here ?

**Comment by wolfieorama** [comment]
@timoschilling i have used the below code and i an running in a cyclic error 

```ruby 
def team_code
    "#{team_code}"
  end

  alias_method :display_name, :team_code
```

**Comment by timoschilling** [comment]
That can't work, your `team_code` method call it self.
Remove your `team_code` method. If `team_code` is a database field you will already have that method via active record.

Just keep the `alias_method :display_name, :team_code` or you can write:
```ruby
def display_name
  team_code
end
```
thats the same like `alias_method ...`

**Comment by wolfieorama** [comment]
Thanks finally it work
