### ISSUE TITLE
Nested Resource controller actions

### ISSUE THREAD

**Issue by pandugreycampus** [activeadmin/activeadmin#4229]
I created a resource in activeadmin called companies, all controller actions are working fine. Now i have routes like below

admin/companies
admin/companies/:company_id
admin/companies/:company_id/edit
and soon...
Now i need to created nested resources it means

admin/companies/:company_id/company_email_formats
admin/companies/:company_id/company_email_formats/:id
admin/companies/:company_id/email_formats/:id/edit

i've done this by referring following link
http://stackoverflow.com/questions/12373381/how-to-declare-a-nested-resource-in-activeadmin?answertab=active#tab-top

It generated routes for me but when i accessed a route it showing me " NoMethodError "
NoMethodError at /admin/companies/168/company_email_formats

Please help me how can i solve this problem

**Comment by timoschilling** [comment]
You need to provide more information about that error

**Comment by pandugreycampus** [comment]
I created a model named company and all actions are working fine
Routes are:
/admin/companies
/admin/companies/:company_id
/admin/companies/:company_id/edit

now i need one more resource company_formats which basically depends on company model

and routes should be
/admin/companies
/admin/companies/1
/admin/companies/1/edit
/admin/companies/1/company_formats
/admin/companies/1/company_formats/5
/admin/companies/1/company_formats/5/edit

please help me
