### ISSUE TITLE
customize menu

### ISSUE THREAD

**Issue by mastermike14** [activeadmin/activeadmin#4234]
http://activeadmin.info/docs/2-resource-customization.md#customize-the-menu

The docs link to a bad url. How do I customize the activeadmin menu?

**Comment by timoschilling** [comment]
here is the right url http://activeadmin.info/docs/2-resource-customization.html#customize-the-menu.
Where did you found the wrong url?

**Comment by peric** [comment]
Here's the wrong link I just also stumbled upon.

http://activeadmin.info/docs/10-custom-pages.html#customize-the-menu
