### ISSUE TITLE
user.admin? not working

### ISSUE THREAD

**Issue by hostingnuggets** [activeadmin/activeadmin#4238]
I am following the same code as mentioned in the "Getting Access to the Current User" paragraph of http://activeadmin.info/docs/13-authorization-adapter.html with ActiveAdmin v1.0.0.pre2 as you can see below:

```
class OnlyAdminUsersAuthorization < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end
```

but it does not work, as I get:

```undefined method `admin?' for #<User:0x007fef81369b38>```

any idea what could be wrong?

**Comment by timoschilling** [comment]
You need to implement `admin?` on your `User` model by your self.
