### ISSUE TITLE
Delay resource decoration until right before view render

### ISSUE THREAD

**Issue by PragTob** [activeadmin/activeadmin#4243]
Hi there,

thanks for making activeadmin.

Currently, if one uses `decorate_with` resources are decorated as soon as they are retrieved from the databse:

``` ruby
    def find_resource(id)
      resource = resource_class.public_send *method_for_find(id)
      decorator_class ? decorator_class.new(resource) : resource
    end
```

Which imo is unhandy as the main use case for decorators (imo) is to decorate/prepare them for the view with a bunch of view specific convenience methods that have nothing to do with the main model.

Having a decorated model in a custom controller action can lead to many subtle bugs. For instance:

``` ruby
[12] pry(main)> tp = Model.last; nil
=> nil
[13] pry(main)> tp.dup.id
=> nil
[15] pry(main)> tpd = tp.decorate; nil
=> nil
[16] pry(main)> tpd.dup.id
=> 28
```

Hence I'd like it if the default would be to just decorate right before render time or if there would be an option to configure this (option to `decorate_with`).

If agreed upon and maybe with a small pointer I'd be happy to help out and implement this myself :)

Cheers,
Tobi

**Comment by timoschilling** [comment]
What problem do you have with the decorated model?

**Comment by PragTob** [comment]
See the irb session, the decorated model does not set its id to nil when dupped. Which means if you want to copy some models and then save them this will override the original model. Sort of like (pseudo code)

```ruby
    blog.posts.each do |post|
      new_post = post.dup
      new_post.blog = new_blog
      new_post.save!
    end
```

As the posts here will end up with the same id as the one they were dupped from, they will override the original in the database, thereby the original blog loses the posts and the posts are only attached to the new_blog.

That is one of the problems we encountered. There were others due to that exact reason, but I can't recall them atm (I just see the tests that say "it doesn't go crazy when the object is decorated") :)

**Comment by timoschilling** [comment]
The reason is that you `dup` the decorator and not the model. You can solve your problem by 'undecorating' the model.

**Comment by PragTob** [comment]
I do know how to solve it. But this is the problem imo with having the decorator even inside the controller action (hence this issue) as imo decorators are meant to be used for views only and not in controller actions. That leads to confusion, e.g. I wouldn't expect it to be like that hence the issue.

If you disagree with that view of decorators and think they should also be used in controller actions and not only in views then I'll close this issue and come up with another solution.

**Comment by seanlinsley** [comment]
I agree with the general idea that decorators should only be applied for the view, not for the controller. In fact I've argued for that in the past. But I'm not sure how you'd implement that in our existing code. Reading `data_access.rb` would be a good start.

**Comment by seanlinsley** [comment]
Actually what I think I argued for was to not apply the decorator in the form, since e.g. Draper can easily break the interface and data that Formtastic expects.
