### ISSUE TITLE
AuthorizationAdapter based on resource name

### ISSUE THREAD

**Issue by thehappycoder** [activeadmin/activeadmin#4245]
I have the following resource:

``` ruby
ActiveAdmin.register Ad, as: 'SendToPoliceAd' do
...
end
```

And many other resources that have the same resource class -- Ad.

In order to restrict access to "SendToPoliceAd" resource I am doing the following workaround:
1)

``` ruby
class ActiveAdminAuthorization < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    if @resource.resource_name.to_s == 'SendToPoliceAd'
      user.admin?
    else
      true
    end
  end
end
```

2)

``` ruby
ActiveAdmin.register Ad, as: 'SendToPoliceAd' do
  menu parent: 'Данные для полиции', if: proc{ current_user.admin? }
  ...
```

Would be good to do this more proper way but currently it's impossible.

**Comment by seanlinsley** [comment]
By the way @thehappycoder, when posting code on Github it's best to use [Github-flavored markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) which lets you apply syntax highlighting to your code, making it easier to read.

I just updated your comment with that syntax.

**Comment by varyonic** [comment]
Would someone elaborate what "more proper" might look like in this case?

**Comment by daveclay** [comment]
I've got the same situation; several activeadmin pages that correspond to a particular `scope` on some `ActiveRecord` class:

```
ActiveAdmin.register Widget, as: "Today's Widgets" do
  menu label: "Today's Widgets"
  controller do
    def scoped_collection
        Widget.for_today
      end
    end
  end
  ...
end
```

```
ActiveAdmin.register Widget, as: "All Widgets" do
  menu label: "All Widgets"
  controller do
    def scoped_collection
        Widget.all
      end
    end
  end
  ...
end
```

And an `Ability` to configure access to those pages based on roles:

```
class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, :dashboard
    if user.roles.include?("admin")
      # doesn't work
      can :manage, ActiveAdmin::Page, name: "All Widgets"
    else
      # doesn't work
      can :manage, ActiveAdmin::Page, name: "Today's Widgets"
    end
  end
end
```

Unfortunately, activeadmin only uses the `active_admin_config.resource_class` when calling `authorize!`:

https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource_controller/data_access.rb#L45

And so these lines in `Ability` do not allow users access to those pages based on `name`:

```
      can :manage, ActiveAdmin::Page, name "All Widgets"
      can :manage, ActiveAdmin::Page, name: "Today's Widgets"
```

We've worked around this by doing three things. First, creating a subclass of the `ActiveAdmin::CanCanAdapter`:

```
class ResourceNameAuthorizationAdapter < ActiveAdmin::CanCanAdapter
  def authorized?(action, subject = nil)
    normalized_resource_name = case subject
    when Symbol
      # for normal "class"-type pages
      subject
    else
      # for "scoped" pages, like "all_widgets" vs "todays_widgets"
      resource.resource_name.param_key.to_sym
    end

    super(action, normalized_resource_name)
  end
end
```

Second, which is more annoying, adding dynamic menu proc on every page we want to restrict:

```
ActiveAdmin.register Widget, as: "All Widgets" do
  menu label: "All Widgets", if: -> { authorized?(:show, :all_widgets) }  
```

```
ActiveAdmin.register Widget, as: "Today's Widgets" do
  menu label: "Today's Widgets", if: -> { authorized?(:show, :todays_widgets) }  
```

And third, adding those specific "subjects" to `Ability`:

```
class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, :dashboard
    if user.roles.include?("admin")
      can :manage, :all_widgets
    else
      can :manage, :todays_widgets
    end
  end
end
```

This works, but it's not as convenient as being able to easily restrict both the page access _and_ have it not show up in the menu by specifying the `resource_class`:

```
class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, :dashboard
    if user.roles.include?("admin")
      can :manage, Widget
    else
      can :manage, Cogs
    end
  end
end
```

I wonder if there's a way to configure what the page passes to `authorize!`
