### ISSUE TITLE
NoMethodError in Admin::AdminUsersController#index

### ISSUE THREAD

**Issue by timetoshift** [activeadmin/activeadmin#4249]
I'm getting the following error message `NoMethodError in Admin::AdminUsersController#index` when selecting "Admin User" or "Comments" on the dashboard (http://localhost:3000/admin/admin_users) when I installed `gem 'activeadmin', github: 'gregbell/active_admin'` in my gem file. I'm not sure if there is an issue with 1.0.0.pre2 and I'm unable to install "0.0.6".
I'm running: 
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
Rails 4.1.8

**Comment by timoschilling** [comment]
please provide a full stacktrace.

**Comment by seanlinsley** [comment]
I'm going to close this ticket since you haven't responded. If you can provide more information, we'll reopen this ticket.
