### ISSUE TITLE
Workaround For CSV Vulnerability

### ISSUE THREAD

**Issue by jaredsmithse** [activeadmin/activeadmin#4256]
#### Problem
For the CSV export functionality, there is a known bug in versions of OpenOffice Excel where someone could get the office programs to execute code on loading of the file. 

An example of how someone could open an executable called calc.exe would look something like `=-2+3+cmd|' /C calc'!'C2' `

#### Recommended Fix
From what I've found, the recommended fix is to prefix everything with a single apostrophe. All of the office programs will ignore it and always treat the cell as inactive content.

[CVE Link](http://seclists.org/bugtraq/2014/Aug/115)
[OWASP Description](https://www.owasp.org/index.php/CSV_Excel_Macro_Injection)

**Comment by seanlinsley** [comment]
Thanks for pointing this out.

There is a `force_quotes` option provided by Ruby's CSV library:
```ruby
>> puts CSV.generate{ |c| c << ['a', 'b'] }
a,b
 => nil 
>> puts CSV.generate(force_quotes: true) { |c| c << ['a', 'b'] }
"a","b"
 => nil 
```

Using that option [is in our documentation](https://github.com/activeadmin/activeadmin/blob/e829379d844e03ab33e619647355091c4859f407/docs/4-csv-format.md). I guess the only question is whether we should set `force_quotes: true` as a default for everyone. Are there any potential problems with that?

**Comment by jaredsmithse** [comment]
Yea the force quotes get used for text that might have a comma in it, but it won't stop the code from being executed. 

Excel only ignores if its one single quote in front. :confused:

**Comment by seanlinsley** [comment]
Are there any spreadsheet applications currently vulnerable to this? That CVE was from 2014.

**Comment by seanlinsley** [comment]
I would argue that it's a bug in those applications, because the CSV format isn't intended to include executable formulas. And if the latest versions of those applications no longer have this bug, I don't think it's important enough that it deserves our time to fix.

**Comment by timoschilling** [comment]
@seanlinsley I agree with you

**Comment by jaredsmithse** [comment]
We verified that it still works in Excel and OpenOffice (both Mac).

Although this format was not intended to have formulae in them, I think thats one of the main value adds of Excel or any spreadsheet processor is to be able to export your data in CSV and then start treating it like a spreadsheet to verify information.

It would be nice though if they didn't give their applications functionality to run code locally from a CSV :stuck_out_tongue:

**Comment by seanlinsley** [comment]
@jaredsmithse if I understand correctly, this is the sort of code we would need to add to our [CSV generator]():

```diff
     def build_row(resource, columns, options)
       columns.map do |column|
-        encode call_method_or_proc_on(resource, column.data), options
+        encode escape(call_method_or_proc_on(resource, column.data)), options
       end
     end
 
@@ -84,6 +84,10 @@ module ActiveAdmin
       end
     end
 
+    def escape(string)
+      string.prepend "'" if string.start_with? '='
+    end
+
     def method_missing(method, *args, &block)
       if @view_context.respond_to? method
         @view_context.public_send method, *args, &block
```

Not only is it a bit of a hack, but it at the very least doesn't work with the only spreadsheet application I have installed: Apple's Numbers.

Given this CSV:
```
a,b
=1+2,'=1+2
```

It treats the `'` and `=` as literal characters, which isn't desirable. Additionally, it doesn't attempt to evaluate `=1+2` as a formula.

<img width="126" alt="screen shot 2015-12-31 at 12 39 40 pm" src="https://cloud.githubusercontent.com/assets/688886/12067212/bee4600e-afbb-11e5-8524-a65f03ce49c5.png">

**Comment by seanlinsley** [comment]
Especially since there isn't a solution that works everywhere, this isn't something that should be fixed in Active Admin.

**Comment by seanlinsley** [comment]
We could certainly add it to our documentation, though.

**Comment by seanlinsley** [comment]
I added this to our documentation in 44e6b83ad41b9332156e75db8434324dfad63960

**Comment by jaredsmithse** [comment]
@seanlinsley good point, I didn't realize that Numbers didn't handle the apostrophe the same way. It seems they did the right thing for CSVs by making sure formulae are never saved.

Considering the fix wouldn't have the same effect on all spreadsheet editors I agree this shouldn't be fixed here. Thanks for you time!

**Comment by seanlinsley** [comment]
Happy to help :dog:
