### ISSUE TITLE
Run tests in Travis in parallel

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#4257]
Travis provides 1.5 "virtual" CPU cores for each VM. Their documentation hints that you may see gains if you use the parallel_tests gem (that we already have set up for local test runs), and the [parallel_tests wiki](https://github.com/grosser/parallel_tests/wiki/Distributed-Parallel-Tests-and-Travis-Support#travis-ci-support) describes how to get it working on Travis.

So with parallel_tests to run two workers on Travis, how long does it take for our test suite to run?

Note this requires **order independent cucumber tests**.

**Comment by javierjulio** [comment]
@deivid-rodriguez do you still want to give this a shot? For faster Travis builds, I'll buy you dinner! 😂

**Comment by deivid-rodriguez** [comment]
This needs order independent cucumbers as a prerequisite. Then we can give parallelization a shot. But yes, leave this one opened! :)

**Comment by javierjulio** [comment]
Oh wow are cucumber tests are order dependent? I've been thinking we should have an issue where we can dump various things that need to be done whether new features or not and see if others want to take it on.

**Comment by deivid-rodriguez** [comment]
Yes, they are... And cucumber does not have a bisect feature like RSpec, so it's not an easy one to tackle.

Maybe we can open an issue and label it with `help wanted`?

**Comment by javierjulio** [comment]
The dinner offer only applied if this was still on Travis! 🤣 So glad that we were able to get this in. Thanks!
