### ISSUE TITLE
Change Text on buttons and bread crumbs for a particular resource 

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [activeadmin/activeadmin#4260]
I have a resource named 'Criterium'. I want to rename it to 'Criteria'

I achieved it with as: 'Criteria', this will make the routes available via /criteria.

Also I want in buttons showing text(create criteria, update criteria, delete criteria). Even the breadd crum should show Criteria instead of acriterium.

Is there any possibility to achieve above?

**Comment by timoschilling** [comment]
You can rename it via the locales

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
