### ISSUE TITLE
New scaffolded controllers inherit from InheritedResources::Base

### ISSUE THREAD

**Issue by Stormcore** [activeadmin/activeadmin#4261]
Is there a way to disable this?

**Comment by seanlinsley** [comment]
Take a look at this: https://github.com/josevalim/inherited_resources/issues/195

**Comment by Stormcore** [comment]
Thanks!

--  
 		
Dzmitry Sukhau
Founder, Stormnet
+375447165233 | stormdjent@gmail.com | Skype: D.Sukhau
 

On January 6, 2016 at 8:05:50 PM, Sean Linsley (notifications@github.com) wrote:

Take a look at this: josevalim/inherited_resources#195

**Comment by Stormcore** [comment]
Hi activeadmin/activead,

I'd like to add you to my professional network on LinkedIn.

- Dzmitry

Confirm that you know Dzmitry: https://www.linkedin.com/e/v2?e=0-ik63jozv-qs&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=Yhee9K8X&invitationId=6100444538151723008








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ik63jozv-qs&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGAtoWlqA_BNQAAAVKkiJC32ArS1I5XTuzL0PJjGitMljax0TRN7oM-aYAvgnM_3dkqIjtxRNqfs5x16oxBwVV4HUYnLkcOaGsrqe3r4f-1sTUzgmJuvs6NwIMoMeRIZ4NpOthpfKd21NVmxpO4SCPffu-qa_qneOE2bhLBzgEapL6WhVrfz_K3eR0ovgFS-h2Q&eid=0-ik63jozv-qs


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ik63jozv-qs&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Stormcore** [comment]
Dzmitry Sukhau would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-a65qk1-ikeyjpmz-5f&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=Yhee9K8X&invitationID=6100444538151723008

View Dzmitry Sukhau&#39;s profile: https://www.linkedin.com/e/v2?e=-a65qk1-ikeyjpmz-5f&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Yhee9K8X&invitationID=6100444538151723008





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-a65qk1-ikeyjpmz-5f&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-a65qk1-ikeyjpmz-5f&loid=AQECzzR7HSBKQAAAAVLFSD0gME7utmJP9W-bD5DkNr3apJveJod26fFplwm89eWmPWs-sJ2wwH8M49w8PS-VEMWXxSOjxovVuM7wD_vr7ffpMOMHTwibLVwYfZS8qekRcasCNdM632Bl6Kfhdntq7jfhAosgbScpsfNuH9ZKUEi72ZkPz0xaRaTD1JKFv3eihw9W

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-a65qk1-ikeyjpmz-5f&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by Stormcore** [comment]
Dzmitry Sukhau would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-a65qk1-ikp7k9yd-ht&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=Yhee9K8X&invitationID=6100444538151723008

View Dzmitry Sukhau&#39;s profile: https://www.linkedin.com/e/v2?e=-a65qk1-ikp7k9yd-ht&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Yhee9K8X&invitationID=6100444538151723008





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-a65qk1-ikp7k9yd-ht&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-a65qk1-ikp7k9yd-ht&loid=AQETm-g4pzn6cwAAAVLqmn-C_qNZ8LFyi3QYketTJ6Yz-q8rJiwLcj5UNNZMEoX791oztTJspsF28MwUGDt0hh93msxpcmvXxYzXD4uGPtIi1j48sbgetEP7L50MczMXBMHLPpv-w6XSlaCJFGdMoSkj04Wa6lCmpao4l2749zXcOOaLe7J0Etb6hPL78afSkbpl

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-a65qk1-ikp7k9yd-ht&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
