### ISSUE TITLE
Should the base install not create the AdminUser table?

### ISSUE THREAD

**Issue by jasper502** [activeadmin/activeadmin#4263]
I was banging my head against the wall all last night trying to get AA installed until I came across what is either a bug or a poorly documented feature.

I ran `rails g active_admin:install` and finally realized that the `add_devise_to_admin_users` migration has `change_table(:admin_users)` vs `create_table(:admin_users)`.  I manually changed that and all was good.  I could be wrong but even if you had an existing AdminUser table this would still fail on a rake right?

**Comment by seanlinsley** [comment]
That migration is generated by Devise, not Active Admin. It looks like there are two different migrations that Devise can use, based on whether the model already exists (AFAICT at least).

https://github.com/plataformatec/devise/tree/master/lib/generators/active_record/templates

**Comment by jasper502** [comment]
Ok.. that makes sense now.  Thanks!
