### ISSUE TITLE
Provide Bootstrap theme at least as an option

### ISSUE THREAD

**Issue by arogachev** [activeadmin/activeadmin#4266]
There is already issue #1027 about it, but it's locked, so I decited to create new one.

Standard theme is OK, but it will be much better to have Bootstrap 3 theme out of the box.

**Comment by timoschilling** [comment]
If you want one, build one

**Comment by arogachev** [comment]
So you are against to include it to extension core?

**Comment by spurdow** [comment]
I really love this as an option, I tried adding my  bootstrap but I need to have to work hard for it and then I had to rollback my ui cause its breaking the font sizes and textsizes which is daunting for me and again another hard work, Im new to rails but It is really a nice added option if bootstrap is supported. 

thanks.
