### ISSUE TITLE
Error when using resource with dymamic list of permitted params

### ISSUE THREAD

**Issue by arogachev** [activeadmin/activeadmin#4267]
According generated comments we can made permitted params list dynamic:

```ruby
# permit_params do
#   permitted = [:permitted, :attributes]
#   permitted << :other if resource.something?
#   permitted
# end
```

However, when I tried to use:

```ruby
permit_params do
  permitted = [:name, :description]
  permitted << :property_group_id if resource.new_record?
  permitted
end
```

I got the following error:

> Couldn't find Product::Category with 'id'=

Error appears not after submit, but on initial page load.

The workaround I used:

```ruby
permitted << :property_group_id if params[:action] == 'create'
```
But it doesn't seem right for me because we can't use `resource`.

I'm using Rails 5.0.0.beta1.

My `Gemfile` contents:

```ruby
gem 'activeadmin', github: 'activeadmin/activeadmin', branch: 'rails-5-rspec'
```

**Comment by timoschilling** [comment]
yes you can access `resource` at that point, while resource isn't initialized at that point.

**Comment by arogachev** [comment]
But in the generated comments there is an example of using `resource`:

```ruby
 permitted << :other if resource.something?
```

Is it deprecated or means something different? How to use resource in this case?

**Comment by seanlinsley** [comment]
Sorry about that. I updated the example code in b20fd04e992f721f49557f4dc59c7da3a732ba68
