### ISSUE TITLE
What is supposed to be returned by ActiveAdmin::Component#build ?

### ISSUE THREAD

**Issue by simon0191** [activeadmin/activeadmin#4269]
I want to create a custom index page. I saw your docs, specifically this page:
https://github.com/activeadmin/activeadmin/blob/master/docs/3-index-pages/custom-index.md#custom-index

I understand that I have to override `build`, but I don't understand what's supposed to be done inside `build` nor what's supposed to be returned.

Could you write a more illustrative example of how to implement `build` and what's the expected return value?

---

Some context:

I want to add a custom filter in top of the index table. Something like:

``` erb
<%= form_tag(some_path) %>
  <%= text_field_tag :query %>
  <%= submit_tag :submit %>
<% end %>
```

**Comment by kashifnaseer** [comment]
Any update on this ? I'm having same issue.

I'm trying to have 3 views on Index page, Grid, Table and Map. 

Map is a custom view. When i click on Map button, it doesnt show any record on Index page. though I've following code for map views

    index as: ActiveAdmin::Views::IndexAsMap do

     column (:title)
      column (:company)
      column "Plot", :plot_number
    end

**Comment by varyonic** [comment]
build returns an [Arbre::Component](https://github.com/activeadmin/arbre/)  There are various examples in the [ActiveAdmin source](https://github.com/activeadmin/activeadmin/tree/master/lib/active_admin/views/components)  Once you understand Arbre you can understand how the [index views](https://github.com/activeadmin/activeadmin/tree/master/lib/active_admin/views) are built.
