### ISSUE TITLE
Can't login. 

### ISSUE THREAD

**Issue by iancui** [activeadmin/activeadmin#4271]
I use the default User and Password:
> admin@example.com
> password

it did't work.
what' wrong with me?

**Comment by lubc** [comment]
Same problem for me. The admin_users table is empty.

**Comment by lubc** [comment]
Any suggestion? Thanks.

**Comment by corydiamand** [comment]
As a workaround you can create an Admin User from the rails console with -

AdminUser.create(:email => 'admin@example.com', :password => 'password')

**Comment by lubc** [comment]
Yes, I did it but I only could see the dashboard, the other pages in the admin gave me an error. This works for you @corydiamand ?

**Comment by iancui** [comment]
@corydiamand Thanks for your suggestion，I will try it.

**Comment by iancui** [comment]
@corydiamand The code line works for me ,but I find another code also works. Maybe it is more simpler.
`rake db:seed`

**Comment by corydiamand** [comment]
@iancui - Yours is a better way! :+1:
