### ISSUE TITLE
Cassandra model (Cequel gem) with active_admin

### ISSUE THREAD

**Issue by dksharp** [activeadmin/activeadmin#4274]
Hi,
I am trying to add a Cassandra ( with Cequel gem) model in active_admin resources but its throwing error on loading,

undefined method `quote_column_name' for #<Cequel::Metal::Keyspace:0x00000006dba0c8>

any help ?

**Comment by timoschilling** [comment]
ActiveAdmin don't support other ORM's then ActiveRecord and Mongoid.
