### ISSUE TITLE
Email/logout, add new link and filters disappear after adding image

### ISSUE THREAD

**Issue by KikoH** [activeadmin/activeadmin#4278]
I am using ActiveAdmin with rails 4 and it is working fine. When I add an item, I am taken to the index page listing the new item/items and the filters on the right side. Also, there are the email and logout links at the top right.

My issue is when I add an item with an image the filters, email and logout links disappear.

If I delete the item with the image they appear again. I can add /new to the url and it still takes me to the form but I am trying to figure out why adding a picture removes the links.

here is my form:
```ruby
form(:html => { :multipart => true }) do |f|
f.inputs "Size" do
  f.input :title
  f.input :description
  f.input :price
  f.input :image, :as => :file
  f.input :developer_days
  f.input :designer_days
  f.input :name
end
f.actions
end
```

I just can't figure out why this happens.

**Comment by timoschilling** [comment]
Can you add a screenshot of both states please

**Comment by KikoH** [comment]
Sure.
As you can see the exact same item one with image and one without. Same URL for both as well.

![1](https://cloud.githubusercontent.com/assets/8993460/12476253/ee645770-c01f-11e5-8e82-5d1243c0fdd9.png)
![2](https://cloud.githubusercontent.com/assets/8993460/12476252/ee5f273c-c01f-11e5-97fa-88135044cc01.png)

**Comment by timoschilling** [comment]
Can take a look on the html source code in browser, does the filter really not exist?

**Comment by KikoH** [comment]
It exists.

![screen shot 2016-01-21 at 1 05 55 pm](https://cloud.githubusercontent.com/assets/8993460/12481265/ca4c672c-c03f-11e5-9391-6e9557958e51.png)

**Comment by timoschilling** [comment]
I think the problem is the with of the image col. do you really need the full path there?

**Comment by KikoH** [comment]
No I don't think so. Change the name of the image you mean?

**Comment by timoschilling** [comment]
show a link tag or just the file name without path or just a open link, that should solve the problem

**Comment by KikoH** [comment]
I did that and it solved the problem. Can you explain why this was happening?

**Comment by timoschilling** [comment]
I think thats a css problem

**Comment by KikoH** [comment]
Thank you Tim.
