### ISSUE TITLE
Use input type="password" for devise views

### ISSUE THREAD

**Issue by arogachev** [activeadmin/activeadmin#4280]
It will be more reliable if password field inputs in devise views will have `type="password"` by default:

- https://github.com/activeadmin/activeadmin/blob/master/app/views/active_admin/devise/sessions/new.html.erb
- https://github.com/activeadmin/activeadmin/blob/master/app/views/active_admin/devise/registrations/new.html.erb
- https://github.com/activeadmin/activeadmin/blob/master/app/views/active_admin/devise/passwords/edit.html.erb

Currently it's regular input that means secret information is available for everyone around you while you're typing password.

And there is no way now to configure that, except overriding the whole form.

**Comment by timoschilling** [comment]
They have the `type="password"` attribute by deafult, it is added by formtastic.
![](https://cloud.githubusercontent.com/assets/165599/12506762/88f0aba0-c0f1-11e5-8796-415046f985b0.jpg)

**Comment by arogachev** [comment]
Sorry, maybe it's because of using Rails 5.0.0.beta1.

**Comment by timoschilling** [comment]
report that to formtastic or rails
