### ISSUE TITLE
Mysql2::Error: Specified key was too long; max key length is 1000 bytes: CREATE  INDEX 

### ISSUE THREAD

**Issue by phenomen2277** [activeadmin/activeadmin#4281]
If I pass  ( :options => "ENGINE=MyISAM" ) to create_table() in my migration files. I got Errors, telling my that the index names generated by active_admin are too long "when running rake db:migrate". I know that it is a MySQL issue. But if you could do something about it, it would be nice :)

Mysql2::Error: Specified key was too long; max key length is 1000 bytes: CREATE  INDEX `index_active_admin_comments_on_resource_type_and_resource_id`  ON `active_admin_comments` (`resource_type`, `resource_id`)

**Comment by seanlinsley** [comment]
Assuming you use numeric keys for all models that you might be leaving an Active Admin comment on, you can get around this by changing [`resource_id`](https://github.com/activeadmin/activeadmin/blob/master/lib/generators/active_admin/install/templates/migrations/create_active_admin_comments.rb#L6) from `string` to `integer`. That's of course assuming the column with a value that's too long is `resource_id` and not `resource_type`.

**Comment by dmitry** [comment]
BTW why do you use MyISAM?

**Comment by seanlinsley** [comment]
Closing due to a lack of activity
