### ISSUE TITLE
default input field not respected on has_many

### ISSUE THREAD

**Issue by lowellmower** [activeadmin/activeadmin#4283]
Not sure this is an 'issue' per-say, however, when generating a form with a has_many association to a resource which has a text field, the form input is not automatically generated as a larger input field, rather, it is generated as if it were a string input field. One must pass the option of `as: :text` on the has_many portion of a form to gain the default styling of a larger text field.

``` ruby
    form do |f|

        f.inputs "Report Info" do
            f.input :title
            f.input :sub_title
            f.input :slug
            f.input :meta
            f.input :published
            f.input :publish_date
            f.input :post_author, label: "Author", collection: PostAuthor.all.order(:last_name).map{ |a| ["#{a.first_name} #{a.last_name}", a.id] }, include_blank: false
            f.input :image_id, label: "Header Image", as: :rich_picker, config: { scoped: 'reports', hidden_input: true}, hint: "Use image ~1000x300px"
        end

        f.inputs "Visible Tabs" do 
            f.input :overview  <=# This is :text in DB and defaults to larger input field
            f.input :key_findings <=# This is :text in DB and defaults to larger input field
            f.input :participating_schools  <=# This is :text in DB and defaults to larger input field
            f.input :methodology  <=# This is :text in DB and defaults to larger input field
        end

        f.inputs "Results" do
            f.has_many :insights, allow_destroy: true, heading: false do |ri|
                ri.input :title, label: "Title"
                ri.input :body, label: "Body", as: :text  <=# This is :text in DB but doesn't default
            end
        end

        f.actions
    end
```

associated models:

``` ruby
class Report < ActiveRecord::Base
    belongs_to :post_author
    has_many :report_insights
    has_many :insights, through: :report_insights
    has_one :rich_rich_files, primary_key: :image_id, foreign_key: :id, class_name: RichRichFile

    accepts_nested_attributes_for :insights, allow_destroy: true
    ...
end
```

``` ruby
class Insight < ActiveRecord::Base
  has_many :report_insights
  has_many :reports, through: :report_insights
end
```

``` ruby
class ReportInsight < ActiveRecord::Base
    belongs_to :report
    belongs_to :insight
    ...
end
```

Can't seem to find where in the `FormBuilder` class's `has_many` method this may be happening, if that is in fact even the issue, but would be happy to try and make a PR if this is desired default behavior. Thoughts?

**Comment by seanlinsley** [comment]
Merging this into #3834, as it seems to be the same problem.

**Comment by seanlinsley** [comment]
nevermind, misread the ticket :sweat_smile:

**Comment by Fivell** [comment]
@lowellmower , did you managed to resolve somehow with this?

**Comment by lowellmower** [comment]
@Fivell - I did not as I didn't receive conformation of this as a "bug." Ultimately, one can achieve one's ends with verbosity, e.g. `as: :text`. If I can get confirmation of the default behavior, which I assume is to default to the larger text field on the column of type `text` without having to expressly say so, again, I'd be happy to take a crack at it.

**Comment by Fivell** [comment]
@lowellmower , according to https://github.com/justinfrench/formtastic#the-available-inputs

if columns type is text, it should be displayed with textarea by default,  if it doesn't looks like it is bug.

**Comment by zorab47** [comment]
I'm unable to reproduce this issue on ActiveAdmin 1.2.1 and Rails 5.1. If this is still an issue please reopen @lowellmower.

Configuration I used:

```ruby
class Report < ApplicationRecord
  has_many :insights
  accepts_nested_attributes_for :insights
end

class Insight < ApplicationRecord
  belongs_to :report
end

ActiveAdmin.register Report do
  form do |f|
    f.inputs "Report Info" do
      f.input :name
    end

    f.inputs "Results" do
      f.has_many :insights, allow_destroy: true, heading: false do |ri|
        ri.input :name
        ri.input :body
      end
    end

    f.actions
  end
end
```

![image](https://user-images.githubusercontent.com/25094/35827807-03c7ca52-0a83-11e8-9519-8b94f293c6eb.png)
