### ISSUE TITLE
Formtastic's input subclassing feature messes with ActiveAdmin::Filters::FormBuilder

### ISSUE THREAD

**Issue by faucct** [activeadmin/activeadmin#4284]
Hello, I am trying to use the input subclassing feature from formtastic: https://github.com/justinfrench/formtastic#changing-existing-input-behavior
I wish it would only be applied in new/edit forms, but due to `input_namespaces` configuration the `ActiveAdmin::Filters::FormBuilder` has, my overridden inputs take precedence over `ActiveAdmin::Inputs::Filters` ones too:

``` ruby
module ActiveAdmin
  module Filters
    # This form builder defines methods to build filter forms such
    # as the one found in the sidebar of the index page of a standard resource.
    class FormBuilder < ::ActiveAdmin::FormBuilder
      include ::ActiveAdmin::Filters::FormtasticAddons
      self.input_namespaces = [::Object, ::ActiveAdmin::Inputs::Filters, ::ActiveAdmin::Inputs, ::Formtastic::Inputs]

      # TODO: remove input class finders after formtastic 4 (where it will be default)
      self.input_class_finder = ::Formtastic::InputClassFinder
      ...
    end
  end
end

module ActiveAdmin
  class FormBuilder < ::Formtastic::FormBuilder
    self.input_namespaces = [::Object, ::ActiveAdmin::Inputs, ::Formtastic::Inputs]

    # TODO: remove both class finders after formtastic 4 (where it will be default)
    self.input_class_finder = ::Formtastic::InputClassFinder
    ...
  end
end
```

**Comment by Fivell** [comment]
@faucct , try to configure input namespace by your own.

something like 
```
ActiveAdmin::FormBuilder.input_namespaces = [:MyFormInputs, ::Object, ::ActiveAdmin::Inputs, ::Formtastic::Inputs]
```
and place your extended inputs to ```MyFormInputs``` namespace

**Comment by faucct** [comment]
This would be a solution, though then there is no sense for having `::Object` inside any of input namespaces for both regular and filters `FormBuilder`. What do you think about them having the same `input_namespaces`, but the `Filters::FormBuilder` using an `input_class_finder` which searches for them like this - `"#{as}FilterInput"`?
