### ISSUE TITLE
Default admin users/passwords will not work (new)

### ISSUE THREAD

**Issue by TeamRainless** [activeadmin/activeadmin#4286]
Hey. I've been running activeadmin for years on my old app, but I'm just creating a new rails 4.2 app from scratch and I've installed activeadmin, and migrated and seeded the database... but it simply won't let me login (gives me the "invalid password" thing).

Below is the complete error:

    Processing by ActiveAdmin::Devise::SessionsController#create as HTML
      Parameters: {"utf8"=>"✓", "authenticity_token"=>"edCCf/+TsRq7AVXY8/xMW9ytFvb/9Rk1wNte3EC9CMvrPAuiLdEtzePXlsZ+QV1Md2jbcKFgojg72uLtya996g==", "user"=>{"email"=>"admin@example.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Login"}
      User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["email", "admin@example.com"]]
    Completed 401 Unauthorized in 10ms (ActiveRecord: 1.0ms)

And in the off chance you want to see the rest:

    Processing by ActiveAdmin::Devise::SessionsController#new as HTML
      Parameters: {"utf8"=>"✓", "authenticity_token"=>"edCCf/+TsRq7AVXY8/xMW9ytFvb/9Rk1wNte3EC9CMvrPAuiLdEtzePXlsZ+QV1Md2jbcKFgojg72uLtya996g==", "user"=>{"email"=>"admin@example.com", "password"=>"[FILTERED]", "remember_me"=>"0"}, "commit"=>"Login"}
      Rendered /Users/rainless/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-557d143e8a48/app/views/active_admin/devise/shared/_links.erb (2.2ms)
      Rendered /Users/rainless/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-557d143e8a48/app/views/active_admin/devise/sessions/new.html.erb within layouts/active_admin_logged_out (23.9ms)
    Completed 200 OK in 194ms (Views: 119.7ms | ActiveRecord: 0.0ms)

The user exists, I can only imagine that the password is, in fact, "password"... but just in case I also created my own admin user and couldn't login with that either.  I even went so far as to make a user controller:

    class UsersController < ApplicationController
      def create
        User.create(user_params)
      end
    
      def user_params
        params,require(:user).permit(:email, :password, :password_remember, :id)
      end
    end

...to specifically allow email and password and id and everything else... no avail.

Also did everything this guy did:

http://stackoverflow.com/questions/25498878/cant-login-to-activeadmin

Absolutely nothing has helped.

Rails version is 4.2.5

ActiveAdmin is: activeadmin (1.0.0.pre2 557d143)
Devise is: devise (3.5.5)

Please help

**Comment by TeamRainless** [comment]
Sooo... People have been having this problem over and over again over the years... but, for some odd reason, nobody ever updates the installation docs or the readme.

The problem is that the user MUST exist in both Users and AdminUsers.  I didn't have this problem when I setup ActiveAdmin the first time because there was simply a boolean in the guide I was using where you could check or uncheck if a user was an admin user or not. (It was more difficult to setup but a MUCH more sensible way of doing things.

Anyway you just need to go to a rails console and do this:

    User.create :email => 'abc1@example.com', :password => 'password', :password_confirmation => 'password'

If you follow the installation guide... as is... it simply won't work. You'll do your activeAdmin install and not be able to login.  Why not, if it knows you're using Devise, seed both the AdminUser and User tables at the same time?

**Comment by seanlinsley** [comment]
The documentation clearly says to run `rake db:seed`: https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md#setting-up-active-admin

**Comment by seanlinsley** [comment]
The documentation also specifies how to use an existing `User` class instead of creating an `AdminUser` class:
```
rails g active_admin:install              # creates the AdminUser class
rails g active_admin:install User         # creates / edits the class for use with Devise
rails g active_admin:install --skip-users # skips Devise install

**Comment by seanlinsley** [comment]
https://github.com/activeadmin/activeadmin/blob/bf29c0e6ac786bbaa98ce08d3d5c6074e0cbc948/lib/generators/active_admin/devise/devise_generator.rb#L59

**Comment by TeamRainless** [comment]
You see... this is the problem... You aren't actually listening:

WAAAY up at the top of my issue posting I mention that I *did* seed the database. The problem is that this:

After installing the gem, you need to run the generator. By default we use Devise, and the generator creates an AdminUser model. If you want to create a different model (or modify an existing one for use with Devise) you can pass it as an argument. If you want to skip Devise configuration entirely, you can pass --skip-users.

rails g active_admin:install              # creates the AdminUser class
rails g active_admin:install User         # creates / edits the class for use with Devise
rails g active_admin:install --skip-users # skips Devise install
--------------------------------------------------------

...entire part of the Readme is poorly-written and leads to confusion. (Don't take my word for it. Google: "ActiveAdmin invalid password". People keep having this same problem.)

If you do:
rails g active_admin:install and then rake db:seed

Then active admin will create an AdminUser.

But if you do:
rails g active_admin:install User and then rake db:seed

Then activeadmin will NOT create the user that you need to login. That's the problem.

So then you continue to follow the instructions and you get to localhost:3000/admin and... you can't log in.

The wording... is off.  To put it nicely.

**Comment by seanlinsley** [comment]
Can you provide a set of steps (starting from a brand new Rails repo) to reproduce this error?

This works fine for me:
```sh
rails new aa_test
cd aa_test
echo "gem 'activeadmin', github: 'activeadmin'" >> Gemfile
echo "gem 'devise'" >> Gemfile
bundle
rails g active_admin:install User
rake db:migrate
rake db:seed

rails runner "puts User.count" # prints: 1
```

I'm then able to run `rails server` and log in successfully at <http://localhost:3000/admin>

By the way, [Markdown](https://guides.github.com/features/mastering-markdown/) allows you to visibly quote text that you copied from somewhere else. Doing this makes it easier to read.

**Comment by TeamRainless** [comment]
It's really just a question of wording I guess. Because all three of the lines are together (especially if you're installing a lot of other gems and reading a lot of other installation guides at once) the implication is that you are to run all both, if not all three lines. Thus this is how I (and I suspect everyone else) ran into the error:

>> rails new aa_test
>> cd aa_test
>> echo "gem 'activeadmin', github: 'activeadmin'" >> Gemfile
>> echo "gem 'devise'" >> Gemfile
>> bundle
>> rails g active_admin:install
>> rails g active_admin:install User
>> rake db:migrate
>> rake db:seed

Creates the seed for AdminUser... but not for User. (Of course NOW I realize it was a "one-or-the-other" kinda thing...). If you could give me instructions on uninstalling Activeadmin I'd be more than happy to recreate the steps and report back to you.

I think it would be easier to understand with a few spaces. Something like:

>> If you just want an AdminUser Class you can run: 
>> rails g active_admin:install 
>>
>> Running the following command will either create a new Devise User class or modify an existing one:
>> rails g active_admin:install User

**Comment by seanlinsley** [comment]
That makes sense. Sorry that the documentation wasn't clearer. I just updated it to clarify that only one of the three options should be run: cc85abc99a221b84ae67625843b7e4cb7b850b1e. Let me know if that works for you.

> also I should note that I ran rake db:seed about a hundred times and each time it only created an AdminUser

That's configured by your `db/seeds.rb` file. What code is in it?

If you want to start from scratch, you can remove these files & folders:
- app/admin/*
- app/assets/javascripts/active_admin.js.coffee
- app/assets/stylesheets/active_admin.scss
- config/initializers/active_admin.rb

Also be sure to remove any code in `db/seeds.rb` that Active Admin added.

You can then create a migration to remove the `admin_users` and `active_admin_comments`

**Comment by TeamRainless** [comment]
For point 2 you should mention that... it's not only for an existing user class... but if you don't have one it will be created. Something like:

>> If you want to create or use an existing User class 
>> rails g active_admin:install User

Other than that it's perfect now.

As for what's in my seeds.rb file:

>> AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

Just that. 

I can imagine some instances where having both admin users and regular users could be helpful. (A blog situation or even a newspaper, for example, where you have both authors and commenters as registered users with completely different parameters for each.) I've often wondered about using Activeadmin for both from both a user and admin perspective with each having access to different parameters... but I guess that's a question for another day.

At any rate I can't quite figure out why it only seeded the AdminUser. Maybe it checked to see if there was anything seeded at all?

But I'm sure that's what was causing all the trouble for all those Stackoverflow threads I dug up.

Thanks for the quick responses and good luck on 1.0

**Comment by w33zy** [comment]
Thanks @TeamRainless I just ran into this issue today.

**Comment by TeamRainless** [comment]
No problem.
