### ISSUE TITLE
Rails 5 beta 1

### ISSUE THREAD

**Issue by ahmetabdi** [activeadmin/activeadmin#4291]
Is the latest activeadmin working on rails 5 beta1? or do we need to point to the master branch?

Latest master fails for me:
`rails g active_admin:install User`

`ruby-2.3.0/bundler/gems/activeadmin-ca94d1ccb189/lib/generators/active_admin/devise/devise_generator.rb:22:in rescue in install_devise': You provided devise 4.0.0.pre.dev but we need: ~> 3.2. If you don't want to use devise, run the generator with --skip-users. (ActiveAdmin::GeneratorError)`

Error is failing here https://github.com/activeadmin/activeadmin/blob/master/lib/generators/active_admin/devise/devise_generator.rb#L20

**Comment by asingla** [comment]
I am facing the same issues

**Comment by ahmetabdi** [comment]
hopefully It's just a in need of updating the dependancies to point to the latest version of devise

**Comment by timoschilling** [comment]
closed as double of #4177

**Comment by jstnn** [comment]
i've followed this guide to make it work with rails5: https://rrott.com/blog/ror/rails-5-api-with-activeadmin-integration.html
