### ISSUE TITLE
Rails 4.2.5 & ActiveAdmin 1.0.0.pre2 inside mountable engine

### ISSUE THREAD

**Issue by estum** [activeadmin/activeadmin#4294]
After upgrading to 4.2.5, I've got a headache with missing routes inside mountable engine (non-isolated). As early, I've tried to include `Admin::Engine.routes.url_helpers` every-fckn-where, but nothing happens, and finally I found the solution:

If someone have the similar setup and can't upgrade rails, you should just initialize AA with:

```ruby
ActiveAdmin::BaseController.extend ::AbstractController::Railties::RoutesHelpers.with(Admin::Engine.routes)
```

**Comment by Fivell** [comment]
@estum , can you provide step-by-step instruction how to move resources to mountable engine ?

**Comment by estum** [comment]
@fivell, well, I'll try...

1. Create the engine in your project:
    
    ```
    $ rails plugin new admin --mountable --skip-bundle --skip-gemfile
    ```
    
    It'll create the `Admin` engine in the `admin` dir.

2. In the project's `Gemfile`:
    
    ```ruby
    gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin.git', require: false
    gem 'admin', path: 'admin'
    ```
    
    Add dependencies to the `admin/admin.gemspec` file:
    
    ```ruby
    s.add_dependency 'activeadmin'
    ```
    
    And don't forget to require them in the `admin/lib/admin.rb`:
    
    ```ruby
    require 'activeadmin'
    require 'admin/engine'

    module Admin
    end
    ```

3. Move ActiveAdmin resources to the `admin/app/admin` path

4. Edit the `admin/config/routes.rb`
    
    ```ruby
    Admin::Engine.routes.draw do
      devise_for :admin_users
      ActiveAdmin.routes(self)
    end
    ```
    
    And mount the engine in the `config/routes.rb`:
    
    ```ruby
    mount Admin::Engine => '/'
    ```
    
5. Create an initializer in the `admin/config/initializers/active_admin.rb` path:

    ```ruby  
    ActiveAdmin.setup do |config|
      # add engine's load path
      config.load_paths = [Admin::Engine.root.join("app/admin").to_s]
      config.default_namespace = :admin
      config.namespace :admin do |admin|
        # ...
      end
    end
    
    # Hook ActiveAdmin url helpers to apply engine's routes
    require 'active_admin/helpers/routes/url_helpers'
    ActiveAdmin::Helpers::Routes::UrlHelpers.include(Admin::Engine.routes.url_helpers)
    ActiveAdmin::Helpers::Routes.extend(Admin::Engine.routes.url_helpers)
    ActiveAdmin::BaseController.extend(AbstractController::Railties::RoutesHelpers.with(Admin::Engine.routes))
    ActiveAdmin::Devise::SessionsController.include(Admin::Engine.routes.url_helpers)
    ```

6. That is. You should declare resources as before (`admin/app/admin/users.rb`): 
    
    ```ruby
    ActiveAdmin.register User do
      # ...
    end
    ```
    
    When you want to make link to some admin's path from the engine:
    
    ```ruby
    link_to user.name, [:admin, user]
    
    # to custom action:
    link_to "Ban", ban_admin_user_path(user)
    ```

**Comment by seanlinsley** [comment]
Sounds like this is @estum reporting on what worked for them, not asking for support.

@estum thanks for posting your solution here. If you'd like, you can open a PR to update the documentation.

**Comment by risinglf** [comment]
@estum @seanlinsley I've tried your solution, but it doesn't work...

When I try to go to the dashboard page, I always have this error:

`uninitialized constant Admin::Admin`

it looks like it's searching for a nested Admin module. If I add (just to try) this in lib/admin.rb:

```
module Admin
    module Admin
    end
end
```

the error become `uninitialized constant Admin::Admin::DashboardController`

any idea?

**Comment by ardation** [comment]
@risinglf I got to the bottom of this in the end when I was trying to do the same thing.

In my engine.rb file I had been specifying `isolate_namespace Admin` which was causing the routes to register as:

```
admin_root GET    /admin(.:format)    admin/admin/dashboard#index
```

Once I had removed this it worked successfully. Hope this helps the next person who is trying to get activeadmin working inside an engine!
