### ISSUE TITLE
Actions :all, except: [:create] undefined method

### ISSUE THREAD

**Issue by jonathanpa** [activeadmin/activeadmin#4296]
Hi,
By trying to restrict my routes with `actions :all, except: [:create]`, I got a `undefined method admin_order_line_items_path` for `ActiveAdmin::Helpers::Routes:Module` on `lib/active_admin/resource/routes.rb` line 46 https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource/routes.rb#L46

Don't know if I am wrong by using `actions` as I did or it's a restriction or a bug.

**Comment by timoschilling** [comment]
Please provide a full stacktrace and the related url.

**Comment by seanlinsley** [comment]
Closing due to a lack of response.
