### ISSUE TITLE
Missing field from model

### ISSUE THREAD

**Issue by tylercollier** [activeadmin/activeadmin#4298]
I'm using Active Admin (directly from github in Gemfile, so commit a6f6794c0fba). It's been working fine for a long time. Today I ran a migration to add a field to my Agent model. That field is not showing up in any of the active admin parts for that model (index, form, filter). I'm confident that Active Admin is connecting to the correct database, because if I use the following code in `app/admin/agent.rb`, it DOES show up, with correct values from the database:

```
index do
  selectable_column
  Agent.column_names.each do |c|
    column c.to_sym
  end
  default_actions
end
```

But if remove that code (meaning the columns should be the default), I do not see my field/column. I must do a similar trick on the form inputs.

Any ideas?

**Comment by tylercollier** [comment]
I just added another field to the table in the database. The new field showed up as usual, without me having to do anything special.

In case it helps, the 'special' field, that didn't show up, was named `idx_id`. The one that showed up fine was `email_cc`.

**Comment by seanlinsley** [comment]
Currently we use `content_columns` to decide which attributes to display:
```ruby
lib/active_admin/csv_builder.rb:
   23        new resource: resource do
   24          column :id
   25:         resource.content_columns.each { |c| column c.name.to_sym }
   26        end
   27      end

lib/active_admin/filters/resource_extension.rb:
  140        # Returns a default set of filters for the content columns
  141        def default_content_filters
  142:         if resource_class.respond_to? :content_columns
  143:           resource_class.content_columns.map{ |c| c.name.to_sym }
  144          else
  145            []

lib/active_admin/views/index_as_table.rb:
  234            selectable_column
  235            id_column if resource_class.primary_key # View based Models have no primary_key
  236:           resource_class.content_columns.each do |col|
  237              column col.name.to_sym
  238            end
```

`content_columns` is defined by Rails, and excludes any attributes with `_id` in the name:
```ruby
def content_columns
  @content_columns ||= columns.reject { |c| c.name == primary_key || c.name =~ /(_id|_count)$/ || c.name == inheritance_column }
end
```

That's not the best though. I think a more robust option would map through the associations the model has, and only exclude the attributes ending in `_id` if they're a foreign key on an association.

**Comment by tylercollier** [comment]
Thanks for the great diagnosis. In my case, `idx_id` is not a foreign key. Well, it technically is, but not one known to Rails. So that would explain it.

You must have something special for associations. Because `content_columns` would exclude them right, since it excludes all `_id` columns.

**Comment by timoschilling** [comment]
This is a not solvable edge case. And there is a workaround.

**Comment by tylercollier** [comment]
The edge case is naming fields with `_id`. Is it so edge to name references to external resources that way? Perhaps mention something in the docs?

**Comment by timoschilling** [comment]
You can simply write your own index and form and your problem is solved!
