### ISSUE TITLE
Changes AA sources in dev mode causes cyclic reloading

### ISSUE THREAD

**Issue by DmitryRibalka** [activeadmin/activeadmin#4301]
Even don't know how to explain my problem. I can see queries in log to db and rendered page, but browser still waits it. AA continues reloading its code, i could understand that seeing the queries for filters. Any thoughts?

AA 1.0.0pre2 (master) ruby 2.2.2 rails 4.2.5.1

**Comment by timoschilling** [comment]
Please post the logs

**Comment by DmitryRibalka** [comment]
@timoschilling what logs? there are only sql logs to my db.

**Comment by timoschilling** [comment]
The logs of the rails console

**Comment by DmitryRibalka** [comment]
@timoschilling I cannot proved them, (NDA and privacy sensitive information), but there is only queries for filters, and AA loads the again and again (recursion).  It looks like this flow:
1. It loads filters 
2. It makes queries from show form
3. Renders form
4. Loads filters again
5. Go p.3
6. Browser waits infinitely
If I stop the process browser shows just part of rendered page (mostly w/o css)

On any changing of code I have to restart the server.

**Comment by DmitryRibalka** [comment]
@timoschilling Might loading assets cause sources reloading?
I see in logs this picture:

```
....
Completed 200 OK in 640ms (Views: 573.5ms | ActiveRecord: 21.9ms | SQL count: 29)


Started GET "/assets/jquery.minicolors.self-9ff7744bb0c147c6a6261938fdbb0b5d25e83071fc55b3c4e9a996a0fb7a125a.css?body=1" for 127.0.0.1 at 2016-02-15 20:58:18 +0200
  AdminUser Load (0.5ms)  SELECT `admin_users`.* FROM `admin_users` /*application:SftyHomeNewRails,line:/app/admin/safe4_soap_log.rb:6:in `block in <top (required)>'*/
   (0.2ms)  SELECT `devices_tags`.`tag` FROM `devices_tags` /*application:SftyHomeNewRails,line:/app/admin/tag.rb:9:in `block in <top (required)>'*/
+more sql requests for filters....
...

Started GET "/assets/progress-bar.self-f95e402b5e8540421568432bdf07a4a15c8586522ec53178fa72de9087be4763.css?body=1" for 127.0.0.1 at 2016-02-15 20:58:20 +0200
  AdminUser Load (0.5ms)  SELECT `admin_users`.* FROM `admin_users` /*application:Rails,line:/app/admin/soap_log.rb:6:in `block in <top (required)>'*/
   (0.2ms)  SELECT `devices_tags`.`tag` FROM `devices_tags` /*application:Rails,line:/app/admin/tag.rb:9:in `block in <top (required)>'*/
+more sql requests for filters....
....


```
and repeats for all assets (40+) and becomes slower and slower...

**Comment by seanlinsley** [comment]
@DmitryRibalka unfortunately if you're not able to post information publicly, we're not able to help you. If you are able to pay for assistance, I'd be willing to sign the NDA and help you directly.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
