### ISSUE TITLE
Comments build_comment and the delete link

### ISSUE THREAD

**Issue by lrcrews** [activeadmin/activeadmin#4303]
The comment UI generated by the build_comment method (https://github.com/activeadmin/activeadmin/blob/b44b4f4896ef78b50c35c82a343356d68b937cde/lib/active_admin/orm/active_record/comments/views/active_admin_comments.rb#L31) will add in a "Delete Comment" `if authorized?(ActiveAdmin::Auth::DESTROY, comment)`, however, if I remove the `:destroy` ability:

```
ActiveAdmin.register ActiveAdminComment, as: "Comments" do

    actions :all, except: [ :destroy ]

end
```

The "Delete Comment" is still shown.  (doing the above does properly remove the path, the delete link from the index page, and the delete button from the show page).

**Comment by seanlinsley** [comment]
@lrcrews this is what we do in other parts of the code, if you'd like to open a PR to fix this: https://github.com/activeadmin/activeadmin/blob/b44b4f4896ef78b50c35c82a343356d68b937cde/lib/active_admin/batch_actions/resource_extension.rb#L68

**Comment by javierjulio** [comment]
Closing out as stale. We'll definitely consider a PR if you submit one! Thanks.
