### ISSUE TITLE
Default CSV builder do not use col_sep csv option

### ISSUE THREAD

**Issue by fabien-michel** [activeadmin/activeadmin#4306]
A customized col_sep option in `initializer/active_admin.rb`

      config.csv_options = { col_sep: ';' }

Is not used in default csv export from index page

**Comment by seanlinsley** [comment]
It works for me. Please make sure you're using a version of Active Admin that supports that feature.

Also make sure to restart Rails when changing any files in the `config` folder, otherwise your changes won't be used.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
