### ISSUE TITLE
Setting env in rspec

### ISSUE THREAD

**Issue by amygimma** [activeadmin/activeadmin#4313]
I do not want to show the delete action in production for some models, so I wrote a test to drive: 
```ruby
  context "app is running in the production environment" do
    scenario "admin cannot delete a practice" do
      allow(Rails).to receive(:env).
        and_return(ActiveSupport::StringInquirer.new("production"))
      admin = create(:admin)
      practice = create(:practice)

      sign_in admin
      visit admin_practice_url(practice)

      expect(page).not_to have_content("Delete")
    end
  end

  context "app is NOT running in the production environment" do
    scenario "admin can delete a practice" do
      admin = create(:admin)
      practice = create(:practice)

      sign_in admin
      visit admin_practice_url(practice)

      expect(page).to have_content("Delete")
    end
  end
```

And ended up with this implementation:

```ruby
ActiveAdmin.register Practice do
  menu priority: 0

  if Rails.env.production?
    actions :index, :show, :new, :create, :update, :edit
  end
```

The test won't pass because ActiveAdmin is loaded before `allow(Rails).to receive(:env).and_return(ActiveSupport::StringInquirer.new("production"))` is called. How can I stub the Rails environment earlier to make my tests valid?

**Comment by seanlinsley** [comment]
A clearer way to exclude the delete action is like this:
```ruby
actions :all, except: :destroy
```

But instead of disabling the delete action in production, you should disable it based on user permissions. Here's our documentation on that: https://github.com/activeadmin/activeadmin/blob/master/docs/13-authorization-adapter.md

You can use the built-in authorization adapter, or you can use Draper or Pundit.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
