### ISSUE TITLE
Menu sorting does not work with 10, 20, 30 as priorities

### ISSUE THREAD

**Issue by besi** [activeadmin/activeadmin#4319]
Amongst others I have **Merchants** and **Products** in my ActiveAdmin Setup.

I set the priorities like so:

```ruby
# merchants.rb
ActiveAdmin.register Merchant do

  menu priority: 10
...
end
```

```ruby
# products
ActiveAdmin.register Product do

  menu priority: 20
end
```

However, my menu ends up looking like this:

![screenshot](https://cloud.githubusercontent.com/assets/160412/13062555/c890394a-d43f-11e5-8ab7-eccc166c4bff.png)

However, when I change the priorities to `1` and `2` then it works fine:

![it works](https://cloud.githubusercontent.com/assets/160412/13062575/f57fcce0-d43f-11e5-9b61-b667b0fa7d57.png)

I would expect the same behaviour in both cases and **Merchants** should appear first.

I am using `activeadmin (1.0.0.pre2)`

**Comment by superbilk** [comment]
I used a vanilla Rails 5.beta2 app, added only activeadmin, two empty models (Merchant and Product), your code and disabled to show comments in menu (config.show_comments_in_menu = false).

I can not reproduce your problem.

The activeadmin code is pretty straightforward on sorting the menu items (https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/menu.rb#L71)

Could you check again with a simple setup (as mine) or provide more code?
Maybe debugging the options step by step might bring some insight.
Also make sure there is nothin with other models or ActiveAdmin.setup that might interfere.

**Comment by besi** [comment]
Ok I did dive into that again. In Products I had the `menu` defined twice. So the priority of `10` was overwritten by the second value.

Thanks for your help!
