### ISSUE TITLE
has_many problem; undefined method 'new_record?'

### ISSUE THREAD

**Issue by nickpellant** [activeadmin/activeadmin#432]
I'm trying to customise a ActiveAdmin form for a Recipe model that has a has_many relationship with Step.

``` ruby
class Recipe < ActiveRecord::Base
  has_many :steps
end

class Step < ActiveRecord::Base
  acts_as_list :scope => :recipe

  belongs_to :recipe
end
```

I have the following in my ActiveAdmin file with relation to this:

``` ruby
form do |f|
  f.has_many :steps do |ing_f|
    ing_f.inputs
  end
end
```

The following error is thrown when I try to load the form:

```
undefined method `new_record?' for nil:NilClass
```

I've isolated it so far to the has_many method but I'm lost past this. Any advice and help would be appreciated!

**Comment by tiagodll** [comment]
I wish I could upvote this :+1:

**Comment by bobzhen** [comment]
thank you!

**Comment by dkniffin** [comment]
This should be documented under the "Nested Resources" section of this page: https://activeadmin.info/5-forms.html

**Comment by thisismydesign** [comment]
There should be a complete working example in the docs imo.
