### ISSUE TITLE
Helper method

### ISSUE THREAD

**Issue by kvokka** [activeadmin/activeadmin#4320]
Hello, I'm trying to realize helper for ActiveAdmin, and got strange problem. I cannot get the context in the helper method.

this is helper method text (i leaved the pry binding point)

```ruby
module ActiveAdmin
  module ViewsHelper
    # for quick and clear table resource output in AA
    def custom_tr_for2(context, resource, method)
      binding.pry
      context.instance_exec do
        locale_path = "activerecord.attributes.#{resource.class.to_s.underscore}.#{method}"
        tr do
          td class: 'col-md-6' do
            t locale_path
          end
          td class: 'col-md-6' do
            resource.send method
          end
        end
      end
    end
  end
end
```

and it calls by 

```ruby
...
show do
    div do
      table class: "table table-hover table-bordered" do
        custom_tr_for2 self, user, :foo
...

```

I had to add context variable and send it to method, becourse I did not founud better choise. This code works good now but I cannot explain this phenomen

```ruby
[17] pry(#<#<Class:0x0000000894a8d8>>)> self.class.superclass
=> ActionView::Base
[18] pry(#<#<Class:0x0000000894a8d8>>)> context.class.superclass
=> ActiveAdmin::Views::Pages::Base
[19] pry(#<#<Class:0x0000000894a8d8>>)> 

```

And the main point is to find any way, which do not force me to send `self` to the helper
PS: Till this moment I cannot understand is this a bug or a feature

**Comment by seanlinsley** [comment]
For context: https://github.com/activeadmin/activeadmin/issues/188#issuecomment-184902741

**Comment by kvokka** [comment]
Thank you for the answer.
But I'm already talking about the algoritm, which was provided by @leafr user, from your link.
And I have the problem with partials in `show` action. I it is not provided by `Formtastic`, and it mean that it will have another logic.
The last algoritm, written by @ldlsegovia is the best fot forms, and is perfect to use in partial head

And I'm asking about little helpers INSIDE the output cucles. Imd me, like previour man hane no idea how to write better

**Comment by kvokka** [comment]
Answer is here https://github.com/activeadmin/activeadmin/issues/188#issuecomment-188440120

**Comment by timoschilling** [comment]
closed while solved by https://github.com/activeadmin/activeadmin/issues/188#issuecomment-188440120
