### ISSUE TITLE
No Username no Password!

### ISSUE THREAD

**Issue by SylarRuby** [activeadmin/activeadmin#4323]
Am I missing something here? Ive just installed: `gem 'activeadmin', '~> 1.0.0.pre2'`, ran the install: `rails g active_admin:install` then the migration. Where is the login details for `/admin`? The admin@example.com does not work.

**Comment by SylarRuby** [comment]
Guess you need to tell people about this:

`AdminUser.create!(:email => 'admin@example.com', :password => 'password', :password_confirmation => 'password')`

**Comment by seanlinsley** [comment]
The installation docs explain that you need to run `rake db:seed`: https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md

**Comment by jpalmieri** [comment]
@seanlinsley Unless I'm missing something, it looks like activeadmin.info isn't at parity with the above info regarding seeding.
http://activeadmin.info/docs/0-installation.html

**Comment by jpalmieri** [comment]
I would've posted an issue in that repo, but the contributing guidelines directed me here.
