### ISSUE TITLE
ActiveAdmin Messed up my Foundation CSS

### ISSUE THREAD

**Issue by SylarRuby** [activeadmin/activeadmin#4324]
This gem takes over my entire foundatiion 6 css. From buttons to columns to table. How to prevent this, please?

**Comment by timoschilling** [comment]
don't use a `require_tree .` in your `application.css`

**Comment by SylarRuby** [comment]
@timoschilling I have other files within the tree. I should require those manually in the `application.css`?

**Comment by timoschilling** [comment]
Yes there is no other way, otherwise the `active-admin.scss` will be included in your `application.css`.
But you can use `require_tree components` or something like that.

**Comment by SylarRuby** [comment]
@timoschilling ;)

**Comment by andrewcrabb** [comment]
A simple and effective solution is in the answer by @gfd in [this post](move active_admin.css.scss from app/assets/stylesheets/ to vendor/assets/stylesheets/)
