### ISSUE TITLE
ActiveModel::ForbiddenAttributesError

### ISSUE THREAD

**Issue by SylarRuby** [activeadmin/activeadmin#4325]
Why am I getting this:

```

def sanitize_for_mass_assignment(attributes)
   if attributes.respond_to?(:permitted?) && !attributes.permitted?
        raise ActiveModel::ForbiddenAttributesError 
   else
    attributes
end

```

Was working great with rails_admin. Any code to add? This happen when I try to update a model in the admin section.

**Comment by timoschilling** [comment]
https://github.com/activeadmin/activeadmin/blob/f8ef8ca7f9ce6dc70a4761d6269477f0dff448ec/docs/2-resource-customization.md#setting-up-strong-parameters

**Comment by SylarRuby** [comment]
Thanks!
