### ISSUE TITLE
Empty form values are not included in params

### ISSUE THREAD

**Issue by arogachev** [activeadmin/activeadmin#4327]
Resource form contents:

```ruby
form do |f|
  f.inputs do      
    f.input :name
  end

  f.actions
end
```

I am using Rails 5 beta 3, here is `Gemfile` contents:

```ruby
# Backend
gem 'activeadmin', github: 'activeadmin/activeadmin', branch: 'master'
```

`Gemfile.lock` contents:

```
GIT
  remote: git://github.com/activeadmin/activeadmin.git
  revision: f7483e3b8fcd74437b03c18fb658dac62a9fc62e
  branch: master
  specs:
    activeadmin (1.0.0.pre2)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails
      kaminari (~> 0.15)
      rails (>= 3.2, < 5.0)
      ransack (~> 1.3)
      sass-rails
      sprockets (< 4)
```

Even I include attribute in permitted params:

```ruby
permit_params :name
```

it's missing in params when I submit empty value and as a result name is not updated. Non-empty values work OK.

Same with select boxes.

After error occured, I tried to update activeadmin with:

```
bundle update activeadmin
```

but error still remains.

**Comment by arogachev** [comment]
I tested it on simple rails form (generated by scaffold command) and formtastic, both options work, so it seems to be Active Admin problem. Any thoughts?

**Comment by arogachev** [comment]
Here is how I see params content (also checked logs):

```ruby
controller do
  def update
    abort params.inspect
  end
end
```

So name is not presented even at this moment.

**Comment by micred** [comment]
Same problem here.
Both empty strings and empty checkbox has_many associations are not present in `params`.

Empty attributes are present in the HTTP POST sent by browser.

Rails 5.0.0.beta3 
activeadmin master rev: f7483e3b8fcd74437b03c18fb658dac62a9fc62e
formtastic master rev: 9a1e518fc03c7260ad7b0345ba7915c4643bad1a

**Comment by micred** [comment]
As I told you in stackoverflow, I found this was caused by [a bug in rack](https://github.com/rack/rack/pull/1009).

You can solve it by adding to the Gemfile: 

    gem 'rack', github: 'rack/rack'

**Comment by seanlinsley** [comment]
Sounds like this can be closed then. Thanks @micred for looking into this.

**Comment by arogachev** [comment]
@micred Thanks for your help! But I'm wondering why it worked outside of Active Admin?

**Comment by micred** [comment]
Don't know, maybe because form is encoded in form-data and not urlencode

**Comment by arogachev** [comment]
@micred Unfortunately, this fix blocks installations of some gems, for example https://github.com/refile/refile with error:

> Bundler could not find compatible versions for gem "rack"

Any tips how to resolve it? Removing `Gemfile.lock` and running `bundle install` didn't help.

**Comment by micred** [comment]
Are you using the git master branch of that refile?

**Comment by arogachev** [comment]
@micred Yes, I tried with adding `github: refile/refile` parameter, same error.

**Comment by micred** [comment]
Since I don't see any direct contraints on the gem rake by refile https://github.com/refile/refile/blob/master/Gemfile
try to dig into Gemfile.lock to see which gem are locking rack and open an issue to it.

**Comment by arogachev** [comment]
@micred I created issue with more details there https://github.com/refile/refile/issues/447.
