### ISSUE TITLE
using active_admin_comments in show partial

### ISSUE THREAD

**Issue by tobyhede** [activeadmin/activeadmin#433]
When using active_admin_comments from a HAML partial for my show view, I receive an Exception:

```
undefined local variable or method `active_admin_comments'
```

Is there a way to include the helper methods into my render context?

If I use the "active_admin_comments_for(@event)" method directly from HAML (bypassing the AA View Helper) the comments section renders incorrectly and appears twice in the page (once before the start of the html body, and once in the correct place on the page).

**Comment by BRZInc** [comment]
Hi,

I'm facing similar issue. Have been struggling with this a couple of nights - no luck so far.
I've check also discussions in Google - it seems that this question is simply ignored.

Could someone help with an advice?

**Comment by CapSens-SM** [comment]
Hi, for those who would still stumble in this old post just like me : 

One solution is to pass `self` to the partial : 

```
 # app/admin/users.rb
 
 show do
    render partial: 'admin/users/show', locals: { context: self }
  end
```
then in your partial : 

```
 # app/views/admin/users/_show.arb
 
 context.instance_eval do
 
 # your code in here just like if your were in app/admin/users.rb
 
 end
```
