### ISSUE TITLE
How to reload code in Active Admin Custom Batch Actions

### ISSUE THREAD

**Issue by interpegasus** [activeadmin/activeadmin#4332]
Hi, 

I use active admin in a Rails app with custom batch actions.
The batch actions are created from the last 5 records from the database. Please find attached the code below.

However when a new record (Event) is created the batch actions do not refresh. I would like to know how to force a refresh? Is there a function I can call to make the batch actions refresh from new records? Thanks

```ruby
ActiveAdmin.register TimeLineMessage do
  menu
  menu label: 'Rundown page'
  
  Event.order("created_at DESC").limit(5).reload.each do |event|
    batch_action ("Move to " + event.name.to_s).to_sym do |ids|
      TimeLineMessage.find(ids).each do |tlm|
        tlm.event_id = event.id
        tlm.save
      end
      redirect_to collection_path, alert: "The content tiles have been moved to "+ event.name.to_s + " event "
    end
  end
```

Re: http://activeadmin.info/docs/9-batch-actions.html

**Comment by timoschilling** [comment]
That's not posible.

I'm closing this, while it is not a active admin bug and I have posted you a solution on stackoverflow.
http://stackoverflow.com/questions/35711051/how-to-reload-code-in-active-admin-custom-batch-actions/35718628#35718628
