### ISSUE TITLE
undefined method `city_id' for nil:NilClass

### ISSUE THREAD

**Issue by Rubioli** [activeadmin/activeadmin#4336]
I am using the latest ActiveAdmin and rails 4.2.4. After installation, when I try to login I get this error:
```
NoMethodError in ActiveAdmin::Devise::SessionsController#create
undefined method `city_id' for nil:NilClass
```

And in Extracted source it shows me this code:
```
def after_sign_in_path_for(resource)
      if current_user.city_id.present?
        session[:previous_url] || root_path
      else
        :edit_user_registration
end
```

This code is placed in my ApplicationController. I have tried to add **city_id** to **admin_users** table, but still getting this error. I don't understand why do I get this error and hope someone can help me.

_NB: I use city_id in my application and city_id is important for my application._

This is my ApplicationController:
```
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :send_to_update_city

  # Devise for redirect back to previous page
  after_filter :store_location


  private
    def send_to_update_city
      if user_signed_in? && current_user.city_id.blank?
        redirect_to :edit_user_registration
      end
    end

    def default_url_options(options = {})
      {locale: I18n.locale}
    end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:account_update) << :full_name
      devise_parameter_sanitizer.for(:account_update) << :address
      devise_parameter_sanitizer.for(:account_update) << :phone
      devise_parameter_sanitizer.for(:account_update) << :avatar
      devise_parameter_sanitizer.for(:account_update) << :city_id
      devise_parameter_sanitizer.for(:account_update) << :zip_code
      devise_parameter_sanitizer.for(:sign_up) << :city_id
      devise_parameter_sanitizer.for(:sign_up) << :full_name
    end

    # Devise for redirect back to previous page
    def store_location
      # store last url - this is needed for post-login redirect to whatever the user last visited.
      return unless request.get?
      if (request.path != new_user_session_path &&
          request.path != new_user_registration_path &&
          request.path != "/users/password/new" &&
          request.path != "/users/password/edit" &&
          request.path != "/users/confirmation" &&
          request.path != "/users/edit" &&
          request.path != destroy_user_session_path &&
          !request.xhr?) # don't store ajax calls
        session[:previous_url] = request.fullpath
      end
    end

    def after_sign_in_path_for(resource)
      if current_user.city_id.present?
        session[:previous_url] || root_path
      else
        :edit_user_registration
      end
    end

end 
```

Thanks in advance!

**Comment by timoschilling** [comment]
Your code need's to deal with the case that current_user can be `nil`
```ruby
if current_user && current_user.city_id.present?
```

**Comment by Rubioli** [comment]
Thanks @timoschilling 
I changed after_sign_in_path_for(resource) to this:

```
def after_sign_in_path_for(resource)
      if current_user && current_user.city_id.present?
        session[:previous_url] || root_path
      else
        :edit_user_registration
      end
    end
```

But Still have the problem :/ (its making me crazy). I don't know if I understood correctly or I did something wrong :/

**Comment by timoschilling** [comment]
What error did you get if with `after_sign_in_path`

Where get you this error, if you remove `after_sign_in_path`.

**Comment by Rubioli** [comment]
This error I get with `after_sign_in_path`:
![skjermbilde 2016-03-09 kl 17 14 25](https://cloud.githubusercontent.com/assets/16593596/13641921/b54182e4-e61a-11e5-934b-6a25a240ae64.png)

And the error comes **right after**, when I insert my email and password to login.

And when I comment out/remove the after_sign_in_path, for some reason I still get the same error, see attachment please.
![skjermbilde 2016-03-09 kl 17 15 41](https://cloud.githubusercontent.com/assets/16593596/13641965/e458f292-e61a-11e5-9865-587a63243a30.png)

Hope you can help me out and Thanks :)

**Comment by timoschilling** [comment]
Restart your Webserver, the 2. error can't be true, it looks like a code reloading problem and the 1. is maybe the same. Test both cases with a restart after that change.

**Comment by Rubioli** [comment]
Now I dont get the error (its good sign) BUT when I try to login from **http://localhost:3000/admin/login** I am sent to the "front-end"-login page **http://localhost:3000/login** And I have to sign in there first and then go back to **http://localhost:3000/admin/login** and try to login...

Is it correct?

**Comment by timoschilling** [comment]
You use Devise for Frontend and Backend?

Then you need to write your `after_sign_in_path_for` method like this:
```ruby
    def after_sign_in_path_for(resource)
      if current_user.is_a? AdminUser
         return admin_root_path
      end
      if current_user && current_user.city_id.present?
        session[:previous_url] || root_path
      else
        :edit_user_registration
      end
    end
```

**Comment by Rubioli** [comment]
Thanks for help @timoschilling 

Correct, I use Devise for both Frontend and Backend (backend if ActiveAdmin uses Devise).

I did what you wrote, but I am still  sending back to frontend and when I login there, I am being redirect to
**http://localhost:3000/admin/login** with TOO_MANY_REDIRECT error :/

**Comment by timoschilling** [comment]
It's definitely not a ActiveAdmin bug andi don't have the time to help you more then I have done already.
That's way I'm closing this issue.

Ask on StackOverflow or on the Devise repo.

**Comment by Rubioli** [comment]
Thanks for your help @timoschilling
