### ISSUE TITLE
1.0.0 belongs_to not working?

### ISSUE THREAD

**Issue by mattheworres** [activeadmin/activeadmin#4339]
When I place a `belongs_to` on a child object, I get an error:

`Unable to autoload constant Admin::ParentClass, expected /app/admin/parent_class.rb to define it (LoadError)`

I describe the issue more fully on StackOverflow here: http://stackoverflow.com/questions/35926912/activeadmin-1-0-0-belongs-to-unable-to-autoload-parent

...but I would be willing to provide more specificity here as needed. To be honest, if I get an answer from either site I intend to update the other with whatever information fixes (or at least solves) the issue I'm experiencing here.

**Comment by timoschilling** [comment]
Sounds like you have a Rails autoloading problem. You can fix this with a `require` for the model file in the admin files.

**Comment by mattheworres** [comment]
@timoschilling that doesn't seem to have any effect on the error.

If I were to define a nested resource within `routes.rb` for `:sub_objects` within `:parent_classes`, would that be enough to allow AA to work properly on the route /admin/parent_classes/{parent-class-id}/sub_objects ?

**Comment by timoschilling** [comment]
```ruby
# app/admin/sub_object.rb
require "../model/parent_class"
ActiveAdmin.register SubObject do
  belongs_to :parent_class

  permit_params :name
end
```

That don't work

**Comment by mattheworres** [comment]
@timoschilling no it does not. `require` by default isn't relative (starts at the base of the app) so technically `require "../models/parent_class"` is incorrect, but when I use `require "models/parent_class"` the error stays the same (saying it can't find `Admin::ParentClass` and expected admin/parent_class.rb to define it).

When I use `require "parent_class"` the error is the same still.

**Comment by timoschilling** [comment]
You can try this:
```ruby
belongs_to :parent_class, class: ":: ParentClass"
```

**Comment by mattheworres** [comment]
@timoschilling that did it! You were incredibly close, but the first error that the console threw at me helped me figure it out. Here's what worked for me:

`belongs_to :parent_class, class_name: "::ParentClass"`

Also, this is an oddity within my specific project here, and may not necessarily be an issue with ActiveAdmin per se. I had a standard Rails 4 project with vanilla ActiveAdmin pulled in, and I was able to throw a `belongs_to` on one object to another and the Route was created fine. I'll attempt to figure out what the discrepancy was because this was a true puzzle.
