### ISSUE TITLE
filters does not apply when use custom scope

### ISSUE THREAD

**Issue by gingray** [activeadmin/activeadmin#4343]
I've face with problem when filter does not apply when use custom scope which not defined in model. Also custom scope affects on other scopes

```ruby
    scope('Deleted') { | scope | scope.where('deleted_at IS NOT NULL') }
```
Example of custom scope

**Comment by seanlinsley** [comment]
That works for me. Could you please create a minimal Rails app that can reproduce the error, and upload it to Github?

**Comment by gingray** [comment]
@seanlinsley yes sure during the day i'll provide it. Maybe on this behavior was affected other gems but i'll check this out.

**Comment by gingray** [comment]
@seanlinsley sorry for that noise can't reproduce error in a test rails app.
