### ISSUE TITLE
How to add new users?

### ISSUE THREAD

**Issue by SylarRuby** [activeadmin/activeadmin#4348]
I cant seem to add any new users from the admin page.

app/admin/user.rb:

```
permit_params :email, :password

```

When I hit the "create user" button, the page only blinks and nothing happens. No error, nothing. Do I need to add anything else? I can delete and edit a user no problem but not the password fields.

**Comment by timoschilling** [comment]
You need a `password_confirmation` field too

**Comment by SylarRuby** [comment]
Samething, @timoschilling. No change.

**Comment by timoschilling** [comment]
please post the complete admin/user and model/user file

**Comment by SylarRuby** [comment]
```
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :registration
  has_one :profile
  has_one :company
  has_one :balance
  has_many :quote_milestones, dependent: :destroy
  has_many :quotes
  #before_create :build_profile #-> inbuilt method We have removed this. See devise registration controller!
  before_create :build_balance #-> inbuilt method

  def display_name
    return self.email
  end

end
```

**Comment by timoschilling** [comment]
and the admin/user please

**Comment by SylarRuby** [comment]
```
  permit_params :email, :password, :password_confirmation, :verified, :registration_id


  index do
    selectable_column
    id_column
    column :email
    column :registration_id
    column :verified
    column :created_at
    actions
  end
```

**Comment by timoschilling** [comment]
do you use the auto form? or a custom form?

**Comment by SylarRuby** [comment]
No. Just virgin ruby. I use Foundation 6 though.

**Comment by SylarRuby** [comment]
@timoschilling I have used this method in the User model but password field is blank when user is created:

```

def password_required?
  new_record? ? false : super
end

```

**Comment by SylarRuby** [comment]
@timoschilling I'll close this as I only needed to create a User then the user can request to change their password, but this works with the above code.

**Comment by princetechs** [comment]
After installation run the command:-

`rails db:migrate db:seed
`This will run the code on the seed file:-

```
AdminUser.create!(
  email: 'admin@example.com',
  password: 'beta123',
  password_confirmation: 'beta123'

)
```
