### ISSUE TITLE
Turbolinks preventing CSS from loading (on first request) in ActiveAdmin

### ISSUE THREAD

**Issue by michaelmagistro** [activeadmin/activeadmin#4349]
With Turbolinks enabled, ActiveAdmin is not loading CSS on the first request. If the page is refreshed, then the CSS gets loaded.

![activeadmin_turbolinks](https://cloud.githubusercontent.com/assets/1243197/13803744/bac34878-eb0c-11e5-9831-65abe0082d4f.gif)

**Comment by timoschilling** [comment]
Turbolinks is not supported by ActiveAdmin

**Comment by michaelmagistro** [comment]
It seems the only way around this is to clone ActiveAdmin (or at least the view in question) and edit the body tag from there to disable Turbolinks.

References:
http://stackoverflow.com/questions/7452418/how-can-i-customize-the-active-admin-layout
http://stackoverflow.com/questions/14926120/active-admin-how-to-add-custom-script-before-body-tag

**Comment by timoschilling** [comment]
If you provide a clean way to bring active admin and turbolinks to work, I will merge it!
