### ISSUE TITLE
Remove button turn into checkbox on updating Nested model

### ISSUE THREAD

**Issue by waleedarshad** [activeadmin/activeadmin#4350]
When we use nested model in active admin, it provide us Remove button but on editing, this remove button turns into checkbox, does not it would remain the same as on creation

**Comment by timoschilling** [comment]
please provide the admin file and some screenshots

**Comment by waleedarshad** [comment]
![remove button on creation](https://cloud.githubusercontent.com/assets/5329697/13812776/da8d891e-eb9f-11e5-9da7-b2c6f512a91a.png)
![checkbox on editing](https://cloud.githubusercontent.com/assets/5329697/13812782/e0a4ff4e-eb9f-11e5-9e48-9bcae77e3822.png)

**Comment by timoschilling** [comment]
This is a willed behavior. The reason is that on create JS can destroy the nested model form, but on edit it can't because of the fact that the server need's a notice about the destroy. There is a issue/pr somewhere about a unifying of this.

**Comment by timoschilling** [comment]
The PR is #2827

**Comment by waleedarshad** [comment]
Alright Thanks @timoschilling

**Comment by waleedarshad** [comment]
@timoschilling  is there anyway i can get the uniform behavior on new and edit nested form about remove button if i specifically want this behavior.

**Comment by timoschilling** [comment]
There is no build in way. You can copy the code from the PR.
