### ISSUE TITLE
Batch action select collection delayed update?

### ISSUE THREAD

**Issue by millie** [activeadmin/activeadmin#4351]
I have a batch action to assign a category to products. 

When I add new categories, they don't appear in this dropdown for some unpredictable period of time (yet they appear immediately in the category filter dropdown at right). I'm having this "delayed update" issue with dropdowns in all batch actions.

```ruby
batch_action :set_product_category, form:
    {
        category_id: Category.all.map { |cr| ["#{cr.name}", cr.id] }

    } do |ids, inputs|

  Product.find(ids).each do |product|
    product.category_id = inputs[:category_id]
    product.save!
  end

  redirect_to collection_path, alert: "The products have been added to that category."
end
```

**Dropdown for batch action (missing newest two categories)**
![image](https://cloud.githubusercontent.com/assets/444160/13820711/be653136-eb5b-11e5-9456-cd56e6088779.png)

**Dropdown for filter (showing newest two categories at bottom)**
![image](https://cloud.githubusercontent.com/assets/444160/13820742/e0470824-eb5b-11e5-85cc-a6dded02414b.png)

**Comment by timoschilling** [comment]
```ruby
batch_action :set_product_category, form:
    {
        category_id: Category.all.map { |cr| ["#{cr.name}", cr.id] }

    } do |ids, inputs|
```
This code will be only executed on the boot time of your app, the most webserver restart your app after a period of time, thats way it have a delay.

I'm not sure, but you can try this:
```ruby
batch_action :set_product_category, form:
    {
        category_id: -> { Category.all.map { |cr| ["#{cr.name}", cr.id] } }

    } do |ids, inputs|
```
Then the Proc will be executed on each request.

**Comment by millie** [comment]
Thanks so much for explaining why it's behaving this way. Your code fix didn't work though. Any other suggestions?

**Comment by timoschilling** [comment]
I did something wrong, try this:
```ruby
batch_action :set_product_category, form: -> {
        category_id: -> { Category.all.map { |cr| ["#{cr.name}", cr.id] } }

    } do |ids, inputs|
```
The complete `form:` value must be a proc.

**Comment by millie** [comment]
That gets me:
**
syntax error, unexpected tLABEL
    category_id: -> { Category.all.map { |cr|...**

**Comment by timoschilling** [comment]
sorry, I updated my example above.

**Comment by millie** [comment]
It works! Thanks a million!
