### ISSUE TITLE
Can't bundle on production server

### ISSUE THREAD

**Issue by andreycwb** [activeadmin/activeadmin#4352]
I'm getting the following error when trying to deploy my app to production server using Capistrano. I'm Using Rails 4.2 and it's working fine in my machine (development mode). In my Gemfile I'm using:

gem 'activeadmin', github: 'activeadmin'

Because when I use it without specifying github, I get a loop error because of 'meta_search' gem, in my machine. Can't find a solution anywhere, can anybody help me please?

Errors:

> INFO [2c680ced] Running /usr/local/rvm/bin/rvm default do bundle install --path /home/nossos/public_html/clientes/mapajornada/shared/bundle --without development test --deployment --quiet as deploy@nossosprojetos.com.br
DEBUG [2c680ced] Command: cd /home/nossos/public_html/clientes/mapajornada/releases/20160316210146 && /usr/local/rvm/bin/rvm default do bundle install --path /home/nossos/public_html/clientes/mapajornada/shared/bundle --without development test --deployment --quiet
DEBUG [2c680ced] 	github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
DEBUG [2c680ced] 	github.com[0: 192.30.252.129]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
DEBUG [2c680ced] 	github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
DEBUG [2c680ced] 	github.com[0: 192.30.252.129]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
DEBUG [2c680ced] 	Git error: command `git clone 'git://github.com/activeadmin/activeadmin.git'
"/home/nossos/public_html/clientes/mapajornada/shared/bundle/ruby/2.3.0/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528"
--bare --no-hardlinks --quiet` in directory
/home/nossos/public_html/clientes/mapajornada/releases/20160316210146 has
failed.
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@nossosprojetos.com.br: bundle exit status: 11
bundle stdout: github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
github.com[0: 192.30.252.129]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
github.com[0: 192.30.252.129]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
Git error: command `git clone 'git://github.com/activeadmin/activeadmin.git'
"/home/nossos/public_html/clientes/mapajornada/shared/bundle/ruby/2.3.0/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528"
--bare --no-hardlinks --quiet` in directory
/home/nossos/public_html/clientes/mapajornada/releases/20160316210146 has
failed.
bundle stderr: Nothing written

> SSHKit::Command::Failed: bundle exit status: 11
bundle stdout: github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
github.com[0: 192.30.252.129]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
github.com[0: 192.30.252.129]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
Git error: command `git clone 'git://github.com/activeadmin/activeadmin.git'
"/home/nossos/public_html/clientes/mapajornada/shared/bundle/ruby/2.3.0/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528"
--bare --no-hardlinks --quiet` in directory
/home/nossos/public_html/clientes/mapajornada/releases/20160316210146 has
failed.
bundle stderr: Nothing written

> Tasks: TOP => deploy:updated => bundler:install
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@nossosprojetos.com.br: bundle exit status: 11
bundle stdout: github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
github.com[0: 192.30.252.129]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
github.com[0: 192.30.252.128]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
github.com[0: 192.30.252.129]: errno=Connection timed out
fatal: unable to connect a socket (Connection timed out)
Git error: command `git clone 'git://github.com/activeadmin/activeadmin.git'
"/home/nossos/public_html/clientes/mapajornada/shared/bundle/ruby/2.3.0/cache/bundler/git/activeadmin-c24fcef949b2f1bbdf6b5a17650dcd86d73f2528"
--bare --no-hardlinks --quiet` in directory
/home/nossos/public_html/clientes/mapajornada/releases/20160316210146 has
failed.
bundle stderr: Nothing written

Sorry for any english mistakes.
Thanks in advance.

**EDITED**

I got it to work using gem 'activeadmin', '~> 1.0.0.pre2' and fetching it from RubyGems.

**Comment by timoschilling** [comment]
Thats a network issue between Github and your Server. This error is not in scope of ActiveAdmin, that's why I close this issue.
