### ISSUE TITLE
Forms error visualization 

### ISSUE THREAD

**Issue by estebance** [activeadmin/activeadmin#4357]
When I insert wrong information in my form Active admin show me two error messages for the same field, one below the label (I don't want to show this label) of the input field and the other is the inline error ( this is the error that I want to show to the user).

¿ Someone can help me to delete this label  of my forms 
![screen shot 2016-03-20 at 11 11 49 pm](https://cloud.githubusercontent.com/assets/4256843/13910502/2b4705ca-eef1-11e5-9acf-fa294e870fb4.png)
?

**Comment by seanlinsley** [comment]
Can you post the code of the form, and your Active Admin and Arbre versions?

**Comment by estebance** [comment]
This is the code of the form 

![screen shot 2016-03-28 at 9 32 50 pm](https://cloud.githubusercontent.com/assets/4256843/14096236/acbf3442-f52c-11e5-9830-f427cf13026e.png)

**Comment by estebance** [comment]
I am using Arbre 1.0.3 and ActiveAdmin activeadmin 1.0.0.pre2

**Comment by estebance** [comment]
I'am still working trying to solve this issue,  have you got some idea what happens

**Comment by Fivell** [comment]
@estebance, feel free to open new issue with detailed guide how to reproduce such behaviour or give link to repo with sample application that can confirm this bug.
