### ISSUE TITLE
Multiple ckeditor inputs on the same page.

### ISSUE THREAD

**Issue by RomanKapitonov** [activeadmin/activeadmin#4358]
I've been trying to render several ckeditors on the same page but it seems that only the first one is being initialized and all other inputs get ignored and are rendered as textareas. I'm using a serializer JSON field which represents a number of inputs but I've confirmed that is not the cause.

I've also tried to create two inputs with type `:ckeditor` and only first one gets rendered as a wysiwyg editor. I've been using [this](https://github.com/activeadmin/activeadmin/wiki/Ckeditor-integration) guide for integration. Was not able to find anything of that kind in the issues so creating a new one.

**Comment by timoschilling** [comment]
The wiki contains user generated content wich is not supported by the activeadmin collaborators.
If you need any help in that direction, ask on stackoverflow.

Hint: you need uniq ids for each ckeditor field, the `CKEDITOR.replace` need to call with each of the ids.

**Comment by RomanKapitonov** [comment]
@timoschilling Thank you for your answer, that is true. Rails form builder generated identical ids for inputs. That is where the issue was.
