### ISSUE TITLE
cannot clone repository with `transfer.fsckobjects=true`

### ISSUE THREAD

**Issue by dunn** [activeadmin/activeadmin#4361]
Setting `transfer.fsckobjects=true` means running `git fsck` on fetched objects, and it's flagging an issue with the repo:
```
🌲  git clone https://github.com/activeadmin/activeadmin.git
Cloning into 'activeadmin'...
remote: Counting objects: 31112, done.
remote: Compressing objects: 100% (47/47), done.
error: object f017639a26c2d52520f9c4d34a3d26c40e367c31: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```
It's not like this can be fixed (without force-pushing), but I thought I'd bring it to your attention.

**Comment by seanlinsley** [comment]
Shouldn't this be reported to Github support?

**Comment by dunn** [comment]
AFAIK this is an issue with the repository; the mode bits of `f017639a26c2d52520f9c4d34a3d26c40e367c31` have zero-padding, which is not allowed by Git: http://stackoverflow.com/a/15605031

**Comment by jabbrwcky** [comment]
Looks like this issue still persists.

```
git clone https://github.com/activeadmin/activeadmin.git
Cloning into 'activeadmin'...
remote: Counting objects: 31208, done.
error: object f017639a26c2d52520f9c4d34a3d26c40e367c31: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed
```

This basically breaks installing the gem from github and 1.0.0.pre2 is already 240 commits old...

**Comment by csuhta** [comment]
I can also reproduce this issue with Git 2.9.0. You have to globally disable `fsckobjects` so that Git or Bundler will work with the repo correctly.

```
$ git clone https://github.com/activeadmin/activeadmin.git
Cloning into 'activeadmin'...
remote: Counting objects: 31538, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 31538 (delta 1), reused 0 (delta 0), pack-reused 31535
Receiving objects: 100% (31538/31538), 5.84 MiB | 9.90 MiB/s, done.
Resolving deltas: 100% (19899/19899), done.
Checking connectivity... done.

$ git config --global transfer.fsckobjects true
$ git config --global fetch.fsckobjects true
$ git config --global recieve.fsckobjects true
$ rm -rf ./activeadmin/

$ git clone https://github.com/activeadmin/activeadmin.git
Cloning into 'activeadmin'...
remote: Counting objects: 31538, done.
remote: Compressing objects: 100% (3/3), done.
error: object f017639a26c2d52520f9c4d34a3d26c40e367c31: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
```

Bundler has the same error as above, then goes into a retry loop three times before giving up.

Fixing this issue may require you to rebase/force-push an un-damaged commit, which will be unpleasant.

**Comment by dunn** [comment]
> Fixing this issue may require you to rebase/force-push an un-damaged commit, which will be unpleasant.

I wouldn't say it's _damaged_; the issue is benign, so just because fsck flags it doesn't warrant such drastic action as rewriting a ton of history.

**Comment by timoschilling** [comment]
I have contacted the GH support:

> Hey there timoschilling,
> 
> Thanks for getting in touch! You asked:
> 
> I have a problem with the repo activeadmin/activeadmin, I don't know enough about git, maybe you can help: https://github.com/activeadmin/activeadmin/issues/4361
> 
> The repository you are trying to clone has an object in its history that violates git's format, but is relatively harmless in practice. However, you seem to have enabled the transfer.fsckObjects configuration in your client, which will reject such an object.
> 
> Upcoming versions of git may have better options for selectively ignoring particular objects or warnings, but for now, the best you can do is to disable the checks completely for the duration of the clone, like:
> 
> git -c transfer.fsckObjects=false clone https://github.com/activeadmin/activeadmin.git
> 
> Subsequent fetches will still use the checks (but won't trigger on the historical object, because git will not need to fetch it again).
> 
> I hope that helps, but let us know if you have any other questions!
> 
> All the best,
> Francis
