### ISSUE TITLE
Login page translation problem

### ISSUE THREAD

**Issue by batizhevsky** [activeadmin/activeadmin#4368]
I use last master version (988b34e77d1f69efa5fef97e0397b64b8656d11d) and last formtastic
My locale is `Ru`
Issue:  Login button duplicate it's cation outside of `li` list
![image](https://cloud.githubusercontent.com/assets/165599/14079085/55eb4074-f4fb-11e5-9d7f-3607f2b3cae0.png)

I've tried to dive in to the problem, but lack of success. But I found consistent pattern: at every time `translate` (and it's alias `t`) the same time result of translation was added as `ol` child.

**Comment by timoschilling** [comment]
double of #3666
