### ISSUE TITLE
Rails 5: Migration is missing "[5.0]" when auto created

### ISSUE THREAD

**Issue by bestori** [activeadmin/activeadmin#4369]
The automated migration created for creating admin comments is currently: 

**class CreateActiveAdminComments < ActiveRecord::Migration**

When it **should be**:

**class CreateActiveAdminComments < ActiveRecord::Migration[5.0]**

Instead.

**Comment by seanlinsley** [comment]
How do we make this change so that it's backwards-compatible?

**Comment by bestori** [comment]
@seanlinsley maybe create the migration based on rails version...?

**Comment by bestori** [comment]
Opened a matching PR.
