### ISSUE TITLE
Rails 5: Auto-generated migrations upon install are created in the wrong order

### ISSUE THREAD

**Issue by bestori** [activeadmin/activeadmin#4370]
(timestamp)

Repro:

after running `rails generate active_admin:install`, run 

> rake db:migrate

 and watch rails migration error.

**Comment by seanlinsley** [comment]
Our test rails app runs that same command and doesn't have a problem, so the issue might be something else. Can you add the file names (with their timestamps?)

**Comment by timoschilling** [comment]
Which devise version do you use?

**Comment by bestori** [comment]
@timoschilling latest devise (no version specified)

@seanlinsley should I attach a mini app sample?

**Comment by timoschilling** [comment]
@bestori `3.x` or `4.x`, for Rails `5.x` you need `4.x`

**Comment by bestori** [comment]
I'm using [devise](https://github.com/plataformatec/devise) on master. (No version specified) Bundling gave me 3.5.6

**Comment by timoschilling** [comment]
You do something wrong, devise is on master at version [`4.0.0.rc2`](https://github.com/plataformatec/devise/blob/master/lib/devise/version.rb) and this version is required for Rails 5

**Comment by bestori** [comment]
Alright. I will test again and gist as necessary. You can close this report. Thank you.
