### ISSUE TITLE
Rails 5: Auto generated admin_users migration relies on having admin_users table

### ISSUE THREAD

**Issue by bestori** [activeadmin/activeadmin#4371]
Auto-generated migration upon install

> class AddDeviseToAdminUsers < ActiveRecord::Migration[5.0]
>   def self.up
>     **change_table** :admin_users do |t|
>     #.....
> 
> 

Should be

> class AddDeviseToAdminUsers < ActiveRecord::Migration[5.0]
>   def self.up
>     **create_table** :admin_users do |t|
>     #.....
> 
>

**Comment by seanlinsley** [comment]
We don't control that, Devise does. I believe it switches between `change_table` and `create_table` based on whether the model already exists.
