### ISSUE TITLE
Breadcrumbs should not link to show action with to_param

### ISSUE THREAD

**Issue by BrahimDa** [activeadmin/activeadmin#4376]
I have this code

```ruby
ActiveAdmin.register MyModel do
  actions :all, :except => :show
  ...
end
```

in case i use "to_param" (in model)  in order to use permalink instead of the "id" in the url, the breadcrumb genarte the same error like [#736](https://github.com/activeadmin/activeadmin/issues/736) issue

**Comment by timoschilling** [comment]
wich active admin version do you use?

**Comment by BrahimDa** [comment]
i'm in 1.0.0.pre2

**Comment by bestori** [comment]
@BrahimDa , thanks for reporting! 

Can you provide a short gist link or code so we could review it?

Thanks!

**Comment by timoschilling** [comment]
https://github.com/activeadmin/activeadmin/pull/4485#issuecomment-228703698
