### ISSUE TITLE
Error installing with Rails 5 beta.3

### ISSUE THREAD

**Issue by SylarRuby** [activeadmin/activeadmin#4378]
>/Users/sylar/.rvm/gems/ruby-2.2.3/gems/activeadmin-1.0.0.pre2/lib/generators/active_admin/devise/devise_generator.rb:22:in `rescue in install_devise': You provided devise 4.0.0.rc2 but we need: ~> 3.2. If you don't want to use devise, run the generator with --skip-users. (ActiveAdmin::GeneratorError)

[As per doc](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md):

```
gem 'activeadmin', '~> 1.0.0.pre2'
gem 'devise', '> 4.x'

```

**Comment by seanlinsley** [comment]
Right above that:
> Active Admin master has preliminary support for Rails 5. To give it a try, these Gemfile changes may be needed:

There isn't a Rubygems release that supports Rails 5 yet.

**Comment by bestori** [comment]
:+1: Non-issue

**Comment by SylarRuby** [comment]
So no one is using this with rails 5? It only works with rails 4?

**Comment by bestori** [comment]
@SylarRuby ,we didn't say that :) 

In your gemfile, use the line(s)

> gem 'devise', git: 'git@github.com:plataformatec/devise.git'
> gem 'activeadmin', github: 'activeadmin'
> 

Hope this helps. Let me know!

**Comment by SylarRuby** [comment]
@bestori All green lights, mate! Thanks.

**Comment by bestori** [comment]
:+1: welcome!
