### ISSUE TITLE
form for member action

### ISSUE THREAD

**Issue by seaify** [activeadmin/activeadmin#4379]
there has form support for batch_action

``` ruby
batch_action :flag, form: {
  type: %w[Offensive Spam Other],
  reason: :text,
  notes:  :textarea,
  hide:   :checkbox,
  date:   :datepicker
} do |ids, inputs|
  # inputs is a hash of all the form fields you requested
  redirect_to collection_path, notice: [ids, inputs].to_s
end
```

But i need similar form popup when i click a member_action link, how can i archive it?

**Comment by axorinc** [comment]
+1

**Comment by timoschilling** [comment]
Here is a example from one of my apps:
```ruby
member_action :call_later, method: :post do
  ...
end
index do
  actions do
    item t(".label.call_later"), call_later_call_list_path(company.id), id: :call_later, method: :post, :'data-confirm' => t(".confirm.call_later"), :'data-inputs' => { date: :datepicker, hour: :text, minute: :text, important: :checkbox }.to_json
  end
end
```

**Comment by seaify** [comment]
![11f07c91-bd1e-4178-8688-93992270bfd4](https://cloud.githubusercontent.com/assets/3056030/16908293/e5c97fa4-4cfc-11e6-89a1-828d9a42bcfe.png)

![c38aff8b-5e21-4635-9943-994bf8cc3afe](https://cloud.githubusercontent.com/assets/3056030/16908311/101a6db8-4cfd-11e6-9a68-62a78a1e5286.png)


@timoschilling it doesn't work. the popup form only show the "date-confirm".

**Comment by aleksandra-stolyar** [comment]
@seaify have you found some approach?

**Comment by Fivell** [comment]
@seaify do you mean something like this supposed to be working?
```
mamber_action :update, form: {
  type: %w[Offensive Spam Other],
  reason: :text,
  notes:  :textarea,
  hide:   :checkbox,
  date:   :datepicker
} do |inputs|
   resource.update!(inputs)
   redirect_to :back
end
```

**Comment by imsinu9** [comment]
@timoschilling As @seaify said that approach shows only Confirm box but not data input provided. 

@Fivell Since its a long time post wanted to check is there any way of doing same, where form can be sent just like batch_action for member_action. 

Thanks

**Comment by prerakd** [comment]
Can this issue be reopened again? I don't think it is completely resolved yet.
