### ISSUE TITLE
undefined method `page' for #<AdminUser::ActiveRecord_Relation []>

### ISSUE THREAD

**Issue by RustComet** [activeadmin/activeadmin#4381]
So I have recently installed active admin v1.0.0-pre2 (from GitHub), but unfortunately I cannot access anything other than the dashboard. All resource base pages are throwing the error in the title.

**Rails:** 4.2.6
**Ruby:** 2.3.0
**Active Admin**: `v1.0.0-pre2` from GitHub

I originally thought it was the issue where `kaminari` was clashing with `will_paginate`, but I am not using `will_paginate` and it's not listed as a dependency anywhere in my `Gemfile.lock`. Even so I tried the fixes there and it still throws the error, except saying 'undefined method `per_page_kaminari' instead.

Kaminari is definitely being loaded correctly, as you can see below:

```
>> Kaminari
=> Kaminari
>> Kaminari.config.page_method_name
=> :page
>> AdminUser.page(1)
!! #<NoMethodError: undefined method `page' for #<Class:0x007fa8fb1dd2c8>>
```

I have used ActiveAdmin for dozens of projects before, including `pre2` and have never come across this. Just hoping someone can help work out what is going on, and whether this is an `ActiveAdmin` or `Kaminari` bug

**Comment by RustComet** [comment]
Investigating further, it appears that if I manually include the Kaminari methods in my model, then everything begins to work:

```ruby
class AdminUser < ActiveRecord::Base
  self.send(:include, Kaminari::ConfigurationMethods)

  def self.page(num = nil)
    limit(default_per_page).offset(default_per_page * ((num = num.to_i - 1) < 0 ? 0 : num)).extending do
      include Kaminari::ActiveRecordRelationMethods
      include Kaminari::PageScopeMethods
    end
  end
end
```

This loads up fine. So I am guessing there is an error with kaminari being loaded correctly

**Comment by seanlinsley** [comment]
Perhaps this works: https://github.com/amatsuda/kaminari/issues/213#issuecomment-5014913

**Comment by seanlinsley** [comment]
You may also be running Spring, and have to restart it.

**Comment by RustComet** [comment]
Looks like adding `require 'kaminari'` in `application.rb` solves the issue. 

I wonder what has changed to make this necessary. I'll keep having a small poke around to see what I find. But thank you for the help!

**Comment by seanlinsley** [comment]
The order of gems in your Gemfile might cause this.

It's unlikely that ActiveAdmin can do anything to prevent this, so I'm going to close this ticket.
