### ISSUE TITLE
Form select #<Region:0x00...........> 

### ISSUE THREAD

**Issue by DRAKUN** [activeadmin/activeadmin#4385]
Hi , i have a problem to see lib region in form select
![screenshot at avr 07 14-34-47](https://cloud.githubusercontent.com/assets/366065/14354812/41ac591a-fcce-11e5-8940-54544518b375.png)

**Comment by seanlinsley** [comment]
That happens if you won't have one of the [`display_name_methods`](https://github.com/activeadmin/activeadmin/blob/d84f8190edac8c28f942cd4b6c3e16086da9d7a2/lib/active_admin/application.rb#L119) defined on your model.

**Comment by DRAKUN** [comment]
how can i customize it

**Comment by DRAKUN** [comment]
#timoschilling i dont understand

**Comment by seanlinsley** [comment]
You can define one of those methods in your model.

**Comment by DRAKUN** [comment]
ce n'est pas si evident, je fais mais debut sur ruby on rails alors si vous pouvait me donner un exemple pour que je puisse m'inspirer de cela..... merci a vous pour votre réactivité sorry for french

**Comment by seanlinsley** [comment]
Translated:
> this is not so obvious, but I'm beginning to ruby on rails so if you could give me an example so that I can inspire me to it ..... thank you to you for your responsiveness

```ruby
class Region < ActiveRecord::Base
  def display_name
    a_region_attribute
  end
end

**Comment by DRAKUN** [comment]
Its work for me . thanks for all
