### ISSUE TITLE
ActiveAdmin cant handle my own primary_key

### ISSUE THREAD

**Issue by cryuff** [activeadmin/activeadmin#4389]
I want to make app that will be on top of exisiting database.
So i need to use in my model code like _self.pimary_key='primsoft'_ for example.
Now when i try to add soft through activeadmin panel i get: _ActiveModel::ForbiddenAttributesError_
The only case that i can save object is to use:

```
  controller do
    def create
      @notification = Notification.new(notification_params)
      @notification.id = Notification.last.id+1
      @notification.save
    end
end
```
but when i use that i get object without any params, everything is empty.
Any possible way to save objects through activeadmin or i need to make my own admin panel?

Edit:

I can save object now i just add :+1: 
```
  def notification_params
    params.require(:notification).permit(:opis_zgloszenia, :id_firmy,:id_produktu)
  end
```
to controller do, but still  why i cant add this to my main controller instead?

**Comment by timoschilling** [comment]
Have you read this?: https://github.com/activeadmin/activeadmin/blob/c69ace35722c57f956a59445733f61e81f946003/docs/2-resource-customization.md#setting-up-strong-parameters

> why i cant add this to my main controller instead?
What does you mean?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
