### ISSUE TITLE
[JS] assets wrong included in production

### ISSUE THREAD

**Issue by krtschmr** [activeadmin/activeadmin#4392]
we tried for a few hours to get our assets corect in production. in development its always fine, whatever we try.

the generated html looks this:

    <link rel="stylesheet" media="screen" href="/stylesheets/active_admin.css" />
    <link rel="stylesheet" media="print" href="/assets/active_admin/print-1337DIGEST1337.css" />
    <link rel="stylesheet" media="screen" href="/assets/active_admin/admin-1337DIGEST1337.css" />    
    <script src="/javascripts/active_admin.js"></script>

the active_admin.css and the active_admin.js are empty.

we have it organized:

    /assets/stylesheets/active_admin/admin.scss
    /assets/javascripts/active_admin/admin.js

also we defined in our initializer

    Rails.application.config.assets.precompile += %w( active_admin/admin.css active_admin/admin.js)

the problem is, that the CSS is working but the JS won't do anything.

the admin.js content

    //= require jquery
    //= require jquery_ujs

what are we doing wrong?

**Comment by krtschmr** [comment]
unicorn restart is helping... omfg -.-

**Comment by maxcodes** [comment]
Also having this issue. Any idea about how to debug? I'm getting the same output, and it works on dev.
