### ISSUE TITLE
CSS Conflicts with application CSS

### ISSUE THREAD

**Issue by TopHatSolutions** [activeadmin/activeadmin#4394]
The issue here is that out of the box, ActiveAdmin overrides base element styles for many HTML elements. It cause silly conflicts with any CSS bootstrapper, including Bootstrap. There are many solutions out there, involving moving the active-admin.scss file from app/assets/stylesheets (in rails) to vendor/assets/stylesheets; removing the `*=require_tree` line from app/assets/stylesheets/application.css; I found both of these solutions on [This StackOverflow Answer](http://stackoverflow.com/a/10321125) which referenced both a railscast and other SO answers. But really, none of that is necessary.

The fix is simple, scope your CSS, apply a parent  ID to the base wrapper around any ActiveAdmin page, and have all CSS inherit/affect only elements within that base ID.

IE:
```
input[type=submit] {
   look: gross;
}
```
to 
```
#active-admin-wrapper input[type=submit] {
   look: good-for-active-admin;
}
```

if you happen to take advantage of SCSS/SASS it can be as simple as shifting all css into a 
```
#active-admin-wrapper {
   ... 
}
```
block.

My aim here is to be more helpful than annoying, but I understand if I'm just annoying.

**Comment by timoschilling** [comment]
Our recommendation is to exclude the active admin css from the application css.
Other wise you will blow up you application css.

**Comment by gobijan** [comment]
If you are worried about interfering css you can simply alter the default application.css like this:

```
*= require_tree .
 *= stub "active_admin"
 *= require_self
```
