### ISSUE TITLE
Batch Actions Label

### ISSUE THREAD

**Issue by luisbraga** [activeadmin/activeadmin#4395]
How do you remove the word "Selected" from a batch action label?

**Comment by timoschilling** [comment]
overwrite this key:
https://github.com/activeadmin/activeadmin/blob/master/config/locales/en.yml#L72

**Comment by luisbraga** [comment]
thank you. was totally lost where to search. it's obvious now.

**Comment by deepakmahakale** [comment]
FYI: The above link points to incorrect line number now

https://github.com/activeadmin/activeadmin/blob/acfd8f33f219c0b6d9f47c5ad437f5509207639d/config/locales/en.yml#L97

**Comment by ammarqadir99** [comment]
Above referenced line is moved to: 
`https://github.com/activeadmin/activeadmin/blob/master/config/locales/en.yml#L84`
