### ISSUE TITLE
I can't change meta charset for active admin

### ISSUE THREAD

**Issue by cryuff** [activeadmin/activeadmin#4397]
I'm trying to change that param of active admin:
`<meta http-equiv="Content-type" content="text/html; charset=utf-8"/>`
I need it to change to windows-1250
any advice how to do that?

**Comment by dmitry** [comment]
I believe you have to redefine template https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/app/views/layouts/active_admin_logged_out.html.erb in your project.

**Comment by cryuff** [comment]
I did that already in this file i got: 
`  <meta http-equiv="Content-type" content="text/html; charset=windows-1250">`
while on activeadmin page:
`<meta http-equiv="Content-type" content="text/html; charset=utf-8"/>`
so this not working at all.

**Comment by dmitry** [comment]
@cryuff then you might searching for this one: https://github.com/activeadmin/arbre/blob/6d902ae0b6eec3f8ed8faa603b3c2979f5a68614/lib/arbre/html/document.rb#L32

**Comment by cryuff** [comment]
Thank you very much :)
