### ISSUE TITLE
Approach for sorting and filtering json column's keys

### ISSUE THREAD

**Issue by prasadsurase** [activeadmin/activeadmin#4399]
Hi. This issue is more of request for information & guidance and less of an issue. I have a requirement wherein I need to have sorting and filtering on the keys of a json column data. Below is the requirement and my approach over it. I need to know if this is right? Could it have been better and how?

I have a model named Box which stores (length, width & height) as a json in a column named dimensions.

```sql
id | volumn |                        dimensions
---+---------+-------------------------------------------
 1 |     64 | {"length":1,"width":8,"height":8}
 2 |     32 | {"length":4,"width":2,"height":4}
 3 |      0 | {"length":0,"width":3,"height":5}
```
I have added filter as below. The filter is being displayed properly.

```ruby
ActiveAdmin.register Box do
  filter :length, as: :numeric
  filter :width, as: :numeric
  filter :height, as: :numeric
  filter :volume, as: :numeric
end
```
In the Box model, I have ransackers defined as

```ruby
ransacker :length do |parent|
  Arel::Nodes::InfixOperation.new('->>', parent.table[:dimensions], Arel::Nodes.build_quoted('length'))
end
```
**Regarding Filtering**
The filters are displayed in weird fashion(the dropdown at the top and textfield on the bottom) and they don't seem to work. If I select 'Greater than' or 'Less than' option and specify the value, it still sends an equal query.

```ruby
Parameters: {"utf8"=>"✓", "q"=>{"length_equals"=>"5"}, "commit"=>"Filter", "order"=>"id_desc"}
```
The issue isn't with ransacker but with active_admin. If we remove the *ransacker?* from [this](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/filters/formtastic_addons.rb#L57) file, the filters are displayed properly(dropdown with text field on the right side) and they work as expected but select filters arent displayed in Search Status(the Selected Filters under Search Status shows None). The *seems_searchable?* method defined in the above file is used [here](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/filters/base/search_method_select.rb#L34). The class *select_and_search* is added to the dropdown whose presence/absence cause the filter to work/fail respectively. **I wanted to know if we need the *ransacker?* method and if yes, what does it do and whats its importance in the code.**

**Regarding Sorting**
I am displaying the json field's keys as separate columns in the table and need the columns to be sortable. So, I declared AA for Box as below and had to alter *ActiveAdmin::OrderClause* so that sorting is available. Using the below approach, sorting works.

```ruby
controller do
  def scoped_collection
     Box.select("*, dimensions ->> 'length' as length, dimensions ->> 'breadth' as breadth, dimensions ->> 'height' as height")
  end
end #controller

index do
  column :length, label: 'Length', sortable: "dimensions->>'length'"
  column :breadth, label: 'Breadth', sortable: "dimensions->>'breadth'"
  column :height, label: 'Height', sortable: "dimensions->>'height'"
  column :volume, label: 'Volume', sortable: true
end

# Agree that the code is crude and could have been better but was in a rush so added it. Refactor later.
module ActiveAdmin
  class OrderClause
    attr_reader :field, :order

    def initialize(clause)
      clause =~ /^([\w\_\.]+)(->'\w+')?_(desc|asc)$|^([\w\_\.]+->>'[\w\_]+')(->'\w+')?_(desc|asc)$/
      @column = $1 || $4
      @op = $2 || $5
      @order = $3 || $6

      @field = [@column, @op].compact.join
    end

    def valid?
      @field.present? && @order.present?
    end

    def to_sql(active_admin_config)
      table = column_in_table?(active_admin_config.resource_column_names, @column) ? active_admin_config.resource_table_name : nil
      table_column = (@column =~ /\./) ? @column : [ table, json_column?(@column) ? @column : active_admin_config.resource_quoted_column_name(@column) ].compact.join(".")
      [table_column, @op, ' ', @order].compact.join
    end

    private

    def json_column?(column)
      column.include?('->>')
    end

    def column_in_table?(names, column)
      column = json_column?(column) ? column.split('->>')[0].strip : column
      names.include?(column)
    end
  end
end
```

**I wanted to know if the altered *ActiveAdmin::OrderClause* is right and if not, what am I missing?** I forked and cloned the repo, but it has some failing specs. If it works out, I would like to create a PR for the same. [Here](https://github.com/prasadsurase/active_admin_with_json_field) is a demo repo which implements the above functionality.

**Comment by timoschilling** [comment]
this is a double of #3085
