### ISSUE TITLE
Using ActiveAdmin with a neo4j graph DB

### ISSUE THREAD

**Issue by Julien-Nicault** [activeadmin/activeadmin#4403]
I have a website that is backed by a neo4j graph DB, I would like to use ActiveAdmin to generate admin pages.

Currently it seems there is a possiblility to use ActiveAdmin with mongoDB ORM.
I wondered if there is a way to use it with neo4j ORM.

Eventually, would it be hard to implement a mapper?
Where to look for a start?

**Comment by timoschilling** [comment]
There is no plan to support other ORM then active record and mongoid (mongo db).

If you have a neo4j adapter which works similar to active record you can build a adapter by copying the active record or mongoid one.
