### ISSUE TITLE
Turn off activeadmin programmatically

### ISSUE THREAD

**Issue by zocoi** [activeadmin/activeadmin#4404]
Hi

I have a rails app which was deployed to multiple instances in production. Is there any way I can turn off activeadmin during app initialization time programmatically?

Thanks

**Comment by timoschilling** [comment]
Yes:
```ruby
# routes.rb
ActiveAdmin.routes(self) unless ENV['NO_ACTIVE_ADMIN']
```

**Comment by sbleon** [comment]
@zocoi did @timoschilling's suggestion answer your question? If so, please close this issue. Thanks!

**Comment by zocoi** [comment]
thanks, it does help!
