### ISSUE TITLE
The problem with belongs_to

### ISSUE THREAD

**Issue by afuno** [activeadmin/activeadmin#4407]
There are two models - Blog and Post.

**blog.rb:**

    class Blog < ActiveRecord::Base
    	has_many :post
    end

**post.rb:**

    class Post < ActiveRecord::Base
    	belongs_to :blog
    end

**Next ActiveAdmin files:**

**admin/blog.rb:**

    ActiveAdmin.register Blog do
    	permit_params do
    		allowed = [
    			:title,
    			:description
    		]
    		permitted = *allowed
    		permitted << :other if params[:action] == 'create' && current_user.is_admin?
    		permitted
    	end
    end

**admin/post.rb:**

    ActiveAdmin.register Post do
    	belongs_to :blog
    end

Did all of this on a manual: http://activeadmin.info/docs/2-resource-customization.html#belongs-to

**As a result, getting the error:** https://habrastorage.org/files/bd9/2b7/0f6/bd92b70f6ed741ceb871ca59987bf5d4.png

Add something to the table can blogs. The only problem with belongs_to - per page: */admin/blogs/5/posts*.

What is the problem?

**Comment by jeantristan** [comment]
I have the same issue here.
The route exists in http://localhost:3000/rails/info/routes
But when i try to display it i've got undefined method error.
