### ISSUE TITLE
Unpermitted parameter: remove_screenshot

### ISSUE THREAD

**Issue by hudsonsferreira** [activeadmin/activeadmin#4411]
Hey guys,

I'm using Refile in ActiveAdmin forms. I would like to enable users to delete existing attachments on edit action following this example: https://github.com/refile/refile#removing-attached-files, where `Order#screenshot` is my attribute in question. But, the controller is returning me `Unpermitted parameter: remove_screenshot` even with following declation:
```
ActiveAdmin.register Order do
  permit_params :remove_screenshot ...
```
Refile version: 0.6.2
ActiveAdmin version:  1.0.0.pre2

**Comment by timoschilling** [comment]
What is the exact key, `remove_screenshot` or `model[remove_screenshot]` (for example: `user[remove_screenshot]`?

**Comment by timoschilling** [comment]
I would be help if you post the first lines of the request console output.

**Comment by hudsonsferreira** [comment]
It was my mistake, sorry.
