### ISSUE TITLE
No way to overide the devise function

### ISSUE THREAD

**Issue by ImDineshSaini** [activeadmin/activeadmin#4413]
I have installed active admin with multi-user role as an additional field. I have following challenges now:

- I have to create a separate login page for front-end user, not the one created by active admin.
- If i define routes devise_for users then it is saying already used routes.

Can't we just override the controller?

**Comment by timoschilling** [comment]
Thats possible, take a look on the devise readme about how to.

**Comment by ImDineshSaini** [comment]
Could you please share the link?
