### ISSUE TITLE
Remove dependency on coffeescript

### ISSUE THREAD

**Issue by wireframe** [activeadmin/activeadmin#4414]
As a Rails engine, the fewer dependencies, the better.

active admin is not a javascript heavy engine, and so including coffeescript feels like using a sledgehammer to pound a nail.

Not only does this increase application size, but it also can lead to unnecessary version conflicts when applications require certain versions of coffeescript gems.

**Comment by timoschilling** [comment]
Using coffeescript is a common practice, which has no impact on the host application and since we don't have a version requirement there is no reason to rewire every coffeescript to javascript.

**Comment by javierjulio** [comment]
Personally I'm for removing CoffeeScript. JS has come a long way now and other major gems like foundation-rails use ES6 code via sprockets-es6 gem. Definitely something worth considering for v2. I'll look into it.
