### ISSUE TITLE
remove add new button In has_many nested form

### ISSUE THREAD

**Issue by kurotyan514** [activeadmin/activeadmin#4415]
i want to remove add new button in nested form ,  i follow with documentation
set  `new_record: false` , but the problem is input textarea disappear as well
how can i solve this problem? thanks

```
form do |f|
    f.inputs "User Details"  do
        f.input :name
        f.input :description
        f.input :slug
        f.input :available_on, as: :datepicker ,datepicker_options:datepicker_options
        f.has_many :variants, new_record: false do |variants_form|
          variants_form.input :price
        end
        f.has_many :variants, new_record: true do |variants_form|
          variants_form.input :price
        end


    end
```

![activeadmin_nested_form](https://cloud.githubusercontent.com/assets/14138733/15045804/28ef5006-130f-11e6-9772-84df98a2d68c.png)

**Comment by timoschilling** [comment]
The text area only appears if you click `Add New Variant`.
Why du you list the `variants` tow times?

**Comment by kurotyan514** [comment]
thank you for your answer first

Actually i just need a `variants ` text area
list the variants two times is because i want show what different they are between 
`new_record: false` & `new_record: true`

so is any way can show the text area without click `Add New Variant`in nested form ? 
because in my case when i create a `product`data , i  also need a `variant`data as well
but i  only need add a variant data , don't need add one than more variant ,  if show the `Add new Variant` button that's mean i can keep add multiple variants , and i don't want that 
how should i do ?

here is my models

```
class Product < ActiveRecord::Base
  has_many :variants , dependent: :destroy
  accepts_nested_attributes_for :variants
  validates :name , presence: true

class Variant < ActiveRecord::Base
  belongs_to :product
end

end```

**Comment by timoschilling** [comment]
Ok, I think I know what you want, but there is no build in way to do it.

There are 2 possible solutions:
1. Overwrite the `initialize` method of your model, to initialize a default variant and in the form use `new_record: false`.
2. use `new_record: true` and write a javascript which clicks the button and then hides the button.

**Comment by grahamlyus** [comment]
Came here after trying to figure out how to have a singleton nested `has_many` resource. This may not be the OP's problem but may help others:

The first step is to initialize the object with a single `Variant` by overriding the controller's `new` action. Example uses OP's controller:

```
ActiveAdmin.register Product do
  controller do
    # automatically add an empty Variant on new.
    def new
      @product = Product.new
      @product.variants << Variant.new
      new!
    end
  end

  form do |f|
    f.inputs "User Details"  do
      f.input :name
      f.input :description
      f.input :slug
      f.input :available_on, as: :datepicker
      f.has_many :variants, new_record: false do, allow_destroy: false |variants_form|
        variants_form.input :price
      end
    end
  end
end
```

This leaves us with a Remove button that we don't want because it's a new record - there is no option to hide it, so I decided to just hide it in my `active_admin.css.scss`:

```
// Hide remove button on new product form
#new_product_form .has_many_remove {
  display: none;
}
```

**Comment by Fivell** [comment]
looks like the this can be the easiest way

```
form do |f|
   #force new input if empty
   if f.object.variants.empty?
      f.object.variants << Variant.new
    end

    f.inputs "User Details"  do
        f.input :name
        f.input :description
        f.input :slug
        f.input :available_on, as: :datepicker ,datepicker_options:datepicker_options
        f.has_many :variants, new_record: false do |variants_form|
          variants_form.input :price
        end


    end
```

**Comment by laclance** [comment]
using fields_for worked for me (note variant is singular).

```
form do |f|

    f.inputs "User Details"  do
        f.input :name
        f.input :description
        f.input :slug
        f.input :available_on, as: :datepicker ,datepicker_options:datepicker_options

        f.fields_for :variant do |variants_form|
          variants_form.input :price
        end

    end
```

**Comment by chibuezeayogu** [comment]
> looks like the this can be the easiest way
> 
> ```
> form do |f|
>    #force new input if empty
>    if f.object.variants.empty?
>       f.object.variants << Variant.new
>     end
> 
>     f.inputs "User Details"  do
>         f.input :name
>         f.input :description
>         f.input :slug
>         f.input :available_on, as: :datepicker ,datepicker_options:datepicker_options
>         f.has_many :variants, new_record: false do |variants_form|
>           variants_form.input :price
>         end
> 
> 
>     end
> ```

Thanks man this was really helpful..

**Comment by tranngoclai** [comment]
Can resolve this problem like this:

```
form do |f|
    f.inputs "User Details"  do
        f.input :name
        f.input :description
        f.input :slug
        f.input :available_on, as: :datepicker ,datepicker_options:datepicker_options
        f.has_many :variants, new_record: false do |variants_form|
          variants_form.input :price
        end
        f.has_many :variants, new_record: true do |variants_form|
          variants_form.input :price
        end
    end
```
