### ISSUE TITLE
ActionController::UrlGenerationError after saving new subscriber

### ISSUE THREAD

**Issue by dkey94** [activeadmin/activeadmin#4420]
Hi there,
I have a strange problem with saving new values in AA. What I have is just empty scaffold called subscriber. Everything works fine, except from active admin area. I've genereated new active admin resource (rails g active_admin:resource subscriver). The index page works nice, all my subscribers are on the list. The problem is with creating new subscribers. After filling the form I get 

> ActionController::UrlGenerationError in Admin::Subscribers#show 
> 
> Showing /Users/dk/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-d84f8190edac/app/views/active_admin/resource/show.html.arb where line #2 raised:
> 
> No route matches {:action=>"edit", :controller=>"admin/subscribers", :id=>#<Subscriber id: nil, email: nil, token: nil, is_active: false, created_at: nil, updated_at: nil>} missing required keys: [:id]

The subscriber model is empty, in admin/subsriber.rb i've just setted up permitted params:

> permit_params do
>     permitted = [:email, :is_active, :token]
>   end

I've got some other resources, the problem is only with subsribers.

Thanks!

**Comment by timoschilling** [comment]
please post your `Subscriver` model

**Comment by dkey94** [comment]
That's the funniest part:

> class Subscriber < ActiveRecord::Base
> end

Here is the migration of subsribers table:

> class CreateSubscribers < ActiveRecord::Migration
>   def change
>     create_table :subscribers do |t|
>       t.string :email
>       t.string :token
>       t.boolean :is_active, :default => false
> 
>       t.timestamps null: false
>     end
>   end
> end

**Comment by timoschilling** [comment]
> In SubscribersController I've removed update and edit methods. Maybe this is the reason?

Do you mean in `controllers/subscribers_controller.rb` or in `admin/subscriber.rb`?

**Comment by dikey94** [comment]
controllers/subscribers_controller.rb

**Comment by timoschilling** [comment]
that doesn't matter

**Comment by dikey94** [comment]
i'm sure it's something simple :) i don't what exactly, but this is very strange

**Comment by dkey94** [comment]
Well, there is another problem with deleting items. After clicking "delete" the page is beeing refreshed but all items are on the list.

**Comment by dkey94** [comment]
I've changed the Subscriber resource into Recipient resource and all works fine.
