### ISSUE TITLE
Is there a way to truncate a text in the index view?

### ISSUE THREAD

**Issue by Drillan767** [activeadmin/activeadmin#4421]
Hello, 
I'm not sure if my question is clear or not, but I can't find a way to be as explicit as I wish.
I use active_admin to write some articles that can be long. 
Everything is working fine, but when I go on my model's index page, I get to see the each of my articles' whole content, that are sometimes really big. 
How can I truncate the content part to, say, 200 characters ? I tried with 'truncate' but it went wrong, and I can't find anything related to this in active_admin in the documentation.

**Comment by timoschilling** [comment]
You can write a custom index like this:
```ruby
index do
  column :title
  column :text do |article|
    article.text[0...50]
  end
end
```
