### ISSUE TITLE
Optimistic Locking Not Supported

### ISSUE THREAD

**Issue by aselder** [activeadmin/activeadmin#4422]
Due to business rules, we use optimistic locking on several of our models.

Occassionally, we get lock conflicts and ActiveAdmin returns a 500 error (StaleRecordError), rather than handling this and displaying a nice message to the end user.

I'll look and see if I can put together a patch.

**Comment by timoschilling** [comment]
@aselder can you give some examples?

**Comment by aselder** [comment]
@timoschilling Sure, I'll whip up an example... 

Ideally, this would be handled similar to a validation error.

**Comment by timoschilling** [comment]
After some reading, I think Optimistic Locking is not in the scope of ActiveAdmin.
Optimistic Locking should be handeld by inherited_resources.
Workaround: https://gist.github.com/jasoncodes/1294696
