### ISSUE TITLE
new_with_cast no longer works (regression)

### ISSUE THREAD

**Issue by shaicoleman** [activeadmin/activeadmin#4424]
I have a model that uses new_with_cast (an example would be something like http://www.simple10.com/rails-3-sti/ , Option 1)

After commit 6488d6319187c1f0b1f9916cd36d76b84e40f641 , it is no longer working

**Comment by shaicoleman** [comment]
Pull request to fix it: https://github.com/activeadmin/activeadmin/pull/4426

**Comment by shaicoleman** [comment]
Pull request to fix:
https://github.com/activeadmin/activeadmin/pull/4426

**Comment by timoschilling** [comment]
Reopen, because of revert of #4426

**Comment by Fivell** [comment]
have such problem after update AA too, here 6488d6319187c1f0b1f9916cd36d76b84e40f641 changed behaviour of building resource and params are not passed to constructor now
