### ISSUE TITLE
When name is blank active_admin should not return the name but continue to until it finds a non-blank value in utlility navigation

### ISSUE THREAD

**Issue by travisdmathis** [activeadmin/activeadmin#4428]
my user table has a name, but it's not required.  If it is blank activeadmin does not handle this and returns /users/:id

to fix I had to do something like this in my user model, but i don't believe it's how it should work.  My understanding is it goes down the list starting with display_name, name, etc until it finds one that exists, but apparently doesn't check if the field actually has a value.

```
def display_name
  return self.name.blank? ? self.email : self.name
end
```

I will submit a pull request with a fix to utility navigation if you agree with me on this.

**Comment by timoschilling** [comment]
That's how it works.
https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/docs/3-index-pages/index-as-table.md#defining-columns
