### ISSUE TITLE
Make preview when create or edit an model 

### ISSUE THREAD

**Issue by vietkungfu** [activeadmin/activeadmin#4437]
I wanna make make preview pane for an model like a Blog.

Any someone has some idea ?

**Comment by bestori** [comment]
Not an issue. Are you suggesting a feature...?

**Comment by vietkungfu** [comment]
oh really!
because i cant find out the solution for this.
Hmm. It seems to be a new feature.
Thanks so much!

**Comment by varyonic** [comment]
PRs welcome but I don't really understand this.

**Comment by Fivell** [comment]
@varyonic , sounds like a question , not even well-defined feature request, +1 for closing this

**Comment by varyonic** [comment]
Feel free to reopen with more details.
