### ISSUE TITLE
Resources with models define in engine with isolate_namespace doesn't work

### ISSUE THREAD

**Issue by jonathantribouharet** [activeadmin/activeadmin#4446]
Hi,
I have an engine `MyEngine` defining a class `User`, this engine use `isolate_namespace` with

```
module MyEngine
    class Engine < ::Rails::Engine
        isolate_namespace MyEngine
    end
end
```

in the code of my application I have a file with

```
ActiveAdmin.register MyEngine::User do

    permit_params :username

end
```

But when I create or update an user, the attribute `username` is not set, I have to do this hack to make ti work:

```
ActiveAdmin.register MyEngine::User do

    # Doesn't seems to work
    permit_params :username

     # The hack I have to do
    before_save do |u|
        u.attributes = params.require(:user).permit(:username)
    end

end
```

I think the bug is because with the `isolate_namespace` option, the `route_key` return `user` whereas if the `User` model was in a simple module `MyEngine` it will be `myengine_user` and ActiveAdmin may try to read `params[:myengine_user]` instead of `params[:user]`.
The link to the docs: http://api.rubyonrails.org/classes/ActiveModel/Naming.html#method-c-route_key

**Comment by vasilakisfil** [comment]
I confirm this.
