### ISSUE TITLE
Undefined method `reorder' for Array

### ISSUE THREAD

**Issue by ahmgeek** [activeadmin/activeadmin#4449]
What should I do if I want to disable the sorting for the current scope ?
I have this :
```rb
ActiveAdmin.register Stream, as: "Classes"  do
  controller do
    def scoped_collection
       current_user.accessible_schools.map(&:grades).flatten.uniq.map(&:streams).flatten.uniq
    end
  end
end
```
the thing is I retrieve an array of the objects, I really want to display it, but I git the error of Undefined method `reorder` for the Array.
alternatively, I need to do this to get rid of the error:
```rb
  controller do
    def scoped_collection
      Stream.where(id: current_user.accessible_schools.map(&:grades).flatten.uniq.map(&:streams).flatten.uniq)
    end

```  
why I need to do all of that queries to the database ?

**Comment by timoschilling** [comment]
`scoped_collection` need's to return a query object. But there should be a better way then yours.

Take a look on ransack, with it you can write selects over different models/tables.
