### ISSUE TITLE
Ransacker in model class call twice in numeric range filter with lteq and gteq values , can't we have both values at once in ransacker.  

### ISSUE THREAD

**Issue by Hassan9229** [activeadmin/activeadmin#4450]
Hi , 

This is my filter in active admin resource.
`filter :date_of_birth, as: :filter_numeric_range`

In my model i definced this ransacker : 

`ransacker :date_of_birth, 
          :formatter => ->(v) {
            binding.pry
            puts v
            #User.where('date_of_birth > ?', DateTime.now - 4.years)
            #data = data.present? ? data : nil
           } do |parent|
      parent.table[:id]
  end`

I want to get user in range , but cannot able to get both values at once + also not anything display in table if i just write User.all in ransacker method.

**Comment by timoschilling** [comment]
You don't have a active admin problem, you have a ransacker problem.
BTW: don't do this formatter shit, I know google is full with it but it is wrong, to query data in the formatter is the wrong way!
HINT: http://stackoverflow.com/a/27788668/4152876

**Comment by Hassan9229** [comment]
Thanks for ur comment , i have seen ur answer on stackoverflow , but i want to add numeric range on datetime attribute. I want to get both range value in ransacker and i am failed to do so.

**Comment by timoschilling** [comment]
Ok, let you help on https://github.com/activerecord-hackery/ransack, if you have a `ransacker` which work for your case, came back and I will help you integrate it into active admin, but we don't have the time to help you with ransack.
