### ISSUE TITLE
self with nested resource, polymorphic assoc and custom field

### ISSUE THREAD

**Issue by kvokka** [activeadmin/activeadmin#4452]
I've explained main question here http://stackoverflow.com/questions/37517644/rails-4-2-polymorphic-nested-attributes-activeadmin-1-0-0pre2-custom-fields and I suggest that it is active admin bug(feature?).

**Comment by timoschilling** [comment]
We do not accept Stackoverflow links as issues. Feel free to create a new full qualified issue.
