### ISSUE TITLE
filtering by Created At date not working

### ISSUE THREAD

**Issue by ebbnormal** [activeadmin/activeadmin#4453]
Hello, I am trying to use the AA filters to filter by the field Created At. 

I set the ranges to be 8-1-2015 to 12-31-2015.

After I click 'Filter' I see that the filters are being applied. However the data is not actually being sorted by date as It has Created At results that are the present day.

**Comment by timoschilling** [comment]
There is no relation between filtering and sorting, if you want to sort the results, you need to create a column for it and click on it.

**Comment by ebbnormal** [comment]
I am not trying to sort, just filter by a range of dates.

On Tue, May 31, 2016 at 1:54 PM, Timo Schilling <notifications@github.com>
wrote:

> There is no relation between filtering and sorting, if you want to sort
> the results, you need to create a column for it and click on it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/activeadmin/activeadmin/issues/4453#issuecomment-222817115>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEE8iaEgLPjBLVbMLMwMmnNTRmBgOiVRks5qHJ_wgaJpZM4Iq4bo>
> .
>



-- 
ॐ नमः शिवाय

**Comment by timoschilling** [comment]
Then you need to explain your problem.

**Comment by ebbnormal** [comment]
My problem is the following. I choose a range of dates for the column
called "Created at", and then click filter. The page re-renders, showing
the current filters being the range of dates i select. However the actually
entries from the db that are displayed do not conform to the range of dates
I select. That is they are past the right bound.


On Tue, May 31, 2016 at 2:16 PM, Timo Schilling <notifications@github.com>
wrote:

> Then you need to explain your problem.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/activeadmin/activeadmin/issues/4453#issuecomment-222823455>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEE8iYaWreKoBvkD4QsgxGcUAEd2uHS0ks5qHKU6gaJpZM4Iq4bo>
> .
>



-- 
ॐ नमः शिवाय

**Comment by timoschilling** [comment]
ok, can you give a example of the range query and the wrong data?

**Comment by ebbnormal** [comment]
Created At
2015-01-01 - 2015-12-31

click Filter and then:


   - Created At greater than or equal to*2015-01-01*
   - Created At less than or equal to *2015-12-31*

Great which is what I want. But when I look at what is displayed I have
the first thing being
Created AT: May 31, 2016 01:55

On Tue, May 31, 2016 at 2:22 PM, Timo Schilling <notifications@github.com>
wrote:

> ok, can you give a example of the range query and the wrong data?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/activeadmin/activeadmin/issues/4453#issuecomment-222825043>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEE8iS3sZbBSfWnOB7kb5h25SQJbErdZks5qHKaNgaJpZM4Iq4bo>
> .
>



-- 
ॐ नमः शिवाय

**Comment by timoschilling** [comment]
Can you post the generated sql query.
How do you define the rage filter?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
