### ISSUE TITLE
Batch action button disabled

### ISSUE THREAD

**Issue by WillTaylor22** [activeadmin/activeadmin#4454]
Using activeadmin version tracking Github.

In initialisers, have set:
'''
  config.batch_actions = true
'''
And have regenerated the CSS and JS 

But for any resource, the batch actions remain disabled.

![image](https://cloud.githubusercontent.com/assets/7004983/15704861/65f9e328-27e4-11e6-8d57-f0b6b4b6c690.png)

**Comment by timoschilling** [comment]
Do you have a batch action defined?
Do you have disabled the resource delete function?
Does your browser shows a JS error?

**Comment by WillTaylor22** [comment]
Thanks for the quick reply Timo.

1. Have tried unsuccessfully with no batch action defined and with  "batch_action :destroy” registered (also I do have the selectable column)

2. Have not disabled the resource delete function - I can delete items one by one.

3. no JS error. Console is blank

**Comment by olendorf** [comment]
I am also having a similar issue. I have config.batch_actions = true, and regenerated my assets. However, I am getting a console error for the jquery.

It was working fine until recently. Also I get the same console error when I have a drop down menu in my index action items using

```
    actions dropdown: true, defaults: true
```
Console error looks like this. 

```
    has_many.js?body=1:42 Uncaught TypeError: elems.sortable is not a function
        init_sortable @ has_many.js?body=1:42
       (anonymous function) @ has_many.js?body=1:35
       fire @ jquery.js?body=1:3120
       fireWith @ jquery.js?body=1:3232
       ready @ jquery.js?body=1:3444completed @ jquery.js?body=1:3475
```

**Comment by olendorf** [comment]
I fixed my issue. I was requiring jquery in `config/initializers/active_admin.rb`. Once I removed that line it works fine. 

```ruby
      # To load a javascript file:
      # config.register_javascript 'jquery.js'
```
