### ISSUE TITLE
Basic filters not working with Rails 5

### ISSUE THREAD

**Issue by gouthamvel** [activeadmin/activeadmin#4456]
Here's a sample app: https://github.com/gouthamvel/upgraded-octo-succotash
Filters not working on simple model with name:string attribute.

Rails version: 5.0.0.rc1
Activeadmin: 1.0.0.pre2
Ruby: 2.3.0

**Comment by tmbeihl** [comment]
Hey @gouthamvel,

**Comment by tmbeihl** [comment]
Hey @gouthamvel , 
Changing your gemfile to use
`gem 'activeadmin', github: 'activeadmin'` 
fixed this for me.

**Comment by gouthamvel** [comment]
Switching to github/master works thanks 👍
