### ISSUE TITLE
html for menu label?

### ISSUE THREAD

**Issue by niksfirefly** [activeadmin/activeadmin#4464]
Is there an option to turn off html escaping for menu labels?
for example to add tag
<i class=icon"></i>

**Comment by timoschilling** [comment]
There is no way to disable escaping.

You can try this:
```ruby
menu "<b>Foo</b>".html_safe
```

Or you can hack in you tag with a javascript.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
