### ISSUE TITLE
Pop up alert is showing twice in my app admin side.

### ISSUE THREAD

**Issue by Hassan9229** [activeadmin/activeadmin#4466]
On deleting any row alert box shown twice. How to fix it,

**Comment by timoschilling** [comment]
You mean this 'Do you want do delete this row?' Javascript confirm box?

**Comment by Hassan9229** [comment]
yes

**Comment by timoschilling** [comment]
which javascript are loaded in your admin interface?

**Comment by Hassan9229** [comment]
activeadmin.js is loaded and its content is 

//= require active_admin/base

**Comment by Hassan9229** [comment]
I still not able to fix this.

**Comment by timoschilling** [comment]
please do this:
```ruby
# development.rb
config.assets.debug = false
```
And then post the complete `<head>` section from you admin interface.

**Comment by timoschilling** [comment]
sorry for closing

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
