### ISSUE TITLE
Subdomain - Decouple path from namespace

### ISSUE THREAD

**Issue by nitsujri** [activeadmin/activeadmin#4467]
Thanks guys for this great gem. This is purely a non-critical request/support.

We currently use activeadmin on: `example.com/admin`

We want to move it to: `admin.example.com/`

[This](https://github.com/activeadmin/activeadmin/issues/3911) and [this](https://github.com/activeadmin/activeadmin/issues/691) describe how to do that.

The problem is we already use the default `admin_` namespace for most things and when attempting to set the namespace to `false` the admin area clashes with the main app since `admin_organization_path` now looks just like our other `organization_path`.

Is it possible decouple the `namespace` from the `path`? i.e.

```
#routes.rb
ActiveAdmin.routes(self, path: '')
```

**Comment by timoschilling** [comment]
Your idea with `ActiveAdmin.routes(self, path: '')` can't work while `ActiveAdmin.routes(self)` draws many namespaces at once.

But we can add `config.namespace.route_options`, which will apply to the `routes.namespace`, then you can configure the `path` option.

**Comment by SaiVardhan** [comment]
@timoschilling can you suggest a road map for this to contribute.. :)
