### ISSUE TITLE
reflection.rb undefined method `klass' for nil:NilClass

### ISSUE THREAD

**Issue by spyrosavl** [activeadmin/activeadmin#4470]
reflection.rb:806 `through_reflection.klass._reflect_on_association(n)`
undefined method `klass' for nil:NilClass

**Comment by maysam** [comment]
what happened here? lol

**Comment by tootis** [comment]
I am having this trouble right now!
What should i do?

**Comment by varyonic** [comment]
See also https://stackoverflow.com/questions/46613118/rails-5-1-activeadmin-error-undefined-method-klass-for-nilnilclass

**Comment by lgm1213** [comment]
I posted that question on Stack, no one has a good resolution to it. Why is this issue closed

**Comment by varyonic** [comment]
Closed by the OP, not maintainers.  Either add more details and request it be reopened or open a new issue.
