### ISSUE TITLE
Current Filters not showing

### ISSUE THREAD

**Issue by luisbraga** [activeadmin/activeadmin#4472]
Scopes are showing in the search results panel but filter 'terms' don't show at all in any of my models.
What am I missing here? How can I debug?

**Comment by vraravam** [comment]
Same case here. Latest version of activeadmin from the github repo (master branch) - and the "current filters" section that appears below the filters always reports "none"

**Comment by cbortz** [comment]
Same. Has anyone looked into this at all?

**Comment by grubinsky** [comment]
I think the issue is being addressed on #4551

**Comment by timoschilling** [comment]
close as double of #4342
