### ISSUE TITLE
How to use sortable option of complex query

### ISSUE THREAD

**Issue by lion-man44** [activeadmin/activeadmin#4473]
Hello.

What specify to `sortable option` ?

```rb
class Group
  has_many :hoges

  # attributes
  # id, domain, created_at, updated_at
end
```
```rb
class Hoge
  belongs_to :group

  # attributes
  # id, name, created_at, updated_at
end
```

```rb
ActiveAdmin.register Group do
  ...
  index do
    column :last_one_month_of_created_hoges, sortable: ??? do |group|
      group.hoges.where('hoges.created_at >= ?', DateTime.now - 1.month).count
    end
  end
end
```

`Hoge` model is `last_one_month_of_created_hoges` column nothing.
Also `counter cache` is not use to complex query.

What specify is `sortable option`?

Thank you for reading it through.
Are your have good idea?

**Comment by timoschilling** [comment]
You can only sort by sql queries, so it doesn't make sense to make a count query inside the block.

This is not a ready solution, but it should point you in the right direction.
```ruby
controller do
  def scoped_collection
    super.select("groups.*, (SELECT COUNT(*) FROM `hoges` WHERE `hoges.id` = `groups.id` AND hoges.created_at >= <SQL_TIME_CACLULATION>) AS hoges_count")
  end
end
```
Now you can do this, with sorting out of the box and without n+1 queries:
```ruby
index do
  column :hoges_count
end
```
Pleas respect that we can not give more support on this. If the query don't work ask on Stackoverflow.

**Comment by lion-man44** [comment]
Thank you for teaching!
And sorry.
I'll try to use Stackoverflow.
