### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by Ammet** [activeadmin/activeadmin#4475]
I want to say thanks to the all developers and contributors of this gem. It's incredible! So flexible and user-friendly.
Big thanks from me and from each of developer from my team!

**Comment by SaiVardhan** [comment]
Hi @Ammet 
I am a mid level engineer and planning for contribution to develop my skills.
Are there any open issues if so can you suggest one to kick start my contribution.

Thanks in advance !!

**Comment by muhammednagy** [comment]
hello i have a small issue if u can help 
i wanna add first name and last name to the activeadmin table

**Comment by SaiVardhan** [comment]
sure .. can you give me road map of it @muhammednagy 

you can reach me saimca03@gmail.com

**Comment by timoschilling** [comment]
@ammet thanks for your tribute! I wish there are more people like you wich honor our work...
