### ISSUE TITLE
ActiveAdmin using the wrong HTTP Method?

### ISSUE THREAD

**Issue by jtmarmon** [activeadmin/activeadmin#4476]
I'm using ActiveAdmin (master) on Rails 4.2 with rails-api. I've done all the proper configuration so that AA works properly. I can use index pages, show, use the edit form, etc. But when it comes time to take a destructive action, for some reason AA uses POST instead of the proper http verb. The result is a 404:

> No route matches [POST] "/admin/admin_users/1"

When I copy the request as a cURL via the chrome console, modify the HTTP method from POST to DELETE, everything works properly and the user is deleted. So why is ActiveAdmin using POST?

**Comment by timoschilling** [comment]
Whats result of `rake middleware` in your app?

**Comment by jtmarmon** [comment]
```
use Rack::Cors
use ActionDispatch::Static
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007fc630b59f98>
use Rack::Runtime
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Rollbar::Middleware::Rails::RollbarMiddleware
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use ActionDispatch::Flash
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
run MyApi::Application.routes
```

**Comment by jtmarmon** [comment]
Also, to clarify, this happens when I perform the edit action as well as delete. I can view the edit page, but when the form is submitted, it's a POST request with `_method=PATCH` in the body, but rails receives it as a POST

**Comment by tmbeihl** [comment]
Need to be using Rack::MethodOverride as part of your middleware stack

**Comment by jtmarmon** [comment]
@tmbeihl i added that in my config, re-ran rake routes to confirm it's there, restarted server, and the error has not gone away

**Comment by jtmarmon** [comment]
just kidding - there error has gone away, replace by a different unrelated issue. thanks everyone!
