### ISSUE TITLE
show_comments_in_menu config option gone without deprecation

### ISSUE THREAD

**Issue by duksis** [activeadmin/activeadmin#4479]
the config option for disabling admin comments in menu is working on v1.0.0.pre2 but crushing on master

would be great to have a deprecation message with alternatives.

```ruby
ActiveAdmin.setup do |config|
  config.show_comments_in_menu = false
end
```

❤️ Thanks a lot guys/girls for active admin! - has saved me a lot of time

**Comment by pynixwang** [comment]
i also run into this issue

**Comment by FranckKe** [comment]
For anyone wondering, it has been changed for 

```Ruby
ActiveAdmin.setup do |config|
  config.comments_menu = false
end 
```
See #4187

**Comment by timoschilling** [comment]
We have change log entry for that
