### ISSUE TITLE
Safari autofilling email / password fields

### ISSUE THREAD

**Issue by habermeier** [activeadmin/activeadmin#4480]
We have a situation where an admin may edit all fields of a user record, such as email and password. Safari is being insistent on pre-filling out email field, overriding a perfectly good pre-filled input with the user's own email. auctomopelte=off is ignored.

There are some workarounds: http://stackoverflow.com/a/24471266/1131764 -- similar to other suggestions that go all the way back to 2014. The basic idea is to include fake email / password fields that are offscreen.

All those solutions require silliness that I could implement with HTML by hand easily enough, but I'm really unclear on how to get this to work from a form that looks like this:

```
 form :html => { autocomplete: 'off'} do |f|
    f.inputs 'Member Details' do
      f.input :first_name, :input_html => { autocomplete: 'off' }
      f.input :last_name, :input_html => { autocomplete: 'off' }
      f.input :email, :label => "User Email", :input_html => { autocomplete: 'off', type: 'text' }
      f.input :password, :input_html => { autocomplete: 'off' }
      f.input :password_confirmation, :input_html => { autocomplete: 'off' }
...
end
```

note: I tried to override type: 'email' and remove autocomplete on the form itself as well the inputs.  No luck on Safari.  Chrome is OK though.

Any help would be appreciated.

This is the crosspost: https://github.com/justinfrench/formtastic/issues/1222

**Comment by seanlinsley** [comment]
@habermeier when cross-posting to multiple repos, please link them together.

https://github.com/justinfrench/formtastic/issues/1222

**Comment by seanlinsley** [comment]
Have you tried `f.input :password, as: :string`?

**Comment by habermeier** [comment]
@seanlinsley Thanks for the suggestion on posting the cross-post.  I did it now on both posts.  Unfortunately the only trick that seems to work is to render email and password fields off-screen (absolute, negative positioning have been shown to work).  It's obviously a pretty lame hack, but apparently this issue has been around for years in Safari.

I've only just noticed it because I finally got around to switching my server to using https:// -- which I think is a requirement for Safari to auto-populate fields. (I think).  

Anyhow, I'm a bit stuck as to how to implement that work-around.  Another SO article describes the work-arounds: http://stackoverflow.com/a/36809898/1131764

Most of the work-arounds have to do with adding fake entries.  My particular issue is with the `email` and `password` fields -- which we definitely do not want to pre-populate with the administrative users email / password.

For now I've asked our admin to use Chrome, but it's kind of crazy overall.  So I'd love some thoughts on how I could do this within the activeadmin framework.

**Comment by habermeier** [comment]
Is there a way I could have the field names be something that differs from what it's in the database?  With that I don't mean the labels, but the name of the fields?  My guess is if I could call the field names something else it might also work.  Someone suggested adding random numbers into the field names... obviously if that works, I'd need a way to convert it back to the actual names that the rest of code is expecting.

**Comment by justinfrench** [comment]
I've provided some pure-HTML guidance over on the Formtastic thread, but wanted to chime-in here too.

> Is there a way I could have the field names be something that differs from what it's in the database?

Yes. Basically, you would create "alias" attributes/accessors in your model (e.g. `User#special_email`, `User#special_password`), use those in the form (`f.input :special_email`) and then have a before_validation hook on the model to shuffle the data around to the right attributes. Totally awful busy work, but it's possible.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
