### ISSUE TITLE
scoped_collection issue

### ISSUE THREAD

**Issue by ahmgeek** [activeadmin/activeadmin#4482]
I have an issues in scoped_collection, when I specify a specific set to retrieve, simply like:
```ruby
    def scoped_collection
      School.where(id: current_user.accessible_organizations.map(&:schools).flatten.uniq)
    end
``` 
the new `school` always getting me this error:
```
::UniqueViolation: ERROR: duplicate key value violates unique constraint "schools_pkey" DETAIL: Key (id)=(3) already exists. : INSERT INTO "schools" ("id", "organization_id", "name", "description", "address", "location", "telephone_number", "mobile_number", "postal_code", "area", "city", "country", "account", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING "id"
```
it's already inserting and id that's already there.

**Comment by timoschilling** [comment]
You get this error if you create a new school?

**Comment by timoschilling** [comment]
Did the same happen if you don't overwrite `scoped_collection`?

**Comment by ahmgeek** [comment]
no, I figured out that if I added 'scoped_collection', I must override the default actions in controller, like `create' '`update' as scoped_collection override all the controller action ?
so I override'd them, it worked, but I created some redundant actions :cry: 

thing is, I must include scoped_collection too, as it behave exactly as I wanted..

**Comment by timoschilling** [comment]
Try this:
```ruby
    def scoped_collection
      end_of_association_chain.where(...)
    end
```
or
https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/docs/2-resource-customization.md#scoping-the-queries

**Comment by ahmgeek** [comment]
it didn't work too, I still get the
 ```
::UniqueViolation: ERROR: duplicate key value violates unique constraint "schools_pkey" DETAIL: Key (id)=(3) already exists. : INSERT INTO "schools" ("id", "organization_id", "name", "description", "address", "location", "telephone_number", "mobile_number", "postal_code", "area", "city", "country", "account", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING "id"
``` 
error, I needed to override the new, create action as usual..
