### ISSUE TITLE
Can't sort tables

### ISSUE THREAD

**Issue by davidalejandroaguilar** [activeadmin/activeadmin#4483]
I'm trying to add a table at the dashboard page where admins can sort by _viewed_ orders and act accordingly.

Unfortunately, there's no documentation on sorting tables.

Based on Google research, I've come along this pretty straigtht-forward code:
```

    section h2 "Recent Completed Orders" do
      table_for Order.where(order_status_id: 2).order("purchased_at desc").limit(5), sortable: true do
        column "Order Number", :id do |order|
          link_to "Orden ##{order.id}", view_admin_order_path(order), method: :put
        end
        column :user
        column :total do |order|
          number_to_currency order.total
        end
        column :purchased_at, sortable: :purchased_at do |order|
          order.purchased_at
        end
        column :viewed, sortable: :viewed
      end
      span link_to "View recent orders", admin_orders_path
    end
```

However, for some reason, neither _purchased at_ nor _viewed_ columns are able to be sorted. In fact, the table is not sortable at all.

**Comment by grubinsky** [comment]
I'm not sure if activeadmin provides the sorting on table_for out of the box. I couldn't find it in the past, so I ended up did it manually:
```
order_expr = if params[:order]
  params[:order].gsub(/[^a-z_]/,'').gsub(/_(asc|desc)$/, ' \1') #sanitize and convert to order expression
else
  "purchased_at desc" #default
end

table_for Order.where(order_status_id: 2).order(order_expr).limit(5), sortable: true do
```

And if you set the option class: 'index_table' on the table_for you will get the arrows pointing the sort direction on the column header.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by borenho** [comment]
Hi guys, if anyone finds themselves here again, i found a helpful solution from Ryan Bates' screencasts. Just call the order function and pass the column name with which you'd like to have it sorted, and the how(desc or asc).

```
table_for boat.bookings.order('created_at desc') do
  column :name
  column :created_at
end
```

**Comment by AlphaFayme** [comment]
> Hi guys, if anyone finds themselves here again, i found a helpful solution from Ryan Bates' screencasts. Just call the order function and pass the column name with which you'd like to have it sorted, and the how(desc or asc).
> 
> ```
> table_for boat.bookings.order('created_at desc') do
>   column :name
>   column :created_at
> end
> ```

I think this was not the expected answer of the original question since i haven't been able to sort my table according to a column inside dashboard @kaka-ruto
