### ISSUE TITLE
before_batch_import and after_batch_import options

### ISSUE THREAD

**Issue by wolfieorama** [activeadmin/activeadmin#4484]
Hello, my apologies if this has been covered elsewhere, i was trying to figure my way thro active admin admin plugins to be specific active_admin_import. 

My challenge is how would i import nested resources i.e An order and order items without having to two separate imports, id this possible in one go ? I have a feeling i can tinker with this code and refactor but not sure how 

`ActiveAdmin.register Post  do
        active_admin_import validate: true,
        before_batch_import: proc { |import|
           import.file #current file used
           import.resource #ActiveRecord class to import to
           import.options # options
           import.result # result before bulk iteration
           import.headers # CSV headers
           import.csv_lines #lines to import
           import.model #template_object instance
        },
        after_batch_import: proc{ |import|
           #the same
        }
    end`

any tips welcome

**Comment by timoschilling** [comment]
You can get support for `active_admin_import` here: https://github.com/activeadmin-plugins/active_admin_import
