### ISSUE TITLE
Your version releasing schedule is laughable and indefensible

### ISSUE THREAD

**Issue by joelmichael** [activeadmin/activeadmin#4487]
You somehow managed to go the entirety of Rails 4 without releasing a version. You have been "working on 1.0.0" for years now. You are the only gem I can think of that **requires that its users track master in production**. When I called you out about it politely, you did nothing. So here's an insult. You have let us all down. Get with the program, people, you should be embarrassed over this ridiculous behavior.

**Comment by timoschilling** [comment]
Our goal is too release 1.0 if all bugs are gone. We put all the time we have into this project, to make other developers life easier. If you want a stable 1.0 version, close all bugs and we will release a 1.0 version! Other wise you should life with what you give you for free. This is OpenSource and not a Product with support your are paying for! If you don't accept that you should stop using our OpenSource Project and maybe others OpenSource Project too, and starting building your own shit.

Love it, change it or leave it...
