### ISSUE TITLE
Tabbed Navigation with relative_url_root

### ISSUE THREAD

**Issue by gustavobn** [activeadmin/activeadmin#4488]
- When deploying to a subdirectory with Nginx or Apache, main `TabbedNavigation` ignores the controller's `relative_url_root`

Eg:

1. Code is deployed to http://example.com/my-app

2. All navigation links ignore `my-app` namespace causing routing errors.

**Comment by timoschilling** [comment]
closed because of https://github.com/activeadmin/activeadmin/issues/101#issuecomment-63240288
