### ISSUE TITLE
Mount ActiveAdmin routes to a different path other than "/admin"

### ISSUE THREAD

**Issue by nlively** [activeadmin/activeadmin#4495]
Is it possible to use a path other than "/admin"?  Please advise.

**Comment by dlackty** [comment]
You can try [changing namespace](https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/docs/1-general-configuration.md#namespaces) to achieve this.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by i7an** [comment]
```ruby
// config/initializers/active_admin.rb
ActiveAdmin.setup do |config|
   config.default_namespace = :foo_bar
end
```
