### ISSUE TITLE
I can't add a link in a flash message

### ISSUE THREAD

**Issue by luctus** [activeadmin/activeadmin#4496]
I'm trying to add a link to the notice flash message, when I save a resource.
I have this code:
```rb
  if @product.save
    redirect_to products_path, notice: "#{@product.title} was saved. #{view_context.link_to("Edit again", edit_product_path(@product))}".html_safe
```
But the link is being escaped... (even if I use the html_safe method)

I'm using Rails 4.2.1 and ActiveAdmin 1.0.0.pre2

**Comment by timoschilling** [comment]
The reason that rails escape and serialize the flash message, this issue is out of scope of active admin.

**Comment by futuretap** [comment]
Would love how to do this, too. @luctus did you find a solution in the meantime?

**Comment by kuchick** [comment]
found dirty solution here
https://stackoverflow.com/questions/55588739/add-link-to-a-flash-notice-in-rails-activeadmin-view
```
class ActiveAdmin::Views::Pages::Base
  def build_flash_messages
    div class: 'flashes' do
      flash_messages.each do |type, message|
        div message.html_safe, class: "flash flash_#{type}"
      end
    end
  end
end

**Comment by futuretap** [comment]
I found that too, thanks.
