### ISSUE TITLE
Associated Scopes not working until I made any change in register file

### ISSUE THREAD

**Issue by Asnadatta** [activeadmin/activeadmin#4500]
I have two models, restaurant and cuisine with a many to many association. And I have this in my app/admin/restaurant.rb
```ruby
ActiveAdmin.register Restaurant do
  scope("All"){|scope| scope.order("created_at desc")}
  Cuisine.all.each do |c|
     scope(c.name) { |scope| scope.joins(:cuisines).where("cuisines.id=?",c.id)}
  end
end
```
The problem is whenever I delete or add a new cuisine the scopes do not change until I make a change to my admin/restaurant.rb file. How can I fix this issue?
I have also asked this question [here](http://stackoverflow.com/questions/38070110/associated-scopes-not-working-until-i-made-any-change-in-register-file)

**Comment by timoschilling** [comment]
You can't define dynamic scopes. Maybe you can solve your Problem with filters.
