### ISSUE TITLE
any blockers for a release?

### ISSUE THREAD

**Issue by darix** [activeadmin/activeadmin#4501]
just wondering because the last release, even the pre. is really old.

maybe also bump deps in the gemspec where possible.

**Comment by timoschilling** [comment]
I have mate a new pre version now (1.0.0.pre3).

Hope we will release a final version very short.

**Comment by timoschilling** [comment]
@darix what version bumps do you suggest?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
