### ISSUE TITLE
Left sidebar not displaying properly

### ISSUE THREAD

**Issue by sjtilney** [activeadmin/activeadmin#4502]
When I move the sidebar to the left side, it pushes the table below it. Any idea what can be causing this?

config/initializers/active_admin.rb
```
 config.before_filter do
    left_sidebar! if respond_to?(:left_sidebar!)
  end
```

assets/stylesheets/active_admin.scss
`@import "active_admin_sidebar/index";`

Gemfile
```
gem 'activeadmin', github: 'activeadmin'
gem 'devise'
gem 'active_admin_sidebar', '0.0.5'
```

<img width="1048" alt="screen shot 2016-06-28 at 9 21 10 am" src="https://cloud.githubusercontent.com/assets/9960124/16423942/e9423a3a-3d12-11e6-9067-19310b1577ed.png">

**Comment by timoschilling** [comment]
wrong repository, ask your question here: https://github.com/activeadmin-plugins/active_admin_sidebar
