### ISSUE TITLE
custom datetime format

### ISSUE THREAD

**Issue by cle61** [activeadmin/activeadmin#4503]
Hello,
i would like to custom my datetime field to change the format of the date like this : 
`input :date, as: :just_datetime_picker, datepicker_options: {dateFormat: 'dd/mm/yy'}`

how can do this ?

thanks

**Comment by timoschilling** [comment]
This should work:
```ruby
input :date, as: :just_datetime_picker, input_html: { dateFormat: 'dd/mm/yy' }
```
That should result in:
```html
<input ... dateFormat="'dd/mm/yy"/>
```

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
