### ISSUE TITLE
action_item not showing

### ISSUE THREAD

**Issue by yoonwaiyan** [activeadmin/activeadmin#4507]
I want to add two action items to show the link to logs:

```ruby
  action_item :fulfillment_logs, only: :show do
    link_to 'View Fulfillment Logs', admin_source_fulfillment_logs_url(source)
  end

  action_item :sync_logs, only: :show do
    link_to 'View Sync Logs', admin_source_sync_logs_url(source)
  end
```

but my resource show page isn't showing up the link.
The weird thing is that the action item block is generated as two same blank containers:
```html
  <span class="action_item">
    <source>
  </span>
```

Is this a bug?

**Comment by timoschilling** [comment]
Is this still a issue?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
