### ISSUE TITLE
I can't acess Admin Dashboard

### ISSUE THREAD

**Issue by isaacguerreir** [activeadmin/activeadmin#4512]
I have using a open source project with ActiveAdmin. I don't know how acess the admin dashboard. I don't know the admin login and password.

Why acess admin resources?

**Comment by JMCQ87** [comment]
By default, it will be at /admin.

If you have database access and ActiveAdmin has a standard devise setup, you can simply create a new row in the "users" table with your email and then send yourself a password reset mail.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
