### ISSUE TITLE
`inputs` helper ignores all attributes except `:class`

### ISSUE THREAD

**Issue by afurmanov** [activeadmin/activeadmin#4516]
I upgraded to latest version of AA - '1.0.0.pre4'
and code below started to work differently:
```
ActiveAdmin.register Post do
  form title: 'My Title' do |f|
    inputs 'My Details', class: 'my_class', style: 'my_style' do
      input :content, label: "My Content"
    end
  end
end
```
It used to generate:
```
<fieldset class="my_class" style="my_style">....</fieldset>
```

But now the `style` attribute gets dropped and it generates:
```
<fieldset class="my_class">....</fieldset>
```

I believe the code responsible for such behavior is: 
https://github.com/activeadmin/activeadmin/blame/master/lib/active_admin/views/components/active_admin_form.rb#L58
and 
https://github.com/activeadmin/activeadmin/blame/master/lib/active_admin/views/components/active_admin_form.rb#L103

It is worth noting the Formtastic code generating same form does not drop `style` attribute:

```
<%= semantic_form_for @post do |f| %>
  <%= f.inputs :name => "My Details", :class => 'my_class', :style => 'my_style' do %>
    <%= f.input :content %>
    <%= f.input :published_at %>
  <% end %>
<% end %>
```

The generated HTML is:
```
<fieldset class="my_class" style="my_style">...</fieldset>
```

The only workaround I found is to write somewhat like:
```
ActiveAdmin.register Post do
  form title: 'My Title' do |f|
    inputs 'My Details', class: 'my_class', style: 'my_style', for: f.object do |f|
      f.input :content, label: "My Content"
    end
  end
end
```

In that case  ActiveAdmin just redirects `inputs` helper to the Formtastic form builder. I'd prefer to fix this, because
1. The `inputs` helper behavior is different than  Formtastic one
2. It breaks old code

But not sure what the proper fix would be.

**Comment by timoschilling** [comment]
double of #3954
