### ISSUE TITLE
Readme update: use DatabaseCleaner/database_cleaner instead of pschambacher/database_cleaner in Rails 5

### ISSUE THREAD

**Issue by ro4tub** [activeadmin/activeadmin#4521]
before:
`gem 'database_cleaner',            github: 'pschambacher/database_cleaner', branch: 'rails5.0', ref: '8dd9fa4'`

after:
`gem 'database_cleaner',            github: 'DatabaseCleaner/database_cleaner'`

ref #4177

**Comment by seanlinsley** [comment]
It would've been just as easy to create a PR 😄 

I fix this in #4522
