### ISSUE TITLE
Inheriting layout

### ISSUE THREAD

**Issue by ahmgeek** [activeadmin/activeadmin#4523]
Building a custom form with
 ```ruby
  form partial: 'new'
```
and custom `erb` file, it doesn't inherit activeadmin layout, when I put this in the controller
```ruby
  controller do
     layout 'active_admin', only: [:new, :edit]
  end
```
it goes in a loop and hangs the server, how can I inherit the layout in any custom form ?

**Comment by prasadsurase** [comment]
@ahmgeek You want a custom page for _new_ with a custom _active_admin_ layout?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
