### ISSUE TITLE
Display behavior of columns defined as a block changed unexpectedly

### ISSUE THREAD

**Issue by swrobel** [activeadmin/activeadmin#4524]
Something in [this commit](https://github.com/activeadmin/activeadmin/commit/3efb359533df46e76bb4355a02ad31e727fb0da3) changed the display behavior of columns defined as a block:

Code

``` ruby
index do
  column :users do |event|
    event.users.each do |user|
      if can? :read, user
        link_to user.name, admin_user_path(user)
      else
        user.name
      end
    end
  end
end
```

Output before this commit:
**USERS** [Stefan Wrobel]()

Output after this commit:
**USERS** [Stefan Wrobel]() #User:0x007fe2a3129fe8

It seems that it's inspecting the user record after outputting what's specified in the block. Any ideas why this is happening? We've had to roll back to 1.0.0.pre2

**Comment by Fivell** [comment]
@swrobel , is it still an issue using master branch ?

**Comment by swrobel** [comment]
No, the behavior is different, though. I realize my last example was unnecessarily complex. Here's a better one:

```ruby
index do
  column 'Users' do |org|
    org.users.each do |user|
      user.name
    end
  end
end
```

Output in 1.0.0.pre2:
`Stefan Wrobel`

Output in 1.0.0.pre4:
`#<User:0x007fe2a3129fe8>` (seems to be calling user.to_s)

Output in current master:
`[#<User id: "74b0fab1-c79e-488e-ac8b-855a195bf482", name: "Stefan Wrobel"]` (seems to be calling user.inspect)

**Comment by Fivell** [comment]
@swrobel  , there is workaround by @timoschilling  https://github.com/activeadmin/activeadmin/issues/4653#issuecomment-255071731

```ruby
index do
  column 'Users' do |org|
    org.users.each do |user|
      user.name
    end
    nil
  end
end

```

**Comment by timoschilling** [comment]
@Fivell It's not a arbre bug

**Comment by Fivell** [comment]
@timoschilling , than this commit can be a reason https://github.com/activeadmin/activeadmin/commit/91392b708da0c23e914523d5a8bde17d9fec121c

**Comment by Fivell** [comment]
@kaspth, do you have this issue ?

**Comment by kaspth** [comment]
Already in deep with Rails issues, so I can't commit much time unfortunately.

Do we know for sure if it's 91392b7 or 3efb359 causing this?

Personally, without having looked at this code since that July last year, I'd probably revert both those commits. Since 3efb359 unintentionally removed the autolinking from models mentioned as the cause for 91392b7, which was the big issue for us when upgrading from pre2 to pre4 (and seems a strange thing to break in a prerelease).

My 2 cents, thanks! ❤️

**Comment by Fivell** [comment]
@kaspth , don't know yet exactly, I will test it on the weekend

**Comment by Fivell** [comment]
@swrobel , @kaspth  I think proc should be evaluated in arbe context to fix this.

this method https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/lib/active_admin/view_helpers/display_helper.rb#L55

now we have
```ruby
  def find_value(resource, attr)
        if attr.is_a? Proc
          attr.call resource
        elsif attr =~ /\A(.+)_id\z/ && reflection_for(resource, $1.to_sym)
          resource.public_send $1
        elsif resource.respond_to? attr
          resource.public_send attr
        elsif resource.respond_to? :[]
          resource[attr]
        end
      end
```

and should be


```ruby
 def find_value(resource, attr)
        if attr.is_a? Proc
          Arbre::Context.new { attr.call resource }
        elsif attr =~ /\A(.+)_id\z/ && reflection_for(resource, $1.to_sym)
          resource.public_send $1
        elsif resource.respond_to? attr
          resource.public_send attr
        elsif resource.respond_to? :[]
          resource[attr]
        end
      end
```

**Comment by Fivell** [comment]
however this can break other edge cases

**Comment by kaspth** [comment]
If that works 👍 by me. Other edge cases can be dealt with if/when we see them would be my call :)

**Comment by zorab47** [comment]
The example above is returning the collection of Users for the column's value due to the behavior of `each`. Because the collection doesn't respond to one of the pretty format methods, it is being rendered via `to_s`.  Using `map` instead would return a string and work as expected.

```ruby
  column 'Users' do |org|
    org.users.each do |user|
      user.name
    end # returns org.users collection
  end
```

would become

```ruby
  column 'Users' do |org|
    org.users.map { |user| user.name }.join # returns String
  end
```

**Comment by zorab47** [comment]
I don't see this as an issue with ActiveAdmin's output, although it is strange that the output changed between commits.
