### ISSUE TITLE
Exports should probably be improved

### ISSUE THREAD

**Issue by kiddrew** [activeadmin/activeadmin#4525]
I've tried out the CSV and JSON exports, and they both have their own unique issues.

CSV - doesn't include any foreign keys.

JSON - only includes a single page of data.

The second one I sort of get, but the first one makes absolutely no sense to me.  Even stranger is why the two exports would be different in any way other than format.

**Comment by timoschilling** [comment]
How should we include `foreign keys`?

**Comment by kiddrew** [comment]
Just include them verbatim.  If an object belongs to a user, it should have a `user_id` field, but the CSV doesn't include that.

**Comment by timoschilling** [comment]
You can customize the CSV http://activeadmin.info/docs/4-csv-format.html
