### ISSUE TITLE
Creating a link to a status_tag using link_to causes the tag to render twice

### ISSUE THREAD

**Issue by dschwetz** [activeadmin/activeadmin#4526]
Hey guys, thanks for putting in the time on this project.

I've recently found that using `status_tag` inside the `link_to` method -- trying to create a hyperlink on a status tag -- causes the tag to render twice. Once immediately before the `<a href>`, and once inside the link.

I wrote about this issue more extensively here, thinking it might be something I was doing wrong: http://stackoverflow.com/questions/38360601/using-activeadmins-status-tag-in-a-link-to-method-causing-the-tag-to-render-twi

But basically, putting this:
`link_to status_tag('test', label: 'testing', class: 'error'), edit_admin_bar_path(hh.bar)`

in a column in an index block within an ActiveAdmin resource yields this html:

```
<span class="status_tag test error">testing</span>
    <a href="/admin/bar/1/edit">                          
       <span class="status_tag test error">testing</span>
    </a>
```

It's fallen flat on SO, and looking into it further I'm wondering more if its a bug. I'm working with version 1.0.0.pre2 (0ac35b7). Thanks for any help.

**Comment by timoschilling** [comment]
In with context do you try this?

**Comment by dschwetz** [comment]
I'm using it specifically in the AA index page from within a column block -- I haven't tested it elsewhere:

```
ActiveAdmin.register Foo do
   index do
      column "Bar" do
         link_to status_tag('test', label: 'testing', class: 'error'), '#'
      end
   end
end
```

I'd expect this to give one tag with a hyperlink, but it instead produces two tags -- one before, and one after.

**Comment by timoschilling** [comment]
Can you try this:
```ruby
ActiveAdmin.register Foo do
   index do
      column "Bar" do
         link_to '#' do
           status_tag('test', label: 'testing', class: 'error')
         end
      end
   end
end
```

**Comment by dschwetz** [comment]
That code does produce only one `status_tag`, but it is not hyperlinked at all. 

The resulting html from that snippet: 
```html
<td class="col col-bar">
   <span class="status_tag test error">testing</span>
    <a href="#"></a>                          
</td>
```

**Comment by grubinsky** [comment]
You could use the "a" Arbre element so everything would be written on the same buffer

    a href: '#' do
      status_tag('test', label: 'testing', class: 'error')
    end
