### ISSUE TITLE
Streaming CSV mixin prevents passing options hash to index action

### ISSUE THREAD

**Issue by lserman** [activeadmin/activeadmin#4535]
InheritedResources accepts an options hash when calling `super` from a controller action. These options are piped into `respond_with`. I'm using ActiveModelSerializers and want to use a custom serializer for my index action when I pull it down as JSON, so I was hoping I could do:

```
controller do
  def index
    super serializer: MyCustomSerializer
  end
end
```

This cannot be done on the index action because `ActiveAdmin::ResourceController::Streaming` is mixed in, and it's index method does not accept any arguments.

**Comment by varyonic** [comment]
Did you figure out a workaround for this?

**Comment by javierjulio** [comment]
Closing out as stale. Please update or submit a new PR if you can!
