### ISSUE TITLE
Problems with datepicker input

### ISSUE THREAD

**Issue by jtmarmon** [activeadmin/activeadmin#4540]
![image](https://cloud.githubusercontent.com/assets/4528076/16967904/9cbbc140-4dd9-11e6-8923-0abf5e8bd9de.png)

When using a custom ransack scope for a filter, along with `as: :datepicker`, the formatting gets screwed up. 

**Issues:**
1. The element is an `li` instead of a `div`, giving it a list element bullet
2. There is spacing missing margin on the bottom. This can be resolved by adding the `filter_form_field`  class to the `li`
3. The element has the `required` class on it. I can get around this by adding `required: false`, but I don't see why that should be necessary

**Comment by jtmarmon** [comment]
this isn't specific to using a custom filter. any `as: :datepicker` filter will break this. repro case here:

https://github.com/jtmarmon/activeadmin-4540-repro

**Comment by grubinsky** [comment]
The available input types for filters are supposed to be [here](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs.rb#L/-L17)

So I think that using `:date_picker` instead of `:datepicker` should be what you are looking for.

**Comment by jtmarmon** [comment]
seems like a bug then that `:datepicker` is allowed?

**Comment by grubinsky** [comment]
It seems so. Because using an input type that not targeted to be a filter is generating an inconsistent markup for filter form.
But on the other side, not restricting the input types you can use will allow you to customize the filters with lot of possibles types directly from Formatastic.

**Comment by Fivell** [comment]
looks like ```datepicker``` was designed to be used only in forms. but ```ActiveAdmin::Filters::FormBuilder``` is picking it because ```::ActiveAdmin::Inputs``` namespaces is also used for filters. 

https://github.com/activeadmin/activeadmin/blob/74163a81d838e062233ed40e03a93a9cd33b3bea/lib/active_admin/filters/forms.rb#L7

**Comment by Fivell** [comment]
@timoschilling , can you take a look if this is desired behaviour or we should remove  ```::ActiveAdmin::Inputs``` namespace  from the filters  form builder.
