### ISSUE TITLE
install from devise user admin axisting allready

### ISSUE THREAD

**Issue by jerome-diver** [activeadmin/activeadmin#4541]
Hi, i just install this gem. Before install it, i had allready devise user and admin user routes.
Nothing talk about that, but now i had many problems (some of them unresolved):
1/ migration add columns to user table (i had to remove migration file, columns allready exist when you allready use devise for user...)
2/ now i have two same routes "double as:" directions on same user
3/ i removed/commented the concerned adminActive part of routes (and also try to only remove my devise user routes), but not works, something has been break by the installation.
4/ then i try to look at the doc for "uninstall or remove" key word to follow the "hwo to remove adminactive... but there is not. Looks like there is no documentation plan for going back...

Please, tell me how to:
1/ going back to first initial clean position (position before i install this gem was clean)
2/ how t install when devise and user with admin session is allready used.

Thank you for help and maybe for put these information in the doc.

**Comment by timoschilling** [comment]
Uninstall:
1. remove `app/admin`
2. remove `config/initializers/active_admin.rb`
3. remove all ActiveAdmin code from `config/routes.rb`
4. make a reverse migration or delete the migration file, depending on you DB state.
5. remove `gem 'activeadmin'` from your gemfile

Install after devise is already installed: We can't give a manual for that. How do you install it depends on what you want.

The double devise migration issue is not our foult, we just run the devise installer.

**Comment by jerome-diver** [comment]
hi timoschilling, and thank you for your quick reply.
So... if i remove app/admin, i remove also my old files (i understand now that activeadmin write on the old ones... is it ?), then that is why my user devise connection is broken now.
cool... why nothing is writing on that ? maybe now you maybe want to profit my story (and maybe some other ones in same situation) for write something on that... yes ?

You have to seriously talk about that and take care of facts, then situation of people had allready Devise installed with maybe presence of routes on /app/admin for admin users... because it is a way to use devise from devise doc too... it is not something new.

Sure double issue is not your fault... it is the fault of no one in fact (it serve nothing to search a person/team/dev to be guilty, i'm not policeman to... this resolve nothing), double route issue is a problem to car about for do better. For your gem application, just because in real world, i'm not the only one to use devise before use admin_active gem.
So because the situation exist and it is not an exception, you have to care about that i think.
but... it's up to you to realize or not.
anyway... i loos my time with that i think, thank you, admin_active broke my application and make me loose time, i will use it for sure, but i know now that i have to not trust to much your poor doc.

**Comment by jerome-diver** [comment]
and the next question stay: "how to install this gem if you allready have a devise gem with user with admin ?" (tell me the page in the doc, i not see...)
or do i need to open an other issue for that (i think this should interest some other dev/users) ?

**Comment by timoschilling** [comment]
PR's for the docs are welcome.

**Comment by jerome-diver** [comment]
Is it an answer for this question:
"how to install this gem if you allready have a devise gem with user with admin ?"

**Comment by timoschilling** [comment]
Run the active admin installer with `--skip-users`
