### ISSUE TITLE
"No route matches PATCH" or "DELETE" when using a model called "Collection"

### ISSUE THREAD

**Issue by snoopdouglas** [activeadmin/activeadmin#4544]
I'm dealing with a model called `Collection` in ActiveAdmin. `index, new, show, edit` methods work absolutely fine, but `update` and `destroy` do not, because the `/:id` seems to be being omitted from the end of paths.

For instance, here is the opening code from the form tag when editing one of these models:

```
<form novalidate="novalidate" class="formtastic collection" id="edit_collection" action="/collections" accept-charset="UTF-8" method="post">
  <input name="utf8" type="hidden" value="✓">
  <input type="hidden" name="_method" value="patch">
```

If I use the inspector to alter the `action` attribute to `"/collections/3"`, the model updates successfully when the submit button is clicked.

(nb. I am not using a global namespace for ActiveAdmin here.)
### Workaround

Register the model under a different name with ActiveAdmin, eg.:

```
ActiveAdmin.register Collection as: 'collection_thing' do
  ...
```

**Comment by prasadsurase** [comment]
This error is reproducible. [this](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/views/pages/form.rb#L39) method is causing the issue. The _resource_path(resource)_ returns _/collections_ instead of _/collections/:id_.

**Comment by Fivell** [comment]
@timoschilling ,  I can't reproduce with current master

my result

`<form accept-charset="UTF-8" action="/admin/collections/33" class="formtastic collection" id="edit_collection" method="post" novalidate="novalidate">`

**Comment by timoschilling** [comment]
@Fivell curios, I could reproduce it, with the master from Sep 2016. Maybe you can't while you use the `admin` namespace and @snoopdouglas and me not.

**Comment by Fivell** [comment]
@timoschilling , I  yes , I used to try setup with /admin namespace (basically modified version of our demo project on github) and can't reproduce it

**Comment by timoschilling** [comment]
can you retry it with a root namespace

**Comment by timoschilling** [comment]
@snoopdouglas @prasadsurase do you still have this problem?

**Comment by Fivell** [comment]
@timoschilling , I retried and can reproduce it without namespace.

**Comment by timoschilling** [comment]
@Fivell Does `ActiveAdmin.register ::Collection` (with `::`) fix the problem?

**Comment by Fivell** [comment]
@timoschilling , no

**Comment by Fivell** [comment]
@timoschilling , just checked @prasadsurase  comment with debugger. 
results 
```ruby
0> resource_path(resource)
=> "/collections"
```

but we can change it to

```
0> active_admin_config.route_instance_path(resource)
=> "/collections/33"
```

to make it work

**Comment by timoschilling** [comment]
@Fivell ca you write a PR

**Comment by Fivell** [comment]
@timoschilling , yep let's try to use activeadmin helpers by default

**Comment by javierjulio** [comment]
@Fivell since you closed out your PR what should we do here? I noticed in your PR you mentioned about supporting all Rails versions, was this with an old version we now don't support?

**Comment by deivid-rodriguez** [comment]
@javerjulio No, this can be reproduced with recent versions. This is just an unresolved bug I'm afraid :)

**Comment by Fivell** [comment]
@javierjulio , @deivid-rodriguez , yes it is unresolved, but we didn't try lucky hack with calling  ```helpers``` yet
😂
