### ISSUE TITLE
Can you package an existing already customized active_admin as a rail engine?

### ISSUE THREAD

**Issue by ikhakoo** [activeadmin/activeadmin#4545]
This is not an issue but I thought this might be the best forum to post this.  I should iterate what I am trying to say:

We have 1 rails application that uses ActiveAdmin and the idea is to spin an identical application that serves its own purpose which would also use the ActiveAdmin panel. This second app run its own db and we've gone the establish_connection route and it just doesn't seem all that great for what we are trying to accomplish (same goes or Apartment). Instead of doing a huge copy paste job and eventually most likely needing this logic again I thought about packaging it all up inside a rails engine and distributing it to both applications.

Does anyone know if this is possible at all?

**Comment by timoschilling** [comment]
Yes it works, but is not official supported. Search the issues, there are some ones round that topic or ask on Stackoverflow.

**Comment by ikhakoo** [comment]
Thanks @timoschilling
