### ISSUE TITLE
register_page method not support label or title, or i18n

### ISSUE THREAD

**Issue by seaify** [activeadmin/activeadmin#4546]
it works
```
ActiveAdmin.register_page "Content Income" do
```

but 
```
ActiveAdmin.register_page "内容收入" do
```
will raise exception.

i tried to add activerecord/models/content_income into zh-CN.yml, and zh-CN.activeadmin.content_income into activeadmin.zh-CN.yml, it also not work.

**Comment by grubinsky** [comment]
Did you already try keeping the title in english and setting the menu label as it documented here?

http://activeadmin.info/docs/2-resource-customization.html#labels

**Comment by seaify** [comment]
@grubinsky 

it works, menu, label way. thanks
