### ISSUE TITLE
upgrade gem dependency of inherited_resources to 1.7

### ISSUE THREAD

**Issue by maia** [activeadmin/activeadmin#4547]
`inherited_resources` is available as `1.7.x` (supporting Rails 5), but `activeadmin.gemspec` uses `'~> 1.6'`. Is there anything preventing an update of the gemspec? Thanks.

**Comment by timoschilling** [comment]
`'~> 1.6'` covers `1.7.x`

**Comment by maia** [comment]
@timoschilling Oh, you're right. In that case I'm clueless why `bundle update inherited_resources` will keep it at `1.6.0` while only activeadmin 1.0.0.pre4 lists it as dependency in my `Gemfile.lock`. Interesting… Thanks!
