### ISSUE TITLE
how to Downloadable XLSX For Each index file 

### ISSUE THREAD

**Issue by saroar** [activeadmin/activeadmin#4549]
I have to download each page separately 
Here what should look like 
http://prntscr.com/bxbpgy

Is there any way i can alive this link and download real xlsx file format

**Comment by timoschilling** [comment]
![screenshot_by_lightshot](https://cloud.githubusercontent.com/assets/165599/17287976/ecd48bd2-57d2-11e6-9d57-b970eb4ab469.png)

**Comment by saroar** [comment]
yes but this is for all project not each but anyway i hope i fine solution thanks Timo

**Comment by timoschilling** [comment]
Then I don't understand what you want

**Comment by saroar** [comment]
i mean for each project separate button http://prntscr.com/c04fmo it means for show page not for index

**Comment by timoschilling** [comment]
You want a download link for each project on the show page?

**Comment by saroar** [comment]
yes but it can be also here yes ? > http://prntscr.com/c04fmo  or inside show page and when i download it should give me right format :)

**Comment by timoschilling** [comment]
Still I don't know what you want! A download button on the Index or on the Show page?

**Comment by saroar** [comment]
show page

**Comment by timoschilling** [comment]
and that link should deliver a XLSX of the current showing project?

**Comment by saroar** [comment]
yes

**Comment by timoschilling** [comment]
Thats is not a build in function from AA!
But you can try this way:
- create a `action_item`
- create a `member_action`
- write your own code for XLSX creation

**Comment by saroar** [comment]
Thanks i will try it and will update you later :)
