### ISSUE TITLE
Displaying related resources on show page displays raw objects at the end

### ISSUE THREAD

**Issue by davidalejandroaguilar** [activeadmin/activeadmin#4550]
I'm trying to display the sides for my order_item's. (_Order has_many order_items has_many Sides through OrderItemSides)_

I'm trying in two ways: 1) Iteration 2) Table_for (since it is a collection of related resources)

1) For some reason, ActiveAdmin will display the raw objects at the end of the first column (i.e. #<OrderItemSide:0x007fdc59a04be0>).

2) Second column works but it creates a table inside my table.

Is this even possible in ActiveAdmin? I've looked everywhere!

```
    panel "Order Details" do
      table_for order.order_items, sortable: true, class: "product-order-table" do
        order = Order.find(params[:id])
        order_items = order.order_items
        
        column "Sides" do |oi|
          oi.order_item_sides.each do |ois|
            ul do 
              li ois.side.name
            end
          end
        end
        
        column "Sides" do |oi|
          table_for oi.order_item_sides do
            column do |ois|
              ul do
                li ois.side.name
              end
            end
          end
        end
```

![da2553290a408a790eb2a04bc73dbb23](https://cloud.githubusercontent.com/assets/15317732/17160675/4813544e-536c-11e6-9c09-d92cabd11d40.png)

**Comment by grubinsky** [comment]
column method of table_for is meant to render the result of the block it receives.
each statement return the last iterated item. That's way you are seeing that on the first example.

I notice you are rendering an ul and li for each side. So if you change that your problem goes away because ul just render html and doesn't return anything.

I meant to changing it this way:

```
column "Sides" do |oi|
  ul do
    oi.order_item_sides.each do |ois|
      li ois.side.name
    end
  end
end
```

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
