### ISSUE TITLE
Filters using custom ransacker not showing in sidebar

### ISSUE THREAD

**Issue by xhero** [activeadmin/activeadmin#4554]
I have some filters that use a custom ransacker. Filtering works, but when submitting the form upon reload all the fields are blank. I tried it with the most basic example from ransack and I still have the issue.

In my model:

```ruby
ransacker :reversed_title, formatter: proc { |v| v.reverse } do |parent|
  parent.table[:title]
end
```

In my controller

```ruby
filter :reversed_title, :as => :string
```

Now if I do a search the items are filtered correctly in the list view, but the contents of the checkbox are erased. The parameter is passed correctly in the quest url:

http://localhost:3000/admin/mymodel?utf8=%E2%9C%93&q%5Breversed_title%5D=test

I passed a couple hours poling through ActiveAdmin but I'm, stuck. It seems some magic happens in `get_parent_and_attribute_name` in Ransack::Adapters::ActiveRecord, where it tries to match the filter name to the model columns, and does not find it.
I looked through the Any ideas?

**Comment by timoschilling** [comment]
double of #3510
