### ISSUE TITLE
CHANGELOG: Can you split up pre-releases?

### ISSUE THREAD

**Issue by brendon** [activeadmin/activeadmin#4555]
Hi there, I was wondering if say from now on the `CHANGELOG` could specify which `pre` version a change was introduced on. I was just moving from `pre2` to `pre4` and missed the but about the comments configuration. :)

**Comment by timoschilling** [comment]
https://github.com/activeadmin/activeadmin/compare/v1.0.0.pre2...v1.0.0.pre4#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by brendon** [comment]
Thanks @timoschilling, I know about that method. Commit messages aren't always as clear as what's entered in the changelog. Thanks for taking the time to respond.

**Comment by timoschilling** [comment]
Sorry the link don't work as expected. Klick the link, klick "Files changed", klick "Showing 160 changed files", klick "CHANGELOG.md", then you can see the diff of the CHANGELOG.md between pre2 and pre4

**Comment by brendon** [comment]
Oh lol, now I get it! :) That's logical :D Thanks again!
