### ISSUE TITLE
doubling nested resources when creating a model

### ISSUE THREAD

**Issue by diaksid** [activeadmin/activeadmin#4560]
nested resources are created twice in the form of creating a model (ROR 5.0.0)

**Comment by timoschilling** [comment]
post the form and all related models

**Comment by diaksid** [comment]
everything is standard.  doubling disappears when adding:

```
controller do
    def create
      @mynested = Mynested.new permitted_params[:certificate]
      if @mynested.save
        redirect_to admin_mynested_path @mynested
      end
    end
end

```

**Comment by timoschilling** [comment]
post the form and all related models, other wise I can't help. Why do you overwrite the create action?

**Comment by diaksid** [comment]
for disposal of doubling nested resources.
this error appeared in all simple applications since the last update ROR. the only thing they have in common - nested resources is polymorphic...

**Comment by timoschilling** [comment]
I close this issue until you provide the necessary informations.
