### ISSUE TITLE
undefined method `quoted_table_name' 

### ISSUE THREAD

**Issue by radhakmk** [activeadmin/activeadmin#4561]
I am getting "**undefined method `quoted_table_name'**" when i access activeadmin admin modules.

Gemfile:
`gem 'activeadmin', github: 'activeadmin'
`

ActiveAdmin admin module:

> ActiveAdmin.register SiteConfig, as: "Site Configs", sort_order: :updated_at_desc do
 end

I am using rails 4.2.7, ruby 2.3.1p112, Activeadmin with mongodb. 

Can someone help me on this issue?

**Comment by timoschilling** [comment]
ActiveAdmin do not support Mongodb/Mongoid!

There are some ways to get it work. Search the issues/pullrequests and Stackoverflow.

**Comment by radhakmk** [comment]
thanks.
I was using "https://github.com/elia/activeadmin-mongoid" before and now its no longer maintained, but there is a note which says **"Official support has started, subscribe to activeadmin#2714 for updates!"**

**Comment by timoschilling** [comment]
Thats true, but #2714 is still open and the related PR issn't merged, you can try to use the PR branch.
