### ISSUE TITLE
activeadmin issue in rail 5

### ISSUE THREAD

**Issue by vijayvyas** [activeadmin/activeadmin#4562]
version conflict of actionpack, below error comes after bundle install
Fetching git://github.com/activeadmin/activeadmin.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Bundler could not find compatible versions for gem "actionpack":
  In snapshot (Gemfile.lock):
    actionpack (= 5.0.0)

  In Gemfile:
    rails (~> 5.0.0) x86-mingw32 was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) x86-mingw32 was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0) x86-mingw32

    rails (~> 5.0.0) x86-mingw32 was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) x86-mingw32 was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0) x86-mingw32

    rails (~> 5.0.0) x86-mingw32 was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) x86-mingw32 was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0) x86-mingw32

    rails (~> 5.0.0) x86-mingw32 was resolved to 5.0.0, which depends on
      actionmailer (= 5.0.0) x86-mingw32 was resolved to 5.0.0, which depends on
        actionpack (= 5.0.0) x86-mingw32

    activeadmin x86-mingw32 was resolved to 1.0.0.pre4, which depends on
inherited_resources (~> 1.6) x86-mingw32 was resolved to 1.6.0, which
depends on
        actionpack (< 5, >= 3.2) x86-mingw32

    activeadmin x86-mingw32 was resolved to 1.0.0.pre4, which depends on
      sass-rails x86-mingw32 was resolved to 5.0.6, which depends on
sprockets-rails (< 4.0, >= 2.0) x86-mingw32 was resolved to 3.1.1, which
depends on
          actionpack (>= 4.0) x86-mingw32

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by timoschilling** [comment]
Read this https://github.com/activeadmin/activeadmin#rails-5
