### ISSUE TITLE
Scope should have another argument to generate @id to take care of multibyte string

### ISSUE THREAD

**Issue by supermomonga** [activeadmin/activeadmin#4563]
## Problem

[Scope takes `name` arg and use it to generate `@id` and html label.](https://github.com/activeadmin/activeadmin/blob/1c85c5654a2ce1d43d4c64d98b928ff133d46406/lib/active_admin/scope.rb#L27-L35)

To generate `@id`, scope will use `ActiveAdmin::Dependency.rails.parameterize` so If we pass the multibyte only string like `"日本語"` to the `name` arg, it will be empty string. It breaks scope function.

I think we should allowed to use any of characters for `name` args, to make i18n supported Admin panel.

## Solution(Suggestion)

Maybe Scope should stop to generate `@id` from `name`, and take another arg for `@id` (as `id` arg or one key of option hash arg).

**Comment by timoschilling** [comment]
Maybe this is a double of a other issue, but I can't find it yet.

Yes it is a bug, but the solution should be to use only a english symbol as name and use the translation for the not ascii name.

**Comment by supermomonga** [comment]
What does `translation` means?

**Comment by timoschilling** [comment]
Example:
```ruby
ActiveAdmin.register Foo do
  scope "日本語"
  # change to
  scope :japanese
```
```yaml
jp:
  active_admin:
    scopes:
      japanese: "日本語"
```

**Comment by supermomonga** [comment]
Ah, I got it. thanks.
