### ISSUE TITLE
Last row on index page not rendering fully

### ISSUE THREAD

**Issue by rorykoehler** [activeadmin/activeadmin#4565]
I have a site using `Rails 4.2.6` with `ActiveAdmin 1.0.0.pre2 from git://github.com/activeadmin/activeadmin.git (at master@d84f819)` and the last row on one of the index pages is not rendering properly (see image). 

This is the same on Chrome and Firefox. No console errors or strange log activity.

![screen shot 2016-08-08 at 22 24 44](https://cloud.githubusercontent.com/assets/7286286/17483433/90d95cb8-5db8-11e6-88de-1a31864d3499.png)

**Comment by timoschilling** [comment]
please post a fullpage screenshot including the boarder of the browser

**Comment by rorykoehler** [comment]
![screen shot 2016-08-08 at 22 48 37](https://cloud.githubusercontent.com/assets/7286286/17483871/4acf10e4-5dba-11e6-9e3a-1a4875097c73.png)

**Comment by rorykoehler** [comment]
with column labels: 
![screen shot 2016-08-08 at 22 49 06](https://cloud.githubusercontent.com/assets/7286286/17484058/f453e360-5dba-11e6-9684-395e4df773f4.png)

**Comment by timoschilling** [comment]
sorry can you do the same screenshot but from the end of the page?

**Comment by timoschilling** [comment]
Sorry I don't seen the first new screenshot

**Comment by timoschilling** [comment]
Can you check the html output? Is that complete or is it sliced at some point?

**Comment by rorykoehler** [comment]
I figured out what is going on. A load of empty html had been pasted into the JS text editor. Sorry for wasting your time, I should have seen it yesterday as I had fixed the exact same problem in another place (with different symptoms). It looks like I need to do some formatting removal on paste.
