### ISSUE TITLE
Batch actions add trailing slash to path

### ISSUE THREAD

**Issue by aleksandra-stolyar** [activeadmin/activeadmin#4566]
Figured out that when batch_action is called (no matter default or custom) it builds such route:
`Started POST "/admin/blocks//batch_action"`
If I set `Rails.application.default_url_options[:trailing_slash] = false`, in my config/application.rb it starts working correctly, but I can't do that because it's necessary to be `= true.`
P.S. slash is added when form `#collection_selection` is rendering.

**Comment by varyonic** [comment]
Which version of Rails are you using?  Do any of [these Rails issues](https://github.com/rails/rails/issues?utf8=%E2%9C%93&q=is%3Aissue%20trailing%20slash%20route) apply?

**Comment by Fivell** [comment]
@aleksandra-stolyar,  can you  try bug-report template  https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#4-did-you-find-a-bug ? 

We will fix this if reproducible.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback. Feel free to reopen with reproduction steps!
