### ISSUE TITLE
'row' with has_many through association shows ruby object

### ISSUE THREAD

**Issue by seanlerner** [activeadmin/activeadmin#4567]
Hello,

I've just switched from 1.0.0.pre2 to 1.0.0.pre4 and when I display a row now, it shows the ruby object along with my desired content. 

So for example, this:

```ruby
  show do
    attributes_table do
      row :name
      row :alternate_names
      row :published
      row :developers do
        if game.developers?
          game.games_creators.developers.each do |developer|
            text_node link_to developer.creator.name, admin_creator_path(developer.creator)
            text_node '<br>'.html_safe
          end
        end
      end
```

displays this:
![active_admin_showing_object](https://cloud.githubusercontent.com/assets/191691/17524078/04c1fe60-5e2b-11e6-885f-fdada44a0e4a.png)

I've found a work around by putting an empty text_node:

```ruby
  show do
    attributes_table do
      row :name
      row :alternate_names
      row :published
      row :developers do
        if game.developers?
          game.games_creators.developers.each do |developer|
            text_node link_to developer.creator.name, admin_creator_path(developer.creator)
            text_node '<br>'.html_safe
          end
        end
        text_node ''  # adding this makes it so the ruby object isn't displayed.
      end
```

It seems to have been introduced by switching from 1.0.0.pre2 to 1.0.0.pre4.

My full code is here:
[(https://github.com/seanlerner/tovgdb/blob/master/app/admin/game.rb)]

Thanks,

Sean

**Comment by timoschilling** [comment]
That issn't a bug, thats a feature for this:
```ruby
row :foo do
  "bar"
end
```
You can also do add a `nil` at the end of the block, instead of the `text_node ''`.

**Comment by seanlerner** [comment]
I see, thx!
