### ISSUE TITLE
Add Scaffold Warning to documentation

### ISSUE THREAD

**Issue by alfmatos** [activeadmin/activeadmin#4568]
Scaffolding is broken when using active_admin, through the imported of the deprecated 'inherited_resources'. It would be great to add a warning about this on the documentation and the corresponding fix:

Adding the following to the application.rb file as outlined in https://github.com/josevalim/inherited_resources/issues/195
```
module SampleApp
  class Application < Rails::Application
    ...
    config.app_generators.scaffold_controller = :scaffold_controller
    ...
  end
end
```

**Comment by timoschilling** [comment]
PR's are welcome.

**Comment by alfmatos** [comment]
Great. Will try to send it later today.
