### ISSUE TITLE
uninitialised constant

### ISSUE THREAD

**Issue by saroar** [activeadmin/activeadmin#4569]
```
ActiveAdmin.register Client do
  permit_params :name, :image

  actions :quick_add, :quick_create

  action_item only: :index do
    link_to 'Quick Client Add', admin_client_quick_add_path, class: 'fancy box', data: { 'fancybox-type' => 'ajax' }
  end

  controller do
    def quick_add
      @client = Client.new
      render layout: false
    end

    def quick_create
      @client = Client.new(permitted_params[:client])
      @client.save!
      render 'quick_response', layout: false
    end
  end
end

#ActionController::RoutingError at /admin/clients/quick_create
#uninitialized constant Admin::ClientController

# here is my routes
  ActiveAdmin.routes(self)
  get  '/admin/clients/new/quick_add' => 'admin/clients#quick_add',   as: :admin_client_quick_add
  post '/admin/clients/quick_create'  => 'admin/client#quick_create', as: :admin_client_quick_create
```

**Comment by timoschilling** [comment]
you forget the s in the last row admin/client => admin/clients

**Comment by saroar** [comment]
thanks for you quick reply its fixed me that error but it give me new error please let me know if you know already why this error 
ActionController::InvalidAuthenticityToken at /admin/clients/quick_create
ActionController::InvalidAuthenticityToken

**Comment by timoschilling** [comment]
google for that, your form needs to send a AuthenticityToken

**Comment by saroar** [comment]
if u add this 
``` simple_form_for @client, url: admin_client_quick_create_path,  :authenticity_token => true, remote: true do |f| ``` its work but getting new error 

ActionView::MissingTemplate at /admin/clients/quick_create
Missing template admin/clients/quick_response, active_admin/resource/quick_response, active_admin/base/quick_response, inherited_resources/base/quick_response, application/quick_response with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:era, :builder, :raw, :ruby, :coffee, :arb, :slim]}

http://prntscr.com/c3wo4j
