### ISSUE TITLE
Precompile failure when updating from master@244a2b3 to master@f3acefd

### ISSUE THREAD

**Issue by arent-groebner** [activeadmin/activeadmin#4573]
Precompilations fails when updating from...

  activeadmin 1.0.0.pre4 from https://github.com/activeadmin/activeadmin.git (at master@244a2b3)

to...

  activeadmin 1.0.0.pre4 from https://github.com/activeadmin/activeadmin.git (at master@f3acefd)

with the error message...

  rake aborted! - Sprockets::FileNotFound: couldn't find file 'jquery2' with type 'application/javascript'

=== Logfile

Running: [bash -c cd /opt/releaseinfo && bundle exec rake assets:precompile]
I, [2016-08-11T11:12:51.978002 #2]  INFO -- : Writing /opt/releaseinfo/public/assets/active_admin-599cdc6ba1ba20e4a37e4081e6cbecc9793ac56a1f7e3f4fd9c0eab38f67aa4e.css
I, [2016-08-11T11:12:51.978693 #2]  INFO -- : Writing /opt/releaseinfo/public/assets/active_admin-599cdc6ba1ba20e4a37e4081e6cbecc9793ac56a1f7e3f4fd9c0eab38f67aa4e.css.gz
rake aborted!
Sprockets::FileNotFound: couldn't find file 'jquery2' with type 'application/javascript'
Checked in these paths: 
  /opt/releaseinfo/app/assets/active_admin
  /opt/releaseinfo/app/assets/images
  /opt/releaseinfo/app/assets/javascripts
  /opt/releaseinfo/app/assets/stylesheets
  /opt/releaseinfo/vendor/assets/javascripts
  /opt/releaseinfo/vendor/assets/stylesheets
  /usr/lib64/ruby/gems/2.3.0/bundler/gems/activeadmin-f3acefd6a1b3/app/assets/images
  /usr/lib64/ruby/gems/2.3.0/bundler/gems/activeadmin-f3acefd6a1b3/app/assets/javascripts
  /usr/lib64/ruby/gems/2.3.0/bundler/gems/activeadmin-f3acefd6a1b3/app/assets/stylesheets
  /usr/lib64/ruby/gems/2.3.0/gems/jquery-ui-rails-5.0.5/app/assets/images
  /usr/lib64/ruby/gems/2.3.0/gems/jquery-ui-rails-5.0.5/app/assets/javascripts
  /usr/lib64/ruby/gems/2.3.0/gems/jquery-ui-rails-5.0.5/app/assets/stylesheets
  /usr/lib64/ruby/gems/2.3.0/gems/formtastic-3.1.4/app/assets/stylesheets
  /usr/lib64/ruby/gems/2.3.0/gems/bourbon-4.2.7/app/assets/stylesheets
  /usr/lib64/ruby/gems/2.3.0/gems/simple_calendar-2.1.5/app/assets/stylesheets
  /usr/lib64/ruby/gems/2.3.0/gems/jquery-rails-3.1.4/vendor/assets/javascripts
  /usr/lib64/ruby/gems/2.3.0/gems/coffee-rails-4.2.1/lib/assets/javascripts
  /usr/lib64/ruby/gems/2.3.0/gems/turbolinks-source-5.0.0/lib/assets/javascripts
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
run: exit status 1
Ending the build

**Comment by timoschilling** [comment]
fixed by #4575
