### ISSUE TITLE
Tabs do not render properly in show block after commit f3acefd

### ISSUE THREAD

**Issue by dschwetz** [activeadmin/activeadmin#4574]
I use the `tabs` method within the `show` block of my active admin resource to display my content in tabs.

After upgrading my AA version yesterday, these failed to render at all. All that displayed was the tab headers in a standard `ul` list (the developer mode in Chrome was telling me they were stylized by the _user agent stylesheet_), followed by the rest of the tabbed content in one `tab-content` `div`, all on one page.

I walked back the commits on master and found this happened as a result of **f3acefd**. The only change in this commit was to update the dependency in base.js.coffee from `jquery` to `jquery2`. Setting my `ref` on the activeadmin line in bundler to **244a2b3**, the previous commit, fixes the problem.

I'm not too familiar with the differences between jquery and jquery2, but I wanted to point this out in case this really was a bug or a misconfiguration in some way. Thanks for the good work.

**Comment by halilim** [comment]
I have the same problem in forms as of c69ace35722c57f956a59445733f61e81f946003. My workaround:
```coffee
# In active_admin.coffee or a file required from it
$ = jQuery
$ ->
  $('#active_admin_content .tabs').tabs()
```

The original loading mechanism is:
```coffee
# .../gems/activeadmin-c69ace35722c/app/assets/javascripts/active_admin/initializers/tabs.js.coffee
$(document).on 'ready page:load turbolinks:load', ->
  # Tab navigation
  $('#active_admin_content .tabs').tabs()
```

**Comment by ericpeters0n** [comment]
Still broken, unfortunately. Also, @halilim's workaround doesn't seem to work for me. :(

**Comment by Fivell** [comment]
@ericpeters0n , I can't reproduce with master, any assistance ?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback. Feel free to reopen with reproduction steps!
