### ISSUE TITLE
"register Xxxx, as: 'yyyy'" does not update button text

### ISSUE THREAD

**Issue by samstickland** [activeadmin/activeadmin#4578]
If I do:

```
ActiveAdmin.register Entity, as: 'Company' do
...
end
```

Then the buttons still rename labelled 'Create Entity', 'Update Entity', rather than 'Create Company', 'Update Company' etc.

I'm happy to try and make a PR for this if this is desirable behaviour.

**Comment by bolshakov** [comment]
That happens because ActiveAdmin uses Formtastic gem to render forms. Formtastic has its [own mechanism for action labels rendering](https://github.com/justinfrench/formtastic/blob/master/lib/formtastic/actions/base.rb#L134).   To overcome this issue you have to provide translation for your model.

**Comment by samstickland** [comment]
OK, thanks!

2016-08-15 13:34 GMT+01:00 Tema Bolshakov <notifications@github.com>:
