### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Chaniel** [activeadmin/activeadmin#4581]
```
$ rails g active_admin:install
Running via Spring preloader in process 5426
/Users/yq/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load': no implicit conversion of nil into String (TypeError)
       	from /Users/yq/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
       	from /Users/yq/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
       	from /Users/yq/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
       	from /Users/yq/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /Users/yq/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from -e:1:in `<main>'
```

**Comment by timoschilling** [comment]
Whats happen durring this command?: `rails g devise:controllers users -c=sessions`?

**Comment by Chaniel** [comment]
$rails g devise:controllers users -c=sessions
Running via Spring preloader in process 4718
      create  app/controllers/users/sessions_controller.rb
===============================================================================

Some setup you must do manually if you haven't yet:

  Ensure you have overridden routes for generated controllers in your routes.rb.
  For example:

    Rails.application.routes.draw do
      devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
    end

===============================================================================

**Comment by Chaniel** [comment]
now I can start the server, but when I access http://localhost:3008/admin/login, 

Sass::SyntaxError in ActiveAdmin::Devise::Sessions#new

Showing /Users/yq/.rvm/gems/ruby-2.3.1/bundler/gems/activeadmin-cc178ad0ebe1/app/views/layouts/active_admin_logged_out.html.erb where line #9 raised:

Undefined mixin 'box-shadow'.

Extracted source (around line #25):

23
24
25
26
27
28
              

	


    &:focus {
      @include box-shadow(none);
      border: 1px solid #C9D0D6;
      border-top: 1px solid lighten(#C9D0D6, 10%);
    }

Rails.root: /data/ruby-apps/railscms

**Comment by timoschilling** [comment]
`rails g devise:controllers users -c=sessions` was not a workaround, just a test to make sure that your `rails g` works.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
