### ISSUE TITLE
Filtering by has_one, through causes error - (PG::AmbiguousColumn: ERROR:  column reference "id" is ambiguous

### ISSUE THREAD

**Issue by ianpetzer** [activeadmin/activeadmin#4584]
Hi there,

I have 3 models:
Lodge belongs_to Region
Region belongs_to  Country
Lodge has_one Country through Region

However when I try to filter by the country I get an exception when Active Admin tries to calculate the number of matching records. The exception is:

    (PG::AmbiguousColumn: ERROR:  column reference "id" is ambiguous

Which Comes from the query:

    SELECT COUNT(DISTINCT "lodges"."id") FROM "lodges" LEFT OUTER JOIN "regions" ON "regions"."id" = "lodges"."region_id" WHERE "regions"."country_id" = 2 AND (id IN (NULL,70,47,45,52,251,17, .... all lodge ids)

It appears the AND clause is just using id instead of lodges.id but this auto-generated through active admin.

Any ideas how I can fix this or work around it?

Thanks for any help!

**Comment by timoschilling** [comment]
Please provide all related models and admin files and a stacktrace.

**Comment by ianpetzer** [comment]
Hi @timoschilling,

Thanks for the rapid response. I copied over all the model definitions and the stack trace and then figured it out!

I had a scope defined as:

    scope :lodges_in_stages, -> { where('id IN (?)', Stage.pluck(:lodge_id).uniq) }

I changed that to:
 
      scope :lodges_in_stages, -> { where('lodges.id IN (?)', Stage.pluck(:lodge_id).uniq) } 

And everything is working.

Thanks!
Ian
