### ISSUE TITLE
Nested attributes form creates duplicate entries for rails 5 

### ISSUE THREAD

**Issue by amalaba** [activeadmin/activeadmin#4587]
I have a 'Product' model with a has_many relation with 'Rates' model. I'm using nested attributes form to enter values for rates. (See the code below). During an insert, this is creating duplicate records for rates.  

app/admin/products.rb:

```
ActiveAdmin.register Product do
  permit_params :name, :rates,
    rates_attributes: [:id, :slab, :_destroy]

  index do
    selectable_column
    id_column
    column :name

    actions
 end

  form do |f|
    f.inputs "Product Details" do
      f.input :name
    end

    f.has_many :rates, allow_destroy: true, heading: 'rates' do |i|
      i.input :slab
    end

    f.actions
  end

  show do |ad|
    attributes_table do
      row :name
      table_for ad.rates do
        column "slab", :slab
        end
    end
  end
end
```

app/models/product.rb:
```
class Product < ActiveRecord::Base
  has_many :rates, dependent: :destroy
  accepts_nested_attributes_for :rates, allow_destroy: true
end
```

app/models/rate.rb:

```
class Rate < ActiveRecord::Base
  belongs_to :products
end
```
Log looks like this:

Started POST "/admin/products" for 127.0.0.1 at 2016-08-19 14:45:22 +0530
Processing by Admin::ProductsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"xSLqjztRq7cbjnKh1zIJfv+1b0bYCJqW0FXfw+uwCNptNXDyyeDagTUaDe7BGO88AEWgDkjJA4LVgr03cHm+hA==", "product"=>{"name"=>"foobar", "rates_attributes"=>{"0"=>{"slab"=>"123"}}}, "commit"=>"Create Product"}
   (0.1ms)  begin transaction
  SQL (0.3ms)  INSERT INTO "products" ("name") VALUES (?)  [["name", "foobar"]]
  **SQL (0.2ms)  INSERT INTO "rates" ("slab", "product_id") VALUES (?, ?)  [["slab", "123"], ["product_id", 3]]
  SQL (0.1ms)  INSERT INTO "rates" ("slab", "product_id") VALUES (?, ?)  [["slab", "123"], ["product_id", 3]]**
   (377.6ms)  commit transaction
Redirected to http://localhost:3000/admin/products/3
Completed 302 Found in 403ms (ActiveRecord: 378.3ms)

Please note the two inserts for rates that is happening. 
Is there a fix for this. 

PS:
I created an exact replica of the models in rails 4, and the issue doesnt exist there.

**Comment by saroar** [comment]
check you JS not duplicate ? can you show me please you assert ? js

**Comment by macowie** [comment]
I've also hit this exact issue. Associations being saved twice on new [parent] records. Fixed by reverting from master to 1.0.0.pre4.

**Comment by saroar** [comment]
cool happy to hear :)

**Comment by Paxa** [comment]
I found it too, it happen because `record_attributes=()` method called twice.

For now solved with hack
```ruby
  def photos_attributes=(args)
    if @unsaved_photos == args
      puts "Prevent duplicated photos"
      return
    end
    @unsaved_photos = args
    super(args)
  end
```

**Comment by saroar** [comment]
NO i think its JS duplication i had same problem u just check JS file once more time.

**Comment by aldreth** [comment]
I have had exactly the same issue - I don't think it can be JS related, as the params only have the nested resource once. From the dev rails logs:

```
Processing by Admin::CountriesController#create as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"IMscZ8/gIqCYJ4cXV99yf9MBkvQG6vu6Xf46WzsvwxlV2CBAQtmK5Lxk4DnoXYvBAiIz00StVrdyiC6r9Ve/cQ==", "country"=>{"name"=>"Test country", "region"=>"", "code"=>"TCT", "latitude"=>"", "longitude"=>"", "countries_have_languages_attributes"=>{"0"=>{"language_id"=>"6452"}}}, "commit"=>"Create Country"}
```
and
```
SQL (0.2ms)  INSERT INTO `countries` (`name`, `region`, `code`, `created_at`, `updated_at`, `slug`) VALUES ('Test country', '', 'TCT', '2016-08-23 09:27:02', '2016-08-23 09:27:02', 'adss')
SQL (0.2ms)  INSERT INTO `countries_have_languages` (`country_id`, `language_id`, `created_at`, `updated_at`) VALUES (253, 6452, '2016-08-23 09:27:02', '2016-08-23 09:27:02')
SQL (0.2ms)  INSERT INTO `countries_have_languages` (`country_id`, `language_id`, `created_at`, `updated_at`) VALUES (253, 6452, '2016-08-23 09:27:02', '2016-08-23 09:27:02')
```

As @macowie said, it is solved by reverting  from master to 1.0.0.pre4.

**Comment by timoschilling** [comment]
can someone find out which commit introduce this bug:
https://github.com/activeadmin/activeadmin/compare/v1.0.0.pre4...master

**Comment by halilim** [comment]
It seems to be 487f976fb895adfb780d682d85674dc35862b72b (parent commit is OK).

```ruby
def build_resource
  get_resource_ivar || begin
    resource = build_new_resource
    resource = apply_decorations(resource)
    resource = assign_attributes(resource, resource_params)
    run_build_callbacks resource
    authorize_resource! resource

    set_resource_ivar resource
  end
end

#...

def build_new_resource
  scoped_collection.send method_for_build, *resource_params
end
```

Calling `Model.new` with params in `build_new_resource` builds a new object with attributes already assigned. Since that responsibility belongs to `assign_attributes`, we get double assignment; which goes undetected for the base attributes since they are overwritten.

**Comment by codyrobbins** [comment]
I’m also seeing this same problem and also came to the same conclusion that it’s because `build_resource` is being called twice. I’m using Rails 4.2.7 and 85ab3f5961e1fab5d5c864ba9170b5e0fd1f6548 of Activeadmin.

**Comment by timoschilling** [comment]
This is a double of #4548, which is now solved at master.

**Comment by kjellberg** [comment]
I'm having exactly the same problem.

```
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'activeadmin', github: 'activeadmin', branch: 'master', ref: 'f892683' # Latest commit
gem 'inherited_resources', github: 'activeadmin/inherited_resources'
```
