### ISSUE TITLE
filename and format missing from ActiveAdmin file upload

### ISSUE THREAD

**Issue by saroar** [activeadmin/activeadmin#4588]
form upload image file show when create new http://prntscr.com/c7oj1j its show file name and formate but when i like to edit its empty http://prntscr.com/c7ojm2

i don't know what i am missing here is my form 

  form do |f|
    f.inputs 'Create New Client' do
      f.input :name
      f.input :image, :as => :file
    end
    f.actions
  end

**Comment by som4ik** [comment]
@saroar  what you asking here is not an issue i think, cuz the file uploader label changes when you upload an file or picture,
i think its better to show the picture if its present, this i suggest
in admin/clinets.rb
remove this 
form do |f|
f.inputs 'Create New Client' do
f.input :name
f.input :image, :as => :file
end
f.actions
end
add this 
form partial: 'form'
- in views/admin/clients/ 
create partail _form.html.slim (( if you use slim )): 
= semantic_form_for @client do |f|
  = f.inputs 
    = f.input :name
    = f.input :image, as: :file
    = image_tag(f.object.image_url) if f.object.image?
    = f.submit
That is it, when you do edit client and if the image present you will see it.

**Comment by saroar** [comment]
:-)

**Comment by som4ik** [comment]
make this: 
```
= semantic_form_for @product do |f|
  = f.inputs
    = f.input :name
    = f.input :image, as: :file, :input_html => { :class => 'hidden-picture'}
    button.choose_image href="#" choose file
    span.text #{f.object.picture? ? f.object.picture.file.filename : 'choose file'}
    br/
    = f.submit
javascript:
  $(function(){
    $('.choose_image').on('click', function(e){
      e.preventDefault();
    $('#client_image').click();
    });
    $('#client_image').on('change',function(){
      var _this = $(this).prop("files")[0]['name'];
      $('.text').html(_this);
    });
  });

```
add to activeadmin.css this 
```
.hidden-picture{
display:none;
}
```

**Comment by saroar** [comment]
thanks @som4ik awesome Job :)
