### ISSUE TITLE
Strange documents in /activeadmin.info/docs

### ISSUE THREAD

**Issue by maangie** [activeadmin/activeadmin#4594]
Hi

There are some strangeness in documents, http://activeadmin.info/docs/.

- Code of the chapter "Conditionally Showing / Hiding Menu Items" is not formatted. Like the following:
![code](https://cloud.githubusercontent.com/assets/6139686/17926725/4286fada-6a2d-11e6-9efd-0e4f3376f55e.jpg)
http://activeadmin.info/docs/2-resource-customization.html#customize-the-menu

- 2 Links in the chapter "Custom Pages" are 404. "Customize the Menu" and "Add a Sidebar."
http://activeadmin.info/docs/10-custom-pages.html

I want someone to correct, please. I'm counting on you.

**Comment by timoschilling** [comment]
wrong repo https://github.com/activeadmin/activeadmin.info
