### ISSUE TITLE
Filters are lost from custom index view navigation links

### ISSUE THREAD

**Issue by jordelver** [activeadmin/activeadmin#4595]
I've have an app which was recently upgraded to revision d84f8190edac8c28f942cd4b6c3e16086da9d7a2

The links to my custom index views were broken after the upgrade. They were missing the querystring and, as such, any applied filters.

This is the commit that broke things for me: https://github.com/activeadmin/activeadmin/commit/4f2916bef684c695afd6346e2365e4d0bdc25927

This seems like undesired behaviour to me. What do you think?

I'm happy to create a PR if you agree.

**Comment by timoschilling** [comment]
Please explain more details on what breaks.

**Comment by jordelver** [comment]
Sure. I select filters and the page refreshes. I click "Summary" and the link does not contain the filters I just set.

![2016-08-24 at 12 48](https://cloud.githubusercontent.com/assets/6588/17929586/4d689a8c-69f9-11e6-9e51-cb418c615edb.png)

**Comment by timoschilling** [comment]
@seanlinsley what do you say, it was your commit?

**Comment by Fivell** [comment]
refs #4646

**Comment by Fivell** [comment]
fixed by https://github.com/activeadmin/activeadmin/pull/4646
