### ISSUE TITLE
Admin::Engine (NameError) after updating to Rails 5

### ISSUE THREAD

**Issue by JesalR** [activeadmin/activeadmin#4598]
Hi.

Seem to be getting an error after updating to Rails 5. 

Using ActiveAdmin 1.0.0.pre4, Inherited Resources 1.6.0, all of which upgrade from 1.0.0.pre and 1.5.1 when using Rails 4.2

> /Users/jesalrajdev/.rvm/gems/ruby-2.2.5@rails5/bundler/gems/activeadmin-fcc5a60e01c5/lib/active_admin/namespace.rb:189:in `eval': uninitialized constant Admin::Engine (NameError)

Stack trace is available at [http://pastebin.com/KYJQKszM](url)

Any help would be greatly appreciated. 

Thanks,
Jesal

**Comment by timoschilling** [comment]
closed as double of #4596
