### ISSUE TITLE
ActiveAdmin::CanCanAdapter is not compatible with CanCanCan's check_authorization

### ISSUE THREAD

**Issue by pre** [activeadmin/activeadmin#4599]
Using: 
* Rails 5.0.0.1
* ActiveAdmin 1.0.0.pre4
* CanCanCan 1.15.0

ActiveAdmin's CanCanAdapter does not mark resource as being authorized in the way CanCanCan expects it to be.

If you define `check_authorization` in ApplicationController, [CanCan expects instance variable `@_authorized` being defined](https://github.com/CanCanCommunity/cancancan/blob/v1.15.0/lib/cancan/controller_additions.rb#L260). 

However, `@_authorized` remains nil under ActiveAdmin's controllers. Calling `authorize! :access, Resource` under ActiveAdmin resources has no effect. Calling `controller.authorize`, `controller.any_can_can_method` under ActiveAdmin resources has no effect either.

As a result, the following exception will be raised:
```
CanCan::AuthorizationNotPerformed in Admin::DashboardController#index
This action failed the check_authorization because it does not authorize_resource. Add skip_authorization_check to bypass this check.
```

Only way seems to be to bypass CanCan `check_authorization` for ActiveAdmin resources in `ApplicationController`. 

Initializer:
```ruby
  config.authorization_adapter = ActiveAdmin::CanCanAdapter
  config.default_namespace = :admin
  config.authentication_method = :authenticate_admin_user!
  config.current_user_method = :current_admin_user
  config.before_filter :authorize_admin_access
```

ApplicationController:
```ruby
  check_authorization :unless => :is_devise_or_active_admin?

  protected

  def is_devise_or_active_admin?
    devise_controller? || active_admin_resource?
  end

  def active_admin_resource?
    self.class.ancestors.include? ActiveAdmin::BaseController
  end
```

ActiveAdmin resource
```ruby
  before_filter :authorize_this
  
  controller do
    # CanCanCan raises `CanCan::AuthorizationNotPerformed` because 
    # `@_authorized` is not defined in the controller's scope 
    # after this method call
    def authorize_this
      authorize! :manage, NameOfThisResource
    end
  end
```

Somebody else had reported [the issue in StackOverflow](http://stackoverflow.com/a/26247543/422848) in 2014. I only found it now when I finally had to upgrade from Rails 3.2 to Rails 5.0. 

This problem did not appear in ActiveAdmin 0.5.1 and Rails 3.2.

**Comment by timoschilling** [comment]
The ActiveAdmin::CanCanAdapter works in a different way then the `authorize!` method works.
There are already some issues for that topic.

BTW: PRs are welkome.

**Comment by ammaar-buzz** [comment]
can someone please share any facts how ActiveAdmin::CanCanAdapter authorize! method  works actually.
