### ISSUE TITLE
Dynamic site title image

### ISSUE THREAD

**Issue by reicheltd** [activeadmin/activeadmin#4600]
Is there a way to make a dynamic site title image `config.site_title_image` from the `initializers/active_admin.rb`, based on the `current_user` ?

Thank you

**Comment by timoschilling** [comment]
`site_title_image` can be a proc

**Comment by reicheltd** [comment]
Thanks. I tried something like this and it works.

     config.site_title_image = ->(view) {  
        if current_user  
          if current_user.company.id == 1  
            'company_logo.png'  
          end  
      end
      }
