### ISSUE TITLE
Properly format boolean values in attribute tables

### ISSUE THREAD

**Issue by AlexVPopov** [activeadmin/activeadmin#4602]
I propose the following change:

``` ruby
def pretty_format(object)
  case object
  when String, Numeric, Symbol, Arbre::Element
    object.to_s
  when TrueClass, FalseClass
    status_tag value
  when Date, Time
    localize object, format: active_admin_application.localize_format
  else
    if defined?(::ActiveRecord) && object.is_a?(ActiveRecord::Base) ||
       defined?(::Mongoid)      && object.class.include?(Mongoid::Document)
      auto_link object
    else
      display_name object
    end
  end
end
```

in [ActiveAdmin::ViewHelpers::DisplayHelper](https://github.com/activeadmin/activeadmin/blob/552289200049851540393db2dbf142ab311ced1e/lib/active_admin/view_helpers/display_helper.rb#L68)

The idea is that currently the value of boolean columns is displayed via `status_tag` and the result of methods, that return  `true`/`false`, is displayed via a ✔/✗. In an attributes table, where some of the rows are for boolean columns and some of the rows are for methods returning booleans, the table looks inconsistent.

Would such a PR be accepted?

**Comment by Fivell** [comment]
@AlexVPopov , what about null values?

**Comment by AlexVPopov** [comment]
Maybe we can add `NilClass` to the first case?

**Comment by Fivell** [comment]
@AlexVPopov, I didn't test but according to current implementations nulls are displayed as status_tag  'false' if database column is boolean and just nil in all other cases ..

**Comment by AlexVPopov** [comment]
@Fivell I need to take and do a research on this, as it's been a long time since I proposed this.

**Comment by AlexVPopov** [comment]
@Fivell nice, thank you.
