### ISSUE TITLE
v1.0.0.pre4 breaks deferred constraint

### ISSUE THREAD

**Issue by irubnich** [activeadmin/activeadmin#4603]
Hi,

I've started encountering some test failures on my app when upgrading to 1.0.0.pre4.

Specifically, I have a deferred unique constraint on a table, and when creating or editing an object with Active Admin, Rails fails saying that the constraint was triggered. Additionally, the console produces an output of `WARNING:  there is no transaction in progress` as the object attempts to be saved.

Some background: I have a table which has a "position" column which is supposed to be unique per the value of a "parent" column. It's deferred because otherwise this constraint would always fail when swapping the values of "position" with another item's position.

A git bisect traced the issue to this commit: https://github.com/activeadmin/activeadmin/commit/6488d6319187c1f0b1f9916cd36d76b84e40f641 although that might be a red herring since reverting it does not fix the issue.

Info:
Rails 4.2.7.1

**Comment by varyonic** [comment]
This commit caused an issue for me also because it causes assign_attributes to be called during create where previously assign_attributes was used only for update.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
