### ISSUE TITLE
ActiveAdmin and Active Record Store

### ISSUE THREAD

**Issue by alfmatos** [activeadmin/activeadmin#4606]
I'm using activeadmin with a rails application that has an angular frontend using `ng-token-auth` and `devise-token-auth`. 

Angular produces large cookies so it usually results in:
```
ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):
```

The solution is to use the active record store:

```
 config.session_store :active_record_store
```

However, I can't get authentication to work with activeadmin and the active_record_store. On successful authentication I get redirected to the home url, and get a 403.

Any way to use the activer_record_store with activeadmin?

**Comment by timoschilling** [comment]
Your problem related to ActiveAdmin. ActiveAdmin uses Devise for auth. Your problem is between Devise and Angular.

**Comment by alfmatos** [comment]
@timoschilling indeed. I raised it here because it's activeadmin which requires the cookies (and that is the source of all evil). Solved this by using a different middleware specifically for activeadmin as suggested here for different purposes: http://stackoverflow.com/questions/26922343/omniauthnosessionerror-you-must-provide-a-session-to-use-omniauth-configur

```
class SelectiveStack
  def initialize(app)
    @app = app
  end

  def call(env)
    if env["PATH_INFO"].start_with?("/admin")
      middleware_stack.build(@app).call(env)
    else
      @app.call(env)
    end
  end

private
  def middleware_stack
    @middleware_stack ||= begin
      ActionDispatch::MiddlewareStack.new.tap do |middleware|
        middleware.use Rack::MethodOverride
        middleware.use ActionDispatch::Flash
        middleware.use ActionDispatch::Cookies
        middleware.use ActionDispatch::Session::CookieStore
      end
    end
  end
end
```

Thanks.
