### ISSUE TITLE
Button "has many add" fires multiple times

### ISSUE THREAD

**Issue by marcomd** [activeadmin/activeadmin#4607]
It is troublesome and I would propose a solution to fix it!  :fire:

This happen because that binds are under a function.
The solution is very simple: move them outside.

If there're not any downside I could create a PR.

[activeadmin/app/assets/javascripts/active_admin/lib/has_many.js.coffee](https://github.com/activeadmin/activeadmin/blob/master/app/assets/javascripts/active_admin/lib/has_many.js.coffee)

**Comment by marcomd** [comment]
I forgot to specify that it happen with turbolinks.

The environment:
Rails 5 + turbolinks 5 + jquery.turbolinks + turbolinks-compatibility

**Comment by timoschilling** [comment]
Please provide a PR and describe the problem (maybe with ref to a existing bug issue), then we can talk about the change there.
