### ISSUE TITLE
NameError: undefined local variable or method `user' for main:Object

### ISSUE THREAD

**Issue by agentargyle** [activeadmin/activeadmin#4609]
If I run rails generate active_admin:resource [MyModel] or even just rake db:migrate i get an error:

`undefined local variable or method `user' for main:Object (NameError)`

Here is the full text:

```
DEPRECATION WARNING: Support for Rails < 4.1.0 will be dropped. (called from <top (required)> at /var/lib/gems/1.9.1/gems/formtastic-3.1.4/lib/formtastic.rb:4)
/home/myapp/app/admin/[user].rb:1:in `<top (required)>': undefined local variable or method `user' for main:Object (NameError)
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `load'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `block in load'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:214:in `load_dependency'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `load'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:216:in `block in load'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/error.rb:41:in `capture'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:216:in `load'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:208:in `block in load!'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:208:in `each'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:208:in `load!'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:230:in `routes'
	from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin.rb:79:in `routes'
	from /home/myapp/config/routes.rb:3:in `block in <top (required)>'
	from /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:341:in `instance_exec'
	from /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:341:in `eval_block'
	from /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:319:in `draw'
	from /home/myapp/config/routes.rb:1:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `load'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `block in load'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:214:in `load_dependency'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `load'
	from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:40:in `each'
	from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:40:in `load_paths'
	from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:16:in `reload!'
	from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:26:in `block in updater'
	from /usr/lib/ruby/vendor_ruby/active_support/file_update_checker.rb:75:in `call'
	from /usr/lib/ruby/vendor_ruby/active_support/file_update_checker.rb:75:in `execute'
	from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:27:in `updater'
	from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:6:in `execute_if_updated'
	from /usr/lib/ruby/vendor_ruby/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
	from /usr/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/1.9.1/tsort.rb:180:in `each'
	from /usr/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
	from /usr/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
	from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
	from /usr/lib/ruby/vendor_ruby/rails/application.rb:215:in `initialize!'
	from /usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
	from /home/myapp/config/environment.rb:5:in `<top (required)>'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:229:in `require'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:229:in `block in require'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:214:in `load_dependency'
	from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:229:in `require'
	from /usr/lib/ruby/vendor_ruby/rails/application.rb:189:in `require_environment!'
	from /usr/lib/ruby/vendor_ruby/rails/commands.rb:44:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by timoschilling** [comment]
please post your `routes.rb` and `active_admin.rb` files

**Comment by agentargyle** [comment]
I'm closing this because I had been following the directions from activeadmin.info and just saw that they were out of date.

**Comment by kamranawan** [comment]
If I run rails generate active_admin:resource [MyModel] or even just rake db:migrate i get an error:

undefined local variable or methoduser' for main:Object (NameError)`

Here is the full text:

DEPRECATION WARNING: Support for Rails < 4.1.0 will be dropped. (called from <top (required)> at /var/lib/gems/1.9.1/gems/formtastic-3.1.4/lib/formtastic.rb:4)
/home/myapp/app/admin/[user].rb:1:in `<top (required)>': undefined local variable or method `user' for main:Object (NameError)
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `load'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `block in load'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:214:in `load_dependency'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `load'
    from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:216:in `block in load'
    from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/error.rb:41:in `capture'
    from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:216:in `load'
    from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:208:in `block in load!'
    from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:208:in `each'
    from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:208:in `load!'
    from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin/application.rb:230:in `routes'
    from /var/lib/gems/1.9.1/gems/activeadmin-1.0.0.pre4/lib/active_admin.rb:79:in `routes'
    from /home/myapp/config/routes.rb:3:in `block in <top (required)>'
    from /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:341:in `instance_exec'
    from /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:341:in `eval_block'
    from /usr/lib/ruby/vendor_ruby/action_dispatch/routing/route_set.rb:319:in `draw'
    from /home/myapp/config/routes.rb:1:in `<top (required)>'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `load'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `block in load'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:214:in `load_dependency'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:223:in `load'
    from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:40:in `block in load_paths'
    from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:40:in `each'
    from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:40:in `load_paths'
    from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:16:in `reload!'
    from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:26:in `block in updater'
    from /usr/lib/ruby/vendor_ruby/active_support/file_update_checker.rb:75:in `call'
    from /usr/lib/ruby/vendor_ruby/active_support/file_update_checker.rb:75:in `execute'
    from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:27:in `updater'
    from /usr/lib/ruby/vendor_ruby/rails/application/routes_reloader.rb:6:in `execute_if_updated'
    from /usr/lib/ruby/vendor_ruby/rails/application/finisher.rb:69:in `block in <module:Finisher>'
    from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `instance_exec'
    from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:30:in `run'
    from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:55:in `block in run_initializers'
    from /usr/lib/ruby/1.9.1/tsort.rb:150:in `block in tsort_each'
    from /usr/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
    from /usr/lib/ruby/1.9.1/tsort.rb:219:in `each_strongly_connected_component_from'
    from /usr/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
    from /usr/lib/ruby/1.9.1/tsort.rb:180:in `each'
    from /usr/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
    from /usr/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
    from /usr/lib/ruby/vendor_ruby/rails/initializable.rb:54:in `run_initializers'
    from /usr/lib/ruby/vendor_ruby/rails/application.rb:215:in `initialize!'
    from /usr/lib/ruby/vendor_ruby/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/myapp/config/environment.rb:5:in `<top (required)>'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:229:in `require'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:229:in `block in require'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:214:in `load_dependency'
    from /usr/lib/ruby/vendor_ruby/active_support/dependencies.rb:229:in `require'
    from /usr/lib/ruby/vendor_ruby/rails/application.rb:189:in `require_environment!'
    from /usr/lib/ruby/vendor_ruby/rails/commands.rb:44:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
