### ISSUE TITLE
has_one vs has_many: how to limit "Add new" to only accept 1 nested object

### ISSUE THREAD

**Issue by vraravam** [activeadmin/activeadmin#4614]
Looking through a lot of comments/issues related to this, I couldn't find the solution. I have used the `has_many` feature in AA to build out a form. But, the underlying domain has only 1 object (its a `belongs_to/has_one` relationship. Is there a way to limit the number of times the user can click on "Add new" for this nested form?

**Comment by prasadsurase** [comment]
@vraravam Could you please add more details?

**Comment by vraravam** [comment]
Hi,
I have user has_one profile photo. Since I wanted to allow the user to
upload a pic in the AA edit screen for user, I was forced to use the
has_many in the form section. But, in the browser, since it's has_many, the
ui allows the end user to submit multiple files in the same submit action.

I wanted a way to limit the firm submission to only allow one nested form.

Hope that makes it clear,
Vijay

sent using an itty-bitty keyboard that assumes it can think

**Comment by timoschilling** [comment]
There is no build in support for that, you can write a javascript to hide the button if there is more than one element.

**Comment by vraravam** [comment]
@timoschilling - that is finally what I have implemented. In fact most of the "code" is already present in as comments in the AA codebase. If you are willing to incorporate it as "built-in" functionality for future versions of AA, I can create a PR for it. But, I wouldn't want to spend time, if it doesn't jive with the core team's vision of the roadmap - ie if you think this kind of functionality is only done in an adhoc basis and doesn't need to be in the core. What are your thoughts?

**Comment by chouroukmrad** [comment]
Is there any solution for this issue?

**Comment by vraravam** [comment]
@chouroukmrad - I had to implement it using javascript to "hide" the "Add new record" button - based on whether I allow 1 or X number of child records. As stated earlier, I have incorporated it within the context of my codebase, not in a generic manner - till the authors are willing to accept a PR for the same.

**Comment by chouroukmrad** [comment]
+1

**Comment by sercul** [comment]
+1

**Comment by nikolai-b** [comment]
If you wrap the `.has_many` in a `.has-one` class e.g.
```ruby
span class: "has-one" do
  f.has_many :model do |ff|
    ...
  end
end
```

Then if you add this js it should mean the "Add new" is hidden when one

```js
  var toggleManyAdd = function(e) {
    $(e.target).closest(".has_many_container").find("a.has_many_add").toggle();
  }

  // Adds the toggleManyAdd click handler to the Add and Remove buttons
  var initToggleManyAdd = function(){
    $(".has-one a[class*='has_many_']").not(".toggle-many-added").click(toggleManyAdd);
    $(".has-one a[class*='has_many_']").addClass("toggle-many-added");
  }
  initToggleManyAdd();
  $(document).on('has_many_add:after', initToggleManyAdd)

  // Hides the Add button if a `.has-one` element already exists
  $(".has-one .has_many_container").each( function(_, container) {
    if($(container).find("ol").length){ $(container).find("a.has_many_add").hide(); }
  })
```

**Comment by timoschilling** [comment]
@vraravam if you have a slim implementation you're welcome.

**Comment by laclance** [comment]
@timoschilling I have it working for adding but when editing an item the add new button is there even if there is already an association.

**Comment by pavel-jurasek-bcgdv-com** [comment]
Solution to add has_one to active admin:

app/models/marker.rb
```ruby
  class Market < ApplicationRecord
    has_one :service_url
  end
```

app/admin/market.rb
```ruby
ActiveAdmin.register Market do
  controller do
    def build_new_resource
      super.tap { |resource| resource.build_service_url }
    end

    def find_resource
      super.tap do |resource|
        resource.build_service_url unless resource.service_url.present?
      end
    end
  end

  form title: 'Market' do |f|
    render 'form', context: self, f: f
  end
end
```

app/views/marker/_form.html.erb
```ruby
<% context.instance_eval do
    semantic_form_for resource, url: admin_markets_path do
  		f.semantic_errors *f.object.errors.keys
  	   	f.inputs 'Details' do
  			f.input :name
  			f.input :country, as: :select, collection: Market.supported_countries_for_display
  			f.input :language, as: :select, collection: Market.supported_languages_for_display
  			f.input :from_email, as: :email
  			f.input :customer_support_phone_number, as: :phone
  			f.input :st_point, as: :string
  			f.input :terms_of_service_version
  			f.input :opening_time, as: :time_picker
  			f.input :closing_time, as: :time_picker
  			f.input :time_zone, as: :time_zone
  		end
  		f.inputs 'Service URLs' do
  		  f.semantic_fields_for :service_url do |s|
    			s.input :market_id, as: :hidden
    			s.input :terms_of_service_local
    			s.input :terms_of_service_english
    			s.input :data_privacy_local
    			s.input :data_privacy_english
    			s.input :newsletter_conditions_local
    			s.input :newsletter_conditions_english
    			s.input :support_local
    			s.input :support_english
  		  end
  		end

  		f.actions
	  end
  end
%>
```

`tap` approach can be used to initialize multiple different association with admin specific values without changing business logic for rest of the code base

Solution looks like:
<img width="1420" alt="screen shot 2017-06-02 at 08 27 39" src="https://cloud.githubusercontent.com/assets/7910967/26713513/60881726-476d-11e7-9fca-3108206a40e1.png">

**Solution 2**
if you are fine to add callback to your ActiveRecord model you can just use after_initialization callback

**Comment by Fivell** [comment]
related #4415

**Comment by 4ndv** [comment]
Made it like this:

1. Add a `class: 'has_one'` on f.has_many
2. Add this to your AA css:

```css
.has_one ~ .has_many_add {
  display: none !important;
}
```

This will hide button once you're clicked on "Add Item" and return it back once you're removed this single item

**Comment by pedroviana** [comment]
@4ndv hot solution!

My workaround was creating a hidden input with new_record? value to show/hide the buttons through has_many:after callbacks.

**Comment by fuadkhan1996** [comment]
You can use `f.inputs` to limit `Add New` only to accept 1 nested object.

```
form do |f|
    f.inputs do
      # has_one association
      f.inputs Address, for [:address, f.object.address || f.object.build_address] do |address_form|
        address_form :street
        address_form :city
      end
   end
end
```

Now to permit params,

`permit_params address_attributes: %i[id street city]`
