### ISSUE TITLE
Configuring filters in ActiveAdmin.setup should be lazy

### ISSUE THREAD

**Issue by lukeredpath** [activeadmin/activeadmin#4617]
We have an issue using ActiveAdmin (master branch) in our application (Rails 4) when configuring a skip_before_filter in our ActiveAdmin configuration.

The issue manifested itself as an undefined helper method that was supplied by a module in another Rails engine we are using.

That engine correctly injects the helper module in an engine initialiser, after ActionController is loaded:

``` ruby
initializer "mountain_view.add_helpers" do
      ActiveSupport.on_load :action_controller do
        helper MountainView::ApplicationHelper
        helper MountainView::ComponentHelper
      end
    end
```

The error only occurs after initially starting up a server - saving any file to trigger Rails class reloading makes the problem go away.

On investigation it appears the reason this happening is that calling `config.skip_before_filter` (or any controller filter method in ActiveAdmin.setup block (which happens during the Rails initialisation process) causes ActionController to be loaded early, before the initialisation process is finished and before this particular engine has been loaded, so the helper module is never included.

It is recommended by the Rails core team _not_ to reference any Rails class directly during the initialisation process - see this issue which describes a similar problem:

https://github.com/rails/rails/issues/23589#issuecomment-239584721

One suggested approach would be to replace the following code with custom methods and delay the process of configuring these on each controller until after the initialisation process:

```
AbstractController::Callbacks::ClassMethods.public_instance_methods.
      select { |m| m.match(/(filter|action)/) }.each do |name|
      define_method name do |*args, &block|
        controllers_for_filters.each do |controller|
          controller.public_send name, *args, &block
        end
      end
    end
```

In the meantime we will try and find a workaround.

**Comment by Fivell** [comment]
@lukeredpath, any update on this?

**Comment by javierjulio** [comment]
Seeing this now, I remember a more recent issue about this where there was a conflict with generator when used alongside MountainView and Draper #5022 so going to close this out as its stale but also very liked resolved.
