### ISSUE TITLE
Handle STI subclasses

### ISSUE THREAD

**Issue by dwaynemac** [activeadmin/activeadmin#4623]
Hello.

Lets say I have a Product resource.

And I have subclasses: Book and Toy , both subclasses of Product.

Book < Product
Toy < Product

Is there a way for the activeadmin Product register to handle all these models transparently.

I'm currently getting an error for urls not found on the index page.

**Comment by timoschilling** [comment]
Post your Admin file and the error

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
