### ISSUE TITLE
Update text of link_to_add text using nested form in activeadmin

### ISSUE THREAD

**Issue by Bilkhaan** [activeadmin/activeadmin#4626]
I am using nested attributes in active admin. Here is my code:

```
form do |f|
  f.inputs 'Basic information' do
    f.input :event_name
  end

  if f.object.persisted?
    f.inputs 'Examples' do
      f.has_many :event_resources do |event_resource|
        event_resource.input :event_resource_id, as: :select, collection: EventResource.available_packages
        if event_resource.object.persisted?
          event_resource.input :_destroy, as: :boolean, label: "Destroy this resource"
        end
      end
      f.link_to_add "Add Resource", :event_resources
    end
  end
  f.actions
end
```
I want to update the text of the add link. But i am getting error that link_to_add is not defined for active admin view. Can anyone guide me in right direction. Thanks

**Comment by timoschilling** [comment]
You can change that text via the locales.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
