### ISSUE TITLE
collection_actions not working properly - routes defined by them finally point to my :create member_action

### ISSUE THREAD

**Issue by luismasuelli-alturasoluciones** [activeadmin/activeadmin#4628]
This is Rails 5, with ActiveAdmin 1.0.0.pre4

I have this ActiveAdmin registration:

    ActiveAdmin.register User do
      permit_params :first_name, :last_name, :email, :role

      scope :all
      scope :admin
      scope :professor
      scope :student

      config.clear_action_items!

      index do
        id_column
        column :name do |c|
          c.full_name
        end
        column :email
        column :created_at do |c|
          c.created_at.strftime("%Y-%m-%d %H:%M")
        end
        column :role
        column :login_as do |c|
          link_to "login as", login_as_admin_user_path(c.id)
        end
        actions defaults: false do |c|
          item 'Show', admin_user_path(c.id)
          span '  |  '
          item 'Edit', edit_admin_user_path(c.id)
        end
      end

      filter :first_name
      filter :last_name
      filter :email

      form do |f|
        f.inputs do
          f.input :first_name
          f.input :last_name
          f.input :email
          if f.object.new_record?
            f.input :role, as: :select, collection: [['Professor', :professor], ['Student', :student]]
          elsif f.object.admin?
            f.input :role, as: :readonly, display: 'Administrator'
          else
            f.input :role, as: :select, collection: [['Professor', :professor], ['Student', :student], ['Administrator', :admin]]
          end
        end
        f.actions
      end

      action_item :only => :index do
        link_to 'Invite User', new_admin_user_path
      end

      action_item :only => :index do
        link_to 'Bulk Invite Users', bulk_new_admin_users_path
      end

      collection_action :bulk_new, method: :get do
        # Just render - no specific implementation
      end

      collection_action :bulk_create, method: :post do
        # Also tried: raise StandardError.new 'foo'
        render nothing: true
      end

      member_action :create, method: :post do
        pparams = permitted_params[:user]
        @user = User.new(pparams)
        if @user.admin?
          flash[:error] = 'Cannot invite admin users with this method'
          render :new
        else
          @user.avoid_password_validation = true
          if @user.valid?
            @user.invite!(current_user)
            redirect_to admin_user_path(@user.id), notice: "Invitation sent to email: #{@user.email}"
          else
            render :new
          end
        end
      end

      member_action :login_as do
        new_user = User.find(params[:id])
        session["admin_user_id"] = current_user.id
        sign_in(:user, new_user)
        redirect_to root_path
      end

      member_action :resend_activation do
        @user = User.find(params[:id])
        @user.send_confirmation_instructions
      end

      show do
        attributes_table :id, :first_name, :last_name, :email, :role, :encrypted_password, :reset_password_oken, :reset_password_sent_at, :remember_created_at,
                         :sign_in_count, :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, :last_sign_in_ip, :invitation_token, :invitation_created_at,
                         :invitation_sent_at, :invitation_accepted_at, :invitation_limit, :invited_by, :invited_by_type, :invitations_count, :created_at, 
                         :updated_at
      end
    end

And my routes are generated like this:

                             admin_user POST   /admin/users/:id(.:format)                              admin/users#create
                    login_as_admin_user GET    /admin/users/:id/login_as(.:format)                     admin/users#login_as
           resend_activation_admin_user GET    /admin/users/:id/resend_activation(.:format)            admin/users#resend_activation
                   bulk_new_admin_users GET    /admin/users/bulk_new(.:format)                         admin/users#bulk_new
                bulk_create_admin_users POST   /admin/users/bulk_create(.:format)                      admin/users#bulk_create
               batch_action_admin_users POST   /admin/users/batch_action(.:format)                     admin/users#batch_action
                            admin_users GET    /admin/users(.:format)                                  admin/users#index
                                        POST   /admin/users(.:format)                                  admin/users#create
                         new_admin_user GET    /admin/users/new(.:format)                              admin/users#new
                        edit_admin_user GET    /admin/users/:id/edit(.:format)                         admin/users#edit
                                        GET    /admin/users/:id(.:format)                              admin/users#show
                                        PATCH  /admin/users/:id(.:format)                              admin/users#update
                                        PUT    /admin/users/:id(.:format)                              admin/users#update
                                        DELETE /admin/users/:id(.:format)                              admin/users#destroy

When I reach the `/admin/users/bulk_new` route, which is just a form hitting `/admin/users/bulk_create` (Url: `bulk_create_admin_users_path`, I can verify that for true in the browser itself, with no url wrapping or anything like that meddling), it displays as expected.

However, when I submit (also checking in the browser's Network tab to check no redirections exist - the url is `/admin/users/bulk_create`), the post request is handled by the `:create` member action (which is wrong since I need the collection_action to be executed) instead of being handled by the `:bulk_create` collection action.

If this is not a bug but an intended behavior, please make the point clear in the documentation.

**Comment by timoschilling** [comment]
Please post the console output of the related request

**Comment by luismasuelli-alturasoluciones** [comment]
I found the problem. It was an 8th-layer problem. What happened is that :create was a member_action instead of a collection_action, and :post-ing to /admin/users/bulk_create was handled by :create (:post to /admin/users/:id with id: 'bulk_create'). I understand the bug was mine.

However, I would like to change this into a suggestion: It would be useful if you document about the route matching precedence, and/or add a feature to specify precedence in route matching for both collection_action and member_action.

Sorry for bothering. My bad xD.
