### ISSUE TITLE
Precompilation issue Sass::SyntaxError: Undefined mixin 'global-reset'.

### ISSUE THREAD

**Issue by railsfactory-bhaskararao** [activeadmin/activeadmin#4630]
rake aborted!
Sass::SyntaxError: Undefined mixin 'global-reset'.

avtive_amin.scss

// SASS variable overrides must be declared before loading up Active Admin's styles.
```
//
// To view the variables that Active Admin provides, take a look at
// `app/assets/stylesheets/active_admin/mixins/_variables.scss` in the
// Active Admin source.
//
// For example, to change the sidebar width:
// $sidebar-width: 242px;

// Active Admin's got SASS!
@import "active_admin/mixins";
@import "active_admin/base";
```

// Overriding any non-variable SASS must be done after the fact.
// For example, to change the default status-tag color:
//
//   .status_tag { background: #6090DB; }

Rails: 4.2.4
activeadmin:   gem 'activeadmin', '~> 1.0.0.pre4'

**Comment by timoschilling** [comment]
Is this still a issue?

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by prawin** [comment]
Came across this while upgrading one of my rails 4.2 to application to rails 5.0
