### ISSUE TITLE
Empty page 

### ISSUE THREAD

**Issue by sofianegargouri** [activeadmin/activeadmin#4631]
Hi guys

I just installed ActiveAdmin in my project, and the installation went fine. But when I try to go to /admin, I get an empty page. When looking in the console, I get a 403 error.

Thanks for help ! :D

**Comment by timoschilling** [comment]
Did you have restarted after install?
Please post your `active_admin.rb` and `routes.rb` files.
Please post the console outpout of that request and the output of `rake routes`

**Comment by sofianegargouri** [comment]
Okey, after a few searches, I found the issue.
I'm using Rails API, and not the basic Rails, so, if someone needs it, here is [the solution](http://arturmin.com/en/2015/09/25/the-friendly-union-of-rails-base-api-and-active-admin.html)
