### ISSUE TITLE
Active Admin Pagination Error

### ISSUE THREAD

**Issue by wizvs** [activeadmin/activeadmin#4634]
Hi My active admin pagination works fine till i turn filter like service state to active.

Check out the attachment it says "Displaying Contractors 1 - 1 of 80 in total"

I think the pagination count is wrong.  
When i dont use the filter it works fine.

I am using Ruby 1.9.3 and Rails 3 .
![2016-09-19 19_39_45-new notification](https://cloud.githubusercontent.com/assets/9604689/18635065/3f87c2e6-7ea1-11e6-89a8-8c1f421f674c.png)
![pagi](https://cloud.githubusercontent.com/assets/9604689/18635064/3f7e5f62-7ea1-11e6-9e32-ba84acefbe70.png)

**Comment by jclay** [comment]
@wizvs, what is the expected count? Is it that the count is not decreasing to the correct value after applying a filter?

I would first try upgrading to a newer version of `activeadmin`.

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
