### ISSUE TITLE
Arbre duplicates form fields when inspecting model during production/debug

### ISSUE THREAD

**Issue by gbisheimer** [activeadmin/activeadmin#4639]
## Description
I came across this problem when building [this activeadmin addon](https://github.com/bys-control/activeadmin_custom_layout) aiming to customize default ActiveAdmin layout by using CaptureHelper methods.

I'm getting repeated form fields when inspecting or evaluating arbre components related to forms. I didn't had problems with anything else but forms. Seems related to Arbre but couldn't find the bug yet.

## Versions
activeadmin 1.0.0.pre4
rails 5.0.0.1.
ruby 2.3.0p0

## Steps to reproduce
Take any ActiveAdmin resource that has a form declaration in its DSL and add a `puts self.inspect` before closing the block. You will get the form fields duplicated.

## Example
I'll use the default admin_user Resource as an example:

```RUBY
ActiveAdmin.register AdminUser do
  permit_params :email, :password, :password_confirmation

  index do
    selectable_column
    id_column
    column :email
    column :current_sign_in_at
    column :sign_in_count
    column :created_at
    actions
  end

  filter :email
  filter :current_sign_in_at
  filter :sign_in_count
  filter :created_at

  form do |f|
    f.inputs "Admin Details" do
      f.input :email
      f.input :password
      f.input :password_confirmation
    end
    f.actions
    puts self.inspect
  end

end
```

Go to the edit or new route and you will get something like this:

![image](https://cloud.githubusercontent.com/assets/3077123/18656782/a1ef8ba2-7eca-11e6-914a-07e2be4383a1.png)

**Comment by timoschilling** [comment]
Thats a Arbre issue not a ActiveAdmin one

**Comment by gbisheimer** [comment]
That's correct, but it affects Active Admin as it is a required dependency. I will move the issue to Arbre repository. Thanks!
