### ISSUE TITLE
fields_for in Active Admin is not displaying all records

### ISSUE THREAD

**Issue by Bilkhaan** [activeadmin/activeadmin#4644]
I have used a html partial in active admin form and created 2 associated records. But the issue is that only one record is displayed in the table and the other is ignored. Here is my code:

```
<%= semantic_form_for [:admin, resource], builder: ActiveAdmin::FormBuilder do |f| %>
   <%= f.inputs "detail" do %>
      <table>
         <tr>
            <th>field</th>
            <th>label #1</th>
            <th>label #2</th>
          </tr>
          <%= f.fields_for :games do |b| %>
             <tr>
                <td><%= b.input :field, :label => false %></td> 
                <%= b.fields_for :field_labels do |field_label| %>
                  <td><%= field_label.input :team_id, as: :select, collection: Model.all.collect { |model| [model.title, model.id] }, label: false %></td>
                <% end %>
             </tr>
          <% end %>
       </table>
    <% end %>
<% end %>
```
I have 2 field_labels but only one is displayed. Can any suggest any fix for the problem.

**Comment by JakubStadtmuller** [comment]
Did you try put all nested inputs inside "b.inputs" and "field_label.inputs"? Checkout https://github.com/activeadmin/activeadmin/issues/80 and the gregbell's comment. 

IMHO this gem can be helpful with nested form -> https://github.com/nathanvda/cocoon

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
