### ISSUE TITLE
Fix for undefined method `omniauth_authorize_path'

### ISSUE THREAD

**Issue by gaqzi** [activeadmin/activeadmin#4649]
With the latest version of ActiveAdmin from GitHub and Devise 4.0.3 + omniauth_google_oauth2 I'm getting the error `undefined method`omniauth_authorize_path'` when trying to view my login page.

Digging around I found that if I added `helper ::Devise::OmniAuth::UrlHelpers` after `helper ::ActiveAdmin::ViewHelpers` in [active_admin/devise.rb#31](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/devise.rb#L31) makes this work as expected.

Looking at the test code I'm a bit unsure how to actually make a PR but given some hints I could make one for this.

For anyone else that might be seeing this problem I'm currently running with the following monkey patch on my site:

``` ruby
ActiveAdmin::Devise::SessionsController.class_eval do
  helper ::Devise::OmniAuth::UrlHelpers
end
```

**Comment by timoschilling** [comment]
Please post your `config/application.rb`

**Comment by timoschilling** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
