### ISSUE TITLE
using 'each' in :row or :column block produces duplication

### ISSUE THREAD

**Issue by reicheltd** [activeadmin/activeadmin#4653]
Using '1.0.0.pre4' I somehow notices this, whenever I use an 'each' loop inside a :row or :column block.

    column :users do |u|
      u.users.each do |user|
        li link_to user, '#'
      end
    end

If I have 3 users to render, it would render 3 'li' links and beneath the 3 users again. If I dont use 'to_s' in my model, it would be '#<User:0x007f87aec82188>' that would be rendered.

So there is always the exact amout of data right below again when I use an 'each' loop.
This wasnt the case before the '1.0.0.pre4' or earlier.

**Comment by timoschilling** [comment]
change your code to:
```ruby
column :users do |u|
  u.users.each do |user|
    li link_to user, '#'
  end
  nil
end
```

**Comment by reicheltd** [comment]
Thx Timo, that works fine.
Will I have to keep the `nil` there? Why did the behaviour change?
