### ISSUE TITLE
git source insecure warning

### ISSUE THREAD

**Issue by daya** [activeadmin/activeadmin#4654]
Given

`gem 'activeadmin', github: 'activeadmin'`

bundler throws this warning

`The git source `git://github.com/activeadmin/activeadmin.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.`

any alternatives?

**Comment by timoschilling** [comment]
This is a bundler issue, see: http://bundler.io/v1.13/man/gemfile.5.html#GITHUB
This can fix your problem: http://bundler.io/v1.13/man/gemfile.5.html#GIT (via https)

**Comment by seanlinsley** [comment]
This is what I do:
```ruby
# Force the `github:` syntax to use HTTPS instead of the Git protocol.
# The Git protocol isn't encrypted, and so is subject to MiTM attacks.
# This can be removed once Bundler 2.0 is released.
# https://github.com/bundler/bundler/pull/2569
git_source :github do |repo|
  repo = "#{repo}/#{repo}" unless repo.include? '/'
  "https://github.com/#{repo}.git"
end
```

**Comment by dmitry** [comment]
Any easier solution in novadays?
