### ISSUE TITLE
Custom pages documentation displaying incorrect links

### ISSUE THREAD

**Issue by jonathanyeong** [activeadmin/activeadmin#4655]
The [Custom Pages](http://activeadmin.info/docs/10-custom-pages.html) documentation displays incorrect links, specifically for the [Customize the Menu](http://activeadmin.info/docs/10-custom-pages.html#customize-the-menu) and [Add a Sidebar](http://activeadmin.info/docs/10-custom-pages.html#add-a-sidebar) sections.

The links link to http://activeadmin.info/docs/2-resource-customization.md#customize-the-menu
and http://activeadmin.info/docs/7-sidebars.md, respectively. 

The fix would be to replace the .md with .html.

**Comment by thomas0087** [comment]
The documentation on http://activeadmin.info is out date, the [docs](https://github.com/activeadmin/activeadmin/tree/master/docs#activeadmin-documentation) and [wiki](https://github.com/activeadmin/activeadmin/wiki) are recommended instead.
