### ISSUE TITLE
How do I separate admin panel into two parts?

### ISSUE THREAD

**Issue by afuno** [activeadmin/activeadmin#4656]
It is necessary to implement the project in two admin panel:

1. Usual admin panel for administrators (`/admin` path).

2. Admin panel for editors (user role; `/editor` path). And to restrict access to specific sections and actions in them.

On your site I found nothing on the subject. Either I do not understood nothing. :)

Please help to solve this problem.

**Comment by timoschilling** [comment]
You need Namespaces, this should help you: https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/docs/1-general-configuration.md#namespaces
https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/docs/2-resource-customization.md#customize-the-namespace
https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/docs/13-authorization-adapter.md

**Comment by afuno** [comment]
@timoschilling I added it to the configuration:
```
config.namespace :editor do |namespace|
	admin.site_title = 'Editor'
end
```

Now, at the address "/editor", I get it:

> Unable to autoload constant Editor::DashboardController, expected /path/to/app/controllers/editor/dashboard_controller.rb to define it

Well. I create the file with this content:
```
module Editor
	class DashboardController
		# ...
	end
end
```

As a result, I get it:

> undefined method `make_response!' for Editor::DashboardController:Class

**Comment by timoschilling** [comment]
You don't need this:
```ruby
module Editor
    class DashboardController
        # ...
    end
end
```

What files do you have in your `app/admin` folder?
