### ISSUE TITLE
Comments should be able to be added during edit

### ISSUE THREAD

**Issue by jostster** [activeadmin/activeadmin#4657]
When editing a record people should be able to also add comments. Probably the best solution would be to allow comments to be programmatically generated so a user can display a field for the comment input. When the record is saved, it is then also added to the comments.

**Comment by timoschilling** [comment]
You can do that if you build a relation on your Models and build a Form Field for that relation.
See #2149 for some details.
closed as double of #2149

**Comment by jostster** [comment]
@timoschilling Doing a relation doesn't seem to work as it isn't populating the resource, author, or namespace. I ended up trying this and it still doesn't save the comment.

```
f.inputs "Add A Comment" do
          f.semantic_fields_for :comments, ActiveAdmin::Comment.new do |c|
            c.inputs :class => "" do
              c.input :resource_id, :input_html => { :value => "1" }, as: :hidden
              c.input :resource_type, :input_html => { :value => "Member" }, as: :hidden
              c.input :namespace, :input_html => { :value => :admin }, as: :hidden
              c.input :body, :label => "Comment"
            end
          end
        end
```

**Comment by timoschilling** [comment]
do you have a `accept_attributes_for :comments` on your model?

**Comment by jostster** [comment]
I have
```
has_many :comments, as: :resource, dependent: :destroy, class_name: 'ActiveAdmin::Comment'
accepts_nested_attributes_for :comments, reject_if: :reject_comment
```

**Comment by timoschilling** [comment]
what shows your console as received params?
`Parameters: {"utf8"=>"✓", "filter"=>{"q"=>"dewde"}}`

**Comment by jostster** [comment]
```
@_params = {ActionController::Parameters} ActionController::Parameters (8 elements)
 'utf8' = "✓"
 '_method' = "patch"
 'commit' = "Update Member"
 'member' = {ActionController::Parameters} ActionController::Parameters (47 elements)
  'photo_cache' = ""
	...
  'status_histories_attributes' = {ActionController::Parameters} ActionController::Parameters (1 element)
  'attachments_attributes' = {ActionController::Parameters} ActionController::Parameters (1 element)
  'comments_attributes' = {ActionController::Parameters} ActionController::Parameters (1 element)
   '0' = {ActionController::Parameters} ActionController::Parameters (4 elements)
    'resource_id' = "1"
    'resource_type' = "Member"
    'namespace' = "admin"
    'body' = "test"
  'notes' = ""
 'controller' = "admin/members"
 'action' = "update"
 'id' = "1"
```
@timoschilling

**Comment by timoschilling** [comment]
looks ok.

Sorry I didn't have the time to help you more then pointing you in the right direction.
Maybe Stackoverflow or a other Developer can help

**Comment by jostster** [comment]
np, Yea i already posted on SO a few weeks ago but no response, just put a bounty on it today.

**Comment by timoschilling** [comment]
Post the link here, maybe it will help

**Comment by jostster** [comment]
http://stackoverflow.com/questions/39989569/add-active-admin-comments-during-edit

**Comment by jostster** [comment]
I finally solved this! thanks for the assistance. Posted the answer on SO
