### ISSUE TITLE
display_name method not working

### ISSUE THREAD

**Issue by maxpark-jd** [activeadmin/activeadmin#4658]
- I have no `config.display_name_methods` setting in my active_admin config.
- `display_name` method is created with a string in the model.
- In the `new` action, when I set pry right after `form do |f|`, `model.display_name` in the pry console correctly shows the string set.

However, in the actual loaded page, breadcrumb text is the original model name, not the string set with display_name method. Can you guide me to find what is interfering?

I even tried to set `config.display_name_methods` and use that method name, but the result was the same. When I set pry in the 'new' page, I could get the string set with the new method, but the actual loaded page only uses the original model name instead of newly set string in its breadcrumb.

Rails 4.1.1
Gemfile entry: `gem 'activeadmin', github: 'gregbell/active_admin'`

Thank you!

**Comment by chumakoff** [comment]
The `display_name` method was designed to display names of a persistent records. It is used in breadcrumbs on pages like 'show' and 'edit'. In your case, on the new page, the record is not persisted, so it is not going to have a name. The `display_name` method represents a name of a Model instance. What you are trying to change is the representation of the name of the Model class, aren't you?

For example, on the 'show' page the breadcrumbs are:
ADMIN / PRODUCTS / PRODUCT_NAME

'PRODUCT_NAME' is the place where `display_name` method works.

On the 'new' page the breadcrumbs are: 
ADMIN / PRODUCTS /
The `display_name` has nothing to do with 'PRODUCTS' here.

This link might help you do what you need http://www.rubydoc.info/github/gregbell/active_admin/ActiveAdmin%2FDSL%3Abreadcrumb

**Comment by timoschilling** [comment]
@chumakoff 👍

**Comment by maxpark-jd** [comment]
Thank you @chumakoff. If I use the `breadcrumb` method, it forces the same breadcrumb for all pages of a controller and it doesn't change breadcrumb dynamically. For example, if I do 
```
   breadcrumb do
      [
          link_to('admin', admin_dashboard_path),
          link_to('new name', admin_old_model_names_path)
      ]
    end
```
the breadcrumb will be always those two links, even in the index page which is not desirable. I ended up inserting a code to check if the path includes old model name and set it to the new name in ActiveAdmin::ViewHelpers::BreadcrumbHelper module's breadcrumb_links method. I don't like a hack but I couldn't find any other good way to achieve this. (I didn't want to use javascript, either.)

**Comment by chumakoff** [comment]
There is another way, which is a hack too, but perhaps a better solution:

 
    breadcrumb do
      if request.params[:action] == "new"
        [
          link_to('admin', admin_dashboard_path),
          link_to('new name', admin_old_model_names_path)
        ]
      else
        breadcrumb_links # this shows default links
      end
    end

**Comment by maxpark-jd** [comment]
Thank you @chumakoff ! I agree, this is much cleaner.
