### ISSUE TITLE
link_to within map blocks return plain texts in index page

### ISSUE THREAD

**Issue by hegwin** [activeadmin/activeadmin#4660]
My model `EmissaryTaskType` has_many `AimBuffPrototypes`, I want show the names with links of all the buff_prototypes of an emissary_task_type in index page. So I have:

```ruby
ActiveAdmin.register EmissaryTaskType do
  index do
    column 'ID', :id
    column :name
    column :category
    column :default_duration
    column :work_required
    column 'Aim Buffs' do |task_type|
      task_type.aim_buff_prototypes.map do |buff|
        link_to buff.name, admin_buff_prototype_path(buff)
      end.join(' | ')
    end

    actions
  end
end
```
I expect to get a list of links separated  by "|", but I just got plain <a> text. What should I do?

![screenshot](https://cloud.githubusercontent.com/assets/1659895/20095337/148f2456-a5e0-11e6-8be4-0edd6c3fd3ba.png)

**Comment by timoschilling** [comment]
```ruby
    column 'Aim Buffs' do |task_type|
      task_type.aim_buff_prototypes.map do |buff|
        link_to buff.name, admin_buff_prototype_path(buff)
      end.join(' | ').html_safe
    end
```

**Comment by hegwin** [comment]
Thank you and... sorry for that it seems to be a silly question...
