### ISSUE TITLE
"Admin Details" is not translated

### ISSUE THREAD

**Issue by mdesantis** [activeadmin/activeadmin#4662]
"Admin Details" in [lib/generators/active_admin/install/templates/admin_user.rb.erb](https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/lib/generators/active_admin/install/templates/admin_user.rb.erb#L22) is not translated. I suggest to replace it with something like  `t('active_admin.admin_user.admin_details')`.

**Comment by timoschilling** [comment]
Yes that is something that could be work with `t`, but I don't will it change.
The reason is that the file name, the related model name and the following that convention the locale key, is depending on the user class name, and we don't provide translations for models or user configurable things.
