### ISSUE TITLE
[Rails 5] All formtastic inputs disappeared

### ISSUE THREAD

**Issue by anthony-robin** [activeadmin/activeadmin#4664]
I am currently migrating my Rails application from 4.2.7.1 to 5.0.0.1.

When I try to create or edit a resource, all inputs, textarea, select, ... disappeared from form. 
I made some experiment with Devise views: replacing `active_admin_form_for` by `simple_form_for` make fields to appear (with broken style) which make me think there is an issue with `formtastic`.

I'm not sure to understand what changed in this new version because everything was working in 4.2. 

Here is a screenshot of my invisible inputs form:  

<img width="1279" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5428510/20249245/9cf89890-a9f5-11e6-8200-220a934e6d10.png">  

**My stack**:
- Rails 5.0.0.1 / Ruby 2.3.0
- ActiveAdmin 1.0.0pre4
- ActiveAdmin Addons 0.9.3
- Formtastic 3.1.4
- Devise 4.2.0
- Devise I18n-views 1.1.1

**Comment by zorab47** [comment]
Can you post some details about your `form` block? It is difficult to help without more information.

**Comment by anthony-robin** [comment]
Here is an extract of my resource:

```ruby
ActiveAdmin.register Blog do
  ...

  form do |f|
    f.semantic_errors(*f.object.errors.keys)
	
    f.inputs t('formtastic.titles.post_generals') do
      f.input :allow_comments
      f.input :online
    end

    ...
  end

  ...
end
```

Source files:
- [ActiveAdmin Blog resource](https://github.com/lr-agenceweb/rails-starter/blob/feature/Rails5/app/admin/optional_modules/blogs/blog.rb#L45)
- [ActiveAdmin Form view](https://github.com/lr-agenceweb/rails-starter/blob/feature/Rails5/app/views/admin/posts/_form.html.arb)
- [Gemfile](https://github.com/lr-agenceweb/rails-starter/blob/feature/Rails5/Gemfile.lock)
- [Full project](https://github.com/lr-agenceweb/rails-starter/tree/feature/Rails5)

Thanks !

**Comment by anthony-robin** [comment]
After more investigations, the guilty gems is `ActiveAdminAddons` with `Enumerize` support.
Removing `enumerize` in my code make forms to appears again.
