### ISSUE TITLE
Custom sort on specific column incompatible with filters

### ISSUE THREAD

**Issue by chdem** [activeadmin/activeadmin#4678]
Hello,

In my application, users can put elements in a temporary table. Elements in this table are "starred". Here the index/column concerned :
```ruby
column "STARRED", sortable: 'star_count' do |element|
  if !current_user.settings[:elements_array].nil? &&(current_user.settings[:elements_array]).include?(element.id)
    fa_icon('star')
  end
end
```

As you can see, users can sort the index by 'starred' elements on a specific column called 'star_count'. Here my code that create a column and name it in a SQL way. Everything's made in scoped_collection :
```ruby
def scoped_collection
  rank_col = "(CASE elements.id "
  if !current_user.settings.elements_array.nil?
    current_user.settings.elements_array.each_with_index do |id, index|
      rank_col << "WHEN #{ id } THEN #{ index } "
    end
  else
    rank_col << "WHEN -1 THEN 0 "
  end
  rank_col << 'ELSE NULL END)'

  end_of_association_chain.select("*, #{ rank_col } as star_count").includes([:elements_groupe,:patient,:sgl_key,:status])

end
```

This code is running perfectly......except when I'm using filter.....
With filters, a strange behaviour appearing : 
- all the elements are correctly printed in the index BUT the id column is set to 1 for all.....
- because id is 1, my code in index/column is not able to print the 
```ruby 
fa_icon('star')
```

Do you have any idea of the reason of this bug ?
Perharp my method is not good at all....

Thank you for helping me !

**Comment by chdem** [comment]
Hello,
Just an update....
:)

**Comment by Fivell** [comment]
@chdem , can you show what raw sql query is performed when filters present and what is difference from raw sql that is performed without filters?

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
