### ISSUE TITLE
Sprockets::FileNotFound: couldn't find file 'jquery-ui/datepicker' with type 'application/javascript'

### ISSUE THREAD

**Issue by afuno** [activeadmin/activeadmin#4683]
I can not understand why this error occurs?

I did not do anything in the Active Admin files. I did not touch any JS files.

/app/assets/javascripts/active_admin.coffee:

```
#= require active_admin/base
#= require jqueryui-editable.min
#= require ckeditor/init
```

The problem in this line:

`#= require active_admin/base`

If you delete this line, the file `active_admin.coffee` is successfully compiled.

**Comment by afuno** [comment]
I understood what was the problem.

It is necessary to this line:

`gem 'activeadmin', '~> 1.0.0.pre4'`

To replace on this:

`gem 'activeadmin', github: 'activeadmin'`

After these steps, I have everything compiled.

**Comment by mauriciopasquier** [comment]
`jquery-ui-rails` [changed the way to load assets](https://github.com/jquery-ui-rails/jquery-ui-rails#require-specific-modules) in version 6
