### ISSUE TITLE
dashboard index page blank

### ISSUE THREAD

**Issue by bennyzr** [activeadmin/activeadmin#4686]
Hi,

I am using Rails 5 with devise & pundit. When navigatin to the admin_root_path I get a blank page. Other than setting Pundit in the config I am using the default generated configuration. Below are the logs:

Processing by Admin::DashboardController#index as HTML
  User Load (4.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 16 ORDER BY `users`.`id` ASC LIMIT 1
Completed 200 OK in 58ms (ActiveRecord: 7.8ms)

Any ideas? Thanks.

**Comment by timoschilling** [comment]
please post a screenshot

**Comment by bennyzr** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1097846/20910697/1e7be1dc-bb31-11e6-83ea-a75764d14eb7.png)

**Comment by timoschilling** [comment]
please post the console output

**Comment by bennyzr** [comment]
Started GET "/admin" for 127.0.0.1 at 2016-12-05 22:59:27 -0500
Processing by Admin::DashboardController#index as HTML
  User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 16 ORDER BY `users`.`id` ASC LIMIT 1
Completed 200 OK in 5ms (ActiveRecord: 0.4ms)

**Comment by bennyzr** [comment]
I even put a byebug statement in the "ActiveAdmin.register_page "Dashboard" do" block which did not stop execution. Where would I put a bye bug statement upstream to determine why the code is not being executed?

**Comment by bennyzr** [comment]
I narrowed down the issue to Pundit. Active Admin was resolving to an unauthorized status which was redirecting too a blank page.

I also had this in my active_admin config file:   
config.on_unauthorized_access = :root_path

I now am trying to figure out how to get a pundit policy to be called by the Admin::DashboardController. Namespaces seem to be an issue with Pundit.
