### ISSUE TITLE
How to pass validation errors and keep values

### ISSUE THREAD

**Issue by Awatatah** [activeadmin/activeadmin#4691]
Hello, I have a custom controller (I'm using it as a patch for issue #4685)
the problem I need to fix is the validation errors and keeping the form data. Before I did the custom controller, the errors would pop up underneath the input field like so 

![screen shot 2016-12-07 at 5 43 52 pm](https://cloud.githubusercontent.com/assets/17914534/20992962/c44e16c4-bca4-11e6-96f0-5254d022a837.png)

but now they do not show up. Please help! Thanks :)

**ActiveAdmin.register**
```
controller do
	    def create
	      @section = AbqCouncilors::Councilor.create!(permitted_params[:abq_councilors_councilor].as_json)
              redirect_to admin_faq_sections_path, notice: "Section was successfully created!"      	
	    end
	end
```

**Comment by dmitry** [comment]
Looks like it should raise an error on validator error or proceed to redirect on a list. You have to write additional logic in `create` action method.

**Comment by Awatatah** [comment]
@dmitry have an example?

**Comment by Awatatah** [comment]
I got it with 
```
controller do
	    def create
	      @section = AbqCouncilors::Councilor.new(permitted_params[:abq_councilors_councilor].as_json)
	      	if @section.save
		        flash[:notice] = "Councilor was successfully created!"
		        redirect_to admin_abq_councilor_path(@section.id)
		else
		  	flash[:error] = "Your form is missing or has incomplete fields. Please review your entry below."
       			render action: 'new'
		 end
	    end
	end
```
