### ISSUE TITLE
disable turbolinks for AA pages

### ISSUE THREAD

**Issue by bennyzr** [activeadmin/activeadmin#4693]
What would be the most elegant way to disable turbo links for only AA and not the whole site? How to embed data-no-turbolink into the body of AA pages via a before action or something similar?

**Comment by bennyzr** [comment]
I imagine that the best place for disabling turbo links for all Active Admin pages would be in the config. However since I don't see such an option what would be the next best option?

**Comment by dmitry** [comment]
Just copy-paste `active_admin.js` from the source-code into the `app/assets/javascripts/` and remove turbolinks from there.

**Comment by bennyzr** [comment]
Wouldn't that remove turbolinks from the whole app as well? I was thinking of somehow adding a data-no-turbolink attribute to the body tag of all AA pages.

**Comment by dmitry** [comment]
No, it will remove only from the AA.

**Comment by bennyzr** [comment]
I already have a active_admin.js.coffee file in my app/assets/javascripts. It has a one liner: #= require active_admin/base. I tried removing //= require turbolinks from my application.js though that caused other problems.

**Comment by dmitry** [comment]
In that case add `active_admin/base.js` to your assets and remove `//= require turbolinks` from it.

**Comment by bennyzr** [comment]
Moving base.js.coffee to my assets causes broken references to some of the files referenced in base.js.coffee.

#= require jquery
#= require ./jquery_ui
#= require jquery_ujs
#= require_self
#= require_tree ./lib
#= require_tree ./ext
#= require_tree ./initializers

Are you suggesting to copy all of these files to my assets?

**Comment by bennyzr** [comment]
Well, I copied all the files to my assets and the js & css errors went away. 

I'm confused though. Originally I removed the js require tree . directive due to some issues and now copying all the active admin js files to my assets fixes everything.
