### ISSUE TITLE
Improvement: Keep the current scope when deleting multiple records from the list view

### ISSUE THREAD

**Issue by besi** [activeadmin/activeadmin#4694]
### Situation

I have a list of products and I have several scopes to tidy up my lists.
I often work in the scope **Today** where I usually delete products that I no longer need.

![screen shot 2016-12-12 at 23 09 03](https://cloud.githubusercontent.com/assets/160412/21118878/2991eece-c0c0-11e6-8fbf-0db2569214ff.png)

### Current behaviour
As soon as I select multiple products and delete them I am thrown back to the main scope. As shown on the screenshot.

![screen shot 2016-12-12 at 23 09 21](https://cloud.githubusercontent.com/assets/160412/21118886/2f621806-c0c0-11e6-89b4-70f371242a67.png)

### Expected behaviour
Since the scope works nicely for sorting the items and filtering I would expect that I remain in the current scope when deleting items from the list.

Thanks for considering this change

**Comment by timoschilling** [comment]
double of #3833
