### ISSUE TITLE
Monkey patch ActiveAdmin::Views::Pages::Base.build

### ISSUE THREAD

**Issue by bennyzr** [activeadmin/activeadmin#4695]
I would like to add and call a method add_attributes_to_body in the ActiveAdmin::Views::Pages::Base.build method in order to be able to add an attribute to the body tag in Active Admin pages. Can anybody help me with the monkey patch? When attempting to do this:

ActiveAdmin::Views::Pages::Base.class_eval do
	def add_attributes_to_body
		@body.attributes[:"data-no-turbolink"] = "true"
	end
end

 I run into the following error:

.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:512:in `load_missing_constant': Unable to autoload constant ActiveAdmin::Base, expected app/lib/active_admin/base.rb to define it (LoadError)

**Comment by timoschilling** [comment]
If you want to do things like that you need to find a solution by your self

**Comment by bennyzr** [comment]
I am only taking this approach since I need a quick solution to this problem in my production environment. I would be happy to explore a more elegant solution going forward.
