### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by mehdi9500** [activeadmin/activeadmin#4698]
I puts: 
gem 'devise', '~> 4.2'
gem 'activeadmin', '~> 1.0.0.pre4'
in Gemfile and update and  install bundle but after rails g active_admin:install I get Could not find gem 'activeadmin (~> 1.0.0.pre4) x64-mingw32' in any of the gem sources listed in your Gemfile or available on th
is machine.
Run `bundle install` to install missing gems.
errors messages.

**Comment by timoschilling** [comment]
maybe a problem in your environment setup, ask on stackoverflow
