### ISSUE TITLE
Active Admin displays record successfully destroyed after aborted delete

### ISSUE THREAD

**Issue by bennyzr** [activeadmin/activeadmin#4700]
How do I get Active Admin to recognize an aborted delete of a record and display an error message instead of the successful delete message.

**Comment by varyonic** [comment]
[Modify the controller](http://www.activeadmin.org/docs/8-custom-actions.html) action provided by [inherited_resources](https://github.com/activeadmin/inherited_resources)
```
  controller do
    def destroy
      destroy! do |success, failure|
	failure.html do
	  flash.now[:error] = ...
	end
    ...
```
Please use [StackOverflow](http://stackoverflow.com/questions/tagged/activeadmin) for general help requests, open an issue if you suspect a bug.
