### ISSUE TITLE
Whats the syntax(expected return) for .xml.builder

### ISSUE THREAD

**Issue by IvRRimum** [activeadmin/activeadmin#4701]
So i added a file `/views/admin/payments/index.xml.builder` and active admin finds it.

But whats the syntax? What should this file return, so it would show in the `/payments.xml` ?

Thanks!

**Comment by IvRRimum** [comment]
If i add just `<asd></asd>` to the builder i get this error:

```
syntax error, unexpected '<', expecting keyword_end
...f.output_buffer = xml.target!;<asd>ads</asd>
...             
```                  ^

**Comment by IvRRimum** [comment]
After digging google for a few HOURS, i finally got some [pointers](http://stackoverflow.com/questions/30078753/rails-xml-builder-not-rendering):

It looks something like this:
xml.bar do
  xml.foo(@payments.first.status)
  xml.bar(@payments.first.status)
end

And it works.

Still didn't find original documentation for the matter.

**Comment by varyonic** [comment]
Rendering the XML is done by Rails [Builder::XmlMarkup](http://apidock.com/rails/Builder/XmlMarkup) as described in [this article](https://richonrails.com/articles/outputting-xml-using-ruby-on-rails).  ActiveAdmin simply delegates to Rails in this case.  StackOverflow is a good place for questions like this.
