### ISSUE TITLE
Resource registered twice have unexpected route using belongs_to

### ISSUE THREAD

**Issue by achiinto** [activeadmin/activeadmin#4702]
I have setup so that a Resource is being registered to ActiveAdmin twice, so to have two different sections in the admin panel to manage the same resource. However, when I have other resource admin configured to belongs_to this resource, the route that got created is different.

For example,
```
ActiveAdmin.register VClass do
 # code...
end
```
And the other register under a different folder: admin/r_folder
```
ActiveAdmin.register VClass, as: 'C somehting' do
 # code...
end
```

When I have another resource to belongs to V, like this
```
ActiveAdmin.register QClassdo
  belongs_to :v_class, optional: true
  # code
end
```
...Then the unexpected happened.

When I was working at my development machine, RedHat 6.7, it would generate route as v_class_q_classes_path. But on my production machine, RedHat 7.2, it would genereate route as c_somthing_q_classes_path.

So, I bet this is somewhat related to how the different version of OS access a the list of files/folders differently.

Ideally, it would be nice that I could specify the belongs_to to a more specific registration, maybe by path or the route name.

For a solution right now, I am not using the 'belongs_to', but instead configured a specific nested routes and added scoped_collection with condition based on the parent resource reference in the parameter. This workaround works for me since my belongs_to is optional. But for people that is not using belongs_to optionally but having to configure the admin system with multiple registration of the same resource, they might need a fix/ enhancement to the code, or another type of workaround.

**Comment by dmitry** [comment]
What version of gems do you have on both machines? Better to show both `Gemfile.lock` files here.

**Comment by achiinto** [comment]
both at activeadmin (1.0.0.pre1), you think upgrading will help?

**Comment by achiinto** [comment]
But either way, I think the configuration for Belongs_to does not allow us to specify which registration to resource to use.
```
belongs_to :v_class, optional: true
```
This will become ambiguous of which specific registration, unless it could take this form.
```
belongs_to :v_class, as:  'C somehting', optional: true
```
While without specifying the 'as', it will just default to the one without the 'as'.

I think this come down to these line of code in activeadmin/lib/active_admin/resource/routes.rb
```
def belongs_to_name
  resource.belongs_to_config.target.resource_name.singular if nested?
end
```
Perhaps somehow we need to identify the target properly. I will try to take a look if this is the right path and if the community agree that this is something that can enhance the gem.

**Comment by Fivell** [comment]
@achiinto , did you resolve this?

**Comment by mrstif** [comment]
Had the same behaviour in ActiveAdmin **1.0.0** as I noted in #4965 ... 
The routes were being generated in a seemingly indeterministic way since I had different behaviours on different environments using the exact same code base and gem version...

I also opened a stackoverflow question: http://stackoverflow.com/questions/43998704/activeadmin-generating-wrong-routes-for-belongs-to-association

**Comment by deivid-rodriguez** [comment]
@mrstif and @achiinto. Can you check #5826, I think it should fix the issue you're having.
