### ISSUE TITLE
AuthorizationAdapter with CanCan uses `read` action name for both index and show actions

### ISSUE THREAD

**Issue by RobinDaugherty** [activeadmin/activeadmin#4704]
CanCan expects to be asked to authorize action names such as `show` and `index`, and provides aliases so that both of these can be granted with the single name `read`, allowing the writer of abilities to use the "standard" CRUD names in the Ability model.

However, activeadmin authorizes the action `read` for both showing the index (the `index` action), and showing in individual resource (the `show` action). Because of this, it is not possible to grant `show` on specific records without also allowing the user to `index` those records.

So for example, if you want a user to be able to view and edit their own User record, but not have access to the User index, there's no permission-based way to restrict this access.

This shows Users in the menu even when the user should not have index access to it:
```rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can %i(read update), user if user
  end
end

ActiveAdmin.register User do
  menu if: proc { can? :index, User }
end
```

While this denies access to the user's own profile:
```rb
class Ability
  include CanCan::Ability
  def initialize(user)
    can %i(show update), user if user
  end
end

ActiveAdmin.register User do
  menu if: proc { can? :index, User }
end
```

The solution here is to have activeadmin authorize the `index` and `show` actions instead of `index`. This should work immediately for any project, since CanCan already provides aliases for these action names.

This was previously [discussed](https://github.com/activeadmin/activeadmin/issues/3164#issuecomment-44792837) as part of #3164, but it seems like something that could be done separately from a complete refactoring.

More Info:

- [CanCan action aliases](https://github.com/CanCanCommunity/cancancan/wiki/Action-Aliases)
- [CanCan's default aliases](https://github.com/CanCanCommunity/cancancan/blob/0d833ecc309bde13da86fc3a8587be5a73e372e3/lib/cancan/ability.rb#L413)

**Comment by dmitry** [comment]
Great that you have described an issue you have so detailed, but seems like activeadmin activity is not so rapid, as we all would like to have. I'm waiting for the changes to be merged for few years already, and looks like I have to switch to the alternative admin management system for rails, and I suggest you if you want to stick with ActiveAdmin better do changes on your own, rather than wait until something will happen here.

**Comment by wvteijlingen** [comment]
I use Pundit, but ran into the same problem as you described. Instead of waiting for this to be fixed, I worked around it myself using an initialiser with the following. I don't know how the CanCan adapter works, but this might just work for you.

```ruby
# Active Admin does not differentiate between :index / :read, :new / :create, and :edit / :update.
# We add these missing authorization verbs here.

module ActiveAdmin
  module Authorization
    INDEX = :index
    NEW   = :new
    EDIT  = :edit
  end
end

ActiveAdmin::BaseController::Authorization::ACTIONS_DICTIONARY[:index] = ActiveAdmin::Authorization::INDEX
ActiveAdmin::BaseController::Authorization::ACTIONS_DICTIONARY[:new]   = ActiveAdmin::Authorization::NEW
ActiveAdmin::BaseController::Authorization::ACTIONS_DICTIONARY[:edit]  = ActiveAdmin::Authorization::EDIT
```
