### ISSUE TITLE
Wiki - paper_trail - Wrong instructions for model

### ISSUE THREAD

**Issue by rootux** [activeadmin/activeadmin#4708]
I'm missing something.

why does this says 'in app/admin/**posts**.rb:'
does it mean 'in app/admin/**post**.rb':

https://github.com/activeadmin/activeadmin/wiki/Auditing-via-paper_trail-(change-history)#versioning-models

**Comment by varyonic** [comment]
By convention Rails model source files (app/model) match the class name and are singular, ActiveAdmin DSL files (app/admin) are pluralized.

**Comment by rootux** [comment]
thank you for clearing this up. closing the issue.

**Comment by rootux** [comment]
@varyonic  When I try to create the `posts.rb`
with this content:
```controller do
  def show
      @camp = Camp.includes(versions: :item).find(params[:id])
      @versions = @camp.versions 
      @camp = @camp.versions[params[:version].to_i].reify if params[:version]
      show! #it seems to need this
  end
end
  sidebar :versionate, :partial => "layouts/version", :only => :show
```
I get:
`<top (required)>': undefined method `controller' for main:Object (NoMethodError)`

**Comment by varyonic** [comment]
The wiki is community content, you may want to ask one of the article authors.
