### ISSUE TITLE
Undefined method helper_method for InheritedResources::Base:Class 

### ISSUE THREAD

**Issue by anandshri** [activeadmin/activeadmin#4712]
I am working on 3-tier Rails application it mean Front end and Back end both are rails server and separate.
Front and doesn't have database.yml and Back end doesn't have assets.
Now I wants to use active-admin gem to install.
So I added this Gem in my Back end Gem file for Rails-5 and it installed.
but when I am running rails g active_admin:install --skip-users command getting following error

![activeadmin error](https://cloud.githubusercontent.com/assets/1044427/21677057/6b64e74c-d35e-11e6-8632-d7ec4ca369b4.png)

**Comment by timoschilling** [comment]
Do you use the Rails 5 API only mode?

**Comment by anandshri** [comment]
yes timoschilling I am using config.api_only = true API only mode.

Although by doing below changes issue will resolve.
1) config.api_only = false 
2) class ApplicationController < ActionController::API change to class ApplicationController < ActionController::Base
Is there any approach?

**Comment by timoschilling** [comment]
ActiveAdmin don't work with `api_only` and/or `ApplicationController < ActionController::API`. ActiveAdmin has UI and your setup is not for UI, it is for `api_only`!

**Comment by francirp** [comment]
For those who find this Github issue stumbling around on Google...

The following article shows how to run ActiveAdmin with Rails 5 API only: https://medium.com/superhighfives/a-top-shelf-web-stack-rails-5-api-activeadmin-create-react-app-de5481b7ec0b
