### ISSUE TITLE
Who wants to become an ActiveAdmin Maintainer?

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/activeadmin#4714]
How want to join the ActiveAdmin Maintainer Team and want to support me maintaining ActiveAdmin?

**Comment by varyonic** [comment]
If you are interested I think [this was a great presentation by Daniel Doubrovkine (Artsy, Grape) at Golden Gate Ruby 2014](https://www.youtube.com/watch?v=8ijzefV-B7U).

**Comment by timoschilling** [comment]
I'm disappointed that nobody want to help!

**Comment by seanlinsley** [comment]
ActiveAdmin is particularly difficult for people with no experience maintaining open source projects. There's so much to do that it can be daunting.

If anyone is interested please speak up; we'll do everything we can to help people adjust to the role.

**Comment by joelcollinsdc** [comment]
perhaps tag issues as good for beginners?  or less-technical like documentation / etc?

**Comment by varyonic** [comment]
@timoschilling It is not really true that nobody wants to help, you have added three new maintainers this week, all of which have made previous contributions.  Communicating with contributors and plugin authors is key.  Merging pull requests and making regular releases is also important to maintaining the health of the project and motivating people to make the significant effort to contribute.  I encourage beginners to try Schneeman's codetriage.com.  I also agree tagging issues suitable for beginners is a good idea.

**Comment by timoschilling** [comment]
@varyonic sorry you are right

**Comment by ccallebs** [comment]
@timoschilling and anyone else -- not sure if I have time to be a maintainer but if anyone wants to tag me on bug triage you can offload some of that work. More than happy to help, a lot of the GH notifications get lost in the noise for me though.

**Comment by varyonic** [comment]
Thanks @ccallebs, that's great!  I'm using Octobox to manage notifications.  I'm trying to tag issues 'help wanted' that are up for grabs.  Especially those also tagged 'bug'.

**Comment by emilebosch** [comment]
@seanlinsley I'd love to work on active admin, but i really find it a very very complicated piece of software. There is a lot of meta programming and magic going on for newbies, and that makes it i think also quit hard to maintain. At the moment everything is really outdated to (docs, site etc), but even core dependencies. I'd love to help out but i think, it needs more strategy and a laser sharp focus and maybe a partial rewrite. I love active admin, it's always in my toolshed, and i've been monkey patching it a lot.

**Comment by eshaiju** [comment]
@timoschilling @seanlinsley I love to work and contribute to maintaining and improve this project. I used to raise issues and commits in a few years back. Now thinking about more active in this community if you help me.

**Comment by timoschilling** [comment]
To all people out there that want to help: You're Welcome!!!

But: In the last 2 Year I get round about 1 offer per month from people that would like to become a maintainer. That's nice! The problem was, that the most of them had mostly mate between zero or two PR's or had helped closing other peoples issues. It's hard to estimate their engagement. Some of them maybe just want to get there hacky PR's merged.

I think I tell this in the name of all other maintainer, If you want to help, just do it! Write PR's, help other people closing their issues. Don't worry, doing something wrong, we will help you! And if we think you are doing a good job, we will ask you to join us.

For now I log this Issue.
