### ISSUE TITLE
Bad parameter name in belongs_to resource route

### ISSUE THREAD

**Issue by Aschen** [activeadmin/activeadmin#4718]
Hi,

I have 2 models :
```ruby
class Serie < ApplicationRecord
  belongs_to :admin_user
  has_many :seasons
end

class Season < ApplicationRecord
  belongs_to :serie
end
```
and the associated configuration for `active_admin`
```ruby
ActiveAdmin.register Season do
  belongs_to :serie, parent_class: Serie
  permit_params :number, :serie_id
  navigation_menu :serie
end

ActiveAdmin.register Serie do
  permit_params :name, :admin_user_id
  menu label: "Mes séries", priority: 1
  sidebar "Saisons", only: [:show, :edit] do
    ul do
      li link_to "Toutes les saisons", admin_series_seasons_path(serie)

      serie.seasons.each do |season|
        li link_to "#{season}", admin_series_season_path(serie, season)
      end
    end
  end
end
```

When I try to access a season via the generated links in the sidebar menu, I can't retrieve my `Serie`. (`ActiveRecord::RecordNotFound in Admin::SeasonsController#show  Couldn't find Serie with 'id'=`)

After some investigations the problem seems to be the param name, the finder method try to find my model with `params[:serie_id]` but the param is named `series_id` in my routes :
```ruby
batch_action_admin_series_seasons POST       /admin/series/:series_id/seasons/batch_action(.:format) admin/seasons#batch_action
             admin_series_seasons GET        /admin/series/:series_id/seasons(.:format)              admin/seasons#index
                                  POST       /admin/series/:series_id/seasons(.:format)              admin/seasons#create
          new_admin_series_season GET        /admin/series/:series_id/seasons/new(.:format)          admin/seasons#new
         edit_admin_series_season GET        /admin/series/:series_id/seasons/:id/edit(.:format)     admin/seasons#edit
              admin_series_season GET        /admin/series/:series_id/seasons/:id(.:format)          admin/seasons#show
                                  PATCH      /admin/series/:series_id/seasons/:id(.:format)          admin/seasons#update
                                  PUT        /admin/series/:series_id/seasons/:id(.:format)          admin/seasons#update
                                  DELETE     /admin/series/:series_id/seasons/:id(.:format)          admin/seasons#destroy

```

You can see that the expected param name is `serie_id` in the `parent_config` hash.
![active_admin_issue](https://cloud.githubusercontent.com/assets/4447392/21804102/8569bc80-d72d-11e6-8134-6171e093ad1f.png)

How can I tell to active_admin the right parameter name ?

**Comment by Fivell** [comment]
@Aschen , you're able to specify options when declaring ```belongs_to```  for instance 
```finder``` and ```param``` (you can see it in your attached screen)

Looks like in your case you can declare ```param: :series_id```

so 

```ruby
belongs_to :serie, parent_class: Serie,  param: :series_id
```

Checkout how inherited resources loads parent object 

https://github.com/josevalim/inherited_resources/blob/db803393cf852656b8d516ca0d54ccaf9c2ea2af/lib/inherited_resources/belongs_to_helpers.rb#L90



Inherited resources belongs_to declaration explanation

https://github.com/josevalim/inherited_resources/blob/db803393cf852656b8d516ca0d54ccaf9c2ea2af/lib/inherited_resources/class_methods.rb#L83

**Comment by Aschen** [comment]
@Fivell Thanks you, it's exactly what I am looking for !
