### ISSUE TITLE
has_many checkboxes join table not saving data

### ISSUE THREAD

**Issue by anandshri** [activeadmin/activeadmin#4719]
class Business < ApplicationRecord
	has_many :business_categories
	has_many :categories, through: :business_categories
end

class BusinessCategory < ApplicationRecord
  belongs_to :business
  belongs_to :category
end

class Category < ApplicationRecord
  has_many :business_categories
  has_many :businesses, through: :business_categories
end

Now I wants to create a business with categories.
that entries should be go in join table(:business_id, :category_id) not in category table.

    f.inputs 'Business' do
      f.input :name
      f.fields_for :business_categories, BusinessCategory.new do |business_category|
        business_category.input 'category_id' , as: :check_boxes, collection: Category.all.map{|category| [category.name, category.id]} 
    end
    f.actions
  end

Params : 

usiness"=>{"name"=>"Test Businessas", "website"=>"http://www.google.com", "email"=>"test1@example.com", "description"=>"", "business_price_range_id"=>"1", "business_gender_id"=>"1", "booking_enabled"=>"false", "avg_wait_time"=>"0", "business_address_attributes"=>{"street"=>"", "pincode"=>"456012", "locality_id"=>"1", "sub_locality_id"=>"6", "latitude"=>"", "longitude"=>""}, "business_categories_attributes"=>{"0"=>{"category_id"=>["", "1", "2"]}}}, "commit"=>"Create Business"}

although only a single entry is going in join table with category_id null :(

**Comment by dmitry** [comment]
You forgot `accepts_nested_attributes_for` in one of your models.

**Comment by anandshri** [comment]
no dmitry it is there I did not mentioned.

Although the issue if I will allow all params.
  def permitted_params
      params.permit!
   end

**Comment by dmitry** [comment]
It's hard to tell you where to look, because you haven't provided all the necessary information. Looks like an issue in `permit_params` or somewhere else.

**Comment by dmitry** [comment]
Please close or answer.

**Comment by timoschilling** [comment]
I will reopen it if you answer
