### ISSUE TITLE
Single Table Inheritance: Unable to update row type.

### ISSUE THREAD

**Issue by denodster** [activeadmin/activeadmin#4723]
I have a User model that uses single table inheritance to determine a user's role So a user can be a 'User' or an 'Admin' or a 'SuperAdmin' Etc. I have models for each type and I have a registred a single 'Users' page on active admin. So far so good.

Now if I want to change an 'Admin' into a 'User' I run into trouble. I get a NotFound Error

```
ActiveRecord::RecordNotFound at /admin/users/9999
Couldn't find Admin with 'id'=9999 [WHERE `users`.`user_type` IN ('Admin')]
```
Since we also have a way to do this using our front end interface, I ran into this problem there too. The solution was to use the .becomes method. if the object `becomes` it's base class before being updated it accepts the new type without issue, but if this step is skipped it fails to update with a not found error.

`admin.becomes(User).update(user_params)`

I would make a PR myself but I'm not really familiar with the ActiveAdmin codebase and I assume someone else might be able to make this patch quicker.

**Comment by varyonic** [comment]
Have you reviewed [Customizing resource retrieval](http://www.activeadmin.org/docs/2-resource-customization.html)?  The specs for STI are in [features/sti_resource.feature](https://github.com/activeadmin/activeadmin/blob/master/features/sti_resource.feature)  See also #52

**Comment by Fivell** [comment]
@denodster , your case is very specific, and as I understand your issue is about you need to redirect to another resource after update. 

to override redirect behaviour use next aproach


controller do
  def update
    update! do |format|
      format.html { redirect_to  ....  }
    end
  end
end

**Comment by Fivell** [comment]
@varyonic , can we close this? what do you think ?
