### ISSUE TITLE
The activeadmin/inherited_resources repo, referenced for Rails 5, doesn't exist

### ISSUE THREAD

**Issue by tjwallace** [activeadmin/activeadmin#4727]
The [inherited_resources repo](https://github.com/activeadmin/inherited_resources), [referenced for Rails 5](https://github.com/activeadmin/activeadmin/blob/master/README.md#rails-5) not longer exists.

Was it removed on purpose? Is that dependency no longer required to run activeadmin on Rails 5?

**Comment by timoschilling** [comment]
We are currently transferring the josevalim/inherited_resources repo into the activeadmin org, thats why we need to remove it temporary.

**Comment by tjwallace** [comment]
Thanks @timoschilling. Could you update this issue when everything is good to go?

**Comment by timoschilling** [comment]
It should be back

**Comment by markrebec** [comment]
Yup, looks like we're able to bundle again! Thanks @timoschilling
