### ISSUE TITLE
Custom CSV on Heroku leads to H17

### ISSUE THREAD

**Issue by rootux** [activeadmin/activeadmin#4730]
I just implemented my own
`csv do`
and now when I press on export as CSV I get H17 from heroku means

> H17 - Poorly formatted HTTP response
> Our HTTP routing stack has recently changed and no longer accepts responses that are missing a reason phrase in the status line. ‘HTTP/1.1 200 OK’ will work with the new router, but 'HTTP/1.1 200’ will not.

This works locally I assume it's related to CSV streaming.

**Comment by Fivell** [comment]
@rootux ,FYI if default csv exports works and custom doesn't it means that problem is in your implementation.

**Comment by rootux** [comment]
Yes. it was an error on my end. closing.

**Comment by rylanb** [comment]
Adding some info about WHAT the problem was on your end could have helped those who come after. 

Any recall what the issue was? Having this issue but can't figure out what could be causing it as its so generic.

**Comment by rootux** [comment]
Hmmm.. Yes that's a good idea for future me.

This was from the day I told it was closed - 
https://github.com/Midburn/Dreams/commit/bf76078973228a2f3b25331ba9f2524c249430eb#diff-c9bbbddadbe122f8bb90b6fdd26d12eb

Or maybe this one fixed it?
https://github.com/Midburn/Dreams/commit/72273f95768ccc6a136ea5e081a0230dda748e9e#diff-c9bbbddadbe122f8bb90b6fdd26d12eb

**Comment by rylanb** [comment]
Thanks for posting those! Not 100% sure they will fix any issue I am having, but will compare.
