### ISSUE TITLE
active_admin_comments table ruins the schema.rb after migrating on Rails 5

### ISSUE THREAD

**Issue by kiote** [activeadmin/activeadmin#4736]
## Anamnesis

Quite specific set of conditions to reach that, but that might be not so rare-to-meet conditions:

1. PostgreSQL as a database;
2. Rails upgrade from 4 to 5;
3. Master branch of ActiveAdmin;
4. Being an old fan of active admin (since 2012 at least, I'll explain later why it's important);
5. Run migration with `rails db:migrate` after upgrade leads to 

```
 id: :integer, default: -> { "nextval('admin_notes_id_seq'::regclass)" }
```

this part to be added in `schema.rb` file for `active_admin_comments` table.

Then the attempt to recreate database for testing fails with postgresql has no idea what `admin_notes_id_seq` is.

## Why 

`admin_notes` table had been renamed to `active_admin_comments` long time ago (back to 2012), but the sequence for that table still stayed with the same name (`admin_notes_id_seq`).

Seems like rails 4 doesn't really care about this divergence, but rails 5 does. I suspect that rails 5 wants to see `active_admin_comments_id_seq` here, so it creates it automatically for us. But then it sees somewhere underneath that table `active_admin_comments` associated with `admin_notes_id_seq`, thinks "okay, whatever" and carelessly adds this line to `schema.rb`.

But it does not create `admin_notes_id_seq`, and database re-creation from `schema.rb` fails.

## Suggestion (how to fix)

I can suggest to add a migration which renames `admin_notes_id_seq` (if exists) to `active_admin_comments_id_seq`, we can do that in our app only, but it seems like it might affect other oldfags like us, too.

**Comment by deivid-rodriguez** [comment]
Uggg... That's bad, but I'm not sure if it's worth fixing inside ActiveAdmin since this only affects very old installations and I don't think AA currently provides an upgrade mechanism...

**Comment by kiote** [comment]
Okay, need to say that renaming really helps here. Should I close the issue then?

**Comment by deivid-rodriguez** [comment]
Yeah, I know, I've been there and had similar problems in the future: https://github.com/rails/rails/issues/12856. The thing is I'm not sure how we can fix this inside AA. What do you suggest? I don't think adding a migration helps because migrations are only run once when you install AA, right?

**Comment by kiote** [comment]
uh, yes, seems like it's a bit out of AA workflow to fix that. At least we can be sure that new users won't struggle. And old one probably used to do that :)

**Comment by deivid-rodriguez** [comment]
Maybe adding this information somewhere in the wiki?

**Comment by varyonic** [comment]
Contributions to [Upgrading-ActiveAdmin](https://github.com/activeadmin/activeadmin/wiki/Upgrading-ActiveAdmin) welcome.

**Comment by deivid-rodriguez** [comment]
Closing this since we seem to agree there's nothing to do on our side. Feel free to update the upgrade docs in the wiki! :wink:
