### ISSUE TITLE
undefined method `page_action' for #<ActiveAdmin::ResourceDSL:0x007fdbec8e1028>

### ISSUE THREAD

**Issue by Corstiaan84** [activeadmin/activeadmin#4742]
When I define a page_action like so:

```
page_action :add_event, method: :post do
# stuff...
end
```

I get the following error:

undefined method `page_action' for #<ActiveAdmin::ResourceDSL:0x007fdbec8e1028>

I am pulling activeadmin from github in my gemfile like so: `gem 'activeadmin', github: 'activeadmin'`

Any ideas? :-)

**Comment by Fivell** [comment]
@Corstiaan84 , you're trying to call page_action on resource DSL ,should be called on page DSL check how this feature work

https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/features/registering_pages.feature#L113

**Comment by Corstiaan84** [comment]
Obviously :-). Thank you!
