### ISSUE TITLE
Union of multiple filters

### ISSUE THREAD

**Issue by ldthorne** [activeadmin/activeadmin#4743]
Hi all,

I'm trying to create a new filter on AA to accomplish the following: a city has many properties; a property has many rooms. I'd like to create a filter on the rooms page where a user is able to filter the results by rooms in one or more cities. For example, if we have the cities of Chicago, Miami, and Montreal, I'd like the user to be able to filter for rooms in one city, both cities, or all three cities (so the union of the rooms in whichever cities they select). My question is whether or not this is possible with Active Admin and, if so, how to approach it.

Thanks!

**Comment by Fivell** [comment]
@ldthorne , sounds like you're asking about filter by multiple cities for your room resource? 
Is that right? If yes

```ruby
class Room < ActiveRecord::Base
   belongs_to :city
end
```

```ruby

ActiveAdmin.register Room do
filter :city, as: :select, multiple: true
end

```

**Comment by ldthorne** [comment]
Perfect. Thank you!
