### ISSUE TITLE
Search filter lost after batch action

### ISSUE THREAD

**Issue by abrambailey** [activeadmin/activeadmin#4746]
The photo below shows me about to delete a bunch of fake users who registered from @163.com emails:

![image](https://cloud.githubusercontent.com/assets/978462/22179968/285073ce-e0c7-11e6-96fd-f479651ec579.png)

Unfortunately page 2 of those search results did not appear upon deleting all of page 1. Instead I see the default /users with no search filtering:

![image](https://cloud.githubusercontent.com/assets/978462/22179969/446853c4-e0c7-11e6-8c40-63b707d32ce1.png)

This caused a major headache for me after I deleted 30 users assuming it was page 2 of the @163.com users.

**Comment by abrambailey** [comment]
Basically the search params are lost and I am directed from `/users?utf8=✓&q%5Bemail_contains%5D=163.com&commit=Filter&order=id_desc`  to `\users` after hitting delete all.

**Comment by Fivell** [comment]
duplication of #3833

**Comment by varyonic** [comment]
Sorry Abram, closing this as a dup.  Thanks for taking the time to remind us of this gotcha.

**Comment by abrambailey** [comment]
No worries thanks.
