### ISSUE TITLE
Filter search status buggy + turn off current_filters on a per-model basis

### ISSUE THREAD

**Issue by davidwparker** [activeadmin/activeadmin#4757]
### Filter search status

I have filters listed out for a page:

```
filter :id
filter :user_id, label: "User ID"
filter :user_username, as: :string
```

But when they're currently in use (ID equals n), and the filters work ok:
<img width="286" alt="screen shot 2017-01-25 at 8 34 46 am" src="https://cloud.githubusercontent.com/assets/2379/22296991/283e08ec-e2d9-11e6-87c5-6de2d6d63962.png">

But then in the "Search Status" box, it shows up with nothing:

<img width="286" alt="screen shot 2017-01-25 at 8 34 01 am" src="https://cloud.githubusercontent.com/assets/2379/22296954/0df0a3d2-e2d9-11e6-9c65-e7d6e2bf4492.png">

### Turning off current filters

Per advice here (https://github.com/activeadmin/activeadmin/issues/2122) I see how to turn off filters:

/config/initializers/active_admin.rb
```
   config.current_filters = false #or true
```

I tried following additional advice there and move that to a registered page and it doesn't work on a per-page basis and was informed to create an issue for it.

Doesn't work:
```
ActiveAdmin.register MyModule::MyThing, as: "MyThing" do
   config.current_filters = false #or true
end
```

Thanks and keep up the great work!

**Comment by Fivell** [comment]
thanks @davidwparker , I'll take a look

**Comment by Fivell** [comment]
https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/filters/resource_extension.rb#L166

this line is buggy
```ruby
if: -> { params[:q] || params[:scope] } 
```

    should be changed to 

```ruby
if: -> { active_admin_config.current_filters_enabled?  && (params[:q] || params[:scope]) } 
```

**Comment by Fivell** [comment]
@davidwparker , first part of issue should be solved via #4748, pls check

**Comment by davidwparker** [comment]
@Fivell - thanks! Is there an easy way for me to test and pull this down via my Gemfile?

Will this work?
`gem 'activeadmin', '~> 1.0.0.pre1'` --> `gem 'activeadmin', 'github: https://github.com/activeadmin/`

Also, until it's up on RubyGems, I won't be able to pull it into production, as we don't have external access outside of RubyGems for the environment.

Thanks for the great quick work!

**Comment by Fivell** [comment]
@deivid-rodriguez 

`gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin'`

**Comment by davidwparker** [comment]
Works great, thanks! Once it's on Rubygems, I'll upgrade, cheers!
