### ISSUE TITLE
Allow customizing Footer via partial

### ISSUE THREAD

**Issue by blimmer** [activeadmin/activeadmin#4758]
https://github.com/activeadmin/activeadmin/pull/4641#issuecomment-275053467

**Comment by dmitry** [comment]
Who are going to implement it? I think it's better was to merge #4641 and then work on more advanced support.

**Comment by Fivell** [comment]
@dmitry, you're welcome to create new PR with improvements :1st_place_medal:

**Comment by dmitry** [comment]
@Fivell done. #4641  :)
