### ISSUE TITLE
"Unable to find input class DaterangeInput" when using Postgres daterange fields

### ISSUE THREAD

**Issue by aguynamedben** [activeadmin/activeadmin#4761]
Thanks for the time you spend working on this awesome library. It's going to be very valuable in my project. I think I've identified a fairly simple bug with class name capitalization.

From my schema.rb

```rb
  create_table "trips", force: :cascade do |t|
    t.integer   "user_id"
    t.string    "name"
    t.string    "slug"
    t.string    "location"
    t.datetime  "created_at", null: false
    t.datetime  "updated_at", null: false
    t.daterange "duration"
    t.index ["slug"], name: "index_trips_on_slug", unique: true, using: :btree
    t.index ["user_id"], name: "index_trips_on_user_id", using: :btree
  end
```

Then I go to localhost:3000/admin/trips/new to create a new Trip in activeadmin. I get this error:
```
Unable to find input class DaterangeInput
```

Screenshot:
<img width="1011" alt="action_controller__exception_caught" src="https://cloud.githubusercontent.com/assets/107841/22322740/f8d266be-e352-11e6-9379-ad06f8d37b34.png">

Trace:
<img width="762" alt="action_controller__exception_caught" src="https://cloud.githubusercontent.com/assets/107841/22322748/0134bc12-e353-11e6-87ca-3089d75fac4e.png">

I see in the activeadmin code there is a class named `DateRangeInput` (note the capitalization), but when the code runs it's looking for `Daterangeinput` (note the capitalization differs from the correct class name).

From my Gemfile.lock

```
GIT
  remote: https://github.com/activeadmin/activeadmin.git
  revision: ca723e38bc7285f3fc155e3e909f7477f30e28fb
  specs:
    activeadmin (1.0.0.pre4)
      arbre (~> 1.0, >= 1.0.2)
      bourbon
      coffee-rails
      formtastic (~> 3.1)
      formtastic_i18n
      inherited_resources (~> 1.6)
      jquery-rails
      jquery-ui-rails
      kaminari (>= 0.15, < 2.0)
      railties (>= 3.2, < 5.1)
      ransack (~> 1.3)
      sass-rails
      sprockets (< 4.1)

...

    formtastic (3.1.4)
      actionpack (>= 3.2.13)
    formtastic_i18n (0.6.0)
```

**Comment by Fivell** [comment]
there are few range types in postgreSQL 
https://www.postgresql.org/docs/9.3/static/rangetypes.html I think no one from the ranges types are supported. 

@aguynamedben , thanks for reporting this. 
I also think this issue should be reported to formtastic as well.

**Comment by timoschilling** [comment]
Formtastic tries to infer a input type by the field value type, for your type `Daterange` no input exists. Is is no ActiveAdmin issue and no Formtastic one. You need to implement a `DaterangeInput` or set an explicit input type for that field.
