### ISSUE TITLE
permit_params - Unpermitted parameter of related model

### ISSUE THREAD

**Issue by mdaymond** [activeadmin/activeadmin#4765]
I have a Orders model and OrdersProducts model.   Multiple orders can be held inside OrdersProducts.  In my OrdersProducts I have the following:
```
belongs_to :order
permit_params :order,
              :order_id,
              :product_id,
              :item_id,
              :user_id,
              :order_type,
              :product_label
              #order_ids:[]
```

When I attempt to update or create I get the following issue:  
**Unpermitted parameter: order_id**

Looking at the logs everything looks find with the request, but the transaction is being rolled back because the param is not allowed.

**Log** 
```
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"ZS46Src+SHV9ufiZ5nEqiBnyIEq2DMS3CQL/f3rbqjNDJFAukuJ1bDOgW//0WwOJap2UR6bzw2nsvFCVCTCkqA==", "orders_products"=>{"product_label"=>"sdafasd", "order_type"=>"purchase", "product_id"=>"18", "item_id"=>"", "order_id"=>"42"}, "commit"=>"Create Orders products", "order_id"=>"42"}
```

**Comment by dmitry** [comment]
You have `"order_id"=>"42"}` in the end of params.

**Comment by Fivell** [comment]
refs #3556

**Comment by Fivell** [comment]
@timoschilling , I think #3556 should be reopened and this one should be closed as duplicate.
