### ISSUE TITLE
Disable comments

### ISSUE THREAD

**Issue by merqlove** [activeadmin/activeadmin#4767]
Can't disable comments from config.
It is lost or deprecated setting?

```
config/initializers/active_admin.rb:122:in `block in <top (required)>': undefined method `comments=' for #<ActiveAdmin::Application:0x007fb1d71d3658> (NoMethodError)
	from gems/2.3.0/bundler/gems/activeadmin-0f7b70036354/lib/active_admin.rb:72:in `setup'
```

**Comment by timoschilling** [comment]
renamed to `allow_comments`

**Comment by merqlove** [comment]
@timoschilling  gems/activeadmin-0f7b70036354/lib/active_admin/application.rb:140:in `allow_comments=': `config.allow_comments` is no longer provided in ActiveAdmin 1.x. Use `config.comments` instead. (RuntimeError)

**Comment by timoschilling** [comment]
oh sorry `config.comments` is it now
