### ISSUE TITLE
Circular bundle dependencies when installing, refuses to install

### ISSUE THREAD

**Issue by deemytch** [activeadmin/activeadmin#4777]
Added activeadmin and meta_search in the existing project, as in docs
**№1**
<pre>gem 'activeadmin'
gem "meta_search", '>= 1.1.0.pre'</pre>
then
**№2**
<pre>$ bundle
Fetching gem metadata from https://rails-assets.org/...
Fetching version metadata from https://rails-assets.org/..
Fetching gem metadata from https://rails-assets.org/...
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rails-assets.org/..
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rails-assets.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies....
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove gem 'meta_search' and try again.
</pre>
**№3**
then removed gem meta_search from Gemfile, checked twice
loop to №2

**software**
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
rails 4.2.7.1
Bundler version 1.13.7
[gemfile.zip](https://github.com/activeadmin/activeadmin/files/750487/gemfile.zip)

**Comment by deivid-rodriguez** [comment]
Hei! You're specifying wrong dependencies.

`metasearch` was replaced a while ago with `ransack` and the latest release of `activeadmin` does not support `Rails 4.2` which you are using. Please refer to the README for installation instructions.

**Comment by varyonic** [comment]
Use pre4 or master and [installation doc](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md), not http://activeadmin.info/

**Comment by deemytch** [comment]
Сахар в банке из-под соли с надписью "перец".
Who can correct the docs?

**Comment by Fivell** [comment]
@deemytch activeadmin in your Gemfile,  can't be used with rails 4.2.
for rails 4.2 use master branch and readme here https://github.com/activeadmin/activeadmin/blob/master/docs/README.md

**Comment by deemytch** [comment]
Thank you, I got that.
I just mentioned, that the site need updates.
Or maybe, on the top of README with very big letters.
