### ISSUE TITLE
config.max_per_page has no effect?

### ISSUE THREAD

**Issue by rdlugosz** [activeadmin/activeadmin#4778]
I'm trying to limit the number of records returned in a CSV export (to avoid Heroku Timeouts), but setting `config.max_per_page = 1_000` in my initializer seems to have no effect on the output. I've also tried a few of the older methods mentioned here and elsewhere for controlling the number of results & none of those worked either... Am I missing something obvious?

**Comment by varyonic** [comment]
I think max_per_page applies only to pagination, which is skipped by CSVBuilder#build.  Try subclassing CSVBuilder to get the desired behavior.

**Comment by Fivell** [comment]
@varyonic , looks like we should split ```CSVBuilder#build``` to several methods to make it easier to override.

**Comment by varyonic** [comment]
Maybe, but for myself I always send larger exports to a background job and I think that is out of scope for AA.
