### ISSUE TITLE
Publish frontend javascript/css onto npm.

### ISSUE THREAD

**Issue by mistlight** [activeadmin/activeadmin#4779]
For those of us that don't rely on asset pipeline but uses npm to manage frontend dependencies, this would be a huge help.

**Comment by timoschilling** [comment]
No, that isn't an option for now. Maybe later if we only support Rails >=5

**Comment by varyonic** [comment]
FWIW we use ActiveAdmin with React on Rails to integrate webpack and asset pipeline without any issues.

**Comment by rhymes** [comment]
@varyonic can you explain how? using a separate entry for AA ?

**Comment by varyonic** [comment]
Nothing special.  Javascript from gems continues to get served alongside npm packages.

**Comment by rhymes** [comment]
@varyonic ah ok, you just let it be as it is. I thought you found a way to put them in webpack. Thanks!

**Comment by cdebruyn** [comment]
@varyonic I also use React_on_rails with webpacker. We installed active admin alongside. It seems the css of active admin is affecting the our other css. I'd like to remove active admin as I don't need it anymore. Tried to do that but the styling is still being affective.

**Comment by cdebruyn** [comment]
The auto generated styling seems to be coming from public/assets

**Comment by senid231** [comment]
I think now we can reopen it again
Now, when we only support Rails 5+
