### ISSUE TITLE
How to check cancan permission on ActiveAdmin custom page?

### ISSUE THREAD

**Issue by mabdelfattah** [activeadmin/activeadmin#4783]
I've the following Ability:

`can :manage, ActiveAdmin::Page, name: 'My Page'`

And it is working fine, but I want to check if the user has the ability to manage this ActiveAdmin::Page in different pages. So, when I used the following:

`can? :manage, ActiveAdmin::Page, name: 'My Page'`

It returns true for any page even if it does not exist!

I asked on StackOverFlow
https://stackoverflow.com/questions/41850126/how-to-check-cancan-permission-on-activeadmin-custom-page

And the question turned to: what is the right syntax to access ActiveAdmin page instance?

**Comment by timoschilling** [comment]
please read this:
https://github.com/activeadmin/activeadmin/blob/master/docs/13-authorization-adapter.md#using-the-cancan-adapter

**Comment by mabdelfattah** [comment]
I read it and using it, but my question is how to access ActiveAdmin::Page instance to check if the user has access to this page or not!

**Comment by mabdelfattah** [comment]
@timoschilling Sorry man, but this is not mentioned anywhere in the documentation.

**Comment by mabdelfattah** [comment]
I figured out a way but not sure if it is the right one or not

`can? :manage, (ActiveAdmin::register_page 'My Page')`

**Comment by lokiirss** [comment]
I used
 can? :manage, (ActiveAdmin::register_page 'My Page') 
but looks like my menu bar is now extending the menu dropdowns to individual menu links! 
Adding the above line is causing it. Any other way to enable activeadmin custom page to have access to all the database objects regardless of which user has logged in. Because my custom page is for viewing some data.

**Comment by texpert** [comment]
I found an ugly way :)

For a page, defined like `ActiveAdmin.register_page 'User Changes'`, have to search for its instance in the ActiveAdmin::Namespace::Store:

```
    page = ActiveAdmin.application.namespaces.each do |n|
      page = n.resources['User Changes']
      break page if page.present?
    end

    do_smth if can?(:read, page)
```

Would be good to have something like this as a method of ActiveAdmin::Namespace::Store.

**Comment by pamit** [comment]
I just wanted to share what I did for my case:

```
# ability.rb

can(:manage, ActiveAdmin::Page, name: 'Page Title')
```

```
# ActiveAdmin page

action_item :specific_page, only: :show, if: proc { authorized?(:manage, controller.instance_variable_get(:@specific_page)) } do
  link_to 'Page Title', "/admin/..."
end
...  
controller do
  def show
    @specific_page = ActiveAdmin.application.namespaces[:admin].resources.select { |resource| resource.resource_label == 'Page Title' }.first
  end
end
```
