### ISSUE TITLE
Turbolinks is or isn't supported?

### ISSUE THREAD

**Issue by sxjoel** [activeadmin/activeadmin#4788]
Hello,
I've read in an a closed issue that activeadmin does not support turbolinks. 
However in my app I've set up turbolinks and everything seems to work fine. 
Am I missing something (perhaps some ui is broken without me finding it out yet?)
Can I please know what is the current state of turbolinks and activeadmin?

The only issue I've seen so far is this:  I've had to override activeadmin_base jquery's includes because for turbolinks to work the scripts order is important (so basically, currently i'm including jquery twice) 

     #= require active_admin/base
     #= require jquery
     #= require jquery.turbolinks
     #= require jquery_ujs
     #= require jquery-ui
     #= require tag-it
     #= require chartkick
     #= require turbolinks

**Comment by varyonic** [comment]
Which closed issue?  It works, but the current maintainers are not familiar with it so we rely on community feedback and fixes, eg. #4517, #4448.

**Comment by sxjoel** [comment]
Thanks @varyonic  .  This closed issue https://github.com/activeadmin/activeadmin/issues/4349 was talking about it being not supported. Glad to see it is (?)
