### ISSUE TITLE
Error with using multiple http methods with page_action

### ISSUE THREAD

**Issue by mabdelfattah** [activeadmin/activeadmin#4795]
I'm trying the following syntax:
```
  page_action :preview, method: [:get, :post] do
    @page_title = 'Preview and Compare Zones'
    render 'preview', layout: 'active_admin'
  end
```

And getting the following error:
```/usr/local/lib/ruby/gems/2.4.0/gems/actionpack-5.0.1/lib/action_dispatch/routing/mapper.rb:328:in `check_part': Missing :controller key on routes definition, please check your routes. (ArgumentError)```

**Comment by timoschilling** [comment]
Multiple methods are not supported at the moment.

**Comment by Fivell** [comment]
@timoschilling , https://github.com/activeadmin/activeadmin/commit/e5b74430734962b772c3e6e1f10b1fe9484f84ec

**Comment by Fivell** [comment]
or it doesn't related to page actions ?

**Comment by timoschilling** [comment]
@Fivell ok, never mind

**Comment by Fivell** [comment]
@timoschilling , you were  right it is not supported, I will fix it later and add specs for both member actions and page actions
