### ISSUE TITLE
Customize Comments

### ISSUE THREAD

**Issue by jwcarman** [activeadmin/activeadmin#4796]
Is there a way to add/remove columns from the ActiveAdmin Comments listing?  I suppose we'd have to modify the actual underlying resource in order to add new stuff.  How tough would it be to turn off a couple of columns in the table?

**Comment by Fivell** [comment]
@jwcarman , can you please explain what exactly you need ? 
Do you want to add new columns to  comments component?

**Comment by jwcarman** [comment]
I need to be able to remove and add new columns to the table.  Removing is probably easier.  How tough would it be to add new fields (editable) to the comments also?

**Comment by Fivell** [comment]
@jwcarman,  take a look at current implementation https://github.com/activeadmin/activeadmin/tree/master/lib/active_admin/orm/active_record

**Comment by Fivell** [comment]
@jwcarman , you can create your own custom comments components like in example above

**Comment by Fivell** [comment]
@timoschilling , I think it should be closed , it is not bug request neither well-described feature request.

**Comment by jwcarman** [comment]
If it's already supported, let's definitely close it.  If you need more info, I can provide it.  I'm not terribly familiar with Rails, so I may just not know how to effectively express what I'm asking in the right terms.  I have a request from my customer to add extra fields to the comments.  They want to use them for a workflow-like system, where they would use these extra fields to help track progress.  I could add a whole new entity type I suppose, but was wondering if we could augment the comments since they were already using them.

**Comment by Fivell** [comment]
@jwcarman , don't think it will be implemented , comments are just comments and nothing more, your case is very specific. 
There are 2 options
1) develop own comments-like extension.
2) path active admin sources

If you not familiar with rails both options will be quite difficult of course.

But at least you can try,  I believe   google groups and stackoverflow is good start for getting community help, btw there already were similar discussion   https://groups.google.com/forum/#!topic/activeadmin/jFGjyTKcKz0

**Comment by jwcarman** [comment]
That's what I figured, but it couldn't hurt to ask.  Thanks for the pointers.  I'll probably just add a new entity and use a one-to-many relationship or something.
