### ISSUE TITLE
Delete everything but still find the error on active admin

### ISSUE THREAD

**Issue by NiteshKaradwall** [activeadmin/activeadmin#4798]
I was using active admin but mistakenly integrated in wrong repo. When I found it and I removed everything about active admin from that repo but still find issue related to active admin. Don't understand how my application find that admin namespace part on server.

Error :- 
Circular dependency detected while autoloading constant User
app/admin/user.rb:1<top (required)>
RuntimeError·Circular dependency detected while autoloading constant User

Thanks in advance !!

**Comment by Fivell** [comment]
@NiteshKaradwall , revert your commits instead of removing everything by hand

**Comment by sachin-kumar-rathore** [comment]
@Fivell  :-  I already did that on my production server. just run "rails destroy active_admin:resource" which remove everything about models, removed js and css manually. 

Now I can't revert the commit of that. What should I do with this.

**Comment by NiteshKaradwall** [comment]
@Fivell :- I already did that on my production server. just run "rails destroy active_admin:resource" which remove everything about models, removed js and css manually.

Now I can't revert the commit of that. What should I do with this.
