### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by sakshi7896** [activeadmin/activeadmin#4799]
Hello all
I am new to the project and is interested in contributing to it. 
Some of the features I can think of : 
1. Loading data in chunks. Instead of loading the entire database at once wjich takes more time, we can load it in chunks to reduce time.
2. Archiving feature: We can reduce the size of the database by converting very old files in csv and auto downloading and finally deleting them from data base. In this way we can make the databse light.
3. Zoom in/out feature: We can add the zoom in/out feature of the products to let the user analysie the product in a a better way. 

I would like to have some suggestions from the project maintainers and contributors to know if this is at all feasible. 
( Or any other feature/bug on which I can work upon as I am new to it but the project is ineteresting)
Thanks

**Comment by timoschilling** [comment]
1. What are you talking about. Where do we load the entire database?
2. That is out of scope of this gem

**Comment by timoschilling** [comment]
If you want to fix bugs or implement features, take a look on the issue tracker.

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
