### ISSUE TITLE
How to configure string filter to default search with starts_with

### ISSUE THREAD

**Issue by lauraeci** [activeadmin/activeadmin#4800]
I would like to know how to configure active admin filters to use starts_with as the default string filter.

Thank you,
-Laura

**Comment by Fivell** [comment]
@lauraeci , try this
```ruby
filter :name, as: :string, filters: [:starts_with, :equals, :contains, :ends_with]
```

**Comment by lauraeci** [comment]
Thanks, @Fivell is there a way to configure this as the default order for all filters or per namespace?
Like
```
ActiveAdmin.setup do |config|
    config.filters = [:starts_with, :equals, :contains, :ends_with]
end
```

**Comment by Fivell** [comment]
@lauraeci , there is no such config at the moment, string filters positions are hardcoded.  You can patch default behaviour globally using ruby 

Such rails initialiser might work for you.
 
```ruby
module MyStringInputExt
  def self.included(base)
    base.class_eval do
      @filters = [:starts_with, :equals, :contains, :ends_with]
    end
  end
end 
ActiveAdmin::Inputs::Filters::StringInput.send(:include, MyStringInputExt)
```

**Comment by lauraeci** [comment]
Thanks, @Fivell

**Comment by Fivell** [comment]
@lauraeci , there is shorter way.
```ruby
ActiveAdmin::Inputs::Filters::StringInput.filters.clear
ActiveAdmin::Inputs::Filters::StringInput.filter(:starts_with, :equals, :contains, :ends_with)
```

**Comment by JagadeshRaj05** [comment]
Thanks @Fivell. But when I use the solution in rails v3.2.22.2 and active-admin v0.6.6, below error is coming. Kindly help with this one.

**uninitialized constant ActiveAdmin::Inputs::Filters (NameError)**

**Comment by JagadeshRaj05** [comment]
After deep digging, I got the answer.

**For active-admin v0.6.6, it should be** 
``` ruby
ActiveAdmin::Inputs::FilterStringInput.filters.clear
ActiveAdmin::Inputs::FilterStringInput.filter(:equals, :starts_with, :ends_with, :contains)
```
**Replacing Filters::StringInput to FilterStringInput will work**

**Comment by i7an** [comment]
Probably [the filter names](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/filters/string_input.rb#L9) were changed at some point. The option that works for me is:
```ruby
filter :name, filters: %i[eq cont start end]
```
