### ISSUE TITLE
Bourbon assign-inputs deprecation warnings in rails 5

### ISSUE THREAD

**Issue by ankitrg** [activeadmin/activeadmin#4801]
WARNING: [Bourbon] [Deprecation] `assign-inputs` is deprecated and will be removed in 5.0.0

I am getting this warning, is it ok to have them?

**Comment by varyonic** [comment]
Related to discussion in #4791?

**Comment by deivid-rodriguez** [comment]
I grepped activeadmin for `assign-inputs`, so I assume this is not caused by this gem.

@ankitrg Feel free to reopen with reproduction steps or an explanation if you disagree!
