### ISSUE TITLE
Override default action for Pundit

### ISSUE THREAD

**Issue by bennyzr** [activeadmin/activeadmin#4812]
I would like to use a custom policy method for the index action of a resource. I am currently using the index policy for a non-admin page for the resource and would like to be able to have Active Admin authorize against a custom policy action. e.g. 

```
def admin_index
  is_admin?
end
```
I already tried using `authorize @resource, :admin_index?` in the index method which did not help.

**Comment by Fivell** [comment]
@bennyzr, I suggest you to inherit from pundit adapter and to use own one.
documentation is [here](https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/docs/13-authorization-adapter.md
)


You can override ```format_action``` to make it work

something like may work
```ruby
class ActiveAdminPunditAdapter < ActiveAdmin::PunditAdapter
   def format_action(action, subject)
       #here we go adding "admin_" prefix to all stuff from default pundit adapter
        ["admin", super(action,subject)].join("_")
   end
end
```

take a look at original [implementation](https://github.com/activeadmin/activeadmin/blob/380ead0e730ac7533800a7577cba761336ef368a/lib/active_admin/pundit_adapter.rb#L45)
