### ISSUE TITLE
Record update should be wrapped in a transaction for a consistent modification

### ISSUE THREAD

**Issue by dmitry** [activeadmin/activeadmin#4815]
At the moment if a persisted record has collection with `_ids` and failed validation, modified `_ids` will be updated anyway. It's kind of a feature-bug, but in practice `assign_attributes` must be wrapped in a `transaction` or should be used `update_attributes` to prevent updating `_ids` in case if validation of the parent or children models returned false.

Following change should solve such issue:

```ruby
      def update_resource(object, attributes)
        object.with_transaction_returning_status do
          object = assign_attributes(object, attributes)

          run_update_callbacks object do
            save_resource(object)
          end
        end
      end
```

similary `update_attributes` has the following code:

```ruby
    def update(attributes)
      # The following transaction covers any possible database side-effects of the
      # attributes assignment. For example, setting the IDs of a child collection.
      with_transaction_returning_status do
        assign_attributes(attributes)
        save
      end
    end
```

**Comment by varyonic** [comment]
PR welcome.  Do you have any links to StackOverflow or Rails issues?

**Comment by Fivell** [comment]
https://github.com/rails/rails/issues/26656

**Comment by dmitry** [comment]
@varyonic no, I've found it while digging in my application code.

PS. Does anyone know why collection setter `collection_ids` writes data at the same time when data passed, instead of writing to a database only after `save` is invoked? Is it designed like that, if yes - why? It works like that only if record persisted in the database, when it's a new record it just saves with all the validations and callbacks after the `save`.

**Comment by Fivell** [comment]
@dmitry ,  from docs

```
4.3.1.7 collection_singular_ids=(ids)

The collection_singular_ids= method makes the collection contain only the objects identified by the supplied primary key values, by adding and deleting as appropriate.
```

nothing about it is called in save callback

**Comment by dmitry** [comment]
@Fivell here is more detailed overview of the `collection_singular_ids` issues I found: https://groups.google.com/forum/#!topic/rubyonrails-core/FlPLRCBC2ns

**Comment by Fivell** [comment]
closing this because it is related to ActiveAdmin very weakly.

**Comment by dmitry** [comment]
At the moment it's related to the AA, because `assign_attributes` in AR work incorrectly for _collection ids_ and AA uses _save_ logic without any transaction block.

**Comment by Fivell** [comment]
@dmitry, yes it has no transaction block like any other action in AA and even in Rails, to wrap action in transaction you should do this yourself.
For instance

```ruby
controller do
  around_action :wrap_in_transaction
  def wrap_in_transaction
    ActiveRecord::Base.transaction do
      yield
    end
  end
end
```

**Comment by dmitry** [comment]
So AA by default is not transaction safe (partially) in case if you would like to change associations?
I think AA should have transaction safety by default, it's an admin panel with DSL, isn't it should have all the best practice features out of the box?

**Comment by timoschilling** [comment]
I agree with @Fivell, this is currently not the domain of AA, it should be placed in the domain of inherited_resources

**Comment by Fivell** [comment]
@timoschilling , not sure it can be placed to inherited resources as well, collection_singular_ids=(ids) is not an active-record attribute or setter , it works like described in docs (as expected)
 ```
The collection_singular_ids= method makes the collection contain only the objects identified by the supplied primary key values, by adding and deleting as appropriate. The changes are persisted to the database.
```


I think It is not  good  way to allow call this method from customers input.

Anyway will see what guys from  rails will answer

**Comment by mherold** [comment]
Sorry to post in a closed Issue, but I'm not really getting what the status is... will it be addressed?

I just had a similar problem as initially described by @dmitry, which resulted in inconsistent data. 

I think it's safe to say that using `_ids` in params for associating other models is a fairly common use case. Because of that, and since the rails/AR `update` method handles this cleanly out-of-the-box, I feel it's pretty counterintuitive that one would be required to manually add a transaction for this in AA. 

Did I miss anything? Can I help?

**Comment by joker-777** [comment]
I agree this issue still exists and it seems that [Rails doesn't want to do anything to improve this either](https://github.com/rails/rails/issues/29420) :(

**Comment by joker-777** [comment]
For now I fixed it by adding this to my active admin page

```rb
controller do
  def update(options={}, &block)
    resource.update(*resource_params)
    options[:location] ||= smart_resource_url
    respond_with_dual_blocks(resource, options, &block)
  end 
end
```
