### ISSUE TITLE
code formatting in resources doc

### ISSUE THREAD

**Issue by ryanhertz** [activeadmin/activeadmin#4817]
The code block needs to be closed in docs/2-resource-customization.md

![image](https://cloud.githubusercontent.com/assets/2022057/23213760/29943a60-f8da-11e6-8603-daf3c59448dc.png)

**Comment by deivid-rodriguez** [comment]
Could you add a PR for this?

**Comment by ryanhertz** [comment]
Certainly - https://github.com/activeadmin/activeadmin/pull/4818

**Comment by Fivell** [comment]
closed by #4818
