### ISSUE TITLE
Menu reloading

### ISSUE THREAD

**Issue by theo-bittencourt** [activeadmin/activeadmin#4820]
Hi guys!

We've a music festival admin that works like a hub for different cities.

For example, `.com/usa/en/admin/` should present the admin for USA festival edition. And `.com/madrid/es/admin` should present the admin for Spain edition.

The pattern is `.com/city/locale/admin`.

The resources (models and pages) should be scoped by the city.

We need to reload menu so items hrefs could be updated.
So, when admin user switch from `/usa` to `/madrid`, all menu links will be updated to point to new `/madrid`.

**Comment by timoschilling** [comment]
This isn't an issue, ask on stackoverflow

**Comment by theo-bittencourt** [comment]
Thanks @timoschilling. I'll do.
