### ISSUE TITLE
Please! Restore activeadmin.info old documentation structure

### ISSUE THREAD

**Issue by novill** [activeadmin/activeadmin#4821]
![image](https://cloud.githubusercontent.com/assets/1174697/23251677/a1736428-f9c7-11e6-8214-e8126a3243bb.png)

**Comment by novill** [comment]
![image](https://cloud.githubusercontent.com/assets/1174697/23251659/92d35860-f9c7-11e6-827e-f692b1ab1078.png)

**Comment by Fivell** [comment]
@novill , this http://activeadmin.info/5-forms.html

**Comment by novill** [comment]
1. You've lost thousands external links to your site
2. It's very uncomfortable to fix url each time you read some article with link to site
![image](https://cloud.githubusercontent.com/assets/1174697/23251967/8ba6729c-f9c8-11e6-8ec1-84a64e7ad610.png)

**Comment by novill** [comment]
Maybe you can use redirect

**Comment by deivid-rodriguez** [comment]
Agreed. We should redirect old URLs to new ones using 301's, if possible.

**Comment by varyonic** [comment]
See https://superdevresources.com/redirects-jekyll-github-pages/

**Comment by novill** [comment]
Thank you very much!
