### ISSUE TITLE
has_one association form has "Remove" button that cannot be removed

### ISSUE THREAD

**Issue by Ru-T** [activeadmin/activeadmin#4830]
The form controller is: 

```ruby
  controller do
    def new
      @object = Object.new
      @object.build_address
    end
  end
```

and the form is: 

```ruby
  form do |f|
    f.inputs "Object" do
      f.input :name
      f.has_many :address, new_record: false do |t|
        t.input :line1
        t.input :line2
        t.input :city
        t.input :state
        t.input :zip
      end
    end
    f.actions
  end
```

This creates a form with an Object with one address, but the address is followed by a "Remove" button. When the address is removed, the object can no longer be created because address is required. 

There is no discernible way to remove the "Remove" button from the form without some hacky jquery.

**Comment by varyonic** [comment]
Looks like you would have to override ActiveAdmin::FormBuilder#has_many_actions.  Pull request welcome.

**Comment by Fivell** [comment]
@Ru-T , did you try 
```ruby
 f.has_many :address, new_record: false, allow_destroy: false
```
?

**Comment by deivid-rodriguez** [comment]
Tentatively closing since the suggestion seems fine and the OP has not given any feedback.

**Comment by Fivell** [comment]
@deivid-rodriguez , after  re-read  I think @Ru-T  means that possibility needed in UI to not remove last  address

**Comment by deivid-rodriguez** [comment]
Mmmm, isn't that what `destroy: false` does?

**Comment by Fivell** [comment]
@deivid-rodriguez , I think ```destroy: false``` does it only for persisted records, in current example address is not persisted

**Comment by deivid-rodriguez** [comment]
I didn't know that. I would've expected it to behave in the same way.

**Comment by Fivell** [comment]
@deivid-rodriguez , I'm not sure too, need to be checked

**Comment by Fivell** [comment]
@Ru-T , please provide more information about your problem.

**Comment by Fivell** [comment]
@deivid-rodriguez , let's keep it closed anyway
