### ISSUE TITLE
ActiveAdmin v 0.6.6 and v 1.0.0.pre4 doesn't depend on the latest version of Kaminari (v 1.0.1).

### ISSUE THREAD

**Issue by DevotionGeo** [activeadmin/activeadmin#4840]
Bundler gives the following error:

Bundler could not find compatible versions for gem "kaminari":
  In Gemfile:
    kaminari (>= 1.0.1, ~> 1.0)

    activeadmin (~> 1.0.0.pre4) was resolved to 1.0.0.pre4, which depends on
      kaminari (~> 0.15)

**Comment by deivid-rodriguez** [comment]
We just released 1.0.0.pre5, it should be fixed there. Could you try?

**Comment by DevotionGeo** [comment]
Thank You, it worked!

**Comment by deivid-rodriguez** [comment]
Great! Happy it's working now! :)
