### ISSUE TITLE
Broken utility menu when no namespace?

### ISSUE THREAD

**Issue by TheFlow0360** [activeadmin/activeadmin#4843]
I'm currently creating a prototype using [active_skin](https://github.com/rstgroup/active_skin) and noticed something weird: When accessing the root of the site which is  Active Admin without namespace, the utility menu at the top right doesn't look right and also the user is not a link to the user show page:
![normal](https://cloud.githubusercontent.com/assets/7249679/23697840/a0ce0f7e-03e9-11e7-99ff-f6982e30bb2d.png)

When navigating into the admin area, which is namespaced as `:admin`, it looks fine and also the link to the user page is available:
![admin](https://cloud.githubusercontent.com/assets/7249679/23697882/c3b9f41c-03e9-11e7-8cc3-907bf23877ba.png)

I didn't modify the `utility_navigation` in the initializer, and my pages are mostly empty. Why is the utility menu working if namespaced and otherwise broken? I could just rebuild the utility navigation but to me, this doesn't seem like the best solution.

**Comment by Fivell** [comment]
@TheFlow0360 , please attach raw html of generated utility_navigation with namespace and without

**Comment by TheFlow0360** [comment]
The `<div class="header" id="header">` for the non-namespaced area:
    
    <h1 class="site_title" id="site_title">PrototypeWebPlatform</h1>
    <ul class="header-item tabs" id="tabs">
      <li class="current" id="dashboard"><a href="/dashboard">Dashboard</a></li>
      <li id="admin_area"><a href="/admin/dashboard">Admin Area</a></li>
    </ul>
    <ul class="header-item tabs" id="utility_nav">
      <li id="current_user">
        <span>Admin</span>
      </li>
      <li id="logout"><a rel="nofollow" data-method="delete" href="/users/sign_out">Logout</a></li>
    </ul>

and for the `:admin`-namespaced area:

    <h1 class="site_title" id="site_title">Admin Area</h1>
    <ul class="header-item tabs" id="tabs">
      <li class="current" id="dashboard"><a href="/admin/dashboard">Dashboard</a></li>
      <li id="users"><a href="/admin/users">Users</a></li>
      <li id="back_to_user_area"><a href="/dashboard">Back to User Area</a></li>
    </ul>
    <ul class="header-item tabs" id="utility_nav">
      <li id="current_user"><a href="/admin/users/1">Admin</a></li>
      <li id="logout"><a rel="nofollow" data-method="delete" href="/users/sign_out">Logout</a></li>
    </ul>

Do I need to define a `User` ActiveAdmin in the non-namespaced area too? The working link refs to the user show of the admin area. I don't really want to have another User page, but seeing it like this I could imagine there is no link by default because I don't have `User`s in den non-namespaced area...

**Comment by TheFlow0360** [comment]
Creating another resource without namespace for `User`` really solves the problem. But now, I have two resources to maintain, that isn't really what I want...

**Comment by TheFlow0360** [comment]
My solution is now to have a non-namespaced User resource that's just responsible for viewing and editing the current user and the "real" User resource to manage all users, which is in the `:admin` namespace. 

    ActiveAdmin.register User, namespace: :admin do
      actions :all, except: [:edit, :update]
      menu priority: 2 
    end
    
    ActiveAdmin.register User do
      actions :show, :edit, :update
      menu false
    end

To make this work, I also had to modify the utility menu for the admin namespace, so that the link doesn't refer to the admin User controller.

    config.namespace :admin do |admin|
      ...
      admin.build_menu :utility_navigation do |menu|
        menu.add id: 'current_user', label: -> { display_name current_active_admin_user }, url: -> { user_path(current_active_admin_user) }, if: :current_active_admin_user?
        admin.add_logout_button_to_menu menu
      end
    end
