### ISSUE TITLE
change form actions cancel link destination without breaking design

### ISSUE THREAD

**Issue by TheFlow0360** [activeadmin/activeadmin#4845]
When creating the default actions submit and cancel by writing `f.actions` this currently looks for me like this:

    <fieldset class="actions">
      <ol>
        <li class="action input_action " id="user_submit_action">
          <input name="commit" value="Update User" data-disable-with="Update User" type="submit">
        </li>
        <li class="cancel">
          <a href="/users">Cancel</a>
        </li>
      </ol>
    </fieldset>

The problem is, my controller doesn't allow the index action - cancel should go back to the show action (where I'm already coming from, so imho it SHOULD go back there by default). So I tried writing this:

    form do |f|
      f.inputs do
        ...
      end
      f.actions do
        f.action :submit
        f.action :cancel
      end
    end

Now my html looks like this:

    <fieldset class="actions">
      <ol>
        <li class="action input_action " id="user_submit_action">
          <input name="commit" value="Update User" data-disable-with="Update User" type="submit">
        </li>
        <li class="action link_action " id="user_cancel_action">
          <a href="http://127.0.0.1:3000/users/1">Cancel User</a>
        </li>
      </ol>
    </fieldset>

The cancel link is now working like it should (although the link isn't that pretty), but my problem is that it now looks different. It's a link instead of the button. What parameters do I need to supply to let it look the same? 

Or is there a better way to do this? I tried to debug a little and found that the default `commit_action_with_cancel_link` calls `cancel_link` without parameters, and thus defaults to the index action. I don't see a way to interfere with this.

**Comment by Fivell** [comment]
@TheFlow0360 , in my opinion cancel link should redirect to ```:back```

**Comment by Fivell** [comment]
@TheFlow0360 , can you try
```ruby
f.actions do
    f.action :submit
    f.cancel_link({action: "show"})
  end
```

**Comment by TheFlow0360** [comment]
That's working, thanks a lot! It's so easy and obvious, I could have had this idea myself *facepalm*.

**Comment by lauraannwilliams** [comment]
I wish this was in the doc examples, took me forever to find!

**Comment by mirelon** [comment]
```
f.actions do
    f.add_create_another_checkbox
    f.action :submit
    f.cancel_link({action: "show"})
end
```
