### ISSUE TITLE
Support dynamic sidebar titles.

### ISSUE THREAD

**Issue by codebymikey** [activeadmin/activeadmin#4846]
I'm aware that I can use a proc like this:

```ruby
sidebar_title = proc{ "User's friends (#{user.friend_count})" }.call
sidebar sidebar_title, only: [:show, :edit]  do
   # ...
end
```

I'm trying to create a Sidebar title that contains the length of its children like this `User's friends (20)`, but there doesn't seem to be a way to access the current scope/parameters from inside the proc.

**Comment by varyonic** [comment]
I've not done this, but I think the solution would be:
1. Subclass ActiveAdmin::ViewsSidebarSection and override build to set section.title as needed.
2. Use `config.sidebar_sections << MyCustomSidebarSection` in the resource DSL.

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded.  Please feel free to leave a comment requesting this issue be reopened if needed.

**Comment by joshlin** [comment]
I am still looking for this feature to have in AA. 
I've tried:

-  sidebar "#{user.friend_count}"

-  sidebar proc{ "#{user.friend_count}" } .call

Both don't work for me. It seems the resource "user" is not evaluated. Is there any workaround I can do?

**Comment by jeff-upbit** [comment]
@joshlin 
```
  module ActiveAdmin
    class SidebarProc < Proc
      def to_s
        self
      end
      def titlecase
        self.call.titlecase
      end
      def downcase
        self.call.downcase
      end
      def underscore
        self.call.underscore
      end
    end
  end
```
```
sidebar ActiveAdmin::SidebarProc.new { "#{user.friend_count}" } do
```
