### ISSUE TITLE
Unable to wrap the table caption in index_as_table

### ISSUE THREAD

**Issue by priyanka** [activeadmin/activeadmin#4855]
Hi,

   I've used active admin in my rails application. I'm using index_as_table approach on my backend page. I want to set fix width for column and tried to use css approach. Via css i'm able to fix the width but now issue is in table caption as text can't wrap or break into word. I've tried to wrap the text, break the word but no joy with css.

Here is attached screenshot and css which i've applied (tried overflow-x but no success).
![index_as_table_column_issue](https://cloud.githubusercontent.com/assets/55856/23821133/84698a94-064f-11e7-919f-bd6ce530cd9b.png)

Can anyone assist me to resolve this caption overlapping issue?

**Comment by varyonic** [comment]
You can embed <br/> like so: `column raw('Progress<br>Rating'), :qty`

**Comment by priyanka** [comment]
Thanks. Closing this issue.
