### ISSUE TITLE
Current Filter: fields not translated, values not resolved

### ISSUE THREAD

**Issue by momolog** [activeadmin/activeadmin#4859]
I am defining a filter like so:

    filter :eventtype, as: :select
    filter :user

The result looks like this:

<img width="1178" alt="veranstaltungen schallware-2" src="https://cloud.githubusercontent.com/assets/71108/23908530/93db68d0-08d4-11e7-98b3-d9f91bd18ee8.png">

The field names in the filter section are nicely translated, the values in the select boxes are resolved.
But in the "current filters" section, this is no longer the case, instead it shows the titleized field names and the raw ids.

This is probably a bug.

**Comment by Fivell** [comment]
refs https://github.com/activeadmin/activeadmin/pull/3902

**Comment by ccallebs** [comment]
@Fivell I can take another look at this tonight -- maybe get the PR into a mergeable state.

**Comment by deivid-rodriguez** [comment]
ping @ccallebs

**Comment by deivid-rodriguez** [comment]
Refs #3958, #4899. We should probably unify all these.

**Comment by Fivell** [comment]
closed by #4951
