### ISSUE TITLE
export csv file as delayed job then upload the file to amazon bucket

### ISSUE THREAD

**Issue by shimaalynks** [activeadmin/activeadmin#4860]
I want to override the default behavior of exporting CSV format to browser into delayed job that run in background, then upload the created csv file to amazon bucket.
how can i achieve that?
ur help is highly appreciated
note: activeadmin version 0.6.6, rails 3

**Comment by varyonic** [comment]
Use a [collection_action](https://activeadmin.info/8-custom-actions.html#collection-actions) to queue the background job, from there use regular Rails functionality.  I recommend asking follow up questions on StackOverflow, here's a [good example](http://stackoverflow.com/questions/8788307/how-to-generate-a-csv-file-in-a-background-task).
