### ISSUE TITLE
Override ActiveAdmin Devise Session Controller

### ISSUE THREAD

**Issue by chrisseldo** [activeadmin/activeadmin#4861]
I need to override the ActiveAdmin Session Controller with my own authentication method. What's the best way to achieve this?

**Comment by varyonic** [comment]
See [this answer](http://stackoverflow.com/questions/21713915/how-do-i-override-the-passwordscontroller-actions-in-a-rails-app-with-activeadmin) as a good starting point.  I would copy and modify ActiveAdmin::Devise.config and pass it to devise_for.
