### ISSUE TITLE
Has many / nested object problem in form

### ISSUE THREAD

**Issue by knagode** [activeadmin/activeadmin#4863]
I have event has many event_sessions relation. I want to easily manage event_sessions of specific event. 

I am trying like this:
```
  form do |f|
    f.inputs "Event Details" do
      f.input :name
    end

    f.inputs 'Sessions' do
      f.has_many :event_sessions, new_record: true do |c|
        c.input :starts_at
      end
    end
    f.actions
  end
```

But I am getting:

```
undefined method `new_record?' for nil:NilClass
```

I have Rails 5. Is there a better way to make this work?

**Comment by knagode** [comment]
It started working when I added 'accepts_nested_attributes_for :event_sessions' on `event` model.

**Comment by dhunnapotha** [comment]
This helped. Thanks :+1:
