### ISSUE TITLE
How do you use this gem with jQuery 3?

### ISSUE THREAD

**Issue by blimmer** [activeadmin/activeadmin#4864]
I'm trying to figure out how to configure ActiveAdmin to use jquery version 3. Because of this line:

https://github.com/activeadmin/activeadmin/blob/6411350c8abf8dd8229dfe3e6e3f898a8992fd16/app/assets/javascripts/active_admin/base.js.coffee#L1

We're always importing jquery version 1.x, according to the [jquery-rails](https://github.com/rails/jquery-rails#installation) documentation.

Is there a way I can use this with jquery3? Is it not supported? It seems like this project went from jquery2 back down to jquery 1 with [this commit](https://github.com/activeadmin/activeadmin/commit/d32d4c7cea92155c76e1425aa450b0fa835a0662) by @timoschilling , which seems a bit strange.

**Comment by varyonic** [comment]
ActiveAdmin tends to upgrade dependencies as slowly as possible to remain backwardly compatible as long as possible.  What are the benefits of jQuery 3 in your case?  Have you tried adding it at the top of your active_admin.js?

**Comment by blimmer** [comment]
Interesting about the Rails 4.2+ requirement in jquery rails. Thanks for the explanation, that makes sense.

I'm not in a huge rush to get onto jQuery 3, I was just upgrading to `pre5` and touching up all of my other JS library dependencies that now support jQuery 3. I thought if it was easy to get onto 3, I might as well do it now. That said, I'd rather stick with what AA is using for best support.

Thanks!

**Comment by javierjulio** [comment]
No need to keep this open if we are looking into v3. No helpful info here since it only references switching to use v3. The other ticket is useful since it is easy to replicate.
