### ISSUE TITLE
Can anyone assist me to integrate Angular2 bootstrap with ActiveAdmin?

### ISSUE THREAD

**Issue by priyanka** [activeadmin/activeadmin#4865]
Hi,

I have created Application which has Rails & Angular2 JS combination. Added ActiveAdmin gem. Now at backend i see default active admin layout but i want to change theme to use NG2 bootstrap.

I've added layout_hack.rb

module ActiveAdmin::Views::Pages::BaseExtension
  def build_active_admin_head
    super
    within @head do
      render partial: 'layouts/active_admin_header'
    end
  end
end

class ActiveAdmin::Views::Pages::Base
  prepend ActiveAdmin::Views::Pages::BaseExtension
end

=> active_admin_header.html.erb contains header which loads from Angular2.

Here is screenshot of admin section.
![active-admin-angular2-bootstrap](https://cloud.githubusercontent.com/assets/55856/24033375/9fac79de-0b12-11e7-9ed4-1d280fdc905f.png)

Thanks for help in advance.

**Comment by timoschilling** [comment]
This is not an issue, ask on stackoverflow

**Comment by varyonic** [comment]
You can try looking at the other [theme plugins](https://github.com/activeadmin/activeadmin/wiki/Themes) for ideas, but [StackOverflow](http://stackoverflow.com/search?q=%5Bactiveadmin%5D+angular) is the best place to follow up.
