### ISSUE TITLE
Unregister Resources?

### ISSUE THREAD

**Issue by TheFlow0360** [activeadmin/activeadmin#4872]
I'm currently playing around with meta programming and was successful in dynamically creating AA resources. The problem, however, is deleting them. Every time I delete a model for which I registered a resource, the `ActiveAdmin.routes` call fails (no surprise there). I have to restart the server to be able to retrieve the routes again.

I need to somehow unregister resources. I haven't found anything when I searched regarding this topic. Is this possible?

**Comment by Fivell** [comment]
@TheFlow0360 , for development env AA uses [load! and unload! methods](https://github.com/activeadmin/activeadmin/blob/5b711b6e22230e6e28be2a9d7367e9423d5dcc25/lib/active_admin/application.rb#L213)

**Comment by TheFlow0360** [comment]
@Fivell thanks, I'll try to work with this. It looks like I need to unload the whole namespace, which means I have to reload all other Resources (could be quite an overhead). But I'll have a closer look, maybe there is a workaround for that.

**Comment by TheFlow0360** [comment]
I found this block that does the unregistering for the resources I guess I'll use this for my specific resource if the full unload has a performance impact that is unbearable, but for now, I'll stick with the oneliner.

    def unload_resources!
      resources.each do |resource|
        parent = (module_name || 'Object').constantize
        name   = resource.controller_name.split('::').last
        parent.send(:remove_const, name) if parent.const_defined?(name, false)

        # Remove circular references
        resource.controller.active_admin_config = nil
        if resource.is_a?(Resource) && resource.dsl
          resource.dsl.run_registration_block { @config = nil }
        end
      end
      @resources = ResourceCollection.new
    end
