### ISSUE TITLE
Current filters not work via click on pagination links

### ISSUE THREAD

**Issue by nizovtsevnv** [activeadmin/activeadmin#4874]
I use current version from Github on Rails 4.2.8.

Step by step explanation:
1. I choose some filters in the sidebar and click "Filter"
2. I see the page with filtered list
3. I click on second page in the pagination bar
4. I see the page without appended filters

In the URL on p4 I see all filters, but without parameter commit=Filter, if I add it manually then I see second page with proper filters.

**Comment by Fivell** [comment]
@nizovtsevnv , can you add more details, please take a look at #4876, can't reproduce this

**Comment by Fivell** [comment]
@nizovtsevnv , we can't reproduce it, feel free to create another issue with more details and steps to reproduce

**Comment by zio-buck** [comment]
FWIW I've not solved this but I think I tracked it down to Kaminari. Specifically it looks like kaminari-core blacklists the `commit` param.

https://github.com/kaminari/kaminari/blob/v1.1.1/kaminari-core/lib/kaminari/helpers/tags.rb#L4
