### ISSUE TITLE
Is it possible to show first active_admin_comment in top-level columns?

### ISSUE THREAD

**Issue by exequeryphil** [activeadmin/activeadmin#4878]
I've got an admin file that looks like this:

```
ActiveAdmin.register BlockedDate do
  permit_params :start_date, :end_date, :updated_at, :blocked_date
  index do
  	column :start_date
  	column :end_date
  	column :updated_at
  end
end
```

I'm wondering if there's a way to add a column that displays the FIRST active_admin_comment for each row item in the BlockedDate model?  Is this even possible?

**Comment by varyonic** [comment]
I don't use them, but my guess would be:
```ruby
column(:comment) { |r| r.active_admin_comments.first.body }
```

**Comment by Fivell** [comment]
related
http://stackoverflow.com/questions/18453520/how-to-get-a-collection-of-comments-from-a-resource-in-activeadmin
