### ISSUE TITLE
Flash is not persisted and not shown in Rails 4.2.7

### ISSUE THREAD

**Issue by andreydeineko** [activeadmin/activeadmin#4879]
As title says.

I have the `member_action`:

```ruby
member_action :invalidate_feed_products, method: :get do
  store.invalidate_feed_products
  redirect_to admin_store_path(store), flash: { notice: "Store's feed was invalidated." }
  binding.pry # <=========== checking the `flash`
end
```

In the `binding.pry` line I cal see, that `flash` is there:
```ruby
<ActionDispatch::Flash::FlashHash:0x007ff5c5b6b490 @discard=#<Set: {}>, @flashes={"notice"=>"Store's feed was invalidated."}, @now=nil>
```

But right after that the page gets reloaded:

```
Started GET "/admin/stores/1" for 127.0.0.1 at 2017-03-23 19:59:38 +0100
Processing by Admin::StoresController#show as HTML
  Parameters: {"id"=>"1"}
```

And when I check `flash` in here:
```ruby
module ActiveAdmin
  module ViewHelpers
    module FlashHelper

      # Returns all the flash keys to display in any Active Admin view.
      # This method removes the :timedout key that Devise uses by default.
      # Note Rails >= 4.1 normalizes keys to strings automatically.
      def flash_messages
        binding.pry #<===================== flash is empty
        @flash_messages ||= flash.to_hash.with_indifferent_access.except(*active_admin_application.flash_keys_to_except)
      end
    end
  end
end
```

flash is empty:
```
<ActionDispatch::Flash::FlashHash:0x007ff5a77cd220 @discard=#<Set: {}>, @flashes={}, @now=nil>
```

**EDIT**

With either of below **situation is the same**:

```ruby
  member_action :invalidate_feed_products, method: :get do
    store.invalidate_feed_products
    redirect_to({ action: :show }, notice: "Store's feed was invalidated.")
  end
```

```ruby
  member_action :invalidate_feed_products, method: :get do
    store.invalidate_feed_products
    redirect_to admin_store_path(store), notice: "Store's feed was invalidated."
  end
```

```ruby
  member_action :invalidate_feed_products, method: :get do
    store.invalidate_feed_products
    redirect_to resource_path, notice: "Store's feed was invalidated."
  end
```

**Comment by Fivell** [comment]
@andreydeineko ,  did you try [this?](http://stackoverflow.com/a/8171144/246544)

**Comment by andreydeineko** [comment]
@Fivell absolutely. I should have mentioned this. The problem is not with setting the flash, it works either way, problem is that page gets reloaded and when it gets to `ActiveAdmin::ViewHelpers::FlashHelper#flash_messages` the `flash` is emptied...

**Comment by Fivell** [comment]
also checkout [documentation](https://activeadmin.info/8-custom-actions.html) . There are examples that included redirect with notice.
```
ActiveAdmin.register User do

  member_action :lock, method: :put do
    resource.lock!
    redirect_to resource_path, notice: "Locked!"
  end

end
```

So looks like instead of
```
   redirect_to admin_store_path(store), flash: { notice: "Store's feed was invalidated." }
```

this can be used

```
   redirect_to admin_store_path(store), notice: "Store's feed was invalidated." 
```

**Comment by andreydeineko** [comment]
@Fivell I appreciate your input, but it is not helping, which is very-very unfortunate for me...

Please, check it out thoroughly, you'll see that the problem is not with setting the flash - *it is being set with all of the options* - problem is that it gets lost because of the redirect.

**Comment by Fivell** [comment]
@andreydeineko, I can't reproduce this, also there is  a [cucumber feature ](https://github.com/activeadmin/activeadmin/blob/9f157bb178ec76dd55dca630664f8bf44d8e6abc/features/specifying_actions.feature#L116) to test flash is visible after redirect

**Comment by andreydeineko** [comment]
@Fivell I am sure tests are fine.

Btw, when I set flash inside the `ActiveAdmin::ViewHelpers::FlashHelper#flash_messages` - it is being properly displayed. Maybe this could be a hint?...

Either way, thanks a lot for the help so far!

**Comment by Fivell** [comment]
@andreydeineko , no it is not clean for me, looks like not an activeadmin issue

**Comment by varyonic** [comment]
I've not noticed this elsewhere as a problem.  I use
```ruby
  redirect_to resource_path, notice: "Store's feed was invalidated."
```
or
```ruby
  flash[:notice] = "Store's feed was invalidated."
  redirect_to resource_path
```
We're on 4.2.7 for a while.  If you can reproduce in a sample app that would be great.

**Comment by hickscorp** [comment]
:+1: never got the flash to work with AA.

Rails 4.2 here. I tried to debug this to some extent, something's clearly wrong.
It's like if the flashes are never wrote into the session. I can see themright after calling `flash[:...] =` or right after a `redirect_to ... alert: '...'` but on the next load they're gone.

Maybe a problem with the order of the session being loaded too late?

**Comment by andreydeineko** [comment]
Silly of me. In the project there was
```ruby
request.session_options[:skip] = true
```

in `before_action`. Skipping this makes flash working as it should be. Closing.
