### ISSUE TITLE
Pre5 works fine but master causing a "too many redirects" error

### ISSUE THREAD

**Issue by JimW** [activeadmin/activeadmin#4884]
I have a project that works fine with Pre5 but with the current master that uses a different formtastic, Arbre, Inherited _Resources I get this redirect error.  Any obvious areas to focus? I forgot what broke that forced me to use the master instead of Pre5, but I guess I'll find out again.. 

I'm using Devise+Activeadmin+Pundit  and it only happens on Heroku, not locally.

Thanks for any ideas,
Jim

**Comment by Fivell** [comment]
@JimW , any more details? logs? etc..

**Comment by JimW** [comment]
@Fivell Details coming soon.  Had to finish some other things first.

**Comment by Fivell** [comment]
@JimW ,  closing this since you didn't provide any information.
