### ISSUE TITLE
Doc moving resources from RailsAdmin to Acitive Admin

### ISSUE THREAD

**Issue by pesaply** [activeadmin/activeadmin#4885]
Hii , I I Was Using Railsadmin But I Decided To Move To Activeadmin , my issue cant find doc on mooving my currently resources

**Comment by Fivell** [comment]
@pesaply , you mean documentation about migration from rails admin to AA ?

**Comment by varyonic** [comment]
I think that would make a great blog post.  Unfortunately I don't know anyone who has done that or written about it.  Let us know how it works out!
