### ISSUE TITLE
Question: way to dynamically display information about a model in a form

### ISSUE THREAD

**Issue by smileytechguy** [activeadmin/activeadmin#4886]
Hi,

I currently have a form which uses a dropdown to select a model instance, and that instance has a attribute which I want to display on the form.

I currently have
```
f.input :athlete, :collection => Athlete.all.sort_by(&:last_name), :required => true
```
I would like a additional row right below to show the additional attribute from the selected athlete.  How can I do this

Thanks,
smileytechguy

**Comment by varyonic** [comment]
So when an athlete is selected by last name then display additional information about that athlete on the form.  You probably need AJAX for that.  Best to ask on [StackOverflow](http://stackoverflow.com/questions/1151835/ajax-rails-validation).

**Comment by smileytechguy** [comment]
@varyonic I ended up implementing an AJAX solution, thanks
