### ISSUE TITLE
Can't add new records via nested form

### ISSUE THREAD

**Issue by lesniakania** [activeadmin/activeadmin#4887]
I have following setup:

```ruby
ActiveAdmin.register Section do
  belongs_to :questionnaire
  permit_params :title, questions_attributes: [:id, :title, :_destroy, :_create, :_update]

  form do |f|
    f.inputs do
      f.input :title
    end

    f.has_many :questions do |q|
      f.inputs do
        q.input :title
      end
  end
end
```

And what I get in controller is:

```
D, [2017-03-28T10:13:21.444361 #97753] DEBUG -- : Unpermitted parameter: NEW_QUESTION_RECORD
=> {"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"h9XC+iYRjdpoDXhNK3JCts3jgxTjQb+MovnL+Ka2Sy9NxDB3no8KNxNa6ssZbYT5OdMvb8NMfJleOAAbb2j07g==",
 "commit"=>"Save Section",
 "id"=>"1",
 "questionnaire_id"=>"1",
 "section"=>{"title"=>"Section1", "questions_attributes"=>{}}}
```

From what I was able to debug, is that this key `NEW_QUESTION_RECORD` is preventing strong parameters from working correctly, as this syntax to permit dynamic keys in the hash works only with numerical values.

Is this `NEW_QUESTION_RECORD` intended behavior?

Rails: 4.2.8 (although I tried with 5.0.0 and nothing changes)
Active admin: All versions starting from `1.0.0.pre2`, even `master`

**Comment by jdenquin** [comment]
Could you paste your `Section` model?

**Comment by lesniakania** [comment]
Sure:

```ruby
 class Section < ActiveRecord::Base
   belongs_to :questionnaire
   has_many :questions
 
   accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
end
```

**Comment by stasou** [comment]
Shouldn't it be `q.inputs do` for the nested form?

**Comment by varyonic** [comment]
I believe stasou is correct. I’m going to close this since you haven’t responded.  Please feel free to leave a comment requesting this issue be reopened if needed.
