### ISSUE TITLE
Is there a way of rendering a single index page row?

### ISSUE THREAD

**Issue by fabrouy** [activeadmin/activeadmin#4888]
Hello everyone,

I'm trying to reuse my code written in the index block in order to render a single row. 

```ruby
index do
    selectable_column
    id_column
    column(:school) { |user| link_to user.school, admin_school_path(user.school) }
end
```

I want to respond rendering a admin/users/update.js.erb template file which inside updates the full user table row, something like this:

```ruby
$("#user_<%= @user.id %>").html("<%= j(render(partial: 'user', locals: { user: @user })) %>"); 
```
How can accomplish this using ARBRE? 

I see I can do this:

```ruby
index do
    render "index", context: self
end
```

```ruby
context.instance_eval do
    selectable_column
    id_column
    column(:school) { |user| link_to user.school, admin_school_path(user.school) }
end
```

But not sure I'm going in the right direction. 

Thank you

**Comment by varyonic** [comment]
I guess you are trying to do something [like this](https://amolnpujari.wordpress.com/2013/10/23/activeadmin-cool-tweaks/) I can't say it's the 'right' direction.  Perhaps a [custom index](https://activeadmin.info/3-index-pages/custom-index.html) with a JavaScript component?  You might get better responses on [StackOverflow like this](http://stackoverflow.com/questions/7818722/grid-view-that-would-add-and-edit-rows-on-the-client-side-and-save-the-whole-tab)

**Comment by fabrouy** [comment]
Hey there @varyonic, thank you for your response.

I have indeed something similar to the tweak you mention (but using best_in_place). But is not enough because if request is successful I need to update the whole table row because other column values depend on this previous action made.

So what I need to find is how to render a single row, and best desirable reusing the code I have written. Which is:
```ruby
selectable_column
id_column
column(:school) { |user| link_to user.school, admin_school_path(user.school) }
```

Is there a way of extracting the above code to a builder file and render that template passing a single object (not a collection) so it outputs a table row HTML?

I searched and asked in SO but can't come to an elegant solution on this.

I have been reading the code but it's not clear to me how things are getting rendered
https://github.com/activeadmin/activeadmin/blob/8d58c9bdcbdfd634a366b423cf19f91d8ed7363a/lib/active_admin/views/components/table_for.rb#L84
```ruby
def build_table_body
  @tbody = tbody do
    # Build enough rows for our collection
    @collection.each do |elem|
      classes = [helpers.cycle('odd', 'even')]

      if @row_class
        classes << @row_class.call(elem)
      end

      tr(class: classes.flatten.join(' '), id: dom_id_for(elem))
    end
  end
end
```

**Comment by dmitry** [comment]
There are no way to do that easily, as `TableFor` creates table not by row, but by the column. Search for `@tbody` and you will understand what I mean. The only solution to create a new class with parts of the code, including `build_table_cell` and `column` or better propose better implementation of the `TableFor` (including https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/views/index_as_table.rb#L251)

**Comment by fabrouy** [comment]
Hello @dmitry, thanks for your response.

It's too bad that tables are generated this way, with no per-row code abstraction and no easy way of replacing a whole row content. Kind of a must nowadays we are trying to build more and more responsive apps.

I will try to put something together, however my knowledge on AA implementation is limited so any help will be very appreciated.
