### ISSUE TITLE
Bad Pagination HTML

### ISSUE THREAD

**Issue by jdenquin** [activeadmin/activeadmin#4891]
Hi guys,

I currently have a problem with the pagination HTML.
It doesn't render the HTML and i've a string with links

Here is the code i've : 
```
<li class="active"><a href="/admin/audiences?order=updated_at_desc">1</a></li><li><a rel="next" href="/admin/audiences?order=updated_at_desc&amp;page=2">2</a></li><li><a href="/admin/audiences?order=updated_at_desc&amp;page=3">3</a></li><li><a href="/admin/audiences?order=updated_at_desc&amp;page=4">4</a></li><li><a href="/admin/audiences?order=updated_at_desc&amp;page=5">5</a></li><li><a href="#">&hellip;</a></li><li><a rel="next" href="/admin/audiences?order=updated_at_desc&amp;page=2"><i class="fa fa-angle-right"></i></a></li><li><a href="/admin/audiences?order=updated_at_desc&amp;page=6"><i class="fa fa-angle-double-right"></i></a></li>
```

I've searched where these links are rendered but found anything.
Any ideas? 

Thanks!

**Comment by varyonic** [comment]
ActiveAdmin::Views::TableFor#build_table_header  Did you html_safe a column heading perhaps?  Best to ask on [StackOverflow](http://stackoverflow.com/questions/tagged/activeadmin)

**Comment by jdenquin** [comment]
OK I close it, the fix is just to add `==` in the kaminari view instead of `=` for partials.
Some work on the CSS and everything is fine.
