### ISSUE TITLE
Multiple confirm prompts appear in batch action

### ISSUE THREAD

**Issue by gxaAlfie** [activeadmin/activeadmin#4893]
Upon performing a batch action then performing the delete action, a confirm modal usually appears asking whether the user wants to proceed with the transaction. I noticed that it is still possible to click the batch action that triggers the confirm prompt to appear. Upon clicking the action again, you can see that another confirm prompt appears. This can be noted when you drag the previous confirm prompt to a different position

**Comment by Fivell** [comment]
hello @gxaAlfie , I can't reproduce this, can you share screens? what version of AA are you using ?

**Comment by gxaAlfie** [comment]
just checked version via bundle show
activeadmin (1.0.0.pre4)

Here's a screenshot of what I'm seeing:
![screen shot 2017-04-03 at 3 30 42 pm](https://cloud.githubusercontent.com/assets/19216508/24599392/966ac3e4-1882-11e7-87c1-4d391a637de4.png)

**Comment by Fivell** [comment]
@gxaAlfie , I can't 
```
select option "delete selected" again while confirm prompt is shown
```

layout is blocked for me
