### ISSUE TITLE
Filtering on a composite column crashes.

### ISSUE THREAD

**Issue by hickscorp** [activeadmin/activeadmin#4898]
We have a filter defined like so:

```
filter :composite_bool, as: :boolean
```

Later we define our collection like so:

```
controller do
  def scoped_collection
    Model.includes(:other_model)
         .select('*, (some_date_column > NOW()) as composite_bool')
  end
end
```

This generates an error: undefined method `composite_bool_eq' for #<Ransack::Search:0x007f95488cecb0>`

When we remove the `filter`, we get the `composite_bool` in the listing table correctly.
We cannot rely on a ruby method on the `Model` instance, we want the filtering to be delegated to the database.

We tried lots of different approaches for defining the filter, no cigar so far.

**Comment by Fivell** [comment]
@hickscorp , did you try [ransackable_scopes](https://github.com/activerecord-hackery/ransack#using-scopesclass-methods) ?

**Comment by Fivell** [comment]
@hickscorp , filters doesn't work with aliases , so best option for you is filtering using custom scope as it was mentioned earlier
