### ISSUE TITLE
Missing translations in filter 'current_filters' section.

### ISSUE THREAD

**Issue by stasou** [activeadmin/activeadmin#4899]
Hello,
I know that the translations issue at the search_status section has been addressed, however, I reckon there are a few issues remaining.
I do manage to translate all the `search_status` fields in my language (greek), but I don't get the field names and some other things translated. See the screenshot:

![image](https://cloud.githubusercontent.com/assets/5177486/24795692/eb834398-1b92-11e7-92ee-4934339ac787.png)

The green arrow shows the field name translated in the filter form.
However, a little lower, in the current_filters section, the field name does not get translated.
Also, I'm struggling to find where is the translation for the scope results (ALL or anything else).

I know I need not praise, but there has been some seriously greatly done work here, this is one of the most helpful tools one can get. Congrats.

Anyway, any help will be appreciated. Thanks

**Comment by stasou** [comment]
Well, after some code digging, I realized that all I had to do was override one method from the `ActiveAdmin::Filters::Active` class to give to my app functionality, that in my opinion should be there off-the-shelf.

`module ActiveAdmin
  module Filters
    class Active
      def build_filters
        filters = @params[:q] || []
        filters.map do |param|
          f = param[0].sub(/((_contains)|(_begins_with)|(_ends_with)|(_equeals)|(_greater_than)|(_less_than)|(_eq))\z/, '')
          n = I18n.t("activerecord.attributes.#{@resource_class.to_s.downcase}.#{f}")
          param[0] = param[0].sub(f, n)
          Humanized.new(param)
        end
      end
    end
  end
end`

**Comment by varyonic** [comment]
Original PR was #3289 by @ccallebs and @timoschilling made some i18n fixes.

**Comment by stasou** [comment]
Below, I am posting a workaround I used to force translation of active filters.

It will require adding keys to the i18n locales, to manage associations and enumerable attributes (AR Enums). It will also require to export a default naming method for associated models.

In my workaround, I am making the subjective assumption that this method (attribute) should be named either `display_name`, `fullname` or `name`, in that specific order of preference. Should none of the above exist, the output will use the id of the associated object.

This is not the best solution that can exist of course, it has not been put to dev tests and I do not recommend others to use it. Plus, it has only been used with ActiveRecord. I am just posting it here to show what the matter is and to give a possible orientation towards a plausible solution.

So, hands on:
I am overriding the `ActiveAdmin::Filters::Active` class, rewriting the `build_filters` method to handle a number of different scenarios (see inline comments)

```
module ActiveAdmin
  module Filters
    class Active
      def build_filters
        filters = @params[:q] || []
        filters.map do |param|
          f = param[0].sub(/((_contains)|(_starts_with)|(_ends_with)|(_equals)|(_greater_than)|(_less_than)|(_eq))\z/, '')
          n = I18n.t("activerecord.attributes.#{@resource_class.to_s.downcase}.#{f}").gsub(/[\. ]*/, '')
          param[0] = param[0].sub(f, n)

          pl = f.pluralize
          enumcondition = @resource_class.methods.include?("#{pl}".to_sym)

          if param[0].match?(/_eq\z/)
            m = f.gsub(/_([a-z])/) { $1.upcase }.sub(/Id\z/, '').camelcase
            n = f.sub(/_[^_]+\z/, '').sub(/_[^_]+\z/, '').gsub(/_([a-z])/) { $1.upcase }.sub(/Id\z/, '').camelcase.sub(/s\z/,'')
            ff = m.sub(/\A#{n}s/, '')
            if Kernel.const_defined?(ff) && !Kernel.const_defined?(m)
              # If param is a joint table
              c = Module.const_get( ff )
              o = c.find(param[1])
              v = o.try(:display_name) || o.try(:fullname) || o.try(:name) || o.id
              param[1] = v
            elsif Kernel.const_defined? m
              # If param is a dependency
              c = Module.const_get( m )
              o = c.find(param[1])
              v = o.try(:display_name) || o.try(:fullname) || o.try(:name) || o.id
              param[1] = v
            elsif enumcondition
              # If param is an ActiveRecord Enum
              my_enum = eval("#{@resource_class}.#{pl}")
              my_val  = my_enum.select {|k| my_enum[k] == param[1].to_i }.keys[0]
              param[1] = I18n.t("activerecord.attributes.#{@resource_class.model_name.i18n_key}.#{pl}.#{my_val}")
            elsif param[1] == "true"
              # If param is true
              param[1] = I18n.t('active_admin.status_tag.yes')
            elsif param[1] == "false"
              # If param is false
              param[1] = I18n.t('active_admin.status_tag.no')
            end
            # else leave it as is
          end

          Humanized.new(param)
        end
      end
    end
  end
end
```
