### ISSUE TITLE
There was an error while trying to load the gem 'activeadmin'. (Bundler::GemRequireError)

### ISSUE THREAD

**Issue by seemalakishore** [activeadmin/activeadmin#4901]
Am trying to deploy active admin application in UAT environment. Everything worked fine in development, but when I try to deploy with nginx and puma. It is throwing error.

`There was an error while trying to load the gem 'activeadmin'. (Bundler::GemRequireError)`
Am referencing active admin gem with github url in to my application

**Comment by varyonic** [comment]
Stack trace? Is a firewall blocking access from UAT to GitHub?

**Comment by Fivell** [comment]
closing due lack of feedback
