### ISSUE TITLE
ActionView::Template::Error (undefined method `order_clause' for #<ActiveAdmin::Page:0x0000000971c650>):

### ISSUE THREAD

**Issue by mike1011** [activeadmin/activeadmin#4902]
My Rails app has been working great with ActiveAdmin..but now i am facing an issue ..which seems very hard to resolve.

The only reason i can see is my Gemfile.
`gem 'activeadmin', github: 'activeadmin'`

which always points to master,when i took a look at the previous working app..it had version of `1.0.0.pre2` and now it has `pre5`.Should i use a version number or Is there a fix for this issue.?

any help will be appreciated

```

ActionView::Template::Error (undefined method `order_clause' for #<ActiveAdmin::Page:0x0000000971c650>):
    1: insert_tag active_admin_application.view_factory["page"]
  app/admin/dashboard.rb:81:in `block (5 levels) in <top (required)>'
  app/admin/dashboard.rb:76:in `block (4 levels) in <top (required)>'
  app/admin/dashboard.rb:74:in `block (3 levels) in <top (required)>'
  app/admin/dashboard.rb:11:in `block (2 levels) in <top (required)>'
```

this is my view file ..`dashboard.rb.`.snippet of the code inside tab block

 ```
table_for @request_edits, sortable: true do
                  column :email do |edit|
                    edit.hall_request.user.email
                  end
                  ##it fails here..this is line 81..
                  column("Status")   {|request_edit| status_tag(request_edit.status)}
                  column :type_of_edit do |edit|
                      link_to(edit.type_of_edit.capitalize,admin_hall_request_request_edit_path(edit.hall_request,edit))
                  end
                  column :comment do |edit_request|
                    slice_extra_texts(edit_request.comment)
                  end
```

**Comment by Fivell** [comment]
@mike1011 , thanks , looks like we forgot  to include  [this method](https://github.com/activeadmin/activeadmin/blob/5b711b6e22230e6e28be2a9d7367e9423d5dcc25/lib/active_admin/resource.rb#L163) to [page class](https://github.com/activeadmin/activeadmin/blob/5b711b6e22230e6e28be2a9d7367e9423d5dcc25/lib/active_admin/page.rb)

**Comment by mike1011** [comment]
Hi @Fivell, Let me know,when i can again point to the latest master branch .as of now i have fixed this error again pointing to 1.0.0.pre2...which is not good as i need to use master.

**Comment by Fivell** [comment]
@mike1011 , can you show how are you handling sorting within page?

``` table_for @request_edits, sortable: true do```

**Comment by Fivell** [comment]
@mike1011 ,can you please  try ```issue_4902``` branch from [fork](https://github.com/Fivell/activeadmin) ?

**Comment by mike1011** [comment]
Thanks @Fivell , i am pointing it to `gem 'activeadmin', git: 'https://github.com/Fivell/activeadmin.git' , :branch => 'issue_4902' `, 

I will love to get this in the master ? :)

**Comment by Fivell** [comment]
@mike1011 , will be merged after review
cc @varyonic

**Comment by mike1011** [comment]
Now .i am using the master branch and its working great.

`gem 'activeadmin', git: 'https://github.com/Fivell/activeadmin.git'`

Thanks

**Comment by Fivell** [comment]
@mike1011 this is how it should be
```
gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin.git'
```
