### ISSUE TITLE
Example User Creation

### ISSUE THREAD

**Issue by ajsnavyae2** [activeadmin/activeadmin#4909]
I'm not getting an example user so I can perform the initial login. Below is the cut from activeadmin.info. I have tried creating a user in phpmyadmin, but keep getting the incorrect email and password message.

Getting Started
Active Admin is released as a Ruby Gem. The gem is to be installed within a Ruby on Rails 4 application. To install, simply add the following to your Gemfile:

# Gemfile
gem 'activeadmin', github: 'activeadmin'
After updating your bundle, run the installer

rails generate active_admin:install
The installer creates an initializer used for configuring defaults used by Active Admin as well as a new folder at app/admin to put all your admin configurations.

Migrate your db and start the server:

$> rake db:migrate
$> rails server
Visit http://localhost:3000/admin and log in using:

User: admin@example.com
Password: password
Voila! You’re on your brand new Active Admin dashboard.

**Comment by varyonic** [comment]
Try StackOverflow, for example [this Q&A](http://stackoverflow.com/questions/7590609/adding-new-admins-to-active-admin).

**Comment by stoplion** [comment]
you have to run `rake db:seed`
Should prob update the doc https://activeadmin.info/documentation.html
