### ISSUE TITLE
Turn off count for entire app?

### ISSUE THREAD

**Issue by galenscook** [activeadmin/activeadmin#4910]
Love that [this](https://github.com/activeadmin/activeadmin/commit/c12dc45cdb1922e131044f75bbdcace0213518db) introduced the ability to turn off count for a specific scope with `show_count: false`.  Is there any way to set this as the default for the entire app?  I'm working with a really huge data set and *never* need a count (on an index, scope or query), it just ends up slowing everything down.

**Comment by Fivell** [comment]
@galenscook , no way at the moment, but FYI it will be  not hard to implement. 
 - create inherited ```default_show_count``` config for this, [example](https://github.com/activeadmin/activeadmin/blob/5b711b6e22230e6e28be2a9d7367e9423d5dcc25/lib/active_admin/application.rb#L30)
 - pass value from config [here](https://github.com/activeadmin/activeadmin/blob/fc08c0faff09d8257860c80fd81ee4278fc186be/lib/active_admin/resource_dsl.rb#L37) if ```show_count``` was not set

**Comment by galenscook** [comment]
@Fivell , as it turns out, `show_count: false` doesn't actually solve one of my problems.  It disables the count on scopes, but I can't find a way to make it successfully disable the count on filters (by filters I mean the queries in the side bar).  Is there any way to do this?

For reference:

In model:
```
scope :full_name_equals, -> (name) { joins(:user).where("lower(full_name(users.first_name, users.last_name)) = lower(?)", name.strip) }
```
In controller:
```
...
  filter :full_name, as: :string, filters: ['equals', 'contains']
```
Query when searching by "Full Name Equals"
```
(125.6ms)  SELECT COUNT(DISTINCT count_column) FROM (SELECT  "organizations_users"."id" AS count_column FROM "organizations_users" INNER JOIN "users" ON "users"."id" = "organizations_users"."user_id" LEFT OUTER JOIN "organizations" ON "organizations"."id" = "organizations_users"."organization_id" WHERE (lower(full_name(users.first_name, users.last_name)) = lower('Galen Cook')) LIMIT 30 OFFSET 0) subquery_for_count
```

**Comment by Fivell** [comment]
@galenscook , there were issues about this I think, take a look #4133

**Comment by Fivell** [comment]
kaminari supports this https://github.com/kaminari/kaminari/blob/2efad3fc7ff1920b2ea2ebc03e3003c938c7decd/README.md#paginating-without-issuing-select-count-query

**Comment by Fivell** [comment]
https://github.com/activeadmin/activeadmin/issues/4910#issue-221645390 this was resolved by linked PR,

**Comment by Fivell** [comment]
@galenscook if you  have any idea how we can improve this you're welcome to contribute.
