### ISSUE TITLE
Multiple Select Filter with IDs Fails in 1.0.0pre5 

### ISSUE THREAD

**Issue by dfockler** [activeadmin/activeadmin#4911]
Multiple select filters in ActiveAdmin when used with ActiveRecord models returns an array of strings in the query params. The current Ransack version is not filtering these string IDs into integers and is causing an exception to occur in AREL. A `params` example that fails is
```
{
        "utf8" => "✓",
        "q" => {
              "subtopic_ids" => [
                  "1696", <-- These strings are causing it to fail
                  "1699"
              ]
        },
       "commit" => "Filter",
       "order" => "published_at_desc",
       "controller" => "admin/content_topics",
       "action" => "index"
}
```

**Comment by Fivell** [comment]
@dfockler , 

>> The current Ransack version is not filtering these string IDs into integers and is causing an exception to occur in AREL. 


how do you know this? And what version of ransack are you talking about ?

**Comment by Fivell** [comment]
@dfockler  can you try [subtopic_id_in](https://github.com/activerecord-hackery/ransack/wiki/basic-searching#in) instead of subtopic_ids.

To use subtopic_ids I think you should define  [custom ransackable_scopes](https://github.com/activerecord-hackery/ransack#using-scopesclass-methods)

**Comment by Fivell** [comment]
I closing this because I have this feature working using master branch, @dfockler ,  try my suggestions if it doesn't help update this issue with more information and I will reopen this.
