### ISSUE TITLE
unpermitted parameters for activeadmin on forked branch

### ISSUE THREAD

**Issue by mike1011** [activeadmin/activeadmin#4912]
I am using rails 4.2 and  active admin branch - 
`gem 'activeadmin', git: 'https://github.com/Fivell/activeadmin.git' , :branch => 'issue_4902'` as a solution suggested for one of my issue raised earlier here- `https://github.com/activeadmin/activeadmin/issues/4902#issuecomment-292863448`.However, now i am unable to create my model through admin dashboard as everytime its giving me `unpermitted parameters `error even after adding the attributes in `permit_param` block.

my `admin/hall.rb`

```
ActiveAdmin.register Hall do

belongs_to :hall_request
permit_params  do
        params =[:name,:description,:home_url,:capacity_in_persons,:additional_details, :event_types,:catering_tag, :hall_request_id,event_types:[],facilities:[]]
        params.push(:catering_tag, :hall_request_id,:event_types=>[],:facilities=>[])
        params
end

```

i have my create action in `controllers/halls_controller.rb` which works fine for non admin but here ,whenever i try to create hall from admin dashboard.i fails always...
i have tried various ways to define permitted attributes in both `admin/hall.rb` and `model/hall.rb` but it is failing always.

`controllers/halls_controller.rb`
  ```
private
    def hall_params
      params.require(:hall).permit(:name, :home_url, :description, :capacity_in_persons, :additional_details, :catering_tag, :hall_request_id,:event_types=>[],:facilities=>[])
      end

```

server console output----
```

Processing by Admin::HallsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"blahblahblahWXq6m+ULi65bC8/H/mzlqcmk+VX3VMTZcGAXcNw8gTB4Q==", "event_types"=>["any string of array comes here"], "catering_tag"=>"BOTH", "facilities"=>["any string of array comes here"], "hall"=>{"name"=>"testers hall", "home_url"=>"", "description"=>"this si any comment this is any commentthis si any comment this is any commentthis si any comment this is any commentthis si any comment this is any comment", "capacity_in_persons"=>"1000"}, "commit"=>"Submit", "hall_request_id"=>"testers-hall"}
```

Kindly advice 

Thanks in advance.

**Comment by Fivell** [comment]
@mike1011 ,  first of all use 
```
https://github.com/activeadmin/activeadmin.git
```

**Comment by Fivell** [comment]
@mike1011 ,
 
```ruby
 params.require(:hall).permit(:name, :home_url, :description, :capacity_in_persons, :additional_details, :catering_tag, :hall_request_id,:event_types=>[],:facilities=>[])
```


should be defined as


```ruby
permit_params :name, :home_url, :description, :capacity_in_persons, :additional_details, :catering_tag, :hall_request_id,:event_types: [], facilities: []
```

documentation 
https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#setting-up-strong-parameters


method

https://github.com/activeadmin/activeadmin/blob/fc08c0faff09d8257860c80fd81ee4278fc186be/lib/active_admin/resource_dsl.rb#L63

**Comment by mike1011** [comment]
i tried above method too but it was **not working**.So finally i tried adding 

```
controller do
  def permitted_params
    ##allows all attributes to be edited
     params.permit!
    end
end


```

as `permit_params` calls this method in the controller.Now i can access the non model attributes by `permitted_params[:event_types].`

**Comment by Fivell** [comment]
>>  it was not working

@mike1011, please show log with error and your resource source code

**Comment by mike1011** [comment]
@Fivell ,Logs are the same as shown above with error warnings as unpermitted paramters.Now its working as i said with below code.

`in admin/hall.rb`

```
 permit_params :here i add all the form fields

controller do
  def permitted_params
    ##allows all attributes to be edited
    params.permit!
  end
  
  ##custom create method for hall
  def create
   ##here i am using permitted_params hash to get any value that i am passing from the form
  end
```

Kindly close this issue ,if this response seems adequate.

**Comment by Fivell** [comment]
@mike1011 , looks like you didn't show exact error .
What I see is
```
Processing by Admin::HallsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"blahblahblahWXq6m+ULi65bC8/H/mzlqcmk+VX3VMTZcGAXcNw8gTB4Q==", "event_types"=>["any string of array comes here"], "catering_tag"=>"BOTH", "facilities"=>["any string of array comes here"], "hall"=>{"name"=>"testers hall", "home_url"=>"", "description"=>"this si any comment this is any commentthis si any comment this is any commentthis si any comment this is any commentthis si any comment this is any comment", "capacity_in_persons"=>"1000"}, "commit"=>"Submit", "hall_request_id"=>"testers-hall"}
```

**Comment by Fivell** [comment]
feel free to open another issue with full  problem description if still  relevant
