### ISSUE TITLE
Renaming Action Items Documentation is Unclear

### ISSUE THREAD

**Issue by thejourneydude** [activeadmin/activeadmin#4921]
I'm attempting to rename action items and discovered the following documentation [here](https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#renaming-action-items).

I'm having an awful time understanding how this works. Where do I put this code? Where do I add the custom text 'Make an Offer'? This documentation should be clearer.

**Comment by varyonic** [comment]
Sigh.  See #2823 and #4739.  I never even use this, but try config/locales/*.yml, an entry like:
```ruby
en:
  active_admin:
    resources:
      offer:
        new_model: 'a new label'
```
Correct me, anyone that uses this (PR welcome).  This could in theory be in a different backing store from yml files.

**Comment by timoschilling** [comment]
We can add a node that `active_admin.resources.offer.new_model` means a I18n key.

**Comment by varyonic** [comment]
I suspect this is confusing to english-only users that ignore i18n most of the time.  Here's a blog post with [example yml and I18n::BackendActiveRecord](http://www.justinweiss.com/articles/rails-i18n-3-quick-tips-and-1-crazy-abuse/).  I understand new users being unfamiliar with i18n but it's not clear what ActiveAdmin documentation can do to help.

**Comment by deivid-rodriguez** [comment]
The wording "For example to change 'New Offer' to 'Make an Offer' set active_admin.resources.offer.new_model." in our docs is definitely unclear. PR with the suggestions above welcome!

**Comment by Fivell** [comment]
@varyonic , can this be closed now?
