### ISSUE TITLE
HIPPA compliant administration (custom index page displaying only when filtered)

### ISSUE THREAD

**Issue by grimmwerks** [activeadmin/activeadmin#4930]
I've got a weird use case; we've got a lot of HIPPA compliant information that we want to protect even from the admins, so in order to be compliant (and yet still get work done) we've decided that a few of our resources have to:

- index page doesn't automatically load but only after selecting custom filter information will the results be displayed
- any adminstration of these resources (update, view, delete, or even filter) will create an entry into an immutable Tracking event with what that user was doing
- if an admin updates or deletes mutable resources they will have to enter a comment - much like a git commit.  So the delete action will have to use the jquery popup / custom action for entering in a commit message or it will be ignored.

I don't need direction for a good portion of this as I've already been poking around and slogging through it; but the way I was doing it wasn't very dry, which is why I'm asking:

What would be the best way of overriding the active admin resource controller and having these special resources inherit from the 'hippa compliant' ones?  I saw some examples with class / inherited resources overrides in the active_admin config?

I figure I create my own index page (with it's own delete action) --- but what would be the best way to only show filtered index requests? Look at the request url or is there some internal param that I can know when something is filtered?

Any other suggestions are appreciated, but I don't expect others to do my homework....

**Comment by varyonic** [comment]
In case you are not aware there are a couple of PaperTrail [plugins for ActiveAdmin](https://github.com/activeadmin/activeadmin/wiki/Plugins) that might help.  If you want an index to not show records you might try setting an empty scope as the default.  Overriding ActiveAdmin::ResourceController might be problematic, stay with [customizing the controller](https://activeadmin.info/8-custom-actions.html) as far as you can.  These kind of design questions are best asked on StackOverflow.

**Comment by grimmwerks** [comment]
Appreciate the suggetion about an empty scope as the default - but it seems any filter then is filtering on the default scope, so it's always empty?

It seems I'm definitely going to have to create my own index pages, so just need to see about how to sniff out if a filter is in use.

**Comment by Fivell** [comment]
>> but what would be the best way to only show filtered index requests?

@grimmwerks 
you can override controller per resource 
something like
```ruby
ActiveAdmin.register Something do
 controller do 
   def apply_filtering(chain)
     if params['q'].blank?
       chain.none
     else
       super
     end 
   end
 end
end
```

**Comment by grimmwerks** [comment]
Appreciate it - see what you're doing, trying to return a [] but I get an error at line 438 of action_view/form_helper: 
```
raise ArgumentError, "First argument in form cannot contain nil or be empty" unless object
```

**Comment by Fivell** [comment]
@grimmwerks , do not return [] , it should be relations , so ```chain.none``` should work

**Comment by grimmwerks** [comment]
@Fivell chain.none is what's throwing the "First argument in form cannot contain nil or be empty"

**Comment by Fivell** [comment]
@grimmwerks . I need to see full backtrace , resource source and request log

**Comment by grimmwerks** [comment]
How's this: https://gist.github.com/grimmwerks/62f73e7cfb338a4f38d6fbcb585778b5

Not sure about the request log for puma?

In BetterErrors it seems to be a sidebar issue as it hits
build_sidebar_content
lands on line 25 of SidebarSection#build_sidebar_content and the rvalue is nil....

**Comment by Fivell** [comment]
@grimmwerks , ok try 
```ruby
ActiveAdmin.register Something do
 controller do 
   def apply_filtering(chain)
     if params['q'].blank?
       @search = chain.ransack({})
       chain.none
     else
       super
     end 
   end
 end
end
```

**Comment by grimmwerks** [comment]
@Fivell AH brilliant! Thank you!  
Not trying to push my luck; but would you happen to know how to customize the blank slate for a resource?  I don't even need specialized ones per resource, but I've got a standard blank_slate_hippa that I'd like to throw in on only the hippa resources (rather than a global change)?

**Comment by Fivell** [comment]
@grimmwerks , for current implementation there is no config for this https://github.com/activeadmin/activeadmin/blob/d01155f73a0e2cc27d712792270357e2b3759d05/lib/active_admin/views/pages/index.rb#L112
