### ISSUE TITLE
ActionController::UnknownFormat 

### ISSUE THREAD

**Issue by amiuhle** [activeadmin/activeadmin#4945]
I'm currently using something like this to send a generated PDF:

```ruby
  controller do
    def show
      super do |format|
        format.pdf do
          # ...
          send_data # <generated.pdf>
        end
      end
    end
  end
```

This worked until `1.0.0.pre5`, but after upgrading to `1.0.0`, I'm getting an `ActionController::UnknownFormat` error.

Is this even the correct way to send PDFs and stuff? I think I've seen something in the docs about that in the past, but couldn't find anything just now.

**Comment by varyonic** [comment]
More likely a [Rails issue](https://github.com/rails/rails/issues?utf8=%E2%9C%93&q=is%3Aissue%20ActionController%3A%3AUnknownFormat) than Active Admin?

**Comment by amiuhle** [comment]
@varyonic Maybe, but reverting back to `1.0.0.pre5` helped.

**Comment by Fivell** [comment]
@amiuhle , do you have
```
 config.download_links = [:csv, :xml, :json, :pdf]
```
in your activeadmin initializer ?

**Comment by Fivell** [comment]
@amiuhle , there are  options to setup download_links
```ruby
ActiveAdmin.register Something do
  index download_links: [:csv, :pdf]
end
```
it supports proc
```ruby
index download_links: -> { params[:action] == :show ?  [:pdf] : [:csv] }
```

**Comment by Fivell** [comment]
@amiuhle , did you try that ?

**Comment by amiuhle** [comment]
@Fivell Sorry for being slow, but as noted above I've just reverted back to `1.0.0.pre5 ` for now, and another project has priority at the moment.

I'll look into when I'm working on that project again. If you want, you can close this issue for now and if your comments above don't help I'll reopen it.

**Comment by Fivell** [comment]
@amiuhle , it can wait. I will wait for your feedback

**Comment by amiuhle** [comment]
Finally had time to look into this, and setting the `download_links` helps.

`params[:action]` is a string, however, so comparing to a symbol doesn't work. Here's what works for me:

```ruby
index download_links: -> { params[:action] == 'show' ? [:pdf] : nil } do
  # ...
end
```

Thanks!

**Comment by Furqanameen** [comment]
@Fivell not downloading as like your given answer......
