### ISSUE TITLE
belongs_to polymorphic true not working

### ISSUE THREAD

**Issue by krtschmr** [activeadmin/activeadmin#4946]
```
class Something
  belongs_to :owner, required: true

   def owner
      owner_type&.constantize&.find(owner_id)
    end
end
```

Owner can be either a `User` or a `Team`

```

# admin
controller do
  belongs_to :owner, polymorphic: true
end
```

`/admin/something/1`throws me 
*Could not find param for polymorphic association. The request parameters are ["controller", "action"] and the polymorphic associations are [:owner].*
which comes from https://github.com/activeadmin/inherited_resources/blob/master/lib/inherited_resources/polymorphic_helpers.rb#L157

what am i doing wrong?

**Comment by Fivell** [comment]
@krtschmr , check comments here https://github.com/activeadmin/activeadmin/issues/221

**Comment by krtschmr** [comment]
@Fivell, i did. the conclussion is: 

```
# Models 
class Mod
  belongs_to :owner, required: true # either a User or a  Team
  def owner
    owner_type&.constantize&.find(owner_id)
  end
end 
class User; has_many :mods; end
class Team; has_many :mods; end
```

with this basic structure then i need to do the following in my admin
`mod.rb`, `team.rb`, `user.rb`do exist. 

my Mod indeed belongs_to an owner. i do register it via 

```
ActiveAdmin.register Mod do
  belongs_to :owner, polymorphic: true
end
```

as explained i do setup the routes
```

  namespace :admin do
    # workarounds
    # https://github.com/activeadmin/activeadmin/issues/221#issuecomment-10757256

    resources :users, only: [] do
      resources :mods
    end

    resources :teams, only: [] do
      resources :mods
    end
  end
```


that throws me 


```
ActiveAdmin::Resource::BelongsTo::TargetNotFound - Could not find Owner in admin with 
  [#<ActiveAdmin::Resource::Name:0x007f9cb0a9abd8 @name="Mod", @klass=Mod(id: integer, ... ), >, #<ActiveAdmin::Resource::Name:0x00000008e282d8 @name="User", @klass=User(id: integer, ..
```

either it's not working as expected or i am unable to read and understand :)

**Comment by krtschmr** [comment]
we do not need AA-magic for /users/mods and /teams/mods as we are making this for sure by ourself but if i don't have the `belongs_to` inside the controller then i get an `uninitialized constant Mod::Owner
`
