### ISSUE TITLE
Rails 5.1: Please remove gem 'meta_search' and try again.

### ISSUE THREAD

**Issue by widescape** [activeadmin/activeadmin#4947]
When running `bundle update` with Active Admin `v1.0.0` with Rails `v5.1.0.` Bundler reports the following error:

    $ bundle update
    Fetching https://github.com/appsignal/appsignal-ruby.git
    Fetching gem metadata from https://rubygems.org/...........
    Fetching version metadata from https://rubygems.org/..
    Fetching dependency metadata from https://rubygems.org/.
    Resolving dependencies..........................................................
    Your bundle requires gems that depend on each other, creating an infinite loop.
    Please remove gem 'meta_search' and try again.

Gemfile:

    source 'https://rubygems.org'
    ruby '2.3.1'
    gem 'activeadmin'
    gem 'rails'

When fixing the version numbers in the Gemfile to:

    gem 'activeadmin', '1.0.0'
    gem 'rails', '5.1.0'

… Bundler reveals the real issue:
**`inherited_resources` requires `rails < 5.1`**

    Bundler could not find compatible versions for gem "actionpack":
      In Gemfile:
        activeadmin (= 1.0.0) was resolved to 1.0.0, which depends on
          formtastic (~> 3.1) was resolved to 3.1.5, which depends on
            actionpack (>= 3.2.13)
    
        activeadmin (= 1.0.0) was resolved to 1.0.0, which depends on
          inherited_resources (~> 1.7) was resolved to 1.7.0, which depends on
            actionpack (< 5.1, >= 3.2)

There is already a pull request for `inherited_resources` to address this: https://github.com/activeadmin/inherited_resources/pull/433

**Comment by timoschilling** [comment]
No AA issue
