### ISSUE TITLE
Does ActiveAdmin supports Rails 5.1

### ISSUE THREAD

**Issue by ankitrg** [activeadmin/activeadmin#4949]
I am using Rails 5.1.0rc2 and everything worked fine. Now as Rails5.1 is out and I try to update my gem file I get the following error:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    activeadmin was resolved to 1.0.0, which depends on
      railties (< 5.2, >= 4.2)

    rails (~> 5.1) was resolved to 5.1.0, which depends on
      railties (= 5.1.0)

    activeadmin was resolved to 1.0.0, which depends on
      sass-rails was resolved to 6.0.0.beta1, which depends on
        railties (< 5.1, >= 4.0.0)

    webpacker was resolved to 1.2, which depends on
      railties (>= 4.2)
```

**Comment by Fivell** [comment]
https://github.com/rails/sass-rails/pull/400

**Comment by cintrzyk** [comment]
@ankitrg use `sass-rails` with `5.0.6` version instead of `6.0.0.beta1`

**Comment by varyonic** [comment]
Yes, but there are still one or two upstream issues that may require pulling dependencies from GitHub, see inherited_resources/issues/434

**Comment by krtschmr** [comment]
i hav 5.1 and `master` in current development. working fine so far.

**Comment by Fivell** [comment]
since activeadmin/demo.activeadmin.info#29 was merged, closing this
