### ISSUE TITLE
Active Admin Successful login redirect to User login page

### ISSUE THREAD

**Issue by shahzaibawan** [activeadmin/activeadmin#4956]
We are facing a issue in active admin successful login the issue is after successful login active admin redirect to user login page i.e _http://localhost:3000/users/sign_in_ . It was working fine earlier but all of sudden may be new update in active admin causing this issue because we have active admin in other projects too which were working fine until we update the gems with bundle and behaviour changed there too.  Any Suggestion ?

Thanks

**Comment by MariosY** [comment]
I checked the source code changes and the last commit was five days ago. Maybe the problem lies in any configuration changes to your rail app?

**Comment by varyonic** [comment]
Responded on [StackOverflow](http://stackoverflow.com/questions/43866091/active-admin-successful-login-redirect-to-user-login-page/43878977#43878977)
