### ISSUE TITLE
'review and confirm' feature

### ISSUE THREAD

**Issue by krtschmr** [activeadmin/activeadmin#4958]
```
ActiveAdmin.register VeryImportantThing do 
    config.create_needs_review = true
end

```

everytime, when a resource is created, we get a 'step' where we really need to confirm that we want to do exactly this.
very useful for important stuff. withdrawals, credits etc.
a simple `data-confirm` is often not enough.

we could just show the form and route it towards /confirm. we will call `valid?` there to catch any errors. if valid we show the confirmation where all the fields become hidden fields and we can display a table.

> Do you really want to do this and this? and display some values

we can specify the fields: 
`config.review_fields = [:amount, :currency, :bank_account]`

any suggestions?

**Comment by varyonic** [comment]
I suggest implementing for your project and writing a blog post.  I'll leave open for more feedback for now, but maybe this is better as a plugin.

**Comment by javierjulio** [comment]
Agree with @varyonic on trying it out. I think this is app specific rather than a concern for AA. Closing out.
