### ISSUE TITLE
Generate specific route for belongs_to association

### ISSUE THREAD

**Issue by mrstif** [activeadmin/activeadmin#4965]
I have the same resource being mentioned in two pages:

```
ActiveAdmin.register Project
ActiveAdmin.register Project, as: "Awesome Project"
```

The first one generates routes as `admin/projects` and the latter as `admin/awesome_projects`.

The issue comes when I have a belongs_to association:

```
ActiveAdmin.register Task do
  belongs_to :project
end
```

I would expect the routes generated for task are `admin/projects/:project_id/tasks`. Somehow this is not entirely true in an indeterministic way.

In my development and staging environments the routes are generated as I stated above but in my production environment they are generated as `admin/awesome_projects/:awesome_project_id/tasks`

**Is this scenario contemplated at all by ActiveAdmin and is there a way I can specify these routes in a deterministic way?**

I'm using Rails 4.2.7.1 with ActiveAdmin **1.0.0**

I created a stackoverflow question to this issue:
http://stackoverflow.com/questions/43998704/activeadmin-generating-wrong-routes-for-belongs-to-association

**Comment by varyonic** [comment]
Same as #4702?

**Comment by mrstif** [comment]
true @varyonic ... it's the same. closing this one
