### ISSUE TITLE
Rendering admin page within another page as a partial view

### ISSUE THREAD

**Issue by adaam2** [activeadmin/activeadmin#4966]
I am in the process of refactoring the UI of our admin area. I currently have a `Blah` model as well as tons of other related models relating to the `Blah` model such as `BlahConfiguration`, `BlahAnotherThing` etc. Each of these models has its own Active Admin page. The extraneous models are not necessarily linked to the main `Blah` model with an AR relationship. 

Ideally I'd like to move each one of these "child" pages into the main admin page for `Blah` (would be super cool to have each of these within a tab). Is there any way I can render the `BlahConfiguration` or `BlahAnotherThing` model as a partial view within my main `Blah` admin view, or by any other means customize the retrieval of these things to achieve what I'm trying to do without moving massive amounts of code around?

**Comment by varyonic** [comment]
You have two broad options to customizing ActiveAdmin: customizing resource pages and using custom  pages, both are covered well by the documentation.  Beyond that you need to familiarize yourself with the gem source code and the way views are composed with Arbre.  Arbre was conceived as an object oriented view layer and hence is open to extension, but perhaps not surprisingly many prefer to use Arbre's Rails integration to load partials: be sure not to confuse the two.  ActiveAdmin can be heavily customized with effort, but it is not a general purpose web framework, so you will have to figure out for yourself if it is worth it.  Follow up questions might be best on [StackOverflow](http://stackoverflow.com/questions/tagged/activeadmin)
