### ISSUE TITLE
.each inside row doesn't let you insert content

### ISSUE THREAD

**Issue by mashedkeyboard** [activeadmin/activeadmin#4967]
Within an attributes table in a show inside a resource, you can't use anything that returns inside a `.each`. I know how confusing that sounds from the way I've structured the sentence, but here's an example:

```
show do
  attributes_table do
    [blah]
    row :images do |resource|
      resource.images[0].url
    end
    [blah]
  end
end
```
-- outputs the url of images[0]

```
show do
  attributes_table do
    [blah]
    row :images do |resource|
      urls = []
      resource.images.each do |image|
        urls.append image.url
      end
    end
    [blah]
  end
end
```
-- outputs an array of urls of all the images in the resource

```
show do
  attributes_table do
    [blah]
    row :images do |resource|
      resource.images.each do |image|
        image_tag image.url
      end
    end
    [blah]
  end
end
```
-- outputs the default value (acts as if the `row :images` statement simply doesn't exist)

Extracting into a separate function in `ApplicationHelper` makes no difference.

Is this a bug? Is there any way of getting image tags for everything in resource.images into the table?

**Comment by varyonic** [comment]
Try [img](http://www.rubydoc.info/github/activeadmin/arbre/Arbre/HTML/Tag) instead of `image_tag`?

**Comment by mashedkeyboard** [comment]
Nope, no change.

Incidentally, just putting text doesn't output either:

```
show do
  attributes_table do
    [blah]
    row :images do |resource|
      resource.images.each do |image|
        'woot'
      end
    end
    [blah]
  end
end
```
-- outputs the default value (acts as if the row :images statement simply doesn't exist)

**Comment by workgena** [comment]
@mashedkeyboard , this should work:

```ruby
show do
  attributes_table do
    row :images do |resource|
      resource.images.each do |image|
        div do
          'woot'
        end # or text_node 'whoot'
      end
    end
  end
end
```

**Comment by mashedkeyboard** [comment]
@workgena Can confirm, for anyone else who's using CarrierWave and looking for a solution for this, this works:

```
row :images do |resource|
      resource.images.each do |image|
        div do
          image_tag image.url
        end
      end
      nil
end
```

Thanks guys, you do amazing work! Keep fighting the good fight :) When I have a moment (freelance work means that's quite rare, but I live in hope), I'll look into donating some time myself!

**Comment by scottbarrow** [comment]
Sorry to continue a closed thread, but this is a change that has affected recent versions of active admin. Prior to 1.1.0 the original object being enumerated was not returned from the block, and now it is, forcing you to write a nil return value. 
Is this by design or a potential bug?
