### ISSUE TITLE
undefined method `tagged_in' for Ransack::Search<class: User, base: Grouping <combinator: and>>:Ransack::Search

### ISSUE THREAD

**Issue by Erincom** [activeadmin/activeadmin#4968]
Hi,

I'm encountering the above error with Active Admin and specifically displaying the User model in the dashboard, which has a HMT relation that I've renamed (:tagged_in).

As a work around, I've done a remove_filter for this relation and when I do this, the dashboard displays the information about the User model.

Here is the code in the User model with the renamed relation:
`class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  has_many :comments
  has_many :posts
  has_many :user_posts
  has_many :tagged_in, :class_name => :Post, through: :user_posts, :foreign_key => "post_id", source: :post
  has_one :as_politician, :class_name => :UserAsPolitician, :foreign_key => "user_id"`

If you'd like more information, just let me know.

**Comment by Fivell** [comment]
@Erincom ,
>>As a work around, I've done a remove_filter for this relation and when I do this, the dashboard displays the information about the User model.

Can you show your AA code ?

**Comment by Erincom** [comment]
@Fivell, here is my **app/admin/dashboard.rb**:

`ActiveAdmin.register_page "Dashboard" do
  menu priority: 1, label: proc{ I18n.t("active_admin.dashboard") }
  content title: proc{ I18n.t("active_admin.dashboard") } do
    div class: "blank_slate_container", id: "dashboard_default_message" do
      span class: "blank_slate" do
        span I18n.t("active_admin.dashboard_welcome.welcome")
        small I18n.t("active_admin.dashboard_welcome.call_to_action")
      end
    end
end
end`


**app/admin/user.rb**:

`ActiveAdmin.register User do
permit_params :first_name, :last_name, :email, :address, :city, :neighbourhood, :admin

remove_filter :tagged_in

index do
    selectable_column
    column :id
    column :email
    column :first_name
    column :last_name
    column :address
    column :city
    column :neighbourhood
    column :last_sign_in_at
    column :created_at
    column :admin
    actions
end

form do |f|
    f.inputs "Identity" do
      f.input :first_name
      f.input :last_name
      f.input :email
      f.input :address
      f.input :city
      f.input :neighbourhood
    end
    f.inputs "Admin" do
      f.input :admin
    end
    f.actions
  end

end`

**Comment by Fivell** [comment]
@Erincom , can you please check if it works if you rename  association to 

```
has_many :tagged_in_posts
```

**Comment by javierjulio** [comment]
@Erincom were you able to try @Fivell's suggestion? Did you fix the issue?

**Comment by varyonic** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or reopen this issue. Thanks!
