### ISSUE TITLE
Can I replace Arbre to ERB?

### ISSUE THREAD

**Issue by nardonykolyszyn** [activeadmin/activeadmin#4969]
I would wish change from Arbre to something more natural with erb. There are any solution for this?

**Comment by varyonic** [comment]
Not entirely, no.  You can [render a partial at any point](https://activeadmin.info/6-show-pages.html).  You can also use ERB partials for [forms](https://activeadmin.info/5-forms.html#partials).  Arbre is baked into Active Admin and unlikely to be fully replaced soon.
