### ISSUE TITLE
Showing totals as a column in CSV export

### ISSUE THREAD

**Issue by mrmanishs** [activeadmin/activeadmin#4971]
I am currently running the following query:

results = Metric.select("a, b, count(*) as tot").group("a,b")

The results are good and it processes fine for my columns in my csv do:

csv do
....
         column("A"){ |metrics| metrics.a} 
         column("B"){ |metrics| metrics.b}
...
end

However, how do I also get totals in? 
Similar to: 
      column("Totals"){|metrics|metric.tot} does not work.  

It throws an error:
 undefined method `tot' for #<Metric:0x007fec294405d0>

**Comment by varyonic** [comment]
Define a tot method on Metric or create and use a Metric decorator.  Please post follow up help questions to [StackOverflow](https://stackoverflow.com/questions/tagged/activeadmin)

**Comment by varyonic** [comment]
I'm not clear why you are calling `group` here, maybe a [view backed model](https://dan.chak.org/enterprise-rails/chapter-11-view-backed-models/) is what you are looking for.  Please post follow up help questions to [StackOverflow](https://stackoverflow.com/questions/tagged/activeadmin)
