### ISSUE TITLE
gem spree_price_books is not compatible  for  rails 5

### ISSUE THREAD

**Issue by ajayyuvasoft141** [activeadmin/activeadmin#4973]
Spree price_books_books is not wroking with rails 5. I am getting such types issues-
Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 3.2.1)

  In Gemfile:
    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree_price_books was resolved to 2.3.0.beta, which depends on
      spree_core (~> 2.3.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

 Please Help  me. How Can i fixed this issues.

**Comment by timoschilling** [comment]
This issue is not active admin related

**Comment by ajayyuvasoft141** [comment]
Only i am asking.  spree_price_books  gem is working with rails 5 or not.

**Comment by varyonic** [comment]
Try https://github.com/spree-contrib/spree_price_books/issues
