### ISSUE TITLE
Compatible spree_price_books version for rails 5.0.0 

### ISSUE THREAD

**Issue by ajayyuvasoft141** [activeadmin/activeadmin#4974]
Hi
I installed spree application with rails version 5.0.0 just now,  And I used gem spree_price_books but It is not compatible with it.
Here what i get when i run bundle install :

Bundler could not find compatible versions for gem "spree_core":
  In snapshot (Gemfile.lock):
    spree_core (= 3.2.1)

  In Gemfile:
    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree (~> 3.2.0) was resolved to 3.2.1, which depends on
      spree_core (= 3.2.1)

    spree_price_books was resolved to 2.3.0.beta, which depends on
      spree_core (~> 2.3.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Please help me.

**Comment by timoschilling** [comment]
As I told you in https://github.com/activeadmin/activeadmin/issues/4973, you have a problem with spree and noch active admin.
