### ISSUE TITLE
global level setting belongs_to (required: true) of rails 5 does not work once active admin gem is included.

### ISSUE THREAD

**Issue by aashishgarg** [activeadmin/activeadmin#4975]
### Expected behavior

Rails 5 global setting  - 
Rails.application.config.active_record.belongs_to_required_by_default = true
in app -> config -> initializers -> new_framework_defaults.rb
should work.

### Actual behavior

Once activeadmin gem is included, this global setting stops working.

### How to reproduce

1. Create a new rails app and create two models(user, post) with has_many and belongs_to association(User has_many posts, post belongs_to user).
2. Now try to create post without user. It shows error - User is required.
3. Now add activeadmin gem in gemfile and bundle it.
Confirm  - 
Rails.application.config.active_record.belongs_to_required_by_default = true
in app -> config -> initializers -> new_framework_defaults.rb

4. Now try to create post without user. It allows to create post.
Which is changing the rails 5 behavior throughout the application.

**Comment by aashishgarg** [comment]
Yes

**Comment by varyonic** [comment]
Try `config.active_record.belongs_to_required_by_default = true`

**Comment by deivid-rodriguez** [comment]
@aashishgarg I just tried to reproduce this following your steps and confirmed this works as expected. I'm going to close this but feel free to reopen providing a sample application where this can be reproduced. Thanks!
