### ISSUE TITLE
Active admin ignoring .limit() in scopes

### ISSUE THREAD

**Issue by concept47** [activeadmin/activeadmin#4977]
Say I have a scope like this on my Active Record model
  
    scope :test, -> {  where(arel_table[:created_at].gteq 30.days.ago) }

which returns 5 records

and one like this

     scope :test_limit, -> {  where(arel_table[:created_at].gteq 30.days.ago).limit(1) }

And I change the default scope on my Active Admin record  from

     scope :test, default: true

to 

    scope :test_limit, default: true

### Expected behavior

Active Admin should go from displaying 5 records to only displaying 1 record when I change the scope from :test to :test_limit

### Actual behavior

Active admin keeps on displaying 5 records even with the explicit scope limiting it to 1 but, the count in the scope tab displays 1

### How to reproduce

See above. Also just add `.limit(1)` to any of your Model scopes that you are referencing in Active admin. The tab will say (1) but it will display all the records up to the page limit

**Comment by Fivell** [comment]
@concept47 , see related PR with example how it can work
