### ISSUE TITLE
[Suggestion] Using Ant.Design for enterprise-class administration

### ISSUE THREAD

**Issue by TangMonk** [activeadmin/activeadmin#4982]
I am a React and Rails developer, And I love ActiveAdmin too.

Here are some high-quality awesome React Components for enterprise-class administration in [Ant.Design](https://ant.design)

There are many big china company using it:

- Ant Financial
- Alibaba
- Koubei
- Meituan
- Didi

screenshots:

[Button](https://ant.design/components/button/):

![image](https://cloud.githubusercontent.com/assets/3498786/26750580/60c68a96-4859-11e7-93e5-a524e8b08c62.png)

[Breadcurmb](https://ant.design/components/breadcrumb/)

![image](https://cloud.githubusercontent.com/assets/3498786/26750591/8c4f835c-4859-11e7-9ef0-9bf632c7796f.png)

[Menus](https://ant.design/components/menu/)

![image](https://cloud.githubusercontent.com/assets/3498786/26750603/de7087ee-4859-11e7-861e-b00a009430a9.png)

[Step](https://ant.design/components/steps/)

![image](https://cloud.githubusercontent.com/assets/3498786/26750613/fa0a93d2-4859-11e7-9ccb-5ceda840833b.png)

[Tabs](https://ant.design/components/tabs/)

![image](https://cloud.githubusercontent.com/assets/3498786/26750617/0b0c72ea-485a-11e7-884c-dce081a2f687.png)

[auto-complete](https://ant.design/components/auto-complete/)
![image](https://cloud.githubusercontent.com/assets/3498786/26750622/3511c31a-485a-11e7-87eb-8b4eacaac94f.png)

[cascader](https://ant.design/components/cascader/)

![image](https://cloud.githubusercontent.com/assets/3498786/26750626/463946d6-485a-11e7-860e-08bc302940d5.png)

[data picker](https://ant.design/components/date-picker/)
![image](https://cloud.githubusercontent.com/assets/3498786/26750630/5f3f0670-485a-11e7-955a-71279340f551.png)

and so on...

there are some [online showcase](https://github.com/ant-design/ant-design/issues/477)

You should [take a look and try your self ](https://ant.design/docs/react/introduce)

Currently, Rails 5.1 support React [in internal](http://weblog.rubyonrails.org/2016/12/10/this-week-in-rails-yarn-webpack-bigint-pks-and-more/)

I am planning to create a theme for it, But I have job, and It is heavy workload for me, I hope active admin team think about it

**Comment by varyonic** [comment]
You are welcome to create a theme.  Take a look at this one for [Bootstrap](https://github.com/vinhnglx/active_bootstrap_skin) or this one inspired by [Google Material Design](https://github.com/vigetlabs/active_material) or maybe [this one](https://github.com/Papercloud/flattened_active_admin) is closer to the Ant Design aesthetic.  As to React I am looking for blog posts or sample apps that use React for custom pages or indexes, but so far the only article I have seen is [this popular tutorial](https://medium.com/superhighfives/a-top-shelf-web-stack-rails-5-api-activeadmin-create-react-app-de5481b7ec0b).  If you want to see ActiveAdmin use Ant.Design or React get involved and make it happen.
