### ISSUE TITLE
Citext not searchable

### ISSUE THREAD

**Issue by casiodk** [activeadmin/activeadmin#5000]
### Expected behavior

When I have a postgres citext field in my db, I expect to be able to filter on that field same as an ordinary text field

### Actual behavior

ActiveAdmin.register User do
  filter :name
  filter :uuid

When I do this, uuid field does not even show up on my index page

### How to reproduce
create a citext column and add a filter like above
http://nandovieira.com/using-insensitive-case-columns-in-postgresql-with-citext

**Comment by Fivell** [comment]
@casiodk , AA skips filter if filter object can't be found. 
Can you try
```
filter :name, as: :string
```

**Comment by casiodk** [comment]
yes! its working, thanks a lot
