### ISSUE TITLE
Authorizing a new resource

### ISSUE THREAD

**Issue by machty** [activeadmin/activeadmin#5002]
I'm using CanCanCan for authorization and I'm running up against an awkward corner case for authorizing an unsaved resource.

Here's the setup: AdminUser has_many Locations. Locations has_many Deals. I'm using CanCanCan to specify that an AdminUser can manage Deals, but only for the Locations that belong to the AdminUser:

```ruby
      can :manage, Deal, { locations: { admin_user_id: admin_user.id } }
```

Everything "works" about this setup, but one awkward pain point with AA is that when I click "New Deal", I immediately get redirected back with a "You don't have access to this resource" auth error, which is caused by the fact that AA is trying to authorize that the user can manage `Deal.new`, which hasn't had its `location` set.

Now, I _could_ use an `after_build` callback (or some other means) to set a `location` so that AA will properly authorize this unsaved Deal, but it would mean arbitrarily selecting one of the many valid Locations, and hence the Locations dropdown in the form will already be pre-populated with a location, which is a hazard since, to the user, it looks like that field already has a meaningful value set.

### Expected behavior

AA's auth adapter might be smart enough to detect such cases when authorizing unsaved resources.

### Actual behavior

I have to arbitrarily choose a value among many possible valid values, which is a UX hazard.

### How to reproduce

See above.

**Comment by Fivell** [comment]
@macarthy , why not to skip authorizing new action in this case?

**Comment by machty** [comment]
@Fivell what API can I use to selectively skip authorization (via auth adapter) for a specific action?

**Comment by Fivell** [comment]
@machty ,
```ruby
controller do
   def authorize_resource!(resource)
        #skip authorization on new action
        super unless params[:action] == 'new'
    end
end


```

**Comment by machty** [comment]
That works, but then I have the problem where if someone leaves the Location blank on create, they hit an authorization error rather than a validation error.

I'm sure there are workarounds but I'm sharing this issue as food for thought that perhaps the auth vs validation story isn't totally fleshed out. I don't yet have a great idea as to how to address it but perhaps something along the lines of "don't authorize unsaved resource instances (only their classes) until they're about to be saved, at which point a failed authorization is treated as a validation error"

**Comment by Fivell** [comment]
@machty , I'm not sure a lot can be changed in how authorisation adapters work in ActiveAdmin, also your case is very specific, and actually I never used such nested authorization rules even within app without ActiveAdmin. Anyway, ActiveAdmin provides you a lot of base functionality out of the box , but it can not handle all the cases in each application automatically. I might not agree  this is bug in ActiveAdmin, so my proposal for you is ask on stackoverflow for workaround or for another way to solve your issue. 
But If you have any ideas of clean implementation that solve your problem using ActiveAdmin, feel free to contribute.
