### ISSUE TITLE
active admin has overridden whole MAC computer css: SOS

### ISSUE THREAD

**Issue by ayazahmadtarar-pikessoft** [activeadmin/activeadmin#5008]
I used active admin and generated assets. but it messed with my whole theme i ma unable to use bootstrap classes. I moved the js and css to vendor but still not working . 

I am unable to use javascript in any of project in my laptop
In every project my menu look like . I have to deliver project in few days
<img width="1237" alt="screen shot 2017-06-15 at 1 46 50 am" src="https://user-images.githubusercontent.com/23359792/27153915-9767811a-516c-11e7-9ad7-c8a23db46761.png">

**Comment by varyonic** [comment]
You should not need to move activeadmin assets to vendor.  Bootstrap is [not supported](https://stackoverflow.com/questions/17690103/reskinning-activeadmin-using-bootstrap).
