### ISSUE TITLE
humanize_name option for csv DSL columns

### ISSUE THREAD

**Issue by megatux** [activeadmin/activeadmin#5010]
feature requests, I think. I would like the _humanize_name_ on the *csv* DSL (for all columns on a resource). Tried this:
`csv humanize_name: false do`
but it is throwing an "ArgumentError at /admin/processing_orders.csv Unknown options:  humanize_name" error.
I thought that pull #3145 added that.
Using 607054214d4eaba5b59e2eab736c6a41edfc7795 revision, btw.

**Comment by Fivell** [comment]
@megatux , yes this feature was added however looks like it worked never

**Comment by varyonic** [comment]
I remember #3145 fixing #2771, which was a pain.
