### ISSUE TITLE
BUNDLE_GEMFILE not set by default

### ISSUE THREAD

**Issue by wesley6j** [activeadmin/activeadmin#5018]
The [document](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md) says  `This will automatically run the tests against Rails 5.0` but it does not seem to work?

**Comment by deivid-rodriguez** [comment]
The document is outdated, it should be against 5.1. But it should work I think. It's set [here](https://github.com/activeadmin/activeadmin/blob/ced57fd41e5501f98612050ad0b58006e7fc19be/Rakefile#L4-L13). What problem are you having?

**Comment by deivid-rodriguez** [comment]
Ooops, I just checked. `bundle exec rake` works, but `bundle exec rake test` does not! I'll fix it!

**Comment by wesley6j** [comment]
For `bundle install` to work, I have to set env `export BUNDLE_GEMFILE=gemfiles/rails_51.gemfile`. And I tried to see where the auto-set-gemfile magic happens by searching `rails_51` in the project, but could not find anything relevant.

**Comment by deivid-rodriguez** [comment]
I fixed one problem in #5020, but he task would need to run `bundle install` automatically the first time it is run to properly work... I'll fix it too.

**Comment by wesley6j** [comment]
Found `gemfile_path = File.expand_path('../gemfiles/rails_51.gemfile', __FILE__)` in Rakefile.

So as you mentioned, `bundle exec rake` works if user has already install the gems.

**Comment by wesley6j** [comment]
Thanks. I would suggest to make setting `BUNDLE_GEMFILE` the first step before bundle install to be explicit.

**Comment by wesley6j** [comment]
Without this env, some gems won't be updated: `bundle install | grep rails`
```
Using jslint_on_rails 1.1.1
Using rails-dom-testing 2.0.3
Using rails-html-sanitizer 1.0.3
Using cucumber-rails 1.5.0 from https://github.com/cucumber/cucumber-rails.git (at master@302fa3b)
Using rails-i18n 5.0.4
Using rspec-rails 3.6.0
```
rails is missing here.

**Comment by deivid-rodriguez** [comment]
Yes, the main `Gemfile` contains only the gems common to all Rails versions, but the `rails` gems themselves are in `gemfiles/rails_*.gemfile`.
