### ISSUE TITLE
How to create a expandable  row

### ISSUE THREAD

**Issue by wuqinggengjueqing** [activeadmin/activeadmin#5023]
### Expected behavior

I'm writing a shopping application to practice ruby on rails, and using active admin.
Now, I want to the index page of order can display  order and order_item in the same row. You know! One order usually contains multiple order_item. So, I want let order_item show under of itself parent order and can expand or fold. How  should I do?
### Actual behavior
I see the doc files, but I can not find any description about this!

**Comment by Fivell** [comment]
@wuqinggengjueqing , https://activeadmin.info/3-index-pages.html
