### ISSUE TITLE
Upgrade default to jQuery v3

### ISSUE THREAD

**Issue by javierjulio** [activeadmin/activeadmin#5047]
We are still running the admin on jQuery v1 so lets upgrade to v3 and see what happens.

**Comment by varyonic** [comment]
Duplicates #4915

**Comment by javierjulio** [comment]
I'm not so sure this is much of a breaking change. If anything users are baffled as to how we are still on jQuery v1. With approving #4682 and doing more testing, what do we think about getting this out as part of 1.1? Might be better to get earlier feedback rather than later. What do you think @Fivell, @deivid-rodriguez?

**Comment by Fivell** [comment]
@javierjulio , I think you can merge that one and open new pr with jquery v3. let's see

**Comment by javierjulio** [comment]
With @deivid-rodriguez's help this is changing a little bit so it seems we can get this out on v1.1. All code changes being done in #5052.
