### ISSUE TITLE
Look into rewriting JS as ES6 and drop CoffeeScript

### ISSUE THREAD

**Issue by javierjulio** [activeadmin/activeadmin#5050]
JS has come a long way now and other major gems like foundation-rails use ES6 code via sprockets-es6 gem. Something to give a try and see how it works out.

**Comment by varyonic** [comment]
Could have reopened #4414?

**Comment by varyonic** [comment]
There are tools now to convert coffeescript -> es6, eg. [decaffeinate-project](http://decaffeinate-project.org/repl/).  Sprockets 4.x has babel-transpiler, see [UPGRADING]( https://github.com/rails/sprockets/blob/master/UPGRADING.md) or webpacker [supports Rails 4.2+](https://github.com/rails/webpacker)

**Comment by javierjulio** [comment]
We should change our sprockets dependency to be '>= 3.0'. We will be covered there as Rails 4.2 worked with Sprockets 3 and up. We can use sprockets-es6 which has the babel-transpiler with sprockets 3. Unless we want to start requiring v4? If we do this for AA v2 we could just up the minimum to sprockets v4 but perhaps we can do this rewrite as AA v1.x since it will work without breakage?

**Comment by varyonic** [comment]
Requiring 3.x for 1.1 sounds good to me.

**Comment by javierjulio** [comment]
I'm not concerned with sprockets-es6 because its being used already. I use it in production through foundation-rails for more than a year now and it hasn't given me any issues other than a deprecation warning I helped fix. I think it'll be an ok choice for now until better support for sprockets v4 comes out (sass-rails v6 needs to be released since it requires sprockets v3).
