### ISSUE TITLE
ActiveAdmin - Google_visualr conflicts?

### ISSUE THREAD

**Issue by dhock194** [activeadmin/activeadmin#5067]
I build an app leveraging ActiveAdmin to manage the backend for authentication. Everything working for ActiceAdmin/Devise, and the app as is works great. However, I also wanted to use a gem I have used previously for Google charts (google_visualr), but when I add this to the Gemfile ( + bundle install) and restart puma for test, I get the following error. Simple commenting out in the Gemfile eliminates the issue. Looks like possibly Devise and google_visualr have conflicting helper methods?

google_visualr/app/helpers/view_helper.rb:7:in block in <module:ViewHelper>': undefined methodhelper_method' for ActionController::API:Class (NoMethodError)

Has anyone run into this, might know of a resolution or workaround for this?

**also posted in the google_visualr issues page (https://github.com/winston/google_visualr/issues/114#issuecomment-312557311)

**Comment by deivid-rodriguez** [comment]
Based on https://github.com/activeadmin/activeadmin/issues/5022 and its resolution, what happens if you go to the file where the crash happens and add the following change:

```diff
-        # Rails 5 compatibility fix
-        if respond_to?(:helper_method)
-          helper_method "render_chart"
-        end
+       ::ActionController::Base.helper_method "render_chart"
```

Does it fix the problem?

**Comment by dhock194** [comment]
I was able to test this, and this addressed the issue perfectly. Thanks again!

**Comment by javierjulio** [comment]
@dhock194 thanks for the heads up! @deivid-rodriguez is the solution anything we need to worry about internally too?

**Comment by deivid-rodriguez** [comment]
Nope, the OP should file a PR to `google_visualr`.
