### ISSUE TITLE
undefined method `login'

### ISSUE THREAD

**Issue by Dnnecessary** [activeadmin/activeadmin#5071]
我是用 devise 和 activeadmin 。 在 Genfile 添加了
`gem 'activeadmin'

# Plus integrations with:
gem 'devise'
gem 'cancan' # or cancan`

`rails g active_admin:install`

`rake db:migrate
rake db:seed
rails server`
在 访问 127.0.0.1:3000/admin  就报错了

**Comment by babyhai** [comment]
![image](https://user-images.githubusercontent.com/22759331/27944193-d43a061e-6317-11e7-9f24-2795b16d23ce.png)

**Comment by varyonic** [comment]
Were you able to resolve this?
