### ISSUE TITLE
When upgrading to current master, the JSON request for GET no longer works for admin resources

### ISSUE THREAD

**Issue by jancel** [activeadmin/activeadmin#5080]
### Expected behavior

What do you think should happen?

Rails 4.2, Active Admin 1.0 @ Master, June 1st. (Rev. adcc7e379d1a3f2fab478f0b5c4d11af1bf488ea)

When making a request to http://myresource.com/admin/titles the application shows you the titles in html and index view for titles. Once upgraded to master, it no longer works with a route as http://myresource.com/admin/titles.json (with an authenticated admin user) to return a json list of titles. 

In migration docs, I was unable to find this change.  

### Actual behavior

What actually happens?

 It presents as "Unauthorized".  

### How to reproduce

Create a new rails app and set up activeadmin.  Migrate at least one field and create the admin interface.  Browse to the index view and then add .json to the route.

**Comment by javierjulio** [comment]
Wow, I had no idea this was possible but then because of inherited_resources maybe it enables HTML and JSON by default? I hit an admin I have that is running on master and it works fine. It actually returns JSON for all records for that resource. Crazy.

**Comment by jancel** [comment]
I'm updating to latest to see if I can't get a different result. I tried it with a rails 5 app and it worked like a charm.

**Comment by jancel** [comment]
May be related to: 

Security Fixes

Prevents access to formats that the user not permitted to see #4867 by @Fivell and @timoschilling

**Comment by jancel** [comment]
I was able to fix it by enabling json download format in the initializer. Not great because now users see it, but this is a quick fix.

```
      admin.download_links = [:csv, :json]
```

**Comment by Fivell** [comment]
@jancel root is here
https://github.com/activeadmin/activeadmin/blob/9cffa4a8113405a6fb0a73b9ec725a1d55ed039a/lib/active_admin/resource_controller.rb#L62

Leave it only of :index 

can you make pr ?

**Comment by Fivell** [comment]
@jancel you want json export works but only link to be hidden ?

**Comment by jancel** [comment]
That would be reasonable.  JSON to work without a link. I'll take a look at this tomorrow AM.

**Comment by jungbunzlav** [comment]
Is the `restrict_format_access!` method the reason why I can't use the `pdf` format anymore?

```
      respond_to do |format|
        format.html
        format.pdf do
          render(
            pdf: "invoice",
            layout: "pdf",
            template: "invoice.html.haml",
            disposition: "attachment",
          )
        end
      end
```

**Comment by Fivell** [comment]
@jungbunzlav looks like we should rethink this behaviour, that changes were made to  #3539,

maybe we should make configuration with  whitelist of formats on namespace/resource level 

like 
```
config.white_list_formats = [:json, :pdf]
```

**Comment by Fivell** [comment]
@jungbunzlav, try this workaround for now 
```
  skip_before_action :restrict_format_access!, only: [:show]
```
