### ISSUE TITLE
Add link to formtastic documentation

### ISSUE THREAD

**Issue by iamkhaya** [activeadmin/activeadmin#5082]
The current documentation on forms recommends that the reader "see the Formtastic documentation for more details". It would be useful to have a link to the mentioned documentation.

### Expected behavior
Add a link to Formtastic's wiki.
```
For more details, please see [Formtastic's documentation](https://github.com/justinfrench/formtastic/wiki).
```
### Actual behavior
The documentation on forms currently has this
```
For more details, please see Formtastic's documentation.
```

### How to reproduce

See the current file [here](https://github.com/activeadmin/activeadmin/blob/master/docs/5-forms.md)

**Comment by iamkhaya** [comment]
I have a branch for this issue, but I get a Permission error when I try and push to it.

**Comment by varyonic** [comment]
Use the branch to [open a PR](https://help.github.com/articles/creating-a-pull-request/)
