### ISSUE TITLE
Dashboard name has not been changed

### ISSUE THREAD

**Issue by hussainakram** [activeadmin/activeadmin#5085]
I tried to change the name Dashboard to "Insights", for this I had to change routes path and title of previous dashboard to 'Insights' and also the file name to insights.rb. It worked but the name on navbar tab is being shown as **translating missing: en active_admin.insights** not as **insights**. I'm using activeskin with it. Have I missed something?
<img width="544" alt="insights" src="https://user-images.githubusercontent.com/20062423/28269827-d4cfd7b8-6b1c-11e7-9878-296d38ea4feb.png">

**Comment by javierjulio** [comment]
@hussainakram do you have that translation defined? If not you will need it because I see the generated dashboard template includes the following:

```ruby
menu priority: 1, label: proc{ I18n.t("active_admin.dashboard") }
```

If you changed that to "insights" keep in mind, you'll have to add that entry to the actual translations file.

**Comment by javierjulio** [comment]
I haven't heard back but my response should get it working just fine. If you still have problems let us know! Thanks!
