### ISSUE TITLE
Using paginated collection for embedded lists produces unusable download links

### ISSUE THREAD

**Issue by urkle** [activeadmin/activeadmin#5090]
### Expected behavior

What do you think should happen?

CSV/XML/JSON download links that go to the paginated lists not the main resource

### Actual behavior

What actually happens?

The CSV/XML/JSON links download the main resource being viewed.

### How to reproduce
```ruby
show do
    panel 'Sprocket buyers' do
      paginated_collection(sprocket.buyers.order('created_at desc').page(params[:sprocket_buyers_page]).per(15), param_name: 'sprocket_buyers_page') do
        table_for collection do
          column :buyer_name
          column :purchase_date
          column :quantity
          column :price
        end
      end
    end
end
```

The download links end up being  /admin/sprockets/1.json, etc..   instead of something that will give me the list of associated buyers to the sprocket..  e.g.  /admin/buyers.json?q[sprocket_id_eq]=1

**Comment by Fivell** [comment]
@urkle , download links always use current request path to build links.

https://github.com/activeadmin/activeadmin/blob/7461a55e8c367cb6546c96ed7bfb90c952da2eb5/lib/active_admin/view_helpers/download_format_links_helper.rb#L21

Pr are welcome for this feature

**Comment by leonardoprg** [comment]
Hey guys, please follow 

https://github.com/activeadmin/activeadmin/pull/5128

**Comment by sposinff** [comment]
Would love for this to be resolved. 
However, until this is resolved, to avoid confusing our users, I am going to pass the option to hide the links.
```paginated_collection(resource.parents, download_links: false) do```
Another option is to create dynamic scopes
```
ActiveAdmin.register Product do
  Store.all.each do |store|
    scope("#{store.name}") { |scope| scope.where(store_id: store.id) }
  end
end
```

**Comment by javierjulio** [comment]
This is a PR ready for this. Thank you.
