### ISSUE TITLE
Generator broken

### ISSUE THREAD

**Issue by elbarto132** [activeadmin/activeadmin#5097]
https://activeadmin.info/0-installation.html
Create a new rails project (Ruby 2.4.1, Rails 5.1.2)

Add this to gemfile:
gem 'activeadmin'
gem 'devise'

Run: bundle install
Run: rails g active_admin:install

/Users/elbarto132/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.2/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined method `devise' for AdminUser (call 'AdminUser.connection' to establish a connection):Class (NoMethodError)

**Comment by gbirchmeier** [comment]
I wish you'd specified what other code was causing the problem, because I'm running into this very same issue.

**Comment by gbirchmeier** [comment]
I ran into this same issue.

In my case, seems the problem was caused by having `rails server` running in the background.  I killed the server, then reverted the generator's output, and then ran the generator again and it worked.
