### ISSUE TITLE
Filters on string with multiple choice always use default value

### ISSUE THREAD

**Issue by ArnaudRemi** [activeadmin/activeadmin#5102]
When I use a filter with multiple choice (:contains, :starts_with, :ends_with) I could select a choice and search with it.
The default multiple choice has a default value, by example :contains.

`filter :title, filters: [:contains, :starts_with, :ends_with]`

When I want to select a filter value which is not the default value, by example :starts_with, the search is done with :contains.

I can see in the URL that the search is made with :contains. If I change the search filter directly in the URL it works normally.

**Comment by kxhitiz** [comment]
Looks like this issue has been here for quite a while. I am having the same issue now with the filter. Would appreciate if anyone can share their workaround for this specific issue?

**Comment by lautarol** [comment]
I'm also reproducing this issue

**Comment by javierjulio** [comment]
I'm not able to reproduce this.
