### ISSUE TITLE
[proposal] add opportunity to add a form to resource's sidebar

### ISSUE THREAD

**Issue by alex-bogomolov** [activeadmin/activeadmin#5108]
Recently a client asked if it is possible to add a form to the index page of resource. It would simplify the process of adding entries with a small amount of columns to the project without the need to click "Add new entry", fill the form, click "Save" and then return back to the index page.

I searched for this feature and realized that it's missing. So I suggest to add the following DSL to the resource:
```ruby
sidebar_form do |f|
   # ...
end
```
This DSL will generate a form in the sidebar section under the filters. When a user fills the form and clicks "Create", if the filled values are valid, the entry will be created and he will be redirected back to index page. If the values are not valid, the `new` action will be rendered.

I think this feature should be added to the project, because it will reduce amount of repetitive actions to do when adding a lot of entities and will improve the usability of ActiveAdmin.

**Comment by varyonic** [comment]
FYI HE:labs wrote up a ['quick add' feature using fancybox](https://helabs.com/artigos/2014/05/28/quick-add-and-quick-edit-on-active-admin/) that may be of interest to others. I see your PR was closed after some discussion. I think this might make a good [plugin](https://github.com/activeadmin/activeadmin/wiki/Plugins).
