### ISSUE TITLE
[kaminari] undefined method display_tag

### ISSUE THREAD

**Issue by gingray** [activeadmin/activeadmin#5111]
Got the following issue
```
ActionView::Template::Error: undefined method `display_tag?' for #<Kaminari::Helpers::Paginator::PageProxy
```
If you're on Rails 5 and update to kaminari 0.17 you can probably get this error.

Solution:
This commit will solve the issue https://github.com/kaminari/kaminari/commit/e95bb74abba741299df3ed4bde2dba91d5313936

```
gem 'kaminari', github: 'kaminari/kaminari', ref: 'e95bb74'
```
I think it will be helpful for activeadmin users maybe we need to handle this on activeadmin side to explicitly include 'kaminari/core' but I'm not sure.

**Comment by javierjulio** [comment]
@gingray this isn't an issue that ActiveAdmin should fix since all you have to do is update Kaminari. They includes a lot of fixes in the next version which was 1.0. Just run `bundle update kaminari` and you'll be good.

**Comment by senid231** [comment]
face it with rails 4.2.8 and activeadmin 1.1.0

every page with pagination raises same error for kaminari 0.15.0 and 0.17.0 
for kaminari >= 1.0.0 looks fine

proposal: change kaminari dependency from `kaminari (>= 0.15, < 2.0)` to `kaminari (>= 1.0.0, < 2.0)`

**Comment by senid231** [comment]
@Fivell what do you think?
