### ISSUE TITLE
Apartment Gem and CSV Streaming Downloads

### ISSUE THREAD

**Issue by rylanb** [activeadmin/activeadmin#5115]
### Expected behavior
When I click the csv download link in the admin, the CSV would be for the current tenant's Postgres schema based on subdomain switching in Rack Middleware.

### Actual behavior
CSV streaming ignores the subdomain tenant schema set by Apartment in Rack Middleware and goes to the root / public schema and gives a tenant access to public schema data.

### How to reproduce
Install Apartment.
Use Subdomain or GenericElevator configuration.

Something like: 

```
require 'apartment/elevators/generic'

class ClientElevator < Apartment::Elevators::Generic

  # @return {String} - The tenant to switch to
  # request is an instance of Rack::Request
  def parse_tenant_name(request)

    domain_or_client_code = subdomain(request.host)

    # Default is public for base client
    # They will also be able to manage new clients.
    if domain_or_client_code.nil?
      client_code = request["HTTP_CLIENT_ID"] || '1111'
      client = Client.find_by(client_code: client_code)
    else
      client = Client.where('subdomain = ? or client_code = ?', domain_or_client_code, domain_or_client_code).first
    end

    tenant_name = client.schema_name

    return tenant_name
  end

  protected
  # Only care about the first subdomain for the database name
  def subdomain(host)
    subdomains(host).first
  end

  def subdomains(host)
    return [] unless named_host?(host)

    host.split('.')[0..-(Apartment.tld_length + 2)]
  end

  def named_host?(host)
    !(host.nil? || /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.match(host))
  end
end

```

In application.rb

`Rails.application.config.middleware.insert_before 'Warden::Manager', 'ClientElevator'`

_Note: I think you could do this with any sort of elevator, but I included my custom one just to be safe_

**Comment by macfanatic** [comment]
Did you ever find a way around this @rylanb?  We're using `acts_as_tenant` and have the same issue.

I believe that the block from `CSVBuilder` passed to the `Enumerator` to enable streaming is not run within the block with a tenant set, leading to unscoped queries.  Only have this issue in production as well, not in development.

**Comment by macfanatic** [comment]
I ended up solving this by using a branched version of the [RequestStore](https://github.com/steveklabnik/request_store) library, which how `ActsAsTenant` stores the current tentant during a request.  `RequestStore` cleared the thread variables when the controller began streaming, and since the block is lazily evaluated for each record on the CSV export, the contents weren't scoped once it began rendering.

The simplest solution would be to just disable CSV streaming in ActiveAdmin, or to keep that functionality and use what appears to be a fixed `RequestStore`, add to your `Gemfile`.

```ruby
# Fixes CSV streaming losing the ActsAsTenant current_tenant
gem 'request_store', github: 'aasmith/request_store', ref: '0fa2c76f66616ee472c2c4da9cf87582a6f01a54'
```

There is an open PR for this, but doesn't appear it's going to be merged ever: https://github.com/steveklabnik/request_store/pull/52

**Comment by rylanb** [comment]
@macfanatic Sorry for not getting back to you sooner, so busy lately!

I don't believe I fixed this, but I may have just disabled CSV streaming or hid the download link for now. :( 

Nice job finding a solution!

**Comment by steveklabnik** [comment]
I've cut a request_store 1.4.0 that should fix the issue here.

**Comment by javierjulio** [comment]
If there is an issue here I will accept a PR to resolve it. Thank you.
