### ISSUE TITLE
custom member actions do not check admin permission correctly.

### ISSUE THREAD

**Issue by urkle** [activeadmin/activeadmin#5116]
### Expected behavior

To not allow access to the page

### Actual behavior

It *sort of* allowed access to the page.. the main core renders our permission denied page, but the actions and sidebars all render when they should not.

### How to reproduce
The activeadmin configuration
```ruby
config.authentication_method = :require_admin_access
```
require_admin_access is a method on our application controller that raises a PermissionDenied error if they do not have admin access which is then caught by the app controller to render a permission denied page.

The admin controller for the resource
```ruby
ActiveAdmin.register Model do
  action_item :manage, only: :show do
    link_to 'Manage', manage_admin_model_path(resource)
  end

  member_action :manage, method: :get do
    # renders a view page
  end

  action_item :invalidate, only: :manage do
    link_to 'Invalidate', invalidate_model_admin_model_path(resource)
  end

  member_action :invalide_model, method: :post do
  end

  sidebar 'Side Panel', only: :manage do
    render partial: 'side_panel'
  end

  sidebar 'Details', only: [:show, :manage] do
     attributes_table_for(resource) do
       row :name
     end
  end
end
```

For the "show" action on the model, the permission denied page is the only thing rendered..  for the "manage" action, the top  navs render and the sidebars render.. but the "body" of the show page renders the permission denied only.   and we have action_items and sidebars on the show page and those correctly do not render.

I discovered this when on of our support team hit the admin site but had not received the correct role and they triggered an error as we were using

```ruby
  action_item :invalidate, only: :manage do
    link_to 'Invalidate', invalidate_model_admin_model_path(model)
  end
```
instead and it raised a undefined variable error because "model" wasn't defined (but resource is?)

**Comment by Fivell** [comment]
@urkle , please attach screenshots if you can

**Comment by urkle** [comment]
@Fivell sure.. (Text have been changed to protect the innocent)

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/101123/28940370-8c8f00ca-7862-11e7-8d6d-ee67cb1af878.png">

When viewing the "show" page just the perm denied shows up like this.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/101123/28940447-c80d3284-7862-11e7-8145-f2b56de2e100.png">

**Comment by Fivell** [comment]
@urkle , root is here https://github.com/activeadmin/activeadmin/blob/beed9fbf3da6be710948fae9c68cafe79edcfba2/lib/active_admin/base_controller.rb#L71

**Comment by Fivell** [comment]
@urkle  you can override this method in your controller , not sure where exactly I didn't see your implementation

**Comment by urkle** [comment]
@Fivell hmm.. so it's probably my perm-denied renderer rendering w/ a layout that is triggering this..  

Can I easily define a "controller" method override in the parent of the activeadmin controllers? (e.g. between our applicationController and the model specific admin controller)

our application controller has these two methods in it controlling our perm denied

```ruby
  ## Active Admin Overrides
  def admin_access_required!
    permission_denied
  end

  def permission_denied
    if authenticated?
      respond_to do |format|
        format.html { render 'layouts/denied' }
        # .. other formats trimmed for brevity.
      end
    else
      respond_to do |format|
        format.html { save_after_login_endpoint; redirect_to login_now_url }
        # .. other formats trimmed for brevity.
      end
    end
  end
```

**Comment by urkle** [comment]
@Fivell thanks for the help.. I found a simple workaround.

I changed my permission_denied to accept a layout: param and just set it to false for the active admin method in my controller..  like so.

```ruby
  ## Active Admin Overrides
  def admin_access_required!
    permission_denied(layout: false)
  end

  def permission_denied(layout: true)
    layout_args = {}
    layout_args[:layout] = false unless layout
    if authenticated?
      respond_to do |format|
        format.html { render 'layouts/denied', **layout_args }
        # .. other formats trimmed for brevity.
      end
    else
      respond_to do |format|
        format.html { save_after_login_endpoint; redirect_to login_now_url }
        # .. other formats trimmed for brevity.
      end
    end
  end
```
