### ISSUE TITLE
Bug: comment routes appear even when comments are disabled

### ISSUE THREAD

**Issue by shaldengeki** [activeadmin/activeadmin#5117]
### Expected behavior

When disabling comments through `config.comments = false`, the comments-related routes should not be registered.

### Actual behavior

Comments-related routes (e.g. `/admin/comments`) appear in routes even if comments are disabled in configuration.

### How to reproduce

1. Add `config.comments = false` to `config/initializers/active_admin.rb`
2. Add `ActiveAdmin.routes(self)` to `config/routes.rb`
3. Run `rake routes | grep comments`

Comment-related routes appear.

(cc @alainbloch)

**Comment by Fivell** [comment]
looks like this can be handled here 
https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/router.rb#L81

**Comment by ghilead** [comment]
Perhaps registering the Comment resource should be avoided altogether for namespaces that disable it? 

https://github.com/activeadmin/activeadmin/blob/4b49319751b8c58363f46ae1d99e5bb1b7b65c39/lib/active_admin/orm/active_record/comments.rb#L23

**Comment by vanegomez** [comment]
I have the same issue. I'm a bit confused on how you were able to solve it. Thank you

**Comment by ghilead** [comment]
@vanegomez I ended up doing a workaround: created an empty custom resource page for ActiveAdmin::Comment. The routes are still there, but the page is blank. 

```
ActiveAdmin.register ActiveAdmin::Comment, as: 'Comment', namespace: :portal do
  index do
  end

  show do
  end
end
```

I traced back to where this was introduced and tried to understand the rationale, I don't think the fix as I proposed above is going to be effective. I tried to re-ignite the conversation here: 

https://github.com/activeadmin/activeadmin/issues/3695


Hope this helps!

**Comment by mef79** [comment]
Found a workaround that prevents the apps from being generated that works for my purposes. It's not ideal, but I really wanted them gone.

```
# in config/intializers/active_admin.rb
# or anywhere else after ActiveAdmin is loaded but before ActiveAdmin.routes gets called

module NamespaceWithoutComments
  def register(resource_class, options = {}, &block)
    super unless resource_class == ActiveAdmin::Comment
  end
end

module ActiveAdmin
  class Namespace
    prepend NamespaceWithoutComments
  end
end
```

Consider before using:
- future compatibility concerns - if any of the active admin code that this references changes and you update, this snippet might cause problems in your app
- It's at odds with the maintainers' stated intention of allowing comments to be turned on for an individual resource
- actually, it invalidates the `config.comments` setting - if you later want to have comments, this needs to go
