### ISSUE TITLE
Cant make custom dropdown menu 

### ISSUE THREAD

**Issue by rbUUbr** [activeadmin/activeadmin#5118]
Hi!
I've made custom menu within ``` belongs_to ``` and ``` navigation_menu ```:
```
ActiveAdmin.register Order do
  belongs_to :company
  navigation_menu :company
end
```
2
```
ActiveAdmin.register Service do
  belongs_to :company
  navigation_menu :company
end
```
And main model:
```
ActiveAdmin.register Company do
  index do
    selectable_column
    id_column
    column :name
    column :slug
    column :email
    column :address
    actions
  end
end
```
I want to make dropdown menu from 1 and 2 models, but, cause it custom namespace (url: admin/companies/1/orders)
But ``` menu parent: 'text' ``` does not work
Any ideas?
Have a nice day!

**Comment by stefsava** [comment]
There is an error in @rbUUbr issue text, he refers to the `navigation_menu: company` lines.

However the bug seem confirmed.

This is my code:

```
ActiveAdmin.register Host do
end

ActiveAdmin.register Mac do
  belongs_to :host
  navigation_menu :host
end
```

_ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]_
_Rails 5.1.3_
_activeadmin (1.1.0)_

The routes are created and working properly the menu is not created.

![host 3 network](https://user-images.githubusercontent.com/19606/29924157-47a757a4-8e5c-11e7-8003-3b622cb2e3a9.png)

**Comment by yahooguntu** [comment]
I also ran into this issue with the same resource setup as @stefsava.

_ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
Rails 5.0.6
activeadmin (1.1.0)_

**Comment by lauraannwilliams** [comment]
Ditto, no change to global navigation for me.
