### ISSUE TITLE
Trying to run active_admin:resource {ModelName} throws error

### ISSUE THREAD

**Issue by JGailor** [activeadmin/activeadmin#5123]
### Expected behavior

Running rails generate active_admin:resource {ModelName} should do it's thing

### Actual behavior

An error message stating:

Could not find "admin.rb" in any of your source paths. Your current source paths are:
{some local paths}

**Comment by cemmanuel1** [comment]
+1 same issue

**Comment by hashlin** [comment]
+1 same issue

**Comment by varyonic** [comment]
Caused by 4818927cf4c0f48d82ba48e8d52672fbd6d3c719 I expect.

**Comment by hashlin** [comment]
@varyonic Thanks . It works now :100:
