### ISSUE TITLE
Using globalize or any other way to translate models

### ISSUE THREAD

**Issue by dikey94** [activeadmin/activeadmin#5127]
Hello everybody,
I'm looking for a way to use ActiveAdmin with model translations. Let's say there is Article model with multilanguage field "title". I'd like to use ActiveAdmin to edit the field in each language I have. I know there use to be a gem called "ActiveAdmin::Globalize" or similar but it's really old and doesn't work with rails 5.

Thanks for any help!

**Comment by varyonic** [comment]
[@fabn's fork](https://github.com/fabn/activeadmin-globalize) was last updated end of last year, I would love to see it actively maintained again.

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded.  Please feel free to leave a comment requesting this issue be reopened if needed.

**Comment by baka-san** [comment]
What is the status on this? Is Globalize supported with Rails 6/ActiveAdmin 2.8.1? If so, is there any documentation on using it?
