### ISSUE TITLE
Comments are not destroyed when parent resource is

### ISSUE THREAD

**Issue by pacuna** [activeadmin/activeadmin#5141]
### Expected behavior

If a resource with comments gets destroyed, its comments should also be destroyed.

### Actual behavior

They still remain in the database.

### How to reproduce

Just add comments for a resource and then look for its comments using ActiveAdmin::Comment

**Comment by zorab47** [comment]
Why should removal of comments be the behavior? If they are considered audits, then keeping them would be desired.

Can you elaborate on the use case?

**Comment by pacuna** [comment]
@zorab47 what's the point of having an audit if you can't see the object it was related to?

**Comment by varyonic** [comment]
I don't use this feature but I'ld consider a PR that optionally did this. I think an easy workaround would be an `on delete cascade` database constraint.
