### ISSUE TITLE
Chinese filters translation missing

### ISSUE THREAD

**Issue by rita1014** [activeadmin/activeadmin#5147]
translation missing: 
zh-CN.active_admin.filters.predicates.from
zh-CN.active_admin.filters.predicates.to

**Comment by varyonic** [comment]
PR for translation please, it's [not difficult](https://github.com/activeadmin/activeadmin/pulls?q=is%3Apr+label%3Atranslation)

**Comment by varyonic** [comment]
Closed by #5266
