### ISSUE TITLE
The Method member_action fails for a particular action name.

### ISSUE THREAD

**Issue by GeorgeLautenschlager** [activeadmin/activeadmin#5148]
### Expected behavior

The member_action method should generate a route.

### Actual behavior

The member_action method crashes with an error:
`wrong number of arguments (given 1, expected 0)`

### How to reproduce

Actual model names and attributes have been renamed, but here's the code as it stands:

```
ActiveAdmin.register SomeModel do
  menu parent: "parent"
  config.filters = false
  config.per_page = 50
  config.comments = false

  form do |f|
    f.inputs "Details" do
      f.input :attribute1
      f.input :attribute2
      f.input :file_attribute, as: :file, required: false, label: "File Attribute"
    end

    f.actions
  end

  action_item :process, only: :show  do
    link_to 'Process', process_admin_some_model_path(resource), method: :put
  end

  member_action :process, method: :put do
    resource.process!

    redirect_to resource_path
  end
end
```
What seems particularly odd about this is that the exact same code works fine if the action is renamed to 'generate'. Like so:

```
ActiveAdmin.register SomeModel do
  menu parent: "parent"
  config.filters = false
  config.per_page = 50
  config.comments = false

  form do |f|
    f.inputs "Details" do
      f.input :attribute1
      f.input :attribute2
      f.input :file_attribute, as: :file, required: false, label: "File Attribute"
    end

    f.actions
  end

  action_item :generate, only: :show  do
    link_to 'Process', generate_admin_some_model_path(resource), method: :put
  end

  member_action :generate, method: :put do
    resource.process!

    redirect_to resource_path
  end
end
```

**Comment by aarek** [comment]
Hi. You are seeing this error because by adding `member_action` you redefined one of the `AbstractController::Base` core methods: [AbstractController::Base#process](http://api.rubyonrails.org/classes/AbstractController/Base.html#method-i-process).

The error at this moment is very cryptic so i added Pull Request to raise error informing that the method is already defined while registering resource in active admin

**Comment by varyonic** [comment]
aarek's explanation is correct. Maybe it was a bad design decision to use the action name directly as a generated controller method name (eg. without appending "_action"). Leaving this open because too many users follow the GitHub default and don't search closed issues.
