### ISSUE TITLE
Make select elements with a large number of options faster

### ISSUE THREAD

**Issue by phillipoertel** [activeadmin/activeadmin#5151]
After trying several Rails admin tools, I've become a fan of active admin now. But doing long select elements has been a difficult, although this is a very common case IMHO. So here's my suggestion.

### Expected behavior

- In forms, it's fast and easy to choose one or more options from form fields that have a large number of options. Examples: a list of countries, a list of all "tags" in an application, selecting one of overall 10.000s of records.
- technically, it would be possible define if the options should be fetched from the server side (idea: ... `as: :select, autocomplete: -> { |name| User.active.find_by(name: name) }`

### Actual behavior

- long lists require a lot of scrolling to choose an option
- when there is a  large number of options, page load and selecting an element gets sluggish.

### Suggestion

- integrate the excellent select2 JS library into the core of activeadmin, or make a separate gem supported by the activeadmin which adds select2 as a drop-in replacement to the HTML standard element (no config needed). While there are at least two gems that integrate select2, I found them to be unreliable/require hacking to get them to work, and break after the 1.0 / 1.1 update of active admin.
- define a standard how the API for the autocomplete should be implemented, if that can't be handled generically by activeadmin gem.

**Comment by Fivell** [comment]
related #2692

**Comment by Fivell** [comment]
@phillipoertel did you try this solution https://github.com/activeadmin/activeadmin/issues/2692#issuecomment-259031231 ?

**Comment by phillipoertel** [comment]
@Fivell thanks for the link. I ran across that some weeks ago but at that point had already hacked my own autocomplete solution, and didn't look closely enough to see it worked in regular forms as well (not just filters). My situation was further complicated because I had to use form objects/decorators since our business logic is not implemented in ActiveRecord models.

I still think activeadmin should handle huge associations reliably and out of the box; ideally with a separate gem that you can opt-in into using.

Closing this ticket because it's already discussed in detail in #2692.
