### ISSUE TITLE
subdomain routing conflict

### ISSUE THREAD

**Issue by salihsagdilek** [activeadmin/activeadmin#5158]
i try use activeadmin with subdomain, my case 2 subdomain 
1. api.example.com
2. admin.example.com

routes.rb
```ruby
Rails.application.routes.draw do
  constraints :subdomain => "admin" do
    ActiveAdmin.routes(self)
    devise_for :admin_users, ActiveAdmin::Devise.config
  end
  resources :currencies
  root 'index#index'
end
```
initializers/active_admin.rb
```ruby
config.default_namespace = false
````
normally work perfectly also i can use 
api.example.com/currencies and admin.example.com

but when i add resources to active admin 
api.example.com/currencies redirect to me login page
but also admin subdomain work perfectly and api.example.com perfect without currencies pages.

anyone have idea ?

**Comment by macfanatic** [comment]
There are two issues that might be useful to review @salihsagdilek:

#4731  and #2163.

**Comment by salihsagdilek** [comment]
@macfanatic thank you
