### ISSUE TITLE
ActiveFilters ignores the primary_key setting of an association

### ISSUE THREAD

**Issue by Darhazer** [activeadmin/activeadmin#5164]
I have associations that are not based on the primary key of the table, but use some other key instead.
When filtering on such a field however, ActiveFilters correctly detects the associated class, but takes the value and uses it  as a primary key in a simple `find` call.

The association is set up like this:
`belongs_to :part, foreign_key: :sn, primary_key: :sn`

When filtered by sn, it correctly found that it should display a Part resource, but uses the `sn` value as `id` and either displays wrong Part or raises an exception, when there is no such id.
On a side note, there is no option to disable this box, in order at least not to raise errors

### Expected behavior

Find the part by `sn`

### Actual behavior

Tries to find part by `id`

**Comment by wspurgin** [comment]
Related to #5223 because of the [`find`](https://github.com/activeadmin/activeadmin/blob/v1.1.0/lib/active_admin/filters/active_filter.rb#L22) in `ActiveFilter`. I think with some changes in that PR, this issue could also be resolved.
