### ISSUE TITLE
Remove !important from css

### ISSUE THREAD

**Issue by MaicolBen** [activeadmin/activeadmin#5169]
It isn't a bug, it is a improvement in order to override better your css. Using [!important isn't recommended](https://cssguidelin.es/#important) and here are [some examples of it](https://github.com/activeadmin/activeadmin/search?utf8=%E2%9C%93&q=important&type=)

**Comment by javierjulio** [comment]
This is being worked on as part of #3862

**Comment by MaicolBen** [comment]
Thanks! I didn't know
