### ISSUE TITLE
nokogiri (1.6.8) error Rails 

### ISSUE THREAD

**Issue by akshay18496** [activeadmin/activeadmin#5179]
[Please follow the guidelines for creating a bug report](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#4-did-you-find-a-bug).

The issue tracker is only for bugs and feature requests. If you need general
help please post to
[StackOverflow](http://stackoverflow.com/questions/tagged/activeadmin).

### Expected behavior
i want to run activeadmin
What actually happens?
 below error in terminal
Bundler::GemspecError: Could not read gem at
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/cache/nokogiri-1.6.8-x86-mingw32.gem.
It may be corrupted.
An error occurred while installing nokogiri (1.6.8), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.

In Gemfile:
  activeadmin was resolved to 1.0.0.pre4, which depends on
    rails was resolved to 5.0.0, which depends on
      actioncable was resolved to 5.0.0, which depends on
        actionpack was resolved to 5.0.0, which depends on
          actionview was resolved to 5.0.0, which depends on
            rails-dom-testing was resolved to 2.0.1, which depends on
              nokogiri
### How to reproduce

Your best chance of getting this bug looked at quickly is to provide an
**executable test case** demonstrating the expected behavior that is not
occurring. [Please follow the guidelines for creating a bug
report](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#4-did-you-find-a-bug).

**Comment by deivid-rodriguez** [comment]
bundler/bundler#6034 seems enough to get help with this. Thanks.
