### ISSUE TITLE
NameError: uninitialized constant MyModel

### ISSUE THREAD

**Issue by StephanMeijer** [activeadmin/activeadmin#5184]
### Expected behavior

Create an ActiveAdmin model and be able to use `rake` and `rails.

### Actual behavior

```
rake aborted!
NameError: uninitialized constant MyModel
/home/steve/Projects/testapp/app/admin/my_models.rb:1:in `<top (required)>'
/home/steve/Projects/testapp/config/routes.rb:3:in `block in <top (required)>'
/home/steve/Projects/testapp/config/routes.rb:1:in `<top (required)>'
/home/steve/Projects/testapp/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:abort_if_pending_migrations => environment
(See full trace by running task with --trace)
```

After running:
```
rails generate active_admin:resource MyModel

rake db:seed
```

### How to reproduce
Following the instructions at https://activeadmin.info/0-installation.html

```
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```
```
Rails 5.0.6
```
```
rake, version 12.1.0
```

**Comment by varyonic** [comment]
The instructions are for registering an existing Rails model with ActiveAdmin.  They assume the model is already created, eg. with `rails g model MyModel name email`  You may want to [start with a tutorial](https://gorails.com/episodes/using-activeadmin-to-build-an-admin-ui).

**Comment by zorab47** [comment]
The suggested fix looks good. Reopen the issue if there is more to add to the conversation.

**Comment by snipertop** [comment]
To register an existing model with Active Admin:

rails generate active_admin:resource MyModel
This creates a file at app/admin/my_model.rb to set up the UI; refresh your browser to see it.

**Comment by snipertop** [comment]
To register an existing model with Active Admin:

rails generate active_admin:resource MyModel

This creates a file at app/admin/my_model.rb to set up the UI; refresh your browser to see it.
仔细阅读这句话，你需要在一个你已经生成好的模型上注册UI
