### ISSUE TITLE
Footer of the login view is empty

### ISSUE THREAD

**Issue by kensk8** [activeadmin/activeadmin#5188]
There is a way to the footer on the activeadmin config appears on the login view?
, actually I set one footer but in the login view is empty
<img width="554" alt="captura de pantalla 2017-09-28 a la s 11 42 51" src="https://user-images.githubusercontent.com/3844557/30972912-429944d8-a442-11e7-8cd6-af56f0eced16.png">

**Comment by varyonic** [comment]
The footer only applies after login.  To customize the login page see [this StackOverflow answer](https://stackoverflow.com/questions/46343448/how-to-show-some-content-for-non-login-admin-user-before-admin-login-page-load-i/46345515#46345515)

**Comment by varyonic** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or reopen this issue. Thanks!
