### ISSUE TITLE
no notice flash when comment successfully created

### ISSUE THREAD

**Issue by pacuna** [activeadmin/activeadmin#5193]
### Expected behavior

When a comment is created, a flash message indicating success should be displayed.

### Actual behavior

Nothing shows up.

### How to reproduce

Create a comment.

Maybe there's a reason behind this decision? I would happily send a PR

**Comment by mykubicle** [comment]
@pacuna is this still an issue? I have added comments and the success flash message does appear.

**Comment by pacuna** [comment]
@mykubicle thanks! I'll close the issue
