### ISSUE TITLE
Insert Partial in head or body of every response of active admin.

### ISSUE THREAD

**Issue by sanyam-j** [activeadmin/activeadmin#5201]
Hi, I have a tracking script for user session and to set user session i have to render one script in every response. So how can i append it to response in active admin. Is there any way to over ride admin layout or to just interest some partial in every request?

**Comment by dhyegofernando** [comment]
@sanyam-j take these steps:

**Appending content to the header (logged-user only):**
1. Create a view file in `app/views/shared/tracking_script.html.erb` and put your content there.
2. Create a file `config/initializers/active_admin/header.rb` with the following content:
```ruby
module ActiveAdmin
  module Views
    module Pages
      module TrackingScriptBuilder
        def build(*args)
          super(*args)
          build_tracking_script
        end

        def build_tracking_script
          within @head do
            render 'shared/tracking_script'
          end
        end
      end

      Base.prepend(TrackingScriptBuilder)
    end
  end
end
```

**If you want to render the tracking script inside the body (logged-user only):**
Follow the same steps from the tutorial for `@head` rendering but change one line in the initializer file:
```ruby
module ActiveAdmin
  module Views
    module Pages
      module TrackingScriptBuilder
        def build(*args)
          super(*args)
          build_tracking_script
        end

        def build_tracking_script
          within @body do # Only change this line
            render 'shared/tracking_script'
          end
        end
      end

      Base.prepend(TrackingScriptBuilder)
    end
  end
end
```

**To render this script even for a non-logged-user:**
1. Create the view in `app/views/shared/tracking_script.html.erb` too
2. Create another view in `app/views/layouts/active_admin_logged_out.html.erb` to override active_admin default path with the following content:
```ruby 
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">

  <title><%= [@page_title, render_or_call_method_or_proc_on(self, ActiveAdmin.application.site_title)].compact.join(" | ") %></title>

  <%= stylesheet_link_tag 'active_admin.css', media: 'screen' %>
  <%= stylesheet_link_tag 'active_admin/print.css', media: 'print' %>
  <%= javascript_include_tag 'active_admin.js' %>

  <%= render 'shared/tracking_script' %>

  <% ActiveAdmin.application.meta_tags_for_logged_out_pages.each do |name, content| %>
      <%= tag(:meta, name: name, content: content) %>
  <% end %>

  <%= csrf_meta_tag %>
</head>
<body class="active_admin logged_out <%= controller.action_name %>">
<div id="wrapper">

  <div id="content_wrapper">
    <% flash_messages.each do |type, message| %>
        <%= content_tag :div, message, class: "flash flash_#{type}" %>
    <% end %>
    <div id="active_admin_content">
      <%= yield %>
    </div>
  </div>
  <div id="footer">
    <%= yield :footer %>
  </div>
</div>
</body>
</html>
```

**Comment by varyonic** [comment]
This may have been resolved by #5220 but in any case it is a good workaround. I am going to close but feel free to leave a comment requesting this issue be reopened if needed.

**Comment by nfedyashev** [comment]
Perhaps this might be useful for anyone who finds this old thread.

From what I see, this method doesn't seem to work in recent versions(at least in activeadmin 2.6.0).

```
ActionView::Template::Error (Can't be in the context of nil. [, <!DOCTYPE html><html lang="en">
  <head>
    <title>Resources | Admin App</title>
```

```
</html>
]):
    1: insert_tag renderer_for(:index)

config/initializers/active_admin_header.rb:11:in `build_tracking_script'
```

`@head` & `@body` are nil in that `build_tracking_script` method.
* looking for an alternative solution

/cc @dhyegocalota

**Comment by elassadi** [comment]
Who ever it may  help 
`module AdminPageLayoutOverride
  def build_page(*args)
    within super do
      render "layouts/environment"
    end
  end

  def build_active_admin_head
    within super do
      render "admin/custom_script_tags"
    end
  end
end

ActiveAdmin::Views::Pages::Base.send :prepend, AdminPageLayoutOverride`

This way you can include your tags

**Comment by paulomcnally** [comment]
> 

Hi, where you put this code? Where is te file?

Thanks
