### ISSUE TITLE
Unable to find input class InetInput

### ISSUE THREAD

**Issue by saroar** [activeadmin/activeadmin#5204]
http://prntscr.com/gxdcvz

ActionView::Template::Error (Unable to find input class InetInput):
    1: insert_tag renderer_for(:edit)
  
formtastic (3.1.5) lib/formtastic/helpers/input_helper.rb:336:in `rescue in namespaced_input_class'
formtastic (3.1.5) lib/formtastic/helpers/input_helper.rb:333:in `namespaced_input_class'
formtastic (3.1.5) lib/formtastic/helpers/input_helper.rb:342:in `input_class'
formtastic (3.1.5) lib/formtastic/helpers/input_helper.rb:240:in `input'
formtastic (3.1.5) lib/formtastic/helpers/inputs_helper.rb:330:in `block in fieldset_contents_from_column_list'
formtastic (3.1.5) lib/formtastic/helpers/inputs_helper.rb:318:in `collect'
formtastic (3.1.5) lib/formtastic/helpers/inputs_helper.rb:318:in `fieldset_contents_from_column_list'
formtastic (3.1.5) lib/formtastic/helpers/inputs_helper.rb:297:in `inputs'
arbre (1.1.1) lib/arbre/rails/forms.rb:30:in `proxy_call_to_form'
/Users/alif/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/views/components/active_admin_form.rb:60:in `inputs'
/Users/alif/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/views/pages/form.rb:45:in `block in default_form_config'
/Users/alif/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/views/components/active_admin_form.rb:35:in `instance_eval'
/Users/alif/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/views/components/active_admin_form.rb:35:in `build'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:28:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `active_admin_form_for'
/Users/alif/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/views/pages/form.rb:25:in `main_content'
/Users/alif/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-f28a4e0fb315/lib/active_admin/views/pages/base.rb:91:in `block (2 levels) in build_main_content_wrapper'

`# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20171014153634) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"
  enable_extension "pgcrypto"

  create_table "active_admin_comments", force: :cascade do |t|
    t.string "namespace"
    t.text "body"
    t.string "resource_type"
    t.bigint "resource_id"
    t.string "author_type"
    t.bigint "author_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["author_type", "author_id"], name: "index_active_admin_comments_on_author_type_and_author_id"
    t.index ["namespace"], name: "index_active_admin_comments_on_namespace"
    t.index ["resource_type", "resource_id"], name: "index_active_admin_comments_on_resource_type_and_resource_id"
  end

  create_table "roles", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
    t.string "name"
    t.uuid "resource_id"
    t.string "resource_type"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["name", "resource_type", "resource_id"], name: "index_roles_on_name_and_resource_type_and_resource_id"
    t.index ["name"], name: "index_roles_on_name"
  end

  create_table "users", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet "current_sign_in_ip"
    t.inet "last_sign_in_ip"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "name"
    t.string "surname"
    t.date "date_of_birth"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  create_table "users_roles", id: false, force: :cascade do |t|
    t.uuid "user_id"
    t.uuid "role_id"
    t.index ["user_id", "role_id"], name: "index_users_roles_on_user_id_and_role_id"
  end

end
`

`ActiveAdmin.register User do
  permit_params :name, :surname, :date_of_birth, :email, :password, :password_confirmation
end
`

**Comment by saroar** [comment]
i fixed it thanks

**Comment by oxfist** [comment]
I'd strongly recommend editing the original post for better clarity, since the format is way off. Also, you mind sharing how you fixed it, I'm having the same problem?

**Comment by varyonic** [comment]
Duplicates #3682
