### ISSUE TITLE
has_many form breaks when first deleting objects, then adding objects

### ISSUE THREAD

**Issue by caifara** [activeadmin/activeadmin#5207]
Using a has_many form with pre-initialized objects breaks the js when first deleting objects and then adding objects.
I needed such a form letting our users "duplicate" an object. When they do that, they see a form starting with a `dup` object and its associated `dup`-children.

### Expected behavior

All objects in the form should be created.

### Actual behavior

Some objects do not get saved because the has_many form memoizes the index upon first clicking the "add record" button:

https://github.com/activeadmin/activeadmin/blob/master/app/assets/javascripts/active_admin/lib/has_many.es6#L44

However, if the form already starts out with some objects and you deleted some of those prior to clicking "Add record", the index is too low (because `parent.children('fieldset').length`is now lower), duplicating some already existing fields.

For example: starting name attributes:

    posts_0_name
    posts_1_name

* Then: remove object "0", 
* then add a new object

=> new object has field `posts_1_name` again.

**Comment by dhyegofernando** [comment]
I've tried to reproduce this error but I couldn't. It seems to work fine.

p.s. that piece of code (`parent.children('fieldset').length`) gets executed only once since in the line after that, it [saves as a element data cache](https://github.com/activeadmin/activeadmin/blob/master/app/assets/javascripts/active_admin/lib/has_many.es6#L45).

Anyway, could you create a single gist or detail even more the steps?

**Comment by caifara** [comment]
Thanks for investigating.

The problem only arises if one changes the fieldset length _before_ that line of code gets executed. This happens when the has_many form for a new object is already populated and one removes an item before adding an item.

Say, for example, your "new customer" button shows you a form already populated with two items. These items have index 0 and 1 in the form. If you add an item, the `parent.children('fieldset').length` line gets executed, results in "2" and all is well.
However if one deletes the first element _before_ adding something, the line does not get executed. If you add an item then, the line now does get executed, but results in "1" now. As the second element already uses that index all fields are now duplicated and upon submit one set is ignored.

I hope I made this somewhat more clear.
