### ISSUE TITLE
f.has_many with pre-built children and no remove button

### ISSUE THREAD

**Issue by greggzst** [activeadmin/activeadmin#5214]
### Expected behavior

In activeadmin form template f.has_many remove button is not supposed to show when `allow_destroy` is not passed in as parameter.

### Actual behavior

I've got a has_many through association as in below:

    class Room < ApplicationRecord
      has_many :room_options
      has_many :options, through: :room_options
    
      accepts_nested_attributes_for :room_options, allow_destroy: false
    end
    
    class RoomOption < ApplicationRecord
      belongs_to :room
      belongs_to :option
    end
    
    class Option < ApplicationRecord
      has_many :room_options
      has_many :rooms, through: :room_options
    end

and an activeadmin page:

    ActiveAdmin.register Room do
      permit_params :name, :guests_capacity, :description, :price, photos_attributes: [:id, :image, :is_primary, :_destroy]
   
      form(:html => { :multipart => true }) do |f|
        f.inputs do
          f.input :name
          f.input :guests_capacity
          f.input :description
          f.has_many :photos, allow_destroy: true do |photo|
            photo.input :image, as: :file, 
            hint: image_tag(photo.object.image_url(:thumb))
            photo.input :is_primary
          end
    
          Option.find_each { |option| f.object.room_options.build(option: option)}
    
          f.has_many :room_options, new_record: false, allow_destroy: false do |rof|
            rof.input :option_id, as: :hidden
            rof.input :has_option, as: :boolean, label: rof.object.option.name
          end
    
          f.input :price
        end
        f.actions
      end
    
    end

The screen of what I actually get:
![screen shot 2017-10-20 at 22 29 26](https://user-images.githubusercontent.com/17675583/31840633-8086ae92-b5e6-11e7-83b8-c9b73b9e4c8a.png)

I added `allow_destroy: false` to both `f.has_many` and `accepts_nested_attributes_for :room_options` because I thought it might help but it doesn't work either. The behaviour is the same if I don't add `allow_destroy: false`.

### How to reproduce

Use `f.has_many`.

I use activeadmin 1.1.0 and rails 5.1.4.

**Comment by varyonic** [comment]
This code was refactored recently in #5084. Is the behavior any different for you using master?

**Comment by greggzst** [comment]
@varyonic Unfortunately, it is the same when I use master branch

**Comment by greggzst** [comment]
@varyonic I've found out that remove button stays only when I create new resource.

**Comment by varyonic** [comment]
I think it is working as designed. If you want to override the behavior you can monkey patch ActiveAdmin::HasManyBuilder#has_many_actions

**Comment by greggzst** [comment]
@varyonic Thanks I'll do that even though I actually think you could change it so it works according to passed in parameter.

**Comment by varyonic** [comment]
I see now you are trying to build a form with a fixed number of pre-populated children and I think that is beyond what has_many was intended to support.  My recommendation is that you not use has_many for this scenario and consider a more custom form instead of modifying has_many_actions.  I know has_many could be extended with more options but I have no appetite for it.

**Comment by varyonic** [comment]
PS. A hack might be to assign temporary ids to the children so they appear saved, you would have to figure out the details yourself, however.
