### ISSUE TITLE
undefined method register_javascript for ActiveAdmin

### ISSUE THREAD

**Issue by EnziinSystem** [activeadmin/activeadmin#5216]
I see error "undefined method 'register_javascript' for ActiveAdmin"

```
ActiveAdmin.setup do |config|
  # == Site Title
  #
  # Set the title that is displayed on the main layout
  # for each of the active admin pages.
  #
  config.site_title = "Shop"

  config.register_javascript 'ckeditor/init.js'
```
```
/usr/local/rvm/gems/ruby-2.4.2/bundler/gems/activeadmin-95b8276d307a/lib/active_admin/application.rb:37:in `method_missing': undefined method `register_javascript' for #<ActiveAdmin::Application:0x00005642747c2268> (NoMethodError)
Did you mean?  register_page
        from /home/developer/shop/config/initializers/active_admin.rb:9:in `block in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.2/bundler/gems/activeadmin-95b8276d307a/lib/active_admin.rb:68:in `setup'
        from /home/developer/shop/config/initializers/active_admin.rb:1:in `<top (required)>'

```

**Comment by varyonic** [comment]
See https://stackoverflow.com/questions/46592753/active-admin-installing-issue-in-rails/46867110#46867110

**Comment by EnziinSystem** [comment]
I use:
`gem 'activeadmin', github: 'activeadmin'`
It's lastest version.

**Comment by varyonic** [comment]
Sorry, this was deprecated by #5060 (see [David's advice](https://github.com/activeadmin/activeadmin/pull/5060#issuecomment-313487743) and subsequent responses) and removed by @javierjulio in https://github.com/activeadmin/activeadmin/pull/5099/commits/61502c2900c66b70805be70654c1c8f2ccc83399  See also [Timo's suggestion](https://github.com/activeadmin/activeadmin/pull/5063#issuecomment-313119983).  There is also #5170 and the solution now proposed in #5201.  I reviewed and approved #5099 but now I am thinking it was premature.
