### ISSUE TITLE
products

### ISSUE THREAD

**Issue by estenpolska** [activeadmin/activeadmin#5217]
Hi

I have an issue with Products, when I try to change or delete the item it says "We're sorry but something went wrong"
Usually it was changed and that is it.

I would really need for help please!

**Comment by varyonic** [comment]
Look in the Rails log.

**Comment by estenpolska** [comment]
Thank you . Where to find it?

**Comment by estenpolska** [comment]
I am relly new user so I do not know it well.

**Comment by varyonic** [comment]
This is not the best place to ask questions like that.  Try StackOverflow, where you will find answers [like this one](https://stackoverflow.com/questions/16339735/where-does-rails-show-the-logging-output).
