### ISSUE TITLE
Pagination not working as expected with older versions of kaminari

### ISSUE THREAD

**Issue by HannesBenson** [activeadmin/activeadmin#5219]
### Expected behavior

ActiveAdmin should require the correct version of kaminari when installing to ensure that there isn't an issue with pagination.

_What do you think should happen?_
Change the minimum required version of Kaminari.

### Actual behavior

`ActiveAdmin 1.1.0` installed happily with `kaminari 0.16.3` but when pagination was required ActiveAdmin rendered a `undefined method `display_tag?' for #<Kaminari::Helpers::Paginator::PageProxy:0x00007f6e50ee3278>` error.

### How to reproduce

Install ActiveAdmin 1.1.0 with kaminari 0.16.3 and create enough records to require pagination. This might be a non issue, as upgrading kaminari to the latest version fixed our issue, but others might not be so lucky or could possibly have dependency requirements.

**Comment by zorab47** [comment]
This is resolved in the master branch and will be available in the next release. See this commit for reference: https://github.com/activeadmin/activeadmin/commit/5c29f73946d656ff5f08b2e0cfffcff999d6e67a.

Thanks for reporting.
