### ISSUE TITLE
Slashes in to_param aren't escaped in active admin url helpers

### ISSUE THREAD

**Issue by concept47** [activeadmin/activeadmin#5221]
### Expected behavior

If a model with a name and uuid column has a to_param method like this

    def to_param
      "#{name.parameterize}/#{id}"
    end

[and in the routes file, is setup like this](https://github.com/rails/rails/issues/16058) (link explains why this is necessary)

    get '/model/*slug', to: 'models#show', as: :model

then `model_path(model)` should give you a path like this
    
    model/parameterized-name/id

and `admin_model_path(model)` should give you a path like this

    admin/model/parameterized-name/id

### Actual behavior

What actually happens?

then `model_path(model)` gives you a path like this
    
    model/parameterized-name/id

but`admin_model_path(model)` gives you a path like this

    admin/model/parameterized-name%2Fid

### How to reproduce

See above. Just create a simple model (say, user.rb) with a to_param method, 

    class User < ApplicationRecord
         # has name attribute
         def to_param
            "#{name.parameterize}/#{id}"
         end
    end

... an empty active admin definition
    
     ActiveAdmin.register User do
     end

... in routes add the definition

    get '/users/*slug', to: 'users#show', as: :user
    resources :users 

then in rails console run the two commands

    app.user_path(User.last)
    app.admin_user_path(User.last)

you should see the slash is escaped in the admin path but not the non_admin path

**Comment by varyonic** [comment]
This might be a good first PR for someone.

**Comment by leenasn** [comment]
@varyonic I would like to fix this. Can you let me know where to look for fixing the issue? Thanks.

**Comment by varyonic** [comment]
Looks like Router#build_action needs to be extended with an explicit as: option. Look at the other issues referenced from rails/rails#16058, eg. refinery/refinerycms#2709. This is not as straightforward as I thought.

**Comment by concept47** [comment]
After looking into this, I don't think this can be fixed without monkey patching rails inside of active admin to override [default behavior from this commit](https://github.com/rails/rails/commit/5460591f0226a9d248b7b4f89186bd5553e7768f)

Essentially, in Rails 4.1.1 [if a slash is encountered in a rails route without using route globbing to determine the path, it is escaped](https://github.com/rails/rails/commit/5460591f0226a9d248b7b4f89186bd5553e7768f#diff-e304f21f210ada0bd90fb1990912b08eR3843)

Active Admin seems to lean on the Rails router pretty heavily to generate these urls/paths, so if the to_param method is used to generate the route [like we do here](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource/routes.rb#L75) ([which leads to a to_param call here](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource/routes.rb#L110)) ... then Rails will simply escape the portion of the url/path that has a slash in it. 

Doesn't really seem like theres much we can do here. Let me know what you think @varyonic?

**Comment by concept47** [comment]
what I wound up doing was creating an admin route manually to get around this

    get '/model/*slug', to: 'models#show', as: :model
    get '/admin/deals/*id' => 'admin/deals#show', as: :admin_model
    # used id instead of slug because active admin will pass it in as that
