### ISSUE TITLE
Improve documentation when using Authorization adapter

### ISSUE THREAD

**Issue by Techbrunch** [activeadmin/activeadmin#5222]
Initially I just had another authentication method called `authenticate_admin_user`:

```ruby
  config.authentication_method = :authenticate_admin_user!
```

```ruby
class ApplicationController < ActionController::Base
  def authenticate_admin_user!
    raise SecurityError unless current_user.try(:admin?)
  end

  rescue_from SecurityError do
    redirect_to '/admin/login'
  end
end
```

But then I thought it made more sense to use an `AuthorizationAdapter` and keep the `authenticate_user!` the same since I only want the user with a specific flag to be able to access activeadmin.

```ruby
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
  def authorized?(_action, _subject = nil)
    user.admin?
  end
end
```

I then ran into a redirect loop issue and it took a while to figure out what was happening. After a bit of googling without success I decided to take a deeper look into the ininitalizer until I found that:

```ruby
  # You can specify a method to be called on unauthorized access.
  # This is necessary in order to prevent a redirect loop which happens
  # because, by default, user gets redirected to Dashboard. If user
  # doesn't have access to Dashboard, he'll end up in a redirect loop.
  # Method provided here should be defined in application_controller.rb.
  config.on_unauthorized_access = :access_denied
```

Ok great, but what should I put in this method ? I want the user to be redirected to the login page but if I just use `redirect_to` I end up with the same redirect loop problem.

In the end my solution was to reset the session before redirecting the user:

```ruby
class ApplicationController < ActionController::Base
  def access_denied(exception)
    reset_session
    redirect_to '/admin/login', :alert => exception.message
  end
end
```

While writing this issue I found out that I'm not the first one to encounter this issue (#2081) and it's now actually documented (#2462) but under AuthorizationAdapter > [Using the CanCan Adapter](https://activeadmin.info/13-authorization-adapter.html#using-the-cancan-adapter) which I don't use.

I think the documentation should be updated to make sure that people using activeadmin without the CanCan adapter don't miss it.

I would also add an example when the user is redirected to the login page if not authorized.

I can work on a PR if you agree with this.

**PS1**: What is the best between `user.admin?` & `user & user.admin?` ?

**PS2**: Where do you put your authorization adapter files ? From what I see in other projects there is no clear best practices:

```
app/models
config/initializers/active_admin
app/admin/lib
app/models/adapters
```

Don't you think there should be some convention ?

**Comment by javierjulio** [comment]
I would accept a PR for improving the docs. Thank you.
