### ISSUE TITLE
Handle PG::ForeignKeyViolation: ERROR

### ISSUE THREAD

**Issue by davideghz** [activeadmin/activeadmin#5225]
### Expected behavior

**What do you think should happen?**

- Click on `Delete` link or button of a record with dependent resource pointing to it.
- ActiveAdmin should not delete the record.
- User should be redirected to index/show page.
- ActiveAdmin should displays an alert.

### Actual behavior

**What actually happens?**

- Click on `Delete` link or button of a record with dependent resource pointing to it.
- ActiveAdmin does not delete the record.
- ActiveAdmin displays a `ActiveRecord::InvalidForeignKey` error

### How to reproduce

- Create 2 models `User` has_many `Posts`; `Post` belongs_to `User`.
- Create a `User` and some related `Posts`.
- Try to cancel the `User` from `index` or `show` page.

**Comment by davideghz** [comment]
For the moment, I handled it as suggested [here](https://github.com/activeadmin/activeadmin/issues/2447). But it would be nice to get same behavior "out-of-the-box" with ActiveAdmin.

**Comment by marclerodrigues** [comment]
Is this still an issue? I've tried to reproduce but the behavior now is that the resource gets deleted and the associated records have the resource related foreign_key nullified. In you example:
The `User` would be deleted and the posts `author_id` would become empty.

**Comment by ceberhardt** [comment]
> Is this still an issue? I've tried to reproduce but the behavior now is that the resource gets deleted and the associated records have the resource related foreign_key nullified. In you example:
> The `User` would be deleted and the posts `author_id` would become empty.

Yes, this is still an issue. You have to make the has_many relation with dependent: :restrict_with_error in order to generate the error in the model object.

`has_many :programs, inverse_of: :program_group, dependent: :restrict_with_error`
