### ISSUE TITLE
I want to do a custom filter

### ISSUE THREAD

**Issue by sinansahin** [activeadmin/activeadmin#5230]
```
ActiveAdmin.register User do
  ...
  ...
  filter :email
  ...
  ...
end
```

I want to have the following database query
Form:
f.input :parent_unit_id, collection: ParentUnit.all

`User.where(id: Graduation.where(id: ParentUnit.find(params[:parent_unit_id]).graduation_ids).map { |x| x.user_id })`

how can I do it?

**Comment by varyonic** [comment]
This question belongs on StackOverflow. Also there are resources on the [wiki: filters-and-scopes](https://github.com/activeadmin/activeadmin/wiki#index-pages-filters-and-scopes)
