### ISSUE TITLE
Configure Nested namespaces in the 'active_admin' initializer.

### ISSUE THREAD

**Issue by AlexVentura** [activeadmin/activeadmin#5231]
I was trying to create some namespaces apart from the default `/admin` one, following the [documentation](https://activeadmin.info/1-general-configuration.html#namespaces) but what about if I need nested resources. Does anybody knows how to work with nested namespaces, I want something like this in `active_admin` initializer:

```
ActiveAdmin.setup do |config|
  config.site_title = "Onedocway Rails"
  config.authentication_method = :authenticate_admin_user!
  config.current_user_method = :current_admin_user
  config.logout_link_path = :destroy_admin_user_session_path

  # Custom namespaces at different levels

  # /admin/foo/bar
  config.namespace [:admin, :foo, :bar] do |foobar|
    foobar.site_title = "Admin Site"
    foobar.authentication_method = :authenticate_user!
  end

  # /reportmanager
  config.namespace :reportmanager do |report_manager|
    report_manager.authentication_method = :authenticate_reportmanager_user!
    report_manager.current_user_method = :current_reportmanager_user
    report_manager.root_to = 'dashboard#index'
  end

  # /customersuccessmanager
  config.namespace :customersuccessmanager do |customer_success_manager|
    customer_success_manager.authentication_method = :authenticate_customersuccessmanager_user!
    customer_success_manager.current_user_method = :current_customersuccessmanager_user
    customer_success_manager.root_to = 'dashboard#index'
  end
end
```
And also set this to the corresponding resources like this:
```
ActiveAdmin.register Post, namespace: [:admin, :foo, :bar] do
  ...
end
ActiveAdmin.register Post, namespace: :reportmanager do
  ...
end
ActiveAdmin.register Post, namespace: :customersuccessmanager do
  ...
end
```

Any help or tip to achieve this?

**Comment by varyonic** [comment]
Duplicates #615?

**Comment by AlexVentura** [comment]
Mmm I think it is not duplicated at all because there you are just mentioning the resources like `Post` model. But here I’m also mentioning the nested `namespaces` configuration in the `active_admin` initialization file!

I think those are two similar features but must be treated and fixed apart under its own scenario!

**Comment by wspurgin** [comment]
Aren't you trying to nest namespaces? That's what #615 is about as well. Take a look at #5185, that's the PR targeting this nested namespace support (if I'm understanding what you're asking).

You can then have in your routes

```ruby
namespace :admin do
  namespace :foo do
    namespace :bar do
      #...
    end
  end
end
```

Checkout that PR for more details and an example. I think that is what you're looking for.

**Comment by AlexVentura** [comment]
Mmm ok guys @wspurgin @varyonic I think it is pretty similar I got some confusing because I did not see something going deep into `active_admin.rb` file configuration for **nested namespaces** like this maybe:
```
config.namespace [:admin, :semiadmin] do |semi_admin|
    semi_admin.authentication_method = :authenticate_semiadmin_user!
    semi_admin.current_user_method = :current_semiadmin_user
  end
```
Hope it could be clear!

**Comment by varyonic** [comment]
I'm going to go ahead and close as a duplicate. Please feel free to leave a comment requesting this issue be reopened if needed.
