### ISSUE TITLE
Styles do not get inherited when working with namespaces!

### ISSUE THREAD

**Issue by AlexVentura** [activeadmin/activeadmin#5232]
I was trying to create some namespaces apart from the default `/admin` one, following the [documentation](https://activeadmin.info/1-general-configuration.html#namespaces). And now I have the next routes:

***/admin/dashboard*
*/reportmanager/dashboard*
*/customersuccessmanager/dashboard***

So in my `active_admin` initializer file:
```
ActiveAdmin.setup do |config|
  # /reportmanager
  config.namespace :reportmanager do |report_manager|
    report_manager.authentication_method = :authenticate_reportmanager_user!
    report_manager.current_user_method = :current_reportmanager_user
  end
  # /customersuccessmanager
  config.namespace :customersuccessmanager do |customer_success_manager|
    customer_success_manager.authentication_method = :authenticate_customersuccessmanager_user!
    customer_success_manager.current_user_method = :current_customersuccessmanager_user
  end
end
```

When I go to the `admin` namespace the styles work excellent but when I go to any of the other ones some styles seems to crash as in the next picture:
![screen shot 2017-11-02 at 15 59 33](https://user-images.githubusercontent.com/13169164/32359977-5c3b85cc-c017-11e7-9b97-8aaa2ccb4b41.png)

Then digging a little bit more I saw that the problem comes in the classes that the gem sets automatically in the `<body>` tag as shown below:
![screen shot 2017-11-02 at 21 51 32](https://user-images.githubusercontent.com/13169164/32360053-07f547ea-c018-11e7-886d-d5240a8816ab.png)
![screen shot 2017-11-02 at 17 23 25](https://user-images.githubusercontent.com/13169164/32360055-0b59a2c8-c018-11e7-9265-26dacba69dfe.png)
![screen shot 2017-11-02 at 21 52 44](https://user-images.githubusercontent.com/13169164/32360070-328721b8-c018-11e7-8abf-5c51931c14eb.png)

When changing `reportmanager_namespace` or `customersuccessmanager_namespace`class to `admin_namespace` it all works. So, depending on the namespace **ActiveAdmin** creates a special class with the `_namespace` ending and that's why the styles crash when in other namespaces different than `/admin`.

- Any suggestion how to fix it different than creating my own classes or duplicating the ActiveAdmin ones?
- Shouldn't they be automatically generated for each namespace?
🤔

**Comment by wspurgin** [comment]
Well there's no mention of `admin_namespace` anywhere in the assets directory. Are you sure this isn't your own styling? The pictures you gave don't look like the default AA styles.

**Comment by AlexVentura** [comment]
Yes you're right!
I was confusing because this styles come from the [ArcticAdmin](https://github.com/cle61/arctic_admin) gem so, close this up!
