### ISSUE TITLE
Error with formtastic with translations

### ISSUE THREAD

**Issue by antprt** [activeadmin/activeadmin#5234]
I have an error with formtastic.

My application has two languages spanish and english.

When I try to edit a register with a date formtastic raise Exception "undefined select_año". Only occurs with dates created by other gem. Never with created_at and updated_at that are created by rails.

año is year in spanish. If I have the application only in english the problem never happens. I suppose that in that case the application search "select_year" instead of "select_año"

Does someone knows how to avoid this error? Where is the translation? Why does I have that error?

**Comment by antprt** [comment]
I have an error with formtastic. 

My application has two languages spanish and english.

When I try to edit a register with a date formtastic raise Exception "undefined select_año". Only occurs with dates created by other gem. Never with created_at and updated_at

año is year in spanish. If I have the application only in english the problem never happens. I suppose that in that case the application search "select_year" instead of "select_año"

Does someone knows how to avoid this error? Where is the translation? Why does I have that error?

**Comment by varyonic** [comment]
This belongs on StackOverflow. Post the other gem and the stack trace for the error.
