### ISSUE TITLE
Support input type=password in modal dialog on batch actions

### ISSUE THREAD

**Issue by nlsrchtr** [activeadmin/activeadmin#5243]
### Expected behavior

I would have expected to get a password field in the batch action forms if I use the type "password".

### Actual behavior

I got an error that type password is not supported. But since I would like to submit a password to the batch action, it would be great to get also password as support type.

It should be a small change of adding it into the [supported types](https://github.com/activeadmin/activeadmin/blob/6b7a77c82ce4f0a576e4397f7a86a7332c128256/app/assets/javascripts/active_admin/lib/modal_dialog.es6#L6).

Changing the line from:
`if (/^(datepicker|checkbox|text|number)$/.test(type)) {`
to
`if (/^(datepicker|checkbox|text|number|password)$/.test(type)) {`

### How to reproduce

```ruby
batch_action :update, form: {
  passphrase: :password,
} do |ids, inputs|
  ...
end
```

Are there any known issues with this? Otherwise I would like to add an PR to this issue.

**Comment by wspurgin** [comment]
I don't see a problem. I wonder why we included so few in the first place. It's just to pick the right wrapper html for the type. We should probably update that regex to include *all* the possible input types:

```
button
checkbox
color
date 
datetime-local 
email 
file
hidden
image
month 
number 
password
radio
range 
reset
search
submit
tel
text
time 
url
week
```

Right? @javierjulio What are your thoughts? I guess some that shouldn't be supported are things like `submit`, `hidden`, `file`, and `image`. Otherwise will get this same issue when someone wants to support for the `week` or `url` (etc.) fields.

**Comment by dbackeus** [comment]
It also isn't possible to get a `<select multiple>...</select>` type input.

At the end of the day seems like you'll need to allow a deeper configuration hash for things to come together. Right now if an `Array` is supplied as a "type" that turns into a regular `<select>` field but what would be needed to support all types is likely something like:

```ruby
batch_action :update, form: {
  countries: {
    type: :select,
    options: { "Sweden" => "se", "United States" => "us" }, # label / value pairs could be accepted
  },
  interests: {
    type: :multiple,
    options: %w[gaming meditation tennis swimming], # Arrays could also be accepted
  },
  gender: {
    type: :radio,
    options: %w[male female whatevs],
  }
}
```

Makes sense?
