### ISSUE TITLE
Conflict Active Admin and Swaggard

### ISSUE THREAD

**Issue by marcodotcastro** [activeadmin/activeadmin#5244]
Could someone guide me to find the solution?

The project was created with Rails 5 API.

The gem swaggard continues to function normally, but gem activeadmin is no longer working. The error that is happening is as follows:

> Sprockets :: Rails :: Helper :: AssetNotFound at / admin / login
> The asset "active_admin.css" is not present in the asset pipeline

Here are also the gens I'm using in the project:

GemFile
```
gem 'rails', '5.1.4'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.7'
gem 'rack-cors'
gem 'rack-attack'
gem 'devise'
gem 'omniauth-facebook', '4.0.0'
gem 'koala'
gem 'simple_token_authentication', '~> 1.0'
gem 'dotenv-rails'
gem 'active_model_serializers', require: true
gem 'figaro'
gem 'paranoia', '~> 2.2'
gem 'activeadmin', github: 'activeadmin'
gem 'swaggard'
gem 'inherited_resources', git:'https://github.com/activeadmin/inherited_resources'

group :development, :test do
  gem 'ffaker'
  gem 'faker'
  gem 'rspec-rails'
  gem 'rspec-core'
  gem 'simplecov', :require => false
  gem 'rubycritic', :require => false
  gem 'capybara'
  gem 'spork', '~> 1.0rc'
  gem 'factory_girl_rails'
  gem 'annotate'
  gem 'letter_opener'
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'better_errors'
  gem 'listen', '~> 3.1.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'rack-mini-profiler'
  gem 'binding_of_caller'
  gem 'brakeman', :require => false
  gem 'rubocop', require: false
  gem 'sprockets', '~> 3.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Autodeploy
gem 'capistrano', '~> 3.7', '>= 3.7.1'
gem 'capistrano-rails', '~> 1.2'
gem 'capistrano-passenger', '~> 0.2.0'
gem 'capistrano-rbenv', '~> 2.1'
gem 'capistrano-bundler', '~> 1.3'
```

**Comment by javierjulio** [comment]
You’re missing the sass-rails gem.

**Comment by marcodotcastro** [comment]
I put the gem and it still does not work

**Comment by marcodotcastro** [comment]
Replicate the error in this project:

https://github.com/marcodotcastro/poc_administrate_api

**Comment by karlwilbur** [comment]
FWIW, I'm having the same problem with my quick and dirty [rails-5-example](https://github.com/K-and-R/rails-5-example). I'm not using `swaggard` in my project but I can confirm that I am seeing the same error ('The asset "active_admin.css" is not present in the asset pipeline.') in my project that I see with [poc_administrate_api](https://github.com/marcodotcastro/poc_administrate_api). Removing Swaggard from the Gemfile, routes, and initializer does make the error go away and Activeadmin loads as expected. I'm still trying to figure out the issue with my project.

**Comment by zorab47** [comment]
A Rails app generated with the `--api` option doesn't support stylesheets or any assets.

**Comment by varyonic** [comment]
I'm not happy about it, but there is a popular blog post on [Setting Up Rails 5 API Only App with ActiveAdmin](https://rrott.com/blog/ror/new-rails-5-api-with-activeadmin-integration.html) Any questions should go to the author.
