### ISSUE TITLE
using member_action with different verbs leads to same controller action

### ISSUE THREAD

**Issue by krtschmr** [activeadmin/activeadmin#5250]
member_action :merge, method: :get do
      #render a form
    

    member_action :merge, method: :post do
      # process the form

this results into 

    GET        /admin/bug_tracker_tickets/:id/merge(.:format)                       admin/bug_tracker_tickets#merge
    POST       /admin/bug_tracker_tickets/:id/merge(.:format)                       admin/bug_tracker_tickets#merge

so it's impossible to have it twice. workaround is to call the get method `merge_form`. should we stick to that workaround or should activeadmin be able to detect that it needs 2 different actions and call them `merge_get` and  `merge_post`

**Comment by Fivell** [comment]
@krtschmr take a look https://github.com/activeadmin/activeadmin/blob/8541a5deeedf48d470ab8c5e93eafdb95d8def1b/docs/8-custom-actions.md#http-verbs

AA supports same method for both http verbs instead 

So I think that we should just raise exception in case when member action  described second time

**Comment by zorab47** [comment]
@Fivell the goal is to be helpful and raise an error on duplicate action definition?

**Comment by Fivell** [comment]
@zorab47  I think yes we already have something similar https://github.com/activeadmin/activeadmin/commit/e0dd00b10dd5737177fb43ea2f6e8688b4f8137f

**Comment by varyonic** [comment]
I think #5167 addresses this.
