### ISSUE TITLE
Comment wasn't saved, text was empty - when adding comment

### ISSUE THREAD

**Issue by hendricius** [activeadmin/activeadmin#5258]
### Expected behavior

After a blank installation I want to be able to add comments to a user.

### Actual behavior

I am adding a comment after a fresh install and then only get the error `Comment wasn't saved, text was empty.`

Did a small video with the issue here: https://app.hyfy.io/v/ab4tNqZiULU/

### How to reproduce

* Latest active admin version from github or `1.1.0`
* User model
* Enable comments

**Comment by hendricius** [comment]
Has anyone had a similar issue before?

**Comment by 8vius** [comment]
Having the same issue

**Comment by OthmanAmoudi** [comment]
did you try migrating the database ?
in your terminal try:
`rails db:migrate
`

**Comment by zorab47** [comment]
Might it be related to permitted parameters?

**Comment by clay-f** [comment]
same issue here

<img width="1014" alt="screen shot 2018-01-30 at 11 55 51" src="https://user-images.githubusercontent.com/16079417/35547541-9550ce16-05b4-11e8-8970-81806c4db54d.png">


this is terminal info

<img width="790" alt="screen shot 2018-01-30 at 11 57 21" src="https://user-images.githubusercontent.com/16079417/35547580-d02b4a84-05b4-11e8-949f-cf01ae693ec6.png">

user table:

```
  create_table "users", force: :cascade do |t|
    t.string "name"
    t.string "password_digest"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end
```



activeadmin version: 1.2.1
rails version: 5.1.4
ruby version: 2.5.0
mac os: 10.13

**Comment by rainchen** [comment]
OK, I got it.
This is what happing when fails:

```
resource.errors
=> #<ActiveModel::Errors:0x00007fbf30436bc8
 @base=
  #<ActiveAdmin::Comment:0x00007fbf317f32b0
   id: nil,
   namespace: "admin",
   body: "11",
   resource_type: "Site",
   resource_id: 1,
   author_type: nil,
   author_id: nil,
   created_at: nil,
   updated_at: nil>,
 @details={:author=>[{:error=>:blank}]},
 @messages={:author=>["must exist"]}>

 ```

comment's author is nil and validation fails.

This issue is caused by Rails 5 makes belongs_to association required by default, here is [detail](https://blog.bigbinary.com/2016/02/15/rails-5-makes-belong-to-association-required-by-default.html)

Here is a quick solution without monkey patching activeadmin:

```
# makes belong to association optional by default
# save to config/initializers/rails_framework_defaults.rb
Rails.application.config.active_record.belongs_to_required_by_default = false
```

For activeadmin, should use `optional: true` in Comment model:

```
# Rails 5 makes belongs_to association required by default
 belongs_to :author,  polymorphic: true, optional: true
# notice :required is deprecated
```

activeadmin version: 1.2.1
rails version: 5.1.4

**Comment by zorab47** [comment]
Why would author be `nil`? It should be set to the `current_active_admin_user` to record which user made the comment. I'm running Rails 5.1 with ActiveAdmin 1.2.1 without hitting this issue.

Can you provide more of your configuration? Like the `config/initializers/active_admin.rb`

**Comment by rainchen** [comment]
@zenbaku I inited the project without a user model using cmd `rails g active_admin:install --skip-users`, so `current_active_admin_user` is nil for this case.

**Comment by zorab47** [comment]
@rainchen what user model are you using? Is it an existing one? Did you disable authentication?

See docs for [Authentication](https://github.com/activeadmin/activeadmin/blob/3733f703f28c1548dcc300da076f0cb11be1ea01/docs/1-general-configuration.md#authentication) for more information.

**Comment by rainchen** [comment]
@zorab47 
No user model in my project.

thx for the Authentication tips. I tried using:

```
config.authentication_method = false
config.current_user_method   = false
# these 2 settings were commented by default
```
but no luck.

**Comment by rainchen** [comment]
@zorab47 
I sent a PR #5360 , please have a look.

**Comment by zorab47** [comment]
The root idea here is to allow comments without a user model?

Is it strange that there isn't an associated `current_active_admin_user`? You do have users that are accessing the ActiveAdmin interface, right? They do not have to be an `AdminUser` as generated by the AA installer.

**Comment by rainchen** [comment]
@zorab47
It's a single user project, so no need to create a user model.
anyway if allowing `--skip-users`, it's expected to work without users, right?

**Comment by priegler** [comment]
We had the same error message but a totally different reason. 
So if you are using uuid`s as identifiers for your models instead of integer ids you will appreciate the following fix via a migration:

`
def change
    remove_column :active_admin_comments, :resource_id, type=:bigint
    add_column :active_admin_comments, :resource_id, :uuid
    add_index :active_admin_comments, [:resource_type, :resource_id], name: 'index_active_admin_comments_on_resource_type_and_resource_id'

    remove_column :active_admin_comments, :author_id, type=:bigint
    add_column :active_admin_comments, :author_id, :uuid
    add_index :active_admin_comments, [:author_type, :author_id], name: 'index_active_admin_comments_on_author_type_and_author_id'
  end
`

**Comment by hendricius** [comment]
Please see here: https://github.com/activeadmin/activeadmin/issues/5258. I fixed it only in the 1.2 branch. I also had to do the same things `priegler` did for this to work.

**Comment by djalmaaraujo** [comment]
@priegler is that all you had to do? run the migration? comments works for me unless when I customize the show page. It says this empty error

**Comment by djalmaaraujo** [comment]
But now all other models are having the empty issue, except the customized one. lol

**Comment by agrberg** [comment]
Has there been any update on this? Unfortunately you cannot cleanly get around this without changing the relationship when it is initially defined in the gem. The best workaround I came up with was after looking at how [`skip_callback`](https://github.com/rails/rails/blob/v6.0.2.1/activesupport/lib/active_support/callbacks.rb#L700) works in Rails. I put the following in my initializer:

```ruby
# config/initializers/active_admin.rb

callback_chain = ActiveAdmin::Comment.send(:get_callbacks, :validate)
author_callback = callback_chain.find { |callback| callback.filter.attributes == [:author] }
callback_chain.delete(author_callback)
```

**Comment by djalmaaraujo** [comment]
@agrberg I just tried your code in active_admin.rb, added a comment to my model, but did not work. I am using uuid btw.

```bash
2.6.5 :001 > ActiveAdmin::Comment.last
2020-01-20T19:46:24.408Z 23492 TID-owun8ep2f DEBUG:   ActiveAdmin::Comment Load (1.1ms)  SELECT  "active_admin_comments".* FROM "active_admin_comments" ORDER BY "active_admin_comments"."id" DESC LIMIT $1  [["LIMIT", 1]]
 => #<ActiveAdmin::Comment id: 308, namespace: "admin", body: "Duvido", resource_type: "Apuration", author_type: "User", created_at: "2020-01-20 19:45:58", updated_at: "2020-01-20 19:45:58", resource_id: "29e6fe30-d501-416f-8e4b-62d437eea37c", author_id: nil> 
```

**Comment by agrberg** [comment]
@djalmaaraujo Are you using ActiveAdmin w/ User models? From your output it looks like that is the type of your `author` but there is no id.

I'm using Active Admin w/o Users but HTTP Basic Auth instead and looking to save comments w/o triggering the validation on the `author` relationship.

**Comment by djalmaaraujo** [comment]
@agrberg I do. I use User model + devise. I added the comment to another Model. I also tried to User model, but I am getting the empty text problem.

**Comment by agrberg** [comment]
Sorry @djalmaaraujo I'm not sure what's going on. This is the first time I've touched ActiveAdmin in years so I'm a little rusty. What I'd recommend is opening the local gem `bundle open activeadmin` and putting in a break point `binding.pry` if using `pry-byebug` where the `ActiveAdmin::Comment` model is saved so you can see the associated errors. If after this setup you're getting one for the `author` association, I'm not sure why as this removes that from the callback chain. It is really hacky though and making the relationship `optional: true` would be the long term solution. You can see if that's the issue as well by adding that to the `belongs_to` call and reloading your server. I was able to confirm that was the root of my problem by doing so.

Also, I don't know if I'm cargo culting, but stopping/restarting spring is never a _bad_ idea 🤷‍♂

**Comment by djalmaaraujo** [comment]
@agrberg No problem. Thanks anyway. I will try what you suggested.

**Comment by romiras** [comment]
Any updates? We have 2.7.0 with same issue.
Meanwhile used this gist as work-around: https://gist.github.com/djalmaaraujo/d0cf4f23aace48e2f4ea4921c2d1297f

**Comment by deivid-rodriguez** [comment]
No, but I should've followed up on this. I'll have a look soon.

**Comment by steakknife** [comment]
None of these "fixes" work. `cant_modify_encrypted_attributes_when_frozen`

**Comment by ronnyworm** [comment]
This worked for me today on Rails 6.1: (just a summary of different comments from above, thank you @agrberg / @romiras and @priegler)

at the end of config/initializers/active_admin.rb (before the end ofc)

	# Fix author comment
	callback_chain = ActiveAdmin::Comment.send(:get_callbacks, :validate)
	author_callback = callback_chain.find { |callback| callback.filter.attributes == [:author] }
	callback_chain.delete(author_callback)

and add this migration

	def change
		remove_column :active_admin_comments, :resource_id, type=:bigint
		add_column :active_admin_comments, :resource_id, :uuid
		add_index :active_admin_comments, [:resource_type, :resource_id], name: 'index_active_admin_comments_on_resource_type_and_resource_id'

		remove_column :active_admin_comments, :author_id, type=:bigint
		add_column :active_admin_comments, :author_id, :uuid
		add_index :active_admin_comments, [:author_type, :author_id], name: 'index_active_admin_comments_on_author_type_and_author_id'
	end

**Comment by mrgenixus** [comment]
@ronnyworm FTW here. the UUID was my issue as well!
