### ISSUE TITLE
Cancancan and InheritedResources

### ISSUE THREAD

**Issue by runephilosof** [activeadmin/activeadmin#5261]
ActiveAdmin supports Cancancan, but Cancancan 2 [dropped support for InheritedResources](https://github.com/CanCanCommunity/cancancan/pull/370), which ActiveAdmin uses.
I haven't looked into how InheritedResources is used by ActiveAdmin. So I don't know if this causes any bugs, but I am guessing that it does.

I suggest either ActiveAdmin stops using InheritedResources, or remove the notice at the top of the InheritedResources README.md.

**Comment by varyonic** [comment]
Thanks Rune for reporting.  The README was updated when inherited_resources was transferred to the activeadmin organization last January.  The ticket to [stop using inherited_resources](#3604) has been open for three years now, I don't expect it to close any time soon.  As far as I can tell the CanCanCan 'support' was a performance optimization.  If you do find a bug feel free to reopen.
