### ISSUE TITLE
ActiveAdmin::Namespace label on each page

### ISSUE THREAD

**Issue by accessd** [activeadmin/activeadmin#5262]
I see `<div class="component">#&lt;ActiveAdmin::Namespace:0x00007fc58e305628&gt;</div>` on each page.

<img width="1429" alt="admin_users___babysnap" src="https://user-images.githubusercontent.com/592430/33484998-c1a14708-d6b5-11e7-9b3f-87d38291ec21.png">

Ruby 2.4.2
Rails 5.1.4
ActiveAdmin 1.1.0

### Expected behavior

There's no `ActiveAdmin::Namespace` label on each page

### Actual behavior

There's `ActiveAdmin::Namespace` label on each page

### How to reproduce

Nothing special

**Comment by zorab47** [comment]
Can you provide the contents of your `app/admin/admin_user.rb` file? You might have a stray value somewhere in the `index` block or odd input for a `filter`.

**Comment by accessd** [comment]
```
# frozen_string_literal: true
ActiveAdmin.register AdminUser do
  permit_params :email, :password, :password_confirmation

  index do
    selectable_column
    id_column
    column :email
    column :current_sign_in_at
    column :sign_in_count
    column :created_at
    actions
  end

  filter :email_cont, label: AdminUser.human_attribute_name(:email)
  filter :current_sign_in_at
  filter :created_at

  form do |f|
    f.inputs 'Admin Details' do
      f.input :email
      f.input :password
      f.input :password_confirmation
    end
    f.actions
  end
end
```

**Comment by accessd** [comment]
any updates?

**Comment by zorab47** [comment]
The code you posted looks fine. The issue must be in another file, like a template or model customization. Can you post other relevant files or provide a sample app demonstrating the issue?
