### ISSUE TITLE
`table_for` doesn't allow customizing the name of the `order` parameter.

### ISSUE THREAD

**Issue by MrJoy** [activeadmin/activeadmin#5277]
This is inconsistent with `paginated_collection`, which accepts `param_name`, and makes it impossible to have multiple sorted collections on a single page.

### Expected behavior

`table_for` (or any helper that can produce a sortable table) takes an optional parameter specifying the name of the parameter for ordering information, and utilizes that parameter when applying ordering to the collection.

### Actual behavior

`table_for(..., sortable: true)` can only be used meaningfully once on a page.

### How to reproduce

Simply try to have two sortable tables on a single page.

**Comment by MrJoy** [comment]
One thing that occurs to me is implementing this capability will be challenging in a way that preserves discoverability across related features.  `param_name` would be an obvious guess for someone using `paginated_collection` but that's fairly vague in context of `table_for`.  Having `order_param` for `table_for` and a `page_param` for `paginated_collection` might ease discovery for people who don't have the full docs in their head.

**Comment by zorab47** [comment]
What use case are you envisioning?

Sortable options are only supported on the columns defined in the resource `index` block. Implementation on tables defined elsewhere would require customization of controller actions and there are complexities where tables might overlap.

My solution to this in the past is using JavaScript to sort the table when all the data is visible.

**Comment by MrJoy** [comment]
My use-case is multiple lists on the show action of a related element.

I.E. given a model like this:

```ruby
class Foo < ApplicationRecord
    has_many :bar
    has_many :baz
end
```

I have an ActiveAdmin screen like this:

```ruby
ActiveAdmin.register Foo do
  show do
    attributes_table do
      # The usual stuff here...
    end

    panel 'Bars' do
      bars = foo
             .bars
             .order('bars.id DESC') # Hard-coded because I can't allow sorting with multiple tables due to param name collision
             .page(params[:page_bars])
             .per(10)
      paginated_collection(bars, param_name: :page_bars, download_links: false) do
        table_for(bars) do
          # Columns go here...
        end
      end
    end

    panel 'Bazs' do
      bazs = foo
             .bazs
             .order('bazs.id DESC') # Hard-coded because I can't allow sorting with multiple tables due to param name collision
             .page(params[:page_bazs])
             .per(10)
      paginated_collection(bars, param_name: :page_bazs, download_links: false) do
        table_for(bazs) do
          # Columns go here...
        end
      end
    end
end
```

I would _like_ to allow the user to adjust sorting of each table here, but cannot.  I _have_ succeeded in supporting pagination here, because `paginated_collection` already exposes an option to customize that.

**Comment by MrJoy** [comment]
For this use-case, pagination is just not optional:  We absolutely do NOT want to show some of these associations in their entirety here.  I.E. JavaScript-side ordering is not a viable workaround.  Our current workaround is just that one does not get to control the ordering here, so that pagination can be preserved.
