### ISSUE TITLE
'resource' method was lost in 'action_item'

### ISSUE THREAD

**Issue by nizovtsevnv** [activeadmin/activeadmin#5280]
In old versions of ActiveAdmin I used next notation:

```
  action_item only: [:edit, :show] do
    attributes = resource.attributes
    attributes.delete(:created_at)
    attributes.delete(:id)
    attributes.delete(:updated_at)

    link_to "Copy", new_admin_link_path(link: attributes)
  end
```

But now this code is not work because I have no 'resource' in the namespace.
What I need to use instead of it?

**Comment by varyonic** [comment]
I'm not aware of anything, can you narrow down when it stopped working for you?  Logic is in resource/action_items.rb

**Comment by nizovtsevnv** [comment]
I used gem version before, but now I use RoR5 and github branch by this line:
`gem 'activeadmin', github: 'activeadmin', ref: '5fce9ec3ceb57ba4eb85c3c3708231c1d572b235'`
Unfortunately I dont know why and when 'resource' was lost in this name space.

**Comment by varyonic** [comment]
0.6? 1.0?

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
