### ISSUE TITLE
Add a link in documentation to source

### ISSUE THREAD

**Issue by roberthopman** [activeadmin/activeadmin#5281]
Documentation can be improved [here](http://github-docs.activeadmin.info/2-resource-customization.html#renaming-action-items) with a link to [the source.](https://github.com/activeadmin/activeadmin/blob/master/config/locales/en.yml)

Please advise.

**Comment by varyonic** [comment]
Hmm, maybe. The idea is that you add changes to your local application config/locales/[en].yml for resources (entities) specific to your domain, but your link is to the version included in the gem, which does not and should contain such entries.  Perhaps "your local" should be added.

**Comment by roberthopman** [comment]
It took me about 1-2 hours before I understood what the exact options where of the config/locales/[en].yml file. I just typed them in my local yml file until something started to change on my screen. A link to the source as an example would have saved me that time.

**Comment by zorab47** [comment]
Closing in favor of PR #5327.
