### ISSUE TITLE
Override text of "Remove" button from has_many form builder for specified resource

### ISSUE THREAD

**Issue by newton10471** [activeadmin/activeadmin#5283]
There doesn't seem to be a straightforward way to change the text of the "Remove" button (to, in my case, something like "Hide") in the has_many form builder, .i.e., f.has_many, on a single page/model and not site-wide.  I just want to confirm that is the case.  If so, was there a specific reason this was left out?  I can submit a PR to make it changeable if that helps.

**Comment by varyonic** [comment]
Seems localized to me? https://github.com/activeadmin/activeadmin/blob/c1b2889bff016c54956d48624fa230ef0d5fb316/lib/active_admin/form_builder.rb#L110

**Comment by newton10471** [comment]
Hi @varyonic, that allows for site-wide changes, right?  I want to make a change to a single page / model.  Is there a way to do that that I'm missing?

**Comment by varyonic** [comment]
For a single model, eg. Offer, see if this works:
```ruby
en:
  active_admin:
    resources:
      offer:
        has_many_remove: 'Remove Offer'
```

**Comment by newton10471** [comment]
This works for site-wide if I change config/locales/en.yml:
```
en:
  active_admin:
    has_many_remove: 'Hide'
```
but I tried what you suggested above for two different models and it doesn't seem to like it :(.

**Comment by newton10471** [comment]
I'm using activeadmin 1.0.0.pre1, by the way.  Not sure if that makes a difference?

**Comment by varyonic** [comment]
Right, so further work is needed to make has_many remove button customizable in same way as action items. I don't think it was deliberately left out, just missed/forgotten.

**Comment by kazu9su** [comment]
I investigated this issue and found that `FormBuilder` becomes to depend on `Resource` to implement this feature(I guess it means `FormBuilder` depends on `Application`), but I wonder it is a correct approach or not.

I'd appreciate if I could listen to any opinion if you have.

**Comment by kazu9su** [comment]
@varyonic 
I investigated this issue and found that `FormBuilder` becomes to depend on `Resource` to implement this feature(I guess it means `FormBuilder` depends on `Application`), but I wonder it is a correct approach or not.

I'd appreciate if I could listen to any opinion if you have.

**Comment by littleforest** [comment]
Hi, I'd like to work on this ticket.
