### ISSUE TITLE
Method add_classes_to_body  not present in master branch

### ISSUE THREAD

**Issue by casecamp** [activeadmin/activeadmin#5288]
method add_classes_to_body from base class not present in current master branch, but it is there in previous branches and rails-5.2 branch

**Comment by varyonic** [comment]
Correct, it was replaced by `body_classes` in https://github.com/activeadmin/activeadmin/pull/5233/commits/dbac8811ee2b0ce3da80e76f2dbc121ab80d34a7 of 2.0.alpha. I considered it a private method and may be proposing another change shortly so I am interested to know how this impacts you.

**Comment by casecamp** [comment]
We have tried to use boolean_taggable with active admin, there gem raised errors.

**Comment by varyonic** [comment]
I'm not familiar with `boolean_taggable`, can you link to more info?

**Comment by varyonic** [comment]
I see, ActiveAdmin is being monkey patched by the plugin to add a feature switch: the PR to activeadmin_addons linked above should resolve the issue.

**Comment by xn** [comment]
@varyonic, is there some larger push to document what's public(and can be extended) or private (and cannot be extended) api?

**Comment by varyonic** [comment]
No. Monkey patch gems at your own risk.  IMHO if Platanus packaged select2 support as a separate gem they would not need to inject a flag to turn it off.

**Comment by varyonic** [comment]
Resolved by platanus/activeadmin_addons#172
