### ISSUE TITLE
Inputs Character count

### ISSUE THREAD

**Issue by misner** [activeadmin/activeadmin#5293]
**Feature Request: could we add Character count for inputs.**

Maybe I am wrong and it already exists but I looked for it for one of my RoR 4.2 app, and a lot of solutions exist, mostly on javascript/jquery but none seem to work/fit formtastic/rails.

I mostly see in this feature:

- Need to connect to Rails models to get the maximum length authorized in the Model

- Need to plug into formtastic inputs to show in "live" the number of characters typed and/or the remaining characters allowed (like on Twitter)

What do you think ? If it's not baked-in in Active Admin, are there recommended strategies or examples of successful implementations as all jquery "character count" I tried did not work on Active Admin (maybe due to formtastic?).

**Comment by varyonic** [comment]
This would be a good idea for a plugin. There are several other [jQuery based UI plugins](https://github.com/activeadmin/activeadmin/wiki/Plugins) you could look at for ideas.

**Comment by misner** [comment]
Hi, thanks for your answer.
I'd love to but i am more of a RoR beginner to be honest and would not be able to:(
Will do if one day become good enough.
