### ISSUE TITLE
Add items to default_actions column

### ISSUE THREAD

**Issue by chollier** [activeadmin/activeadmin#53]
Let's assume i have a member_action called approve, i'd loveto have a link beside the "View Delete Edit" actions

**Comment by krtschmr** [comment]
this needs some work!

**Comment by danishsatkut** [comment]
We can show multiple action items in the following way:

```ruby
actions defaults: false do |post|
    item 'View', admin_post_path(post), class: 'member_link'
    item 'Archive', archive_admin_post_path(post), class: 'member_link'
    item 'Publish', publish_admin_post_path(post), class: 'member_link'
end
```

The above code will not display the default links of `View`, `Edit`, `Delete` as we are passing `defaults: false` to `actions` method call. Also remember to add the class `member_link` which adds space between links.

**Comment by AlexVentura** [comment]
@danishsatkut Following your example, it work fine but I have a link to _**delete**_ with method set to `delete` like below but how to add a dialog box to confirm the _delete action_ by the user as in a normal `link_to` helper?

```
actions defaults: false do |user|
  item 'View', optumadmin_user_path(user), class: 'member_link'
  item 'Edit', edit_optumadmin_user_path(user), class: 'member_link'
  item 'Delete', optumadmin_user_path(user), class: 'member_link', method: :delete
end
```

**Comment by krtschmr** [comment]
@AlexVentura 

    item 'Delete', optumadmin_user_path(user), class: 'member_link', method: :delete, confirm: "Delete this item"

**Comment by AlexVentura** [comment]
@krtschmr @danishsatkut  Mmm it does not work for me!

**Comment by AlexVentura** [comment]
Now it works adding `data-` prefix:

```
item 'Delete', optumadmin_user_path(user), class: 'member_link', method: :delete, 'data-confirm': "Are you sure you want to delete this?"
```

Thanks!

**Comment by danishsatkut** [comment]
@AlexVentura Try this:

```
item 'Delete', optumadmin_user_path(user), class: 'member_link', method: :delete, data: { confirm: "Delete this item" }
```
