### ISSUE TITLE
specifying index download links

### ISSUE THREAD

**Issue by caifara** [activeadmin/activeadmin#5300]
While upgrading activeadmin (and Rails) I've spent more time than I would like to admit to figure out that I now need to specify download_links as an array of symbols where I had an array of strings. In earlier versions of AA I apparently used both.

Afterwards this is all obvious, and I see that the thrown error has a legitimate reason (AccessDenied), but maybe AA can call :to_sym on the given download_links, or maybe use the error message to tell the dev why this problem occurs?

**Comment by zorab47** [comment]
That would probably be the right approach since the input values are expected to be symbols.

**Comment by caifara** [comment]
It sure is, but the error does not state that as the problem. It just says throws an UnknownFormat error. Which, again, in retrospect is allright. It would also be alright if I were to encounter this problem while developing that single thing. However, during an upgrade from Rails 3 to Rails 4 this took me quite some time.

I expect this issue will come up when someone encounters this problem as I did, so that would probably be enough. Closing the issue.

**Comment by varyonic** [comment]
Help with the [upgrade notes on the wiki](https://github.com/activeadmin/activeadmin/wiki/Upgrading-ActiveAdmin) welcome.

**Comment by caifara** [comment]
Just looked on my pull request on the internal app. I did upgrade AA from 1.0.0.pre4 to 1.0.0, but I think the problem is only due to the upgrade from R3 to R4. I can add a new section for this issue to the wiki for Rails upgrades if that's allowed.
