### ISSUE TITLE
Overriding active admin session controller  Ask

### ISSUE THREAD

**Issue by rjsnh1522** [activeadmin/activeadmin#5303]
I need to add two factor authentication for active admin. Whenever admin tries to login I need to verify them before giving access. Verification can be done either by sending OTP to email or mobile. So I need to over ride the Sessions controller for active admin devise so that I can add the functionality to it. I found a solution which said that we can do that inside initializers folder. I over ride the create method and its working fine.

**#config/initializers/active_admin_devise_sessions_controller.rb**

 **class ActiveAdmin::Devise::SessionsController
   include ::ActiveAdmin::Devise::Controller
   def create

   if params[:admin_user].present? 
    email = params[:admin_user][:email]
    password = params[:admin_user][:password]
    admin_user = AdminUser.find_by_email(email)
    if admin_user.present? && admin_user.valid_password?(password)
    @admin_user = admin_user
    redirect_to verification_method_path
    end
   else
     flash[:error] = "No User Found"
     redirect_to :back
   end

  end

  def verification_method

  end

end**
now my problem is I want to add few methods so I can render some views for verification process for login. And I am not able to add any custom routes for active admin in session controller so I can call it and use as needed.

my active admin routes

  **devise_for :admin_users,ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)**
my custom GET route to render second form for login verification

#active admin session controller verification routes

 **get '/admin/verification_method' => 'active_admin/devise/sessions#verification_method', via: :get, as: "verification_method"**
I didnt find anything similar to my problem. Please guide me how can this be done.

**Comment by varyonic** [comment]
No need to [cross post from StackOverflow](https://stackoverflow.com/questions/48061303/overriding-active-admin-session-controller), I see you are getting responses already.  Please use GitHub for bugs and feature requests.

**Comment by rjsnh1522** [comment]
but that reply is irrilivant to my problem. thats why i asked in github.. i
see that as an issue cuz i m not able to override things
