### ISSUE TITLE
Unable to set ID for items in attributes_table in version 1.2.0

### ISSUE THREAD

**Issue by louffoster** [activeadmin/activeadmin#5304]
#### After updating to version 1.2.0 with rails 5.1.4 and ruby 2.4.1, I can no longer set the ID attribute of elements within an attribute table rendered from an .html.arb file.

Example .arb snippet:

`attributes_table_for order do`
`   row :units do |order|`
`      link_to "#{order.units.size}", admin_units_path(:q => {:order_id_eq => order.id}), {id: "order-units-link"}`
`   end`
`end`

Expected result is something like this:
`<a id="order-units-link" href="/admin/units?q%5Border_id_eq%5D=10145">29</a>`

Actual result is this (missing the ID):
`<a href="/admin/units?q%5Border_id_eq%5D=10145">29</a>`

The same code produces the expected results with version 1.1.0

**Comment by faucct** [comment]
Fixed [here](https://github.com/activeadmin/activeadmin/pull/5299).

**Comment by deivid-rodriguez** [comment]
@louffoster Can you confirmed this is fixed in master now?

**Comment by louffoster** [comment]
Pulling master gives me version 2.0.0.alpha. My application won't even launch when that version is used. Can't verify fix.

**Comment by varyonic** [comment]
@louffoster Does v1.2.1 resolve this?

**Comment by louffoster** [comment]
Yes. It is fixed in 1.2.1. Thanks

**Comment by durcak** [comment]
HI, after updating to version 2.2.0 with rails 6.0.0 and ruby 2.6.2 I am getting similar error

from: `.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activeadmin-2.2.0/app/views/active_admin/resource/index.html.arb where line #2 raised:
Can't be in the context of nil. [, <!DOCTYPE html><html lang="en">` 

Can anyone please help?
