### ISSUE TITLE
Unable to output HTML in index table view

### ISSUE THREAD

**Issue by cannikin** [activeadmin/activeadmin#5305]
### Expected behavior

Should be able to output HTML in an index table if marked `html_safe`. This worked in 1.1.0.

### Actual behavior

HTML, even marked `html_safe` is not rendered. This started in 1.2.0.

### How to reproduce

Override the index action and have a column output HTML:

```ruby
  index do
    selectable_column
    column :id
    column :created_at do
      '<time>12:00</time>'.html_safe
    end
```

Output:

```html
<td class="col col-current_login_at">12:00</td>
```

Was there an HTML whitelist added maybe? I didn't see a mention of one in the CHANGELOG but some tags like `<b>` seem to render okay. 

I can put together a test case file if someone thinks that will help, let me know.

**Comment by faucct** [comment]
Fixed here - https://github.com/activeadmin/activeadmin/pull/5299

**Comment by cannikin** [comment]
@faucct I'll keep an eye on that PR, thanks!
