### ISSUE TITLE
Allow accessing active admin default attributes outside of library

### ISSUE THREAD

**Issue by johnmcconnell** [activeadmin/activeadmin#5310]
In this file: https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource/attributes.rb

The default attributes of a given active record class are defined. I would like to use these same default attributes in my view code however I want to customize the attributes table (with some ui tweaks). I would like to be able to use the same attributes active-admin is aware of and be able to customize the specific items that require more customization. Currently, I am using ruby's reflection api to accomplish this task. However, being able to pass the `resource_class` to the `default_attributes` function would be helpful. For example:
```ruby
      def default_attributes(rc = nil)
        (rc || resource_class).columns.each_with_object({}) do |c, attrs|
          unless reject_col?(c)
            name = c.name.to_sym
            attrs[name] = (method_for_column(name) || name)
          end
        end
      end
```

I realize there is a cached method:
```ruby
      def foreign_methods
        @foreign_methods ||= resource_class.reflect_on_all_associations.
          select{ |r| r.macro == :belongs_to }.
          reject{ |r| r.chain.length > 2 && !r.options[:polymorphic] }.
          index_by{ |r| r.foreign_key.to_sym }
      end
```
that will also need to be changed.

Let me know what you think. Thanks

**Comment by johnmcconnell** [comment]
I'm looking at the test code being able to get the default namespace should also be sufficient:
https://github.com/activeadmin/activeadmin/blob/master/spec/unit/resource/attributes_spec.rb

```ruby
    let(:application) { ActiveAdmin::Application.new }
    let(:namespace) { ActiveAdmin::Namespace.new application, :admin }
    let(:resource_config) { ActiveAdmin::Resource.new namespace, Post }
```

**Comment by zorab47** [comment]
I have a helper module used to simplify introspecting ActiveAdmin in tests. Is this the type of solution you are seeking?

```ruby
module ActiveAdminHelper
  def active_admin_application
    ActiveAdmin.application
  end
  module_function :active_admin_application

  def active_admin_resources
    active_admin_application
      .namespace(:admin)
      .resources
      .select { |r| r.class <= ActiveAdmin::Resource }
  end
  module_function :active_admin_resources

  def active_admin_resource(klass)
    active_admin_resources
      .find { |r| r.try(:resource_class) == klass }
  end
  module_function :active_admin_resource

  def active_admin_pages
    active_admin_application
      .namespace(:admin)
      .resources
      .select { |r| r.class <= ActiveAdmin::Page }
  end
  module_function :active_admin_pages
end
```

**Comment by varyonic** [comment]
Looks like a good approach to me.
