### ISSUE TITLE
Can't set navigation_menu depending on optional belongs_to

### ISSUE THREAD

**Issue by DuBistKomisch** [activeadmin/activeadmin#5313]
Using activeadmin 1.0.0 but can't see anything around this behaviour which has changed since then.

```
  belongs_to :organisation, optional: true
  navigation_menu do
    @organisation ? :organisation : :default
  end
```

### Expected behavior

Switch to parent navigation menu when accessing the resource via the parent, but use the global default menu when accessed directly.

### Actual behavior

Always `:default` because `@organisation` is always `nil`, unlike most other places, e.g. a filter's `if` proc. Seems like it's run in the context of the controller class unlike others. Maybe I'm just missing a better way to detect how it's being accessed?

### How to reproduce

See above code.

**Comment by zorab47** [comment]
The instance variable `@organisation` may not be available at that point in the request because the resource is lazy loaded. Try either calling the method `organisation` or the method `resource`?

```ruby
navigation_menu do
  organisation ? :organisation : :default
end
```

or

```ruby
navigation_menu do
  resource ? :organisation : :default
end
```

**Comment by DuBistKomisch** [comment]
Sorry, I should have mentioned I already tried those:

```
[1] pry(Admin::UsersController)> @organisation
=> nil
[2] pry(Admin::UsersController)> organisation
NameError: undefined local variable or method `organisation' for Admin::UsersController:Class
from (pry):5:in `block (2 levels) in <top (required)>'
[3] pry(Admin::UsersController)> resource
NameError: undefined local variable or method `resource' for Admin::UsersController:Class
from (pry):6:in `block (2 levels) in <top (required)>'
```

Problem is the block is run in the context of the controller class, not an instance (so makes sense the instance variable won't exist), unlike most blocks elsewhere. Thanks anyway.

**Comment by rosendi** [comment]
Same issue.  There is no way to conditionally set the navigation menu depending on the request.

@DuBistKomisch do you have any solutions?

**Comment by DuBistKomisch** [comment]
@rosendi sorry but I never found even a workaround for this, just kept our menu more basic. We've since retired our AA interface in favour of a React SPA anyway.

**Comment by rosendi** [comment]
@DuBistKomisch thank you for the quick answer.

**Comment by rikas** [comment]
I'm having the same problem, is there any workaround?
