### ISSUE TITLE
skip-comments flag on install

### ISSUE THREAD

**Issue by dkniffin** [activeadmin/activeadmin#5322]
Most of the time, when using AA, I don't use comments. Right now, whenever I add AA to a project, I have to go back and delete the migration and add `ActiveAdmin.setup { |config| config.comments = false }` to my initializer. It'd be nice to have a way to disable have these steps done for me automatically with a command-line flag

### Expected behavior

`rails g active_admin:install --skip-comments` would prevent the migration from being created, and it would set `comments = false` in the initializer config.

### Actual behavior

`--skip-comments` is not a supported flag.

**Comment by croz1007** [comment]
@dkniffin Hate to ping you like this, but I am looking for some help.
I literally just ran this installer with the `--skip-comments` flag and it still created the migrations. Also, if I remove the migrations and then migrate my DB this gem is still creating the comments table. Any ideas why is this?

**Comment by dkniffin** [comment]
@croz1007 it's because there hasn't been a release with this change yet.

cc @Fivell can we get a version bump?

**Comment by croz1007** [comment]
@dkniffin Sounds good. I thought I had seen that release. I'll keep an eye out for it. Thanks for the response and the work you did to put in this correction.

**Comment by rusterholz** [comment]
Would it be possible for some information on this flag to be added to [the installation docs](https://activeadmin.info/0-installation.html)? Currently they mention the `--skip-users` option, but they don't mention `--skip-comments` at all, so I didn't even know I should use it until I saw the migration turn up in git and googled to find this issue.

**Comment by javierjulio** [comment]
@rusterholz sure, that's a great idea. We'd accept a PR to add that in.
