### ISSUE TITLE
has_many-partial duplicates all following fields when using haml in the form

### ISSUE THREAD

**Issue by Joerg-Seitz** [activeadmin/activeadmin#5326]
### Expected behavior

The partial should offer the possibility to add multiple objects of it's type. It should be a partial and leave the other parts of the form how they are.

### Actual behavior

It duplicates every following field in the form, even fields from other objects.

### How to reproduce

Partial:
```
# we're in 'admin/students/_form'

- f.has_many :students, allow_destroy: true, new_record: true, heading: false do |student|
  - student.input :student_name
  - student.input :age
```

Form:
```
= semantic_form_for [:admin, @school], builder: SmacssFormBuilder do |f|

  = f.inputs "School" do
    = f.input :name
    = f.input :opens_at,     as: :time_select
    = f.input :closes_at,    as: :time_select

  = f.inputs "students" do
    = render partial: 'admin/students/form', locals: { f: f }

  = f.actions class: 'full_width'
```

If the form is arranged like above, everything seems to work fine and everything looks as it should.
However moving the call to render the partial up, like in the following code, causes every following field in the form to duplicate. 
```
= semantic_form_for [:admin, @school], builder: SmacssFormBuilder do |f|

  = f.inputs "students" do
    = render partial: 'admin/students/form', locals: { f: f }

  = f.inputs "infos" do
    = f.input :name
    = f.input :opens_at,     as: :time_select
    = f.input :closes_at,    as: :time_select

  = f.actions class: 'full_width'
```

So with the code above the form would look like this:
```
name: 
name:

opens_at:
opens_at:

closes_at:
closes_at:
```

I investigated a bit and it seems the duplication is caused by the following line:
https://github.com/activeadmin/activeadmin/blob/fed8657252d147253f4a4171f06b4371253ed9f6/lib/active_admin/form_builder.rb#L67

Setting it to false gets rid of the duplication but prevents some of the fields in the has_many partial from rendering.

**Comment by varyonic** [comment]
I'm not optimistic issues like has_many partials are fixable given the current implementations of Formtastic vs. Arbre.  My advise is to use Arbre instead of Haml here.

**Comment by mackermedia** [comment]
FWIW: I'm not using haml, but am doing the same thing in a rendered form partial and seeing the same results :-/

**Comment by varyonic** [comment]
My advise is not that you should avoid Haml.  My advise is that you should use Arbre instead of Erb, Erubi, Haml, Slim or any other ActionView based template engine, especially and in particular for has_many partials. Maybe it can and should be fixed, but that is the way it currently is.

**Comment by mackermedia** [comment]
@varyonic : Thanks for your reply. However, I'm using an ERB partial, and not HAML. :-/

**Comment by mackermedia** [comment]
Just found something interesting: 
When I was using the following style, I was getting duplicates in the form:
```
<%= f.has_many :somethings do |sf| %>
  <%= sf.input :thing
<% end %>
```

When I changed it to not outputting via ERB the duplicates went away:
```
<% f.has_many :somethings do |sf| %>
  <% sf.input :thing
<% end %>
```

**Comment by NicholasHazen** [comment]
@mackermedia Thanks! This fix worked for me. It was actually hard to find this solution.
