### ISSUE TITLE
Not updating model

### ISSUE THREAD

**Issue by BobWalsh** [activeadmin/activeadmin#5328]
after adding permit_params to an ActiveAdmin.register, I get 
`Unpermitted parameters: :question, :answer, :citation_title, :citation_url, :keycaps, :gif_url, :description, :frontpage, :frontpage_datetime(1i), :frontpage_datetime(2i), :frontpage_datetime(3i), :frontpage_datetime(4i), :frontpage_datetime(5i), :published`
when updating the record from activeadmin. 
Error does not get thrown from regular controller.
These are the correct attributes

My code:

`ActiveAdmin.register Flashcard do
#### https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#setting-up-strong-parameters

  permit_params :user_id , :question, :answer, :citation_title, :citation_url, :keycaps, :gif_url, :description, :frontpage, :frontpage_datetime, :published

end
`

**Comment by varyonic** [comment]
This question is better suited on [StackOverflow](https://stackoverflow.com/questions/tagged/activeadmin).
I'm not trying to ignore the problem you're having. We can still solve it, but it would be more readily available for others with your same problem if we were solving it on [StackOverflow](https://stackoverflow.com/questions/tagged/activeadmin).
