### ISSUE TITLE
proc{xxx} in Filter.label is not executed in Search Status sidebar

### ISSUE THREAD

**Issue by xhero** [activeadmin/activeadmin#5329]
I've been researching this for a couple days now and did not find any other indications, sorry it is it a dup.
I just updated to AA 1.2.0 from 1.1.0. I have many filters with custom labels and i18n, the all look more or less like this:

```ruby
filter :updated_at, :label => proc{I18n.t(:updated_at)}, as: :date_range
```
I use `proc{xxx}` because the user can select the language from a menu and needs to be re-evaluated (It is still in the docs so I hope it is still the correct way).

In the filters sidebar, the element pops up correctly with the correct label, In the "Search Status" it always displays as `#<Proc:0x007fb6bf2eb3f0@...etc>`

Im not sure why. I looked into `ActiveAdmin::Filters::ActiveFilter` and indeed the label is just cast to a string without executing the proc. I'm unsure why in the Filters it is OK since I could not trace that.

I made a small patch to ActiveFilter so the proc gets executed and it works, but I'm unsure this is the right way to do it:

```ruby
      def filter_label
        return unless filter

        if filter[:label].is_a? Proc
          filter[:label].call
        else
          filter[:label]
        end
      end
```

**Comment by varyonic** [comment]
Try 1.2.1, we did ship a related patch.

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded.  Please feel free to leave a comment requesting this issue be reopened if needed.
