### ISSUE TITLE
Preserve 'order' and 'page' when executing batch_actions

### ISSUE THREAD

**Issue by ppsshh** [activeadmin/activeadmin#5335]
Right now, we have this line in file https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource/routes.rb#L68

    query = params.slice(:q, :scope)

which preserves only `:q[]` (various filters) and currently selected `:scope`. Any other parameters, such as `:order` (sort order) and `:page` are omitted. That's why when you apply any batch action, you will always be redirected to first page with default sort order.

Is there any particular reason not to include `:order` and `:page` keys to this list? If not, will it be possible to include them there? I can make a PR for that.

**Comment by varyonic** [comment]
Related? #3833 #4746

**Comment by Fivell** [comment]
@ppsshh  because when redirecting to same page and scope can return zero records after performing batch action , that can be tricky for customer.

**Comment by ppsshh** [comment]
@Fivell that makes sense, but keeping `:q` and `:scope` is also enough to get zero results in some cases, yet these parameters are preserved, though user can decide to keep them or not. Why not to allow the same for other parameters as well?

@varyonic hmm... yes, pretty much. But don't that issue should be closed? Because `:scope` is actually already preserved since this 775aaf0217e5505f18ca9a20cfbd7826a7806ac2 commit

**Comment by ppsshh** [comment]
For those who are interested, here is workaround for this issue, which helped me to preserve all applied filters:

```ruby
  batch_action :flag do |ids|
    batch_action_collection.find(ids).each {|post| post.flag!(:hot)}
    redirect_to request.referer, notice: "The posts have been flagged."
  end
```

There, `redirect_to request.referer` will do the trick.

**Comment by ngelx** [comment]
OMG, `request.referer` made my day. 

In combination with batch_action_form is a quick and simple solution to make modals forms and continue in the same page after submit.

```ruby
batch_action :do_x, form: -> { {  ....  } } do |ids, inputs|
    ....
    redirect_to request.referer, notice: 'X Done!'
end
```

Closing the dialog and displaying the messages seems to be a better solution, but i could not get `batch_action :do_x, form: -> { {  ....  } }, remote: true do |ids, inputs| ` to work and send a AJAX request.

Anyway, not a bad solution.
