### ISSUE TITLE
Actions not working for paranoid items

### ISSUE THREAD

**Issue by 8vius** [activeadmin/activeadmin#5338]
I'm using the [paranoia gem](https://github.com/rubysherpas/paranoia) with makes my selected models act as paranoid and grants me the `with_deleted` scope so I can search for deleted items. 

I've added `scope :with_deleted, default: true` to my admin model and on the index page it works fine, listing all the deleted objects, yet when I try to execute an action I do get not found error. Looking at the output in the console it is in fact not using the default scope I have specified and is searching only on non-deleted objects. 

How can I make actions work with paranoid models?

**Comment by ndbroadbent** [comment]
In case anyone else finds this issue, you should check out the active_admin_paranoia gem, which handles all of these behaviors: https://github.com/raihan2006i/active_admin_paranoia
