### ISSUE TITLE
undefined method alias_method_chain

### ISSUE THREAD

**Issue by bengalamx** [activeadmin/activeadmin#5339]
I keep getting the error:

`Gem Load Error is: undefined method 'alias_method_chain' for #<Class:ActiveRecord::Associations::JoinDependency>`

I have followed every single step i have searched in the web without any success. 6 hours now and no progress.

**Comment by zorab47** [comment]
Without more information it is hard to help, however, it appears to be related to Rails and possibly and load order issue.

1. What version of ActiveAdmin, Ruby, and Rails?
1. What does your Gemfile contain?
1. Can you provide a sample app that reproduces the issue?

**Comment by zorab47** [comment]
Please reopen when more info is available.
