### ISSUE TITLE
undefined method '<<' for nil:NilClass

### ISSUE THREAD

**Issue by geeofree** [activeadmin/activeadmin#5354]
I have two models that has a `has_one` and `belongs_to`  association with one another i.e

```ruby
class User < ActiveRecord::Base
    has_one :hammer, dependent: :destroy
    accepts_nested_attributes_for :hammer, allow_destroy: true
end

class Hammer < ActiveRecord::Base
    belongs_to :user
end
```

After creating said models, I went on to make a form with these nested models following the documentation for it. However, I couldn't do so because I keep having this `undefined method '<<' for nil:NilClass` error that points to this particular code on the stacktrace

![](https://user-images.githubusercontent.com/17492631/36242754-91304f2c-1258-11e8-9dac-5271d4303a9e.png)

Snippet of the code I'm using that makes this happen:

```ruby
form do |f|
    f.inputs 'User Information' do
        # user information inputs
    end

   f.inputs 'Hammer Information' do
       # below is where the error happens
       f.has_many :hammer do |h|
       end
   end
end
```

Is there anyway I can fix this?

Version of ActiveAdmin and Rails I'm currently using if it's needed:  
* activeadmin (1.0.0pre1)
* activeadmin_addons (1.2.0)
* Rails 4.2.6

Thanks in advance!

**Comment by geeofree** [comment]
Closing.. Updating the gem to `1.2.1` fixed it. Sorry 😅

**Comment by geeofree** [comment]
Reopening: Had to rollback to `1.0.0.pre1` because I was advised by my team lead that it had broke a lot of dependencies on the project.

Is there anyway to fix this with the `1.0.0.pre1` version, or at least versions that could fix it without breaking dependencies perhaps?

Thanks again.

**Comment by varyonic** [comment]
I don't think there is any interest in back-porting to a pre-release. You will have better luck opening a fresh issue concerning dependencies.

**Comment by geeofree** [comment]
@varyonic okay, will do. Thanks!

**Comment by geeofree** [comment]
Closing again. No other solution than to upgrade along with missing dependencies. :sweat_smile: :turtle:

**Comment by pragun16** [comment]
This thread is the only place I found my exact problem discussed but sadly upgrading was not a solution in my case. I opted generating the nested attribute form like this which worked.
```
f.inputs "Field", for: [:model_name, f.object.<model_name> ] do |p|
   p.input :field1
   p.input :field2
end
```
