### ISSUE TITLE
Can't log in after switching to windows - wrong query

### ISSUE THREAD

**Issue by gioknx** [activeadmin/activeadmin#5356]
I switched to Windows from a Mac (yeah, I know).

I'm running the rails server on bash in Windows and it works fine.

However, when I try to log into my activeadmin account, I get this error:

```
    ActiveRecord::StatementInvalid in ActiveAdmin::Devise::SessionsController#create

    Mysql2::Error: Unknown column 'admin_users.' in 'where clause': UPDATE `admin_users` SET `current_sign_in_at` = '2018-02-20 01:19:28', `current_sign_in_ip` = '127.0.0.1', `last_sign_in_at` = '2018-02-18 16:12:56', `sign_in_count` = 16, `updated_at` = '2018-02-20 01:19:28' WHERE `admin_users`.`` = 12
```

It should be admin_user.id in the where clause, not just admin_user.

I can't find out why is this happening and how to solve it.

**Comment by gioknx** [comment]
Everything is default. I dropped, reseted and reran the migrations and it worked fine!

Don't know what caused the issue, but now its working. Thank you very much!

**Comment by varyonic** [comment]
Cross posted from [StackOverflow](https://stackoverflow.com/questions/48876599/activeadmin-is-trying-to-update-the-wrong-column-on-log-in)
