### ISSUE TITLE
activestorage helper `direct_upload: true`

### ISSUE THREAD

**Issue by pynixwang** [activeadmin/activeadmin#5365]
### Expected behavior

generate `data-direct-upload-url` attribute.

### Actual behavior

nothing.

### How to reproduce

`f.input :image, as: :file, direct_upload: true`

maybe activeview helper is not usable in activeadmin,  I can use partial form, but it 's look is not AA.

now I use `input_html: { "data-direct-upload-url": rails_direct_uploads_url }`, but it 's ugly.

**Comment by varyonic** [comment]
Isn't this a [Formtastic issue](https://github.com/justinfrench/formtastic/issues)?

**Comment by pynixwang** [comment]
@varyonic maybe, I got when I opened this.

**Comment by juggleross** [comment]
You need to use `direct_upload: true` inside the `input_html` attribute:
`f.input :image, as: :file, input_html: { direct_upload: true }`

**Comment by fedeagripa** [comment]
I'm using the above code but my direct upload is not working, check my generated input data-direct-upload link, it seems wrong (not s3, besides I only have s3 configured as a storage option)
![Screen Shot 2021-04-14 at 15 32 20](https://user-images.githubusercontent.com/23194751/114913898-184bc080-9df8-11eb-8d11-45c6cf34b611.png)

And here is my form input code just in case:
```
f.inputs do
  f.input :public_videos, as: :file, input_html: { multiple: true, direct_upload: true }
end
```

**Comment by acflint** [comment]
@fedeagripa the data-direct-upload-url is supposed to be your server's direct_upload endpoint. The URL you're seeing generated in that screenshot is correct. Watch your network requests when you submit it, and you'll see that part of the response from the direct_upload endpoint includes the S3 URL to upload the file to.
