### ISSUE TITLE
Testing member_action with rspec

### ISSUE THREAD

**Issue by mxdavis** [activeadmin/activeadmin#5371]
Hi, 

I am trying to test a custom controller created with Active Admin member_action.

```
member_action :create_activity, method: :post do
   ...
end
```

In my rake routes I have 
`create_activity_admin_product_round POST     /admin/product_rounds/:id/create_activity(.:format)                                                 admin/product_rounds#create_activity`

So clearly the route exists. If I do `create_activity_admin_product_round(product_round)` I get a generated link.

From within my test which is set up like so:

```
require 'rails_helper'

RSpec.describe Admin::ProductRoundsController, type: :controller do
  include Devise::TestHelpers
  render_views
```

If I try `post :create_activity` I get `ActionController::UrlGenerationError: No route matches {:action=>"create_activity", :controller=>"admin/product_rounds"}`

And if I do `post :create_activity, id: product_round.id` I get `NoMethodError: undefined method `[]' for nil:NilClass` (there has been a product_round previously defined...)

Tried googling a ton nothing seems to help. My next step was to create a resource test instead of a controller test, but posting here in case anyone has any insights.

(show, index, destroy, and create tests are all working)

**Comment by varyonic** [comment]
This question is better suited on [StackOverflow](https://stackoverflow.com/questions/tagged/activeadmin).
I'm not trying to ignore the problem you're having. We can still solve it, but it would be more readily available for others with your same problem if we were solving it on [StackOverflow](https://stackoverflow.com/questions/tagged/activeadmin).

Have you considered [request specs instead of controller specs](https://everydayrails.com/2016/08/29/replace-rspec-controller-tests.html)?

**Comment by mxdavis** [comment]
Thanks, I will post it there. Was thinking of switching it to request, started it out as controller since the core of my tests were copied from active admin documentation using controller spec.

**Comment by TiSer** [comment]
@mxdavis Did you find the answer? Place a link here, please.

**Comment by mxdavis** [comment]
@TiSer Yes. I am using a request spec. Looks something like this:

```
describe "POST create_decision" do
    context "with valid params" do
      let(:activity) { create(:activity, name: "New Activity") }

      let(:valid_decision_attrs) do
        {
          "decision": {
            name: "New Decision"
          }
        }
      end

      let(:create_decision) do
        "#{url}/#{activity.id}/create_decision"
      end

      it "creates a new Decision" do
        expect { post create_decision, valid_decision_attrs }
          .to change(Decision, :count).by(1)
      end
  end
end
```

**Comment by TiSer** [comment]
@mxdavis Hm, doesn't work for me. I still have `ActionController::UrlGenerationError: No route matches` :(

**Comment by TiSer** [comment]
@mxdavis Ouh, the truth is yours, I forgot about `type: :request do`.

And by which way you are logging in as admin? I was using `include Devise::Test::ControllerHelpers` before, but with request spec it seems doesn't work.

**Comment by mxdavis** [comment]
I had to add this in myself and include in the rails_helper. We are no longer using devise so it's been deleted, but it should be easy to google. If you can't find it I can search through the history of the repo

**Comment by TiSer** [comment]
https://github.com/plataformatec/devise/wiki/How-To:-sign-in-and-out-a-user-in-Request-type-specs-(specs-tagged-with-type:-:request)

**Comment by mxdavis** [comment]
Cool, assuming all is working now then.

**Comment by TiSer** [comment]
@mxdavis Yes, thank you!
