### ISSUE TITLE
How can I use `current_user` method in app/admin/user.rb ?

### ISSUE THREAD

**Issue by yuji-for-co** [activeadmin/activeadmin#5372]
Hi there, I've tried to use "current_user" method in app/admin/user.rb like below codes.
```
ActiveAdmin.register User do
  if current_user.role == :admin
     filter :id
     filter :display_name
     filter :email
  end
end
```

then an error comes up.
```
app/admin/users.rb:2:in `block in <top (required)>': undefined local variable or method `current_user' for #<ActiveAdmin::ResourceDSL:0x00007feb5a3aea10> (NameError)
```

In config/initializers/active_admin.rb, I set below.
```
  config.authentication_method = :authenticate_user!
  config.current_user_method = :current_user
```

Hope someone gives me a solution for this problem.

**Comment by varyonic** [comment]
This question is better suited on [StackOverflow](https://stackoverflow.com/questions/tagged/activeadmin).
I'm not trying to ignore the problem you're having. We can still solve it, but it would be more readily available for others with your same problem if we were solving it on [StackOverflow](https://stackoverflow.com/questions/tagged/activeadmin).

The register block is run during application start-up, not during each HTTP request, so you will not be able to access `current_user` like that.  However, I think `filter` accepts `:if` and `:unless` options so you can try:
```
  filter :id if: proc{ current_user.role == :admin }
```

**Comment by yuji-for-co** [comment]
Thank you for the comment
