### ISSUE TITLE
 How can I separate actions Depending on user's status?

### ISSUE THREAD

**Issue by yuji-for-co** [activeadmin/activeadmin#5374]
I want separate actions Depending on user's status, but I dont know how.
I already tried below.

```
ActiveAdmin.register User do
  disable_actions = [ :new, :create, :edit, :update]
  # this if statement doesn't work...
  disable_actions.push(:destroy) if proc {current_user.role == 'admin'}
  actions :all, except: disable_actions
```
these also doesn't work. 
```
ActiveAdmin.register User do
  controller do 
    disable_actions = [ :new, :create, :edit, :update]
    # this if statement doesn't work...
    disable_actions.push(:destroy) if proc {current_user.role == 'admin'}
    actions :all, except: disable_actions
  end

  or 

  actions :index if proc{current_user.role == 'admin'}
  actions :index, :show if proc{current_user.role == 'staff'}
end
```

Also I read this issue. When talking about this issue, active admin didn't support this issue.
Does active admin correspond to this function in this version?
https://github.com/activeadmin/activeadmin/issues/341

**Comment by zorab47** [comment]
I suggest using an authorization library to handle access to specific resources. See the Authorization Adapter documentation for more info.

https://github.com/activeadmin/activeadmin/blob/master/docs/13-authorization-adapter.md

**Comment by kamille-321** [comment]
I solved it by before_action. Thank you.

**Comment by yuji-for-co** [comment]
I can do this by using before_action. thank you!

**Comment by nbalsamo** [comment]
@kamille-c  how did you do this with a before action?
