### ISSUE TITLE
input_html option for filter as a proc is only evaluated once

### ISSUE THREAD

**Issue by kjeldahl** [activeadmin/activeadmin#5377]
### Expected behavior

When I specify `filter :name, html_input: proc { current_scope.&id == :all ? {autofocus: true} : {}}` 
I expect the proc to be evaluated each time the filter form is rendered.

### Actual behavior

It is only evaluated one time and the result is stored and never updated.

I have added a pull request with a solution: #5376

**Comment by Origa7jeffrey** [comment]
#5377 Keeps filiter input_html as an online database

**Comment by deivid-rodriguez** [comment]
@Origa7jeffrey Can you elaborate a bit? What do you mean?
