### ISSUE TITLE
Batch action drop down doesn't disable if there are no batch actions.

### ISSUE THREAD

**Issue by Rohan--** [activeadmin/activeadmin#5382]
### Expected behavior

When there are no batch actions, the batch action drop down should be disabled.

### Actual behavior

The batch action drop down is enabled and I can see a little black arrow/circle with no menu. (Image: https://imgur.com/a/m4kg8)

### How to reproduce

Have batch actions where the proc equates to false.

```
config.batch_actions = true

# remove default batch action
batch_action :destroy, false

batch_action :authorise, if: proc { false } do |selection|
    # Since the proc is false, this action won't be shown and we will have no batch actions
end

```

**Comment by RohanSharma1994** [comment]
In, activeadmin/app/assets/javascripts/active_admin/lib/batch_actions.es6 line #43

```
 $(document).on('change', '.paginated_collection :checkbox', function() {
      if ($(".paginated_collection :checkbox:checked").length) {
        $(".batch_actions_selector").each(function() { $(this).aaDropdownMenu("enable"); });
      } else {
        $(".batch_actions_selector").each(function() { $(this).aaDropdownMenu("disable"); });
      }
    });
```

We should check whether $('.dropdown_menu_list') has any children along with the length before enabling the dropdown.

**Comment by Fivell** [comment]
@varyonic  maybe if there is no children , the  batch action drop down should be invisible ?
