### ISSUE TITLE
action_item redesign and reposition

### ISSUE THREAD

**Issue by eebasadre20** [activeadmin/activeadmin#5392]
Is there a way to redesign the action_item button? and also change the position?

**Comment by varyonic** [comment]
You can restyle any element using your active_admin.css. If you can't get the layout change you want using CSS you can override the classes in [active_admin/views](https://github.com/activeadmin/activeadmin/tree/master/lib/active_admin/views), but I don't recommend it. If you want to do a lot of redesign perhaps ActiveAdmin is not the right tool to use.

**Comment by varyonic** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or reopen this issue. Thanks!
