### ISSUE TITLE
Railties stuck on (< 5.2, >= 4.2) in activeadmin.gemspec which fails for rails 5.2

### ISSUE THREAD

**Issue by clairity** [activeadmin/activeadmin#5393]
i get a bundler error when trying to use rails 5.2 because activeadmin specifies railties less than 5.2:

https://github.com/activeadmin/activeadmin/blob/e2af261544f9965a0c197ab00e1465bc83011058/activeadmin.gemspec#L27

can this be changed to accomodate the recent rails (and railties) 5.2 release?

**Comment by pynixwang** [comment]
I try again on tag v1.2.1, it works.
`gem 'activeadmin', github: 'pynixwang/activeadmin', branch: 'rails-5.2'`

**Comment by GregSilcox** [comment]
I am also having this issue. Rails 5.2 requires railties = 5.2, activeadmin requires < 5.2.

**Comment by jacob-hedengren** [comment]
Same issue here, but @pynixwang solution solved it for me at least!

**Comment by amatriain** [comment]
Rails 5.2 support has been merged into master (https://github.com/activeadmin/activeadmin/pull/5399). Can we expect a gem version with this merge to be released soon?

**Comment by ShamoX** [comment]
I'm also waiting for an updated gem.
In the mean time, I'm using master branch:

`gem 'activeadmin', github: 'activeadmin/activeadmin', branch: 'master'`

**Comment by pynixwang** [comment]
@ShamoX master branch is 2.0.0.pre, may has unstable features.

**Comment by zorab47** [comment]
Thanks to #5403 and the 1.3.0 release of ActiveAdmin we can close this issue. 🎉
