### ISSUE TITLE
Augmenting ActiveAdmin with a gem

### ISSUE THREAD

**Issue by yoelblum** [activeadmin/activeadmin#5397]
I have sort of a feature request: I want to augment activeadmin with a gem I want to create; what I want the gem to do is add a tab (to activeadmin) that has an sql editor of sorts (something similar to heroku snippets if you are familiar with that). Is that sort of augmentation from external gem possible with activeadmin? Sorry if this is not the right place to ask this.

**Comment by varyonic** [comment]
There are plenty of [extension gems on the wiki](https://github.com/activeadmin/activeadmin/wiki/Plugins) you can study for ideas. [StackOverflow](https://stackoverflow.com/tags/activeadmin) might be a better place to ask.
