### ISSUE TITLE
Multiple Namespace Issues

### ISSUE THREAD

**Issue by ryanhmaas** [activeadmin/activeadmin#5400]
Hi all,

I'm running into some issues with multiple namespaces and login routes. The end goal is to have scoped resources for an admin user and for a property manager (two different models) but first I need to get routing working.

My routes.rb file includes:

```
  devise_for :property_managers, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
```

My AA initializer looks something like:

```
ActiveAdmin.setup do |config|
  #config.default_namespace = :admin_dash (when commented out it doesn't generate any login routes other than /admin)
  config.comments = false

  #Administrative Namespace
  config.namespace :admin_dash do |admin_dashboard|
    admin_dashboard.site_title = "Title"
    admin_dashboard.site_title_image = "logo.png"
    admin_dashboard.authentication_method = :authenticate_admin_user!
    admin_dashboard.current_user_method = :current_admin_user
    admin_dashboard.logout_link_path = :destroy_admin_user_session_path
    admin_dashboard.logout_link_method = :delete
    admin_dashboard.batch_actions = true
  end

  #Property Manager Namespace
  config.namespace :property_management do |property_management_dash|
    property_management_dash.site_title = "Title"
    property_management_dash.site_title_image = "logo.png"
    property_management_dash.authentication_method = :authenticate_property_manager!
    property_management_dash.current_user_method = :current_property_manager
    property_management_dash.logout_link_path = :destroy_property_manager_session_path
    property_management_dash.logout_link_method = :delete
    property_management_dash.batch_actions = true
  end
end
```

What I would expect is generated login and logout routes for both `/admin_dash` and `/property_management` but that is not occurring. Any pointers? I've perused the issues docs and haven't found anything helpful yet. Is it even possible to have different auth methods for different namespaces?

Thanks,

Ryan

**Comment by joshmn** [comment]
What's `rake routes` returning?

**Comment by ryanhmaas** [comment]
@joshmn I'm attaching the important bit where it looks like they're using the same route
``` 
new_admin_user_session GET    /admin/login(.:format)

new_property_manager_session GET  /admin/login(.:format)

```

I am able to verify that the login only works for the latter

**Comment by ryanhmaas** [comment]
I'm actually going to close this out - I ended up using a combination of things (such as a subfolder for property_management and overriding the implementation of `after_sign_in_path_for`)
