### ISSUE TITLE
Feature Request: Allow Application-wide disabling of pagination total

### ISSUE THREAD

**Issue by knightstick** [activeadmin/activeadmin#5405]
We have ActiveAdmin running with a large database, where, many of the resources should have the `pagination_total: false`, otherwise our requests will time out.

It would be nice for us to set some application-wide config disallowing the pagination by default, and only allowing where specifically required.

I'm happy to take on this feature with a bit of guidance!

This appears to be the line in question:
https://github.com/activeadmin/activeadmin/blob/fdef5571fafb88465bc0f72c74179e4370477ffb/lib/active_admin/views/components/paginated_collection.rb#L45

It should be possible to check the config in the default block.

**Comment by giubueno** [comment]
Have you checked this PR? https://github.com/activeadmin/activeadmin/pull/5389
