### ISSUE TITLE
No version of ActiveAdmin is compatible with Rails 4.0 or 4.1?

### ISSUE THREAD

**Issue by jasoncrawford** [activeadmin/activeadmin#5406]
I'm trying to upgrade a Rails app from 3.2 to 4.0. (Eventually I will upgrade it to 4.2, but as per Rails's upgrade guidelines, I'm trying to do one patch level at a time and get everything working at each step.)

I cannot find any version of ActiveAdmin that is compatible with either 4.0 or 4.1. When I put `gem 'activeadmin', '~> 1.0.0'` in my Gemfile, I get this:

```
Bundler could not find compatible versions for gem "railties":
  In snapshot (Gemfile.lock):
    railties (= 4.0.13)

  In Gemfile:
    activeadmin (~> 1.0.0) was resolved to 1.0.0, which depends on
      railties (< 5.2, >= 4.2)

    rails (= 4.0.13) was resolved to 4.0.13, which depends on
      railties (= 4.0.13)
```

But when I change the ActiveAdmin version to 0.6.6, I get this:

```
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 4.0.13)

  In Gemfile:
    rails (= 4.0.13)

    activeadmin (~> 0.6.6) was resolved to 0.6.6, which depends on
      rails (< 4, >= 3.0.0)
```

So ActiveAdmin 0.6 requires rails 3.x, and 1.0 requires Rails 4.2 or later, and there's nothing in between as far as I can tell. So nothing at all supports Rails 4.0 or 4.1? That seems like a strange choice. I know Rails 4 is pretty old, and I would understand if it was only compatible with an old, unsupported version of ActiveAdmin, but it seems there is *no* version of ActiveAdmin, anywhere in the version history, that is compatible with Rails 4.0 or 4.1… like they were just skipped. Am I missing something?

Again, I am planning to get this app to Rails 4.2 (or maybe beyond), but I'm trying to be good and do it incrementally, and not having ActiveAdmin is breaking my tests. Thanks for any help!

**Comment by varyonic** [comment]
Congrats! There was a 'dry spell' with official gem releases so for 4.0 use the 1.0.0.pre releases.  More [upgrading details](https://github.com/activeadmin/activeadmin/wiki/Upgrading-ActiveAdmin) are on the wiki.

**Comment by jasoncrawford** [comment]
Got it, thanks! I managed to make it work by deactivating ActiveAdmin and commenting it out, then re-enabling… but maybe this will help someone else who has the issue in the future. It didn't occur to me to check the pre-releases.
