### ISSUE TITLE
inactive_message method not working for active admin

### ISSUE THREAD

**Issue by vishalTatvaSoft** [activeadmin/activeadmin#5407]
In my application , i need to give functionality of active account, AdminUser can't login until his account is activated. 
For implementing this feature i followed [this tutorial](https://github.com/plataformatec/devise/wiki/How-To:-Require-admin-to-activate-account-before-sign_in)

### Expected behavior

it should not allow admin user to login in to his account if its not activated and throw error. i added error 
`not_activated: 'Your account has not been activated by your administrator yet.'` in devise.en.yml .

### Actual behavior

`active_for_authentication?` and  `inactive_message`  methods are working fine. it isn't displaying the flash message that "Your account has not been activated by your administrator yet." 

All other error and notice flash messages working fine .
Is it bug, how to resolve this issue ?

**Comment by giubueno** [comment]
Could you create a small spec to reproduce the problem?

**Comment by vishalTatvaSoft** [comment]
I added this 2 methods in AdminUser model
```

def active_for_authentication?
    super && activated?
  end

  def inactive_message
    if !activated?
      :not_activated
    else
      super # Use whatever other message
    end
  end
```

if condition of inactive_message method is also executing, the problem is just flash error message.  I also tried to put static string and other error message like :invalid . but it seems flash message is not worked from that method

**Comment by vishalTatvaSoft** [comment]
@giubueno i override the layout `active_admin_logged_out.html.erb` and after inactive error occured `flash_messages` is blank

**Comment by varyonic** [comment]
@vishalTatvaSoft are you still having this issue?

**Comment by experimatt** [comment]
I'm having the same issue. I followed the instructions in Devise's docs to override `active_for_authentication?` and `inactive_message`, which works, but no flash message shows up in Active Admin when the inactive user tries to login.

https://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Authenticatable

**Comment by mateuszbialowas** [comment]
@experimatt Did you resolve that issue?
