### ISSUE TITLE
Extra params in the URL for any link.

### ISSUE THREAD

**Issue by alexventuraio** [activeadmin/activeadmin#5410]
After creating a resource like the following code I got wrong link params on the URL for any link in the resource views.

```ruby
ActiveAdmin.register Organization do
  menu parent: 'Users'
end

```
### Expected behavior

No extra URL params should be passed on every request from the view links like this:

```ruby
GET    /admin/organizations/3
POST   /admin/organizations/3/edit
DELETE /admin/organizations/3
```
### Actual behavior

Links show different attributes from the resource when hover on them and also when they are clicked the params are passed through the URL like this:

![screen shot 2018-05-11 at 20 24 21](https://user-images.githubusercontent.com/13169164/39952367-8445a434-555a-11e8-9e79-43f90544fc23.png)
![screen shot 2018-05-11 at 20 23 00](https://user-images.githubusercontent.com/13169164/39952368-846e5d70-555a-11e8-9f94-e046423aa190.png)
![screen shot 2018-05-11 at 20 22 20](https://user-images.githubusercontent.com/13169164/39952369-84a65f4a-555a-11e8-9626-40fe62dc58aa.png)
![screen shot 2018-05-11 at 20 24 25](https://user-images.githubusercontent.com/13169164/39952370-84d5a552-555a-11e8-8cf5-1b5546f84f2a.png)

```ruby
http://localhost:3000/admin/organizations/14?account_manager_id=1&allow_invited_patients_to_complete_profile=false&allow_overlapping_appointments=false&appointment_not_started_notifications_enabled=true&base_url=&bed_form_enabled=false&clarity_enabled=false&created_at=2018-05-08+08%3A11%3A00+-0400&d2c_mode=false&demo_account=false&display_insurance_fields=false&dynamics_url=&emr_integrated=false&emr_processor_type=Q&enable_patient_survey=false&enable_provider_survey=false&erx_enabled=false&genoa_site_id=&kind=care_provider&letterhead=&name=generic+organization&new_providers_can_manage_their_own_availability_by_default=false&office_address=&office_fax=&office_phone=&organization_type_id=1&patient_address_required=false&patient_credit_card_required=false&patient_email_required=false&patients_can_book_appointments=false&rcopia4_enabled=false&receive_from_emr=false&send_to_emr=false&share_notes_across_providers_enabled=false&site_id=5&sso_login_only=false&updated_at=2018-05-11+14%3A53%3A32+-0400&whitelist_enabled=false
```
### How to reproduce

Not sure if something is going wrong with the specific resource because any other resource behaves like that.

**Comment by AlexVentura** [comment]
Printing `edit_resource_path(resource)` show me this:
```bash
"/admin/organizations/14/edit.14?account_manager_id=1&allow_invited_patients_to_complete_profile=false&allow_overlapping_appointments=false&appointment_not_started_notifications_enabled=true&bed_form_enabled=false&clarity_enabled=false&created_at=2018-05-14+19%3A32%3A47+-0400&d2c_mode=false&demo_account=false&display_insurance_fields=false&emr_integrated=false&emr_processor_type=Q&enable_patient_survey=false&enable_provider_survey=false&erx_enabled=false&kind=care_provider&name=generic+organization&new_providers_can_manage_their_own_availability_by_default=false&organization_type_id=1&patient_address_required=false&patient_credit_card_required=false&patient_email_required=false&patients_can_book_appointments=false&rcopia4_enabled=false&receive_from_emr=false&send_to_emr=false&share_notes_across_providers_enabled=false&site_id=5&sso_login_only=false&updated_at=2018-05-14+19%3A32%3A47+-0400&whitelist_enabled=false"
```

**Comment by varyonic** [comment]
Cross posted from https://stackoverflow.com/questions/50302149/activeadmin-resource-extra-params-passed-in-the-url-for-any-link

**Comment by deivid-rodriguez** [comment]
@AlexVentura Could you share a public application that reproduces this issue?

**Comment by AlexVentura** [comment]
@deivid-rodriguez unfortunately I can share since it is a private project and I've tried to reproduce in another project but I haven't had any luck! :(

**Comment by deivid-rodriguez** [comment]
Same as you @AlexVentura. I got interested in this issue, because I run into this myself at some point, but I forgot to isolate a reproduction at the time and then I never saw it again... :/

**Comment by AlexVentura** [comment]
@deivid-rodriguez Yeah, that's so bad but I hope I can isolate it in the future because I still working with this gem. Thanks for your support!

**Comment by javierjulio** [comment]
If this can be reproduced, let us know and we'll reopen. Thank you.
