### ISSUE TITLE
Export data from Show page

### ISSUE THREAD

**Issue by joao-alberto** [activeadmin/activeadmin#5420]
I need to export as `csv` som content from a `Show Page`

I tried to do something similar to [Customizing Download Links](https://activeadmin.info/3-index-pages.html#customizing-download-links) but not work

``` ruby
ActiveAdmin.register Post do
  index download_links: [:csv] # Work for index page
  show download_links: [:csv] # Not work for show page
end
```

Is there a way to export data from the SHOW page?

**Comment by senid231** [comment]
Looks like `active_admin` doesn't have such feature as  downloading csv on show page
but you can do it yourself
```ruby
link_to 'Download CSV', admin_posts_path(q: {id_eq: resource.id}, format: :csv)
```
just put it somewhere on show page

**Comment by joao-alberto** [comment]
@senid231 I did what you suggested but not worked as expected.
Probably i will have to do it manually.

Thanks for your answer and attention ✌️

**Comment by senid231** [comment]
@joao-alberto what did you expect?)

**Comment by joao-alberto** [comment]
@senid231 The content of this page is the result of a poll with questions answered by users, something like:

| User       | Question           | Answer |
| -------- | -------------------- | -----|
| 1   | Question 1 desc | Value 1 |
| 1  | Question 2 desc  | Value 2 |
| 2   | Question 1 desc | Value 1 |
| 1  | Question 2 desc  | Value 1 |

but the exported value using `link_to 'Download CSV', admin_polls_path(q: {id_eq: resource.id}, format: :csv)` was this

![screen shot 2018-06-04 at 13 28 24](https://user-images.githubusercontent.com/10820159/40929474-356b02f6-67fb-11e8-8af0-aa45a05a73a9.png)

**Comment by senid231** [comment]
@joao-alberto so if you have custom show page you should provide custom csv for it
`active_admin` can't read your thoughts and predict youre desires :)
i think easiest way will be to do it through questions resource page
```ruby
ActiveAdmin.register Question do
  actions: index
  menu false

  filter :poll_id, filters: [:equals]

 # place below link to show page on poll resource
 # link_to 'Download CSV', admin_questions_path(q: {poll_id_equals: resource.id})
  csv do
    column(:user) { |r| r.user_id }
    column(:question) { |r| r.question }
    column(:answer) { |r| r.answer }
  end
end
```

or you can add `member_action` and build CSV by yourself

**Comment by senid231** [comment]
BTW it will be great if we can do something like
```ruby
ActiveAdmin.register Question do

  show do
    attributes_table
    text_node link_to('Download CSV', show_csv_admin_poll_path(resource.id))
  end

  member_action :show_csv do
    csv = CSVBuilder.build_from_collection(resource.questions) do
      column(:user) { |r| r.user_id }
      column(:question) { |r| r.question }
      column(:answer) { |r| r.answer }
    end
  end

end
```

but we can't because `CSVBuilder` strictly depends on controller

**Comment by joao-alberto** [comment]
@senid231 Thank you so much, I will implement your suggestion and give a feedback to show the result.
