### ISSUE TITLE
Cannot detect auto increment field existing table

### ISSUE THREAD

**Issue by setoelkahfi** [activeadmin/activeadmin#5421]
[SO thread](https://stackoverflow.com/q/50594710/1137814).

### Expected behavior

I can add new entries for my model even if there are already data in my table before integrating activeadmin.

### Actual behavior

I have to submit, in my case refresh the submitted form, until the generated auto increment id surpass the latest id in my table.

<img width="1440" alt="screen shot 2018-05-30 at 06 52 01" src="https://user-images.githubusercontent.com/1797197/40693822-b618c698-63e3-11e8-9c4a-28606fa6f8d1.png">

### How to reproduce

Install activeadmin on existing rails app with existing data. Try to add new entries for the model.

**Comment by senid231** [comment]
@setoelkahfi can you provide code of your form from active_admin DSL?
like 
```ruby
form do |f|
  # ...
  f.submit
end
```

**Comment by senid231** [comment]
it looks like this issue not connected with active_admin at all
I think you were inserting records provided ID in the past, but it's not a correct way to do it (unless you are know what you are doing and why you doing it).

if you need to provide id when creating a record just add
```ruby
f.input :id if f.object.new_record?
```
to your form DSL

but I think you need to just fix id sequence for this table with something like 
```sql
SELECT setval('song_artist_id_seq', (SELECT max(id) FROM song_artists));
```
like it was already answered in the StackOverflow thread that you create

**Comment by setoelkahfi** [comment]
I just put the permitted params in my code:
```
ActiveAdmin.register SongArtist do
# See permitted parameters documentation:
# https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#setting-up-strong-parameters
#
# permit_params :list, :of, :attributes, :on, :model
#
# or
#
# permit_params do
#   permitted = [:permitted, :attributes]
#   permitted << :other if params[:action] == 'create' && current_user.admin?
#   permitted
# end
  permit_params :album_id, :song_id, :artist_id, :primary
end
```

Anyway, I added the data from postgresql client, this [one](https://github.com/Paxa/postbird. ) Is that maybe the problem?

**Comment by senid231** [comment]
@setoelkahfi i think it may be the problem if you explicitly pass ID for some/all records in that table or maybe client do such strange thing for you

I'm using standard console client `psql` so I don't familiar with `postbird`
but I think you can look at last_value parameter of sequence that called `song_artist_id_seq` - it should equal to `SELECT COUNT(*) + 1 FROM song_artists;`
if it's not - your sequence is broken

**Comment by setoelkahfi** [comment]
It is likely because I input the auto increment field in postgresql client. I closed this issue.
