### ISSUE TITLE
ActiveAdmin breaks Rails UJS. Does not fire 'ajax:success' nor 'ajax:error'.

### ISSUE THREAD

**Issue by starrychloe** [activeadmin/activeadmin#5425]
https://stackoverflow.com/questions/50752746/rails-jquery-unobtrusive-javascript-ajaxsuccess-and-ajaxerror-are-not-firing-o

When you have ActiveAdmin, then it breaks the UJS events that are called when a form is submitted. `ajax:success` and `ajax:error` are not called. Renaming `active_admin.js.coffee` to `active_admin.js.coffee.xxx` fixes the UJS, but then breaks ActiveAdmin.

Rails 5.0.7

### Expected behavior

I expect ActiveAdmin to not interfere with any Rails functionality. It should be limited to /admin only. 

(Also ActiveAdmin styles interfere with Bootstrap styles too. `*= stub active_admin` in `application.css` fixes that.)

### Actual behavior

When you have a `remote: true` form, then after you submit the form, the callbacks `ajax:success` and `ajax:error` are not called.

### How to reproduce

Follow the Rails guide to create a remote form.
http://guides.rubyonrails.org/v5.0/working_with_javascript_in_rails.html#form-for
Add a callback and just try to log something to the console `console.log 'success/fail'`.

**Comment by varyonic** [comment]
You appear to have answered your own question on StackOverflow. ActiveAdmin is maintained and supported by volunteers. If you feel the documentation can be improved feel free to submit a PR. I recommend waiting for feedback on SO before opening GitHub issues.

**Comment by ngouy** [comment]
I still have the issue as of today, and the given solution doesn't works for me.

Unable to trigger `ajax:<whatever>` event on active admin forms/buttons/anything actually
