### ISSUE TITLE
Wrong display of user names in ActiveAdmin forms

### ISSUE THREAD

**Issue by JulienCorb** [activeadmin/activeadmin#5426]
I created a `FreeMeal` tab in my DB; this tab has a foreign key on the `User` tab. When I use the form in Active Admin to create a new entry of FreeMeal, I get a list of all my users for the user input; but users aren't displayed the right way, like so: 

[![FreeMeal form in ActiveAdmin][1]][1]

  [1]: https://i.stack.imgur.com/zIzv1.png

edit: the form is automatically populated as I have the foreign key on users. I simply have the following code for this form in `app/admin/free_meals.rb`:

    ActiveAdmin.register FreeMeal do
      form do |f|
        f.inputs "FreeMeal" do
          f.input :user
          f.input :reason
        end
        f.actions
      end
    end

I would like to have this list with my users' `id`, `first_name` and `last_name`.

How can I do that ?

**Comment by elcortez** [comment]
```
      f.input :user_id, as: :select, collection: User.inject({}) { |collection, user|
          collection[user.display_name] = user.id
          collection
        }, selected: select_field(f.object, params, 'user_id')
```

**Comment by JulienCorb** [comment]
thank you for your answer @elcortez ! 

However, I get `undefined method `inject' for #<Class:0x007ff3aa148020>`

**Comment by senid231** [comment]
just add method `display_name` to `User` class
something like
```ruby
def display_name
  [first_name, last_name].join(' ')
end
```

**Comment by elcortez** [comment]
Yep, sorry, I meant `User.all.inject`
If you run into the problem somewhere, I would recommend using a method in the model that you could call

`def self.get_for_select
    # return here the hash that you need to select objects...
 end`

**Comment by elcortez** [comment]
Also, consider a more optimized way to generate your array

`User.all.pluck(:first_name, :last_name, :id)`

**Comment by varyonic** [comment]
See also https://stackoverflow.com/questions/50812407/wrong-display-of-user-names-in-activeadmin-forms which received a useful answer also.  SO is the recommended first choice for support questions.
