### ISSUE TITLE
Dev logs full of assets requests 

### ISSUE THREAD

**Issue by louffoster** [activeadmin/activeadmin#5427]
My development.rb file contains:

```
config.assets.debug = true
config.assets.quiet = true
config.log_level = :debug
```

### Expected behavior

My logs should be free of asset request

### Actual behavior

They are not.  Example:
`::1 - - [14/Jun/2018:11:34:27 EDT] "GET /assets/jquery-ui/widgets/draggable.self-42c3eda0b49f105628cea7580fe38c7ed77467cee384bb2c4e095a2bd0a172e6.js?body=1 HTTP/1.1" 200 35473
http://localhost:3000/admin/sirsi_metadata?utf8=%E2%9C%93&q%5Buse_right_id_eq%5D=1&commit=Filter&order=id_desc -> /assets/jquery-ui/safe-blur.self-2cc24c46132d51c7724f6371154241b0a81c9bae5d5681d8f62b01ce46236726.js?body=1
http://localhost:3000/admin/sirsi_metadata?utf8=%E2%9C%93&q%5Buse_right_id_eq%5D=1&commit=Filter&order=id_desc -> /assets/jquery-ui/widgets/draggable.self-42c3eda0b49f105628cea7580fe38c7ed77467cee384bb2c4e095a2bd0a172e6.js?body=1
::1 - - [14/Jun/2018:11:34:27 EDT] "GET /assets/jquery-ui/focusable.self-426e99e67d1f1bd4cb444fd878ee63a6de1f5d1d61451e43022c86214b9eec64.js?body=1 HTTP/1.1" 200 2266
http://localhost:3000/admin/sirsi_metadata?utf8=%E2%9C%93&q%5Buse_right_id_eq%5D=1&commit=Filter&order=id_desc -> /assets/jquery-ui/focusable.self-426e99e67d1f1bd4cb444fd878ee63a6de1f5d1d61451e43022c86214b9eec64.js?body=1
::1 - - [14/Jun/2018:11:34:27 EDT] "GET /assets/jquery-ui/scroll-parent.self-38e26a71a450a29fb63425e8f589a7046862f927eb0a1dbf6a6c44da05196d2e.js?body=1 HTTP/1.1" 200 1253
http://localhost:3000/admin/sirsi_metadata?utf8=%E2%9C%93&q%5Buse_right_id_eq%5D=1&commit=Filter&order=id_desc -> /assets/jquery-ui/scroll-parent.self-38e26a71a450a29fb63425e8f589a7046862f927eb0a1dbf6a6c44da05196d2e.js?body=1
::1 - - [14/Jun/2018:11:34:27 EDT] "GET /assets/jquery-ui/widgets/resizable.self-1a46c2f5b876918e02bf979080e56f57846590cd880721bca5058e84f7f60bae.js?body=1 HTTP/1.1" 200 29993
http://localhost:3000/admin/sirsi_metadata?utf8=%E2%9C%93&q%5Buse_right_id_eq%5D=1&commit=Filter&order=id_desc -> /assets/jquery-ui/widgets/resizable.self-1a46c2f5b876918e02bf979080e56f57846590cd880721bca5058e84f7f60bae.js?body=1
::1 - - [14/Jun/2018:11:34:27 EDT] "GET /assets/jquery-ui/position.self-1b49c8c521e67a4a88bfdad6b4d944d33686d25009a0e40a1e170acdd7b6962a.js?body=1 HTTP/1.1" 200 14878
http://localhost:3000/admin/sirsi_metadata?utf8=%E2%9C%93&q%5Buse_right_id_eq%5D=1&commit=Filter&order=id_desc -> /assets/jquery-ui/position.self-1b49c8c521e67a4a88bfdad6b4d944d33686d25009a0e40a1e170acdd7b6962a.js?body=1
::1 - - [14/Jun/2018:11:34:27 EDT] "GET /assets/jquery-ui/tabbable.self-f3f62ceed772d3a325cebd6a03221f8a8cb02c6150f4feba738c6525a2953690.js?body=1 HTTP/1.1" 200 856
http://localhost:3000/admin/sirsi_metadata?utf8=%E2%9C%93&q%5Buse_right_id_eq%5D=1&commit=Filter&order=id_desc -> /assets/jquery-ui/tabbable.self-f3f62ceed772d3a325cebd6a03221f8a8cb02c6150f4feba738c6525a2953690.js?body=1
::1 - - [14/Jun/2018:11:34:27 EDT] "GET /assets/jquery-ui/widgets/dialog.self-2bd687f9580c0be4213c50b4bb1211c28ceedb045eba954e63d40bfbb4d1affd.js?body=1 HTTP/1.1" 200 23228
http://localhost:3000/admin/sirsi_metadata?utf8=%E2%9C%93&q%5Buse_right_id_eq%5D=1&commit=Filter&order=id_desc -> /assets/jquery-ui/widgets/dialog.self-2bd687f9580c0be4213c50b4bb1211c28ceedb045eba954e63d40bfbb4d1affd.js?body=1
::1 - - [14/Jun/2018:11:34:27 EDT] "GET /assets/jquery-ui/widgets/sortable.self-6e5e1f07a29b5a89ec1d359363d2800904e3ae548a38ab2f8eded36746d1adbe.js?body=1 HTTP/1.1" 200 46109`

on and on.

**Comment by h-haraguchi** [comment]
I feel like your log is apache log not rails log.

http://httpd.apache.org/docs/2.4/mod/mod_log_config.html#logformat
