### ISSUE TITLE
"Per page" selector change breaks filters with multiple values

### ISSUE THREAD

**Issue by francois-ferrandis** [activeadmin/activeadmin#5429]
### Expected behavior

On such an index view :

```ruby
filter :tags, multiple: true
config.per_page = [30, 200, 5000]
```

1. Select **multiple values** in the `:tags` filter and click "Filter" button
2. Change the `per_page` parameter at the bottom of the index table from 30 to 200
3. Selected values in filter should not change

### Actual behavior

3. Filter contains only one selected value

### More info

This is due to the way the `queryStringToParams` method is implemented : 
https://github.com/activeadmin/activeadmin/blob/f79e470a04d3ef25230803d83a6b1d26ad5c171a/app/assets/javascripts/active_admin/lib/active_admin.es6#L18

As you can see, this method **does not support querystrings containing arrays**.

The `toQueryString` method seems to exhibit the same flaws:
https://github.com/activeadmin/activeadmin/blob/f79e470a04d3ef25230803d83a6b1d26ad5c171a/app/assets/javascripts/active_admin/lib/active_admin.es6#L29

I am not aware of your policy on using JS libraries (I understand you want to keep it light), but this one seems quite appropriate for this job: https://github.com/ljharb/qs

I tried to look into the issue myself but did not find info on how JS libraries are packaged in this project. I would love some help on how to contribute using the `qs` library.

Thank you very much for your time!

**Comment by javierjulio** [comment]
This should now be using the [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) class in our JS. I would definitely accept a PR for updating that! Thank you.
