### ISSUE TITLE
Making Tableless FormObject work with ActiveAdmin to customise the saving of nested records.

### ISSUE THREAD

**Issue by alliesground** [activeadmin/activeadmin#5439]
Hi,

I was trying to use Form Object to handle form submission, so that I could do my own version of Nested model saving. 

I registered my Form Object which is a tableless model which includes ActiveModel::Model and extends ActiveModel::Naming modules. But I'm getting errors like

> NoMethodError in Admin::CourseRegistrationFormsController#index

> undefined method `column_names' for CourseRegistrationForm:Class

>     
       def resource_column_names
         resource_class.column_names
       end
       def resource_quoted_column_name(column)

> activeadmin (1.3.0) lib/active_admin/resource.rb:111:in `resource_column_names'
activeadmin (1.3.0) lib/active_admin/order_clause.rb:27:in `table'
activeadmin (1.3.0) lib/active_admin/order_clause.rb:32:in `table_column'
activeadmin (1.3.0) lib/active_admin/order_clause.rb:23:in `to_sql'
activeadmin (1.3.0) lib/active_admin/order_clause.rb:36:in `sql'
activeadmin (1.3.0) lib/active_admin/order_clause.rb:19:in `apply'
activeadmin (1.3.0) lib/active_admin/resource_controller/data_access.rb:208:in `apply_sorting'
activeadmin (1.3.0) lib/active_admin/resource_controller/data_access.rb:59:in `block in find_collection'
activeadmin (1.3.0) lib/active_admin/resource_controller/data_access.rb:58:in `each'
activeadmin (1.3.0) lib/active_admin/resource_controller/data_access.rb:58:in `find_collection'
activeadmin (1.3.0) lib/active_admin/resource_controller/data_access.rb:44:in `collection'
inherited_resources (1.8.0) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (1.3.0) lib/active_admin/resource_controller/streaming.rb:12:in `index'
actionpack (5.1.6) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.6) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.6) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.6) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.6) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
webpacker (3.5.5) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
rack-proxy (0.6.4) lib/rack/proxy.rb:57:in `call'
railties (5.1.6) lib/rails/engine.rb:522:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'

wasn't sure if it was possible to make Form Objects work with Active Admin.

****My** Files:**

'app/models/course_registration_form.rb'
```
require 'Tableless'
class CourseRegistrationForm
  include ActiveModel::Model
  include Tableless

  attr_accessor :name

  validates :name, presence: true

  def save
    if valid?
      puts 'persited!'
      true
    else
      false
    end
  end
end

```

lib/tableless.rb
```
module Tableless
  extend ActiveModel::Naming

  def self.columns
    @columns ||= []
  end

  def self.column_names
    @column_names
  end

  def initialize(params)
  end

  def self.find(param)
    true
  end

  def to_model
  end

  def persisted?
    false
  end
end

```

app/admin/course_registration_form.rb
```

ActiveAdmin.register CourseRegistrationForm do
  permit_params :name

  form do |f|
    f.input :name
  end
end

```

**Comment by varyonic** [comment]
Maybe [FormtasticFauxModel](http://dondoh-blog.tumblr.com/post/4142258573/formtastic-without-activerecord) might help.
