### ISSUE TITLE
XML serialization broken in Rails 5.2 if activemodel-serializers-xml not present

### ISSUE THREAD

**Issue by tf** [activeadmin/activeadmin#5440]
### Expected behavior

Clicking the XML-Link below a table should result in a XML serialization of the table including the model attributes.

### Actual behavior

Instead, the output looks like this:

```
<orders type="array">
  <order type="Order">#<Order:0x0055acb3e56388></order>
</orders>
```

### How to reproduce

http://demo.activeadmin.info/admin/orders.xml 

### Solution/Workaround

Adding `activemodel-serializers-xml` to the applications `Gemfile` fixes the issue. Maybe this should be a dependency or added by the install generator by default?

**Comment by varyonic** [comment]
`active-model-serializers` was extracted in Rails 5. It was subsequently added to Draper v3 which is often used with, but not required by ActiveAdmin. Perhaps adding it as a direct dependency would be the simplest fix.
