### ISSUE TITLE
undefined method `[]' for "image":Sass::Script::Value::String

### ISSUE THREAD

**Issue by piyush8** [activeadmin/activeadmin#5442]
Rails version 4.0
Ruby version 2.5.1
While upgrading from rails 3.2 to rails 4.0 facing issue. 

Replace asset-url with two arguments with image-url('logo.png').
For example,

asset-url(‘profile.png’, image)
Changed to
asset-url(‘profile.png’)

Even getting the same error any help will be appreciated. 
![Uploading sass_error.png…]()

**Comment by varyonic** [comment]
Which version of ActiveAdmin are you using? Have you read the [upgrading notes on the wiki](https://github.com/activeadmin/activeadmin/wiki/Upgrading-ActiveAdmin)?

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
