### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by hanishjadala** [activeadmin/activeadmin#5455]
nd_book.rb
```ruby
ActiveAdmin.register ND::Book do
  actions :all, except: [:destroy]

  filter :client_email

  index(:paginate => true) do
    column :client_email
    column :name 
    actions
  end
end

module ND
  class Book < Base
    self.table_name  = 'country_book__c'
  end
end
```
while showing index data is reading from ND::Book but filter is not working. Giving below error
No table named country_book__c exists.

I have multiple db in my project and above table from other db.
While reading it is displaying data from it but not the filter part.

EDIT: code formatting updated

**Comment by varyonic** [comment]
Maybe `establish_connection` will work, see https://stackoverflow.com/questions/30100072/move-activeadmin-queries-to-different-database and maybe follow up there.
