### ISSUE TITLE
custom sorting not working

### ISSUE THREAD

**Issue by newton10471** [activeadmin/activeadmin#5456]
### Expected behavior

I'm trying to use the Custom Sorting feature described in https://github.com/activeadmin/activeadmin/blob/master/docs/3-index-pages/index-as-table.md#custom-sorting, but can't seem to get it to work with a very simple case. The repo for my code is here: https://github.com/newton10471/active_admin_custom_sorting. For what it's worth, I'm using older versions of Rails (4.2.5), and Active Admin (1.1.0).

### Actual behavior

In my repo mentioned above, my AdminUser model looks like this:

```ruby
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  has_many :gold_stars
end
```

and my GoldStar model looks like this:

```ruby
class GoldStar < ActiveRecord::Base
  validates :admin_user_id, presence: true
  belongs_to :admin_user
end
```

I want to be able to sort on the 'Gold Stars' column, which is a count of the number of Gold Stars each AdminUser has earned.

My attempt to use custom sorting looks like this, in app/admin/admin_user.rb:

```ruby
  order_by(:gold_stars) do |order_clause|
    ['COUNT(gold_stars.id)', order_clause.to_sql].join(' ')
  end

  index do
    column :gold_stars, sortable: true do |admin_user|
      admin_user.gold_stars.count
    end
  end
```

But the column isn't enabled as sortable unless I include sortable: true, which makes me think that either I'm doing something wrong or something is not working properly. The setup above doesn't seem to make it sort things any differently than the default case. Looking at the Rails log, it doesn't look like the SQL query is modified, although params[:order] gets populated with what looks like a Proc, along the lines of "<Proc:0x00007fb3c40c8080@/Users/user/active_admin_custom_sorting/app/admin/admin_user.rb:12>_desc"

### How to reproduce

Clone the repo at https://github.com/newton10471/active_admin_custom_sorting, then run these commands:

```ruby
rake db:migrate
rake db:seed
rails s
```

log in as admin@example.com, password 'password' and go to the Admin User tab, and try sorting on 'Gold Stars'

**Comment by chumakoff** [comment]
First of all, it has to be:

```
order_by(:gold_stars) do |order_clause|
  # order_clause.order, not order_clause.to_sql
  ['COUNT(gold_stars.id)', order_clause.order].join(' ')
end

# pass :gold_stars as the :sortable option, not 'true'
column(:gold_stars, sortable: :gold_stars) do |admin_user|
  admin_user.gold_stars.count
end
```

The second problem is that if you want to sort by `COUNT(gold_stars.id)` then the SQL query has to include JOIN with `gold_stars` table and a GROUP BY clause so you can use an aggregate function in the ORDER clause. I am not sure it will work, might depend on DBMS.

So you should somehow modify the base scope to make it work with your new sorting conditions:

```
  controller do
    private

    def scoped_collection
      super.joins(:gold_stars).group("admin_users.id").select("???")
    end
  end
```

There will be another ton of problems ...


**Just add a counter cache column to the `admin_users` table and all your problems will be solved!**

```
# models/admin_user.rb

class AdminUser < ActiveRecord::Base
  has_many :gold_stars, counter_cache: true
end
```

```
# admin/admin_users.rb

  index do
    column :gold_stars_count
  end
```

**Comment by timirwin** [comment]
I think this can be closed. We're using ActiveAdmin 2.9.0 and sorting/pagination both work for us on aggregate functions. Your select will need to include the columns you need, including the aggregate function ones treated as virtual columns in your model. That allowed us to skip the custom `order_by` and even the column block to get the display value.
