### ISSUE TITLE
Are Ransack's features like `*_cont_all` or `*_cont_any` supported?

### ISSUE THREAD

**Issue by kewubenduben** [activeadmin/activeadmin#5457]
Are Ransack's features like `*_cont_all` or `*_cont_any` supported?

I'm trying to look for a filter that uses `contains all` for multiple keyword.

If this is possible in any way, can someone point out on how to do this?

Thanks

**Comment by jzisser9** [comment]
I was just looking for support for `i_cont` as well. AA doesn't seem to support it yet. I might take a crack at adding support for it.

**Comment by kewubenduben** [comment]
> I was just looking for support for `i_cont` as well. AA doesn't seem to support it yet. I might take a crack at adding support for it.

Check out my PR#5465

It wasn't merge though due to not having a spec.

I'm currently using it at the moment
