### ISSUE TITLE
set default_per_page=[10,30,50], NoMethodError in Admin::Model#index per_page.to_i

### ISSUE THREAD

**Issue by LuckyScott** [activeadmin/activeadmin#5463]
**ActiveAdmin Version:  ~> 1.0**

I set default_per_page like this:
```ruby
ActiveAdmin.setup do |config|  
    config.default_per_page = [10, 30, 50]
```
and disabled pagination
```ruby
ActiveAdmin.register StockDayBar do
  index pagination_total: false do
    selectable_column
    id_column
    stock_code
    stock_name
    actions
  end
end
```

**But Got an Error:**
NoMethodError in Admin::StockDayBars#index
undefined method `to_i' for [10, 30, 50, 100]:Array
Did you mean?  to_s
               to_a
               to_h
```ruby
Extracted source (around line #105):
  103 |   # query fast.
  104 |   # if there is another page or not, but the limit/offset make this
=>105 |   offset = collection.offset(collection.current_page * @per_page.to_i).limit(1).count
  106 |   options[:total_pages] = collection.current_page + offset
  107 |   options[:right] = 0
  108 | end
```

**Ccallstack trace:**
activeadmin (1.3.0) lib/active_admin/views/components/paginated_collection.rb:105:in `build_pagination'
activeadmin (1.3.0) lib/active_admin/views/components/paginated_collection.rb:71:in `block in build_pagination_with_formats'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (1.3.0) lib/active_admin/views/components/paginated_collection.rb:69:in `build_pagination_with_formats'
activeadmin (1.3.0) lib/active_admin/views/components/paginated_collection.rb:53:in `build'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `paginated_collection'
activeadmin (1.3.0) lib/active_admin/views/pages/index.rb:132:in `render_index'
activeadmin (1.3.0) lib/active_admin/views/pages/index.rb:50:in `build_collection'
activeadmin (1.3.0) lib/active_admin/views/pages/index.rb:28:in `block in main_content'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `batch_action_form'
activeadmin (1.3.0) lib/active_admin/views/pages/index.rb:36:in `wrap_with_batch_action_form'
activeadmin (1.3.0) lib/active_admin/views/pages/index.rb:26:in `main_content'
activeadmin (1.3.0) lib/active_admin/views/pages/base.rb:93:in `block (2 levels) in build_main_content_wrapper'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (1.3.0) lib/active_admin/views/pages/base.rb:92:in `block in build_main_content_wrapper'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (1.3.0) lib/active_admin/views/pages/base.rb:91:in `build_main_content_wrapper'
activeadmin (1.3.0) lib/active_admin/views/pages/base.rb:77:in `block in build_page_content'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (1.3.0) lib/active_admin/views/pages/base.rb:76:in `build_page_content'
activeadmin (1.3.0) lib/active_admin/views/pages/base.rb:54:in `block (2 levels) in build_page'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (1.3.0) lib/active_admin/views/pages/base.rb:50:in `block in build_page'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
activeadmin (1.3.0) lib/active_admin/views/pages/base.rb:49:in `build_page'
activeadmin (1.3.0) lib/active_admin/views/pages/base.rb:10:in `build'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.1.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.1.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (1.3.0) app/views/active_admin/resource/index.html.arb:2:in `block in __home_zyq__rvm_gems_ruby_______gubang_webapi_gems_activeadmin_______app_views_active_admin_resource_index_html_arb__4468238466627190569_69954453663460'
arbre (1.1.1) lib/arbre/context.rb:45:in `instance_eval'
arbre (1.1.1) lib/arbre/context.rb:45:in `initialize'

**Comment by varyonic** [comment]
Related? #5429
