### ISSUE TITLE
how to specify Module::Class name for upgraded (1.1.0) ActiveAdmin association filters?

### ISSUE THREAD

**Issue by newton10471** [activeadmin/activeadmin#5480]
I recently upgraded from ActiveAdmin 1.0.0.pre1 to 1.1.0. I notice now that filters using this format:

`filter :entity, as: :select, collection: V2::Entity.order(:name).pluck(:name, :id)`

No longer work, and fail with the error ‘uninitialized constant Entity’.

I think the reason for this is that (for legacy reasons) all of my models are in the ‘V2’ module, so it’s correct that Entity doesn’t exist, since it’s actually V2::Entity. 1.0.0.pre1 used to not care about that and was just going on the association name (which is entity), whereas 1.1.0 is doing something else to either verify that :entity points to an ‘Entity’ model or makes a similar assumption.

Is there some way I can tell ActiveAdmin (or, I guess, ransack, since I believe the ransack gem handles the filtering) what the actual model name is for an association?

**Comment by javierjulio** [comment]
@newton10471 in [the docs it states to have the collection provided with a proc](https://github.com/activeadmin/activeadmin/blob/master/docs/3-index-pages.md#index-filters) for a filter. I'm not sure if the change was made to address something like this but its worth a try.
