### ISSUE TITLE
Default Value for Boolean on Filter Not Working

### ISSUE THREAD

**Issue by swedishpotato** [activeadmin/activeadmin#5481]
Hi,

If you have a Boolean field in your model, and try to set a default value for this in the filter, it doesn't work, i.e. 

filter :my_boolean_field, input_html: {value: false }

Does not set the default value to false, as expected. Setting the default value on other types of field works as expected, but not Boolean.

I have a **very ugly** fix at the moment which looks like this:

filter :my_boolean_field_eq, :as => :string, :input_html => { :value => 'false'}

Any help appreciated. I have tried everything, setting the params on a before action in the controller, using select, etc, all to no avail. Any guidance appreciated! Looking on SO I don't seem to be alone in this problem. Formtastic certainly allows default values to be used.

**Comment by varyonic** [comment]
Did you see #5318?

**Comment by swedishpotato** [comment]
Yes indeed. I have the same problem as the other author. It is extremely easy to replicate this problem. Any Boolean value in a table will do. I have the latest version of AA from github. Boolean is the only filter value that doesn’t seem to work as expected.
