### ISSUE TITLE
Tabs are not correctly created when using non-latin characters as title

### ISSUE THREAD

**Issue by omitter** [activeadmin/activeadmin#5484]
This is probably a low priority bug, but it kept me debugging for hours.

Using this code, tab links are not created correctly:
```ruby
tabs do
  tab "テスト" do
    raw "Whatever"
  end
end
```

The id generated for the tab link is blank. This caused my app to reload itself continuously. Afaik jquery-ui interpreted it as link that should get loaded via ajax.

I think the problem is that `title.parameterize` returns `""` for non latin text [here](https://github.com/activeadmin/activeadmin/blob/4b862ed13f9f2a60d4fad48ffe2629e594dadde4/lib/active_admin/views/components/tabs.rb#L18).

As the source shows this can easily be circumvented by passing an `id` value to the method, but I would appreciate it when a clear error is raised (`raise "…" if fragment.blank?`) or if valid ids were generated (i.e. `title.parameterize.presence ||"id_"+SecureRandom.alphanumeric`). Thanks for considering.

**Comment by deivid-rodriguez** [comment]
Hi @omitter! Thanks for the report. I added this spec locally but it passes for me. Can you help me reproducing this with a spec?

```diff
diff --git a/spec/unit/views/components/tabs_spec.rb b/spec/unit/views/components/tabs_spec.rb
index 8d6b9ef2..3ffc027b 100644
--- a/spec/unit/views/components/tabs_spec.rb
+++ b/spec/unit/views/components/tabs_spec.rb
@@ -67,5 +67,21 @@ RSpec.describe ActiveAdmin::Views::Tabs do
         expect(tabs.find_by_tag('span').first.content).to eq('tab 1')
       end
     end
+
+    context "when tab has non-latin characters" do
+      let(:tabs) do
+        render_arbre_component do
+          tabs do
+            tab "テスト" do
+              raw "whatever"
+            end
+          end
+        end
+      end
+
+      it "should create a tab navigation bar based on the symbol" do
+        expect(tabs.find_by_tag('li').first.content).to include("テスト")
+      end
+    end
   end
 end
```

**Comment by omitter** [comment]
@deivid-rodriguez Thanks for looking into this. If I understand the spec correctly, you're looking for the wrong thing. The `content` is fine, it's the `id` that gets set to `id="#"` (for any tag without latin letters). Sorry, I can't check it further before next week.

**Comment by deivid-rodriguez** [comment]
You're absolutely right, what was I thinking? :flushed: I'll have another look!

**Comment by deivid-rodriguez** [comment]
I see the problem now, the report is great, it's just my diagonal reading that made me misunderstand... :rofl:.

As per how to fix it, I don't have a strong opinion, but I have a slight preference for raising. Any other opinions?

**Comment by deivid-rodriguez** [comment]
Something like

>tab title is not transliterable into an ascii only id that can be used as a url fragment for this tab. Either manually specify a tab id, or add the proper [transliteration](https://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-transliterate) rules to your application.

**Comment by javierjulio** [comment]
If it’s unexpected I think raising an error would be best? You could do it as a warning but I feel like that could be easily missed. The message is great to start with. 👍🏻

**Comment by omitter** [comment]
I just found out that there's actually no need for advanced transliteration, [only spaces need to be eliminated to be valid HTML5](https://mathiasbynens.be/notes/html5-id-class). So `.gsub(/[[:space:]]/, '')` should work too.

**Comment by deivid-rodriguez** [comment]
That's pretty cool! I guess we could then entirely drop the `parameterize` call, but I think it's better to conservatively introduce this only as a fallback for the problematic cases. What do you think?

**Comment by omitter** [comment]
You mean something like: `fragment = options.fetch(:id, title.parameterize); fragment = title.gsub(/[[:space:]]/, '') if fragment.blank?; raise "…" if fragment.blank?`. That sounds good to me. We should definitely not change the default `parameterize` call, people might be using custom JS that looks for the ids. Might keep it in mind for a new major version though. It would fix strange behaviour when using mixed text like `idア`, `idイ` all becoming `id`.

Btw, maybe we should add this too, in case a passed in id contains spaces: `fragment = options.fetch(:id, title.parameterize).gsub(/[[:space:]]/, '')`. But we could also keep it in the responsibility of the user to generate valid HTML ids.

Yet another idea, use parameterize for ascii-only strings and the space elimination for the rest.
```ruby
fragment =
if options.key?(:id)
  options[:id]
elsif title =~ /\A[[:ascii:]]+\z/
  title.parameterize
else
  title.gsub(/[[:space:]]/, '')
end
raise "…" if fragment.blank?
```

**Comment by deivid-rodriguez** [comment]
> You mean something like: fragment = options.fetch(:id, title.parameterize); fragment = title.gsub(/[[:space:]]/, '') if fragment.blank?; raise "…" if fragment.blank?. That sounds good to me. We should definitely not change the default parameterize call, people might be using custom JS that looks for the ids.

Yes, this is exactly what I meant, and I want to keep it the same for the reason you indicated :+1:

I like the last idea you mentioned, would you like to work on a PR?

**Comment by omitter** [comment]
I can have a try. Do you think this would be compatible enough, as the behaviour for non-ascii titles will change?

**Comment by deivid-rodriguez** [comment]
You're right, I was thinking that non-ascii titles were already broken so we could change the behavior, but I guess they're working in some cases and people is realying on it.

Let's go with

> fragment = options.fetch(:id, title.parameterize)
> fragment = title.gsub(/[[:space:]]/, "") if fragment.blank?
> raise "…" if fragment.blank?

then!

**Comment by deivid-rodriguez** [comment]
@omitter ping!

**Comment by omitter** [comment]
Ah, sorry, I was not sure you needed a pull request by me.

**Comment by omitter** [comment]
Created it here: #5508

**Comment by panasyuk** [comment]
Working on specs for the PR i did small investigation and found that no one could use non-ascii symbols in tab IDs because jQuery UI Tabs simply would not work correctly with the IDs causing incorrect tab appearance and throwing errors. I've tried all jQuery and jQuery UI versions and none of them showed correct behavior.
Here's the experiment:
https://jsfiddle.net/panasyuk/jtL6rhcy/21/

This means that space elimination would not solve the problem. And i want to propose different approach. Let's use title string hash if the title is not parameterizable.

```ruby
def build_menu_item(title, options, &block)
    fragment = options.fetch(:id, title.parameterize)
    fragment = title.hash.to_s if fragment.blank? && title.present?
    raise 'The tab title is not transliterable into an ascii only id that can be used as a url fragment for this tab. Either manually specify a tab id, or add the proper transliteration rules to your application.' if fragment.blank?
    html_options = options.fetch(:html_options, {})
    li html_options do
      link_to title, "##{fragment}"
    end
end
```

**Comment by panasyuk** [comment]
@deivid-rodriguez @omitter what do you think?

**Comment by omitter** [comment]
I can't check it right now, but this seems to be a good solution. My main concern was getting no error message and looking for hours, that is properly addressed now. Using the hash is convenient if we don't care to specify an id as it hopefully *just works*.

**Comment by deivid-rodriguez** [comment]
@panasyuk Yeah, it looks like a good idea to me too. Ideally the test we add should catch that the previous alternative didn't work.

Thanks for researching and finding about this!

**Comment by panasyuk** [comment]
Added another PR that addresses the issue.
https://github.com/activeadmin/activeadmin/pull/5650
