### ISSUE TITLE
Documentation does not match released features

### ISSUE THREAD

**Issue by deivid-rodriguez** [activeadmin/activeadmin#5499]
### Expected behavior

If I go to the documentation site, and I see a feature documented, I should be able to use it or at least be informed about the series it was (or will be released).

### Actual behavior

Features are documented in the website as soon as the land into master, but the release cycle is much slower.

### How to reproduce

See #5497 for an example.

**Comment by deivid-rodriguez** [comment]
Possible solutions:

* Different sections/tabs in the website for each release series.
* Move the GH-pages build to the latest stable (there still would be a gap between docs and code releases, but much slower).
* Push to GH-pages only upon release.
* Document the release date (past or expected) with each feature.

I think maybe the easiest are the second or third options? In the third option, docs would have the same cycle as releases, making them have changelog entries and all that. The bad thing would be that doc fixes (fixes to get docs match _released_ code) would not get continuously deployed, and that's a good thing about the current system... Maybe we could deploy those manually (or auto-deploy them based on a "documentation" label or something like that?).

Not sure... thoughts?

**Comment by varyonic** [comment]
My preference is the second. We can always back-port significant fixes.

**Comment by deivid-rodriguez** [comment]
I just checked the repo settings and https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/, and I don't think there's a built-in way to do it? :thinking:

**Comment by varyonic** [comment]
I prefer maintaining a `gh-pages` branch as we had before, but it's not a big concern to me.

**Comment by deivid-rodriguez** [comment]
So, I guess we could go back to the old setup and trigger a push to the `gh-pages` branch everytime we merge to the latest stable?
