### ISSUE TITLE
Ruby Sass ("sass" gem) will be end-of-life March 26th 2019 - Consider switching to "sassc-rails" or  "sassc"

### ISSUE THREAD

**Issue by DeeDeeG** [activeadmin/activeadmin#5502]
See this blog post: http://sass.logdown.com/posts/7081811

And this issue over at sass-rails: https://github.com/rails/sass-rails/issues/420

The ruby implementation of sass is already designated as "deprecated", so it's *already* in maintenance mode. They will be archiving the repo and not accepting issues or pull requests after March 29 2019. So it is going to eventually get stale.

I would like to suggest this gem switch to [`sassc-rails`](https://github.com/sass/sassc-rails) or [`sassc`](https://github.com/sass/sassc-ruby), which uses the new C implementation of Sass.

**Comment by Calamari** [comment]
Hey guys. 

Just wanted to ask what the status of this issue is. Is there a plan to switch to `sassc` or something? Would be nice to get rid of the warning and an unmaintained dependency.
