### ISSUE TITLE
Search produces in materialized view raise RuntimeError No table named ... exists

### ISSUE THREAD

**Issue by Barlog951** [activeadmin/activeadmin#5513]
Hi,

I follow [this](https://www.sitepoint.com/speed-up-with-materialized-views-on-postgresql-and-rails/) tutorial for creating materialized view in DB (PostgreSQL)

This is my model 
```
class MeteredPeriodReports < ActiveRecord::Base
    self.table_name = 'metered_period_reports'
    default_scope { order(id: :desc) }

    def readonly?
      true
    end

    def self.refresh_view
      connection = ActiveRecord::Base.connection
      connection.execute('REFRESH MATERIALIZED VIEW metered_period_reports')
    end
end
```

This is my ActiveAdmin controller
```
ActiveAdmin.register MeteredPeriodReports, as: 'Metered Periods Reports' do

  filter :id
  .
  .
  .
```

`#index` works fine, everything shows up, sortable columns works as well, 
but when I try filter I got `RuntimeError - No table named metered_period_reports exists.:`
This happens in default filters as well

**Comment by joshmn** [comment]
Can you create an example application?
