### ISSUE TITLE
Slightly confused on versioning

### ISSUE THREAD

**Issue by seanfcarroll** [activeadmin/activeadmin#5539]
Hi, thank you @varyonic, @javierjulio and all the other contributors for a great gem and massive amounts of hard work. 

I'm slightly confused on the versions and changelog.

- Currently, I am running ActiveAdmin **1.3.0**.
- [Rubygems](https://rubygems.org/gems/activeadmin/versions/0.6.6) says the latest version is **1.3.1**
- The [version file](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/version.rb) says **2.0.0.alpha**, but this commit is from Aug 11, 2017
- The [changelog](https://github.com/activeadmin/activeadmin/blob/master/CHANGELOG.md) has **1.3.0** as the last release, and **master** as unreleased.

There is also [this issue](https://github.com/activeadmin/activeadmin/issues/4677) talking about the road to 2.0, but the last post is from Jun 29, 2017.

So, would be possible to clear up what is the current official version, and is there an active road to 2.0?

Thanks in advance,
Sean

**Comment by deivid-rodriguez** [comment]
Hi @seanfcarroll, all of your bullet points are correct. The only thing wrong is that we need to merge the changelog bits from 1.3.1 back to master. Is there anything else that's confusing you other than that?

For now the focus is to release in 1.4.0 with a few improvements. Then we'll get back to working on 2.0.0.

**Comment by deivid-rodriguez** [comment]
We have been struggling to decide how to proceed with the CSS overhaul, so my idea is to ship a much lighter 2.0 release just dropping support for old Rails and rubies and a few other minor breaking changes.
