### ISSUE TITLE
Is there a way to avoid activeadmin startup when spinning the server up?

### ISSUE THREAD

**Issue by Chucheen** [activeadmin/activeadmin#5547]
I have several admin files that, in order to build scopes, do queries to other tables. The thing is that my rails server, rails console, rake task, etc, is taking too long to start. Plus, as active_admin depends on certain data from the database, and my server configuration (using Chef) hasn't created it, it raises an error. I don't understand why it loads all the files from the very beginning if they are reloaded when entering to the section (locahost:3000/admin/employees)

### Expected behavior

I think ActiveAdmin shouldn't be loading all the files from the very beginning?

### Actual behavior

It does load all the admin files from the very beginning

**Comment by MikeRogers0** [comment]
You could load ActiveAdmin when an `ENV` is present, a bit like:

```ruby  
constraints subdomain: 'admin' do
  devise_for :admin_users, ActiveAdmin::Devise.config.merge(path: '')
  ActiveAdmin.routes(self)
 end if ENV['ENABLE_ACTIVE_ADMIN'].present?
```

I'm not 100% if this will stop ActiveAdmin from loading the files, but it might reduce the routes building time.
