### ISSUE TITLE
Displaying wrong entries count inside table

### ISSUE THREAD

**Issue by krthi** [activeadmin/activeadmin#5549]
I am trying to add pagination inside table, I added initializer as suggested in this issue as I am using will_paginate gem(https://github.com/activeadmin/activeadmin/issues/1833)

Here is the code for adding the pagination for the table,

```
paginated_collection(histories.page(params[:page]).per(5), download_links: false) do
      table_for collection do
           column ('Status') { |bh| bh.status.humanize }
           column ('Reason') { |bh| bh.reason }
           column ('Date') { |bh| bh.created_at }
      end
 end

```
It renders the records as the 'per' count in the pagination, But the links it displays wrong count as below,

![screen shot 2018-11-04 at 2 29 39 pm](https://user-images.githubusercontent.com/37453468/47962263-3403e780-e040-11e8-8c03-c280ccc3140a.png)

![screen shot 2018-11-04 at 2 31 39 pm](https://user-images.githubusercontent.com/37453468/47962262-323a2400-e040-11e8-8f75-8428d405f6d4.png)

**Comment by tylerlu94** [comment]
Running into this too

**Comment by jdugarte** [comment]
@tylerlu94 This is what I did in my app to solve the issue:

```
# config/initializers/kaminari.rb
Kaminari.configure do |config|
  config.page_method_name = :per_page_kaminari
end
```

according to the documentation [here](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md#will_paginate).

**Comment by erotenberg1** [comment]
solution of @jdugarte is not working for me, I still get the page numbering errors similar to the original post.

I'm initializing with: 
```
Kaminari.configure do |config|
  config.page_method_name = :per_page_kaminari
end
```
and, according to [this link](https://github.com/activeadmin/activeadmin/issues/1833), 
```
 if defined?(WillPaginate)
  module WillPaginate
    module ActiveRecord
      module RelationMethods
        def per(value = nil) per_page(value) end
        def total_count() count end
      end
    end
    module CollectionMethods
      alias_method :num_pages, :total_pages
    end
  end
end
```
I am sure both methods are happening during initialization, but I still get the page number errors similar to the original post.
