### ISSUE TITLE
Rails 5.2 usage with webpack, without sprockets or coffeescript

### ISSUE THREAD

**Issue by chriso0710** [activeadmin/activeadmin#5551]
Hi all,

for a new project I am thinking about using Rails 5.2 with webpack and ES6 only. This would mean no standard rails asset pipeline, no sprockets and no coffeescript.

I was wondering, if this setup would be possible and compatible with AA? Can AA use webpack for assets? I would appreciate any tips, thanks.

Christian

**Comment by varyonic** [comment]
You can use webpack for your non-ActiveAdmin code and leave the asset pipeline for ActiveAdmin. If you search the issues and PRs, both open and closed for this project (sprockets, webpack, ES6, coffeescript, etc) you will find more background, eg. #5168, #4779.

**Comment by chriso0710** [comment]
Thanks @varyonic, I read that and already suspected that running both technologies in parallel seems to be the only way ATM. It's a pity, that there is no cleaner approach. I would love to throw out sprockets and coffeescript for new projects. 

IMHO it would be fantastic to have AA only use ES6 and webpack. Would you consider this important? Are there any plans or efforts going on?

**Comment by javierjulio** [comment]
@chriso0710 there are no plans that I know of but yes we would definitely consider something. I'd love to know more about what it would take and whether it is possible to make the sprockets optional for AA users. I think it will still remain the default though. From what I've seen on Rails, the asset pipeline is here to stay but I do know that several developers have gone all in with webpacker and even removed asset pipeline support. I just don't know what it would take and how it would work within AA. We'd appreciate any research and info you or others could share.

**Comment by chriso0710** [comment]
Thanks. Yes, it looks like sprockets version 4 will made a good step forward, but I still have the strong feeling that the rails community moves away from sprockets to other tools like webpack. And coffeescript is dead IMHO.
I don't know how much effort it would take and if it's worth at all to migrate AA to webpack.
I will most likely run webpack and sprockets side by side in the meantime, should be possible.

**Comment by sjieg** [comment]
To help with some ticket cleanup. This ticket is resolved with  #5855 and should be closed.
