### ISSUE TITLE
destroy defined inside create for CommentsController

### ISSUE THREAD

**Issue by amiuhle** [activeadmin/activeadmin#5554]
https://github.com/activeadmin/activeadmin/blob/276d57f7027b89bd3f6a358e987b6687d093cbdc/lib/active_admin/orm/active_record/comments.rb#L75

**Comment by deivid-rodriguez** [comment]
:open_mouth:

So... is removing comments broken?

**Comment by amiuhle** [comment]
I don't think so, I suppose it's just somehow handled correctly in `super`?

**Comment by amiuhle** [comment]
Anyways, I can have a more detailed look at it, I just wanted to know whether I should adress this in #5555 or open another PR?

**Comment by deivid-rodriguez** [comment]
I think a separate PR is better :+1:

**Comment by javierjulio** [comment]
We have a PR ready to fix this.
