### ISSUE TITLE
Javascript toastr

### ISSUE THREAD

**Issue by soundnotation** [activeadmin/activeadmin#5556]
I want to show *toastr* notifications through *JavaScript* in my *ActiveAdmin*, possibly with translations. I put the following code in `app/assets/javascripts/active_admin.js.coffee`:

    #= require active_admin/base
    #= require activeadmin_addons/all
    #= require bootstrap-typeahead-rails
    #= require ./helpers/search
    #= require toastr/toastr
    #= require i18n
    #= require i18n/translations

    ...

    $(document).ready ->
      $('table#index_table_export_orders').on 'click', 'td.col-metadata_file', (e)->
        toastr.warning(I18n.t('bla.bla.bla'));

### How to reproduce
Click on an element table (the code above can be used for other examples by changing the selectors)

### Expected behavior
I expect a toastr warning to appear in my upper left corner of the index table, for example.

### Actual behavior
When clicking on the `'td.col-metadata_file'` element, nothing happens.

I have similar code in another section of my website and it works. Thus I have the sense that this can be a bug in ActiveAdmin.

**Comment by varyonic** [comment]
Cross post https://stackoverflow.com/questions/53265872/activeadmin-and-js-toastr

**Comment by soundnotation** [comment]
Solved it temporarily by importing the basic toastr js and css files from [the toastr GitHub page](https://github.com/CodeSeven/toastr/) (toastr.js, toastr.min.css, toastr.min.js, toastr.min.js.map), adding them to the app/assets/javascripts folder, and register them into the active admin initializer.
If anyone has a better solution, please let me know.
