### ISSUE TITLE
Road to Rails 6

### ISSUE THREAD

**Issue by seanfcarroll** [activeadmin/activeadmin#5558]
Rails 6 will [use Webpacker as the default](https://github.com/rails/rails/pull/33079). Supporting this can also be an opportunity to modernize ActiveAdmin assets, for distribution by Webpacker. This could also fall in line with the ActiveAdmin 2.0 release.

Some discussion on assets has been [made here](https://github.com/activeadmin/activeadmin/issues/3392)

My suggestion is that we move all assets (CSS and JS) into a 'theme', so that the first theme would be ActiveAdmin Classic, which uses jQuery and the current styling, but which is served via Webpack.

Taking this step would then allow the easy creation of new themes, for example with different styling and completely different JS, dropping jQuery if desired. I suggest the main repo would being in the ActiveAdmin Base and the default theme of ActiveAdmin Classic, which would live in an independent repo.

**Comment by deivid-rodriguez** [comment]
Hi @seanfcarroll, Rails 6 is indeed a great opportunity for doing things in more modern ways, but it's also a great challenge, I'm currently focusing on releasing what we now have in master, and I'll then try to give these challenges more thought.

**Comment by javierjulio** [comment]
@seanfcarroll no, Rails 6 will not drop Sprockets. When you have time make sure to read all the comments in that PR. I'm very familiar with it as I had gone through it about a month or two ago when I worked with webpacker to see what it would be like. I was curious as to why support was there for both. After having tried it though I can see why.

That's what makes me wonder if perhaps for AA users that are using webpacker and want to go all in and ditch sprockets, perhaps we could see about having an option to support only webpacker or sprockets for our assets rather than a mix. That might be a good first step here.

**Comment by seanfcarroll** [comment]
> having an option to support only webpacker or sprockets for our assets rather than a mix. That might be a good first step here.

This would be a good stepping-stone.

**Comment by nsuchy** [comment]
There was some mention of removing jQuery entirely. What is jQuery currently being used for? As Javascript has evolved over the years it’s become less and less necessary for projects. How difficult would it be to phase out entirely?

**Comment by yagudaev** [comment]
Any updates on this? The rails 6 betas are all out and it will likely be released at Rails Conf at the end of April

**Comment by isterin** [comment]
Any updates?  Numerous folks already using rails 6 in prod.

**Comment by javierjulio** [comment]
@yagudaev @isterin #5702

**Comment by cdesch** [comment]
Is there a workaround for this?

**Comment by yagudaev** [comment]
@cdesch it should all work for on Rails 6 we have been using it in our app for a while now. You still have to use the asset-pipeline instead of webpacker

**Comment by rept** [comment]
Is there a way of using Webpacker or is it needed to use the asset pipeline?

**Comment by sergewhite** [comment]
@rept Yes, check your ActiveAdmin.config and set `config.use_webpacker = true`

**Comment by rept** [comment]
@sergewhite  Thanks I'll check it out!

**Comment by yhk1038** [comment]
As follow @sergewhite,
> @rept Yes, check your ActiveAdmin.config and set `config.use_webpacker = true`

Just toggling the comment in config file, It was not enough.

I found Docs [docs/0-installation.md#webpacker](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md#webpacker).

Finally, if you already install ActiveAdmin, You may need to:

```ruby
# config/initializers/active_admin.rb

ActiveAdmin.setup do |config|
  ...

  # == Webpacker
  #
  # By default, Active Admin uses Sprocket's asset pipeline.
  # You can switch to using Webpacker here.
  #
  config.use_webpacker = true   # resolve this line
end
```

```bash
# Run the generator to get default Active Admin assets

$ rails g active_admin:webpacker
```

At last, **move old assets to `app/javascript` in properly.**

As follow the answer above, It'll help you some more to using **rails6 webpacker** without **sprocket**.

**Comment by bismark64** [comment]
I'm not sure if this was asked before but I'm using webpacker as the sole JS compiler for my app, and don't seem to find a way to use `config.register_javascript` with webpacker (using it for Google Maps). How can I solve this?
