### ISSUE TITLE
Open Collective

### ISSUE THREAD

**Issue by seanfcarroll** [activeadmin/activeadmin#5559]
I wonder if the key commiters of Active Admin would be interested in [Open Collective](https://opencollective.com/). It seems to have good traction for [larger projects](https://opencollective.com/discover) like Webpack and Babbel.

**Comment by deivid-rodriguez** [comment]
I am, for sure. I actually started a discussion on the Tidelift forum about how the services could [work together](https://forum.tidelift.com/t/opencollective-tidelift/81/6).

**Comment by seanfcarroll** [comment]
I think these movements are a good idea. Maintaining open source takes a lot of work, and money should not be it's own reward, but a bit for key contributors is a good idea.

Another project is https://rubytogether.org/

**Comment by deivid-rodriguez** [comment]
Yes! Each of these projects is very unique but they share some common goals, and they are doing a great job on improving the overall situation of open source. :tada:

**Comment by javierjulio** [comment]
Yes, I agree, all these are great! I'm for it. 👍🏻

**Comment by deivid-rodriguez** [comment]
I registered with opencollective, and I'm hoping to find some time to start playing around with it!
