### ISSUE TITLE
AdminComment priority in menu ignored.

### ISSUE THREAD

**Issue by amaridev** [activeadmin/activeadmin#5560]
Hi,
I have AdminComments enabled and it shows up in the top menu bar. Thing is, ordering is completely ignored as it seems.

### Expected behavior

I have given all resources a priority, starting with 1 up to 11. I wish to have the Admin Comments at position 12. 

In the config I set the following:
* config.comments_menu = { parent: 'Admin', priority: 20 }

### Actual behavior

No matter what priority I set, comments item is always at position 10 (probably default prio.) I also tested different locales, because I thought it would sort alphabetically, but no.

I wasn't able to find out if there is a maximum priority or a range. But the code doesn't seem like that. I also tested priority 0 or negative numbers for AdminComment. But the order stays unchanged.

**Comment by javierjulio** [comment]
If this is still an issue I would accept a PR for it. Thank you.
