### ISSUE TITLE
coffee-rails still listed as runtime dependency in gemspec for 1.4.0

### ISSUE THREAD

**Issue by edennis** [activeadmin/activeadmin#5575]
### Expected behavior

There should be no more dependency to coffee-rails.

### Actual behavior

The dependency is still listed in `activeadmin.gemspec`

### How to reproduce

Install activeadmin via bundler and inspect `Gemfile.lock` which lists coffee-rails as being a dependency of activeadmin.

![screen shot 2018-11-19 at 9 57 41 am](https://user-images.githubusercontent.com/47961/48696376-10b16e80-ebe2-11e8-8b7a-d803b3d59155.png)

**Comment by deivid-rodriguez** [comment]
This is correct, we'll drop the `coffee-rails` dependency in 2.0. I'll release a first prerelease for 2.0 shortly.
