### ISSUE TITLE
conditional scopes output strange output in index page

### ISSUE THREAD

**Issue by knagode** [activeadmin/activeadmin#5578]
After we upgraded to 1.4.0 we see that conditional scopes are outputting some strange debug info in the place where scopes should be. 
```
scope 'test_scope', if: -> { false } do |scope|
    scope.where(...)
  end 
```

This outputs:
![screenshot 2018-11-20 11 02 00](https://user-images.githubusercontent.com/4473199/48766001-bbde2880-ecb3-11e8-9fa5-f692802f18b1.png)

**Comment by deivid-rodriguez** [comment]
Thanks for the report @knagode! Let me have a look at this and I'll get back to you!

**Comment by deivid-rodriguez** [comment]
Hello again @knagode! I tried to reproduce this in both master and 1.4.0 but I couldn't so I'm going to need you to create a sample application that reproduces the error. Thanks!

**Comment by EtienneDepaulis** [comment]
Had the same bug. It happens when all provided scopes have a `false` condition.
We monkey-patched this way : 

```ruby
module ActiveAdmin
  module Views
    class Scopes < ActiveAdmin::Component
      def build(scopes, options = {})
        scopes.group_by(&:group).each do |group, group_scopes|
          ul class: "table_tools_segmented_control #{group_class(group)}" do
            group_scopes.map do |scope|
              build_scope(scope, options) if call_method_or_exec_proc(scope.display_if_block)
            end.compact
          end
        end
      end
    end
  end
end
```
(map + compact)
Not sure where the bug is to be honest. I'm happy to create a PR if this approach can work :)

**Comment by Looooong** [comment]
I can confirm this issue in 2.6.1.
