### ISSUE TITLE
Pundit adapter raise errors when using namespace

### ISSUE THREAD

**Issue by wenderjean** [activeadmin/activeadmin#5579]
I'm trying namespace capabilities for pundit policies on `master` branch where this feature is already available in `ActiveAdmin::PunditAdapter` but this change has broken a previous behavior regarding to collection scopes.

When I try to access my administrative panel the following error is raised:

`undefined method reorder for #<Array>`

It happens because `ActiveAdmin::DataAccess#apply_authorization_scope` calls `adapter#scope_collection` that returns the `Array<namespace, collection>` instead of the `Relation`.

```ruby
def apply_authorization_scope(collection)
  action_name = action_to_permission(params[:action])
  active_admin_authorization.scope_collection(collection, action_name)
end
```

```ruby
def scope_collection(collection, action = Auth::READ)
  # scoping is appliable only to read/index action
  # which means there is no way how to scope other actions
  Pundit.policy_scope!(user, namespace(collection))
rescue Pundit::NotDefinedError => e
   if default_policy_class && default_policy_class.const_defined?(:Scope)
     default_policy_class::Scope.new(user, collection).resolve
   else
     raise e
   end
end
```

### How to reproduce

It's possible to reproduce this behavior following these steps below:

1. Add `ActiveAdmin` from `master` branch in a Rails project
2. Create an admin page for a model
3. Configure a `pundit_default_namespace` 
4. Create a policy below the namespace configured before
5. Try to log into administrative page and go to the page model

**Comment by longkt90** [comment]
did you manage to find a fix for the issue?

**Comment by sasharevzin** [comment]
@longkt90 I tried to update the version but the error is still there :(
