### ISSUE TITLE
--no-assets option at install

### ISSUE THREAD

**Issue by colinrubbert** [activeadmin/activeadmin#5619]
Has there been discussion about having a **--no-assets** option for the initial install phase so that we can provide our own custom styling to be inline with the design assets of our application?

Something like this:
` rails g active_admin:install --no-assets`

I think it would be a beneficial addition to the application to remove the necessity of the included stylesheets and jquery.

**Comment by javierjulio** [comment]
This can't be supported because that would also exclude javascript files which are essential for various components in ActiveAdmin.

**Comment by colinrubbert** [comment]
We could re-write those components with vanilla JS, eliminating a dependency.

Is there no way to have alt files for jQuery and vanilla js or no js? 

I'm new at the whole gem building aspect of Ruby/Rails, enlightenment would be helpful.
