### ISSUE TITLE
How to add an ajax button?

### ISSUE THREAD

**Issue by labolado** [activeadmin/activeadmin#5654]
I want to add an approve buttons to resource items. when user click a "Approve" button, the resource item's status will be changed to  approved, and the button's text will be change to  "Cancel".

**Comment by labolado** [comment]
It's ok now. I added javascript with 
```
action_item :help, priority: 0 do
   render partial: "inc"
end
```

**Comment by antonintouron** [comment]
@labolado plz closed issue if it's ok :)
