### ISSUE TITLE
site_title not working on login page with dynamic namespaces

### ISSUE THREAD

**Issue by mabdelfattah** [activeadmin/activeadmin#5674]
For some reason `active_admin_application.site_title(self)` returns empty string in login page.

### Expected behavior

`active_admin_application.site_title(self)` returns the correct title.

### Actual behavior

`active_admin_application.site_title(self)` returns empty string.

### How to reproduce
```
ActiveAdmin.setup do |config|
    config.default_namespace = :admin

    namespaces = {
        admin: {
            title_i18n: 'admin.admin_site_title'
        },
        user: {
            title_i18n: 'admin.user_site_title'
        }
    }

    namespaces.each do |namespace, configs|
        config.namespace namespace do |namespace_configs|
            namespace_configs.site_title = proc { I18n.t(configs[:title_i18n]) }
        end
    end
end
```

**Comment by goy80** [comment]
active_admin_application.site_title -> returns empty.
active_admin_application.namespace(:admin).site_title_call -> returns corret value. (workaround)
