### ISSUE TITLE
default_actions still referenced in documentation

### ISSUE THREAD

**Issue by florianroesler** [activeadmin/activeadmin#5675]
On https://activeadmin.info/index.html in the code snippet the already obsolete method `default_actions` is still referenced. I think as this first snippet might be an entrypoint for many users, it should be updated to display `actions` instead.

The following line is the culprit: https://github.com/activeadmin/activeadmin/blob/9a33a081c99d9aa19045d46155ffe5f51ea76710/docs/index.html#L105

It also looks like the indentation is a little off for the whole snippet.

**Comment by deivid-rodriguez** [comment]
Closed by #5676. Thanks @florianroesler!
