### ISSUE TITLE
Devise deprecation warnings

### ISSUE THREAD

**Issue by atsushi-zto** [activeadmin/activeadmin#5688]
Hi,

I am running activeadmin with devise 4.6.1.
When I access activeadmin, I get the followings deprecation warnings.

```
DEPRECATION WARNING: [Devise] `DeviseHelper.devise_error_messages!`
```
`devise_error_messages!` will be removed in the next major version.
https://github.com/plataformatec/devise/blob/5be5220e5a65094f09d01b3c55cfb3061d8bce27/CHANGELOG.md#460---2019-02-07

So, actveadmin need to refactor these sources.  
https://github.com/activeadmin/activeadmin/search?q=devise_error_messages&unscoped_q=devise_error_messages

Best regards,

**Comment by JayNewstrom** [comment]
Can this be closed now that #5694 is merged?
