### ISSUE TITLE
Performace in activeadmin

### ISSUE THREAD

**Issue by sechix** [activeadmin/activeadmin#5689]
Hi, We have activeadmin installed but we have some memory problems in staging heroku retrieving data from models , so we are worry about this could affect to users platform performance in production when we are using the admin.

**Comment by chevinbrown** [comment]
This is more likely an issue with the way queries are written than AA itself. 

Can you provide specifics around the actual metrics, data size, and queries you're running?

**Comment by sechix** [comment]
thanks it is solved!
