### ISSUE TITLE
Add custom content to CSV downloads?

### ISSUE THREAD

**Issue by kelynch** [activeadmin/activeadmin#5701]
Is it possible to add custom text to CSVs for download?  I need to add a line of boilerplate explanatory text as the first row of each CSV file downloaded from our ActiveAdmin app.  Is there a logical place to extend this functionality in our app from the ActiveAdmin code base, or some config options I'm overlooking?

**Comment by varyonic** [comment]
You have reviewed [the docs on this](https://activeadmin.info/4-csv-format.html), yes?

**Comment by kelynch** [comment]
Yes, prior to posting this issue.  I also looked at the code and couldn't find a method to take action on a row, nor to reference content that isn't in the data source.  Is there something in the docs that I'm missing?

**Comment by kelynch** [comment]
Hoping for an update here -- is there a way built into this gem that allows one to add a row at the top of each CSV file before it's exported?

**Comment by liurui12w** [comment]
Maybe you need it.

csv do
  column "title" do |o|
    o.user_id && o.user && o.user.username #belong_to or (model def)
  end
end
