### ISSUE TITLE
Custom Menu for only one user role

### ISSUE THREAD

**Issue by josefarrugia** [activeadmin/activeadmin#5709]
Hi there,

Is there anyway to hide a custom menu from other user roles in the initialiser for activeadmin? I have tried `current_user.super_user?` and `current_user.try(:super_user?)`, however, obviously `current_user` hasn't been initialised yet. 

Any thoughts how can we get around this?

**Comment by marclerodrigues** [comment]
Hey @josefarrugia, have you tried following these steps https://activeadmin.info/13-authorization-adapter.html#setting-up-your-own-authorizationadapter ? 

I believe something like (after setting up your custom authorization adapter as described in the docs):
```ruby
class OnlyDashboard < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    case subject
    when ActiveAdmin::Page
      action == :read &&
        subject.name == "Dashboard" &&
        subject.namespace.name == :admin
    else
      false
    end
  end
end
```

would do the job.
