### ISSUE TITLE
Child menu item ends up as top menu item

### ISSUE THREAD

**Issue by lucev** [activeadmin/activeadmin#5712]
Hi, I'm having an issue with nested menu items in some rare occasions.

Instead of having just top menu item which is defined in initializer and corresponding child items defined in resources I end up having resource items both as child and top menu items.

<img width="1440" alt="Screenshot 2019-03-21 at 01 11 17" src="https://user-images.githubusercontent.com/326749/54740283-29935600-4bbb-11e9-92ca-e4dd04568939.png">

I found out that this happens only when web server has more than one thread count so I suspect it is related to race condition or other concurrency issue.

It's not reproducible every time but here is relevant code of my dummy app where I can reproduce it every second or third time. It happens in development when I hit page refresh really fast during server startup.

```
# app/admin/authors.rb
ActiveAdmin.register Author do
  menu parent: 'LIBRARIES', label: 'AUTHORS'
end
```

```
# config/initializers/active_admin.rb
config.namespace :admin do |admin|
  admin.build_menu :default do |menu|
    Rails.logger.debug "INITIALIZER; Time: #{Time.now.to_i}; Thread: #{Thread.current.object_id}"
    menu.add label: 'LIBRARIES', priority: 0
  end
end
```

```
# config/puma.rb
workers Integer(ENV['WEB_CONCURRENCY'] || 1)
threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
threads threads_count, threads_count

preload_app!
```

```
# Gemfile
ruby '2.6.1'

gem 'rails', '~> 5.2.2', '>= 5.2.2.1'
gem 'activeadmin', '~> 1.4.3'
gem 'devise', '~> 4.5.0'
```

[https://github.com/lucev/active_admin_test](https://github.com/lucev/active_admin_test)

I also experience this behaviour on my real project in production on Heroku, with more complex setup but I can't reproduce it consistently.

I'll appreciate any thoughts or feedback on this, thanks!

**Comment by msjonker** [comment]
We ran into this issue, too. It seems it's because the menus are being lazy loaded and stored globally during requests in non-thread-safe code. If they were loaded during `ActiveAdmin.application.load!`, I don't think this would be an issue. Loading them in the `after_load` callback seems to be a workaround that has worked for us:
```ruby
ActiveAdmin.after_load do |app|
  app.namespaces.each do |namespace|
    namespace.fetch_menu(ActiveAdmin::DEFAULT_MENU)
  end
end
```
I'm not terribly familiar with the ActiveAdmin code, but I don't see a downside to doing it this way, compared to what is currently happening. I can create a PR to add this to load code if this makes sense.

**Comment by buffpojken** [comment]
This seems to be related to our issue (see #6233) - will test your workaround.
