### ISSUE TITLE
Exporting two different csv in index page

### ISSUE THREAD

**Issue by Kuassari** [activeadmin/activeadmin#5725]
### The Problem

I tried to follow the solution by the user varunlalan for this issue: https://github.com/activeadmin/activeadmin/issues/4172 and I did everything the same, but got an error when I tried to run the server

### Expected behavior

I expected to have two downloadable files for csv in index page and that everything will work good

### Actual behavior

I got this error when I tried to run the server:
`undefined method csv_email' for #<ActiveAdmin::ResourceDSL:0x00007fc6054021d0> (NoMethodError)`

### How to reproduce

I wrote exactly the same in active admin initializer that was on the solution in https://github.com/activeadmin/activeadmin/issues/4172  and wrote this in admin/users.rb:

`  csv_email do` 
     `      column ("User id")                        { |user| user.id }` 
     `      column ("User Name")                      { |user| user.name }` 
     `      column ("Email")                          { |user| user.email }` 
    `   end` 

Still didn't work
I want to know what I did wrong and how can I make it work

**Comment by unionups** [comment]
See my reply this is maybe solution for you [#4172 ](https://github.com/activeadmin/activeadmin/issues/4172#issuecomment-600855013)
