### ISSUE TITLE
Reloads application twice

### ISSUE THREAD

**Issue by jscheid** [activeadmin/activeadmin#5739]
### Expected behavior

When `Rails.application.reloader.reload!` is invoked, for example because Rails or Spring detected that files have changed, `ActiveAdmin.application.load!` should only be called once because multiple invocations incur unnecessary overhead.

### Actual behavior

`ActiveAdmin.application.load!` is called twice.

### How to reproduce

I became aware of this when running `RubyProf.profile { Rails.application.reloader.reload! }`. The resulting output shows that `load!` is called twice.

I'm also going to send a PR soon that includes a test case.

**Comment by deivid-rodriguez** [comment]
Thanks @jscheid, sounds great!

Is this related to https://github.com/activeadmin/activeadmin/pull/4558? We were about to get that one in but never actually got to get in properly tested or reproduce the double loading.

**Comment by jscheid** [comment]
@deivid-rodriguez ah, I was looking but for some reason missed that one.

I can't tell, it might be related? But I believe it's a separate issue. For one thing, the issue I'm trying to fix gets triggered even when no routes or any ActiveAdmin files are changed.
