### ISSUE TITLE
version upgrade broke `action_item` argument behavior

### ISSUE THREAD

**Issue by manubete** [activeadmin/activeadmin#5745]
### Expected behavior

When I upgraded activeadmin to version `2.0.0.rc1`, I expected our code to be backwards compatible and not error out on previously used functions and methods.

### Actual behavior

Before I upgraded activeadmin to `2.0.0.rc1`, our calls to `action_item` did not require any arguments before starting the `do ... end` block. Below is an example snippet:

```
  action_item do
    resource = Resource.find(params[:resource_id])	    
    link_to "View Resource", admin_announcement_path(resource)
  end
```

After the upgrade however, we are getting errors that action_item requires an argument or two, such as a label or `:only` filter of sorts. Below is an working version of the new `action_item` :

```
 action_item :view_message do
    resource = Resource.find(params[:resource_id])	    
    link_to "View Resource", admin_announcement_path(resource)
  end
```

Was this an intentional change? Or does anyone suspect anything else going on? We never had errors like this before the upgrade
### How to reproduce

Upgrade active admin to version `2.0.0.rc1` in a code repository that uses similar snippets and run locally

**Comment by deivid-rodriguez** [comment]
Hi @manubete, thanks for reporting this. Can you try 2.0.0.rc2 and see if it fixes it? Thanks!

**Comment by deivid-rodriguez** [comment]
Hi @manubete, so I had a closer look at this.

This seems intentional. `action_item` without a name was deprecated in https://github.com/activeadmin/activeadmin/commit/a73ed3637e6a50e28c33c5b70db0d61d936d94d2#diff-529baad25097a0794f167b102b5afc43, which has been out there since 1.0.0.pre1, and indeed removed in https://github.com/activeadmin/activeadmin/commit/4014a37f0035197fd70c376d3b9e7be7b8c2c7f4#diff-529baad25097a0794f167b102b5afc43, released with 2.0.0.rc1.

Did you not see the deprecations?

**Comment by deivid-rodriguez** [comment]
These deprecations should be displayed on 1.x releases, but in any case I also documented this in the change log in https://github.com/activeadmin/activeadmin/pull/5747/commits/3bf2c6ce105eb5545960e828597332665c732ab0.

**Comment by deivid-rodriguez** [comment]
I double checked that this deprecation is correctly generated on activeadmin 1.x, so closing.

**Comment by stephenh** [comment]
@deivid-rodriguez thanks for looking into this and adding the changelog entry; we just wanted to sanity check this was on purpose, so will go fix all of our `action_items`. Thanks!
