### ISSUE TITLE
Resource named Tab gets bad styling

### ISSUE THREAD

**Issue by yoelblum** [activeadmin/activeadmin#5750]
[Please follow the guidelines for creating a bug report](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#4-did-you-find-a-bug).

The issue tracker is only for bugs and feature requests. If you need general
help please post to
[StackOverflow](http://stackoverflow.com/questions/tagged/activeadmin).

### Expected behavior

If you have a model named tab, I expect the activeadmin menu item for "Tabs" to look normal 

### Actual behavior
The menu item inherits a width 100% because of it's "tabs" id, this causes it to be on it's on line. This is solvable by renaming the resource or patching the css but maybe some thought should be given to clashing names (also trouble may happen with 'Dashboard' name)
<img width="1662" alt="Screen Shot 2019-04-25 at 10 34 22" src="https://user-images.githubusercontent.com/3051798/56721918-379e3e80-6746-11e9-8588-e773c4c9d6ba.png">

What actually happens?

### How to reproduce

Your best chance of getting this bug looked at quickly is to provide an
**executable test case** demonstrating the expected behavior that is not
occurring. [Please follow the guidelines for creating a bug
report](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#4-did-you-find-a-bug).

**Comment by javierjulio** [comment]
The CSS in general needs to be rewritten and ideally not adding dynamic classes from resource names, at least without something like a prefix or suffix.
