### ISSUE TITLE
error thrown when customizing controller action: undefined local variable or method `active_admin_authorization' for "            <div class=\"comments\"></div>\n":ActiveAdmin::Comments::Views::Comments Did you mean?  active_admin_form_for

### ISSUE THREAD

**Issue by alaarab** [activeadmin/activeadmin#5754]
### Expected behavior

I should be able to extend my show controller and have comments on an admin show page at the same time. However, doing so results in a failure.

### Actual behavior

```
undefined local variable or method `active_admin_authorization' for "            <div class=\"comments\"></div>\n":ActiveAdmin::Comments::Views::Comments
Did you mean?  active_admin_form_for
```
![image](https://user-images.githubusercontent.com/1730921/57050758-01275e80-6c33-11e9-91b1-4c7e936dd290.png)

### How to reproduce

I have no authorization adapter set in my config file.
I attempt to extend my controller as such (add this to a file in your app/admin/):

```
  controller do

    def show
      @user = User.find(params[:id])
      show! 
    end

  end
```

I was able to extend my controllers in previous versions of ActiveAdmin. I recently updated to the newest version of ActiveAdmin which has now introduced this error, and tracing the file, my assumption is that an update 5 months ago introduced this issue:
https://github.com/activeadmin/activeadmin/commit/585e5937920b76c1d86a6c177f14edba100aef7d#diff-fc2e0ad81b3922c3c09beb9d73c3098a

**Comment by deivid-rodriguez** [comment]
Thanks for the report. I'll have a look!

**Comment by deivid-rodriguez** [comment]
I'll try to find a reproduction for this in any case but if you can share a minimal sample app that reproduces this it'd be great.

**Comment by thibaudgg** [comment]
@deivid-rodriguez if this can help I got the same issue using the `active_admin_comments` on [this file](https://github.com/ragedevert/acp-admin/commit/d3b511dad959511bc590f0cb0129351fb5b8a546), weirdly my app also used `active_admin_comments` in other places without any problem.

**Comment by alaarab** [comment]
> I'll try to find a reproduction for this in any case but if you can share a minimal sample app that reproduces this it'd be great.

@deivid-rodriguez https://github.com/alaarab/aa5754  

check out /admin, create a post, and visit the admin show page.

**Comment by deivid-rodriguez** [comment]
Thanks for the nice repro, #5754 should fix this!
