### ISSUE TITLE
Cannot do column calculation

### ISSUE THREAD

**Issue by Znow** [activeadmin/activeadmin#5757]
### Expected behavior
Calculation of 2 integer fields on object

```ruby
index do
  column "Test" do |property|
    property.field_a / property.field_b * 100
  end
end
```
Should output some calculated amount, but always and only returns "0"

### Actual behavior

The above logic always returns 0 or "0" in the column. No calculations, neither done with "raw" or anything else works.

Both "field_a" and "field_b" has a integer value

**Comment by Znow** [comment]
bump

**Comment by mvz** [comment]
@Znow have you tried the calculation outside of ActiveAdmin? If both fields are integers you get rounding effects. E.g.:

```
irb(main):001:0> 5 / 6 * 100
=> 0
```

**Comment by Znow** [comment]
@mvz Thanks - got it working, .to_f was the issue here.

Besides this - now when I have my custom column with rows, showing data like 0.12, 0.33 and so on, how can I apply sorting on this custom column?

**Comment by Znow** [comment]
@javierjulio Why are you closing it?

**Comment by deivid-rodriguez** [comment]
@Znow Your previous message sounded like you got it working and the problem was not inside activeadmin, right?

**Comment by Znow** [comment]
@deivid-rodriguez Yes certainly - But I still have a question regarding custom column sorting - I can create a new issue for this, since I cannot find any documentation or help regarding this
