### ISSUE TITLE
pass additional field to form

### ISSUE THREAD

**Issue by pulkit005** [activeadmin/activeadmin#5763]
form do |f|
    f.inputs 'TableauEmbeddedCode' do
      f.input :embedded_code
      f.input :report_name, required: false
      f.input :xyz 
      # end
    end
    f.actions do
      f.submit 'Submit'
    end
  end

xyz is not a column in my TableauEmbeddedCode table , so when form is submitted it says xyz is not defined field. how to pass xyz without getting this error.

**Comment by gururuby** [comment]
@pulkit005, Hi, you should add attr_accessor to your model, like
`attr_accessor :xyz`, and add this field to permitted_attributes
