### ISSUE TITLE
Release new version of activeadmin 2.0.1

### ISSUE THREAD

**Issue by zocoi** [activeadmin/activeadmin#5765]
Hi @deivid-rodriguez the current master no longer uses `sass` and instead requires `sassc` which makes compiling assets faster. Could you release a new version of the gem soon?

**Comment by deivid-rodriguez** [comment]
Hi @zocoi! Yes, I expect to cut a new release from master in the next few days. I'll call it 2.1.0 though.

**Comment by deivid-rodriguez** [comment]
ActiveAdmin 2.1.0 has been released :+1:
