### ISSUE TITLE
Feature: support arbre methods in custom action

### ISSUE THREAD

**Issue by salzig** [activeadmin/activeadmin#5766]
### Expected behavior

While defining a `collection_action` or `member_action` i would like to use Arbre, like i'm used to in `index` or `show` 

### Actual behavior

Right now i'm able to call `render text: 'some'`, or render a template file.

### How to reproduce

For any registered Object, define a custom action and try to use Arbre methods. 

```
collection_action :example, methods: [:get] do 
  h1 "Hello World"
end
```

**Comment by macfanatic** [comment]
In the `index` and `show` actions you mention, you're rendering a view via arbre in the DSL itself.  The actual fetching of the collection or individual resource is handled for you as the only real prep work to render the view.

For other controller actions (ie, forms, destroy etc) you are writing the actual controller action implementation.  Your `collection_action` for instance might not render anything at all, but simply redirect.

You're correct in calling `render`.

**Comment by salzig** [comment]
And i would love to render using arbre within the DSL method `collection_action` :)

**Comment by macfanatic** [comment]
But this would be a massive breaking change; there isn't a clear DSL change here that would be a graceful addition.

As you mention uou can render arbre, either using an explicit `render`, or implicit rendering based upon view paths, just not inline.  If you want to render here, you'd need to instantiate an arbre context, convert to html, and render the response as a string via rails.

Ie,

```ruby
ActiveAdmin.register Post do
  collection_action :example do
    # without a render call, you could render "app/views/posts/all.html.arb" by default (vanilla rails)
  end
end
```

**Comment by salzig** [comment]
Something i would like to see it maybe a DSL addition like `respond(&block)` which handles the creation of the context in a way it is done for the "normal" actions, eg.
```
collection_action :exmaple do 
  respond do 
    h1 "Hello World"
  end
end
```

Had planned to show up with a mergerequest, but didn't had much time and haven't fully understand how you do the setup.

**Comment by macfanatic** [comment]
I think the following works today with minimal project-specific setup, but haven't tested this.

```ruby
controller do
  def respond(&block)
    render html: Arbre::Context.new(&block)
  end
end

collection_action :example do
  respond do
    h1 "Hello World"
  end
end
```

**Comment by wyattades** [comment]
The following worked for me:
```ruby

my_block = proc do |users|
  table_for users do
    ...
  end
end

collection_action :example do
  args = [User.all]

  html = Arbre::Context.new({}, view_context).instance_exec(*args, &my_block)

  render html: html
end
```
