### ISSUE TITLE
Hide second drop down based on the first drop down. How do?

### ISSUE THREAD

**Issue by liurui12w** [activeadmin/activeadmin#5770]
Display different inputs by type

**Comment by McAlexVrn** [comment]
Hello! You can use this thing https://github.com/blocknotes/activeadmin_dynamic_fields

**Comment by liurui12w** [comment]
> Hello @liurui12w! You can use this thing https://github.com/blocknotes/activeadmin_dynamic_fields

Thanks for your help. I'll check it out.

**Comment by liurui12w** [comment]
> > Hello @liurui12w! You can use this thing https://github.com/blocknotes/activeadmin_dynamic_fields
> 
> Thanks for your help. I'll check it out.

Thank you again. This I need.
