### ISSUE TITLE
Custom column sorting

### ISSUE THREAD

**Issue by Znow** [activeadmin/activeadmin#5781]
Hi,

I have a custom column as defined below, which does some plain calculation

```ruby
column "Test" do |property|
  (property.field_a.to_f / property.field_b.to_f) * 100
end
```

How can I apply sorting on this column? Since it is not applied by default for custom columns.

I have searched alot through previous issues, stackoverflow, google etc., and cannot seem to find anything that solves my issue.

Thanks in advance

**Comment by Znow** [comment]
Any updates on this?

**Comment by deivid-rodriguez** [comment]
@Znow I'm sorry for the lack of response here.

As the following spec illustrates

https://github.com/activeadmin/activeadmin/blob/5a7db303904260f14aa653cc8280b91c56f92fa6/spec/unit/views/components/table_for_spec.rb#L394-L399

`active_admin` is not able to apply sorting if your column contains a virtual attribute, only if it's a database column.

You can probably do your calculation using SQL, save it to an SQL column alias, and sort by that. Have a look at https://github.com/activeadmin/activeadmin/issues/3085 for ideas.
