### ISSUE TITLE
Add a form option to action items

### ISSUE THREAD

**Issue by Uelb** [activeadmin/activeadmin#5793]
Hi,

There is a form option for batch actions that works great, and I would like to be able to have the same behavior using action items. It seems like it would not take too much time to implement so I'm going to try to do a pull request about it.

Something like :
`action_item :do_something, only: :show, form: { my_param: :text }`

**Comment by deivid-rodriguez** [comment]
@Uelb I think the benefit of `action_item` is to get things done in one click. If you need a for, why not using the "edit" page?
