### ISSUE TITLE
CDN for ActiveAdmin 2

### ISSUE THREAD

**Issue by HienNguyenAsnet** [activeadmin/activeadmin#5804]
### Expected behavior

I want to use CDN link for some javascript lib and CSS. But `register_javascript` and `register_stylesheet` removed out from ActiveAdmin 2. Another way to do that?

**Comment by deivid-rodriguez** [comment]
Hei @HienNguyenAsnet. We ended up not removing nor deprecating those for ActiveAdmin 2. Perhaps you're using an old 1.x version where we planned to deprecate those for ActiveAdmin 2?

**Comment by HienNguyenAsnet** [comment]
Thank for the information. I have plan upgrade activeadmin gem from 1.0 to 2.0 but when upgrade from 1.0 to 1.1. I saw the message and stop upgrading.

One more thing, Are we have a guideline for upgrade from 1.0 to 2.0; necessary change and any issue?

**Comment by deivid-rodriguez** [comment]
There's only minimal incompatibility between 1.0 and 2.0, so we don't have a specific upgrade guide. The CHANGELOG is the best resource to check the main changes being introduced.

Regarding the `register_{javascript,stylesheet}` deprecation, they were undeprecated in 2.0.0.rc1, so you'll get the same message in all intermediate versions (1.1-1.4), but don't worry, they didn't go away in the end.

Closing this, good luck with the upgrade!
