### ISSUE TITLE
Resource-level authorisation?

### ISSUE THREAD

**Issue by Sprachprofi** [activeadmin/activeadmin#5809]
Am I missing something obvious?? I am using ActiveAdmin to control different things in my NGO: members, staff, donations and so on, each defined as an ActiveAdmin Resource (i.e. tab with different views, actions and so on). However, I don't seem to be able to implement proper authorization, because ActiveAdmin does not allow Resource to be a feature in its custom AuthorizationAdapters. That is, the **subject of the authorize? method is either a Rails model (like User or Donation) or an ActiveAdmin::Page but not an ActiveAdmin Resource.**

Actually using the ActiveAdmin::Page for authorization is worse than useless because the subject.name says "Dashboard" no matter whether someone is trying to access members, staff or donations. Also, using Namespace doesn't work because all three were assigned to the :admin namespace. I have not been able to get the authorized? method to tell me the controller name within that namespace, which, according to the documentation, should be Admin::StaffController or similar (knowing the controller name would solve the problem). Some people may be fine using the Rails model for authorisation, but both my Members resource and my Staff resource are based on the User model, they just provide vastly different admin experiences, different actions, and also different people should have access to these admin pages.

Is there really no way to implement access based on the Resource or the controller?? This seems to be the most common-sense way to restrict access to regions of the site, long before we talk about whether someone should be able to delete Users or not...

My production environment currently has ActiveAdmin 1.4.3 with Rails 5.1.

Thank you!

**Comment by deivid-rodriguez** [comment]
Can you show an example? I think you could do what you want by actually defining `Staff` and `Member` models.

```ruby
# app/models/staff.rb
class Staff < User
end

# app/models/member.
class Member < User
end
```

And then defining separate standard admin resources for each.

I guess you're defining the pages using `:as`, like:

```ruby
ActiveAdmin.register User, as: "Member" do
end

ActiveAdmin.register User, as: "Staff" do
end
```

**Comment by Sprachprofi** [comment]
Thank you. Yes, I'm using `as:` for the pages.

I solved the problem by figuring out how to have before_filters in ActiveAdmin Resources, and then using the same access-control that I have in mixed public/private sections of the site:

```ruby
controller do
  before_action -> { require_privilege("administer_staff_in_country", "any") }
    
  def scoped_collection
    scope = UserPrivilege.get_scope_of_privilege(current_user, "administer_staff_in_country")
    if scope != "any"
      User.staff.where(country: scope)
    else
      User.staff
    end
  end
    
end
```

So you can mark this issue as solved. I think it would be good to add to the ActiveAdmin tutorial section on authorisation though ("if you already have an authorisation system functioning on a per-controller basis, you can keep using it within ActiveAdmin by doing ..."), because this information is really hard to find.
