### ISSUE TITLE
loading active_admin assets in admin pages only

### ISSUE THREAD

**Issue by l4u** [activeadmin/activeadmin#581]
I am using Rails 3.1.
Is it possible to exclude the active_admin assets in the asset pipeline, and load them in the admin pages only?

Currently I've removed the assets from asset pipeline.
And I've copied the generated  active_admin.css and active_admin.js to my public/assets/  (not app/assets/) folder

Is there a better way?

**Comment by ayazahmadtarar-pikessoft** [comment]
doest worked for me . active admin overriding all of my apps
