### ISSUE TITLE
start index page with zero record

### ISSUE THREAD

**Issue by g13ydson** [activeadmin/activeadmin#5810]
How can I start index page with zero record?
I've tried the following, my collection of users starts empty, but the filters do not work

```
controller do
    def scoped_collection
      User.none
    end
end
```

> User.none
>  => #<ActiveRecord::Relation []

I want users to only appear after filtering

**Comment by deivid-rodriguez** [comment]
Maybe something like

```ruby
controller do
  def scoped_collection
    if params["q"]
      super
    else
      super.none
    end
  end
end
```

**Comment by g13ydson** [comment]
thanks @deivid-rodriguez , this worked perfect.
