### ISSUE TITLE
Rails 5.2, Active Admin add links to index page

### ISSUE THREAD

**Issue by cristianogregnanin** [activeadmin/activeadmin#5820]
Using Rails 5.2.3, ActiveAdmin 2.1.0 and aasm 5.0.5 I want to create links for the permitted events for a resource managed by aasm.
I want to show the links for the status change in the index page, it works with this code: 

```
  index do
    id_column
    column :status

    actions do |resource|
      item 'pdf', pdf_master_fine_path(resource)

      resource.aasm.events({ permitted: true }, current_user).map(&:name).each do |event|
        item event, polymorphic_path([current_user.role, resource], action: event)
      end
    end
```

In the picture I show the result: the links are created but is printed the entire array.

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/yO87S.jpg

How can I solve? I don't want to print the entire array.

**Comment by digitalidentity4d** [comment]
Digital identity of issud ssn selfe me

**Comment by naveed-ahmad** [comment]
try this 

```
permitted_events = resource.aasm.events({ permitted: true }, current_user).map(&:name)
permitted_events.each do |event|
    item event, polymorphic_path([current_user.role, resource], action: event)
end
```

**Comment by cristianogregnanin** [comment]
> try this
> 
> ```
> permitted_events = resource.aasm.events({ permitted: true }, current_user).map(&:name)
> permitted_events.each do |event|
>     item event, polymorphic_path([current_user.role, resource], action: event)
> end
> ```

same problem

**Comment by nitsujri** [comment]
@cristianogregnanin 

```
    actions do |resource|
      item 'pdf', pdf_master_fine_path(resource)

      resource.aasm.events({ permitted: true }, current_user).map(&:name).each do |event|
        item event, polymorphic_path([current_user.role, resource], action: event)
      end
      nil # Clearning the return from the each, you don't want this.
    end
```

**Comment by javierjulio** [comment]
Duplicate #6014
