### ISSUE TITLE
display_name_methods is not such a great idea

### ISSUE THREAD

**Issue by Ecco** [activeadmin/activeadmin#5825]
Imagine you create a link to an Article object, for example with this:

```ruby
show do
  attributes_table do
    row :article
  end
end
```

Active Admin will automagically pick up a text to display for the Article object, by trying to call `Article#display_name`, `Article#name`, etc… following what is set in `config.display_name_methods`.

The problem : this breaks MVC! Figuring out a *display* name for an object is some *view* code, definitely not some *model* code. For instance, one wouldn't be able to use any view helper in `Article#display_name`.

Instead of calling a method on an object, I think Active Admin should either:

* Call a named helper, whose name is dynamically found from the model's class name. e.g. `admin_article_display_name(article)`.
* Or simply look for an I18n translation, passing the object. E.g. `I18n.t("active_admin.display_name.article", article)`

Something worth noting: Formtastic makes the same "mistake" and uses `Formtastic::FormBuilder.collection_label_methods`.

**Comment by Fivell** [comment]
@Ecco ,  we are using  decorators for it.

**Comment by Ecco** [comment]
Oh… I hadn't seen this part in the Active Admin doc! Thank you so much for the pointer!

Now, even though you've 100% solved my issue, it might still be an interesting discussion. Maybe `display_name_methods` should be deprecated? Feel free to close this issue if you think everything's great as-is though 😄

**Comment by Fivell** [comment]
@Ecco IMO it depends , sometimes I need to setup AA with 10-20 pages in very limited time frame , in such cases display_name methods can be very helpful. When we are talking about large projects and very custom logic for displaying labels/names for records - this is another story 😄

**Comment by Ecco** [comment]
Yeah, I see, `display_name_methods` is a handy quick-and-dirty shortcut. Thanks!
