### ISSUE TITLE
ArgumentError (Invalid route name: '����Q�Vin_scans'):

### ISSUE THREAD

**Issue by ethicalhack3r** [activeadmin/activeadmin#5849]
### Expected behavior

My project should boot without errors.

### Actual behavior

I get the following error from stdout:

```
_web  | ArgumentError (Invalid route name: '����Q�Vin_scans'):
_web  |   
_web  | config/routes.rb:39:in `block (3 levels) in <main>'
_web  | config/routes.rb:38:in `block (2 levels) in <main>'
_web  | config/routes.rb:37:in `block in <main>'
_web  | config/routes.rb:3:in `<main>'
```

### How to reproduce

These are the lines in question in my routes.rb file:

```
constraints subdomain: 'admin' do
    authenticate :user, ->(u) { u.admin? } do
      ActiveAdmin.routes(self)
      require 'sidekiq/web'
      mount Sidekiq::Web => '/sidekiq'
    end
```

Versions in use:

ActiveAdmin version: 2.2.0
Rails version: 6.0.0
Ruby version: ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]

**Comment by deivid-rodriguez** [comment]
Yes, sorry about that. This is a _ruby_ regression in ruby 2.6.4. It will be fixed in ruby 2.6.5, but for now the easiest way to get rid of this is to downgrade to 2.6.3.

See https://bugs.ruby-lang.org/issues/16136 for more information.

**Comment by ethicalhack3r** [comment]
Wow, thanks for the quick response!

I'm glad it's not just me!

I'll downgrade to Ruby 2.6.3 for now.

**Comment by layerssss** [comment]
@ethicalhack3r Ruby 2.6.5 is out. And upgrading 2.6.4 => 2.6.5 fixed the issue for me.

**Comment by deivid-rodriguez** [comment]
Thanks, I'll close this one now!
