### ISSUE TITLE
Feature request: Ability to customize pages <title>s

### ISSUE THREAD

**Issue by megatux** [activeadmin/activeadmin#5852]
Looking at lib/active_admin/views/pages/base.rb I see that the HTML TITLE format is fixed ( "title | site_name" )

```
def build_active_admin_head
          within head do
            html_title [title, helpers.active_admin_namespace.site_title(self)].compact.join(" | ")
```
I would like to be able to redefine it, to match other _custom_ format.  Thx!

**Comment by Andrew-Max** [comment]
:+1:
