### ISSUE TITLE
Custom input_html for DateRangeInput

### ISSUE THREAD

**Issue by mirelon** [activeadmin/activeadmin#5864]
I want to provide custom html option (autocomplete: :off) for DateRangeInput.
I use this filter:

    filter :created_at, as: :date_range, input_html: {autocomplete: :off}

### Expected behavior

HTML element with attribute `autocomplete="off"`

### Actual behavior

HTML element is without that attribute.

DateRangeInput https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/inputs/filters/date_range_input.rb does not allow custom "input_html" options.

Other filters (like DatePickerInput) merges the "input_html" options:

        def input_html_options
          super.merge(class: "datepicker")
        end

Should DateRangeInput do the same?

**Comment by deivid-rodriguez** [comment]
Hi @mirelon, thanks for noticing this!

What you say makes sense, it seems to me that `input_html` should be merged like with other input types. Fancy opening a PR? :)
