### ISSUE TITLE
Conflict between meta_tags config and Tag model

### ISSUE THREAD

**Issue by dvkch** [activeadmin/activeadmin#5890]
First of all, thanks for this amazing gem. I'm new to Rails and this has been invaluable for me.

Now about that bug : when I visit `/admin/tags/:id` I can see a Tag object address printed out in the web page. See first line before header in the attached screenshot.

<img width="414" alt="Screenshot 2019-10-18 at 15 36 57" src="https://user-images.githubusercontent.com/1838148/67098825-285ff100-f1bd-11e9-9d7d-2ba9a6015ded.png">

When inspecting the page source it seems the culprit is linked with meta tags handling. Try searching for `0x00007fb49d066a18` in the following excerpt : 

```
<!DOCTYPE html><html lang="en">
  <head>
    <title>test | My App</title>
<link rel="stylesheet" media="screen" href="/assets/active_admin.self-df2f0b5617ac0f32412df760ed54f228f5b7db311fb640fed3c0926531032ff3.css?body=1" /><link rel="stylesheet" media="print" href="/assets/active_admin/print.self-5d2debdb5d662c201d203d63ad601036a4ce6dced51057e070dddbd4ec256d27.css?body=1" />#&lt;Tag:0x00007fb49d066a18&gt;<script src="/assets/jquery3.self-e200ee796ef24add7054280d843a80de75392557bb4248241e870fac0914c0c1.js?body=1"></script>
<script src="/assets/jquery-ui/version.self-c8e3d1203da26ea7efdf83c1eabb3f0ba55cb68e463f5ccf0d77bd15ce6a8e61.js?body=1"></script>
<script src="/assets/jquery-ui/keycode.self-ad63cd20acf49dd333bbbc537454d7d475bd610eb5b88de0dca009f0c3d314b1.js?body=1"></script>
``` 

This lead me to check how I configured meta tags in `config/initializers/active_admin.rb` :

```
  config.meta_tags = { viewport: 'width=device-width, initial-scale=1' }
  config.meta_tags_for_logged_out_pages = { viewport: 'width=device-width, initial-scale=1' }
```

And bingo, when I remove those two lines the bug disappears. I figure there is some namespacing issues on some variables, but I just started Rails and wouldn't know where to being.

Active Admin version is 2.4.0, Rails is 6.0.0 (was able to reproduce on 5.2.3 too) 

Here is a sample app reproducing the problem :
[my-app.zip](https://github.com/activeadmin/activeadmin/files/3744175/my-app.zip)

Thanks for considering, and if you have any idea for a workaround that would be great!

**Comment by micred** [comment]
We create a PR to (hopefully) fix the bug during an Italian Hacktoberfest event :-)
Hope it helps.

**Comment by dvkch** [comment]
Thanks you for your quick answer, I can confirm `http://localhost:3000/admin/tags`this PR solved the issue on my end!

**Comment by deivid-rodriguez** [comment]
Did you try #5895 or #5892?

**Comment by dvkch** [comment]
Hadn't seen there were two of them. I pulled using `meta_tags_and_tag_conflict` branch name, so i'd say #5895

**Comment by deivid-rodriguez** [comment]
Great, that's the right one, thanks for confirming :+1:.
