### ISSUE TITLE
Content-Security-Policy nonce support?

### ISSUE THREAD

**Issue by gsar** [activeadmin/activeadmin#5891]
### Expected behavior

Rails 5.2 and later support a `Content-Security-Policy` configuration out of the box which allows enabling CSP nonces via an option.

I expect activeadmin to transparently support this option when it is enabled by passing the `nonce: true` option for all helpers like `javascript_tag` and `javascript_*_tag`.

### Actual behavior

No nonce value is included and loading scripts configured in `config.head` fails during initialization.

I am having to monkey patch the `build_active_admin_head` to work around this issue, however this should not be necessary.  My workaround:

``` ruby
# this monkeypatch is needed to support nonce for CSP
module ActiveAdmin
  module Views
    module Pages
      class Base < Arbre::HTML::Document
        alias original_build_head build_active_admin_head

        def build_active_admin_head
          original_build_head

          within head do
            text_node(javascript_include_tag('/javascripts/active_admin.js', nonce: true))
            text_node(javascript_include_tag('/javascripts/json_editor.js', nonce: true))
          end
        end
      end
    end
  end
end
```

**Comment by javierjulio** [comment]
Perhaps a simple options hash feature can be implemented. I would accept a PR for that. Thank you. I believe there may be a similar request or even PR as I think another feature needs being able to pass options to these methods.

**Comment by zacheryph** [comment]
@javierjulio I am not sure this was resolved in an _obvious_ manner?

The only way to set this now is by adding `nonce: true` to every `register_javascript` line. The odd (non obvious) bit here is that; in order to add the nonce to `active_admin.js` I have to add a register line for it. Which otherwise isn't necessary.

**Comment by javierjulio** [comment]
@zacheryph to me that's necessary and expected based on how registration is implemented.

**Comment by guitrusted** [comment]
Hey guys, I was struggling with the same issue and tried to apply the monkey patch but it did not work for me.

So, inspecting the [source code of the active admin v3.1.0](https://github.com/activeadmin/activeadmin/blob/v3.1.0/lib/active_admin/views/pages/base.rb#L42) (the one I'm using now), I found a way to make it work by just adding the code below into the `config/initializers/active_admin.rb` file. 

```ruby
ActiveAdmin.setup do |config|
  # Enabling nonce because CSP strict_dynamic for scripts_src directive
  # Reference: https://github.com/activeadmin/activeadmin/blob/v3.1.0/lib/active_admin/views/pages/base.rb#L42
  config.javascripts['active_admin.js'] = { nonce: true }

  (...)
end
```

Not sure if there is already a better way to solve this, but it seemed like a good solution for me and may help anyone else.

**Comment by gsar** [comment]
@javierjulio correct, all i have now (in activeadmin 3.2.0) is these to lines:

``` ruby
  config.register_javascript 'vendor.js', nonce: true
  config.register_javascript 'active_admin.js', nonce: true
```
