### ISSUE TITLE
Nested forms

### ISSUE THREAD

**Issue by cernyjakub** [activeadmin/activeadmin#59]
Hello! I am looking at ActiveAdmin as a candidate to be used in my next project, I like it a lot.

However in all the examples, the edit form only edits the attributes of the given model. Is it possible to somehow edit associated models like Contacts on Person page (contact belongs_to person)?

I have seen some support for this in Formtastic, but I have no idea if it is possible in ActiveAdmin - how to make "add contact" button on Person page etc...

Thanks in advance for the reply!
Jakub Cerny

**Comment by thesteady** [comment]
I encountered @Zamyatin-AA 's issue: when doing an `f.has_many` in my edit form, existing relationships in my `has_many, :through` were getting duplicated. I needed to add a hidden field with the `id` of the join table and update the accepted attributes to get this problem to go away. Thought I'd report in case anyone else stumbles on this issue!

**Comment by mplewis** [comment]
Sorry for gravedigging, but I came upon this thread trying to learn how to build a nested form and it's extremely helpful.

In the latest build of ActiveAdmin, `f.buttons` has been deprecated and removed. You will need to use `f.actions` instead. Hope this helps!
