### ISSUE TITLE
Download Links showing up with paginated collection despite having download links disabled globally 

### ISSUE THREAD

**Issue by lauramosher** [activeadmin/activeadmin#5922]
[Please follow the guidelines for creating a bug report](https://github.com/activeadmin/activeadmin/blob/master/CONTRIBUTING.md#did-you-find-a-bug).

The issue tracker is only for bugs and feature requests. If you need general
help please post to
[StackOverflow](http://stackoverflow.com/questions/tagged/activeadmin).

### Expected behavior

What do you think should happen?

When the following is set:

```ruby
config.namespace :admin do |admin|
  admin.download_links = false
end 
```
I expect to see no download links anywhere in admin

### Actual behavior

What actually happens?

Instead, download links are available with a paginated collection regardless of the disable everywhere configuration set.

### How to reproduce

Your best chance of getting this bug looked at quickly is to provide an
**executable test case** demonstrating the expected behavior that is not
occurring.

Basic configuration in initializer and my registered resource

```ruby
# config

ActiveAdmin.setup do |config|
  config.namespace :admin do |admin|
    admin.download_links = false
  end 
end

# admin model

ActiveAdmin.register MyModel do
  show do
    tabs do
      tab "MyTab" do
        panel "All" do
          paginated_collection do
            table_for collection { .. }
          end
        end
      end
    end
  end
end
```

Specifying `download_links: false` when instantiating `paginated_collection` works as expected, though I would still expect that the component accepts / adheres to the global configuration.

**Comment by javierjulio** [comment]
If this is still an issue, I would accept a PR for it. Thank you.
