### ISSUE TITLE
bundle error -- An error occurred while installing sassc (2.2.1), and Bundler cannot continue.

### ISSUE THREAD

**Issue by AdminDev826** [activeadmin/activeadmin#5940]
I would like to install `activeadmin` by adding `gem 'activeadmin'` in the Gemfile.
But I am getting the bundler error related with `sacssc`.
ruby -v 2.4
rails -v 5.1.6
```
compiling ./libsass/src/c99func.c
/bin/sh: gcc:  not found
make: The error code from the last command is 127.


Stop.

make failed, exit code 2

Gem files will remain installed in /PowerRuby/prV2R4/lib/ruby/gems/2.4.0/gems/sassc-2.2.1 for inspection.
Results logged to
/PowerRuby/prV2R4/lib/ruby/gems/2.4.0/extensions/powerpc-aix-7/2.4.0/sassc-2.2.1/gem_make.out

An error occurred while installing sassc (2.2.1), and Bundler cannot continue.
Make sure that `gem install sassc -v '2.2.1' --source 'https://rubygems.org/'` succeeds before
bundling.

In Gemfile:
  activeadmin was resolved to 2.4.0, which depends on
    sassc-rails was resolved to 2.1.2, which depends on
      sassc
```
`gem install sassc -v '2.2.1' --source 'https://rubygems.org/'` is not working for me..

**Comment by deivid-rodriguez** [comment]
Hi @AdminDev826!

This is the relevant part of the log you posted:

```
/bin/sh: gcc:  not found
```

The `sassc` gem includes a native extension, so `bundler` needs `gcc` to be able to compile it. So, install `gcc` and you should be fine.

Hope that helps!

Closing since this is not an activeadmin issue in any case!
