### ISSUE TITLE
Active Admin not taking precompile assets on production

### ISSUE THREAD

**Issue by jadamdipak** [activeadmin/activeadmin#5951]
active admin not taking the precompile assets on production even it's present in public assets folder but it's taking different activeadmin.js and activeadmin.css file

**Comment by deivid-rodriguez** [comment]
This might be due to recent changes but we need more information. Did this happen after upgrading to activeadmin 2.5.0?

**Comment by jadamdipak** [comment]
Thanks for reply
I am using activeadmin 1.4.3

**Comment by jadamdipak** [comment]
The weird thing is, It is working fine when I deploy my code via docker with the jenkins but when I deploy directly via mina deploy I face this problem

**Comment by deivid-rodriguez** [comment]
Ah, I see. I'm going to close this, then. If you can still reproduce this issue using the most recent version of activeadmin, please reopen the ticket and we'll try to help!
