### ISSUE TITLE
Customer JS calling ActiveAdmin.modal_dialog no longer working after upgrade

### ISSUE THREAD

**Issue by kernow** [activeadmin/activeadmin#5953]
Hi,

I can't see any docs on how to use `ActiveAdmin.modal_dialog` in custom JS after the upgrading from 2.3.1 to 2.5.0. Looking through the commits I can see the JS has undergone significant changes which would explain the breakage but can't see the new way to use the `modal_dialog` function.

We have a `app/assets/javascripts/active_admin.js` file which is calling `ActiveAdmin.modal_dialog`, this is now raising an `ActiveAdmin is not defined` error.

What is the new way to do this? Our app uses webpacker so I'm happy to switch this JS to webpacker if thats the way to go now, the only sprockets JS we have in our app is some custom active admin code.

Thanks

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this, it does sound related to the JS refactor in preparation for webpacker support.

I'll have a look myself but pinging @sgara in case you have any ideas.

**Comment by sgara** [comment]
I’m pretty sure components are exported at all as I didn’t expect those to be used in client code, sorry about that @kernow.
Webpacker compatible package is not that far from being ready though we would still need to add `export` statements to make this work. 
I’ll check what can be done to mitigate this meanwhile
