### ISSUE TITLE
Default actions in `table_for` for associated resources

### ISSUE THREAD

**Issue by dvkch** [activeadmin/activeadmin#5959]
Hi there and first of all thank you for this amazing tool!

I would like to know how you would suggest adding default actions (view, edit, delete) in `table_for` for an associated collection of resources ? In my case I am displaying a list of `Track`s associated to an `Album`. 

I have found a way to do so by adding a `builder_method` to `IndexTableFor` and mostly everything is okay : 
- `id_column` works and its link redirects to the right page
- `actions` works and all actions are applied to the proper resource 

The only issue I have is: disabling actions at the model level using `actions: all, except: [:destroy]` for instance doesn't work really well :

- If you disable the destroy action for `Album`, associated tracks listed in an album's page will hide the Delete action too
- If you disable the destroy action for `Track`, associated tracks listed in an album's page will still show the Delete action

Here are my stackoverflow question and answer explaining a bit more my process : https://stackoverflow.com/a/59156169/1439489

I've tracked the lines handling default actions to `lib/active_admin/views/index_as_table.rb`, around lines 374 to 386, it seems the issue is with `controller.action_methods.include?` which checks if the action is valid for the current controller, not the controller associated with the resource parameter.

`controller` also seems to be used in `def id_column` to enable/disable the resource link, which means the enable/disable process should break in the same way, even though the generated link itself is valid.

My questions would be : 

1. was it really that smart to use `IndexTableFor` for associated objects?
2. if not, is there another way to easily add actions for associated objects?
3. if yes, is there a way to ask the proper controller for its declared action methods ?

Thanks a lot for considering.

**Comment by kinsbrunner** [comment]
Hi Stanislas,
Have you been able to get any answer about this?
In my case, although actions appear, they are pointing to header's actions instead of child's action. i.e. when clicking Edit; it takes me to Edit the parent and not the child... am I missing something?
Kindly let me know your thoughts.
Regards.
Alejandro.

**Comment by dvkch** [comment]
Hey @kinsbrunner 

I defined a module in my projects : 

```ruby
module ActiveAdminFixResourcesPaths
  extend ActiveSupport::Concern

  # we need at least one method or the module won't exist in rails eyes
  def are_path_fixed
    true
  end

  included do
    # In Admin::Users#show we had an issue causing id_column for resource.artists and resource.playlists to
    # fail because resource_path would return /admin/users/:playlist_id instead of /admin/playlists/:playlist_id
    # for instance. The problem also manifests itself when using `actions`. Curiously this is not an issue in
    # Admin::Albums#show or any other admin controllers. Just Users. And disabling Devise didn't change a thing.
    # This fix is inspired from `auto_link` and https://github.com/activeadmin/activeadmin/issues/279#issuecomment-37366570
    # It works even if its pretty damn weird

    def resource_path(*given_args)
      resource = given_args.first
      config = active_admin_namespace.resource_for(resource.class)
      return unless config

      url_for config.route_instance_path resource, url_options
    end

    def edit_resource_path(*given_args)
      resource = given_args.first
      config = active_admin_namespace.resource_for(resource.class)
      return unless config

      url_for config.route_edit_instance_path resource, url_options
    end
  end
end
```

and in each active admin model definition I add 

```ruby
controller do 
  include ActiveAdminFixResourcesPaths
end
```

This fixes it in every instance of the issue that I had, couldn't see a regression on my end. Hope this helps

**Comment by kinsbrunner** [comment]
> Hey @kinsbrunner
> 
> I defined a module in my projects :
> 
> ```ruby
> module ActiveAdminFixResourcesPaths
>   extend ActiveSupport::Concern
> 
>   # we need at least one method or the module won't exist in rails eyes
>   def are_path_fixed
>     true
>   end
> 
>   included do
>     # In Admin::Users#show we had an issue causing id_column for resource.artists and resource.playlists to
>     # fail because resource_path would return /admin/users/:playlist_id instead of /admin/playlists/:playlist_id
>     # for instance. The problem also manifests itself when using `actions`. Curiously this is not an issue in
>     # Admin::Albums#show or any other admin controllers. Just Users. And disabling Devise didn't change a thing.
>     # This fix is inspired from `auto_link` and https://github.com/activeadmin/activeadmin/issues/279#issuecomment-37366570
>     # It works even if its pretty damn weird
> 
>     def resource_path(*given_args)
>       resource = given_args.first
>       config = active_admin_namespace.resource_for(resource.class)
>       return unless config
> 
>       url_for config.route_instance_path resource, url_options
>     end
> 
>     def edit_resource_path(*given_args)
>       resource = given_args.first
>       config = active_admin_namespace.resource_for(resource.class)
>       return unless config
> 
>       url_for config.route_edit_instance_path resource, url_options
>     end
>   end
> end
> ```
> 
> and in each active admin model definition I add
> 
> ```ruby
> controller do 
>   include ActiveAdminFixResourcesPaths
> end
> ```
> 
> This fixes it in every instance of the issue that I had, couldn't see a regression on my end. Hope this helps

Brilliant, that's the solution for most of the cases. The only exception is when deleting a child object as it takes me to the index of the child list. i.e I have a Family which has Children. When standing on the Show of a specific family, I list the children and click on the delete button attached to one of them; the result is that it gets deleted but it redirects me to the Index of the Children list. My expectation would simply be to get it deleted and refresh the current page.... any idea?

**Comment by dvkch** [comment]
I don’t have this issue since either children objects (photos of a photo album for instance) don’t have their own controller, in which case I have overloaded the « destroy » controller method for that object to redirect to the parent of the destroyed object, or the objects have their own semantic meaning distinct from their association (eg a business associated to a person) and I’ll only display the show and edit actions in the relationships table, not the destroy option.

**Comment by kinsbrunner** [comment]
Ok, I will look into it.

Also, Let's say I have the Family and that each family has Donations. I'd expect to have a button for creating a Donation on the Donations panel that I have on my Family show page. Is this something that comes out of the box somehow? Or how would you suggest me to proceed?

**Comment by dvkch** [comment]
I’m sorry I won’t have the time to help you much further, I’ve given you all the information I had already available on hand, and the documentation of ActiveAdmin is already pretty complete for creating you own custom actions.
