### ISSUE TITLE
Update issue template

### ISSUE THREAD

**Issue by Y0hy0h** [activeadmin/activeadmin#5963]
Opening the [issue template file](https://github.com/activeadmin/activeadmin/blob/master/.github/ISSUE_TEMPLATE.md) reveals a warning that it uses a legacy format.

GitHub now offers a settings page wizard for creating issue templates (which are stored in a folder, not in a single Markdown file as currently). See the instructions for [configuring issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#creating-issue-templates).

**Comment by deivid-rodriguez** [comment]
This will actually be fixed by #5968.
