### ISSUE TITLE
Label of date_select input is missing

### ISSUE THREAD

**Issue by kaneru** [activeadmin/activeadmin#5969]
### Expected behavior

Label of `date_select` input should be presented in new and edit views.

### Actual behavior

Label of `date_select` input is missing.

### How to reproduce

Create a model with a field of `date` type, e.g. `Equipment`:

```bash
rails g model Equipment title purchase_year:date
```

Register a model by running:

```bash
rails g active_admin:resource Equipment
```

```ruby
# app/admin/equipment.rb

ActiveAdmin.register Equipment do
  permit_params :title, :purchase_year
end
```

Then I go to `<site_name>/admin/equipment/new` page and see that label of the `date_select` input is missing.

<img width="473" alt="Снимок экрана 2019-12-11 в 09 50 25" src="https://user-images.githubusercontent.com/17761708/70582009-6cd79e00-1bfc-11ea-95ae-697ecd8369a9.png">

I also tried to add label to the input explicitly:

```ruby
# app/admin/equipment.rb

ActiveAdmin.register Equipment do
  permit_params :title, :purchase_year

  form do |f|
    f.semantic_errors *f.object.errors.keys
    f.inputs do
      f.input :title
      f.input :purchase_year, label: I18n.t('structure.purchase_year')
    end
    f.actions
  end
end
```

But label is still missing.

**Comment by boniattirodrigo** [comment]
Hey @kaneru. I reproduced your error in my machine and it worked as expected I can see the label `Purchase year` beside the date select input.

**Comment by kaneru** [comment]
Hello, @boniattirodrigo! Thank you for responding. I am using `ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin19]` and `Rails 6.0.0`.

**Comment by kaneru** [comment]
Looks like that is Safari's fault. Works as expected in Google Chrome and Firefox. But label and `date_select` are positioned on different lines.

<img width="684" alt="Снимок экрана 2019-12-25 в 14 59 03" src="https://user-images.githubusercontent.com/17761708/71434534-5109e700-2728-11ea-86ee-4f8bf2e0dd28.png">

**Comment by AFlowOfCode** [comment]
I am also having this issue, with both ```date_select``` as well as ```date_field```. On my end the formatting is broken, the input shows up on the left where the missing label should be. Firefox & Chrome look identical. 

```date_select```:

![date_select](https://user-images.githubusercontent.com/14116237/71939532-e022f000-3167-11ea-8669-927a7f68553f.png)

```date_field```:

![date_field](https://user-images.githubusercontent.com/14116237/71939648-4b6cc200-3168-11ea-9388-5ff333220487.png)

This is what it looks like if I add a label as follows.
```
f.label :appointment_date
f.date_field :appointment_date
```

![date_field_label](https://user-images.githubusercontent.com/14116237/71939815-bf0ecf00-3168-11ea-8f2c-5610d891e23e.png)

Activeadmin 2.6.0, ruby 2.5.7p206, rails 6.0.2.

**Comment by AFlowOfCode** [comment]
I solved this doing the following:
```
li do
    f.label :appointment_date
    f.date_field :appointment_date
end
```
And in ```assets/stylesheets/active_admin.scss```
```
form input[type=date] {
  width: calc(80% - 22px);
}
```

**Comment by davitapajos-cm42** [comment]
Hey! This would solve problem to safari of hidden label using "f.input"

```css
form fieldset legend {
  overflow: auto;
}
```

**Comment by javierjulio** [comment]
There is a PR ready for this. Thank you.
