### ISSUE TITLE
how to activate sidebar in member_action

### ISSUE THREAD

**Issue by MathieuDerelle** [activeadmin/activeadmin#5973]
content is written directly into a 
`#active_admin_content.without_sidebar #main_content_wrapper .main_content`
but sidebar is a totally sibling of `#main_content_wrapper` 
(and requires no CSS class `.without_sidebar` on `#active_admin_content`

using `sidebar` as shown https://activeadmin.info/7-sidebars.html in `member_action` does not work
```
sidebar :help do
  "Need help? Email us at help@example.com"
end
```

it raises 
``NoMethodError (undefined method `sidebar' for #<Admin::UsersController:0x007fc300d701e8>)``

and using it in a `.arb` partial raises
``undefined method `sidebar' for :Arbre::Context``

how to ?

**Comment by antonintouron** [comment]
Why you want to use sidebar in a member_action ?
You want to run pop up if you click in an button ? if that's it, this ticket is not acceptable and you must make a post on stackoverflow (https://stackoverflow.com/).

I advise you to use javascript for run custom pop up.

**Comment by MathieuDerelle** [comment]
I want to add a sidebar with my content in a `member_action`

The doc explicitly states that : https://activeadmin.info/7-sidebars.html
> Sidebars allow you to put whatever content you want on the side the page.

and states that you can do it in Arbre
> You can also use Arbre to define HTML content.

but it does not work
