### ISSUE TITLE
You are not authorized to perform this action. (after upgrade to 2.6.0?)

### ISSUE THREAD

**Issue by gingerlime** [activeadmin/activeadmin#5991]
### Did you find a bug?

We notice occasional flash messages: "You are not authorized to perform this action". Things seem to work as expected, but the message appears. I'm still not entirely clear how to reproduce it. It seems intermittent.

![Screenshot 2019-12-25 at 11 52 25](https://user-images.githubusercontent.com/524274/71432554-0dee4a80-270d-11ea-9b1d-f47fcd018979.png)

We recently upgraded from 2.5.0 to 2.6.0, so maybe it's relayed? we didn't notice it before.

We're using Rails 5.2 with ruby 2.5.3 and use CanCanCan for authorization.

### Expected behavior

No flash message?

### Actual behavior

Flash message appears

### How to reproduce

As I mentioned, it's intermittent, so hard to reproduce unfortunately. I'll try to see if I can figure out under which condition it happens. I experienced it once, and my colleague once so far.

**Comment by mbiang** [comment]
This appears to be the result of AA incorrectly handling requests with the request.format = "*/*'".    This occurs when the browser sends a request with the header "Accept: */*".

This method [def restrict_format_access!](https://github.com/activeadmin/activeadmin/blob/b45b1fb05af9a7f6c5e2be94f61cf4a5f60ff3bb/lib/active_admin/resource_controller.rb#L56) doesn't handle request.format = "*/*'

I've added the following monkeypatch which solves the problem, but may not be the best resolution.


```
module ActiveAdmin

  class ResourceController < BaseController

    def restrict_format_access!

      unless request.format.html? || request.format == '*/*'
        presenter = active_admin_config.get_page_presenter(:index)
        download_formats = (presenter || {}).fetch(:download_links, active_admin_config.namespace.download_links)

        unless build_download_formats(download_formats).include?(request.format.symbol)
          raise ActiveAdmin::AccessDenied.new(current_active_admin_user, :index)
        end
      end
    end

  end

end
```

**Comment by gingerlime** [comment]
Thank you. I don't remember seeing this issue recently (reported end of 2019, so it's quite a while).

**Comment by vidurpunj-kiwi** [comment]
after adding code by @mbiang its working fine, No warning messages.
