### ISSUE TITLE
Resources in custom load paths are not getting loaded

### ISSUE THREAD

**Issue by awaismbajwa** [activeadmin/activeadmin#5995]
# Expected behaviour

Active admin should load resources defined in the specified custom load paths.
`ActiveAdmin.setup do |config|`
`  config.load_paths.unshift('gems/ruby-2.4.5/bundler/gems/<some-gem>/admins')`
`end`

### Actual behaviour

Resources specified in the custom load path are not loaded. When those resources are accessed 
error is raised

> NameError: uninitialised constant Admin::ExampleController

**Comment by tf** [comment]
To me it looks like [this commit](https://github.com/activeadmin/activeadmin/commit/2459474c6868aaab9b417fb14bd73345f6714f3d) added an initializer which sets the load path. Later, [this commit](https://github.com/activeadmin/activeadmin/commit/017bc8098db3d7e18b88a49f732ce57268bec41a) simplified this initializer to call `ActiveAdmin::Application.setting :load_paths` directly. In our case this initializer runs after the `active_admin.rb` initializer in the main app and resets the load path. If I change the above code to add the load path after other initializers have run, the correct admin files are loaded again:

```ruby
# my_app/config/initializers/active_admin.rb
Rails.application.config.after_initialize do
  ActiveAdmin.application.load_paths.unshift(Pageflow.active_admin_load_path)
end

ActiveAdmin.setup do |config|
  ...
end
```

**Comment by awaismbajwa** [comment]
From my understanding I think it is caused by a bit complicated architecture of [ActiveAdmin::Application](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/application.rb), [ActiveAdmin::ApplicationSettings](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/application_settings.rb) and [ActiveAdmin::SettingsNode](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/settings_node.rb).

load_paths are registered to Application through SettingsNode [register method](https://github.com/activeadmin/activeadmin/blob/9da88933d40ec29eaef3091054ef71ecb760c15f/lib/active_admin/settings_node.rb#L13). SettingsNode creates a class attribute 'load_paths' using class_attribute meta programming method.

From class_attribute documentation, it is mentioned that 
> Appending in child changes both parent and child because it is the same object:

So there are some differences between the use of setters and unshift in this scenario which I think are causing the load_paths to get reset.

In my case I tried setting custom load_paths using the setter like this
`  ActiveAdmin.application.load_paths += [Pageflow.active_admin_load_path]
`
 Upon using this approach initializer in activeadmin Engine does not effect custom load_paths

**Comment by awaismbajwa** [comment]
But still assigning custom load_path through setter is not solving problem completely.
The issue could arise because this [line of code](https://github.com/activeadmin/activeadmin/blob/9da88933d40ec29eaef3091054ef71ecb760c15f/lib/active_admin/engine.rb#L5) in ActiveAdmin::Engine is getting ignored.
This causes issue for example when working with the dummy app in test environment in that case resources defined in dummy app won't get loaded.
