### ISSUE TITLE
Wrong URL generated by ActiveAdmin for redirect after record creation

### ISSUE THREAD

**Issue by iduuck** [activeadmin/activeadmin#6001]
### Did you find a bug?

I am currently experiencing the following issue with the latest 3 ActiveAdmin versions:

```
undefined method `products_url' for #<Admin::ProductsController:0x00007fad15a22e88>
```

### Expected behavior

I expect the URL to be correctly generated and that `admin_products_url` is used here.

### Actual behavior

I am seeing that ActiveAdmin is using the `product_url` which isn't namespaced with `admin`.

### How to reproduce

I am not able to give out the source code of the application. But I am able to invite someone to review the bug in the private repository.

**Comment by iDuuck** [comment]
One more observation was, that this is only happening with the "Product" model.
