### ISSUE TITLE
Formtastic is no longer being updated and throws copious deprecation warnings in Ruby 2.7

### ISSUE THREAD

**Issue by carltonsmith** [activeadmin/activeadmin#6006]
**Expected behavior**
ActiveAdmin would not depend on gems that are no longer in use or updated, or would fork them to someplace where they can be updated
 
**Actual behavior**
ActiveAdmin depends on Formtastic, which hasn't been updated since 2017 and for which numerous issues exist.

**What actually happens?**
Currently, in Ruby 2.7.0 formtastic is throwing hundreds, if not thousands of deprecation warnings every time I run rspec, making it impossible to look back through the trace and get meaningful results.

### How to reproduce
Upgrade to Ruby 2.7.0 and run rspec

**Comment by dmitry** [comment]
Would be great if the new major version of activeadmin changes formtastic to https://github.com/heartcombo/simple_form.

**Comment by javierjulio** [comment]
Formtastic v4 was recently released which should address the Ruby 2.7 warnings.
