### ISSUE TITLE
Dealing with name spaced models?

### ISSUE THREAD

**Issue by Andrew-Max** [activeadmin/activeadmin#6008]
I have a model which is part of an STI scheme and is namespaced under a base class: `Action::VirusInjection`

When I try to save this model from an edit form I get the error: 
`param is missing or the value is empty: action_virus_injection 

Any idea on how I can allow this form to save a namespaced model? Sorry for the beginner question.

**Comment by asadakbar** [comment]
@Andrew-Max Did you find a solution to this?
