### ISSUE TITLE
Can't load active admin after switching to sprocket 4

### ISSUE THREAD

**Issue by nicolas-brousse** [activeadmin/activeadmin#6009]
### Did you find a bug?

We migrate a Rails application that use `activeadmin`, from Rails 5.2 to 6.0 last week.  
We notice that we was not able to load the administration anymore.

### Expected behavior

Having `activeadmin` load correctly.

### Actual behavior

We cannot load our administration anymore, after having migration to Rails 6.0 (sprocket 4).  
The weird part was that no exception was show, it was `public/500.html` that was loaded. And we didn't found any traces in logs (`logs/development.log`).

To dig into the issue an have a idea of what happened, we decide to edit the installed `activeadmin` gem, used by the application. So we edited `views/page/index.html.arb` and we put a `binding.irb` at the beginning. And we've got the following.

```
[3] pry(#<Arbre::Context>)> insert_tag active_admin_application.view_factory["page"]
Sprockets::ArgumentError: link_tree argument must be a directory
from /Users/b/Sites/website/app/assets/config/manifest.js:1
```

So we edited the `app/assets/config/manifest.js` file, and it works no.

But seems curious that this exception was not printed directly in our logs.

### How to reproduce

I guess, the best way to reproduce the bug, is to having a Rails 6 application, or a Rails application with sprocket 4+ (if I'm not wrong the `manifest.js` was implemented with v4).  
Then put a wrong configuration in `manifest.js` file.

If you need it, I'll try to create a sample app.

**Comment by mrublya** [comment]
if anyone has a similar problem

then I solved it by adding folder images to the app/assets
or by deleting the line, but it may disturb something, I don’t know what exactly

**Comment by deivid-rodriguez** [comment]
> If you need it, I'll try to create a sample app.

Yes, please!
