### ISSUE TITLE
Extra array / enumerable object output in rows and columns

### ISSUE THREAD

**Issue by AFlowOfCode** [activeadmin/activeadmin#6014]
### Did you find a bug?

When enumerating an object for display in a row or column, the entire object itself then shows up in the display.

### Expected behavior

The display behavior done during the enumeration should be the only visible result.

### Actual behavior

Instead of showing eg the specified values enumerated from an array, you get the values as you intended and then also the entire array itself on display.

### How to reproduce

Add an array datatype column to a model if needed:
`add_column :cards, :amounts, :integer, array: true, default: []`

In that table's activeadmin resource `cards.rb`:
```
index do
  column :amounts do |c|
    c.amounts.each do |a|
      para a
    end
  end
end
```
If your amounts column contained [10, 30] this is what will display:
```
10
30
10, 30
```
That's unexpected because if I want the array itself to show up as is, I'd just leave it at `column :amounts`. If you have a conditional for whether `a` displays or not, your whole array is then exposed at the end anyway. 

This is easily worked around by returning `nil` after the `.each` block so the block doesn't get returned. But it might not be immediately obvious to everyone why the object is showing up uninvited. I've seen some weird hacks and I can't imagine a reason why you'd ever want it to do this. So I think it's a little bug 🦟

Searching through old issues I saw this referenced in #4967

**Comment by javierjulio** [comment]
I'm not sure if this is something that can be fixed but if so I would accept a PR for it. Maybe to do with Arbre. Either way the `nil` at the end makes sense.
