### ISSUE TITLE
Datalist filters

### ISSUE THREAD

**Issue by JSRossiter** [activeadmin/activeadmin#6079]
### Did you find a bug?

There doesn't seem to be any way to use a [datalist input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist) as a filter and they would be perfectly suited for this. The error is

```
undefined method `map' for #<Proc:0x00007fe58fcd3bc0>
```

which comes from `raw_collection.map { |o| [send_or_call(label_method, o), send_or_call(value_method, o)] }` in https://github.com/justinfrench/formtastic/blob/f94423144eee14ccc03a64267fcafd583d3cdf85/lib/formtastic/inputs/base/collections.rb#L58

But I think the fix is creating a datalist_input.rb similar to select_input.rb in lib/active_admin/inputs/filters/

I was able to create a datalist input by passing the collection in without using a proc, however this only works in a development environment as that code is executed during application load.

### Expected behavior

Be able to use the datalist input as a filter

### How to reproduce

Add this filter to an `ActiveAdmin.register` block for a model that belongs to a User, or try to replace any similar select filter.
```
filter :user_id_equals, label: 'User ID', as: :datalist, collection: -> { User.all }
```

I'd be willing to attempt a PR for this if it's something that you're open to working on. Thanks.

**Comment by javierjulio** [comment]
Thank you for opening a PR for this. Some updates for it are needed.
