### ISSUE TITLE
Sub sub menus don't work as listed in the documentation

### ISSUE THREAD

**Issue by Andrew-Max** [activeadmin/activeadmin#6130]
### Did you find a bug?
Yes

### Expected behavior
The docs give this example of how to  do sub nested menus:
```
ActiveAdmin.register Post do
  menu parent: ["Admin", "Blog"]
end
```

Should produce a nested menu in a nested menu

### Actual behavior
This throws: `TypeError (Array isn't supported as a Menu ID):`
### How to reproduce

ruby '2.6.3'
gem 'rails', '~> 6.0.1'

Create an app and use the example provided above directly from the documentation.

**Comment by deivid-rodriguez** [comment]
Hi @Andrew-Max, this is a new feature and we haven't yet released it. Unfortunately the documentation site gets autodeployed with every push to master, so we get this "unsyncronized situations" once in a while.

You can try the feature by specifying `gem "activeadmin", github: "activeadmin/activeadmin"` in your `Gemfile`.

**Comment by Andrew-Max** [comment]
@deivid-rodriguez gotcha, thanks. If there is anything I can do in terms of helping to get this merged I could try to give a hand. Code review? testing ?  Something else?

**Comment by deivid-rodriguez** [comment]
It's merged, actually! You can test it by speciyfing

```
gem "activeadmin", github: "activeadmin/activeadmin"
```

in your Gemfile, and running `bundle update activeadmin`.

I'll release a new version anyways very soon.
