### ISSUE TITLE
Nested namespaces

### ISSUE THREAD

**Issue by bradyhigginbotham** [activeadmin/activeadmin#615]
I need to have a nested namespace:

/admin/namespace/resource.rb*

I'd like to know how I could create this through ruby ("rails g active_admin:resource namespace/Resource" didn't work)

and any additions to routes.rb? possibly like the following:

``` ruby
namespace "admin" do
  namespace "namespace" do
    resources :resources
  end
end
```

Thanks for any suggestions!
- just an example

**Comment by snowmoonsoftware** [comment]
+1 struggling with this myself especially with the menus. See issue #3960

**Comment by davidwparker** [comment]
What's the status on this?

I'd like to have dynamic active_admin, based on the parent's namespace in routes.

config/routes.rb
```
resources :marketplaces do
    ActiveAdmin.routes(self)
```

So I can go to `/marketplaces/:marketplace_id/admin`

config/initializers/active_admin.rb
```
config.namespace :admin do |admin|
    admin.site_title = "Admin"
    admin.authentication_method = :authenticate_admin!
  end
```

app/marketplaces/admin/dashboard.rb
```
  ActiveAdmin.register_page "Dashboard", namespace: :admin do
    menu priority: 1, label: proc{ I18n.t("active_admin.dashboard") }
...
```

Right now, I get the error:
```
uninitialized constant Marketplaces::Admin
```

When I try to go to http://localhost:3000/marketplaces/1/admin

Is this possible? Thanks!
