### ISSUE TITLE
Create Form For model with `::` colon in name

### ISSUE THREAD

**Issue by Andrew-Max** [activeadmin/activeadmin#6156]
### Did you find a bug?

I'm using an STI setup so I have models like

```ruby
class Action

end
```

```ruby
class Action::SomeAction < Action

end
```

I Cannot figure out any way to set the model to one of the sub type models in a custom form

So this works
```ruby
  form do |f|
    tabs do
      tab 'Experiment Data' do
        f.inputs do
           f.has_many(:action, allow_destroy: true, new_record: true) do |a|
             a.input :type, label: 'Type', as: :select, collection: User.all.map{|u| u.first_name}
          end
        end
      end

```

But I can't figure out how to something like this: 

```ruby
  form do |f|
    tabs do
      tab 'Experiment Data' do
        f.inputs do
           f.has_many("Action::SomeAction", allow_destroy: true, new_record: true) do |a|
             a.input :type, label: 'Type', as: :select, collection: User.all.map{|u| u.first_name}
          end
        end
      end
```

Is anybody aware of a way to do this?

### Expected behavior

Honestly not sure, but maybe should be able to manually set the underlying model for a form

### Actual behavior
Cannot get this to work

### How to reproduce
Check code in description

**Comment by abdelrahmanabdelnabi** [comment]
I think you should use the relation name not the class name in `f.has_many`. i.e if your` Experiment` model has a line that says `has_many :actions, class_name: 'Action::SomeAction'` Then you should use f.has_many like so: `f.has_many(:actions)`
