### ISSUE TITLE
Strange behaviour with nested STI resources

### ISSUE THREAD

**Issue by jco137** [activeadmin/activeadmin#6192]
### Did you find a bug?

I have theses models : 

class Game < ApplicationRecord
	has_many :titles, :as => :titleable
	has_many :descriptions, :as => :textable
	has_many :reviews, :as => :textable
	accepts_nested_attributes_for :titles, allow_destroy: true
	accepts_nested_attributes_for :descriptions, allow_destroy: true
	accepts_nested_attributes_for :reviews, allow_destroy: true
end

class Text < ApplicationRecord
	belongs_to :textable, polymorphic: true, touch: true
end

class Description < Text
end

class Review < Description
end

I build an activeadmin resource for Game and i display nested resources but table_for game.descriptions display sometimes also the reviews and the panel table_for game.reviews display only the review.

I have the same problem inside a form with f.has_many

The first time it's ok and after it's bad (maybe the cache)

in the console, the first time the selects are 
SELECT "texts".* FROM "texts" WHERE "texts"."type" = ? AND "texts"."textable_id" = ? AND "texts"."textable_type" = ?  [["type", "Description"], ["textable_id", 1], ["textable_type", "Game"]]

SELECT "texts".* FROM "texts" WHERE "texts"."type" = ? AND "texts"."textable_id" = ? AND "texts"."textable_type" = ?  [["type", "Review"], ["textable_id", 1], ["textable_type", "Game"]]

and the next times : 
SELECT "texts".* FROM "texts" WHERE "texts"."type" IN (?, ?) AND "texts"."textable_id" = ? AND "texts"."textable_type" = ?  [["type", "Description"], ["type", "Review"], ["textable_id", 1], ["textable_type", "Game"]]

SELECT "texts".* FROM "texts" WHERE "texts"."type" = ? AND "texts"."textable_id" = ? AND "texts"."textable_type" = ?  [["type", "Review"], ["textable_id", 1], ["textable_type", "Game"]]

**Comment by asadakbar** [comment]
So I've been hunting for a while to a similar problem and I think I found a temporary solution. I also have a similar setup, where my fruit class is an STI class

````
class Fruit < ApplicationRecord
  belongs_to :store
end
class Orange < Fruit; end
class Apple < Fruit; end
class Peach < Fruit; end
````
and the key being that ALL of these classes are defined in a single file.

Another file has this
````
class OrangeStore < ApplicationRecord
  has_many :oranges
end
````

Well, in my AA orange_stores.rb file I have

`ActiveAdmin.register OrangeStore do; end`

and whenever I try to load orangestore.oranges, AA blows up with

`*** NameError Exception: uninitialized constant OrangeStore::Orange`

The temporary fix was to pull out the `class Orange < Fruit; end` into its own `orange.rb` file, at which point the association seemed to load properly. Now keep in mind, Rails was able to properly load the Orange class in the console just fine, but AA had trouble finding it. It seems to be using the filesystem to map the associations, and I have yet to find how to define where it should look for them.

I know its been a while, but were you able to find a solution?
