### ISSUE TITLE
ActiveAdmin got 404 Not Found in Nginx Ubuntu

### ISSUE THREAD

**Issue by onetechlabs** [activeadmin/activeadmin#6199]
hello , my activeadmin in route /admin and other routes except / got error 404 how to fix it ? thanks for help .

**Comment by antonintouron** [comment]
@onetechlabs Hello, I don't think this is a problem on the active admin side. It is most likely due to your server configuration.

- You use docker with nginx (base ubuntu) for web server ?
- You have custom url rewrite ?
Thanks

**Comment by deivid-rodriguez** [comment]
I agree with @antonintouron that this doesn't seem like an issue in activeadmin, and I also appreciate that he's providing some support. I'm closing this but feel free to answer the questions to get some help, @onetechlabs.
