### ISSUE TITLE
Should the sprockets dependency be removed?

### ISSUE THREAD

**Issue by sjieg** [activeadmin/activeadmin#6201]
**Background**

Hey guys, first of all let me say I appreciate all te amazing work on this gem! It's a great addition to the Rails toolset.
Recently, like many of us, I'm looking into moving over to Webpacker and with #5855 you guys now also support it. But when switching,  Sprockets is still installed due to the dependency in the Gemspec. It's not major, but when a Gem is not used, I'd rather not have it installed at all :)

**Reproduction**

1. Set the `config.use_webpacker` config
2. Run `rails g active_admin:webpacker`
3. Remove `gem 'sprockets'` from your project Gemfile
4. Run `bundle update`

**Actual**

Sprockets 4 is installed and added to your Gemfile.lock

**Expected**

Sprockets to not be used at all in the rails project.

**Cause**

In the Gemspec file there is still a dependency to Sprockets: https://github.com/activeadmin/activeadmin/blob/master/activeadmin.gemspec
```
  s.add_dependency 'sprockets', '>= 3.0', '< 4.1'
```

**Possible solution**

Could this dependency be removed? Should it be removed?
The dependency kind of depends on the config setting, if you installed AA normally, then it's dependent on Sprockets, but with the `:webpacker` installation, it's dependent on Webpacker.

Should the generator maybe add the required gem to the Gemfile?
Or should there be 2 gems: `activeadmin` and `activeadmin_webpacker`
Or should a AA version 3 be release dropping support for Sprockets, having a dependency on Webpacker?

_Just braindumping some possible solutions, but I don't have enough knowledge about the whole of AA to know if they're valid options._

**Comment by deivid-rodriguez** [comment]
Thanks for the kind words @sjieg :purple_heart:

I'm happy to explore removing the dependency in the future but note that [`rails` still depends on it](https://rubygems.org/gems/rails/versions/6.0.2.2/dependencies), you even if we removed it, you'll still get it installed and added to the lock file.

**Comment by sjieg** [comment]
Ah, fair point! Honestly I just didn't dig deep enough in my lock file to see the link from `rails-sprockets` to `sprockets`. 👎 

In that case this ticket would even be lower priority. Still, it's probably not a bad idea to not have a dependency on something you're not necessarily dependent on :)

**Comment by deivid-rodriguez** [comment]
Yeah, I'll still leave it open for future evaluation. Thanks @sjieg!
