### ISSUE TITLE
ActiveAdmin crashes on start if there's no app/assets directory

### ISSUE THREAD

**Issue by Ecco** [activeadmin/activeadmin#6206]
### Problem

1. Create a new Rails 6 app using Webpacker. For instance, `rails new FooBar --skip-sprockets --webpack=vue`
2. Remove the `app/assets` directory
3. Run `rails server`. It works!
4. Add activeadmin to the Gemfile and run `bundle install`
5. (Optional) Edit `config/initializers/active_admin.rb` to use webpack
5. Run `rails server`. It crashes with an error.

### Expected behavior

It shouldn't crash. The "app/assets" directory only makes sense if the app uses sprockets, and ActiveAdmin supports Webpacker as an alternative :)

### More info

Here's the error message
```
/Users/ecco/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:105:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server
```

**Comment by Ecco** [comment]
This might be related to #6201.

**Comment by Ecco** [comment]
#### My investigation

1. This is due to unconditionally [requiring sassc-rails](https://github.com/activeadmin/activeadmin/blob/3756c83ab720b0474bb73c477317d55b7948c866/lib/active_admin.rb#L11), which in turn will [require `sprockets/railtie`](https://github.com/sass/sassc-rails/blob/8d0462d54b5b5dd84cb1df31823c3afaebb64534/lib/sassc/rails/railtie.rb#L4).
2. Even if this gem isn't loaded, the engine references `config.assets` unconditionnaly too [here](https://github.com/activeadmin/activeadmin/blob/3756c83ab720b0474bb73c477317d55b7948c866/lib/active_admin/engine.rb#L10) and [there](https://github.com/activeadmin/activeadmin/blob/3756c83ab720b0474bb73c477317d55b7948c866/lib/active_admin/engine.rb#L13).

Commenting those 3 lines fixes the problem, but of course isn't the right solution 😄 

#### Note regarding point #1025 

One could argue that this is a bug in sass/sassc-rails. This might be the case, but what's sure is that ActiveAdmin also does *not* need any sass-related code when using Webpack, since sass compilation would then happen in JS world.

**Comment by hcatlin** [comment]
Yeah, this is affecting me! And hell, I'm a core-team member on sassc-rails, but gosh darnnet I'm using the node-sass version for this and don't need any of that sprockets business.

**Comment by boardfish** [comment]
For my use case, I've torn out the Asset Pipeline completely and am using Webpacker for everything from images to CSS and JS. This bug is stopping me from using ActiveAdmin as it currently stands. @hcatlin's fix looks good and seems well-tested.

**Comment by deivid-rodriguez** [comment]
I'll pick up that PR for review next :+1:.

**Comment by boardfish** [comment]
It's pretty stale so it'll likely need a rebase. I really appreciate the quick response, thank you!

**Comment by Ecco** [comment]
> This bug is stopping me from using ActiveAdmin as it currently stands

 Actually, until this bug is fixed, a simple workaround is to just keep an empty `app/assets/config/manifest.json` file.

**Comment by hcatlin** [comment]
@boardfish @deivid-rodriguez I rebased it for you! <3
