### ISSUE TITLE
The problem with nested forms

### ISSUE THREAD

**Issue by afuno** [activeadmin/activeadmin#6208]
Rails 6.0.2.2, ActiveAdmin 2.7.0

---

It seems that there is a problem when, for example, a triple nested form. More details are described here: https://stackoverflow.com/questions/61573577/why-the-new-data-are-not-saved-in-the-nested-form

You can immediately focus on the second addition.

**Comment by afuno** [comment]
@elia Can anyone answer me on this? I really don't understand how to build such a form in ActiveAdmin. This is not in the documentation.

**Comment by elia** [comment]
@afuno this doesn't look much like an error specific to ActiveAdmin, but rather a nested-attribute  edge case… have you tried looking for articles about nested attributes? I've found this one for example that tackle many complex cases https://www.sitepoint.com/complex-rails-forms-with-nested-attributes/.

I would suggest closing this issue and keeping the question on StackOverflow, which seems more appropriate 👍

**Comment by afuno** [comment]
@elia Thanks you. You made me read the documentation again. I will write a solution here, as well as duplicate it on StackOverflow.

The solution is simple - need to use `inverse_of`. [Documentation](https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html#module-ActiveRecord::NestedAttributes::ClassMethods-label-Validating+the+presence+of+a+parent+model).

And everything will start to work as intended.

**Comment by elia** [comment]
That’s great! Thanks for sharing the solution! 👍
