### ISSUE TITLE
When `belongs_to` record not set, record create/update fails silently

### ISSUE THREAD

**Issue by vfonic** [activeadmin/activeadmin#6217]
I'm not sure about this one. :)

What I was building was:
A nested resource that should automatically be assigned to a parent (existing) record. (`has_many` => `belongs_to`)
I clicked on "New" (on child), filled out the form (that DOES NOT have parent in the form), clicked "Create" and...was redirected to the form, but there were no visible error messages.

This is "obvious", because I don't have parent in the form, but it's also confusing, because the form block as `f.semantic_errors`. I couldn't figure out what could be wrong.

Should this be something that should somehow be addressed?
Since I also use Pundit for authorization I was thinking maybe something went wrong there. Basically, I had no feedback to what was wrong: both logs and UI were not showing any issues: no unpermitted params, no validation errors, no permission errors.
Perhaps a simple `flash[:error]` would solve the issue?

`flash[:error] = 'Validation errors prevented record from saving'` (and then the actual errors would stay inline like now)

What do you think?

**Comment by vfonic** [comment]
Here's what I found out.

I had my form defined like this:

```ruby
  form do |f|
    f.semantic_errors
    f.inputs :question, :answer
    f.actions
  end
```

This caused the silent failure, because the above should be changed to:

```diff
  form do |f|
-    f.semantic_errors
+    f.semantic_errors *f.object.errors.keys
    f.inputs :question, :answer
    f.actions
  end
```

How can we prevent this from happening?

I guess there are two solutions:
We could check the number of arguments passed. If number is zero we can:
1) Raise error
2) Provide validation errors (I'd guess that `f` object would be able to access `f.object.errors.keys` within `semantic_errors` method)

I don't know if someone is using `#semantic_errors` in any different way but: `f.semantic_errors *f.object.errors.keys`. Perhaps we could just do the 2) and have the dsl a tiny bit smaller?

**Comment by javierjulio** [comment]
This seems like user error. It's documented that it has to have the argument.
