### ISSUE TITLE
Make the sassc-rails dependency optional

### ISSUE THREAD

**Issue by Ecco** [activeadmin/activeadmin#6222]
When using webpacker, the `sassc-rails` gem is pulled in even though it is never going to be used.

This is sort of similar to #6201, except that sassc-rails is *not* pulled by Rails already, so it's more visible.

**Comment by alex-hall** [comment]
Any interest in this @gregbell ? I created a fork of this repo and simply made the change: 

`  s.add_dependency 'sassc-rails', '~> 2.1'` =>   `s.add_development_dependency 'sassc-rails', '~> 2.1'`

The same number of tests failed in the before and after case (not sure why there are tests failing on master, perhaps I missed something in the CONTRIBUTING.md doc). 

Additionally, I was able to create the tmp rails server and play around with ActiveAdmin being a development dependency.

**Comment by alex-hall** [comment]
FYI I Have a PR open here with passing CI: #6225

**Comment by alex-hall** [comment]
CC: @deivid-rodriguez

**Comment by alex-hall** [comment]
Hmm.. on further inspection, it looks like sassc-rails IS a dependency rails pulls in. Here is the gemfile.lock from rails 6.0: 

```
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
```

**Comment by Ecco** [comment]
@alex-hall Hmm, I beg to disagree :) `sassc-rails` is indeed a dependency of sass-rails, but AFAIK rails doesn't pull `sass-rails` in.

Would you mind sharing a bigger part of your Gemfile.lock maybe?

**Comment by Ecco** [comment]
FWIW, on rails 6.0.3, `rails new foobar -S` generates a `Gemfile.lock` w/o any mention of sass whatsoever.

**Comment by alex-hall** [comment]
Gotcha @Ecco , I was referring to a vanilla rails install. The gemfile.lock I was referring to was the actual rails repo itself. I did notice beforehand that skipping sprockets leaves that dependency out of the resulting gemfile entry: 

From Rails: 
```
      def assets_gemfile_entry
        return [] if options[:skip_sprockets]

        GemfileEntry.version("sass-rails", ">= 6", "Use SCSS for stylesheets")
      end
```

The hurdle in ActiveAdmin is going to be making [this require](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin.rb#L11) more dynamic : 
```
require 'inherited_resources'
require 'jquery-rails'
require 'sassc-rails'
require 'arbre'
```
