### ISSUE TITLE
Route names get clobbered sometimes

### ISSUE THREAD

**Issue by buffpojken** [activeadmin/activeadmin#6233]
### Did you find a bug?

At perhaps 1 in 10 application starts, application loading fails with an error similar to: 
```
! Unable to load application: ArgumentError: Invalid route name: 'admin/contact_agentsntact_agents'
Invalid route name: 'admin/contact_agentsntact_agents'
```

or 

```
! Unable to load application: ArgumentError: Invalid route name: 'admin/item_groups_item_groups'
Invalid route name: 'admin/item_groups_item_groups'
```

ContactAgent and ItemGroup is a model, and registered resource with ActiveAdmin. 

### Expected behavior

Application should start without issue.

### Actual behavior

Application fails to load.

### How to reproduce

I can't reliably reproduce, but the setup below will trigger issue at roughly 1 out of 10 application starts. My guess is that it's related to resource menu nesting, since I have not seen the issue with any resource routes that's not nested under a parent menu item - but this is a guess, not fact. 

ContactAgent-resource: 
```
ActiveAdmin.register ContactAgent do
  menu parent: 'Admin'

  permit_params :name, :image, :section_tag, :zendesk_id, agent_topic_ids: []

  form do |f|
    f.inputs do
      f.input  :name
      f.input  :zendesk_id
      f.input :image, as: :file

      f.input :section_tag, as: :select, collection: {'Boende' => 'house', 'Kund' => 'customer'}

#      f.input :mungo, as: :select, collection: ItemGroup.as_select_options

      f.input :agent_topics, :member_label => :label, as: :check_boxes
    end
    f.actions
  end

end
```

Routes file:
```
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :skip => [:login]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resource :public 

  resource :authentication, only: [] do 
    post :verify
  end

  resource :home

  namespace :api do

    namespace :admin do 
      namespace :v1 do 
        resources :rentable_items
      end
    end

    namespace :tmp do 
      resources :invoices do 

      end
    end

    namespace :v1 do 

      resources :listings, only: [:show] do 
        collection do 
          post "/", action: :search
        end

        member do 
          post "/application", action: :application
        end
      end

      resources :news do 
        member do 
          put :context
        end
      end

      resource :authentication do 
        member do 
          post :login
        end
      end

      resources :users, only: [:show, :update] do 
        collection do 
          post :login
          put :notifications
        end
      end
    end
  end

  get "/validations/email/:token", to: "validations#email"

  get "/old-browser", to: "publics#update_browser"

 # authenticated :user do
    root to: "homes#show"
#  end

#  root to: "publics#show"

end
```

[our bug report template]: https://github.com/activeadmin/activeadmin/blob/master/tasks/bug_report_template.rb

**Comment by buffpojken** [comment]
This is on activeadmin 2.6.1, Rails 6.0.2 and Ruby 2.6.4.

**Comment by buffpojken** [comment]
So, having been reading through issues, I found #5316 and tried turning of eager_load for this environment, and with that turned off the issue could not be reproduced at all. 

However, turning it off in production is not really an options for us, so I feel this is an issue somewhere within ActiveAdmin.

**Comment by cdalbergue** [comment]
Hi @buffpojken I don't know if you found a way to fix the problem but I had it too, to the point that I could not start my application anymore (neither in local env or in production).

Upgrading to ruby 2.7, rails 6.0.3 and ActiveAdmin 2.7.0 seems to have fixed it for me.
