### ISSUE TITLE
Admin page styles got purged by purgecss

### ISSUE THREAD

**Issue by ChrisZou** [activeadmin/activeadmin#6252]
I use ActiveAdmin and [purgecss](https://purgecss.com/) (because I use [tailwindcss](https://github.com/tailwindcss/tailwindcss)) in my project. And when deployed to production, all the styles on the admin pages are striped.
I tried to add the following rule to whitelist activeadmin styles according to the purgecss docs but didn't work.

```
/* purgecss start ignore */
// Active Admin's got SASS!
@import '~@activeadmin/activeadmin/src/scss/mixins';
@import '~@activeadmin/activeadmin/src/scss/base';

/* purgecss end ignore */
```

Is there a way to make these two work together?

**Comment by ChrisZou** [comment]
The workaround I found, after some searching, is to use assets pipeline to manage ActiveAdmin's assets and move activeadmin.scss to `vender/assets/stylesheets`. Not sure how to use webpacker and purgecss to do that.

**Comment by xrimpy** [comment]
I copied few of the Views of ActiveAdmin to views/admin

That way purge does not delete the ActiveAdmin Tags

**Comment by gotbadger** [comment]
It seems in production comments are stripped so by the time it gets to the purge css plugin the comments have been removed. You can add `!` so comments are preserved and the following will work (at least it does for me):

```
/*! purgecss start ignore */
// Active Admin's got SASS!
@import '~@activeadmin/activeadmin/src/scss/mixins';
@import '~@activeadmin/activeadmin/src/scss/base';

/*! purgecss end ignore */
```

**Comment by deivid-rodriguez** [comment]
I'm not sure whether's there's some actionable for us to do in activeadmin. The solution given seems good enough.
