### ISSUE TITLE
Custom controller actions rendering error

### ISSUE THREAD

**Issue by PulsarV** [activeadmin/activeadmin#6267]
I have an issue with Active Admin 2.4.0 and custom collection action.
When I use 'active_admin' layout for a custom action, the rendering causes the following error:

undefined method `get' for nil: NilClass

The error comes from this call in layout.rb:
1: render view_factory.layout

The same issue was discussed [there](https://github.com/activeadmin/activeadmin/issues/827)

The issue exists only in production mode and directly depends on the config.eager_load parameter (= true in production mode). Do you have any ideas on how to fix this issue without disabling config.eager_load?

**Comment by yaoquan** [comment]
@PulsarV I'm facing the exact error. Did you managed to get this resolved?
