### ISSUE TITLE
Export is no longer filtered

### ISSUE THREAD

**Issue by Sprachprofi** [activeadmin/activeadmin#6272]
Recently ActiveAdmin's CSV function has stopped behaving as expected, namely it now **ignores any filters and always gives a full export of the table**. Even more curiously, this only happens in my production environment; in my dev environment it still works normally. 

There's another difference: **the production environment shows the currently active filters box underneath the list of filters, while my dev environment shows it above the list of filters**. I have no idea how this can happen because my Gemfile requires ActiveAdmin 2.6.1 in both environments. The version of ActiveAdmin's required gems may differ (Heroku only uses my Gemfile and not the Gemfile.lock), but those wouldn't be involved in export or in deciding where to display the current filters, right?

**Comment by javierjulio** [comment]
This does not appear to be an issue. I'm able to filter an index and download the CSV of that filtered index. If something isn't behaving right though please feel free to open a new issue with specifics and I would accept a PR to resolve any bugs.
