### ISSUE TITLE
Column widths?

### ISSUE THREAD

**Issue by jamsi** [activeadmin/activeadmin#63]
Any idea how to achieve this in Index as a table?

**Comment by MikeRogers0** [comment]
I found an easier way is to target the column in the CSS like:

`app/assets/stylesheets/active_admin.css`
```
#index_table_users .col-misc {
  min-width: 85px;
}
```

**Comment by abrambailey** [comment]
@chrisval I would prefer to see max widths as a percentage

**Comment by abrambailey** [comment]
Oh apparently you can do 
```ruby
column(:notes, max_width: "800px", min_width: "400px")  { ... }
```
