### ISSUE TITLE
 how can i required the user to fill all the fields form

### ISSUE THREAD

**Issue by danielshongo** [activeadmin/activeadmin#6316]
### Did you find a bug?

Describe your problem with a **clear title** sumarizing it, and a **clear
description** including as much relevant information as possible about it.

### Expected behavior

What do you think should happen?

### Actual behavior

What actually happens?

### How to reproduce

Your best chance of getting this bug looked at quickly is to provide a **code
sample** or an **executable test case** demonstrating the expected behavior that is not
occurring. Ideally, use [our bug report template] to create the issue. Simply
copy the content of the appropriate template into a .rb file, make the necessary
changes to demonstrate the issue, and **paste the content into the issue
description**.

[our bug report template]: https://github.com/activeadmin/activeadmin/blob/master/tasks/bug_report_template.rb

**Comment by djalmaaraujo** [comment]
Add validations to your models
