### ISSUE TITLE
Return key doesn't submit modal dialog

### ISSUE THREAD

**Issue by slucaskim** [activeadmin/activeadmin#6354]
### Expected behavior

When pressing the return key within a modal dialog for a batch action, it should submit the form.

### Actual behavior

The modal closes and the page refreshes, and it seems like the form submitted, but it's just a refresh.

### How to reproduce

![image](https://user-images.githubusercontent.com/13230168/86550252-f4298d80-bf0f-11ea-8f47-bf48c69e4e3d.png)
Create a batch action modal confirmation, with form fields like above (reference instructions in "Batch Action Forms" [here](https://activeadmin.info/9-batch-actions.html)). Then press ENTER after completing form field. The page refreshes, and form is not submitted.

**Comment by javierjulio** [comment]
I would accept a PR for this. Thank you.
