### ISSUE TITLE
Not loading jQuery-ui using webpacker

### ISSUE THREAD

**Issue by jbirdjavi** [activeadmin/activeadmin#6357]
I'm upgrading an app that uses ActiveAdmin to Rails 6 using Webpacker.  I followed the directions [here](https://github.com/activeadmin/activeadmin/blob/master/docs/0-installation.md#webpacker) to manually use Webpacker.  I'm getting a console error that seems to indicate that jQuery-ui hasn't been loaded.  I'm probably doing something wrong, but I can't seem to figure it out.

Console error:
```
Uncaught TypeError: Cannot read property 'dialog' of undefined
    at base.js:26
    at base.js:15
    at Object.<anonymous> (base.js:16)
    at Object../node_modules/@activeadmin/activeadmin/app/assets/javascripts/active_admin/base.js (base.js:624)
    at __webpack_require__ (bootstrap:19)
    at Module../app/javascript/packs/active_admin.js (active_admin.js:1)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

I'm running Rails 6.0.3.2 with ActiveAdmin 2.7.0.

```
# config/initializers/active_admin.rb
ActiveAdmin.setup do |config|
  config.use_webpacker = true
  config.site_title = "My Site"
  config.authentication_method = :authenticate_active_admin_user!
  config.current_user_method = :current_user
  config.logout_link_path = :destroy_user_session_path
  config.comments = false
  config.batch_actions = true
  config.localize_format = :long
end
```
```
# app/javascript/packs/active_admin.js
// Load Active Admin's styles into Webpacker,
// see `active_admin.scss` for customization.
import "../stylesheets/active_admin";

import "@activeadmin/activeadmin";
```
```
# config/webpack/environment.js
const { environment } = require('@rails/webpacker')
const jquery = require('./plugins/jquery')

environment.config.set("output.filename", chunkData => {
  // if the name of the pack is "widget" then exclude the chunk hash
  if (chunkData.chunk.name === "campaign") return "campaign.js";
  // otherwise fingerprint the asset
  return "[name].[chunkhash].js";
});

environment.plugins.prepend('jquery', jquery)
module.exports = environment
```
```
# config/webpack/plugins/jquery.js
const webpack = require('webpack')

module.exports = new webpack.ProvidePlugin({
  "$":"jquery",
  "jQuery":"jquery",
  "window.jQuery":"jquery"
});
```

**Comment by jches** [comment]
I was having the same problem, and solved it by adding this to my `config/webpack/environment.js` file, loosely based on examples from webpacker docs here https://github.com/rails/webpacker/blob/master/docs/webpack.md:

```jq
const custom = {
  resolve: {
    alias: {
      jquery: 'jquery/src/jquery',
    }
  }
}

environment.config.merge(custom)
```

**Comment by nitsujri** [comment]
WOW okay @jbirdjavi, not sure if you're still having the problem, but it took me "forever" to hunt it down. Like you I was coming from an existing Rails 6 project.

For me it was pretty much 2 small things:

``` json
    "@rails/webpacker": "^4.2.2", <--- Upgrade This
    "jquery": "3.4.1",                      <--- REMOVE THIS
```

It's really clear looking at the js console that the error is `$.ui.dialog...` and `ui` wasn't getting set properly. 

I tried all sorts of configs and then finally gave up and created a brand new rails app w/ an empty ActiveAdmin installed. Clearly it worked there, so I just deleted all my JS until it worked like the empty app did. Finally narrowed it down to that set of conflicts.

Feels good.

**Comment by jbirdjavi** [comment]
@nitsujri That didn't do it for me unfortunately.  I realized that I'm still waiting for activeadmin_addons to release a webpacker compatible version of their stuff so I went back to the asset pipeline for now.  I'll eventually come back to this when all my dependencies are ready to move to webpacker.

**Comment by dkniffin** [comment]
I think I managed to solve this issue by doing the following:
1. `yarn add jquery jquery-ui-bundle`
2. Add the following two imports _before_ `import "@activeadmin/activeadmin"`
```
import 'script-loader!jquery/dist/jquery.min'
import 'script-loader!jquery-ui-bundle/jquery-ui.min'
```

That said, I'm in the same boat as jbirdjavi. Since many of the other dependencies are not ready for webpacker, I'm having a very difficult time migrating.

For now, I'm going with a workaround mentioned [here](https://gist.github.com/francois-ferrandis/1dc749262e7376e62074f908ee70356b) that allows usage of sprockets _and_ webpacker in AA as a temporary measure until the dependencies are updated, or I can find replacements for them.

**Comment by deivid-rodriguez** [comment]
I'm not sure what's going on :disappointed:. Maybe it's related to the fact that for sprockets we vendor `jquery-ui`, but for webpacker we use the library pulled from npm.

Can someone provide a sample application where this problem can be reproduced?

**Comment by ruurd** [comment]
> I think I managed to solve this issue by doing the following:
> 
> 1. `yarn add jquery jquery-ui-bundle`
> 2. Add the following two imports _before_ `import "@activeadmin/activeadmin"`
> 
> ```
> import 'script-loader!jquery/dist/jquery.min'
> import 'script-loader!jquery-ui-bundle/jquery-ui.min'
> ```

Thank you. That did the trick.

> that allows usage of sprockets _and_ webpacker in AA as a temporary measure

That I even distrust more.

**Comment by Fabulej** [comment]
/config/webpack/environment.js
`const { environment } = require('@rails/webpacker')
const jquery = require('./plugins/jquery')
const webpack = require('webpack')

environment.plugins.prepend('Provide',
  new webpack.ProvidePlugin({
  $: 'jquery/src/jquery',
  jQuery: 'jquery/src/jquery',
  'window.jQuery': 'jquery',
  Popper: ['popper.js', 'default']
}))

environment.plugins.prepend('jquery', jquery)
module.exports = environment

`
That did the trick for me.

**Comment by AyoAlfonso** [comment]
> I think I managed to solve this issue by doing the following:
> 
> 1. `yarn add jquery jquery-ui-bundle`
> 2. Add the following two imports _before_ `import "@activeadmin/activeadmin"`
> 
> ```
> import 'script-loader!jquery/dist/jquery.min'
> import 'script-loader!jquery-ui-bundle/jquery-ui.min'
> ```
> 
> That said, I'm in the same boat as jbirdjavi. Since many of the other dependencies are not ready for webpacker, I'm having a very difficult time migrating.
> 
> For now, I'm going with a workaround mentioned [here](https://gist.github.com/francois-ferrandis/1dc749262e7376e62074f908ee70356b) that allows usage of sprockets _and_ webpacker in AA as a temporary measure until the dependencies are updated, or I can find replacements for them.

Unfortunately this didn't solve my issue.


This did!
```

const custom = {
  resolve: {
    alias: {
      jquery: 'jquery/src/jquery',
    }
  }
}

environment.config.merge(custom)
```
