### ISSUE TITLE
Active_admin displaying in plain html.

### ISSUE THREAD

**Issue by Tshamp7** [activeadmin/activeadmin#6382]
Hello! I had my Active Admin panel working great and then I restarted my rails server and this error message appeared:

Not sure whats changed as I didnt really make any changes from when it was working to when it stopped working aside from restarting my server. 

Does anyone know what could be causing this error? I see that in my packs directory there is not active_admin.js file. Should this file be present in there? I had just switched over from using administrate and got everything working okay. 

Any help is greatly appreciated with this issue!

Webpacker::Manifest::MissingEntryError in Admin::Dashboard#index

Webpacker can't find active_admin.js in /Users/mymac/Desktop/payback_webpage/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
  "application.js": "/packs/js/application-cb08020101e27edca70a.js",
  "application.js.map": "/packs/js/application-cb08020101e27edca70a.js.map",
  "entrypoints": {
    "application": {
      "js": [
        "/packs/js/application-cb08020101e27edca70a.js"
      ],
      "js.map": [
        "/packs/js/application-cb08020101e27edca70a.js.map"
      ]
    },
    "hello_react": {
      "js": [
        "/packs/js/hello_react-119d942039e97edd32a6.js"
      ],
      "js.map": [
        "/packs/js/hello_react-119d942039e97edd32a6.js.map"
      ]
    }

**Comment by Tshamp7** [comment]
I forgot to add, if i copy the active_admin.js file from git and put it in my project, the error message goes away but then my dashboard and all active_admin pages are in plain html.

**Comment by seankovacs** [comment]
Same issue - I ended up turning off webpacker in the config.

**Comment by deivid-rodriguez** [comment]
Hi! I'd like more information on how to reproduce this? Did webpacker worked for you at some point? Is this a development or production environment? Does it break randomly or everytime after the first time it broke? Could you share some application where this error can be seen?

**Comment by fedefa** [comment]
Same issue after upgrading to rails 6. All the pages are in plain html.

Steps to reproduce:

1. Sprockets assets pipeline enabled on 5.2.4 rails project
2. Upgrade to rails 6 and enable webpacker: config.use_webpacker = true
3. Run generator to add active admin assets: rails g active_admin:webpacker

**Comment by fedefa** [comment]
@seankovacs @Tshamp7 See this guide, probably you miss to migrate from sprockets. See this guide:

https://blog.carbonfive.com/migrating-from-sprockets-to-webpacker/
