### ISSUE TITLE
Belongs_to dependencies showing up as blank

### ISSUE THREAD

**Issue by TeamRainless** [activeadmin/activeadmin#6388]
### Did you find a bug?

In my app I have a "Campaign" class that "belongs_to" a "User" class. (And User has_many campaigns.) When I load up active admin... I can see  "User" from the search list... but instead of displaying the names of the users... or their id... each user is present and represented as a blank space.

### Expected behavior

I have tried this in Active Admin 2.0 and I just updated to 2.7 where the problem persists. Previous 1.x versions displayed the User "name."

### Actual behavior

But now Active Admin 2.0+ displays a blank space.

### How to reproduce

This seems to happen with every Class I have that has a has_many/belongs_to relationship.

![Screen Shot 2020-08-06 at 7 51 18 PM](https://user-images.githubusercontent.com/3449975/89565721-44518380-d81f-11ea-8a11-9444308b0321.png)

**Comment by awh-tokyo** [comment]
Do you have any other attributes on your User model that might return nil?  Before :name, by default ActiveAdmin will try :display_name and :full_name, so if you have either of those on your model, with blank values in them, that's what will get displayed.

Most of my models have a :display_name attribute, but they're only populated when :name needs to be overridden, so here's what I did to make it stop trying to use :display_name:

```ruby
  config.display_name_methods = [:full_name, :name, :username, :login, :title, :email, :to_s]
  Formtastic::FormBuilder.collection_label_methods = [:full_name, :name, :username, :login, :title, :email, :to_s]
```
