### ISSUE TITLE
SassC::SyntaxError: Error: Undefined variable: "$primary-color".

### ISSUE THREAD

**Issue by sharat-hegde** [activeadmin/activeadmin#6392]
i am getting this error while doing precompile

SassC::SyntaxError: Error: Undefined variable: "$primary-color".
        on line 33:10 of ../../.rvm/gems/ruby-2.5.0@project/gems/activeadmin-2.4.0/app/assets/stylesheets/active_admin/_typography.scss
        from line 6:9 of ../../.rvm/gems/ruby-2.5.0@project/gems/activeadmin-2.4.0/app/assets/stylesheets/active_admin/_base.scss
>>   color: $primary-color;

**Comment by deivid-rodriguez** [comment]
Closing as duplicate of #5933.
