### ISSUE TITLE
filter :src_name_in, as: :string I dont have drop down for selecting “Contains”, “Equals” ...

### ISSUE THREAD

**Issue by Ivanov-Anton** [activeadmin/activeadmin#6413]
Because my field ends with "in" my filter does not work correct. My filter is now displayed as field with the text type without drop down.

I tried this option: `filter :src_name_in, as: :string, filters: [:starts_with, :equals, :contains, :ends_with] `
I tried this option: `filter :src_name_in, as: :string`
I tried this option: `filter :src_name_in`
I tried this option: `filter :src_name_in, filters: [:contains, :equals, :starts_with, :ends_with]`

**Comment by senid231** [comment]
if `ActiveAdmin::Inputs::Filters::StringInput` finds that filter name ends with ransack predicate (@Ivanov-Anton case) or is a ransackable scope it will ignore `search method select` possibility

problem that we can't enforce mode by filter options directly

```ruby
module ActiveAdmin
  module Inputs
    module Filters
      class StringInput < ::Formtastic::Inputs::StringInput
        include Base
        include Base::SearchMethodSelect

        filter :contains, :equals, :starts_with, :ends_with

        # If the filter method includes a search condition, build a normal string search field.
        # Else, build a search field with a companion dropdown to choose a search condition from.
        def to_html
          if seems_searchable?
            input_wrapping do
              label_html <<
              builder.text_field(method, input_html_options)
            end
          else
            super # SearchMethodSelect#to_html
          end
        end

      end
    end
  end
end
```

```ruby
      def seems_searchable?
        has_predicate? || scope?
      end

      # If the given method has a predicate (like _eq or _lteq), it's pretty
      # likely we're dealing with a valid search method.
      def has_predicate?
        !!Ransack::Predicate.detect_from_string(method.to_s)
      end
```

it would be nice to do something like `filter :src_name_in, as: :string, search_method_select: true` or something similar

**Comment by Ivanov-Anton** [comment]
@deivid-rodriguez  we need your comment, thank.

**Comment by Fivell** [comment]
@Ivanov-Anton  , @senid231  possible solution is to check if it is real column name, no other options needed 
```ruby
     def to_html
          if seems_searchable? && column_for(method).blank?
            input_wrapping do
              label_html <<
              builder.text_field(method, input_html_options)
            end
          else
            super # SearchMethodSelect#to_html
          end
        end
```

**Comment by senid231** [comment]
@Fivell I think it's better to patch `seems_searchable?`

```ruby
def seems_searchable?
  return false if column_for(method).present?

  super
end
```
