### ISSUE TITLE
How to overwrite index collection or show/hide records?

### ISSUE THREAD

**Issue by releu** [activeadmin/activeadmin#642]
I have AdminUser and Post.

Post belongs_to AdminUser

In the index action I should show only author posts (Post.where(:admin_user_id => current_admin_user.id)).

How I can do it?

Thanks.

**Comment by seaify** [comment]
now you need to use scope_collection method, not the scoped & metasearch way.

```
  controller do
    def scoped_collection
      params[:supplier_id] ? Car.where(supplier_id: params["supplier_id"]): Car.all
    end
  end
```

**Comment by railsfactory-madhusudhan** [comment]
thanks @timoschilling and @seaify both solution works!!

**Comment by webmaster219** [comment]
Very thanks @timoschilling  and @seaify

**Comment by AlexVentura** [comment]
Hi there!
Maybe it does not have much to see or is not directly related to the main topic. But I what to download CSV files but not the entire records from a table instead export a custom query or a specific scope. I don't want to only customize the columns but also the records that are exported in the CSV file.
I read that it is related to the info you are viewing in the index page but I want the specific records to be exported and it does not matter if the whole records are shown in the index page, I just want to download a specific query or scope.

Any help or suggestion?
I hope I could be clear.

**Comment by Gowtham03** [comment]
It Works for me 

 scope_to :index => :scoped do 
   current_user_profile.organizations.first
  end

**Comment by HanyMoh** [comment]
> HI @izumeroot, this ticket is rather old; why not take the standard approach?
> 
> ```ruby
> controller do
>   def scoped_collection
>     resource_class.foo.bar.baz
>   end
> end
> ```

this worked with me

 controller do
    def scoped_collection
      resource_class.current_venodor_products(current_admin)
    end
  end

current_venodor_products is a scope show only records owned by the current vendor
