### ISSUE TITLE
It does not support splitting js into chunks

### ISSUE THREAD

**Issue by JorgeLeites** [activeadmin/activeadmin#6429]
I have the following webpack configuration:

```js
environment.config.optimization = {
  splitChunks: {
    cacheGroups: {
      vendor: {
        test: /node_modules/,
        chunks: 'initial',
        name: 'vendor',
        enforce: true,
      },
      default: {
        minChunks: 2,
        priority: -20,
        reuseExistingChunk: true,
      },
    },
  },
};
```

Splitting the js into chunks to exclude the node_modules. 
This is causing the js to be loaded incorrectly.

I managed to "fix it" by changing the method `build_active_admin_head` on `ActiveAdmin::Views::Pages::Base` to use webpacker's [javascript_packs_with_chunks_tag helper](https://www.rubydoc.info/gems/webpacker/Webpacker/Helper#javascript_packs_with_chunks_tag-instance_method).

I think there should be a configuration option to enable this.

**Comment by deivid-rodriguez** [comment]
Hi @JorgeLeites! Thanks for the ticket.

Could you make a proposal on how we should make this configurable?

**Comment by JorgeLeites** [comment]
I'd add something like a `use_javascript_chunks` option to the namespace settings and use that to choose between `javascript_pack_tag` and `javascript_packs_with_chunks_tag`.
I imagine that would make `use_webpacker` required to use that option, but I guess it makes sense.

**Comment by deivid-rodriguez** [comment]
It seems like it's no longer an issue in `webpacker`!
