### ISSUE TITLE
Get ready for `circleci/jruby` deprecation

### ISSUE THREAD

**Issue by deivid-rodriguez** [activeadmin/activeadmin#6453]
I received this email from CircleCI a while ago:

![JRubyDeprecation](https://user-images.githubusercontent.com/2887858/93328032-75a87080-f81b-11ea-9b95-af0da94c282d.png)

Apparently `circleci/jruby` will stop receiving updates soon, so we'll need to build our own base image.

Since we're going to need to do this, maybe we can take the chance and migrate to Github Actions + [Github Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/).

**Comment by javierjulio** [comment]
Sounds good to me! Thanks for the heads up as I didn't get this.
