### ISSUE TITLE
Question: Does active admin support global scopes or filtering by record ID in URL?

### ISSUE THREAD

**Issue by interpegasus** [activeadmin/activeadmin#6459]
My app has a DB model called Project. And other models have a `belongs_to :project`

I would like to know if it is possible to pass an `ID` in the URL in order to filter everything by `project_id` automatically?

Sorry for asking here. Thank you

Eg:
```
https://mydomain.com/admin/{PROJECT-ID}/dashboard
https://mydomain.com/admin/{PROJECT-ID}/users
https://mydomain.com/admin/{PROJECT-ID}/games
```

**Comment by deivid-rodriguez** [comment]
Did you check [`belongs_to`](https://github.com/activeadmin/activeadmin/blob/master/docs/2-resource-customization.md#belongs-to).

**Comment by deivid-rodriguez** [comment]
Also, please check https://github.com/activeadmin/activeadmin/tree/db1ac5a0ace0628cf369b59290c3eb6f868971a0#need-help. For questions we prefer stackoverflow so that I wider community can help you. Dealing with issues and feature requests in this tracker is already enough work :sweat_smile:.

**Comment by interpegasus** [comment]
Perfect! belongs_to is what I was looking for. Thank you very much
