### ISSUE TITLE
add sort support for filters

### ISSUE THREAD

**Issue by gutenye** [activeadmin/activeadmin#647]
something like this

```
filter :school, :sort => 'asc'   # User.belongs_to :school
```

I think, it'll be nice with this feature.

current I use below code to make it work.

```
filter :school, :collection => proc { School.order(:name, 'asc') }
```

**Comment by dkniffin** [comment]
It looks like the workaround doesn't work anymore. I think the sort attribute makes sense, so that each filter can define it's own sorting method.

I have no idea who to ping, so I'm just going to pick someone based on activity: @deivid-rodriguez any chance we can re-open this?
