### ISSUE TITLE
Disable COUNT(*) for filtered collections

### ISSUE THREAD

**Issue by kceb** [activeadmin/activeadmin#6492]
### Did you find a bug?

I'm using pagination_total false on the index collection, which works fine and as expected. However, I'm noticing in the SQL debug logs that when I filter a collection (by user_id), it is still doing a `SELECT COUNT(*) FROM (SELECT 1 AS one FROM "large_table" WHERE "large_table"."user_id" = 123 ORDER BY "large_table"."id" desc LIMIT $1 OFFSET $2) subquery_for_count`.

Is there a way to disable this for filters? I have an extremely large table and it is causing my app to timeout.

I'm just using the default filter method on my activeadmin model

### Expected behavior

Filtering large tables should not run an expensive `COUNT(*)` or `ORDER BY` (even if it is using limit and offset)

### Actual behavior

Request times out

### How to reproduce

Have an extremely large table and filter on an indexed column like user_id. Expect it to be relatively performant and not run things like COUNT(*) unnecessarily.

**Comment by allisonphillips** [comment]
I put up a PR for this: https://github.com/activeadmin/activeadmin/pull/7489

I refactored this to prevent it from triggering a COUNT query on loaded records:
```ruby
module ActiveAdmin
  module Helpers
    module Collection
      def collection_size(c = collection)
        # 'length' avoids count query on unloaded collection with a limit_value
        return c.length if c.is_a?(Array) || c.limit_value.present?

        c = c.except :select, :order
        # Size prevents redundant COUNT queries on loaded collections
        c.group_values.present? ? c.size.size : c.size
      end
    end
  end
end
```

Haven't contributed to ActiveAdmin before so I'm not sure how long their review process takes, but I believe this to be the fix.

**Comment by javierjulio** [comment]
There is a PR ready for this that needs an update. Thank you.
