### ISSUE TITLE
Prepare (if necessary) for CircleCI + docker changes

### ISSUE THREAD

**Issue by deivid-rodriguez** [activeadmin/activeadmin#6493]
I just got this email:

> Hi there,
>
> On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow.
>
> Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP.
>
> We are currently working on a partnership with Docker to minimize the impact of this change for our users and will share more details as we get them.
>
> For more information or to leave a question for us, please head over to Discuss or contact support.
>
> Thanks and happy building,
>
> - The CircleCI team 

Just copying it here to make sure we don't forget about it.

**Comment by javierjulio** [comment]
Thanks! I received today too.
