### ISSUE TITLE
Nested resource path adding ID for both resources.

### ISSUE THREAD

**Issue by curtisolson** [activeadmin/activeadmin#6537]
I have a nested resource Message as a child to MessageThread. I created a custom show page for MessageThread (MT) that shows MT and Message. When trying to add an action button to add a Message, the resource path included included the id in both resources.

MessageThread and Message code at bottom.

The workaround was simple, though I'm sure there is a better way to do this.
```
    link=admin_message_thread_message_path(resource).split("/")
    link.pop()
    link_to("New Message", link.join('/'))
```

### Expected behavior

Expected: 
admin_message_thread_message_path(resource) to return: 
**http://localhost:3000/admin/message_threads/12/messages**

### Actual behavior
admin_message_thread_message_path(resource) returns: 
**http://localhost:3000/admin/message_threads/12/messages/12**

### How to reproduce

**message_threads.rb**

```ActiveAdmin.register MessageThread do
#  menu parent: "Messages", label: "Messages Threads", priority: 5
  actions :index, :show

  action_item :new_message, only: :show, if: proc{ !message_thread.closed? } do
    link_to("New Message", admin_message_thread_message_path(resource))
  end

  show do
    attributes_table do
      row ("user_id") {|mt| auto_link mt.user}
      row ("VIN") {|mt| auto_link(mt.vehicle, mt.vehicle.vin )}
      row :closed
      row ("closed_author_id") {|mt| auto_link mt.closed_author}
      row :reported
      row ("reported_author_id") {|mt| auto_link mt.reported_author}
      row :reported_reason
    end

    panel "Messages" do
      table_for(message_thread.messages.order(created_at: :desc)) do |message|
        message.column "Sent", :created_at
        message.column "Message", :body
        message.column "Status", :status
        message.column ("owner_id")  {|message| auto_link message.owner}
      end
    end
  end
end
```

**messages.rb**

```
ActiveAdmin.register Message do
  belongs_to :message_thread
  permit_params :message_thread_id, :owner_type, :owner_id, :body, :status
end
```

**Comment by deivid-rodriguez** [comment]
I think you want `admin_message_thread_messages_path(resource)` instead?
