### ISSUE TITLE
Ransack is unmaintained

### ISSUE THREAD

**Issue by jpsilvashy** [activeadmin/activeadmin#6539]
Ransack has been the source of a lot of problems in recent months, is seems mostly to be related to rails changing how polymorphic joins work. Ransack seems aggressively monkey patch active record and seeing has it's out of active development we're in a bit of trouble.

Rails 6.1 when ever there is any type of join in my activerecord code I get:
   
    ArgumentError (wrong number of arguments (given 3, expected 2)):

Without a stacktrace, if I downgrade to 2.3.0 all the joins work, but active admin does not.

**Comment by varyonic** [comment]
See also activerecord-hackery/ransack#1127

**Comment by deivid-rodriguez** [comment]
I'm talking to former ransack maintainer to get maintainer permissions there and will try my best to improve things. In the mean time I'll close this since I don't think it makes much sense to keep this issue opened in this repo.
