### ISSUE TITLE
Unable to override the index page of the resource which is defined in the engine

### ISSUE THREAD

**Issue by chubchenko** [activeadmin/activeadmin#6562]
### Did you find a bug?

I have an engine with an ActiveAdmin resource, and in my main application, I want to override the `index` page for it. Also, I found the [wiki page](https://github.com/activeadmin/activeadmin/wiki/Define-a-resource-inside-an-engine) that says I should prepend the engine's resource to the ActiveAdmin load path - I did this step. But in the end, my page looks like it was defined in the engine.

### Expected behavior

I expect that I can override the `index` page since I could do the same for the `show` page.

### Actual behavior

The `index` page looks like it was defined in the engine.

### How to reproduce

```ruby
# Engine
# 
# admin/redirect.rb
ActiveAdmin.register Redirectable::Redirect do
  index do
    column :to
  end
end
```

```ruby
# Engine
#
# lib/redirectable/engine.rb
module Redirectable
  class Engine < ::Rails::Engine
    isolate_namespace Redirectable

    initializer 'redirectable' do
      ::ActiveAdmin.application.load_paths.unshift(
        *::Dir[root + 'admin']
      )
    end
```

```ruby
# Main application
#
# app/admin/redirectable/redirect.rb
ActiveAdmin.register Redirectable::Redirect do
  index do
    column :to
    column :from
  end
end
```

activeadmin: `2.8.1`
rails: `6.0.3.4`

Let me know if you need more details thanks.

**Comment by deivid-rodriguez** [comment]
Hi @chubchenko!

Could you make a reproducible example using [our bug report template](https://github.com/activeadmin/activeadmin/blob/07a4489d4dfd54651e348cf432883d89638ac4ed/tasks/bug_report_template.rb#L1) or alternatively provide a sample application with steps to reproduce this?

Thanks!
