### ISSUE TITLE
Support for Rails 6.1.0

### ISSUE THREAD

**Issue by EnziinSystem** [activeadmin/activeadmin#6593]
Please upgrade to support Rails 6.1.0

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    activeadmin (~> 2.8, >= 2.8.1) was resolved to 2.8.1, which depends on
      railties (< 6.1, >= 5.2)

    rails (= 6.1.0) was resolved to 6.1.0, which depends on
      railties (= 6.1.0)
```

**Comment by sjieg** [comment]
Potential (Temporarily) fix:
```
gem 'activeadmin', git: 'https://github.com/activeadmin/activeadmin.git', ref: '8578160'
```
See PR: https://github.com/activeadmin/activeadmin/pull/6548
@deivid-rodriguez

**Comment by whitewolf92** [comment]
Is it fixed?

**Comment by deivid-rodriguez** [comment]
Sorry for the delay, I'm just trying to find time to release this.

**Comment by deivid-rodriguez** [comment]
You can point to the master branch for now.

**Comment by whitewolf92** [comment]
No worries bro, enjoy your weekend. In the meanwhile, I will just use good old rails console lol.

**Comment by rew-ron** [comment]
Looks like this could be closed now. 

I see the new version supporting railties <6.2 https://rubygems.org/gems/activeadmin/versions/2.9.0

**Comment by deivid-rodriguez** [comment]
Oh, yes, forgot to close this! It's out!
