### ISSUE TITLE
 Getting error in Nginx error log

### ISSUE THREAD

**Issue by nitin-rvm** [activeadmin/activeadmin#6618]
My application running perfectly with active admin but I am getting this error in my Nginx error log:
2020/12/16 21:29:27 [error] 13973#0: *50257 open() "/var/www/apps/app_name/production/current/public/assets/active_admin/print-629b804c46f8e53152a27d41c7465a9e.css" failed (2: No such file or directory), client: client_ip, server: app_domian, request: "GET /assets/active_admin/print-629b804c46f8e53152a27d41c7465a9e.css HTTP/1.1", host: "app_domian", referrer: "https://app_domain/honeydue"

I checked page resource for the active admin login page and found this css is calling by active admin gem, so for a temporary fix I have created a blank file with the name print-629b804c46f8e53152a27d41c7465a9e.css at the mentioned path for which I'm getting error but whenever I deploy anything on the server it removes that file because this is calling template under public/assets folder and for my app I always include css files under app/assets/stylesheets folder.

this is what I found in view page source:
<link href="/assets/active_admin/print-629b804c46f8e53152a27d41c7465a9e.css" media="print" rel="stylesheet" type="text/css" />

I just want to stop calling this file from the active admin layout.

here is the info about configuration:
activeadmin gem version: 0.6.6
ruby: 2.0.0
rails: 3.2.13

nginx config to serve assets
location ~ ^/(assets)/  {
     root /var/www/apps/app_name/production/current/public;
    gzip_static on; # to serve pre-gzipped version
    #expires max;
    #add_header  Cache-Control public;
    #add_header Access-Control-Allow-Origin *;
  }

**Comment by deivid-rodriguez** [comment]
Hi @nitin-rvm,

You're using versions of activeadmin, ruby, and rails which are no longer supported. And they're not just recently unsupported, they have been for a very long time. I'm sorry but I can't provide any support for such old versions. I recommend looking for old upgrade guides, and trying to upgrade these dependencies, one at a time.

Good luck!

**Comment by nitin-rvm** [comment]
Do you think I am having this issue due to old versions of gem and ruby rails? or this is something other thing which is not related with versions?please guide me here so I can research on it from my end and do something to fix it.

**Comment by deivid-rodriguez** [comment]
I honestly have no idea what the problem is. Again, my take would be to try upgrade and see if the problem is gone. Good luck with the research!
