### ISSUE TITLE
active_admin_form_for labels not working as expected

### ISSUE THREAD

**Issue by bcavileer** [activeadmin/activeadmin#6620]
Forms across the site say missing translations.
<img width="515" alt="Screen Shot 2020-12-18 at 10 21 47 AM" src="https://user-images.githubusercontent.com/96518/102631448-b4e8a500-411b-11eb-8274-9574eeeb70ec.png">

<img width="342" alt="Screen Shot 2020-12-18 at 10 28 54 AM" src="https://user-images.githubusercontent.com/96518/102631553-dfd2f900-411b-11eb-97d1-5c0f7d43e350.png">

This is a new Rails 6.1 project with ActiveAdmin 2.9

### Expected behavior

`f.input :password, label: t('active_admin.devise.password.title')` should have the label "Password"

```
t('active_admin.devise.password.title')
=> "Password"
```

### Actual behavior

```
f.input :password, label: t('active_admin.devise.password.title')
=> <li class="password input required stringish" 
           id="admin_user_password_input">
           <label for="admin_user_password"
                      class="label">
                         Password<abbr title="translation missing: en.required">*</abbr></label>
                         <input placeholder="translation missing: en.admin_user.new.password" 
                                     maxlength="128" id="admin_user_password" type="password" name="admin_user[password]" />

<p class="inline-hints">translation missing: en.admin_user.new.password</p></li>
```
### How to reproduce

create a new Rails 6.1 project
add gem 'activeadmin', "~> 2.9"
rails g active_admin:install --use_webpacker

**Comment by bcavileer** [comment]
I was using Ruby 3.0.0-preview2

I switched to Ruby 2.7.2 and this problem went away.  This could possibly be a bug in Formtastic with Ruby 3?

**Comment by deivid-rodriguez** [comment]
Maybe, I'm going to run formtastic tests on ruby 3 to double check.

**Comment by Lordnibbler** [comment]
Seeing the same issue when switching to ruby 3, fwiw

**Comment by Lordnibbler** [comment]
Updated `Gemfile` accordingly

```
gem 'formtastic', '4.0.0rc1'
```

and problem solved.
