### ISSUE TITLE
Batch action date has incorrect format

### ISSUE THREAD

**Issue by JorgeLeites** [activeadmin/activeadmin#6635]
### Did you find a bug?

An administrator told us that he was unable to perform a batch action. When we checked the logs, we noticed the date was arriving in a `MM/DD/YYYY` format, causing the batch action to fail.

### Expected behavior

The date should arrive in the usual ISO 8601 format, or at least there should be some place to configure date formats so that the behavior is consistent.

### How to reproduce

I was not able to reproduce the issue. In the screen capture he sent it looks like he is using chrome on windows, if that is of any help.

**Comment by deivid-rodriguez** [comment]
Can you post some logs of the failure?
