### ISSUE TITLE
Receiving "LoadError - cannot load such file -- sassc" after updating from 2.8.1 to 2.9.0

### ISSUE THREAD

**Issue by QuantumWaver** [activeadmin/activeadmin#6636]
I am currently running Rails 6.0.3.4 and Ruby 2.6.6, and when I recently updated AA from version 2.8.1 to 2.9.0 I began receiving this error when attempting to open AA in the local rails server:

```
Processing by Admin::DashboardController#index as HTML
  AdminUser Load (0.8ms)  SELECT "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = $1 ORDER BY "admin_users"."id" ASC LIMIT $2  [["id", 18], ["LIMIT", 1]]
  ↳ app/middleware/cached_response.rb:16:in `call'
  Rendering vendor/ruby/2.6.0/gems/activeadmin-2.9.0/app/views/active_admin/page/index.html.arb
  Rendered vendor/ruby/2.6.0/gems/activeadmin-2.9.0/app/views/active_admin/page/index.html.arb (Duration: 8.1ms | Allocations: 5881)
Completed 500 Internal Server Error in 48ms (ActiveRecord: 9.2ms | Allocations: 38121)

LoadError - cannot load such file -- sassc:
  app/middleware/cached_response.rb:16:in `call'
```

It was running smoothly prior to the upgrade, so any help would be greatly appreciated! Thanks!

**Comment by deivid-rodriguez** [comment]
Hi @QuantumWaver! Sorry about this, I was kind of expecting this issue... :sweat_smile:.

ActiveAdmin 2.9.0 dropped its dependency on `sassc`, so now you have to include it on your side if you need it. Add `sassc-rails` to your `Gemfile`, run `bundle install`, and then you should be ok again.

Let me know!

**Comment by QuantumWaver** [comment]
> Hi @QuantumWaver! Sorry about this, I was kind of expecting this issue... 😅.
> 
> ActiveAdmin 2.9.0 dropped its dependency on `sassc`, so now you have to include it on your side if you need it. Add `sassc-rails` to your `Gemfile`, run `bundle install`, and then you should be ok again.
> 
> Let me know!

Thank you so much for the quick reply! Honestly, I'm not sure WHY I would still need `sassc`, any thoughts on how I can remove the need for that?

**Comment by deivid-rodriguez** [comment]
You could migrate your Rails app to use `webpacker` instead. In fact, the reason we made `sassc` an optional dependency is that it's quite heavy in terms of install time, and people were complaining because it takes long to install and they don't even use it since they use `webpacker`.

**Comment by QuantumWaver** [comment]
@deivid-rodriguez Ok, thank you so much for you help! I got it working for now with the inclusion of the `sassc-rails` gem, but will look into migrating to webpacker in the future!
