### ISSUE TITLE
Could not find table 'active_admin_comments'

### ISSUE THREAD

**Issue by MamaMiaLetMeGo** [activeadmin/activeadmin#6650]
After I do ... rails generate active_admin:install

and then do ... rails db:migrate

I do not get a migration for comments. Ok so who cares about the comments then. But after I set up my has_many relationships and try to create a category from the activeadmin backend I get this error referring to the missing comment:

ActiveRecord::StatementInvalid in Admin::Categories#show

.rvm/gems/ruby-2.7.0/gems/activeadmin-2.9.0/app/views/active_admin/resource/show.html.arb where line 2 raised:

Could not find table 'active_admin_comments'

def table_structure(table_name)
structure = exec_query("PRAGMA table_info(#{quote_table_name(table_name)})", "SCHEMA")
raise(ActiveRecord::StatementInvalid, "Could not find table '#{table_name}'") if structure.empty?
table_structure_with_collation(table_name, structure)
end

Any ideas how to fix this? Any help is greatly appreciated!

**Comment by deivid-rodriguez** [comment]
Hi, sorry for the delay. Can you provide a way to reproduce this? Normally a migration for comments should be generated.
