### ISSUE TITLE
"No route matches" error after upgrading to Rails 6.1 - ActiveAdmin in engine

### ISSUE THREAD

**Issue by wangthony** [activeadmin/activeadmin#6686]
### Did you find a bug?

I have ActiveAdmin set up in an engine for a single model. On Rails 6.0.3.4, it works fine. After upgrading to Rails 6.1.1, rendering the index action raises an error:

```
DRb::DRbRemoteError: No route matches {:action=>"new", :controller=>"admin/tables"} (ActionView::Template::Error)
    /Users/awang/.rvm/gems/ruby-2.6.5/gems/actionpack-6.1.1/lib/action_dispatch/journey/formatter.rb:44:in `path'
    /Users/awang/.rvm/gems/ruby-2.6.5/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:823:in `url_for'
    /Users/awang/.rvm/gems/ruby-2.6.5/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:270:in `call'
    /Users/awang/.rvm/gems/ruby-2.6.5/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:213:in `call'
    /Users/awang/.rvm/gems/ruby-2.6.5/gems/actionpack-6.1.1/lib/action_dispatch/routing/route_set.rb:326:in `block in define_url_helper'
    /Users/awang/.rvm/gems/ruby-2.6.5/gems/inherited_resources-1.12.0/lib/inherited_resources/url_helpers.rb:237:in `block in define_helper_method'
    /Users/awang/.rvm/gems/ruby-2.6.5/gems/inherited_resources-1.12.0/app/controllers/inherited_resources/base.rb:25:in `new_resource_path'
    /Users/awang/.rvm/gems/ruby-2.6.5/gems/arbre-1.4.0/lib/arbre/element.rb:182:in `method_missing'
    /Users/awang/.rvm/gems/ruby-2.6.5/gems/activeadmin-2.9.0/lib/active_admin/resource/action_items.rb:69:in `block in add_default_new_action_item'
```

Looks like the error comes from the ActiveAdmin page trying to render the <New Resource> action item. I did some investigation, and it looks like InheritedResources::UrlHelpers is using engine's routes, not the entire application's. Only the engine's `root_path` route is present in that context. `rails routes` shows that the admin routes are all defined in the application.

### Expected behavior

Test case for the index action should pass (see below for code).

### Actual behavior

Test case raises the error above. When you start the server and go to the admin index URL, the same error is raised.

### How to reproduce

```
git clone https://github.com/wangthony/admin_test
cd admin_test

# the main branch is rails 6.1.1 - this will fail with the error above
bundle install
rails db:setup
BACKTRACE=1 rails t

# rails 6.0.3.4 will pass
git checkout rails-6.0.3.4
bundle update rails
rails t
```

**Comment by wangthony** [comment]
Updated https://github.com/wangthony/admin_test to Rails 6.1.3. The error still happens.

**Comment by wangthony** [comment]
After digging into this a little more, it looks like this is a duplicate of https://github.com/activeadmin/activeadmin/issues/4446 - closing.

**Comment by deivid-rodriguez** [comment]
I did no investigation whatsoever, but I did bisect this to https://github.com/rails/rails/pull/37927.
