### ISSUE TITLE
Undefined Method `per' for #<ActiveRecord::Relation:0x3fd2330>

### ISSUE THREAD

**Issue by Gerhardk** [activeadmin/activeadmin#670]
Environment: 
Ruby 1.9.2
Rails 3.0.10
activeadmin 0.3.2
kaminari 0.12.4
meta_search 1.0.6
will_paginate 3.0.2

When trying to access the index page of a model added to activeadmin the I get the following error:

undefined method `per' for #ActiveRecord::Relation:0x3fd2330

activerecord (3.0.10) lib/active_record/relation.rb:374:in `method_missing'
activeadmin (0.3.2) lib/active_admin/resource_controller/collection.rb:123:in`paginate'
activeadmin (0.3.2) lib/active_admin/resource_controller/collection.rb:114:in `active_admin_collection'
activeadmin (0.3.2) lib/active_admin/resource_controller/collection.rb:17:in`collection'
inherited_resources (1.2.2) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (0.3.2) lib/active_admin/resource_controller/actions.rb:11:in`index'
actionpack (3.0.10) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.0.10) lib/abstract_controller/base.rb:150:in`process_action'
actionpack (3.0.10) lib/action_controller/metal/rendering.rb:11:in `process_action'
actionpack (3.0.10) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
activesupport (3.0.10) lib/active_support/callbacks.rb:461:in `_run__253224298__process_action__730883725__callbacks'
activesupport (3.0.10) lib/active_support/callbacks.rb:410:in`_run_process_action_callbacks'
activesupport (3.0.10) lib/active_support/callbacks.rb:94:in `run_callbacks'
actionpack (3.0.10) lib/abstract_controller/callbacks.rb:17:in`process_action'
actionpack (3.0.10) lib/action_controller/metal/rescue.rb:17:in `process_action'
actionpack (3.0.10) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
activesupport (3.0.10) lib/active_support/notifications.rb:52:in `block in instrument'
activesupport (3.0.10) lib/active_support/notifications/instrumenter.rb:21:in`instrument'
activesupport (3.0.10) lib/active_support/notifications.rb:52:in `instrument'
actionpack (3.0.10) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
actionpack (3.0.10) lib/abstract_controller/base.rb:119:in `process'
actionpack (3.0.10) lib/abstract_controller/rendering.rb:41:in`process'
actionpack (3.0.10) lib/action_controller/metal.rb:138:in `dispatch'
actionpack (3.0.10) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
actionpack (3.0.10) lib/action_controller/metal.rb:178:in `block in action'
actionpack (3.0.10) lib/action_dispatch/routing/route_set.rb:62:in`call'
actionpack (3.0.10) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
actionpack (3.0.10) lib/action_dispatch/routing/route_set.rb:27:in`call'
rack-mount (0.6.14) lib/rack/mount/route_set.rb:148:in `block in call'
rack-mount (0.6.14) lib/rack/mount/code_generation.rb:93:in`block in recognize'
rack-mount (0.6.14) lib/rack/mount/code_generation.rb:75:in `optimized_each'
rack-mount (0.6.14) lib/rack/mount/code_generation.rb:92:in`recognize'
rack-mount (0.6.14) lib/rack/mount/route_set.rb:139:in `call'
actionpack (3.0.10) lib/action_dispatch/routing/route_set.rb:493:in`call'
sass (3.1.10) lib/sass/plugin/rack.rb:54:in `call'
warden (1.0.6) lib/warden/manager.rb:35:in`block in call'
warden (1.0.6) lib/warden/manager.rb:34:in `catch'
warden (1.0.6) lib/warden/manager.rb:34:in`call'
actionpack (3.0.10) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
actionpack (3.0.10) lib/action_dispatch/middleware/head.rb:14:in`call'
rack (1.2.4) lib/rack/methodoverride.rb:24:in `call'
actionpack (3.0.10) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
actionpack (3.0.10) lib/action_dispatch/middleware/flash.rb:182:in `call'
actionpack (3.0.10) lib/action_dispatch/middleware/session/abstract_store.rb:149:in`call'
actionpack (3.0.10) lib/action_dispatch/middleware/cookies.rb:302:in `call'
activerecord (3.0.10) lib/active_record/query_cache.rb:32:in`block in call'
activerecord (3.0.10) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
activerecord (3.0.10) lib/active_record/query_cache.rb:12:in`cache'
activerecord (3.0.10) lib/active_record/query_cache.rb:31:in `call'
activerecord (3.0.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in`call'
actionpack (3.0.10) lib/action_dispatch/middleware/callbacks.rb:46:in `block in call'
activesupport (3.0.10) lib/active_support/callbacks.rb:416:in`_run_call_callbacks'
actionpack (3.0.10) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
rack (1.2.4) lib/rack/sendfile.rb:106:in`call'
actionpack (3.0.10) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.0.10) lib/action_dispatch/middleware/show_exceptions.rb:47:in`call'
railties (3.0.10) lib/rails/rack/logger.rb:13:in `call'
rack (1.2.4) lib/rack/runtime.rb:17:in`call'
activesupport (3.0.10) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.2.4) lib/rack/lock.rb:11:in`block in call'
internal:prelude:10:in `synchronize'
rack (1.2.4) lib/rack/lock.rb:11:in`call'
actionpack (3.0.10) lib/action_dispatch/middleware/static.rb:30:in `call'
railties (3.0.10) lib/rails/application.rb:168:in`call'
railties (3.0.10) lib/rails/application.rb:77:in `method_missing'
railties (3.0.10) lib/rails/rack/log_tailer.rb:14:in`call'
rack (1.2.4) lib/rack/content_length.rb:13:in `call'
rack (1.2.4) lib/rack/handler/webrick.rb:52:in`service'
C:/Ruby192/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
C:/Ruby192/lib/ruby/1.9.1/webrick/httpserver.rb:70:in`run'
C:/Ruby192/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'

Can someone please help me

**Comment by drodrigo** [comment]
Thanks a lot dogweather!

**Comment by germs12** [comment]
:+1: Thanks @dogweather

**Comment by felipecerda** [comment]
Thanks dogweather!

**Comment by TaiwoAyanleye** [comment]
As support to the link @dogweather gave, the file is now "kaminari_config.rb" not "kaminari.rb".
:+1: @dogweather

**Comment by RajRoR** [comment]
Instead of sticking with a specific version, I would prefer to go for the solution given here: http://tech-brains.blogspot.in/2012/11/kaminari-willpaginate-incompatibility.html

**Comment by sadaf2605** [comment]
+1 @RajRoR

**Comment by voltechs** [comment]
:+1: @dogweather :D

**Comment by caesarsol** [comment]
+1 for reopening the issue.

why should ActiveAdmin force me to use Kaminari? :-1:

**Comment by roadev** [comment]
Guys! I'm using kaminari with rails 4.0.4 and I've put and index in controller:
```ruby
@dreams = Dream.all.page(params[:page]).per(5)
```
When I want to paginate @dreams at index view, I got...
``` undefined method `total_pages' for #<ActiveRecord::Relation::ActiveRecord_Relation_Dream:0x0000000751dd38>```
I'm not working with ActiveAdmin....

**Comment by seanlinsley** [comment]
@roadev you should open a separate ticket with more information.

@RajRoR's link doesn't seem to go where it suggests:

<img width="985" alt="screen shot 2015-10-26 at 8 55 20 pm" src="https://cloud.githubusercontent.com/assets/688886/10747514/02b2cddc-7c24-11e5-8768-838f17fb15d8.png">

@sadaf2605, @voltechs, @caesarsol: if you would like to pay the core Active Admin contributors to maintain both kaminari and will_paginate compatibility, that's one thing. But you can't expect us who work on Active Admin for free to take on such a large project, especially one that will inevitably take a large amount of effort to maintain going into the future.

Unless something dramatic were to change, Active Admin will be using Kaminari exclusively for the foreseeable future.
