### ISSUE TITLE
'favicon' configuration option does not honor 'use_webpacker' option

### ISSUE THREAD

**Issue by Fs00** [activeadmin/activeadmin#6728]
I've noticed that `config.favicon` option adds to the page a [`favicon_link_tag`](https://api.rubyonrails.org/v6.1.0/classes/ActionView/Helpers/AssetTagHelper.html#method-i-favicon_link_tag) that points to an image asset managed by the legacy asset pipeline, and thus there is currently no way to use a favicon coming from Webpacker packs.
A simple solution could be to change the following code

https://github.com/activeadmin/activeadmin/blob/a8e9d2f78960968c2c9409b2b7e3c5cf1b5c38ba/lib/active_admin/views/pages/base.rb#L45-L47

to use Webpacker's `favicon_pack_tag` instead of `favicon_link_tag` when `config.use_webpacker` is set to true.

**Comment by deivid-rodriguez** [comment]
@Fs00 Could you open a PR to fix this the way you suggested?

**Comment by Fs00** [comment]
I once tried but I was getting several failures in apparently unrelated Cucumber tests. I gave up because I simply hadn't enough time and motivation to look into them.
That's why I would be happier if you could take care of it 😃

**Comment by deivid-rodriguez** [comment]
Can you push your WIP version to a WIP PR?

**Comment by Fs00** [comment]
Will do when I have some time.
