### ISSUE TITLE
table_for inside `show` view doesn't use I18n

### ISSUE THREAD

**Issue by Zequez** [activeadmin/activeadmin#675]
If you write the following:

```ruby
show do
  panel 'Comments' do
    table_for post.comments do
      column :user_name
      column :user_email
      column :content
    end
  end
end
```

It only humanize the keys, but it does not call I18n
For it to call I18n you have to do the following:

```ruby
show do
  panel 'Comments' do
    table_for post.comments, i18n: Comment do
      column :user_name
      column :user_email
      column :content
    end
  end
end
```

`table_for` inside the `show` view is just calling the default HTML builder function, so I think it should call specific DSL for the show view (I guess even a helper would do?) that behaves the same way as the `index` table.

**Comment by seanlinsley** [comment]
This should be resolved by #3909
