### ISSUE TITLE
How to  display flash message on create and update

### ISSUE THREAD

**Issue by NoharaMasato** [activeadmin/activeadmin#6754]
Hi.
In #3628, #3631, how to display flash message is discussed, but solution is now shown.
I want to know how to display flash message on create and update with responders(gem).

**Comment by deivid-rodriguez** [comment]
Hi. Flash messages for update and create are displayed by default. Do you want to customize the text? In that case, I think you need to override these i18n keys: https://github.com/heartcombo/responders/blob/3611f8c95171eaa87122e2e1ada5a3e0695ddd06/lib/responders/locales/en.yml.
