### ISSUE TITLE
STI association loading issue

### ISSUE THREAD

**Issue by asadakbar** [activeadmin/activeadmin#6757]
So I've been struggling with getting a resource to properly load its associations. Most of them are fine except for one that is an sti model. Below is an example

````
class Fruit < ApplicationRecord
  belongs_to :store
end
class Orange < Fruit; end
class Apple < Fruit; end
class Peach < Fruit; end
````
and the key being that ALL of these classes are defined in a single file as it doesn't make sense to have a new file just for one line.

Another file has this

````
class OrangeStore < ApplicationRecord
  has_many :oranges
end
````

Well, in my AA orange_stores.rb file I have

`ActiveAdmin.register OrangeStore do; end`

and whenever I try to load orangestore.oranges in the view or action that I am overriding, AA blows up with

`*** NameError Exception: uninitialized constant OrangeStore::Orange`

The temporary fix was to pull out the `class Orange < Fruit; end` into its own orange.rb file, at which point the association seemed to load properly. But what I really want is to be able to load the Orange class without sticking it in its own file.

Now keep in mind, Rails was able to properly load the Orange class in the console just fine, but AA had trouble finding it. It seems to be using the filesystem to map the associations, and I have yet to find how to define where it should look for them.

I've seen plenty of ways to define the resource class, but my issue is that I need to define where to look for an assocation, as the association I am trying to find is in a different file than its name would suggest.

Thanks!

**Comment by deivid-rodriguez** [comment]
If you can provide a reproducible example or sample application, I'm happy to have a look at it.
