### ISSUE TITLE
Carriage return is being added at the end of every new line in textrea

### ISSUE THREAD

**Issue by mbronek7** [activeadmin/activeadmin#6780]
I do not know if it is a problem with my setup(default) or some kind of misconfiguration
Each new line in textrea ends with `\r\n` like:
```
"\r\n Line 1 \r\n Line2"
````

### Expected behavior

Only new line characters should be added at the end of line.

code:
```
form do |f|
    f.inputs do
      f.description, as: :text
      .....
```
Stack: Rails 6.0.3, Ruby 2.7.2, ActiveAdmin: 2.8.0

**Comment by deivid-rodriguez** [comment]
Not sure why this would happen. Are you on Windows? Any way to reproduce?

**Comment by mbronek7** [comment]
Hi, thanks for your response. No I am on MacOs, and app is dockerized. I can make a repo with reproduction this week.

**Comment by mbronek7** [comment]
Hi @deivid-rodriguez I have created example application with reproduction of this problem:
https://github.com/mbronek7/ad_test

**Comment by deivid-rodriguez** [comment]
Thank you @mbronek7, I'll have a look :+1:.

**Comment by deivid-rodriguez** [comment]
Hi @mbronek7. Apparently this is HTML spec, not related to ActiveAdmin or Rails. Have a look at https://stackoverflow.com/a/14217315/143243!

**Comment by mbronek7** [comment]
Hi @deivid-rodriguez  thank you very much and sorry I did not know this
