### ISSUE TITLE
Libsassc deprecation

### ISSUE THREAD

**Issue by dzmitrys-dev** [activeadmin/activeadmin#6781]
https://sass-lang.com/blog/libsass-is-deprecated
Need to stop using sassc gem and move to node-sass

**Comment by deivid-rodriguez** [comment]
The should be solved once we make `webpacker` the default.

**Comment by javierjulio** [comment]
Well we won't make webpacker default now since that was deprecated too. For the sassc side of things, I'm hoping that https://github.com/tablecheck/dartsass-sprockets can be the intermediate solution for Rails projects still dependent on that and for ActiveAdmin.

**Comment by dkniffin** [comment]
@javierjulio Another option might be https://github.com/rails/dartsass-rails

**Comment by jsspiegel** [comment]
@javierjulio Are you planning on moving off of `sassc` at some point in the near future, or are there no plans for that right now? Unclear whether your closing of this issue means you're not planning to make `webpacker` the default but are still planning on moving off of `sassc`, or whether it means you're not planning on moving off of `sassc` at all.

**Comment by javierjulio** [comment]
Yes. Webpacker support has already been removed. No plans to support Shakapacker either. If you want to move off of `sassc-rails` you can do that now by just using the https://github.com/tablecheck/dartsass-sprockets gem. I've been working on the next major version of ActiveAdmin which will use TailwindCSS and vanilla JS. The jQuery and jQuery UI dependencies have already been removed. The changes are in-development on the master branch.

**Comment by jsspiegel** [comment]
@javierjulio Thank you! Any rough timeline on when that next major version of ActiveAdmin will be released?

**Comment by javierjulio** [comment]
Hopefully by the end of the year. Maybe not a final release but a prerelease.
