### ISSUE TITLE
id_column should not link to show page if policy forbids show?

### ISSUE THREAD

**Issue by adibsaad** [activeadmin/activeadmin#6787]
### Did you find a bug?

I'm using AA with the Pundit adapter. I have a resource and in its policy class, I define `show?` as `false` and `index?` as `true`. I'm able to go to the index page for the resource (which is correct), and when I see the rows of each record for that resource, I noticed the `View` button in the actions column is not visible, which is also correct, since `show?` is `false`. However, the `id_column` still links to the Show page.

### Expected behavior

The ID column should not link to the show page, since the policy does not allow it. It should only show the ID of the record without a link to anywhere.

**Comment by deivid-rodriguez** [comment]
Agreed, a PR would be appreciated :+1:.

**Comment by rahulknojha** [comment]
@deivid-rodriguez I'm working on it.

**Comment by jmschp** [comment]
Hi,

I believe there is more to it than just the link on the `id` column.

Should the user also be block to access the show page, even if we manually  insert the url in the browser?

**Comment by javierjulio** [comment]
We have a PR ready for this and just needs an update with tests. Thank you.
