### ISSUE TITLE
Install fails without rollback in Rails 6+ when sprockets is disabled if webpacker is not explicitly specified

### ISSUE THREAD

**Issue by ghost** [activeadmin/activeadmin#6834]
As a "new" user in a long time, this one bit me...

When installing active_admin in a Rails app with webpacker only:
```
rails new something --skip-sprockets
...
rails g active_admin:install
```

### Actual behavior

... the following error is raised on this and **every subsequent invocation** of `rails`:
```
...railties-6.1.3/lib/rails/railtie/configuration.rb:97:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x00007fa138a01208>
```

... until `config.use_webpacker = true` is set in config/initializers/active_admin.rb...

... leaving the installation in an unfinished/unclean state. Subsequent invocations of `rails g active_admin:install` cannot complete because the routes are already there, and if these are removed, an extra redundant migration is created.

### Expected behavior

`rails g active_admin:install` should probably default to using webpacker in Rails 6+, unless only sprockets is installed. If both are installed, the default should still probably be webpacker in Rails 6+, with `--use_sprockets` as an install option.

If neither sprockets nor webpacker is installed, or the install otherwise fails, the install should **roll back** the installation.

**Comment by deivid-rodriguez** [comment]
Agreed on essentially everything.

**Comment by javierjulio** [comment]
I’d accept a PR for this.
