### ISSUE TITLE
Export custom data in CSV format

### ISSUE THREAD

**Issue by oguzsoft** [activeadmin/activeadmin#6851]
I have a Author and Book model. This relations like in the below.
```
author has many books
book belongs to author
```

In authors page; I can export all authors in CSV format but ı want export all authors and author's book in the one csv file.
The sample output should look like this. 

| Author | Book |
| :------ | ---- |
Jack London | White Fang
Franz Kafka |
George Orwell | 1984
George Orwell | Animal Farm

If author have not a book, book area is  should be blank.
When I filter the authors by the name George Orwell, for example, the output should look like this.

| Author | Book |
| :------ | ---- |
George Orwell | 1984
George Orwell | Animal Farm

I think need change a collection data. How can ı make overwrite default export csv method? Thank you...

**Comment by deivid-rodriguez** [comment]
Hi!

Have a look at https://activeadmin.info/4-csv-format.html, you should see some helpful documentation in there. If you're still having issues, post a question at StackOverflow where a wider community can help you.

Cheers!
