### ISSUE TITLE
NameError in Admin::DashboardController#index

### ISSUE THREAD

**Issue by m-abdurrehman** [activeadmin/activeadmin#6885]
I followed https://activeadmin.info/0-installation.html
and ran `rails g active_admin:install User` as I have already `User` model connected with **devise**

affected/new files include
```
new file:   app/admin/dashboard.rb
new file:   app/admin/users.rb
new file:   app/assets/javascripts/active_admin.js
new file:   app/assets/stylesheets/active_admin.scss
modified:   app/models/user.rb
new file:   config/initializers/active_admin.rb
modified:   config/routes.rb
```

And getting this error after running migration

`NameError in Admin::DashboardController#index`
or
`uninitialized constant Dashboard`

![screenshot-localhost_3000-2021 04 01-18_50_59](https://user-images.githubusercontent.com/59817964/113304208-3d7e0080-931b-11eb-9c27-32abd48801d9.png)

in `routes.rb` related part is

```
  Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? }  do
    mount Sidekiq::Web, at: '/sidekiq'
  end

  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'activity_feeds#index', as: :root
  
  devise_scope :user do
    get :profile, to: 'users#profile'
  end

```
Version details on my side

rails (6.1.3)
devise (4.7.3)
cancancan (3.2.1)
activeadmin (2.9.0)

I am not sure what/where is something wrong.

What can be the issue?

**Comment by joshmn** [comment]
what's your `app/admin/dashboard.rb` look like?

**Comment by m-abdurrehman** [comment]
@joshmn thanks for your follow up.


Here is my `app/admin/dashboard.rb`
```
ActiveAdmin.register_page "Dashboard" do
  menu priority: 1, label: proc { I18n.t("active_admin.dashboard") }

  content title: proc { I18n.t("active_admin.dashboard") } do
    div class: "blank_slate_container", id: "dashboard_default_message" do
      span class: "blank_slate" do
        span I18n.t("active_admin.dashboard_welcome.welcome")
        small I18n.t("active_admin.dashboard_welcome.call_to_action")
      end
    end
  end 
end
```

Is there anything to change?

**Comment by deivid-rodriguez** [comment]
Can you show the result of `rails routes`?

**Comment by m-abdurrehman** [comment]
@deivid-rodriguez I was somehow abled to resolve the issue. thanks

**Comment by SergeyArenzon** [comment]
@m-abdurrehman How did you resolve it?

**Comment by mario-amazing** [comment]
You can override dashboard controller like this:

```ruby
ActiveAdmin.register_page "Dashboard" do
  controller do
    def index
      ...
      super
    end
  end
end
```
