### ISSUE TITLE
`site_title_image` doesn't work with webpack assets

### ISSUE THREAD

**Issue by clinejj** [activeadmin/activeadmin#6898]
### Did you find a bug?

When using a file that is part of the webpack asset pipeline, there is no way to set it as the `site_title_image`. While `site_title_image` does support a proc, it still sends the output to `image_tag` which looks up the Sprockets asset path. This is true even when `config.use_webpacker = true`

### Expected behavior

`site_title_image` should either use the webpacker asset pipeline (`image_pack_tag`) for the title image if `config.use_webpacker` is true, or otherwise update the `site_title_image` to accept a src url which would bypass the asset pipeline.

### Actual behavior

ActiveAdmin fails to render with a `Sprockets::Rails::Helper::AssetNotFound in Admin::Dashboard#index` error if the asset specified for `config.site_title_image` does not exist in the asset pipeline.

### How to reproduce

- Add a file to `app/javascript/images`
- In `config/initializers/active_admin.rb`, set `config.site_title_image` to the filename, and `config.use_webpacker = true`

**Comment by Fs00** [comment]
I got it to work by passing a proc like this:
```ruby
config.site_title_image = ->(_) { asset_pack_path('media/images/your-logo.png') }
```
This is just a workaround though, we should really be able to pass a string when using Webpacker.
`config.favicon` option has a similar issue (#6728), but in that case there is no workaround.

**Comment by june-sky** [comment]
I have fixed this issue, can anyone help to review this [PR](https://github.com/activeadmin/activeadmin/pull/7615)?

**Comment by javierjulio** [comment]
We have a PR ready for this. Thank you.
