### ISSUE TITLE
Devise config doesn't check namespace route options

### ISSUE THREAD

**Issue by ncampos92** [activeadmin/activeadmin#6912]
### Did you find a bug?

We recently changed the path for ActiveAdmin using the route options of the namespace to `new_route` and after the change realized that the login url keeps pointing to the namespace default path instead of the new configuration. Checking how [devise config is generated](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/devise.rb#L10) I found that route options are not taken into account.

### Expected behavior

We expected that the login path for active admin would have changed to `new_route/login`

### Actual behavior

The route stayed the same at `admin/login`

### How to reproduce

1. Change namespace route options
```ruby
config.namespace :admin do |admin|
    admin.route_options = { path: 'new_route', subdomain: '' }
end
```
2. run `rails routes` and the route will keep pointing to the namespace default:
`new_admin_user_session GET        /admin/login(.:format)                                                                          active_admin/devise/sessions#new`

In the meantime we are replacing the config returned by ActiveAdmin directly on `routes.rb` but I would've expected ActiveAdmin to change it.

**Comment by javierjulio** [comment]
Strange this hasn't come up before if others are using this namespace routing feature. If it is an issue it would help to have a PR to update that. Thank you.
