### ISSUE TITLE
I18n::InvalidPluralizationData translation data {:one=>"inregistrare", :other=>"inregistrari"} can not be used with :count => 2. key 'few' is missing.

### ISSUE THREAD

**Issue by lubosch** [activeadmin/activeadmin#6914]
### Did you find a bug?

Pagination does not work in romanian lang.

```
I18n::InvalidPluralizationData
translation data {:one=>"inregistrare", :other=>"inregistrari"} can not be used with :count => 2. key 'few' is missing.
```

### Expected behavior

It should work in romanian lang

### Actual behavior

it throws error 500

### How to reproduce

set RO lang and use paginated_collection.

rails-i18n/lib/rails-i18n/common_pluralizastions/romanian.rb defined 'few' requirement for RO lang

### How to solve

Add 'few' key to config/locales/ro.yml  -> 'active_admin.pagination.entry.few' should exist

**Comment by deivid-rodriguez** [comment]
Pull request appreciated!

**Comment by lubosch** [comment]
but I don't speak romanian :D google translator is enough?

**Comment by deivid-rodriguez** [comment]
I guess a potentially poor translation is better than a runtime error, yeah!
