### ISSUE TITLE
Changing config.authentication_keys to :login breaks Active Admin login

### ISSUE THREAD

**Issue by deanpcmad** [activeadmin/activeadmin#692]
I have setup my application with Active Admin. I have to say it's extremely simple to get running! 
I have set Devise up in my application before I installed and setup Active Admin. I wanted to allow users to login with either username or password so I changed `config.authentication_keys = [ :email ]` to `config.authentication_keys = [ :login ]`. 
Users can login with either their username or password. Going back into active admin, I am unable to login.
It just shows

```
NoMethodError in Active_admin/devise/sessions#new
undefined method `login' for #<AdminUser:0x007fe5d62bc730>
```

Changing the `config.authentication_keys = [ :login ]` back to `config.authentication_keys = [ :email ]`, I am able to login to Active Admin no problems.

**Comment by takgab99** [comment]
@deanpcmad this solution make my day too and saved me from the hell, etc. Thanks! The line attr_accessible was not recognized by my rails, but uncommented it, and works like a charm. :)

**Comment by zorab47** [comment]
@takgab99 What version of Rails are you using?

**Comment by takgab99** [comment]
Rails 5.1.2, Ruby 2.4, I'm using it in Docker
