### ISSUE TITLE
"Please use symbols for polymorphic route arguments" after updating from Rails 6.0.3.6 => 6.0.3.7

### ISSUE THREAD

**Issue by ndbroadbent** [activeadmin/activeadmin#6943]
I have written some integration tests for my app that test some ActiveAdmin pages, and these integration tests have started crashing with this error:

```
     ActionView::Template::Error:
       Please use symbols for polymorphic route arguments.
```

This is being triggered by a call to `id_column` inside an `index` block for a resource page.

I just wanted to post this issue in case other people come across this, but I will continue investigating and try to add more information.

**Comment by ndbroadbent** [comment]
Should probably move the discussion to this issue on the Rails issue tracker: https://github.com/rails/rails/issues/42157

**Comment by ndbroadbent** [comment]
Looks like it's an intentional change to fix a security vulnerability, in this commit: https://github.com/rails/rails/commit/c4c21a9f8d7c9c8ca6570bdb82d64e2dc860e62c

ActiveAdmin might need to be updated to call `to_sym` in a few places

**Comment by ndbroadbent** [comment]
I think the issue is in inherited_resources, and a fix is mentioned here: https://github.com/activeadmin/inherited_resources/issues/665

**Comment by phoet** [comment]
Same thing for adminsitrate, but it appears to be fixed already https://github.com/thoughtbot/administrate/pull/1972

**Comment by deivid-rodriguez** [comment]
This should've been fixed by the latest `inherited_resources` release: https://github.com/activeadmin/inherited_resources/releases/tag/v1.13.0.

**Comment by deepakmahakale** [comment]
Updating `inherited_resources` to `v1.13.0` worked
