### ISSUE TITLE
Pundit settings ignored under namespace

### ISSUE THREAD

**Issue by rjherrera** [activeadmin/activeadmin#6979]
### Did you find a bug?

When using namespaces in the initializer config, AA ignores the configuration for pundit. In particular, both `pundit_default_policy` and `pundit_policy_namespace` are not set correctly for particular namespaces.

If instead of setting it inside the namespace, I specify both settings at root level, it works as expected.

### Expected behavior

I expected the adapter to correctly use the specified policy and namespace inside the namespace configuration and differentiate between them.

### Actual behavior

It uses the default configuration and fails to find namespaced policies.

### How to reproduce

In the initializer I set our config for 2 namespaces:

```ruby
config.namespace :admin do |admin|
  admin.authorization_adapter = ActiveAdmin::PunditAdapter
  admin.pundit_default_policy = "Admin::AdminDefaultPolicy"
  admin.pundit_policy_namespace = :admin
end

config.namespace :staff do |staff|
  staff.authorization_adapter = ActiveAdmin::PunditAdapter
  staff.pundit_default_policy = "Staff::StaffDefaultPolicy"
  staff.pundit_policy_namespace = :staff
end
```

What does work is setting it outside the namespace config, but it is clearly not useful for my use case because it sets the same config for both namespaces:

```ruby
config.namespace :admin do |admin|
  ...
end
config.namespace :staff do |staff|
  ...
end

config.authorization_adapter = ActiveAdmin::PunditAdapter
config.pundit_default_policy = "Staff::StaffDefaultPolicy"
config.pundit_policy_namespace = :staff
```

I've looked in the code of the authorization adapter and it uses the config from `ActiveAdmin.application.pundit_default_policy` and `ActiveAdmin.application.pundit_policy_namespace` to retrieve the policies when needed. I'm not sure if that is what is causing the issue (maybe it needs to take into consideration the namespace and not just `application`), or if it is something different entirely.

**Comment by javierjulio** [comment]
If this is still an issue with the current version, please submit a PR. Thank you.

**Comment by aalyahya** [comment]
@rjherrera 

To address the challenge of managing multiple dashboards with distinct user roles and policy namespaces , I implemented a solution by monkey-patching the ActiveAdmin::PunditAdapter. This allows dynamic setting of the policy class and namespace based on the current user type using Current.user

## Example Setup:
I am working with the following structure:
- Dashboards: admin, customer, provider
- User Types: AdminUser, CustomerUser, ProviderUser
- Policy Directories: Three namespaces under app/policies, each containing a base policy class:
	•	`app/policies/admin/`: Contains Admin::BasePolicy
	•	`app/policies/customer/`: Contains Customer::BasePolicy
	•	`app/policies/provider/`: Contains Provider::BasePolicy

Each dashboard is tied to a corresponding user type and policy namespace.

Below is the code snippet for the implementation:


```ruby
# config/initializers/active_admin_pundit.rb

ActiveAdmin::PunditAdapter.class_eval do
  private

    def default_policy_class
      return if default_policy_namespace.blank?
      "#{default_policy_module}::BasePolicy".constantize
    end

    def default_policy_namespace
      return if Current.user.blank?
      return @default_policy_namespace if @default_policy_namespace.present?

      @default_policy_namespace = Current.user.class.to_s[0...-4].downcase.to_sym
    end
end
```

Hope this helps!
