### ISSUE TITLE
Cannot log into my fresh active_admin part

### ISSUE THREAD

**Issue by Mamunoz42** [activeadmin/activeadmin#6999]
Hello,

I did enter gem ¨activeadmin¨ into my gemfile
After that I did bundle install.
Then I did rails generate active_admin:install
Then rails server and when I try to login with the admin@example.com and password I got this message:

ActiveRecord::StatementInvalid in ActiveAdmin::Devise::SessionsController#create

PG::UndefinedColumn: ERROR: column admin_users.login does not exist LINE 1: SELECT "admin_users".* FROM "admin_users" WHERE "admin_user... ^ : SELECT "admin_users".* FROM "admin_users" WHERE "admin_users"."login" = $1 ORDER BY "admin_users"."id" ASC LIMIT $2 

Rails.root: /mnt/c/Users/Manuel/Documents/.UWU/2021-1/Ingeniería de Software/grupo-31

Manuel

**Comment by rjherrera** [comment]
did you run the migrations? and where did you try to login? in the /admin path in your localhost?

**Comment by tothpeter** [comment]
Same happened here. (localhost)

 A possible reason:
 The devise config in an initializer: `config.authentication_keys = [:login]`

Possible solution:
Add `authentication_keys: [:email]` to the device config in your `AdminUser` class like:

```ruby
# app/models/admin_user.rb

devise :database_authenticatable,
       :recoverable, :rememberable, :validatable, authentication_keys: [:email]
```

Off topic: I'd raise attention in the docs to add `gem 'sassc-rails'` if not using webpack. It could save hours of research for newcomers. Where would one open a PR for this?

**Comment by ajcollins** [comment]
> Off topic: I'd raise attention in the docs to add `gem 'sassc-rails'` if not using webpack. It could save hours of research for newcomers. Where would one open a PR for this?

Your comment saved me those two hours. Thank you!
