### ISSUE TITLE
Should not display any span element for an action item that the user is not able to use

### ISSUE THREAD

**Issue by shanser** [activeadmin/activeadmin#7084]
### Did you find a bug?

ActiveAdmin renders empty `span` elements for actions that the user is not authorized to use. That is a problem when you need to customize the css style of those elements.

### Expected behavior

Render no `span` element inside the `action_items` `div` element

```
<div class="action_items">
</div>
```

Or even no `div.action_items` at all

### Actual behavior

It renders empty span for each action that te user is not allowed to use

```
<div class="action_items">
   <span class="action_item"></span>
</div>
```

### How to reproduce

* Take an app with 2 users with roles, 1 user with `admin` who can CRUD a resource `Post` and another with a role `reader`, who can only read thoses posts.
* Connect with the user `reader`
* Go to the `Post` resource index
* Inspect the dom within `.title_bar .titlebar_right .action_items` 

https://www.loom.com/share/e72c9af9d26344baa0fcc933084cedbb

**Comment by javierjulio** [comment]
Thank you. We have a PR so we'll look to address there. While I don't think this is worthwhile for an empty span tag when one could possibly use the `:empty` to either target it or in combination with `:not` to not apply styles but the PR does just move around the check and would follow what we suggest doing for action items anyway.
