### ISSUE TITLE
Custom filters: error when passed 1 in params

### ISSUE THREAD

**Issue by smbatinsighty** [activeadmin/activeadmin#7090]
when passed 1 in filters it comes as true

**Comment by evanhoward-id** [comment]
I would guess your issue is caused by Ransack as detailed here: https://stackoverflow.com/questions/64149511/wrong-number-of-arguments-given-0-expected-1-in-ransack-scope

**Comment by smbatinsighty** [comment]
thanks  evanhoward-id it works on my side

**Comment by smbatinsighty** [comment]
> I would guess your issue is caused by Ransack as detailed here: https://stackoverflow.com/questions/64149511/wrong-number-of-arguments-given-0-expected-1-in-ransack-scope

thanks  evanhoward-id it works on my side
