### ISSUE TITLE
HTML sanitization can result in improperly formatted page title

### ISSUE THREAD

**Issue by AlexOverbeck** [activeadmin/activeadmin#7132]
### Did you find a bug?
When setting a custom title for an action, the HTML sanitization that takes place can sometimes result in improperly formatted text in the `<title>` element.

### Expected behavior
```ruby
show :title => "Procter & Gamble" do
    # ...
end
```

In the above example, I would expect the resulting page title tag to be as follows:
```html
<title>Procter & Gamble | App Name</title>
```

### Actual behavior
What actually happens is the `&` gets sanitized into an html character code. This results in the title of the page being:
```
<title>Procter &amp; Gamble | App Name</title>
```
The browser displays the string as stated above _("Procter \&amp; Gamble | App Name")_

### How to reproduce
Setting the page title as below:
```ruby
show :title => "Procter & Gamble" do
    # ...
end
```
Will result in the following html:
```
<title>Procter &amp; Gamble | App Name</title>
```
Which displays as such in the browser:
![tab-title-issue](https://user-images.githubusercontent.com/1075489/132706414-8a9c48a1-cc04-484d-ae8e-dd75b813e789.png)

**Comment by antonintouron** [comment]
Hi @AlexOverbeck,

I reproduce this but I have not a problem (with google chrome) : 
<img width="213" alt="Capture d’écran 2021-09-23 à 21 17 54" src="https://user-images.githubusercontent.com/37710765/134569970-4381fe24-2498-496e-b2d0-65c774b5f2bc.png">

Which browser do you use ?

**Comment by antonintouron** [comment]
Hey ! Sorry at the moment I have very little time, can you give more information on github or is it complicated ?
Thank :)

**Comment by AlexOverbeck** [comment]
I was able to both reproduce this issue **and** realize a work around for us. The issue we were having happened because we weren't specifically declaring a title for a given page. In cases where the title isn't specifically set some extra sanitization seems to happen somewhere. We can work around this by manually declaring the page title.

Given a users table with a name attribute. If the user has a name of `Finn&Jake`. When you view the show page for that user, the title ends up being `Finn&amp;amp;Jake` because the ampersand gets escaped twice. If the title is specified `show title: :name`, everything works fine.

I've reproduced this behavior below. _Note the failing test result._
```
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Use local changes or ActiveAdmin master.
  if ENV["ACTIVE_ADMIN_PATH"]
    gem "activeadmin", path: ENV["ACTIVE_ADMIN_PATH"], require: false
  else
    gem "activeadmin", github: "activeadmin/activeadmin", require: false
  end

  # Change Rails version if necessary.
  gem "rails", "6.0.0"
  gem "sprockets", "3.7.2"
  gem "sassc-rails", "2.1.2"
  gem "sqlite3", "1.4.1", platform: :mri
  gem "activerecord-jdbcsqlite3-adapter", "60.0", platform: :jruby
  gem "jruby-openssl", "0.10.5", platform: :jruby
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :active_admin_comments, force: true do |_t|
  end

  create_table :users, force: true do |t|
    t.string :name
  end
end

require "action_controller/railtie"
require "action_view/railtie"
require "active_admin"

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.eager_load = false
  config.logger = Logger.new($stdout)

  config.hosts = "www.example.com"
end

class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers
end

class User < ActiveRecord::Base
end

ActiveAdmin.setup do |config|
  # Authentication disabled by default. Override if necessary.
  config.authentication_method = false
  config.current_user_method = false
end

Rails.application.initialize!

ActiveAdmin.register User do
  show do
    # ...
  end
end

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
end

require "minitest/autorun"
require "rack/test"
require "rails/test_help"

# Replace this with the code necessary to make your test fail.
class BugTest < ActionDispatch::IntegrationTest
  def test_admin_user_title
    user = User.create! name: "Finn & Jake"
    get admin_user_url(user)
    assert_response :success

    document_title = response.body.match(/<title>(.*?)<\/title>/)[0]
    assert(document_title) # The document has a title
    assert_match "Finn &amp; Jake", document_title # The document title contains full_name
  end

  private

  def app
    Rails.application
  end
end
```

**Comment by antonintouron** [comment]
@AlexOverbeck Thank you I understand.

I've just reproduced the problem and there's a bad encoding, I think. I look at it and submit a pull request.
Have a good day :)
