### ISSUE TITLE
HTTP error 414 when filtering

### ISSUE THREAD

**Issue by Sprachprofi** [activeadmin/activeadmin#7134]
When I filter my users by a list of emails, which can get quite long, I get HTTP error 414. Afaik this problem is unavoidable when using GET. Could the filter form be switched to using POST, at least as an option?

**Comment by Fivell** [comment]
@Sprachprofi  i think making filter form to use POST request conflicts with good REST practices, I think better solution is to change database design and move emails in this case to separate database table, and filter by array of IDs instead
