### ISSUE TITLE
Rails 7 installation does not work because of dependencies

### ISSUE THREAD

**Issue by gobijan** [activeadmin/activeadmin#7151]
### Did you find a bug?

Rails 7 alpha 2 is out but is already very usable and will be finally released in less than two months.
Are there any ongoing efforts to support Rails 7?
I forked and messed a little around with dependencies but one thing leads to the other when it comes to allowing more and more dependencies.

### Expected behavior

Active Admin should be usable in Rails 7.

### Actual behavior

Active Admin won't install because of unmet dependencies (railties as a starting point).

### How to reproduce

Just try to bundle activeadmin into a rails 7 app.

**Comment by javierjulio** [comment]
Closing in favor of #7196 where we have a details on different dependencies that will need to be updated to allow Rails 7. Some we own, some we don't.
