### ISSUE TITLE
Can't use the title 'Ad' in an index column

### ISSUE THREAD

**Issue by sdogruyol** [activeadmin/activeadmin#7171]
### Did you find a bug?

Activeadmin doesn't render the column with `Ad` as title of the `:name` field

### Expected behavior

It should render the `Ad` column as the title of the `:name` field

### How to reproduce

```ruby
ActiveAdmin.register Tag do
  index do
    selectable_column
    column 'Id', :id
    column 'Ad', :name # Doesn't render in the ui
    column 'Açıklama', :description
    actions
  end
end
```

**Comment by Boberkraft** [comment]
Maybe its your adblock blocking the column?

**Comment by deivid-rodriguez** [comment]
I think I saw this in the past and it was indeed an adblocker. I'll close this assuming that was the issue, but feel free to reopen if that's not the case.
