### ISSUE TITLE
feature: make display timezone for date/time values in active admin configurable

### ISSUE THREAD

**Issue by DSalko** [activeadmin/activeadmin#7176]
In global applications, it's common to have database and rails timezone to be set to UTC, it would be beneficial to add display timezone settings to active admin configuration as often administrators find it hard to operate in UTC. 

I propose adding `localize_timezone` setting to active admin configuration.

**Comment by varyonic** [comment]
You can roll this yourself, eg. https://thoughtbot.com/blog/its-about-time-zones

**Comment by jshow** [comment]
what is your recommendation for rolling-this-ourselves ? activeadmin provides hooks to format, but not affect timezone changes - we too store in UTC, with hundreds of places where dates are displayed, what is an efficient means to use the existing ruby apis to roll-this-ourselves @varyonic ? In my case we have a hefty-api server setting within the same codebase, so making a rails wide change that cannot effect the api server is required. thanks
