### ISSUE TITLE
Scrollable menu for narrow displays

### ISSUE THREAD

**Issue by DerekK19** [activeadmin/activeadmin#7179]
A new feature to address the issue of wide global navigation menus on a narrow device

### Expected behavior

I would like to be able to have the menu displayed on a single row, which I could scroll left or right to show all available entries

### Actual behavior

I have an ActiveAdmin site with 5 or 6 entries in the global navigation. This makes the menu 800 pixels wide. If I access the site on a phone (with only about 400 pixels for the menu), I have two options: I can have the menu spread over multiple lines (the default behaviour), in which case the layout doesn't look very good and uses valuable phone real estate. Alternatively by modifying css, I can have the menu truncate, in which case I cannot see the right-hand entries.

### How to reproduce

Create a site with 5 or six menu entries. Display the site either on a phone or on a narrow window

**Comment by varyonic** [comment]
Take a look at a resposive [theme](https://github.com/activeadmin/activeadmin/wiki/Themes) like ArcticAdmin.
