### ISSUE TITLE
Fix Rails 7.0.0.alpha2

### ISSUE THREAD

**Issue by wiseleyb** [activeadmin/activeadmin#7197]
Several issues listed. Just creating this issue to track my attempt to fix. Both issues I found were just about Gem dependencies. 

Current issues I found
* https://github.com/activeadmin/activeadmin/issues/7151
* https://github.com/activeadmin/activeadmin/issues/7196

**Comment by baarkerlounger** [comment]
Are there any branches/PRs that can be tested yet?

**Comment by jstrouse** [comment]
I've got the following running in development, but it's causing a hot-reload issue.

gem 'ransack', github: 'activerecord-hackery/ransack'
gem 'inherited_resources', git: 'https://github.com/naveed-ahmad/inherited_resources.git', branch: 'rails7'
gem 'activeadmin', git: 'https://github.com/naveed-ahmad/activeadmin.git', branch: 'rails7'

**Comment by baarkerlounger** [comment]
Looks like I've got some additional Kaminari issues with that but it's a lot closer

```
ActionView::Template::Error (wrong number of arguments (given 2, expected 1)):
    1: # frozen_string_literal: true
    2: insert_tag renderer_for(:index)
  
kaminari-core (1.2.1) lib/kaminari/helpers/helper_methods.rb:111:in `paginate'
arbre (1.2.1) lib/arbre/element.rb:181:in `method_missing'
activeadmin (b4257759b62a) lib/active_admin/views/components/paginated_collection.rb:111:in `build_pagination'
activeadmin (b4257759b62a) lib/active_admin/views/components/paginated_collection.rb:72:in `block in build_pagination_with_formats'

```

**Comment by wiseleyb** [comment]
I think I should close this - I ran into other deal-breaker-issues on Rails 7 for the project I'm on - so we're not doing this yet :(  It didn't seem even close to trivial to get it working when I was checking - would have been a pretty big PR requiring changing dependent gems. Sorry for flaking on this.

**Comment by baarkerlounger** [comment]
@wiseleyb worth keeping this open to track anyway?

**Comment by wiseleyb** [comment]
I probably won't get back to this for months. Sorry - not sure how this
group works. There are a bunch of other Rails 7 issues ... so it's not like
it's unknown or something if that's the concern
