### ISSUE TITLE
Allow turning off selected default actions for index as table

### ISSUE THREAD

**Issue by mattschouten** [activeadmin/activeadmin#7265]
I would like to be able to selectively turn off default actions for the index as table. 

## Situation

There is a model that I don't want to delete from the index.  It's protected from deletion if certain conditions are met, and I don't want to have to show all the data on the index to let a user know whether they can delete it.  I definitely don't want to confuse users (or myself) with a Delete link if the resource can't be deleted.

## Workaround

For what I'm currently doing, I set `defaults: false`, then added `item`s for View and Edit to my index.
```ruby
    actions defaults: false do |resource|
      # Skip the default View / Edit / Delete and re-create View / Edit (no easy way to suppress Delete on its own)
      localizer = ActiveAdmin::Localizers.resource(active_admin_config)
      item localizer.t(:view), resource_path(resource), class: "view_link member_link", title: localizer.t(:view)
      item localizer.t(:edit), edit_resource_path(resource), class: "edit_link member_link", title: localizer.t(:edit)
    end
```

This works fine, but is kind of clunky. 

## Proposed Solution

I'd like to be able to just specify which defaults I turn on or off:
```ruby
actions no_destroy: true
```

(In my head, that would use the implicit defaults for View and Edit, but not show Delete.  Maybe `destroy_off` or `hide_destroy` would be better?)

There'd be similar options for view and edit.  They would be passed along to `defaults` in `index_as_table` and used in the `if` statements.

I'm happy to implement this, if the proposed solution is acceptable.

**Comment by Fivell** [comment]
@mattschouten  https://github.com/activeadmin/activeadmin/blob/b45b1fb05af9a7f6c5e2be94f61cf4a5f60ff3bb/lib/active_admin/views/index_as_table.rb#L383


there is already authorization implemented to conditionally enable/disable each action 
reference https://activeadmin.info/13-authorization-adapter.html

**Comment by mattschouten** [comment]
@Fivell 

First of all, I realize I was not completely clear in my original post--sorry about that!  I want to not show `Delete` on index, but I _do_ want to show `Delete` on show.  That second part didn't make it into the original, even though it was perfectly clear in my head. 

With that clarification and apology up front, here is some more detail.

---

It looks like those lines of code in `index_as_table.rb` check to see whether it is permitted for anyone (or a particular user, depending on how the authorization adapter is written) to read/update/destroy a resource.  The use case for authorization adapters seems to be "do I have permission to read/update/destroy this resource?"

I might be missing something, but I'm not seeing a way to use an authorization adapter to suppress showing `Delete` on the index (table view), but still include a `Delete My Model` button on the show page.  

What I want to do is:

- Do not allow any user to delete `MyModel` from index
   - There is context the user needs to know if it's safe to delete, which isn't easy/appropriate to show on index
   - Because of that, displaying `Delete` on index would confuse users; therefore I don't want `Delete` to be displayed
- Allow (appropriately authorized) users to delete `MyModel` from show
  - On show, the context can be displayed

If I am understanding authorization adapters correctly, `subject` is either a page or a model.  But I very well could be missing something.  Can you help me understand how an authorization adapter would allow `authorized?(ActiveAdmin::Auth::DESTROY, resource)` to return `false` on index, but `true` on show?

**Comment by Skulli** [comment]
I am facing the same problem at the moment. I have a table with options for select fields and the auth-condition for `delete` is `usages.zero?`. The calculation of the usages can be very slow, so thats the reason i want the destroy-action only on the show view and not on the index page.

It would be nice to have something like

    index do
     ...
      actions execpt: [:delete]
    end

You cannot control this with the auth-adapters, since you cannot access the current page.
