### ISSUE TITLE
Form numeric field

### ISSUE THREAD

**Issue by alexkravets** [activeadmin/activeadmin#731]
```
form do |f|
    f.inputs do
        f.input :column_pos, :as => :number
```

having this error:

`undefined method `number_input' for #<ActiveAdmin::FormBuilder:0x007fdd70480120>`

is [NumberInput](http://rubydoc.info/github/justinfrench/formtastic/master/Formtastic/Inputs/NumberInput) supported by active admin?

**Comment by allomov** [comment]
@alexkravets I know it was a time ago, but it may help someone else. Here the input that can add `:number` input to Active Admin:
```ruby
module Formtastic
  module Inputs
    class NumberInput
      include Base
      include Base::Stringish
      include Base::Placeholder

      def to_html
        input_wrapping do
          label_html << builder.text_field(method, input_html_options.merge(type: 'number', style: "width: 100px"))
        end
      end
    end
  end
end
```
