### ISSUE TITLE
Shakapacker support?

### ISSUE THREAD

**Issue by 7vs** [activeadmin/activeadmin#7335]
Is there any chance to have an update in order to support `shakapacker` any time soon?

Rails team has deprecated the `webpacker` gem.

Alternative and until this new gem is supported how could I use the new structure `src` vs `pack` and active admin config as per original instructions?
```
ActiveAdmin.setup do |config|
  config.use_webpacker = true
end
```
Thanks in advance

Update:
The way now shakapacker configure directories by default is with `src` instead of `pack`, and in lines:
https://github.com/activeadmin/activeadmin/blob/b45b1fb05af9a7f6c5e2be94f61cf4a5f60ff3bb/spec/unit/generators/install_spec.rb#L16-L20

**Comment by tagliala** [comment]
Hi, I'm using Active Admin with shakapacker (and previously with webpacker 6rc) without issues, is there any problem you are experiencing?

**Comment by 7vs** [comment]
Hi @tagliala thanks for replying soon.
I'm fairly new to webpacker and shakapacker and I'm currently migrating to the latter.

There are some inconsistency among configs' approaches:
- When using Webpacker:
`app/javascript/packs/active_admin.js`

- what shakapacker documentation (readme) suggests:
```
app/javascript:
  # Only Webpack entry files here
  └── application.js
  └── application.css
  └── src:
  │   └── my_component.js
  └── stylesheets:
  │   └── my_styles.css
  └── images:
      └── logo.svg
```
- and your configuration:
> This is my `app/javascript/active_admin.js`

Initially I tried using the `src` directory to keep `active_admin.rb` + `active_admin` folder but it didn't worked and I started checking in how ActiveAdmin config the assets' path and I found `pack` as a subfolder in the path.
I guess I'll need to find out how can shakapacker and ActiveAdmin work together.
