### ISSUE TITLE
Singleton controllers breaking with authorization scope applied to new records

### ISSUE THREAD

**Issue by agrobbin** [activeadmin/activeadmin#7339]
Initially reported in https://github.com/activeadmin/activeadmin/pull/6884#issuecomment-1042099107 and moved to it's own ticket!

### Did you find a bug?

When attempting to ugprade to AA 2.10, I ran into an issue to do with the changes in #6884. It seems this breaks when working with a ["singleton controller"](https://github.com/activeadmin/inherited_resources#singletons), which is a feature of Inherited Resources. Since [`scoped_collection`](https://github.com/activeadmin/activeadmin/blob/c9695082a328d4f438ee75d7799c6cb54c3907e4/lib/active_admin/resource_controller/data_access.rb#L65-L76) calls out to [`end_of_association_chain`](https://github.com/activeadmin/inherited_resources/blob/f5ceafb10f0ba371e97f9164bc4cff1b887d310b/lib/inherited_resources/base_helpers.rb#L170-L186), it's possible for that to return a single object, rather than a collection-like thing. When that happens, we end up passing that instance in to `apply_authorization_scope`, which is unexpected and will not work properly with the authorization adapter. In the case of Pundit, it will attempt to invoke `Scope#resolve` with that instance, which will not be expecting it as an argument.

### Expected behavior

With a singleton controller and `belongs_to`, the authorization scope should not be applied to the new record instantiation.

### Actual behavior

An error is raised by the underlying authorization adapter due to it being passed an instance rather than a scope/relation.

### How to reproduce

If you run this test case against v2.9.0, it succeeds, but on v2.10.0 (or `master`), it fails.

```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Use local changes or ActiveAdmin master.
  if ENV["ACTIVE_ADMIN_PATH"]
    gem "activeadmin", path: ENV["ACTIVE_ADMIN_PATH"], require: false
  else
    gem "activeadmin", github: "activeadmin/activeadmin", require: false
  end

  # Change Rails version if necessary.
  gem "rails", "6.1.4"

  gem "sprockets", "3.7.2"
  gem "sassc-rails", "2.1.2"
  gem "sqlite3", "1.4.2", platform: :mri
  gem "activerecord-jdbcsqlite3-adapter", "61.0", platform: :jruby

  gem "pundit"
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :active_admin_comments, force: true do |_t|
  end

  create_table :foos, force: true

  create_table :bars, force: true do |t|
    t.belongs_to :foo
  end
end

require "action_controller/railtie"
require "action_view/railtie"
require "active_admin"

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.eager_load = false
  config.logger = Logger.new($stdout)

  config.hosts = "www.example.com"
end

class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers
end

class Foo < ActiveRecord::Base
  has_one :bar
end

class Bar < ActiveRecord::Base
  belongs_to :foo
end

class ApplicationPolicy
  def initialize(user, record)
    @user = user
    @record = record
  end

  def new?
    true
  end

  def create?
    true
  end

  class Scope
    def initialize(user, scope)
      @user = user
      @scope = scope
    end

    def resolve
      scope.all
    end
  end
end

ActiveAdmin.setup do |config|
  # Authentication disabled by default. Override if necessary.
  config.authentication_method = false
  config.current_user_method = false

  config.authorization_adapter = ActiveAdmin::PunditAdapter

  config.pundit_default_policy = 'ApplicationPolicy'
end

Rails.application.initialize!

ActiveAdmin.register Foo do
end

ActiveAdmin.register Bar do
  menu false

  belongs_to :foo

  controller do
    defaults singleton: true
  end

  form do |f|
    f.actions do
      action :submit
      cancel_link [:admin, resource.foo]
    end
  end
end

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
end

require "minitest/autorun"
require "rack/test"
require "rails/test_help"

# Replace this with the code necessary to make your test fail.
class BugTest < ActionDispatch::IntegrationTest

  def test_admin_users
    foo = Foo.create!

    get new_admin_foo_bar_url(foo_id: foo.id)

    assert_response :success
  end

  private

  def app
    Rails.application
  end
end
```

**Comment by javierjulio** [comment]
@agrobbin since we’ve made updates in this area since then, is this still an issue for you?

**Comment by agrobbin** [comment]
@javierjulio I wish I could tell you, but I have not been using Active Admin recently, so I cannot say for sure.

**Comment by javierjulio** [comment]
@agrobbin ok thank you. I haven't used this feature of InheritedResources before so I'm not familiar with what's involved. I would accept a PR to fix this though. Thank you.
