### ISSUE TITLE
A show page does not display a field ends with a "_count" substring

### ISSUE THREAD

**Issue by plashchynski** [activeadmin/activeadmin#7346]
I have a model with some column ends with a "_count" substring. This column doesn't appear on a show page. It should appear as It is a regular column just like any other.

I've figured out that this is because this column filtered out as a counter cache column by the following code in ```ActiveAdmin::Resource::Attributes#counter_cache_col?```

The code simply checks that the column has a name that ends with "_count". On the one hand, this leads to the situation where a regular columns are filtered out. On the other hand, this code will not filter a counter cache column with a custom name that doesn't match "*_count".

**Comment by javierjulio** [comment]
Thank you for submitting a PR for this. We'll update it and take it from there.

**Comment by pdfrod** [comment]
I just ran into this issue and was very confused why my column was showing up. Can this issue be re-opened? It's definitely not fixed yet, and the mentioned PR has seen no movement for more than a year.

**Comment by javierjulio** [comment]
@pdfrod no sorry, we don't reopen an issue if we have acknowledged that we will accept a PR. Fixing this or documenting a workaround will be dependent on your or the community's contribution. I have left comments on that PR and they haven't been addressed. You are more than welcome to open a new PR. Thank you.

**Comment by pdfrod** [comment]
Thanks for the explanation @javierjulio. I'll see if I can get a new PR to address the issue.
