### ISSUE TITLE
Webpacker is deprecated

### ISSUE THREAD

**Issue by jaynetics** [activeadmin/activeadmin#7376]
webpacker has been deprecated (or [retired](https://rubyonrails.org/2022/1/21/this-week-in-rails-rails-7-0-1-webpacker-retirement-and-more-10bad602) as they call it) and is no longer included in rails 7 by default: 

> Only security issues will be considered and there will be no version 6 release of Webpacker

> For applications currently using Webpacker, the first recommendation is to switch to jsbundling-rails with Webpack.

as a consequence, i think activeadmin should no longer suggest integrating with webpacker. i'll push a PR shortly to remove the relevant section from the installation instructions.

perhaps the `use_webpacker` config option should start showing a deprecation warning as well?

**Comment by deivid-rodriguez** [comment]
As far as I understand, there's https://github.com/shakacode/shakapacker which works just fine with ActiveAdmin (as per https://github.com/activeadmin/activeadmin/issues/7335) and will continue to be maintained.

So for now I think I would just clarify that even though still supported, it's no longer included with Rails by default.

**Comment by deivid-rodriguez** [comment]
@jaynetics Can you change #7377 as suggested? Feel free to comment on jsbundling-rails/esbuild too, although maybe @tagliala is in a better position to write that improvement.

**Comment by baarkerlounger** [comment]
JSBundling with webpack is another potential upgrade path from Webpacker. Doesn't look like that works out of the box?

**Comment by tagliala** [comment]
Apologies for the silence, I was going to write a long comment and I've also tried to change instructions at least to shakapacker but then I had to stop

@baarkerlounger yes, it works. I was eventually able to remove shakapacker and make activeadmin work with jsbundling-rails (with some little changes because [I've migrated a webpacker workflow](https://github.com/rails/jsbundling-rails/blob/main/docs/switch_from_webpacker.md)).

I also use sass via webpack, but that should not be needed

### `package.json` dependencies
```json
  "dependencies": {
    "@activeadmin/activeadmin": "^2.11.0",
    "@rails/ujs": "7.0.2-3",
    "css-loader": "^6.7.1",
    "mini-css-extract-plugin": "^2.6.0",
    "sass": "^1.49.9",
    "sass-loader": "^12.6.0",
    "webpack": "^5.70.0",
    "webpack-cli": "^4.9.2",
    "webpack-remove-empty-scripts": "^0.7.3"
  },
```

### `webpack.config.js`

```js
const path = require('path')
const webpack = require('webpack')

const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts')

const mode = process.env.NODE_ENV === 'development' ? 'development' : 'production'

module.exports = {
  mode,
  optimization: {
    moduleIds: 'deterministic'
  },
  entry: {
    active_admin: [
      './app/javascript/active_admin.js',
      './app/javascript/stylesheets/active_admin.scss'
    ]
  },
  output: {
    filename: '[name].js',
    sourceMapFilename: '[name].js.map',
    path: path.resolve(__dirname, 'app/assets/builds')
  },
  plugins: [
    new webpack.ProvidePlugin({
      // jQuery
      $: 'jquery',
      jQuery: 'jquery',
      jquery: 'jquery',

      // Window
      'window.jQuery': 'jquery'
    }),
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 1
    }),
    new RemoveEmptyScriptsPlugin(),
    new MiniCssExtractPlugin()
  ],
  resolve: {
    extensions: ['.js', '.scss']
  },
  module: {
    rules: [
      {
        test: /\.s[ac]ss$/i,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader']
      },
      {
        test: /\.(png|jpe?g|gif|eot|woff2|woff|ttf|svg)$/i,
        type: 'asset/resource'
      }
    ]
  }
}
```

### `app/javascript/active_admin.js`
```js
import '@activeadmin/activeadmin'
```


### `app/javascript/stylesheets/active_admin.scss`
```scss
@import "@activeadmin/activeadmin/src/scss/mixins";
@import "@activeadmin/activeadmin/src/scss/base";
```

**Comment by baarkerlounger** [comment]
@tagliala does that require using `sprockets-rails` alongside jsbundling/webpack? Without it I get `undefined method `assets'` errors.

**Comment by tagliala** [comment]
afaik `js-bundling` is a "proxy" for sprockets (or propshaft now). It just moves webpack compiled files to a folder accessible by sprockets. You can also see that `manifest.js` requires `//= link_tree ../builds`

Ref: https://github.com/rails/jsbundling-rails/issues/83#issuecomment-1033817472

**Comment by KevinBongart** [comment]
FYI, I tried setting up a Rails 7 demo app for [a bug report related to Shakapacker](https://github.com/activeadmin/activeadmin/issues/7399) but noticed this error when running `rails g active_admin:install --use_webpacker --skip-users`

```sh
The file […]/myapp/config/webpack/environment.js does not appear to exist
```

This is because `ActiveAdmin::Generators::WebpackerGenerator` expects `config/webpack/environment.js` to exist, whereas Shakapacker now uses `config/webpack/webpack.config.js`:

```rb
module ActiveAdmin::Generators::WebpackerGenerator
  module Generators
    class WebpackerGenerator < Rails::Generators::Base
      def install_assets
        […]

        insert_into_file Rails.root.join("config/webpack/environment.js").to_s,
                         "const jquery = require('./plugins/jquery')\n",
                         after: /require\(('|")@rails\/webpacker\1\);?\n/

        insert_into_file Rails.root.join("config/webpack/environment.js").to_s,
                         "environment.plugins.prepend('jquery', jquery)\n",
                         before: "module.exports"

        run "yarn add @activeadmin/activeadmin"
      end
    end
  end
end
```

Shakapacker also updates its config from `require('@rails/webpacker')` to `require('shakapacker')`, so the module needs to look like this:

```rb
        insert_into_file Rails.root.join("config/webpack/webpack.config.js").to_s,
                         "const jquery = require('./plugins/jquery')\n",
                         after: /require\(('|")shakapacker\1\);?\n/

        insert_into_file Rails.root.join("config/webpack/webpack.config.js").to_s,
                         "environment.plugins.prepend('jquery', jquery)\n",
                         before: "module.exports"
```

This works and results into this config file:

```js
const { webpackConfig } = require('shakapacker')
const jquery = require('./plugins/jquery')

// See the shakacode/shakapacker README and docs directory for advice on customizing your webpackConfig.

environment.plugins.prepend('jquery', jquery)
module.exports = webpackConfig
```

However, with a brand new app, when visiting `http://localhost:3000/admin/`, I get this error: `Webpacker::Manifest::MissingEntryError in Admin::Dashboard#index`

```
Webpacker can't find active_admin.css in […]/myapp/public/packs/manifest.json. Possible causes:
1. You forgot to install node packages (try `yarn install`) or are running an incompatible version of Node
2. Your app has code with a non-standard extension (like a `.jsx` file) but the extension is not in the `extensions` config in `config/webpacker.yml`
3. You have set compile: false (see `config/webpacker.yml`) for this environment
   (unless you are using the `bin/webpacker -w` or the `bin/webpacker-dev-server`, in which case maybe you aren't running the dev server in the background?)
4. webpack has not yet re-run to reflect updates.
5. You have misconfigured Webpacker's `config/webpacker.yml` file.
6. Your webpack configuration is not creating a manifest.

Your manifest contains:
{
  "application.js": "/packs/js/application.js",
  "entrypoints": {
    "application": {
      "assets": {
        "js": [
          "/packs/js/runtime.js",
          "/packs/js/vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_localhost_por-54b5bb.js",
          "/packs/js/application.js"
        ]
      }
    }
  },
  "js/application.js.map": "/packs/js/application.js.map",
  "js/runtime.js.map": "/packs/js/runtime.js.map",
  "js/vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_localhost_por-54b5bb.js": "/packs/js/vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_localhost_por-54b5bb.js",
  "js/vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_localhost_por-54b5bb.js.map": "/packs/js/vendors-node_modules_webpack-dev-server_client_index_js_protocol_ws_3A_hostname_localhost_por-54b5bb.js.map",
  "runtime.js": "/packs/js/runtime.js"
}
```

Happy to work on a PR to fix the generator if Active Admin plans to support Shakapacker and, if so, I'd love some help around that importing issue for `active_admin.css`. Otherwise, #7377 could also remove the generator.

**Comment by tagliala** [comment]
Hi, Shakapacker (and webpacker 6) do not automatically add CSS support: https://github.com/shakacode/shakapacker/blob/master/docs/v6_upgrade.md, so I think that more packages should be added to package.json by the generator, if we want to serve css assets

Can you share your package.json dependencies?

**Comment by KevinBongart** [comment]
I generated an example app like this:

```sh
rails new example --skip-javascript
cd example
bundle add shakapacker --version "~> 6.1.1"
bundle install
rails webpacker:install
yarn
```

At this point, `./bin/webpacker-dev-server` can compile the assets and the `webpack.config.js` file looks like this:

```js
const { webpackConfig } = require('shakapacker')

// See the shakacode/shakapacker README and docs directory for advice on customizing your webpackConfig.

module.exports = webpackConfig
```

And `package.json` looks like this:

```json
{
  "name": "app",
  "private": true,
  "dependencies": {
    "@babel/core": "7",
    "@babel/plugin-transform-runtime": "7",
    "@babel/preset-env": "7",
    "@babel/runtime": "7",
    "babel-loader": "8",
    "compression-webpack-plugin": "9",
    "shakapacker": "6.1.1",
    "terser-webpack-plugin": "5",
    "webpack": "5",
    "webpack-assets-manifest": "5",
    "webpack-cli": "4",
    "webpack-merge": "5"
  },
  "version": "0.1.0",
  "babel": {
    "presets": [
      "./node_modules/shakapacker/package/babel/preset.js"
    ]
  },
  "browserslist": [
    "defaults"
  ],
  "devDependencies": {
    "webpack-dev-server": "^4.7.4"
  }
}
```

Then installing Active Admin *using the modified generator from my comment above*:

```js
bundle add activeadmin --version "~> 2.11"
rails g active_admin:install --use_webpacker --skip-users
rails db:migrate
rails server
```

The `webpack.config.js` file looks like this:

```js
const { webpackConfig } = require('shakapacker')
const jquery = require('./plugins/jquery')

// See the shakacode/shakapacker README and docs directory for advice on customizing your webpackConfig.

environment.plugins.prepend('jquery', jquery)
module.exports = webpackConfig
```

And `package.json` looks like this:

```json
{
  "name": "app",
  "private": true,
  "dependencies": {
    "@activeadmin/activeadmin": "^2.11.0", <- the only new line
    "@babel/core": "7",
    "@babel/plugin-transform-runtime": "7",
    "@babel/preset-env": "7",
    "@babel/runtime": "7",
    "babel-loader": "8",
    "compression-webpack-plugin": "9",
    "shakapacker": "6.1.1",
    "terser-webpack-plugin": "5",
    "webpack": "5",
    "webpack-assets-manifest": "5",
    "webpack-cli": "4",
    "webpack-merge": "5"
  },
  "version": "0.1.0",
  "babel": {
    "presets": [
      "./node_modules/shakapacker/package/babel/preset.js"
    ]
  },
  "browserslist": [
    "defaults"
  ],
  "devDependencies": {
    "webpack-dev-server": "^4.7.4"
  }
}
```

At this point, `./bin/webpacker-dev-server` fails to compile (`environment` is not defined) because of this line:

```js
environment.plugins.prepend('jquery', jquery)
```

Hope this helps!

**Comment by joker-777** [comment]
@KevinBongart Thanks for your explanation. I somehow get the error `TypeError: base2 is not a constructor`. Did you get it too and how did you resolve it?

**Comment by tagliala** [comment]
Hello, I've edited my previous comment 

https://github.com/activeadmin/activeadmin/issues/7376#issuecomment-1067830592

Because I found an issue with import syntax and

https://github.com/activeadmin/activeadmin/blob/d5ca7b3ec525e811d5b08d102a9ac1b1b0166795/app/javascript/active_admin/ext/jquery-ui.js#L5

Returning a JS error related to `undefined dialog` (because `$.ui` is not defined at that moment)



I'm not a JavaScript developer, so I wasn't able to identify the source of the issue in a reasonable amount of time and switching to require syntax works better for me

**Comment by niklas** [comment]
@tagliala I could resolve the error about `undefined dialog` by:
1. Making sure only one version of jquery is used in your manifest (yarn.lock)
2. it is provided "globally" using the ProvidePlugin
3. the neccessary jquery-ui assets are `require`d *before* `require('@activeadmin/activeadmin')` (but not `jquery` itself, as of point 2).

Then the factory pattern thingy in `a/a..base.js` will get the same `$` as the `jquery-ui` -  and as the rest of your codebase, for that matter. I had discovered I had 2 different versions of  jquery in my yarn.lock. For me, now they have the same version and point to the same jquery "instance", which I verified by setting a custom attribute on it (`$.foo = "bar"`, later `console.log("foo", $.foo)`.

Hope that helps.

**Comment by tagliala** [comment]
Hi @niklas, sorry but I'm not a javascript developer and I can't properly understand

**Comment by javierjulio** [comment]
Webpacker support (and thus the config) has already been removed from the default branch so closing this out. We are migrating to Tailwind CSS for v4. The conversation here seems to have been helpful for many so please feel free to continue commenting here. Also consider opening a discussion and link back here to continue helping one another out. Thank you!

**Comment by jonathandean** [comment]
> We are migrating to Tailwind CSS for v4

❤️
