### ISSUE TITLE
Two namespaces with one Devise model in activeAdmin in rails

### ISSUE THREAD

**Issue by aqib-muneeb** [activeadmin/activeadmin#7382]
I have set Devise in my application. it has a role column ( two roles , admin and student). Now i have set activeAdmin in my application. I login to my app using http://localhost:3000/admin  but i want admin to login from this route and student to log in using http://localhost:3000/student ..
How can I do that ? How can I set student namespace with this already existing devise model and configure it when to use which route on base of role ..
thanks in advance.

**Comment by rslhdyt** [comment]
Just curious, why do you need to make a different namespace? 
If your goal is to show or hide the menu based on the current user role you can utilize the authorization feature.
https://activeadmin.info/13-authorization-adapter.html

but I got this question in SO, hope it helps.
https://stackoverflow.com/questions/12877139/two-namespaces-of-activeadmin

**Comment by deivid-rodriguez** [comment]
Yes, I'm not sure either why two different routes are needed for login? Can you clarify? I'll close this for now, but I'm happy to reopen if it turns out we need to do something about this on the activeadmin side.
