### ISSUE TITLE
active_admin always falls back from https to http during login

### ISSUE THREAD

**Issue by johannesfritsch** [activeadmin/activeadmin#739]
I set up a fresh rails 3.1.0 app and installed active_admin according to the getting-started guide. The entire page has to be SSL encrypted, so there is no http://*. Everything is handled over the secure connection. 

When I access https://localhost/admin it redirects me to http://localhost/admin/login instead of the https one. When I switch back to the https one I am presented with the dashboard. From there on everything works.

**Comment by GalenkoEugene** [comment]
For those, who looking for an Nginx config
```nginx
proxy_set_header  X-Forwarded-Ssl on;
```
