### ISSUE TITLE
JRuby support for Ruby EOL versions

### ISSUE THREAD

**Issue by alejandroperea** [activeadmin/activeadmin#7393]
I have a general question not only for `activeadmin` but also for `arbre` and `inherited_resources` (and a lot of gems in Ruby world). JRuby is supported by those gems, but the latest version of JRuby supports Ruby 2.6.... which EOL is pretty close (31th March).

I'm not sure how this is going to be handled. Supporting EOL Ruby versions could lead in more work for the maintainers and the community but also could be a problem for security reasons (Ruby 2.6 won't be patched anymore).

What do you think about this?

**Comment by deivid-rodriguez** [comment]
JRuby is only supported on a best effort basis. Right now we only have it in our daily CI matrix (so nothing is enforced for every PR), and it's not even succeeding to `bundle install`.

When it's time for dropping Ruby 2.6 support, we can just drop it, JRuby CI can be fixed once it supports newer implementations.

I wouldn't mind dropping support for Ruby 2.6 right now.

**Comment by alejandroperea** [comment]
Thanks a lot for your response @deivid-rodriguez !

One question more 🙏 . When we are going to drop the support for Ruby 2.6, shall we remove JRuby in the CI Matrix or we shall leave it failing in the CI until a new version of JRuby is released and can be fixed?

**Comment by deivid-rodriguez** [comment]
Either way works for me, but I think I would remove it and re-add it in the future if needed.

**Comment by alejandroperea** [comment]
Good! No more further questions from my side, thanks a lot for your answers!

Closing the issue as has been addressed.
