### ISSUE TITLE
RuntimeError in Admin::Dashboard#index with Shakapacker: stylesheet_pack_tag called more than once

### ISSUE THREAD

**Issue by KevinBongart** [activeadmin/activeadmin#7399]
I've recently migrated an app from Rails 6.1 / Webpacker 6 RC to Rails 7 / Shakapacker. I get this error message when visiting the Active Admin root:

```
RuntimeError in Admin::Dashboard#index
Showing /Users/kevin/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/activeadmin-2.11.0/app/views/active_admin/page/index.html.arb where line #3 raised:

To prevent duplicated chunks on the page, you should call stylesheet_pack_tag only once on the page. Please refer to https://github.com/shakacode/shakapacker/blob/master/README.md#usage for the usage guide
```

This happens because Active Admin is calling `stylesheet_pack_tag` for each stylesheet in `ActiveAdmin::Views::Pages::Base`:

```rb
def build_active_admin_head
  within head do
    […]

    active_admin_application.stylesheets.each do |style, options|
      stylesheet_tag = active_admin_namespace.use_webpacker ? stylesheet_pack_tag(style, **options) : stylesheet_link_tag(style, **options)
      text_node(stylesheet_tag.html_safe) if stylesheet_tag
    end

    […]

    active_admin_application.javascripts.each do |path|
      javascript_tag = active_admin_namespace.use_webpacker ? javascript_pack_tag(path) : javascript_include_tag(path)
      text_node(javascript_tag)
    end
  end
end
```

It's a direct result of [this Shakapacker PR](https://github.com/shakacode/shakapacker/pull/19) but there's [ongoing discussion](https://github.com/shakacode/shakapacker/issues/39) about removing the alert for stylesheets, as it's a common use case to have multiple stylesheets but with different options. In Active Admin's case:

```rb
active_admin_application.stylesheets
=> {"active_admin.css"=>{:media=>"all"}, "active_admin/print"=>{:media=>"print"}}
```

The issue should get fixed in the next few days for stylesheets, and I'm happy to look into how it would impact javascripts. This is the list of javascript files for Active Admin in my application:

```rb
active_admin_application.javascripts
=> #<Set: {"active_admin.js"}>
```

Are there use cases where the list includes more than this JS file?

**Comment by deivid-rodriguez** [comment]
Hei! Thanks for the ticket. If I understand correctly, shakapacker 6.2.0 has been released fixing this so this can be closed, right?

**Comment by KevinBongart** [comment]
@deivid-rodriguez Correct! https://github.com/shakacode/shakapacker/pull/82 closes the stylesheet-part of the discussion in https://github.com/shakacode/shakapacker/issues/39 (the rest of the discussion is about JS). I tested it in my app and upgrading to Shakapacker 6.2.0 works!
