### ISSUE TITLE
Slow view performance after upgrading from 2.11.2 to 2.12.0

### ISSUE THREAD

**Issue by f1sherman** [activeadmin/activeadmin#7477]
### Did you find a bug?

All ActiveAdmin pages are much slower after performing this upgrade (e.g. from 1s to 9s per page load)

### Expected behavior

ActiveAdmin page performance should not change significantly

### Actual behavior

All ActiveAdmin pages are much slower after performing this upgrade (e.g. from 1s to 9s per page load)

### How to reproduce

Upgrade from 2.11.2 to 2.12.0.

Based on our instrumentation, the slowdown appears to be in the view layer. What would be most helpful for us to provide to track down this issue?

**Comment by deivid-rodriguez** [comment]
Hello 👋!

The only culprit I could imagine is https://github.com/activeadmin/activeadmin/pull/7336, which was exactly intended to make things more performant 😆, sorry.

Can you verify that reverting that fixes things? Also, can you confirm whether this slow down happens only in index pages, or in every page, and whether turning off pagination fixes it?

**Comment by f1sherman** [comment]
> Can you verify that reverting that fixes things?

Yep! We had to revert in order to get things back to normal.

> Also, can you confirm whether this slow down happens only in index pages, or in every page, and whether turning off pagination fixes it?

I will give this a try and get back to you. Thanks!

**Comment by deivid-rodriguez** [comment]
What I meant is that you try to bisect the specific change in 2.12.0 that caused this issue. In particular, I wanted you to undo this diff: https://github.com/activeadmin/activeadmin/pull/7336/files, to verify whether that's the culprit.

However, from your answers I don't see how it could be related. Are you using `pundit` for authorization by any chance?

**Comment by f1sherman** [comment]
> What I meant is that you try to bisect the specific change in 2.12.0 that caused this issue.

Ah, sorry, I totally missed that. Let me see if I can find time for that.

> Are you using pundit for authorization by any chance?

Yes, we are!

**Comment by f1sherman** [comment]
I bisected (twice, to make sure) and both times this commit was identified:

https://github.com/activeadmin/activeadmin/commit/e1b58dc3c16bde33175ee73ef6acce9cdba005c2

**Comment by deivid-rodriguez** [comment]
@f1sherman Can you check your logs and verify that you're getting a deprecation warning about your policy names? You should have a `pundit_policy_namespace` configured to `<something>`, but also some namespaceless policies including `<something>` in their names.

**Comment by deivid-rodriguez** [comment]
I think this is due to us lacking any policy caching here, I will prepare a patch that you can try.

**Comment by f1sherman** [comment]
Yes, we did see the deprecation warning

**Comment by deivid-rodriguez** [comment]
Ok, that makes sense. Then another way for you to be able to upgrade without having to wait for a fix would be to fix the deprecation :)

**Comment by deivid-rodriguez** [comment]
@f1sherman Can you check whether #7479 restores performance?

**Comment by f1sherman** [comment]
@deivid-rodriguez yes, that seems to have fixed it, thank you! I'll look into fixing the deprecation warning as well.

**Comment by deivid-rodriguez** [comment]
Awesome, I will release a new version soon!

**Comment by f1sherman** [comment]
@deivid-rodriguez yay, thanks so much for the blazing-fast turn-around!!!
