### ISSUE TITLE
Better support for custom forms that build forms similar to block-style form

### ISSUE THREAD

**Issue by ordinaryzelig** [activeadmin/activeadmin#748]
I have a normal, block-style form declared inside my registration:

``` ruby
ActiveAdmin.register User do
   form do |f|
      f.inputs do
        f.input :first_name
        f.input :last_name
        f.input :email
      end
      f.buttons
  end
end
```

I need to make my own custom form, but I just want to build off of this form. But as soon as I make a custom form, I lose the nice cancel link. I dug into the code and found the code for the cancel link in `ActiveAdmin::FormBuilder`. I tried using the form builder, but quickly found out that that builder is meant to be used only in the resource registration, and not so much with templates using ERB, HAML, etc.

It would be nice if a custom form could have access to a builder that would output EXACTLY the output you would get from declaring the form in the registration so that we could just build off of what is 'standard'. As it stands now, I have to copy the code to get the cancel link to get my custom form to look like the 'standard'.

**Comment by fringlesinthestreet** [comment]
Hello there ✋ 

I resolved it by adding

```ruby
<%= f.actions do %>
  <%= f.action :submit %>
  <%= f.action :cancel, wrapper_html: { class: 'cancel'} %>
<% end %>
```

At the end of the `html.erb` file.

PS: I came some years late :P, hope it helps someone!
