### ISSUE TITLE
Show all batch action names in the batch action selector's title

### ISSUE THREAD

**Issue by jadilet** [activeadmin/activeadmin#7516]
It would be good to show all batch action names in the batch action selector's title, so a user doesn’t need to click the batch action selector to show the full list of batch actions.
<img width="1385" alt="Feature" src="https://user-images.githubusercontent.com/6593519/170226136-c792be41-b944-4813-a824-5797fdfa44ba.png">

**Comment by hubertjakubiak** [comment]
It could be useful for some admin users and should be configurable. We had monkey patch to achieve this behaviour as client requested such feature.

**Comment by javierjulio** [comment]
I'm not sure this makes any sense to me. You want to append a delimited list of the drop down options to the drop down button label so they don't have to click the drop down to see all the options? I don't think this is a good idea nor something we'd want to do and support with a button that could break the layout if the text were too large.
