### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by evberrypi** [activeadmin/activeadmin#7520]
### Did you find a bug?

Demo webiste on heroku is [down](http://demo.activeadmin.info/admin)

### Expected behavior
Could try demo

### Actual behavior

![image](https://user-images.githubusercontent.com/20546327/170883535-af31d997-a1b1-43aa-8c69-515d0a821d4a.png)

### How to reproduce

Click link from README

**Comment by julienemo** [comment]
I confirm the website is back
