### ISSUE TITLE
Install isn't creating `admin_users` table.

### ISSUE THREAD

**Issue by coreyward** [activeadmin/activeadmin#753]
I'm trying to install ActiveAdmin on a Rails 3.1 app following the guide. 

```
# Gemfile
gem 'activeadmin'
gem 'sass-rails'
gem 'meta_search, '>= 1.1.0.pre'
```

Followed by:

```
$ bundle
$ rails g active_admin:install
$ rake db:migrate
```

And I get the first 2 migrations to run successfully, but the third fails:

```
==  AddDeviseToAdminUsers: migrating ==========================================
-- change_table(:admin_users)
rake aborted!
An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'myapp_development.admin_users' doesn't exist: ALTER TABLE `admin_users` ADD `email` varchar(255) DEFAULT '' NOT NULL

Tasks: TOP => db:migrate
```

There's nothing _creating_ the `admin_users` table, though there is a migration that appears to get created and then removed in the `install` task called `[datestamp]_add_devise_to_admin_users.rb`.

**Comment by ancaciascaiu** [comment]
`rake db:drop && rake db:create && rake db:migrate` worked for me

**Comment by muhammad-anas-2** [comment]
As I see the error, I tried a lot and finally succeed. The main error is

**PG::UndefinedTable: ERROR: relation "admin_users" does not exist**

This says that the relation admin_users does not exist. It means the migration is trying to change the admin_users which already existed in the table. But actually, it does not exist in the table we have to create it.

**Hence, in the migration file created by active admin /db/migrate/xxxxxxxxxxxxx_add_devise_to_admin_users.rb, replace change with create as change_table :admin_users do |t| with create_table :admin_users do |t|**

Finally, run rails db:migrate
