### ISSUE TITLE
Status Tag with negative value can not be styled positive

### ISSUE THREAD

**Issue by joachim-pryntad** [activeadmin/activeadmin#7540]
### Did you find a bug?

A status_tag with a negative value is always displayed as negative even if a positive class is set via `class: :green`

### Expected behavior

If a class is explicitly set the default class should be removed.

### Actual behavior

If a class is set explicitly, it is added to the default class and it depends on the order in the CSS which one is applied.

### How to reproduce

* Add `status_tag true, class: :no` to an admin view. It is styled as a "no"-status-tag.
* Add `status_tag false, class: :yes` to an admin view, It is still styled as "no".

**Comment by javierjulio** [comment]
This is meant for a status like completed or failed or displaying a Boolean, for example. I don’t think it should be meant to support numeric values like this although if you want it to do that you can already without having that to be built into the component. I wouldn’t accept a change for this.
