### ISSUE TITLE
OAuth login links don't show up when using omniauth with multiple models

### ISSUE THREAD

**Issue by thisismydesign** [activeadmin/activeadmin#7576]
I'm using omniauth with multiple models as described in https://github.com/heartcombo/devise/wiki/OmniAuth-with-multiple-models 

This means I can't put `:omniauthable` in the models via Devise but have to configure omniauth providers separately. This is supported fine by devise but unfortunately `activeadmin` relies on the model setting to show login links

https://github.com/activeadmin/activeadmin/blob/28c3b8a9117cbf2aa6454f285efb05615076d176/app/views/active_admin/devise/shared/_links.erb#L27-L33

I can redefine this view as a workaround, but I was hoping to use the defaults. I would like to have support for this scenario.

**Comment by javierjulio** [comment]
I'm not sure what the issue here is or the proposed solution. If you have a suggestion to resolve this though please consider submitting a PR. Thank you.
