### ISSUE TITLE
Cannot transliterate strings with ASCII-8BIT encoding

### ISSUE THREAD

**Issue by modullar** [activeadmin/activeadmin#7602]
### Did you find a bug?

I have recently upgraded my ruby app version to `2.7.0` and my rails app version to `6.1.6.1`. My app is running well and most of the active admin pages.
However for some pages on active admin, I am getting the following error:

`Cannot transliterate strings with ASCII-8BIT encoding`

I upgraded my ActiveAdmin library gem to the recent `2.13.1` release. I also downgraded it to other releases and the problem persisted.

### Expected behavior

I wonder whether this a compatibility problem or a configuration problem on ActiveAdmin end and if I have to do any extra configuration.
### Actual behavior

The problem appears inside a panel of a show page looking at `production` logs
For example:

```
panel 'X' do
  table_for xs do
    column :a do |x|
      table_for Xs.Ys do
        column X.a do |y|
          link_to y.a, some_path
        end
      end
    end
  end
end

```

The problem happens specifically at `column X.a do |y|`

### How to reproduce

My logs on `production` shows the trace as mentioned before.

However locally and on a firefox browser I get this extra info about the error

```
Invalid CSRF Token

The browser session might have been cleared, or something went wrong.

[More about Better Errors](https://github.com/BetterErrors/better_errors)
```
and the trace of the error ends at: ` activeadmin (2.10.0) app/views/active_admin/resource/show.html.arb, line 3 `

**Comment by deivid-rodriguez** [comment]
Unfortunately this is not enough information to figure this out. Can you share the full backtrace of the error?

**Comment by modullar** [comment]
@deivid-rodriguez 
Server log:

```
File /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/inflector/transliterate.rb line 67 in transliterate
File /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/inflector/transliterate.rb line 123 in parameterize
File /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/core_ext/string/inflections.rb line 220 in parameterize
File /app/vendor/bundle/ruby/2.7.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/table_for.rb line 152 in initialize
File /app/vendor/bundle/ruby/2.7.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/table_for.rb line 35 in new
File /app/vendor/bundle/ruby/2.7.0/gems/activeadmin-2.13.1/lib/active_admin/views/components/table_for.rb line 35 in column
File /app/vendor/bundle/ruby/2.7.0/gems/arbre-1.5.0/lib/arbre/element.rb line 179 in method_missing

```

**Comment by modullar** [comment]
Update with an answer for whom how could stumble across the same problem in the future:


the DSL syntax of later active admin releases has changed, and I had to transform the following exemplary code snippet:
```
panel 'X' do
  table_for xs do
    column :a do |x|
      table_for Xs.Ys do
        column X.a do |y|
          link_to y.a, some_path
        end
      end
    end
  end
end
```

into 

```
panel 'X' do
  table_for xs do
    column :a do |x|
      table_for Xs.Ys do
        column do |y|
          link_to y.a, some_path
        end
      end
    end
  end
end
```
To summarize: It is no longer valid to write: `column X.a do |y|` for a nested table.
