### ISSUE TITLE
rails api mode use activeadmin,undefined method `layout' 

### ISSUE THREAD

**Issue by claf1314** [activeadmin/activeadmin#7607]
`<class:BaseController>': undefined method `layout' for ActiveAdmin::BaseController:Class (NoMethodError)

**Comment by volcanc333** [comment]
[activeadmin/activeadmin] rails api mode use activeadmin,undefined method
`layout' (Issue #7607)

2022년 8월 9일 (화) 오후 12:09, chengliang ***@***.***>님이 작성:

**Comment by deivid-rodriguez** [comment]
This issue needs more information, so I will close it! Feel free to reopen with a proper issue explain the problem, including details on how to reproduce it (which commands should be run). Thanks!
