### ISSUE TITLE
PG::UndefinedFunction: ERROR:  operator does not exist: character varying[] ~~* unknown

### ISSUE THREAD

**Issue by sajjadmurtaza** [activeadmin/activeadmin#7650]
When I tried to filters with **ALLOW** option
<img width="255" alt="Screenshot 2022-09-27 at 12 20 56" src="https://user-images.githubusercontent.com/8552702/192501253-7e57cd3e-753f-495f-a6b0-732070653584.png">

as my table has **allow** field
<img width="698" alt="Screenshot 2022-09-27 at 12 23 29" src="https://user-images.githubusercontent.com/8552702/192501591-62fc6f28-ac6e-4fd3-973b-fcc3ce83f273.png">

It's raising an error 
> PG::UndefinedFunction: ERROR:  operator does not exist: character varying[] ~~* unknown

<img width="1003" alt="Screenshot 2022-09-27 at 12 21 07" src="https://user-images.githubusercontent.com/8552702/192501323-22668081-554e-4f2b-b611-4cac43537727.png">

**Comment by javierjulio** [comment]
You’d have to support this through a custom Ransack filter. We’ve done similar for JSONB fields.
