### ISSUE TITLE
Exclude column on CSV export

### ISSUE THREAD

**Issue by evanlahurd-drizly** [activeadmin/activeadmin#7659]
I checked the docs here for the CSV download functionality: https://activeadmin.info/4-csv-format.html

It appears that you can customize it by adding the columns you want to export, but I think it would be nice to add a way to just exclude columns you don't want, instead of having to list potentially many columns and keep that up-to-date. Would this be possible? Or is there a better way to handle this? Thanks!

**Comment by ray-curran** [comment]
I don't know a built-in way to do this, but you can exclude columns by iterating through them. This would keep you from needing to type out each one

```
  csv do
    Post.column_names.excluding(['title']).each { |c| column c }
  end
```
