### ISSUE TITLE
box-sizing css breaks form layout for hints and checkboxes

### ISSUE THREAD

**Issue by rdlugosz** [activeadmin/activeadmin#7667]
Per the comment in PR #7349, the change to apply a global `box-sizing: border-box` breaks the layout of Hints and Checkboxes on forms.

Example:
https://user-images.githubusercontent.com/13686/166567459-0a3677b4-72a4-4d9b-b582-1fb84a5bf23e.png

Sort-of fix is to add this to your active_admin.scss:
```
body.active_admin {
  *,
  *:before,
  *:after {
    box-sizing: unset;
  }
}
```

**Comment by PatriciaHudakova** [comment]
god bless you, really :D
