### ISSUE TITLE
Caching on index or other pages in Active Admin

### ISSUE THREAD

**Issue by robertoboldi** [activeadmin/activeadmin#7672]
Is it possible to include caching in Active Admin?
I need a full length index without pagination, but the loading time is very long (I have a huge qty of products), but if I try to cache the page in this way:
```
index do
    cache 'products_list' do 
         my columns
     end
end
```

i get error: undefined method `length' for nil:NilClass

have you any way to cache active admin pages?

thank you 
regards

**Comment by javierjulio** [comment]
I don’t advise rendering a full data set with no pagination. From what I know there is no support for this.
