### ISSUE TITLE
BelongsTo with string foreign key saves empty string

### ISSUE THREAD

**Issue by fynsta** [activeadmin/activeadmin#7721]
### Did you find a bug?

When having a belongs_to relation to a primary key that is given by string instead of int, the ActiveAdmin form saves an empty string instead of nil. Of course the second record that is created as such will throw an error on the uniqueness check.

### Expected behavior

A null value should be saved.

### Actual behavior

A string value is saved.

### How to reproduce

Create one class A with a string primary key. Add a second class B with an optional belongs_to association, with the foreign key pointing to the aforementioned primary key. Create a new record of type B without setting the foreign key. 

Verify that the record has "" instead of NULL for the foreign key in the database.

Currently my solution is to write a custom setter that uses the presence of the value. But of course I'd much rather see this fixed generally. Thank you!

**Comment by JewelSam** [comment]
This behaviour really exists but it seems not the problem of active admin. Belongs_to association produces select field which has an empty option (with value "" - blank string). When Rails saving this value to integer field, it's converting to nil, when to string field - it isn't converting to anything.
