### ISSUE TITLE
Allow toggling the "Remove record" button in nested forms

### ISSUE THREAD

**Issue by ldeld** [activeadmin/activeadmin#7726]
This is more of a feature request rather than a bug, since the behaviour is correctly specified in the documentation

### Expected behavior
It would be useful to have the option to hide the "Remove" button on a nested has_many form, just like I can do for the new record button. An example of a use case is having a has_one relation that admins should not be able to destroy, only edit. 

```ruby
active_admin_form_for [:admin, resource] do |f|
  has_many :children,
    new_record: false, # this hides the new record button
    remove_record: false # this should ideally hide the remove record button  
end
```

### Actual behavior

Setting remove_record to `false` just sets the text to be the default ActiveAdmin text.

**Comment by JewelSam** [comment]
I think, [`allow_destroy: false` option](https://activeadmin.info/5-forms.html) does the same, or I understand wrong what you want to do?

**Comment by 5minpause** [comment]
It doesn't work @JewelSam. I have the same issues as @ldeld .
I tried setting the value to false with `accepts_nested_attributes_for allow_destroy: false`
I set it for the has_many active_admin form. The REMOVE buttoin remains.

**Comment by javierjulio** [comment]
I would accept a PR for this. Thank you.
