### ISSUE TITLE
Date validation doesn't work with format agnostic date

### ISSUE THREAD

**Issue by Souravgoswami** [activeadmin/activeadmin#7727]
### Did you find a bug?
When having a date field like this:

```
f.input :date_of_birth, label: 'Date of Birth',
  as: :datepicker,
  input_html: { autocomplete: 'off', value: f.object.date_of_birth&.strftime('%m/%d/%Y') },
  datepicker_options: { dateFormat: 'mm/dd/yy', min_date: "01/01/#{4.years.ago.year}", max_date: "12/31/#{Date.current.year}" }
````

### Expected behavior
This works, but when the date is entered (pasted) in a format like dd-mm-yyyy or such, I want this to still pass to the model level where the model can correct the date.

### Actual behavior
I have a custom date validator, where the `validate_each` is receiving the date. In this case, when format is wrong, the given date value is nil.
The problem with that is that I can't do `errors.add(:date_of_birth, "Date is invalid")` from the model level in case it's actually invalid. 

I can't find any docs or something where I can use a datepicker and still send the request to the backend when the date is not matching the format.
Sure I can do with a little JavaScript, but it would be nice if there's a way to avoid the format while submitting.

**Comment by JewelSam** [comment]
Hi @Souravgoswami
When you use datepicker in activeadmin, users are not allowed to use other symbols than digits and "/". Am I right that you want to allow users to type, for example, "10-12-2022" and transform date on server side? If yes, I think, it's more about Jquery datepicker plugin than activeadmin, and, as you said, it's possible to do with JS (like this https://stackoverflow.com/questions/4347483/jquery-datepicker-that-supports-multiple-formats).
