### ISSUE TITLE
Demo page shows error

### ISSUE THREAD

**Issue by lumpidu** [activeadmin/activeadmin#7748]
### Did you find a bug?

![grafik](https://user-images.githubusercontent.com/734966/207034179-6f0f7009-3094-44b6-a984-9e3f6feaafa6.png)

### Expected behavior

A demo

### Actual behavior

An error

### How to reproduce

go to the demo page

[our bug report template]: https://github.com/activeadmin/activeadmin/blob/master/tasks/bug_report_template.rb

**Comment by ruffy085** [comment]
😂👍⚠️

**Comment by javierjulio** [comment]
We are aware, thank you. We have to migrate from Heroku to another service that offers a free plan for open source projects. Any suggestions for one would be appreciated.
