### ISSUE TITLE
wrong redirect url after delete comment from show page of Comment

### ISSUE THREAD

**Issue by Ivanov-Anton** [activeadmin/activeadmin#7770]
### Description

When I delete comment ActiveAdmin delete them and redirect to deleted comment that is already deleted.

### Expected behavior
AA delete comment from DB and perform redirect to `/admin/comments`

### Actual behavior
AA delete comment from DB and perform redirect to `/admin/comments/{id}`

### How to reproduce

1. visit /admin/comments/{id}
2. click `Delete comment` link
3. AA redirect to deleted comment and return 404 responce 

Your best chance of getting this bug looked at quickly is to provide a **code
sample** or an **executable test case** demonstrating the expected behavior that is not
occurring. Ideally, use [our bug report template] to create the issue. Simply
copy the content of the appropriate template into a .rb file, make the necessary
changes to demonstrate the issue, and **paste the content into the issue
description**.

[our bug report template]: https://github.com/activeadmin/activeadmin/blob/master/tasks/bug_report_template.rb

**Comment by javierjulio** [comment]
I would accept a PR for this. Thank you.
