### ISSUE TITLE
request to remove docs/Gemfile.lock from gem

### ISSUE THREAD

**Issue by thomasdziedzic-calmwave** [activeadmin/activeadmin#7780]
### Did you find a bug?

Our scanner is picking up the bundled Gemfile.lock bundled with this gem and flagging certain gem versions as being vulnerable. I also don't think including a Gemfile.lock in a gem makes sense does it?

### Expected behavior

I expect there to be no Gemfile.lock file

### Actual behavior

There is a Gemfile.lock file installed with the gem.

### How to reproduce

```
% bundle exec gem contents activeadmin | grep Gemfile.lock
/Users/thomas/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/activeadmin-2.13.1/docs/Gemfile.lock
```

**Comment by javierjulio** [comment]
This will be resolved by #7013.
