### ISSUE TITLE
Install issue regarding migrations

### ISSUE THREAD

**Issue by robotmay** [activeadmin/activeadmin#783]
Just ran across something which caused me a bit of a headache; finally figured out what it was!
Installing for the first time I get an exception when generating the assets:

```
rails g active_admin:install
# ...
    generate  active_admin:assets
Mysql2::Error: Table 'fwd_development.active_admin_comments' doesn't exist: SHOW FIELDS FROM `active_admin_comments` (ActiveRecord::StatementInvalid)
# ...
      create  db/migrate/20111124160741_create_admin_notes.rb
      create  db/migrate/20111124160742_move_admin_notes_to_comments.rb
```

Then, when running the migrations I got the same error:

```
rake db:migrate
rake aborted!
Mysql2::Error: Table 'fwd_development.active_admin_comments' doesn't exist: SHOW FIELDS FROM 'active_admin_comments'

Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

I was able to get past the migration error by removing the following two lines from the routes.rb file and putting them back afterwards:

``` ruby
ActiveAdmin.routes(self)
devise_for :admin_users, ActiveAdmin::Devise.config
```

I then successfully generated the assets using  `rails generate active_admin:assets`.

Not sure if anyone else has experienced this but I thought I'd report it anyway :)
I'm using the master branch, by the way.

**Comment by karmajunkie** [comment]
+1 for reopening. I produced the issue by creating a view-backed model on postgresql and customizing the input form. Using  1.0.0.pre and Rails 4.1 on ruby 2.1.4 in my case.

**Comment by clok** [comment]
+1 for reopening. I am seeing a similar issue when attempting to create and migrate a DB after adding a collection to a filter.

Here is the error:
```
ActiveAdmin::DatabaseHitDuringLoad: Your file, app/admin/image.rb (line 15), caused a database error while Active Admin was loading. This is most common when your database is missing or doesn't have the latest migrations applied. To prevent this error, move the code to a place where it will only be run when a page is rendered. One solution can be, to wrap the query in a Proc.Original error message: PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 1: SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LI...
                               ^
: SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1000
...
```

Here is the filter:

``` ruby
filter :user, as: :select, collection: User.order(:last_name, :first_name).find_each.map{|u| ["#{u.full_name} - #{u.email}", u.id]}
```

If I use a very simple filter `filter :user`, the migrations run. The filter code works great if added in after the DB is created and migrated.

**Comment by jdurand** [comment]
@clok in production, ActiveAdmin classes are loaded before the database is connected. As a workaround, you can pass a lambda : 

````
filter :user, as: :select, collection: -> { User.order(:last_name, :first_name).find_each.map{|u| ["#{u.full_name} - #{u.email}", u.id]} }
````

**Comment by yxlwfds** [comment]
me too

**Comment by JMCQ87** [comment]
The workaround by @developer88 works fine for me, but it doesn't really feel like an ideal solution.

**Comment by mfkp** [comment]
FYI I just ran into this as well, I have a line in my model that gets loaded by ActiveAdmin before db migration and made deploy fail.

```ruby
self.columns_hash['time_block_start_time'] = ActiveRecord::ConnectionAdapters::Column.new('time_block_start_time', nil, ActiveRecord::Type::Time.new)
```

Don't think that's something I can solve with a lambda. I'd also love to avoid the @developer88 hack if possible.

**Comment by NazarK** [comment]
ActiveAdmin.routes(self) rescue true

**Comment by frontandstart** [comment]
@Nazark It is help me, and i think more 'tricky' than add for each Collection -> {}, in model a lot of scopes
but can you clarify this?

**Comment by NazarK** [comment]
@frontandstart it is just a shorter version of https://github.com/activeadmin/activeadmin/issues/783#issuecomment-4076929

**Comment by adisos** [comment]
Better version:
```
ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
```

**Comment by ericpeters0n** [comment]
For me, this was triggered rebuilding the TEST database after creating a module included by many AA-managed modules that calls ```self.column_names``` to determine type of table support.

Incidentally, this code itself caused no issues in the DEVELOPMENT environment... extra fun since both dbs are PostGres....

**Comment by Ecco** [comment]
Just got hit by this again. This should be reopened.

**Comment by Ecco** [comment]
Ok, I eventually found the culprit in my own case. I was defining a scope when a model class was being loaded, and this scope was actually hitting the database (moved to a lambda instead).

That being said, I don't really know if this is a problem on AA's side or not :)

I mean, trying to avoid hitting the db when a model class is loaded makes sense, but AFAIK it's not something that Rails enforces. So maybe AA shouldn't either?

**Comment by deivid-rodriguez** [comment]
I haven't had a close look, but the error seems accurate: DB is being hit during load. The question is whether that's deadly for AA or if we can/should recover. I don't really have an opinion since I haven't studied the problem, but since quite a few people requested reopening, and I don't really mind this being closed or open, I reopened it :man_shrugging:.

**Comment by vfonic** [comment]
I just hit this error on our CI where the db is created every time.

Here's the CircleCI db setup step that fails:

```yaml
      - run:
          name: Database Setup
          command: bundle exec rails db:create db:schema:load --trace
```

And here's the code that hits the database and makes this fail:

```rb
# frozen_string_literal: true

module StripAttributes
  extend ActiveSupport::Concern

  included do
    extend AutoStripAttributes

    string_columns = self.columns.filter { |c| c.type == :string }.map(&:name)
    auto_strip_attributes(*string_columns)
  end
end
```

I don't know how to make this code _not_ hit the database.

**Comment by pre** [comment]
Came here to comment that the problem still exists 11 years after this issue was created. 

A common pattern seems to be that when a database is recreated from scratch, ActiveAdmin raises `ActiveAdmin::DatabaseHitDuringLoad` which is raised even in `rake db:schema:load`. 

I haven't investigated into details, but it intuitively it doesn't feel impossible to have some kind of a check in ActiveAdmin to not raise when one is trying to run `rake db:schema:load`. 

My steps to reproduce:
- Re-create the application database in Heroku
- Attempt `rake db:schema:load`
  - Fails with `ActiveAdmin::DatabaseHitDuringLoad`
- Temporarily comment out from config/routes.rb
```
  # devise_for :admin_users, ActiveAdmin::Devise.config
  # ActiveAdmin.routes(self)
``` 
- Push to Heroku & re-run `rake db:schema:load`
  - Succeeds
- Remove the above temporary comment & push again to Heroku

Of course one could add a workaround in config/routes.rb to conditionally not load ActiveAdmin routes. However, a "is this a rake task" kind of detection in ActiveAdmin would make more sense.

**Comment by vfonic** [comment]
This is the "solution" I ended up with:

```rb
Rails.application.routes.draw do
  # ...

  # this is a dirty hack that we need to use, because ActiveAdmin
  # fails for any db call when db or db tables are not ready
  begin
    ActiveAdmin.routes(self)
  rescue ActiveAdmin::DatabaseHitDuringLoad
    # ignored
  end

  # ...
```

**Comment by javierjulio** [comment]
By nature of the DSL it's easy to miss this and not define something in a proc. I'd accept any improvements to the docs but in general this is user error.

**Comment by jprosevear** [comment]
> By nature of the DSL it's easy to miss this and not define something in a proc. I'd accept any improvements to the docs but in general this is user error.

One challenge is that certain things can't be proc'ed - in my case I was using ransackable_filters (based on database introspection) to set filters - if I could do `filters -> { ... }` I would
