### ISSUE TITLE
ActiveAdmin stylesheets are being included on non-AA pages

### ISSUE THREAD

**Issue by duncan-bayne** [activeadmin/activeadmin#7898]
### Expected behavior

I'd expect ActiveAdmin styles to only apply to pages inside the ActiveAdmin UI.  So for example, if I looked at an unstyled button in my site, I'd see something like:

![without-aa-style](https://user-images.githubusercontent.com/65949/225224026-df4a9609-126e-4499-8145-c26d4c9c7381.png)

(in Firefox 110.0).

### Actual behavior

What actually happens is that the ActiveAdmin styles are included in pages outside the ActiveAdmin UI.  So for example, otherwise unstyled buttons look like:

![with-aa-style](https://user-images.githubusercontent.com/65949/225224174-4a1be112-5a29-4354-ab0a-0b9c48538783.png)

(also in Firefox 110.0).

### How to reproduce

1. Create a new, empty, Rails project with `rails n foo && cd foo`.
2. Add required Gems with `bundle add activeadmin devise sassc`.
3. Create an empty scaffold with `rails g scaffold bar`.
4. Add `<button>baz</button>` to `app/views/bars/index.html.erb`.
5. Migrate the database with `rake db:migrate`.
6. Start the Rails server with `rails server`.
7. Browse to http://127.0.0.1:3000/bars.

Note that at this point the otherwise unstyled button will have ActiveAdmin styling applied:

![repro](https://user-images.githubusercontent.com/65949/225225602-f38f8cde-9d58-421a-9450-e9aa06117da2.png)

**Comment by duncan-bayne** [comment]
Please let me know if you'd be interested in a PR to fix this.  I think there have been some conversations in the past about different ways it could be addressed?

**Comment by javierjulio** [comment]
@duncan-bayne yes I think so. I believe this to be expected behavior knowing how the defaults work with Rails and Sprockets. I don't expect us to change how that happens programmatically but I would be happy to accept a PR to at least update the docs to call that out.
