### ISSUE TITLE
ActiveAdmin requires the sassc Gem but doesn't install it

### ISSUE THREAD

**Issue by duncan-bayne** [activeadmin/activeadmin#7899]
### Expected behavior

I'd expect `bundle add activeadmin` to add all required dependencies.

### Actual behavior

If I install ActiveAdmin without installing sassc, it produces an error when I start the server:

```
LoadError in ActiveAdmin::Devise::SessionsController#new
cannot load such file -- sassc
```

I can work around it by just doing `bundle add sassc` (or `bundle add activeadmin sassc` in the first place).

### How to reproduce

1. Create a new, empty, Rails project with `rails n foo && cd foo`.
2. Add required Gems with `bundle add activeadmin devise`.
3. Migrate the database with `rake db:migrate`.
4. Start the Rails server with `rails server`.
5. Browse to http://127.0.0.1:3000/admin

At this point the error will be displayed.

![sassc-error](https://user-images.githubusercontent.com/65949/225227181-8edfc014-e23d-405c-ad54-4c362183c114.png)

**Comment by hfl** [comment]
uncomment gem in default Gemfile.
`gem "sassc-rails"`

**Comment by javierjulio** [comment]
Thanks! There is an expectation that changes are needed especially with how Rails defaults have changed. I'm happy to accept any PR to improve the docs to call this out as its come up before.

**Comment by duncan-bayne** [comment]
@javierjulio Would you like a PR to address this?  Happy to help out.

**Comment by javierjulio** [comment]
@duncan-bayne sure, I would be happy to accept a PR to update the docs in regards to this. Thanks.

**Comment by Ikariusrb** [comment]
This Issue should not be marked closed, as it still represents the current state, and has no fix in the code or the documentation

**Comment by javierjulio** [comment]
@Ikariusrb no sorry, I don’t keep issues open that have been addressed as I will accept a PR for the v3 stable branch to update the docs. I will not accept a PR for the default branch anymore as almost all SCSS is now replaced with Tailwind CSS for a future v4 release.
