### ISSUE TITLE
Activeadmin using wrong translation key 

### ISSUE THREAD

**Issue by maca** [activeadmin/activeadmin#7981]
### Did you find a bug?

Activeadmin using wrong translation keys

### Expected behavior

Activeadmin is attempting to fetch translations using wrong key scope, instead of `de.activeadmin` is using `de`

<img width="1091" alt="Screenshot 2023-06-04 at 16 25 29" src="https://github.com/activeadmin/activeadmin/assets/29857/3520d466-d987-4c98-8f02-0ed6cc31f11b">

This started happening when updating a legacy app

Here the relevant extract from my Gemfile

```
gem 'devise', '~> 4.9', '>= 4.9.2'
gem 'devise-i18n', '~> 1.11'
gem 'devise_invitable'
gem 'activeadmin', '~> 2.12.0'
gem 'active_admin_theme'
gem 'mobility', '1.2.9'
gem 'mobility-ransack'
```

I've updated activeadmin from 2.3.1, and ruby from 2.7 to 3.1

**Comment by javierjulio** [comment]
There's nothing actionable here. With the gems included there's also too many variables/combinations as to what could possibly be wrong. If you can replicate with our bug report template script so it's isolated to just ActiveAdmin that will help and I'll reopen the issue. Thank you.

**Comment by maca** [comment]
I understand, I'll try to replicate or isolate as much as I can.
