### ISSUE TITLE
Filter input validation (value is out of range for ActiveModel::Type::Integer with limit 4 bytes error)

### ISSUE THREAD

**Issue by dssjoblom** [activeadmin/activeadmin#7983]
### Did you find a bug?

Yes, I would classify this as a bug.

### Expected behavior

When applying a filter on the index page, I should not get errors because of invalid user input. I would prefer for the filter to simply fail to find anything.

### Actual behavior

When inputting a long value for an integer field (e.g. 6509786896 for an object id), the filter raises an exception with the message "6509786896 is out of range for ActiveModel::Type::Integer with limit 4 bytes". Without writing a specific error handler, this will result in a status 500. 

Considering that if you input a clearly invalid string value like "foobar" instead, the filter simply fails to find anything, I think this behavior is a bug.

### How to reproduce

Create a basic index page that allows filtering on object id, say `filter :id_equals`, should be easily reproducible.

**Comment by javierjulio** [comment]
Thank you. I've seen this happen on our app, within or outside the admin. I don't think this is a bug and is helpful that it is raised and logged. Swallowing the error wouldn't be acceptable. I believe we have column metadata for each filter so perhaps a remedy could to be to use that and dynamically apply a maxlength attribute at a minimum. Fixing this or documenting a workaround will be dependent on your contribution. I’m open to a PR. Thanks!
