### ISSUE TITLE
ActiveRecord validations breaks page UI

### ISSUE THREAD

**Issue by moneil868** [activeadmin/activeadmin#7987]
I am unsure whether this issue should live in ActiveAdmin or Formtastic so I am creating it in both places. There seems to be some strange behaviour when attempting to submit a form (either edit or create) on a model containing ActiveRecord validations. For example, let's assume we have a `User` model with `validates :name, presence: true`

#### Current Behaviour

<img width="1618" alt="Screenshot 2023-06-20 at 11 36 13 AM" src="https://github.com/activeadmin/activeadmin/assets/8942020/adcbddc5-3820-48df-b533-69b0ba9056f2">

Attempting to submit this form will provide a validation error (as expected), except the page elements are not formatted as they should.

<img width="1619" alt="Screenshot 2023-06-20 at 11 37 22 AM" src="https://github.com/activeadmin/activeadmin/assets/8942020/26302a1e-0dfe-4ca4-a629-c0ebbc835249">

I am unsure why the page is injecting the HTML as plain text, nor I am able to find where this injection takes place.

```
<li class="string input error required stringish" id="user_first_name_input">&lt;label for="user_first_name" class="label"&gt;First name&lt;abbr title="required"&gt;*&lt;/abbr&gt;&lt;/label&gt;&lt;input id="user_first_name" type="text" value="" name="user[first_name]" /&gt;
<p class="inline-errors">can't be blank</p>
</li>
```

The problem appears to occur regardless of the type of validation message. Manually editing the HTML produces, what I can only assume, is the expected result.

```
<li class="string input error required stringish" id="user_first_name_input">
  <label for="user_first_name" class="label">First name</label>
  <input id="user_first_name" type="text" value="" name="user[first_name]">
<p class="inline-errors">can't be blank</p>
</li>
```

<img width="1607" alt="Screenshot 2023-06-20 at 11 43 19 AM" src="https://github.com/activeadmin/activeadmin/assets/8942020/0363e03f-3cc0-4fe5-a1f0-dcf6d3c01ee2">

---

#### Gem versions
- activeadmin (2.13.1)
- formtastic (4.0.0)
- jquery-rails (4.5.0)

---

[Formtastic Issue](https://github.com/formtastic/formtastic/issues/1369)

**Comment by javierjulio** [comment]
We would need more info/code, etc. Nothing to go off of from this. Ideally a repro. If not, I’ll convert to a discussion to leave it open and see if others can help debug.

**Comment by moneil868** [comment]
Thank you for the response! It's in a live/ private project so unfortunately, I won't be able to share the entire code but I can definitely add any information that would help. 

I am also happy to be pointed in the right direction and go down the rabbit hole myself.

**Comment by javierjulio** [comment]
Your best is to reproduce with a sample app that generate the minimum with a sample admin resource and the form code that triggers this. You could use our dev/test app to get started quickly. Check the contributing guide for info.

**Comment by moneil868** [comment]
**Updating for future visitors**:

Used the demo project and replicated the gem versions and `arctic_admin ` theme configurations. The problem does not exist using this setup, doing a deeper analysis.

**Comment by javierjulio** [comment]
Don't use `arctic_admin` theme since that will just monkey patch and override the gem contents. Only use activeadmin to replicate. If you can't, I'll have to close as its likely caused by the theme gem.

**Comment by javierjulio** [comment]
Feel free to post any updates if you have a reproduction or if you found out what the cause. Thank you.
