### ISSUE TITLE
Controller concern include resources reload error 

### ISSUE THREAD

**Issue by allomov** [activeadmin/activeadmin#8003]
### Bug description

I store resources using namespaces and concerns are stored in the same folder (to keep the modular format). I have a namespace called `legacy` with `sessions` and `combined_logs` resources. The namespace also has `concerns` folder with `Admin::Legacy::Concerns::ReactViewHelperMethods` concern. Here is the file tree:

```
app/admin/
└── legacy
    ├── concerns
    │   └── react_view_helper_methods.rb
    ├── combined_logs.rb
    └── sessions.rb
```

Both `combined_logs` and `sessions` include `Admin::Legacy::Concerns::ReactViewHelperMethods` concern in the following way:
```ruby
ActiveAdmin.register(::Legacy::Models::Sessions) do
  controller do
    include ::Admin::Legacy::Concerns::ReactViewHelperMethods
  end
end
```

After Rails app files are changed in development mode the next request to the server causes the error `NameError (uninitialized constant Admin::Legacy)` and after that `Error during failsafe response: Devise could not find the `Warden::Proxy` instance on your request environment.`.

I've tried different combinations with `require_relative` and include/extend modules, but it does not help. It appeared that the block in `controller` method in the resource declaration has different execution contexts with the situation when the app is reloaded after the file changes.

### How the error is fixed

The only solution that I've found is renaming the files that cause the error to have a name that goes after the file it depends on in the case of alphabetical order. With the example above the renamed files for working configuration will look like the following:
```
app/admin/
└── legacy
    ├── concerns
    │   └── react_view_helper_methods.rb
    ├── session_logs.rb
    └── sessions.rb
```

### Expected behavior

After the app code is reloaded no error is caused.

**Comment by javierjulio** [comment]
Thank you. Sorry, I've not done this before so I'm not familiar. Fixing this or documenting a workaround will be dependent on your contribution. I’m open to a PR to resolve it if possible. In the meantime though it sounds like you have a temporary workaround which is good. Thanks.
