### ISSUE TITLE
Duplicate JavaScript on the page/hard error when using Shakapacker

### ISSUE THREAD

**Issue by Fs00** [activeadmin/activeadmin#8011]
I've recently tried to migrate our ActiveAdmin application from Webpacker 5 to Shakapacker 6, but in the end I gave up due to the following problem.
In our ActiveAdmin configuration, we import a custom JavaScript pack using `register_javascript`:
```rb
ActiveAdmin.setup do |config|
  config.use_webpacker = true

  config.register_javascript 'admin'

  [...]
end
```
With Shakapacker, this causes part of the JS bundle to be duplicated on the page (in our case we noticed it because VueJS was being initialized two times), because ActiveAdmin calls `javascript_pack_tag` once for each script (see #7399) which is [incorrect as per Shakapacker docs](https://github.com/shakacode/shakapacker#view-helpers-javascript_pack_tag-and-stylesheet_pack_tag) and even [raises a hard error on newer versions of Shakapacker](https://github.com/shakacode/shakapacker/blob/94f47bc8bed39db1e2db0f2892aae58e4ffb1d4c/lib/shakapacker/helper.rb#L99-L102).

The same problem exists for `stylesheet_pack_tag`, even though in that case it seems to be tolerated by Shakapacker and doesn't cause much trouble (see discussion in #7399).

### Expected behavior

ActiveAdmin should call `javascript_pack_tag` and `stylesheet_pack_tag` only once, passing all packs to the method call.
It seems that [even Webpacker 5.x supports calling those methods the recommended way](https://github.com/rails/webpacker/blob/5-x-stable/lib/webpacker/helper.rb#L80).

### Actual behavior

ActiveAdmin calls `javascript_pack_tag` and `stylesheet_pack_tag` once for each pack, causing duplicated JS (and potentially CSS) chunks to be added to the page.

**Comment by javierjulio** [comment]
Hi Francesco. Thank you. Sorry about that. I'd suggest looking at #7376 where others have shared using cssbundling-rails and jsbundling-rails with the current version of ActiveAdmin successfully which is great to see and would be worth considering if you don't want to remain on webpacker. I've already started work on the next major ActiveAdmin version which will rely on cssbundling-rails and jsbundling-rails with TailwindCSS and Flowbite. So with that, there will be no support for webpacker or shakapacker. Thanks.

**Comment by Fs00** [comment]
Thanks @javierjulio for the response. That's a bit sad to hear because migrating our project to js/cssbundling-rails won't be easy, however it's good to know that ActiveAdmin will get a nice tech refresh.
Keep up the good work!

**Comment by javierjulio** [comment]
You're welcome and thank you for understanding. I know it's difficult. Know that on the our side it's the same. For us it's a burden to have to maintain different asset management integrations. There are few of us left to maintain ActiveAdmin, so I have to make some tough calls. Feel free to share how any migration goes for you in that issue I linked as others have been kind to share and reply. Thanks Francesco.

**Comment by javierjulio** [comment]
@Fs00 @niklas I've been making improvements here and wanted to let you know that I think with v4 you should be able to use Shakapacker without relying on ActiveAdmin for the necessary config. I'm replacing many of our html head and assets related configs with simple partials which means you can easily replace the tags for CSS, JS, favicon, etc. with Shakapackers' `*_pack_tag` helpers. So if you don't want to use cssbundling-rails or jsbundling-rails, you shouldn't have too. Just the library won't support it out of the box but should give you the simple overrides for doing so. I guess at that point you could even still use webpacker if you wanted. All around, it should be an improvement. Hopefully this helps ease some concern. Thanks.

**Comment by Fs00** [comment]
In the end we migrated our application to jsbundling-rails (and I think it's been worth it), but this change is very welcome nonetheless! Out-of-the-box support for customization via partials makes the setup way more Rails-y and flexible 🙂

**Comment by javierjulio** [comment]
@Fs00 that's great news! Yes, I think it's worth it too, at least having gone through that same switch with ActiveAdmin. I'm glad you think the partials customization will be good. Thank you again for the support.
