### ISSUE TITLE
Add an option to NOT show a count for a given scope.

### ISSUE THREAD

**Issue by MrJoy** [activeadmin/activeadmin#804]
Not all scopes are cheap to compute a count for, even if they are useful to expose in the admin UI.

A configuration option that allows us to disable the count for a given scope would be enormously useful.

**Comment by sadfuzzy** [comment]
Thanks!

**Comment by knagode** [comment]
Any progress here? Would love this feature as well ..

**Comment by javierjulio** [comment]
@knagode what exactly is missing? You can disable scope count per scope and also disable the pagination total count.

**Comment by knagode** [comment]
@javierjulio Nice. I see that `show_count ` option was actually merged into master.
