### ISSUE TITLE
documentation does not mention newer authorization action types

### ISSUE THREAD

**Issue by fwolfst** [activeadmin/activeadmin#8046]
Since 2.14 and https://github.com/activeadmin/activeadmin/pull/6535 , there are more fine grained authorization action types (`:new`, `:edit`, ...).

These are not reflected in
https://activeadmin.info/13-authorization-adapter.html#setting-up-your-own-authorizationadapter .

**Comment by javierjulio** [comment]
Thanks Felix. I'm not too concerned with that now since it's not something I see widely needed so it's not pressing. Updating the documentation will be dependent on your or the community's contribution. We are open to a PR to resolve it. Thanks!
