### ISSUE TITLE
Cannot use block for "create" CanCan ability

### ISSUE THREAD

**Issue by tf** [activeadmin/activeadmin#8067]
Starting with #6884 in version 2.10, authorization scope is also [applied when building or creating new records](https://github.com/activeadmin/activeadmin/pull/6884/files#diff-3b88c5c40d754986abc705be8355cd54a0ffde14944acfba72b6e7de0f5b4eabR131).

The way I understand it, this is meant to ensure defaults are set correctly when using Pundit scopes. When instead using the CanCan adapter, it used to be possible to define the `:create` ability with a block:

```ruby
  can :create, User do |user|
    ...
  end
```

Since 2.10 this now leads to an error of the form:

```
CanCan::Error:
  The accessible_by call cannot be used with a block 'can' definition.
```

This happens since ActiveAdmin now calls `accessible_by` when applying the authorization scope for the `create` action. One workaround is to add a no-op scope to the ability, but this looks rather confusing:

```ruby
  can :create, User, User.all do |user|
    ...
  end
```

For my application, I'm considering patching `CanCanAdapter` to make `scope_collection` no-op for the `:create` action.  The pundit adapter also still [contains a comment](https://github.com/activeadmin/activeadmin/blob/a6d8d453cab58123b77c3dce3a275f45f7c78ccb/lib/active_admin/pundit_adapter.rb#L22) saying that `scope_collection` is only ever called in the index/read case, which does not hold true anymore.

**Comment by javierjulio** [comment]
Thank you Tim. I don't use CanCan so I'm not familiar with it. It's difficult to maintain multiple integrations like this and can see how they would deviate over time and cause bugs. Fixing this and/or documenting a workaround will be dependent on your or the community's contribution. It sounds like you have multiple proposals here. We are open to PRs to resolve it. Thanks.
