### ISSUE TITLE
Nested menu items are rendered top-level

### ISSUE THREAD

**Issue by dssjoblom** [activeadmin/activeadmin#8078]
### Did you find a bug?

We are still encountering the behavior described in this issue: https://github.com/activeadmin/activeadmin/issues/5712

### Expected behavior

The menus should be rendered as expected, with nested menu items being nested under the appropriate parent menu.

### Actual behavior

At times the nested menus are rendered on the top-level instead, as described in the linked issue (#5712). When the bug appears, the menus are randomly rendered correctly/incorrectly on page load. Restarting the servers solved the issue for us (temporarily, I'm assuming it can reappear at any time).

### How to reproduce

This is not easy to reproduce, in fact, in the same code base, this is the first time we have encountered the issue in 5-6 years in production.

### Info

ActiveAdmin version: 2.13.1
Rails version: 6.1.7.6
Ruby version: 3.1.4

**Comment by maokomioko** [comment]
Can confirm this happening to us also. 
We use puma as web server running on pods in kubernetes. 

I tried catching this in development (also experimented with eager_load option), but no luck. 
Reproducible in production all the time. 

ActiveAdmin v3 (latest from master branch).

**Comment by javierjulio** [comment]
Thank you. Your best bet to start here is to have a reproduction, otherwise there's nothing actionable. It could be related to code loading or a threading issue. Fixing this or documenting a workaround will be dependent on your or the community's contribution. We are open to a PR to resolve it. Thanks.

**Comment by javierjulio** [comment]
@maokomioko if this is reproducible for you all the time, can you please test @dssjoblom change in #8132 and see if that resolves it? Thank you.
