### ISSUE TITLE
"Comments" menu item is still shown even though comments are disabled globally / everywhere

### ISSUE THREAD

**Issue by rusterholz** [activeadmin/activeadmin#8081]
## Bug Description

We have disabled comments in our initializer file _and_ also for every resource, but we still see the "Comments" menu item rendered:

<img width="701" alt="Screen Shot 2023-09-29 at 1 13 49 PM" src="https://github.com/activeadmin/activeadmin/assets/1099426/fa19c424-f9aa-49d7-904f-40fdf95f54f3">

Our initializer (with comments removed for brevity) looks like:

```ruby
Rails.configuration.after_initialize do
  ActiveAdmin.setup do |config|
    config.site_title = "Fulfillment Processing (#{Rails.configuration.x.skyline_environment.titleize})" # our internal environment name
    config.authentication_method = :authenticate_user!
    config.current_user_method = :current_user
    config.logout_link_path = :logout_path
    config.comments = false # this line is expected to disable the entire comments system including the menu
    config.batch_actions = true
    config.filter_attributes = %i(encrypted_password password password_confirmation)
    config.localize_format = :long
  end
end
```

If you click on the "Comments" menu item, the resulting page errors out (as expected since the feature is nominally disabled).

Just for sanity, we also attempted to disable comments for every resource individually (adding `config.comments = false` to every `ActiveAdmin.register` block), but this did not change the behavior observed above.

Confusingly, this behavior is only observed when running in a deployed, "production-like" kubernetes environment -- when running the exact same docker image on a local machine via docker-compose, it works as expected (the menu is not shown). Is there some env var that might be overriding the initializer somehow?

### Possibly Related

This behavior started when we first added a new resource file that is intended just to redirect requests to `/admin/orders/:id` (e.g. a show page for Orders) to `/admin/process_instances/` with some query parameters (e.g. an index page for ProcessInstances). This is because this app does not have a model named Order, but each ProcessInstance has an order_id. The content of that new file is:

```ruby
ActiveAdmin.register ProcessInstance, as: "Order" do # note that ProcessInstance is also registered separately on its own
  menu false

  member_action :show, method: :get do
    redirect_to admin_process_instances_path(
      scope: :all, order: :started_at_asc, q: { order_id_eq: params[:id] } # query params to filter ProcessInstances for the given Order
    )
  end

  controller { def find_resource = Object.new } # short-circuit resource loading because Orders don't exist in this app

  config.comments = false # as noted above, we added this in a debugging attempt, but it had no effect
end
```

Is there anything in this new file that would be known to break the disabling of the comments system? I'll definitely concede that the `controller { def find_resource = Object.new }` is a little unorthodox, but it's just to allow _something_ to be returned as the `resource` so that the `member_action` block can ever execute. It's hard for me to imagine that this would be interacting with the comments system in any way, but if you think of a reason it would, let me know.

### Expected Behavior

We expect that by setting `config.comments = false` in our initializer, the "Comments" menu would be disabled and would never render (regardless of any other settings or configuration).

### Actual Behavior

The "Comments" menu is rendered (with a broken URL that goes to an error page).

### How to Reproduce

The files provided above _appear_ to be enough to reproduce the issue on our end, but because this does not occur in local testing, there's probably something we're missing. Let me know if any specific information would prove useful in narrowing down the issue.

**Comment by javierjulio** [comment]
Thank you Andy. Your best bet to start here is to have a reproduction. It could be related to what you suggest as the possible related cause so I would recommend starting there to see what you find or possibly with how the menu is built and how Comments plays into that. Fixing this or documenting a workaround will be dependent on your or the community's contribution. We are open to a PR to resolve it. Since this is also asking a support question, I would suggest creating a post in Discussions for this. Others have been using that to receive help. Thanks.
