### ISSUE TITLE
Support for Rails 7.1

### ISSUE THREAD

**Issue by jgmontoya** [activeadmin/activeadmin#8090]
Hey! Rails 7.1 is out. I was wondering whether support for it in activeadmin is planned and just generally curious of how the changes needed to support it compare to those made to support rails 7 (https://github.com/activeadmin/activeadmin/pull/7235)

Thanks for the awesome work you do with ActiveAdmin!

**Comment by tagliala** [comment]
Ref:
- [ ] https://github.com/activeadmin/arbre/pull/537
- [ ] https://github.com/activeadmin/inherited_resources/pull/873

**Comment by jgmontoya** [comment]
I see both of them are merged now! It's amazing to see this kinda thing moving fast!!

**Comment by daande** [comment]
Now that Rails 7.1 support has been added can we get a release cut 😄 🚀

**Comment by gap777** [comment]
We're blocked upgrade to Rails 7.1 pending this work; any ETA? There's some new features of Rails we're very excited to embrace.

**Comment by gdonald** [comment]
Blocked on my Rails 7.1 upgrade.

**Comment by paulhklam1122** [comment]
Can we make another version release to get this out please?

**Comment by gdonald** [comment]
I guess Rails scaffolding in the meantime.

**Comment by gap777** [comment]
Greg— I don’t understand. Can you explain further ?On Oct 18, 2023, at 6:12 PM, Greg Donald ***@***.***> wrote:﻿
I guess Rails scaffolding in the meantime.
