### ISSUE TITLE
Undefined mixin 'global-reset' -- Rails 3.1 precompile

### ISSUE THREAD

**Issue by ghost** [activeadmin/activeadmin#810]
Precompiling assets on Rails 3.1 gives the following error with ActiveAdmin:

```
Undefined mixin 'global-reset'.
  (in /home/acessor/.rvm/gems/ruby-1.9.2-p290/gems/activeadmin-0.3.4/app/assets/stylesheets/active_admin/_base.css.scss)
```

**Comment by phil-monroe** [comment]
Sorry to bring this thread from the dead, but I just debugged this problem with a rails 4.2 app and found a different issue. Somewhere in the project I found a line that listed all active admin assets for pre-compilation. I'm assuming that this throws off sprockets/sass when compiling dependencies and things get compiled out of order. Just an FYI for people that may still have issues.

```
Rails.application.config.assets.precompile += %w( active_admin/*.* )
```

Be sure something like that does not exist!

**Comment by notunderground** [comment]
Adding 

Rails.application.config.assets.precompile += [/(^[^_\/]|\/[^_])[^\/]*$/]

to config/initializers/assets.rb solved this issue for me.

**Comment by chaostheory** [comment]
This is still an issue and I am not using any wildcards in assets.rb.

**Comment by seanlinsley** [comment]
@chaostheory please post an example Rails app that can reproduce the error

**Comment by chaostheory** [comment]
@seanlinsley I will try but it will take awhile. I forgot to mention that I've also tried using your solution and @notunderground 's solution (separately) as well.

**Comment by NeMO84** [comment]
@jarrodrobins' solution is the only one that worked for me.

**Comment by zirexba** [comment]
@jarrodrobins Thanks!
