### ISSUE TITLE
ActiveAdmin - Error on boot

### ISSUE THREAD

**Issue by YogiBear52** [activeadmin/activeadmin#8121]
### Did you find a bug?

```

ruby '3.2.2'
gem 'activeadmin',            '~> 3.1.0'
gem 'devise',                 '~> 4.9.3'
gem 'rails',                  '~> 7.1.0'



.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activeadmin-3.1.0/lib/active_admin/devise.rb:54:in `<module:Devise>': uninitialized constant Devise::SessionsController (NameError)

    class SessionsController < ::Devise::SessionsController
....
....
....
```

### Expected behavior

It worked before with activeadmin  3.0.0 and rails 6.x

[our bug report template]: https://github.com/activeadmin/activeadmin/blob/master/tasks/bug_report_template.rb

**Comment by javierjulio** [comment]
Thank you. Sorry, there isn't enough to go off from this report. Since you mentioned it worked with Rails 6, I take it you upgraded and Rails included important changes around code reloading from 6 to 7.
