### ISSUE TITLE
Update action does not call `authorize_resource!` after assigning attributes 

### ISSUE THREAD

**Issue by vc-jl** [activeadmin/activeadmin#8141]
When creating new resources, `build_resource` is called which authorizes the new resource by calling `authorize_resource!`:
https://github.com/activeadmin/activeadmin/blob/ccdf0d7ff54db1324fc5cd1e6ef831ab47196c42/lib/active_admin/resource_controller/data_access.rb#L115-L125

This is not done when updating resources. `update_resource` is called and there is no authorization:
https://github.com/activeadmin/activeadmin/blob/ccdf0d7ff54db1324fc5cd1e6ef831ab47196c42/lib/active_admin/resource_controller/data_access.rb#L170-L176

This may lead to a situation, where we can inject data into resources that make them unauthorized for us and authorized for somebody else, who should not be authorized. A scenario might be, where a resource has a `user_id` and I am authorized to manage this resource if and only if my `User` has the same `id`. I would not be able to create a resource with a different `user_id`, because `build_resource` prevents me from doing so. What I could do, is forging the `user_id` to something else when submitting the update form.

My suggestion is to add `authorize_resource!` to `update_resource` after assigning attributes. I could provide a PR if desired.

**Comment by javierjulio** [comment]
@vc-jl thank you. Sorry, this is unnecessary because `build_resource` and also `resource` already does this for all member actions.

https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/resource_controller/data_access.rb#L78-L97

**Comment by vc-jl** [comment]
@javierjulio The code you are referencing is only called *before* assigning attributes in `update`. I can assign values that lead to the resource being saved into other authorization realms. For `create`, it is also done after assignment, which I would also expect from `update`.

**Comment by javierjulio** [comment]
Yes and I see from InheritedResources that there probably wouldn't be much way around it so it. Can you please show how you can update a value a user shouldn't have access too based on a policy?

**Comment by vc-jl** [comment]
@javierjulio My suggestion would be to modify `update_resource` like this:

```ruby
 def update_resource(object, attributes) 
   object = assign_attributes(object, attributes) 
   authorize_resource! object 
  
   run_update_callbacks object do 
     save_resource(object) 
   end 
 end
```

This would make the most sense from my point of view. But I still may be misunderstanding how authorization is supposed to work and what workflow this may break. Any comments? Thanks a lot!

**Comment by javierjulio** [comment]
So you don’t know if this is an issue you are running into? That’s why I asked about how you are using it to bypass authorization on a policy for an update? I’m interested in seeing the actual issue being triggered with something you encountered, not a suggestion or idea. You could try our bug report template script to reproduce. You should be able to implement the fix yourself to vet it, at the least. Thanks!

**Comment by vc-jl** [comment]
@javierjulio I'm sorry, I misread your question. It is certainly an issue I am experiencing, but I still don't know if there is a bug or my assumptions on how authorization should work is accurate. Please find my failing test case below.

My scenario is that I am allowed to manage `posts` with `author_ids` `1` and `2`. I cannot create, see or edit `posts` with another ID. What I can do, is update a `post` to have a different `author_id`.

Thanks again!

### Expected behavior
I think I should not be able to set the `author_id` in my test case to something I am not authorized to.

### Actual behavior
I am able to update a resource such that I am not authorized to use it anymore.

### How to reproduce

```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Use local changes or ActiveAdmin master.
  if ENV["ACTIVE_ADMIN_PATH"]
    gem "activeadmin", path: ENV["ACTIVE_ADMIN_PATH"], require: false
  else
    gem "activeadmin", github: "activeadmin/activeadmin", require: false
  end

  # Change Rails version if necessary.
  gem "rails", "~> 7.0.0"

  gem "sprockets", "~> 3.7"
  gem "sassc-rails"
  gem "sqlite3", platform: :mri
  gem "activerecord-jdbcsqlite3-adapter", platform: :jruby

  # Fixes an issue on CI with default gems when using inline bundle with default
  # gems that are already activated
  # Ref: rubygems/rubygems#6386
  if ENV["CI"]
    require "net/protocol"
    require "timeout"

    gem "net-protocol", Net::Protocol::VERSION
    gem "timeout", Timeout::VERSION
  end
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :active_admin_comments, force: true do |_t|
  end

  create_table :users, force: true do |t|
    t.string :full_name
  end

  create_table :posts, force: true do |t|
    t.integer :author_id
    t.string :name
  end
end

require "action_controller/railtie"
require "action_view/railtie"
require "active_admin"

class TestApp < Rails::Application
  config.root = __dir__
  config.session_store :cookie_store, key: "cookie_store_key"
  secrets.secret_token = "secret_token"
  secrets.secret_key_base = "secret_key_base"

  config.eager_load = false
  config.logger = Logger.new($stdout)

  config.hosts = "www.example.com"
end

module ApplicationHelper
  def destroy_admin_user_session_path
    ""
  end
end

class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers

  def current_user
    User.new(id: 1)
  end

end

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    authorizable_ransackable_attributes
  end

  def self.ransackable_associations(auth_object = nil)
    authorizable_ransackable_associations
  end
end

class User < ApplicationRecord
  def author_ids
    [1, 2]
  end
end

class Post < ApplicationRecord
end

class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    case subject
    when normalized(Post)
      # Only let the author update and delete posts
      if subject.is_a?(Post)
        user.author_ids.include?(subject.author_id)
      else
        true
      end
    else
      true
    end
  end

end

ActiveAdmin.setup do |config|
  # Authentication disabled by default. Override if necessary.
  config.authentication_method = false
  config.current_user_method = :current_user
  config.authorization_adapter = "AdminAuthorization"
end

Rails.application.initialize!

ActiveAdmin.register_page "Dashboard" do
  menu priority: 1, label: proc { I18n.t("active_admin.dashboard") }
  content do
    "Test Me"
  end
end

ActiveAdmin.register User do
end

ActiveAdmin.register Post do
  permit_params do
    [:author_id, :name]
  end
end

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
end

require "minitest/autorun"
require "rack/test"
require "rails/test_help"

# Replace this with the code necessary to make your test fail.
class BugTest < ActionDispatch::IntegrationTest

  def test_admin_posts
    # we should be able to create a post with one of our author_ids
    post admin_posts_url, params: { post: {author_id: 1, name: "My Post"} }
    assert_equal 1, Post.count

    # we should see the post
    get admin_posts_url
    assert_match "My Post", response.body
    assert_response :success

    # and be able to edit it
    get edit_admin_post_url(1)
    assert_response :success

    # we shoould not be able to create a post with a foreign author_id
    post admin_posts_url, params: { post: {author_id: 666, name: "Not my other Post"} }
    assert_equal 1, Post.count

    # we should not be allowed to change the author_id of the first post to something we are not supposed to    
    patch admin_post_url(1), params: { post: {author_id: 666, name: "Not my Post anymore"} }

    # the post should still be one of ours
    get edit_admin_post_url(1)
    assert_response :success
  end

  private

  def app
    Rails.application
  end
end

```

**Comment by javierjulio** [comment]
You're welcome. This is not an issue with the admin. It is a responsibility of the app at the model level to not change the author of a post. You should be guarding that with a validation. I've had to deal with something similar before but not with the admin. That to me makes sense. Thanks!

**Comment by vc-jl** [comment]
Alright, will do :) Thanks again. 
One last question though: Do you know why there is this check `authorize_resource!` in the `build_resource`-method?
https://github.com/activeadmin/activeadmin/blob/ccdf0d7ff54db1324fc5cd1e6ef831ab47196c42/lib/active_admin/resource_controller/data_access.rb#L115-L125

**Comment by javierjulio** [comment]
You're welcome. I don't know. It's been there since the project was created by its original author.

**Comment by vfonic** [comment]
I've also been looking into the same issue.

On #create, AA authorizes the record after assigning the attributes.
On #update, AA authorizes the record before assigning the attributes.

If the app implements functionality which allows for post author change, it allows the user to change from allowed author to disallowed author. For example, I could have a Team and allow users to transfer resources between various Teams user belongs to.

I can have a Pundit policy class written like this:

```ruby
class ResourcePolicy < ApplicationPolicy
  # allows user to manage all resources for all the teams the user belongs to
  # we also allow transferring the resource between teams the user belongs to by having
  #   permit_params :team_id
  # in our ActiveAdmin resource class
  def update? = user.team_ids.include?(resource.team_id)
end
```

This actually allows the user to transfer the resource to _any_ team in the app, even those that user doesn't have access to.

I have written about this here:
https://github.com/vfonic/activeadmin-insecure_on_update/issues/3

I used the use-case of transferring ForumThread from one (sub) Forum to another.

**Comment by vc-jl** [comment]
Thanks for further insights @tagliala.

I understand your point about it being off or a workaround as Pundit specifies to check before assigning attributes. What is still missing is how to check at `create`, and that is where Active Admin behaves inconsistently. Right now the check for `create` takes place after assignment.

Following the example from https://github.com/vfonic/activeadmin-insecure_on_update/issues/3
> You cannot directly create a Thread in Forum 2, but you can create it in Forum 1 and assign it (transfer) to Forum 2 on update.

So there are three obvious options, I guess.
* Resolve this inconsistency by also checking after assignment in `update`. This could lead to apps being more "secure" in cases where developers misunderstood the relationship between assignment and authorization. At the same time it could break apps that rely on the current behavior.  
* Resolve this inconsistency by not checking after assignment in `create`. This would most definitely lead to apps being less secure in cases where developers rely on the current behavior.
* Leave the inconsistency as it is. This does not break any apps but has developers stumble on the inconsistency and potentially misunderstand how authorization works in Active Admin.

**Comment by vfonic** [comment]
I agree with @vc-jl and believe that ActiveAdmin should fix this security issue in the gem code.
ActiveAdmin is a full admin solution, with authorization layer.
My expectations, as a library user, would be that it takes care of authorization.
If one of authorization adapters is Pundit, and I specify `def update? = user.team_ids.include?(resource.team_id)`, (user can only update his teams), I'd expect ActiveAdmin to prevent the resource from entering an unauthorized state.

I don't see where I am able to fix this issue for the admin interface part of my apps? I should either override admin controller `#update` methods for every controller where I consider this to be an issue. Or I could monkey patch the authorization adapter to perform authorization (before and) after assigning the attributes.
