### ISSUE TITLE
uninitialized constant InheritedResources::Base (NameError)

### ISSUE THREAD

**Issue by Hammam94** [activeadmin/activeadmin#8142]
### Did you find a bug?

can't load active admin gem always get this error `uninitialized constant InheritedResources::Base (NameError)`

### My findings

Actually, i can see that you depend on the old version for the `inherited_resources` gem you depend on version 1.7 which doesn't support rails 7 why you didn't consider using the latest version of this gem which is 1.14 which supports rails 7

**Comment by tagliala** [comment]
Hi, this has been fixed a while ago

Please make sure that you are using v2.11.0 at least (and update dependent libraries like arbre and inherited_resources)

> you depend on version 1.7

activeadmin depends on `~> 1.7`, which includes 1.14
