### ISSUE TITLE
Rails 7.1.2 compatibility

### ISSUE THREAD

**Issue by ayaz-ac** [activeadmin/activeadmin#8183]
Hello !

I'm currently working on a Rails app with the latest version: `7.1.2`.

Unfortunately, I cannot install the gem because I'm getting an error on the compatibility with `railties`.

### Expected behavior

The gem should install in a `7.1.2` Rails app

### Actual behavior

```
Could not find compatible versions

Because every version of activeadmin depends on railties >= 6.1, < 7.1
  and rails >= 7.1.2 depends on railties = 7.1.2,
  every version of activeadmin is incompatible with rails >= 7.1.2.
So, because Gemfile depends on rails ~> 7.1.2
  and Gemfile depends on activeadmin >= 0,
  version solving has failed.
```

### How to reproduce

1. Create a new Rails app with the `7.1.2` version
2. Add the gem `activeadmin` to the Gemfile
3. Run `bundle install`

**Comment by javierjulio** [comment]
This isn’t reproducible. The giveaway is the versions first listed for railties as we no longer specify an upper bound dependency limit. Make sure to install the latest version of ActiveAdmin which will resolve that. Thank you.
