### ISSUE TITLE
make a field editable (via checkbox) on index view

### ISSUE THREAD

**Issue by JohnMerlino1** [activeadmin/activeadmin#819]
Hey all,

There is no way to make a field editable on the index view. Right now you have to click the edit button and edit the record rather than just being able to tik a checkbox on list view and then click an update button on list view. In order to accomplish this, must I create my own view or can I modify the index method and do something like this:

  index do
    column "ID",                   :id
    column "Enabled?",             :enabled, :as => :checkbox
    default_actions //custom action for update
  end

In the above example, adding :as => :checkbox does nothing

thanks for response

**Comment by anilnabin25** [comment]
IMO
```
 member_action :enable, :method => :put do
  thing = Thing.find(params[:id])
  thing.enable!
  flash[:notice] = "Some Thing has been enabled!"
  redirect_to :action => :index
end

index do
  # ...
  column |thing|
    link_to "Enable", url_for(:action => :enable, :id => thing.id), :method => :put, :confirm => I18n.t('are_you_sure')
    link_to , url_for(:action => :enable, :id => thing.id), data: { method: :put, confirm: I18n.t('are_you_sure') } do
        check_box("testing", thing.id, { checked: true, class: "active-admin-check-box" })
      end
  end
end
```
