### ISSUE TITLE
after_save called even if validation fails

### ISSUE THREAD

**Issue by timwis** [activeadmin/activeadmin#8244]
Hi team 👋🏻  I noticed my `after_save` callback defined on my ActiveAdmin resource was running even when validation fails, and I can't seem to figure out why. I tried debugging the behaviour, and eventually started a fresh ActiveAdmin project to see if I could reproduce it (and I did).

### Expected behavior

The `after_save` callback defined on the ActiveAdmin resource should not run if the model has validation errors preventing it from saving.

### Actual behavior

The `after_save` callback _is_ called, even though it wasn't saved, then the UI shows the validation errors.

### How to reproduce

I created a minimalist reproduction on a fresh rails app with ActiveAdmin installed on [this code sandbox](https://codesandbox.io/p/devbox/magical-kapitsa-lk786w). The public-facing app should be accessible [here](https://lk786w-3000.csb.app/admin/). Sorry - I didn't realise there was a reproduction script until after I'd made this reproduction. I hope that's okay!

Here's a summary of the reproduction code:

`app/models/post.rb`
```ruby
class Post < ApplicationRecord
  validates :title, presence: true
  validates :slug, uniqueness: true

  def self.ransackable_attributes(_auth_object = nil)
    %w[title slug body published]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end
```

`db/migrate/20240126162807_create_posts.rb`
```ruby
class CreatePosts < ActiveRecord::Migration[7.0]
  def change
    create_table :posts do |t|
      t.string :title
      t.string :slug
      t.text :body
      t.boolean :published

      t.timestamps
    end

    add_index :posts, :slug, unique: true
  end
end
```

`app/admin/posts.rb`
```ruby
ActiveAdmin.register Post do
  permit_params :title, :slug, :body, :published

  after_save do |post|
    puts "*** after_save called. valid? #{post.valid?}"
  end
end
```

If you try to create a post with an empty title, or with a slug that's already in use, and look at the server console, you'll see the log:
```
*** after_save called. valid? false
```

It also happens when updating an existing post.

Have I done something completely wrong, or does this indeed sound like a bug?

Thanks for reading.

**Comment by javierjulio** [comment]
@timwis thank you. Can you please use our bug report template script instead? You should be able to replicate it using that. Sorry, I don't use this callback feature so I'm not familiar with it or what could be wrong if anything.

**Comment by timwis** [comment]
Sure @javierjulio, see below. I've just made `after_save` `raise` (after_save shouldn't be called in the two test cases, as the data is invalid). There's probably a cleaner assertion I could use, but it's late and that's all I could think of! Hope that's okay. For context, my real world use case is hitting a third party forums API when my users resource is created/updated, to update the display name and permissions. I don't want to do it in the model callbacks because then it would get fired on my model tests etc.

It looks like the callbacks are defined [here](https://github.com/activeadmin/activeadmin/blob/d6ee9b85bc17862a0d9b93046a2233718268d3c7/lib/active_admin/callbacks.rb#L74-L76), but I'm not familiar enough with metaprogramming to understand where it's going wrong :/

```ruby
# frozen_string_literal: true
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  # Use `ACTIVE_ADMIN_PATH=. ruby tasks/bug_report_template.rb` to run
  # locally, otherwise run against the default branch.
  if ENV["ACTIVE_ADMIN_PATH"]
    gem "activeadmin", path: ENV["ACTIVE_ADMIN_PATH"], require: false
  else
    gem "activeadmin", github: "activeadmin/activeadmin", require: false
  end

  # Change Rails version if necessary.
  gem "rails", "~> 7.0.0"

  gem "sprockets", "~> 4.0"
  gem "importmap-rails", "~> 2.0"
  gem "sqlite3", platform: :mri

  # Fixes an issue on CI with default gems when using inline bundle with default
  # gems that are already activated
  # Ref: rubygems/rubygems#6386
  if ENV["CI"]
    require "net/protocol"
    require "timeout"

    gem "net-protocol", Net::Protocol::VERSION
    gem "timeout", Timeout::VERSION
  end
end

require "active_record"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :active_admin_comments, force: true do |_t|
  end

  create_table :users, force: true do |t|
    t.string :full_name
  end
end

require "action_controller/railtie"
require "action_view/railtie"
require "active_admin"

class TestApp < Rails::Application
  config.root = __dir__
  config.hosts << ".example.com"
  config.session_store :cookie_store, key: "cookie_store_key"
  config.secret_key_base = "secret_key_base"

  config.logger = Logger.new($stdout)
  Rails.logger = config.logger
end

class ApplicationController < ActionController::Base
  include Rails.application.routes.url_helpers
end

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    authorizable_ransackable_attributes
  end

  def self.ransackable_associations(auth_object = nil)
    authorizable_ransackable_associations
  end
end

class User < ApplicationRecord
end

ActiveAdmin.setup do |config|
  # Authentication disabled by default. Override if necessary.
  config.authentication_method = false
  config.current_user_method = false
end

Rails.application.initialize!

ActiveAdmin.register_page "Dashboard" do
  menu priority: 1, label: proc { I18n.t("active_admin.dashboard") }
  content do
    "Test Me"
  end
end

ActiveAdmin.register User do
end

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
end

require "minitest/autorun"
require "rack/test"
require "rails/test_help"

# Replace this with the code necessary to make your test fail.
class BugTest < ActionDispatch::IntegrationTest

  def test_admin_root_success?
    get admin_root_url
    assert_match "Test Me", response.body # has content
    assert_match "Users", response.body # has 'Your Models' in menu
    assert_response :success
  end

  def test_admin_users
    User.create! full_name: "John Doe"
    get admin_users_url
    assert_match "John Doe", response.body # has created row
    assert_response :success
  end

  private

  def app
    Rails.application
  end
end
```

**Comment by javierjulio** [comment]
Thanks @timwis. To be upfront, I would welcome a fix, I just wouldn't expect to come from us so this is unlikely to be resolved. I'm not familiar with our callbacks implementation. It seems to be a roll-your-own setup so I don't know how this works for Rails and whether it behaves the same or not. I would suggest finding an alternative. You could just override the `update` action for an admin resource and queue the third party call there if you don't want it in a model callback.

**Comment by timwis** [comment]
Okay, thanks @javierjulio. I struggled to work out how the callback implementation works, so I'm not sure I'll be able to provide a fix either. I'll look for an alternative implementation as you suggest.

**Comment by javierjulio** [comment]
For anyone else coming here, please refer to the earlier comment: https://github.com/activeadmin/activeadmin/issues/8244#issuecomment-1912833927
