### ISSUE TITLE
fix ActiveAdmin CSS overriding problem 

### ISSUE THREAD

**Issue by simontol** [activeadmin/activeadmin#825]
CSS files are loaded for ALL the views (only trying in dev env). Quite annoying and will override your styles. To fix just move the app/assets/stylesheets/active_admin.css.scss to vendor/assets/stylesheets/active_admin.css.scss – It is only loaded when required then.
source:
http://robertomurray.co.uk/blog/2011/rails-fix-activeadmin-css-over-riding-problem/

**Comment by gobijan** [comment]
Works for me the best (application.css):

  /*
   * This is a manifest file that'll be compiled into application.css, which will include all the files
   * listed below.
   *
   * Any CSS (and SCSS, if configured) file within this directory, lib/assets/stylesheets, or any plugin's
   * vendor/assets/stylesheets directory can be referenced here using a relative path.
   *
   * You're free to add application-wide styles to this file and they'll appear at the bottom of the
   * compiled file so the styles you add here take precedence over styles defined in any other CSS
   * files in this directory. Styles in this file should be added after the last require_* statement.
   * It is generally better to create a new file per style scope.
   *
   *= require_tree .
   *= stub "active_admin"
   *= require_self
   */
