### ISSUE TITLE
Indentation broken for nested lists

### ISSUE THREAD

**Issue by matteeyah** [activeadmin/activeadmin#8274]
### Expected behavior

Ordered and unordered lists should be working as expected. They should be indented and bulleted. Just like in the old version of ActiveAdmin

<img width="1388" alt="Screenshot 2024-03-01 at 19 19 36" src="https://github.com/activeadmin/activeadmin/assets/1218868/db7c557a-1c64-4812-87e7-a28370aa9bc7">

### Actual behavior

Ordered and unordered lists don't seem to be working as expected. They are not indented, or bulleted.

<img width="1161" alt="Screenshot 2024-03-01 at 19 19 13" src="https://github.com/activeadmin/activeadmin/assets/1218868/67dea117-eee8-485f-9fc7-9851a4d2ecfb">

### How to reproduce

Create an ActiveAdmin page with a field that has a nested ordered and unordered list.

**Comment by javierjulio** [comment]
@matteeyah I believe what you are sharing is from the v4 beta. Note that this is intentional and noted in the upgrading guide.

> Typographic elements (other than links in main content) [are not styled by default](https://tailwindcss.com/docs/preflight). Use the @tailwindcss/typography plugin or apply your own CSS alternative.
