### ISSUE TITLE
No access to routes helpers from ActiveAdmin views [v4.0.0.beta5]

### ISSUE THREAD

**Issue by amkisko** [activeadmin/activeadmin#8279]
Route helpers are not available within ActiveAdmin views, even `root_path` is not available in the context of view Class.

```
ActionController::UrlGenerationError - No route matches {:action=>"index", :controller=>"active_admin/users"}:
  app/views/active_admin/_sidebar.html.erb:3
  app/views/layouts/active_admin.html.erb:15
```

It seems to be related to the recent change of separating contexts, so these helpers are still available under `main_app` variable.

### Expected behavior

Route helpers are available.

### Actual behavior

Helpers are not available, ActiveAdmin v4 code throws exception for new and generated resource.

### How to reproduce

- initialise ActiveAdmin v4 project
- generate sample resource
- run the app, try accessing the resource

**Comment by amkisko** [comment]
Related to post in Discussions: https://github.com/activeadmin/activeadmin/discussions/8223#discussioncomment-8299413

**Comment by amkisko** [comment]
Quite hard to reverse engineer where it breaks, if you have any clues please let me know, will be glad to resolve this and open PR here.

**Comment by javierjulio** [comment]
Thank you. There's nothing actionable here as key details are missing to reproduce. We won't be able to consider anything without a reproduction. On several apps, using path helpers defined in the app but used within the admin work fine. The one caveat being using app path helpers in Devise templates as noted in the Upgrading guide.

**Comment by amkisko** [comment]
> using path helpers defined in the app but used within the admin work fine

The error states that ActiveAdmin path helpers are not available within the view class that is used for ActiveAdmin view render.

> We won't be able to consider anything without a reproduction.

By this you mean: publicly-available repository with code and production instance for seeing the exact effect?

**Comment by javierjulio** [comment]
And those path helpers work as well. I haven't encountered any issues which is why I mention it would need a reproduction. You can try using our bug report template script or yes, using a public repo. Thank you.

**Comment by amkisko** [comment]
Confirming that started from scratch app works fine without issues.

**Comment by amkisko** [comment]
Collected all information that helped me with setup here: https://gist.github.com/amkisko/c704c1a6462d573dfa4820ae07d807a6

**Comment by amkisko** [comment]
@javierjulio I found out that this issue is related to custom namespace like this: `config.default_namespace = :active_admin`, everything works fine when it's `:admin` which is default.
