### ISSUE TITLE
v4: add accessible names for buttons

### ISSUE THREAD

**Issue by tagliala** [activeadmin/activeadmin#8328]
### Expected behavior

No warnings

### Actual behavior

<img width="733" alt="image" src="https://github.com/activeadmin/activeadmin/assets/556268/e1b193b9-6c4d-467b-8db1-458b79378855">

### How to reproduce

1. Go to https://activeadmin-demo.onrender.com/admin
2. Login

Run Lighthouse

**Comment by sveredyuk** [comment]
@tagliala Hi, do you have the source code of this admin deployment? I want to figure out how to setup it with rails 7 + importmaps

**Comment by tagliala** [comment]
Hi, 

not familiar with render. Is it the `render.yml` at https://github.com/activeadmin/demo.activeadmin.info ?

**Comment by sveredyuk** [comment]
Thanks. I think my question was more related to how to use activeadmin 4 without sprockets. Propshaft + impormap? is it possible?

**Comment by tagliala** [comment]
> Propshaft + impormap? is it possible?

The demo should use sprockets + importmap. I guess that by following the migration guide to sprockets to importmap it. should be possible to use propshaft

Please check #8223 and maybe ask there, we are off topic here

**Comment by 319684023** [comment]
I didnt ask for advice
