### ISSUE TITLE
v4: Missing Horizontal scroll on index

### ISSUE THREAD

**Issue by barnaclebarnes** [activeadmin/activeadmin#8343]
On safari Mac (latest versions) the horizontal scroll bar is missing if the width of the columns takes up more than the width of the screen. On Chrome you see a scroll bar

### Expected behavior

You should see a scroll bar if the width of the index gable is wider than the viewport.

### Actual behavior

Scroll bar does not show on Safari Mac (but does on Chrome).

### How to reproduce

Create an index view with enough columns to extend beyond the width of a screen. Open it in Safari on Mac.

![CleanShot 2024-05-28 at 13 46 50@2x](https://github.com/activeadmin/activeadmin/assets/10322/d91898d8-3fa2-4511-bde8-ed6b98d19865)

**Comment by javierjulio** [comment]
@barnaclebarnes thank you. This is expected and by design since that's a Safari default. You should be able to add your own CSS to always display a horizontal scrollbar there if you prefer.
