### ISSUE TITLE
v4: Several required dependencies seem to be missing

### ISSUE THREAD

**Issue by vfonic** [activeadmin/activeadmin#8381]
I'm trying to upgrade to AA v4. I understand it's still in beta, but it's beta7 so that gives me hopes.
I thought "beta" means "for brave users who want to test the latest functionality and report bugs". Maybe I'm wrong and this beta is not meant to be ready for use?

Here's what I tried to make this work:

1. I've updated the `Gemfile`: `gem 'activeadmin', '~> 4.0.0.beta1'`
2. Re-run `rails g active_admin:install User`
3. I needed to add `importmap-rails`:

```sh
bundle add importmap-rails
rails importmap:install
```

4. I also needed to run `rails assets:clobber`.

5. I managed to boot the app and now no styles are applied because the `app/assets/stylesheets/active_admin.css` is returned as-is (Tailwind didn't build the CSS):

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

6. So I added `css: yarn build:css --watch` to my `Procfile.dev` and 
`"build:css": "tailwindcss -i ./app/assets/stylesheets/active_admin.css -o ./app/assets/builds/active_admin.css --minify"`
to my `package.json` under `"scripts"`.

Now Tailwind loads, but Tailwind doesn't find the HTML classes from AA gem and so it only adds the basic Tailwind styles in the newly-generated CSS file. I also see this message in the terminal:

> No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.

This is where I tried a few more things and failed to make Tailwind find the CSS classes in HTML generated by AA (outside of my app project files).

### Expected behavior

The upgrade process should be easier.
The only upgrading docs I found point to `CHANGELOG.md` which is no longer used to document gem changes:
https://github.com/activeadmin/activeadmin/blob/docs-v4/docs/0-installation.md#upgrading

### Actual behavior

The upgrading process is complicated. v4 requires several additional gems which it assumes it has.
I couldn't find much of the documentation. I see the docs are being updated, but not much is mentioned about upgrading.
I think AA has a huge user base and it should be of big importance to provide the documentation on how to upgrade.
I appreciate the work being done and I'm very excited about the AA v4!

### How to reproduce

Try going through the process of upgrading AA from v3 to v4.
Perhaps the best way to document the upgrade process is to go through the upgrade process oneself.

**Comment by vfonic** [comment]
Darn, just as I posted this I found the `UPGRADING.md`.

**Comment by javierjulio** [comment]
@vfonic yes, it's in the UPGRADING guide which is expected since that's what you are doing. It's involved so I felt a dedicated guide would be best. A part of updating the docs site (#8194) will be adding content on upgrading or starting with v4. As you can see it's a challenge because we can't enforce certain dependencies because others will want to use something else. Give it a try and feel free to share any feedback. Thank you.

**Comment by vfonic** [comment]
Thanks for such a quick reply! I managed to get it all to load. Time to migrate all the SCSS and jQuery code.
Thanks!

**Comment by brendon** [comment]
@vfonic, what was your secret to getting the tailwind classes in the build?

**Comment by vfonic** [comment]
@brendon you need to follow this guide: https://github.com/activeadmin/activeadmin/blob/master/UPGRADING.md

This code is crucial:

```sh
yarn add @activeadmin/activeadmin@4.0.0-beta16
npm pkg set scripts.build:css="tailwindcss -i ./app/assets/stylesheets/active_admin.css -o ./app/assets/builds/active_admin.css --minify -c tailwind-active_admin.config.js"
```

**Comment by brendon** [comment]
Oh sorry, in the end I was using Tailwind 4 as that appears to have been released after the upgrade guide was written. It doesn’t read the config correctly but also doesn’t fail so it’s hard to figure out.
