### ISSUE TITLE
4.0.0.beta7:  Can not disable filters

### ISSUE THREAD

**Issue by neidiom** [activeadmin/activeadmin#8382]
When I set `config.filters = false` in the initializer I get this error:
````
9:36:59 web.1  | /home/nedim/.rvm/gems/ruby-3.3.2/gems/activeadmin-4.0.0.beta7/lib/active_admin/filters/resource_extension.rb:76:in `add_filter': Cannot add a filter when filters are disabled. Enable filters with 'config.filters = true' (ActiveAdmin::Filters::Disabled)                            
````
Here is the config/initializers/active_admin.rb
![image](https://github.com/activeadmin/activeadmin/assets/8058363/7e5388aa-62aa-4fa8-8fac-1aaea5631c8e)

**Comment by tagliala** [comment]
I was able to replicate with 

```
bundle exec rake local server
```

After changing that configuration option in

```
tmp/development_apps/rails_71/config/initializers/active_admin.rb
```

**Comment by javierjulio** [comment]
@neidiom my understanding is that this is intentional and has been there for quite some time. The error change from https://github.com/activeadmin/activeadmin/pull/6195 was included in v2.14.0. Thank you.

**Comment by neidiom** [comment]
Any suggestions on how I disable filters? @javierjulio

**Comment by tagliala** [comment]
You should have some `filter` in your active admin models

I can confirm that `bundle exec rake local server` works on main after removing all `filter :...` from

- `tmp/development_apps/rails_71/app/admin/admin_users.rb`
- `tmp/development_apps/rails_71/app/admin/posts.rb`
- `tmp/development_apps/rails_71/app/admin/users.rb`

**Comment by javierjulio** [comment]
@neidiom as @tagliala mentioned, you'll have to remove the filter declarations from your resource files to disable filters globally.

**Comment by neidiom** [comment]
Thank you @tagliala @javierjulio
