### ISSUE TITLE
Batch action automatically submits form even though a partial is being rendered

### ISSUE THREAD

**Issue by ryoung** [activeadmin/activeadmin#8440]
It looks like https://github.com/activeadmin/activeadmin/pull/8389 introduced a bug where batch actions rendered with a partial are being submitted immediately.
If you follow the [batch action partial example](https://github.com/activeadmin/activeadmin/blob/master/UPGRADING.md?plain=1#L104) in the upgrade guide, you can see it does not work.

The change [here](https://github.com/activeadmin/activeadmin/pull/8389/files#diff-f36b5577df9210253db0d1c7f87f3544c7ba2e557fc2e26625981f2e81a3eb7fR17) is causing the form to submit immediately because there is no `confirm` attribute.

### Expected behavior

On an index table:
1. Select rows to perform a batch action on
2. Click `Batch Actions` and select an action
3. Partial is rendered
4. User should be able to interact with the form before submitting

### Actual behavior

On an index table:
1. Select rows to perform a batch action on
2. Click `Batch Actions` and select an action
3. Partial is rendered
4. Form is also submitted

### How to reproduce

Create a batch action with a partial:

```
batch_action(
    :mark_published,
    partial: "mark_published_batch_action",
    link_html_options: {
      "data-modal-target": "mark-published-modal",
      "data-modal-show": "mark-published-modal"
    }
  ) do |ids, inputs|
    # ...
end
```

On the index page, select rows, click `Batch Actions` and select `Mark Published`.
See that the partial is rendered, but the form is submitted immediately and the page refreshes before you can interact with the partial.

**Comment by javierjulio** [comment]
@ryoung we'll accept a fix for this. Thank you.

**Comment by tagliala** [comment]
Mentioning @DarkSwoop as the author of #8389
