### ISSUE TITLE
Docs: Setting up when already using Devise is misleading

### ISSUE THREAD

**Issue by vfonic** [activeadmin/activeadmin#8519]
I'm making a new Rails 8 app and I just set-up and installed Devise with `User` model.

I then followed the ActiveAdmin 4 beta 13 instructions from here:
https://activeadmin.info/0-installation.html#setting-up-active-admin

In it it says:

> After installing the gem, you need to run the generator. Here are your options:
> 
> * If you don't want to use Devise, run it with `--skip-users`:
> ```sh
> rails g active_admin:install --skip-users
> ```

This is not the option I want, because I want to use Devise

> * If you want to customize the name of the generated user class, or if you want to use an existing user class, provide the class name as an argument:
> 
> ```sh
> rails g active_admin:install User
> ```

So this is the one I used.

Here's what it did:

```sh
> rails g active_admin:install User
      invoke  devise
    generate    No need to install devise, already done.
      invoke    active_record
      create      db/migrate/20241028230833_add_devise_to_users.rb
      insert      app/models/user.rb
       route    devise_for :users
        gsub    app/models/user.rb
        gsub    config/routes.rb
      append    db/seeds.rb
      create  config/initializers/active_admin.rb
       exist  app/admin
      create  app/admin/dashboard.rb
      create  app/admin/users.rb
      insert  config/routes.rb
    generate  active_admin:assets
       rails  generate active_admin:assets 
      remove  app/assets/stylesheets/active_admin.scss
      remove  app/assets/javascripts/active_admin.js
      create  app/assets/stylesheets/active_admin.css
      create  tailwind-active_admin.config.js
      create  db/migrate/20241028230834_create_active_admin_comments.rb
```

1. I already have a migration and I already ran `rails db:migrate` for `DeviseCreateUsers` (provided by Devise). This migration is not needed in such cases: `db/migrate/20241028230833_add_devise_to_users.rb`
2. It modified `app/models/user.rb`:

```diff
class User < ApplicationRecord
  # Include default devise modules. Others available are:
-  # :confirmable, :registerable, :omniauthable
+  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
+  devise :database_authenticatable, 
+         :recoverable, :rememberable, :validatable
+  # Include default devise modules. Others available are:
+  # :confirmable,  :omniauthable
  devise :database_authenticatable, :lockable, :recoverable, :rememberable, :timeoutable, :trackable, :validatable
end
```

Seems like it wrongly interpreted my `devise` configuration in the `User` model.

### Expected behavior

Devise setup is picked up correctly and no devise-related migration is added, nor `User` model is modified if there's already a Devise configuration added.

### How to reproduce

1. `bundle add devise`
2. `rails generate devise User`
3. `rails db:migrate`
4. `bundle add activeadmin` # not sure how to do this for beta version
5. `rails g active_admin:install User`

**Comment by javierjulio** [comment]
@vfonic sorry, I'm a bit confused by this submission. If it's a documentation issue we ask on the New Issue page that you open a PR instead with the suggested updates as improvements are welcome. Thank you.

Although it seems what you are suggesting is a problem with the generator. I'm not sure if it's that much of a concern since the extra migration can just be deleted since you knowingly ran Devise directly instead of through the ActiveAdmin setup.

I suspect why it generated the second migration in your case was [due to this method in the generator which invokes devise](https://github.com/activeadmin/activeadmin/blob/master/lib/generators/active_admin/devise/devise_generator.rb#L39-L44). I'm not sure how we'd protect against that there. We will accept a PR though to address that so please feel free to tackle it. Thank you.

**Comment by tagliala** [comment]
> bundle add activeadmin # not sure how to do this for beta version

```
bundle add activeadmin --version "~> 4.0.0.beta13"
```

> This is not the option I want, because I want to use Devise

I may be wrong, but I understand this as a request to make a change like this:

```diff
-  If you don't want to use Devise, run it with --skip-users:
+  If you have already configured Devise or don't need it, run the generator with with --skip-users: 
```

or in other words that "devise is already configured and the user model is already present"

This change may be clearer

**Comment by vfonic** [comment]
@tagliala would this then skip adding routes as well or just skip adding migrations and making changes to User or AdminUser model?

**Comment by tagliala** [comment]
Hi @vfonic I'm seeing in invitation from your side to a private repository

Can I ask if that is related to a security issue?

In case of security issues, there is a section in the readme: https://github.com/activeadmin/activeadmin?tab=readme-ov-file#security-contact-information

**Comment by vfonic** [comment]
Hi @tagliala, yes, it's related to a security issue. It's very difficult to figure out a way to reach out to you. I've read the instructions from the `README.md`. I followed the link from the `README.md` to Tidelift. It was confusing that the page doesn't have Register/Signup button, but it has Log in. I assumed I needed to create an account. Usually, on a new platform, you need to create some kind of an account. Or you can submit a form. The very last resort, IMHO, is to send an email. In order to save my time, I didn't read the whole Tidelift page to see that. I've since read the Tidelift page and emailed security@tidelift.com
I explained them the situation and Jeremy replied saying that I should also invite @deivid-rodriguez alongside @tagliala and @javierjulio, who I already invited.

I'm just trying to save time and report a potential security issue. It would be great if the process was simpler. I don't know why you need to go through Tidelift (email) to receive...an email yourself? Anyway...
I've written the explanation inside the `README.md` and the issue I've created in the private repo where I've invited the 3 of you.

**Comment by vfonic** [comment]
You can accept the invitation, I don't believe there's any security issue in that. And we can continue talking through GH issue. I think that makes most sense.
