### ISSUE TITLE
Blank values for TEXT fields should be set to NULL in db -- instead get set as empty string!

### ISSUE THREAD

**Issue by ghost** [activeadmin/activeadmin#855]
This one is quite big.

If a field allows null in the schema and no value is entered in the ActiveAdmin form, it sets that field in the db as empty string instead of NULL.

**Comment by Empact** [comment]
I disagree this is a Rails issue. In Rails you can control and modify your model inputs. ActiveAdmin should allow the same.

**Comment by BuonOmo** [comment]
@jpemberthy you did not respond here, any new on this one?

**Comment by martinstreicher** [comment]
I would recommend the application-wide adoption of the nilify_blanks gem.
