### ISSUE TITLE
v4 - turbo breaks user menu on navigation

### ISSUE THREAD

**Issue by thisismydesign** [activeadmin/activeadmin#8577]
Using v4.0.0.beta13.  Navigating in the menu breaks the profile menu, so that it no longer opens on clicks after navigating in the menu. This seems to happen because of turbo. Removing `import "@hotwired/turbo-rails"` from `application.js` resolves the issue.

Possible solution:
`application.js`
```js
document.addEventListener("turbo:load", () => {
  // trigger AA re-init
});
```

**Comment by tagliala** [comment]
Hello, is it possible to have a reproducible test case?

Is it related to a problem where from the main application a user follows a link to the admin area?

PS: Please also use beta15 for the reproducible test case

**Comment by tagliala** [comment]
Thanks, I've tried to run it in docker but assets don't work (macOS Sequoia 15.2, Apple Silicon, docker 4.37.0 without login)

I can see that activeadmin is using a custom head partial which is importing application.js, but I don't know if this is a good practice

I would keep them separated.

> Is there something I could call in the turbo hook to re-initialize AA's JS?

Maybe it is flowbite https://github.com/activeadmin/activeadmin/discussions/8573
