### ISSUE TITLE
Warning: method #{name} already defined

### ISSUE THREAD

**Issue by umbertopollasto** [activeadmin/activeadmin#8582]
### Warning: method #{name} already defined

sometimes when autoloading `activeadmin` the console shows this warning:   `warn "Warning: method `#{name}` already defined in #{controller.name}" if controller.method_defined?(name)`

I initialized the controller and added a member_action named clone and it returns me this kind of warning. 
After a thorough analysis I found that `controller.method_defined?(name)` finds the method in ["<internal:kernel>", 47]

### Expected behavior

 if controller.method_defined?(name)`
 returns false 

### Actual behavior

 if controller.method_defined?(name)`
 returns true

### How to reproduce

1. Create a controller as ActiveAdmin.register ControllerName
2.  ``` member_action :clone, method: :post do  <your_code> end ```
3.  Start rails console or server
4. "Warning: method clone already defined in ControllerName"

**Comment by tagliala** [comment]
Hi,

I think this name collides with `Kernel#clone`

https://ruby-doc.org/core-3.0.2/Kernel.html#method-i-clone

This is a plain RoR application without ActiveAdmin:

```
 ActionController::Base.method_defined?(:clone)
=> true
```

**Comment by Oranuch158** [comment]
Oranuch Jaihan

**Comment by Oranuch158** [comment]
Oranuch Jaihan

**Comment by Oranuch158** [comment]
> ### Warning: method #{name} already defined
> sometimes when autoloading `activeadmin` the console shows this warning: `warn "Warning: method `#{name}` already defined in #{controller.name}" if controller.method_defined?(name)`
> 
> I initialized the controller and added a member_action named clone and it returns me this kind of warning. After a thorough analysis I found that `controller.method_defined?(name)` finds the method in ["internal:kernel", 47]
> 
> ### Expected behavior
> if controller.method_defined?(name)` returns false
> 
> ### Actual behavior
> if controller.method_defined?(name)` returns true
> 
> ### How to reproduce
> 1. Create a controller as ActiveAdmin.register ControllerName
> 2. `member_action :clone, method: :post do  <your_code> end`
> 3. Start rails console or server
> 4. "Warning: method clone already defined in ControllerName"

Oranuch Jaihan
