### ISSUE TITLE
Pagination problem: undefined local variable or method 'total_count'

### ISSUE THREAD

**Issue by ZsoltFabok** [activeadmin/activeadmin#861]
Pagination does not work after having more than 30 elements. The root cause is in the line 114 of  paginated_collection.rb.  The pull request is in progress

**Comment by marvindanig** [comment]
Looks like this issue has resurfaced with `rails 5.1.4`:

```
Processing by Admin::UsersController#show as HTML
  Parameters: {"id"=>"zgjimdida-zgjim-dida"}
  [1m[36mAdminUser Load (0.5ms)[0m  [1m[34mSELECT  "admin_users".* FROM "admin_users" WHERE "admin_users"."id" = $1 ORDER BY "admin_users"."id" ASC LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
  [1m[36mUser Load (24.7ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."slug" = $1 LIMIT $2[0m  [["slug", "zgjimdida-zgjim-dida"], ["LIMIT", 1]]
  Rendering vendor/bundle/ruby/2.4.0/gems/activeadmin-1.1.0/app/views/active_admin/resource/show.html.arb
  [1m[36mActiveAdmin::Comment Load (30.0ms)[0m  [1m[34mSELECT  "active_admin_comments".* FROM "active_admin_comments" WHERE "active_admin_comments"."resource_type" = $1 AND "active_admin_comments"."resource_id" = '650' AND "active_admin_comments"."namespace" = $2 ORDER BY created_at ASC LIMIT $3 OFFSET $4[0m  [["resource_type", "User"], ["namespace", "admin"], ["LIMIT", 11], ["OFFSET", 0]]
  Rendered vendor/bundle/ruby/2.4.0/gems/activeadmin-1.1.0/app/views/active_admin/resource/show.html.arb (257.9ms)
exception
undefined method `total_count' for #<ActiveRecord::Relation []>
Did you mean?  total_entries
  Rendering public/500.html
  Rendered public/500.html (0.7ms)
Completed 500 Internal Server Error in 391ms (Views: 59.5ms | ActiveRecord: 60.3ms)
```

**Comment by jainankita90** [comment]
facing same issue :(
is there any way to fix it
Rails 5.0.x

**Comment by ragarwa7** [comment]
Yes, I am getting the same error with 5.1.4.

AdminImagesControllerTest#test_should_get_show_view:
ActionView::Template::Error: undefined method `total_count' for #<ActiveRecord::Relation []>
Did you mean?  total_entries
    activerecord (5.1.4) lib/active_record/relation/delegation.rb:125:in `method_missing'
    randumb (0.5.2) lib/randumb/relation.rb:197:in `method_missing'
    activerecord (5.1.4) lib/active_record/relation/delegation.rb:95:in `method_missing'
    activeadmin (1.1.0) lib/active_admin/orm/active_record/comments/views/active_

Anyone with fix?

**Comment by nikhilgupte** [comment]
This seems to be related to active admin comments.

When I disabled comments by setting ```config.comments = false``` in the initializer, the error was gone.

**Comment by ragarwa7** [comment]
Still getting the same error. :(

**Comment by roberthopman** [comment]
@nikhilgupte thanks!

**Comment by jpdimond** [comment]
I'm also getting this error and would like to preserve the commenting feature.

**Comment by gilbertlcsndle** [comment]
I thought I'm the only one. I think we should use `config.comments = false` at the moment.

**Comment by TranBaVinhSon** [comment]
@nikhilgupte thanks man !

**Comment by wspurgin** [comment]
For anybody still coming to this issue and doesn't want to disable comments, you'll have to [add some configuration in your initializer](https://github.com/activeadmin/activeadmin/issues/5241#issuecomment-344326256).
