### ISSUE TITLE
Can I customize the output of .json?

### ISSUE THREAD

**Issue by cthomaschase** [activeadmin/activeadmin#915]
Can I customize the json output of a custom resource?

**Comment by IvRRimum** [comment]
This doesn't seem to work anymore(XML part).

**Comment by ypresto** [comment]
This old one worked very well: https://github.com/activeadmin/inherited_resources/issues/46#issuecomment-662925

I'm using code like below:

```rb
  controller do
    def index
      index! { |format| format.json { render json: collection.as_json(methods: :display_name) } }
    end
  end
```

**Comment by thisismydesign** [comment]
You can exclude/include fields via `as_json` e.g.

```
```
