### ISSUE TITLE
Getting CanCan::AuthorizationNotPerformed when creating comments

### ISSUE THREAD

**Issue by davidkariuki** [activeadmin/activeadmin#919]
I'm getting 

```
CanCan::AuthorizationNotPerformed in Admin::CommentsController#create 
This action failed the check_authorization because it does not authorize_resource. 
Add skip_authorization_check to bypass this check.
```

when I try to post a comment. The weird thing is that comments are created anyway.  I have `check_authorization` in my application controller so every action needs to be authorized but I'm not sure how to authorize `Admin::CommentsController#create.`

**Comment by xxEoD2242** [comment]
So, I'm not sure if you have found a solution to this or still need a solution, but I solved a similar issue the following way:

From my understanding, CanCan is looking for particular resources to authorize when using that callback for every action. Therefore, in ActiveAdmin, it doesn't explicitly create model files for certain models.  I had one for a different app and simply created a model for the controller action I was trying to create. I would recommend explicitly creating a 'comments' model file and see if that does the trick for the admin controller.
