### ISSUE TITLE
Add :if to filters

### ISSUE THREAD

**Issue by houen** [activeadmin/activeadmin#938]
I am trying to build an admin section, where some sidebar filters should only be available to some users. I am trying something like this:

ActiveAdmin.register User do
filter :first_name, :as => :string, :if => proc { can? :view_personal_information, User }

But it looks like filters do not evalutate proc's the same way e.g. menu calls does. This would be very helpful.

**Comment by reicheltd** [comment]
`filter :customer, if: proc { can? :read, User }` works fine! Thx!

**Comment by okliv** [comment]
yeah... but now, if it is conditionally happens that there is no any filters, it would be great if filter panel become hidden entirely

**Comment by rangerscience** [comment]
FYI: This doesn't appear in the docs - https://activeadmin.info/3-index-pages.html#index-filters

**Comment by rangerscience** [comment]
FYI: This doesn't appear in the docs - https://activeadmin.info/3-index-pages.html#index-filters
