### ISSUE TITLE
Handle serialized fields

### ISSUE THREAD

**Issue by pupeno** [activeadmin/activeadmin#970]
Hello,

It'd be nice if active_admin could handle serialized fields. At the moment it picks the de-serialized content, turns into a string, and then saves that string, causing the field to end up being a serialized string. That means that a field with a serialized field can't be edited (without building a custom form).

It'd be nice if active_admin would show the unserialized content and then just save it without going through serialization.

**Comment by railsfactory-bhaskararao** [comment]
I did not get how to work with https://github.com/justinfrench/formtastic/blob/master/README.md custom & modified input.

Can some one give me an example.
My serialized input is 

 f.object.prices
=> {:single=>
  {:namer=>{:usd=>20, :inr=>1200},
   :family=>{:usd=>30, :inr=>1800},
   :instamojo_base_link=>"https://www.instamojo.com/Epaminond/pay-for-a-contest",
   :instamojo_competition_id_field_name=>"Field_70261"},
 :twins=>
  {:namer=>{:usd=>40, :inr=>2400},
   :family=>{:usd=>50, :inr=>3000},
   :instamojo_base_link=>"https://www.instamojo.com/Epaminond/pay-for-a-contest",
   :instamojo_competition_id_field_name=>"Field_70261"},
 :triplets=>
  {:namer=>{:usd=>60, :inr=>3600},
   :family=>{:usd=>70, :inr=>4200},
   :instamojo_base_link=>"https://www.instamojo.com/Epaminond/pay-for-a-contest",
   :instamojo_competition_id_field_name=>"Field_70261"}}

Thanks in advance
