### ISSUE TITLE
Feature Request: Clone a current record

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/activeadmin#972]
I'd love to be able to clone select values from a previous record into a new record. It would be even better if there was a "clone" link included in default_actions so it shows up on the index page for easy access.

Related to: https://github.com/gregbell/active_admin/issues/53

**Comment by moofmayeda** [comment]
I'm using a member_action like @kim3er's (above) and it's rendering the new clone's form just fine. But when I try to submit the form, I get a 404 routing error saying that the Manage::ProductsController is not found. Any ideas?

**Comment by moofmayeda** [comment]
I figured it out! It was because @product had various associated records that were not being duplicated (thus they were tied to the original record rather than creating new objects and associations).

**Comment by kim3er** [comment]
This is how I tackled associated records, if it's of any use.

admin/product.rb
```
  member_action :clone, method: :get do
    n = resource.clone!

    redirect_to edit_admin_product_path( n )
  end
```

models/product.rb
```
  def clone!
    r = self.dup
    r.name = "#{self.name} #{DateTime.now}"
    r.visible = false

    r.save!

    [ :features, :media_items, :stock_items ].each do |c|
      self.send( c ).each do |child|
        n = child.dup
        n.product_id = r.id

        n.save!
      end
    end

    return r
  end
```

In the code above, the date is appended to the duplicated product and is hidden by default. The `Product` model is associated with three other models using `has_many`, all of which are duplicated as well.

**Comment by thuhuongly** [comment]
For me, I use deep clone for association models:

`  member_action :clone, method: :get do
    product = Product.find(params[:id])
    @product = product.deep_clone include: [:features, :media_items, :stock_items]
    render :new, layout: false
  end

  action_item :only => :show do
    link_to("Clone", clone_admin_product_path(id: product.id))
  end`

**Comment by zorab47** [comment]
@thuhuongly if you don't mind adding another dependency, I have a gem to extend ActiveAdmin with duplicate functionality. It uses the [Amoeba](https://github.com/rocksolidwebdesign/amoeba) gem to facilitate deep cloning of AR models.
